name: murojaah_web
description: A Very Good Project created by Very Good CLI.
version: 0.1.2+1
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  animations: ^2.0.7
  auto_route: ^6.0.0+1
  bloc: ^8.1.1
  cloud_firestore: ^4.4.5
  cloud_firestore_odm: ^1.0.0-dev.52
  confetti: ^0.7.0
  cross_file: ^0.3.3+4
  equatable: ^2.0.5
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_storage: ^11.0.16
  firebase_ui_auth: ^1.1.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  injectable: ^2.1.0
  ionicons: ^0.2.2
  json_annotation: ^4.8.0
  just_audio: ^0.9.31
  loading_animation_widget: ^1.2.0+4
  pwa_update_listener: ^0.1.0
  record: ^4.4.4
  siri_wave: ^0.3.0
  uuid: ^3.0.7

dev_dependencies:
  auto_route_generator: ^6.0.0
  build_runner: ^2.3.3
  build_web_compilers: ^4.0.2
  cloud_firestore_odm_generator: ^1.0.0-dev.52
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1
  very_good_analysis: ^4.0.0

dependency_overrides:
  intl: ^0.18.0

flutter:
  uses-material-design: true
  generate: true
