// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah37 = [
	Ayah(
		ayahId: 3789,
		ayahText: 'وَالصّٰۤفّٰتِ صَفًّاۙ',
		ayahNumber: 1,
		translationId: 'Demi (rombongan malaikat) yang berbaris bersaf-saf,',
	),
	Ayah(
		ayahId: 3790,
		ayahText: 'فَالزّٰجِرٰتِ زَجْرًاۙ',
		ayahNumber: 2,
		translationId: 'demi (rombongan) yang mencegah dengan sungguh-sungguh,      ',
	),
	Ayah(
		ayahId: 3791,
		ayahText: 'فَالتّٰلِيٰتِ ذِكْرًاۙ',
		ayahNumber: 3,
		translationId: 'demi (rombongan) yang membacakan peringatan,',
	),
	Ayah(
		ayahId: 3792,
		ayahText: 'اِنَّ اِلٰهَكُمْ لَوَاحِدٌۗ ',
		ayahNumber: 4,
		translationId: 'sungguh, Tuhanmu benar-benar Esa.',
	),
	Ayah(
		ayahId: 3793,
		ayahText: 'رَبُّ السَّمٰوٰتِ وَالْاَرْضِ وَمَا بَيْنَهُمَا وَرَبُّ الْمَشَارِقِۗ ',
		ayahNumber: 5,
		translationId: 'Tuhan langit dan bumi dan apa yang berada di antara keduanya dan Tuhan tempat-tempat terbitnya matahari.',
	),
	Ayah(
		ayahId: 3794,
		ayahText: 'اِنَّا زَيَّنَّا السَّمَاۤءَ الدُّنْيَا بِزِيْنَةِ ِۨالْكَوَاكِبِۙ',
		ayahNumber: 6,
		translationId: 'Sesungguhnya Kami telah menghias langit dunia (yang terdekat), dengan hiasan bintang-bintang.',
	),
	Ayah(
		ayahId: 3795,
		ayahText: 'وَحِفْظًا مِّنْ كُلِّ شَيْطٰنٍ مَّارِدٍۚ ',
		ayahNumber: 7,
		translationId: 'Dan (Kami) telah menjaganya dari setiap setan yang durhaka,',
	),
	Ayah(
		ayahId: 3796,
		ayahText: 'لَا يَسَّمَّعُوْنَ اِلَى الْمَلَاِ الْاَعْلٰى وَيُقْذَفُوْنَ مِنْ كُلِّ جَانِبٍۖ ',
		ayahNumber: 8,
		translationId: 'mereka (setan-setan itu) tidak dapat mendengar (pembicaraan) para malaikat dan mereka dilempari dari segala penjuru,',
	),
	Ayah(
		ayahId: 3797,
		ayahText: 'دُحُوْرًا وَّلَهُمْ عَذَابٌ وَّاصِبٌ ',
		ayahNumber: 9,
		translationId: 'untuk mengusir mereka dan mereka akan mendapat azab yang kekal,',
	),
	Ayah(
		ayahId: 3798,
		ayahText: 'اِلَّا مَنْ خَطِفَ الْخَطْفَةَ فَاَتْبَعَهٗ شِهَابٌ ثَاقِبٌ ',
		ayahNumber: 10,
		translationId: 'kecuali (setan) yang mencuri (pembicaraan); maka ia dikejar oleh bintang yang menyala.',
	),
	Ayah(
		ayahId: 3799,
		ayahText: 'فَاسْتَفْتِهِمْ اَهُمْ اَشَدُّ خَلْقًا اَمْ مَّنْ خَلَقْنَا ۗاِنَّا خَلَقْنٰهُمْ مِّنْ طِيْنٍ لَّازِبٍ ',
		ayahNumber: 11,
		translationId: 'Maka tanyakanlah kepada mereka (musyrik Mekah), “Apakah penciptaan mereka yang lebih sulit ataukah apa yang telah Kami ciptakan itu?” Sesungguhnya Kami telah menciptakan mereka dari tanah liat.',
	),
	Ayah(
		ayahId: 3800,
		ayahText: 'بَلْ عَجِبْتَ وَيَسْخَرُوْنَ ۖ ',
		ayahNumber: 12,
		translationId: 'Bahkan engkau (Muhammad) menjadi heran (terhadap keingkaran mereka) dan mereka menghinakan (engkau).',
	),
	Ayah(
		ayahId: 3801,
		ayahText: 'وَاِذَا ذُكِّرُوْا لَا يَذْكُرُوْنَ ۖ ',
		ayahNumber: 13,
		translationId: 'Dan apabila mereka diberi peringatan, mereka tidak mengindahkannya.',
	),
	Ayah(
		ayahId: 3802,
		ayahText: 'وَاِذَا رَاَوْا اٰيَةً يَّسْتَسْخِرُوْنَۖ ',
		ayahNumber: 14,
		translationId: 'Dan apabila mereka melihat suatu tanda (kebesaran) Allah, mereka memperolok-olokkan.',
	),
	Ayah(
		ayahId: 3803,
		ayahText: 'وَقَالُوْٓا اِنْ هٰذَآ اِلَّا سِحْرٌ مُّبِيْنٌ ۚ ',
		ayahNumber: 15,
		translationId: 'Dan mereka berkata, “Ini tidak lain hanyalah sihir yang nyata.',
	),
	Ayah(
		ayahId: 3804,
		ayahText: 'ءَاِذَا مِتْنَا وَكُنَّا تُرَابًا وَّعِظَامًا ءَاِنَّا لَمَبْعُوْثُوْنَۙ',
		ayahNumber: 16,
		translationId: 'Apabila kami telah mati dan telah menjadi tanah dan tulang-belulang, apakah benar kami akan dibangkitkan (kembali)?',
	),
	Ayah(
		ayahId: 3805,
		ayahText: 'اَوَاٰبَاۤؤُنَا الْاَوَّلُوْنَۗ ',
		ayahNumber: 17,
		translationId: 'dan apakah nenek moyang kami yang telah terdahulu (akan dibangkitkan pula)?”',
	),
	Ayah(
		ayahId: 3806,
		ayahText: 'قُلْ نَعَمْ وَاَنْتُمْ دَاخِرُوْنَۚ ',
		ayahNumber: 18,
		translationId: 'Katakanlah (Muhammad), “Ya, dan kamu akan terhina.”',
	),
	Ayah(
		ayahId: 3807,
		ayahText: 'فَاِنَّمَا هِيَ زَجْرَةٌ وَّاحِدَةٌ فَاِذَا هُمْ يَنْظُرُوْنَ ',
		ayahNumber: 19,
		translationId: 'Maka sesungguhnya kebangkitan itu hanya dengan satu teriakan saja; maka seketika itu mereka melihatnya.',
	),
	Ayah(
		ayahId: 3808,
		ayahText: 'وَقَالُوْا يٰوَيْلَنَا هٰذَا يَوْمُ الدِّيْنِ ',
		ayahNumber: 20,
		translationId: 'Dan mereka berkata, “Alangkah celaka kami! (Kiranya) inilah hari pembalasan itu.”',
	),
	Ayah(
		ayahId: 3809,
		ayahText: 'هٰذَا يَوْمُ الْفَصْلِ الَّذِيْ كُنْتُمْ بِهٖ تُكَذِّبُوْنَ ࣖ',
		ayahNumber: 21,
		translationId: 'Inilah hari keputusan yang dahulu kamu dustakan.',
	),
	Ayah(
		ayahId: 3810,
		ayahText: 'اُحْشُرُوا الَّذِيْنَ ظَلَمُوْا وَاَزْوَاجَهُمْ وَمَا كَانُوْا يَعْبُدُوْنَ ۙ',
		ayahNumber: 22,
		translationId: '(Diperintahkan kepada malaikat), “Kumpulkanlah orang-orang yang zalim beserta teman sejawat mereka dan apa yang dahulu mereka sembah,',
	),
	Ayah(
		ayahId: 3811,
		ayahText: 'مِنْ دُوْنِ اللّٰهِ فَاهْدُوْهُمْ اِلٰى صِرَاطِ الْجَحِيْمِ ',
		ayahNumber: 23,
		translationId: 'selain Allah, lalu tunjukkanlah kepada mereka jalan ke neraka.',
	),
	Ayah(
		ayahId: 3812,
		ayahText: 'وَقِفُوْهُمْ اِنَّهُمْ مَّسْـُٔوْلُوْنَ ۙ',
		ayahNumber: 24,
		translationId: 'Tahanlah mereka (di tempat perhentian), sesungguhnya mereka akan ditanya,',
	),
	Ayah(
		ayahId: 3813,
		ayahText: 'مَا لَكُمْ لَا تَنَاصَرُوْنَ ',
		ayahNumber: 25,
		translationId: '”Mengapa kamu tidak tolong-menolong?”',
	),
	Ayah(
		ayahId: 3814,
		ayahText: 'بَلْ هُمُ الْيَوْمَ مُسْتَسْلِمُوْنَ',
		ayahNumber: 26,
		translationId: 'Bahkan mereka pada hari itu menyerah (kepada keputusan Allah).',
	),
	Ayah(
		ayahId: 3815,
		ayahText: 'وَاَقْبَلَ بَعْضُهُمْ عَلٰى بَعْضٍ يَّتَسَاۤءَلُوْنَ ',
		ayahNumber: 27,
		translationId: 'Dan sebagian mereka menghadap kepada sebagian yang lain saling berbantah-bantahan.',
	),
	Ayah(
		ayahId: 3816,
		ayahText: 'قَالُوْٓا اِنَّكُمْ كُنْتُمْ تَأْتُوْنَنَا عَنِ الْيَمِيْنِ ',
		ayahNumber: 28,
		translationId: 'Sesungguhnya (pengikut-pengikut) mereka berkata (kepada pemimpin-pemimpin mereka), “Kamulah yang dahulu datang kepada kami dari kanan.”',
	),
	Ayah(
		ayahId: 3817,
		ayahText: 'قَالُوْا بَلْ لَّمْ تَكُوْنُوْا مُؤْمِنِيْنَۚ ',
		ayahNumber: 29,
		translationId: '(Pemimpin-pemimpin) mereka menjawab, “(Tidak), bahkan kamulah yang tidak (mau) menjadi orang mukmin,',
	),
	Ayah(
		ayahId: 3818,
		ayahText: 'وَمَا كَانَ لَنَا عَلَيْكُمْ مِّنْ سُلْطٰنٍۚ بَلْ كُنْتُمْ قَوْمًا طٰغِيْنَ ',
		ayahNumber: 30,
		translationId: 'sedangkan kami tidak berkuasa terhadapmu, bahkan kamu menjadi kaum yang melampaui batas.',
	),
	Ayah(
		ayahId: 3819,
		ayahText: 'فَحَقَّ عَلَيْنَا قَوْلُ رَبِّنَآ  ۖاِنَّا لَذَاۤىِٕقُوْنَ ',
		ayahNumber: 31,
		translationId: 'Maka pantas putusan (azab) Tuhan menimpa kita; pasti kita akan merasakan (azab itu).',
	),
	Ayah(
		ayahId: 3820,
		ayahText: 'فَاَغْوَيْنٰكُمْ اِنَّا كُنَّا غٰوِيْنَ ',
		ayahNumber: 32,
		translationId: 'Maka kami telah menyesatkan kamu, sesungguhnya kami sendiri, orang-orang yang sesat.”',
	),
	Ayah(
		ayahId: 3821,
		ayahText: 'فَاِنَّهُمْ يَوْمَىِٕذٍ فِى الْعَذَابِ مُشْتَرِكُوْنَ',
		ayahNumber: 33,
		translationId: 'Maka sesungguhnya mereka pada hari itu bersama-sama merasakan azab.',
	),
	Ayah(
		ayahId: 3822,
		ayahText: 'اِنَّا كَذٰلِكَ نَفْعَلُ بِالْمُجْرِمِيْنَ',
		ayahNumber: 34,
		translationId: 'Sungguh, demikianlah Kami memperlakukan terhadap orang-orang yang berbuat dosa.',
	),
	Ayah(
		ayahId: 3823,
		ayahText: 'اِنَّهُمْ كَانُوْٓا اِذَا قِيْلَ لَهُمْ لَآ اِلٰهَ اِلَّا اللّٰهُ يَسْتَكْبِرُوْنَ ۙ',
		ayahNumber: 35,
		translationId: 'Sungguh, dahulu apabila dikatakan kepada mereka, “La ilaha illallah” (Tidak ada tuhan selain Allah), mereka menyombongkan diri,',
	),
	Ayah(
		ayahId: 3824,
		ayahText: 'وَيَقُوْلُوْنَ اَىِٕنَّا لَتَارِكُوْٓا اٰلِهَتِنَا لِشَاعِرٍ مَّجْنُوْنٍ ۗ ',
		ayahNumber: 36,
		translationId: 'dan mereka berkata, “Apakah kami harus meninggalkan sesembahan kami karena seorang penyair gila?”',
	),
	Ayah(
		ayahId: 3825,
		ayahText: 'بَلْ جَاۤءَ بِالْحَقِّ وَصَدَّقَ الْمُرْسَلِيْنَ',
		ayahNumber: 37,
		translationId: 'Padahal dia (Muhammad) datang dengan membawa kebenaran dan membenarkan rasul-rasul (sebelumnya).',
	),
	Ayah(
		ayahId: 3826,
		ayahText: 'اِنَّكُمْ لَذَاۤىِٕقُوا الْعَذَابِ الْاَلِيْمِ ۚ ',
		ayahNumber: 38,
		translationId: 'Sungguh, kamu pasti akan merasakan azab yang pedih.',
	),
	Ayah(
		ayahId: 3827,
		ayahText: 'وَمَا تُجْزَوْنَ اِلَّا مَا كُنْتُمْ تَعْمَلُوْنَۙ',
		ayahNumber: 39,
		translationId: 'Dan kamu tidak diberi balasan melainkan terhadap apa yang telah kamu kerjakan,',
	),
	Ayah(
		ayahId: 3828,
		ayahText: 'اِلَّا عِبَادَ اللّٰهِ الْمُخْلَصِيْنَ ',
		ayahNumber: 40,
		translationId: 'tetapi hamba-hamba Allah yang dibersihkan (dari dosa),',
	),
	Ayah(
		ayahId: 3829,
		ayahText: 'اُولٰۤىِٕكَ لَهُمْ رِزْقٌ مَّعْلُوْمٌۙ',
		ayahNumber: 41,
		translationId: 'mereka itu memperoleh rezeki yang sudah ditentukan,',
	),
	Ayah(
		ayahId: 3830,
		ayahText: 'فَوَاكِهُ ۚوَهُمْ مُّكْرَمُوْنَۙ',
		ayahNumber: 42,
		translationId: '(yaitu) buah-buahan. Dan mereka orang yang dimuliakan,',
	),
	Ayah(
		ayahId: 3831,
		ayahText: 'فِيْ جَنّٰتِ النَّعِيْمِۙ',
		ayahNumber: 43,
		translationId: 'di dalam surga-surga yang penuh kenikmatan,',
	),
	Ayah(
		ayahId: 3832,
		ayahText: 'عَلٰى سُرُرٍ مُّتَقٰبِلِيْنَ',
		ayahNumber: 44,
		translationId: '(mereka duduk) berhadap-hadapan di atas dipan-dipan.',
	),
	Ayah(
		ayahId: 3833,
		ayahText: 'يُطَافُ عَلَيْهِمْ بِكَأْسٍ مِّنْ مَّعِيْنٍۢ ۙ',
		ayahNumber: 45,
		translationId: 'Kepada mereka diedarkan gelas (yang berisi air) dari mata air (surga),',
	),
	Ayah(
		ayahId: 3834,
		ayahText: 'بَيْضَاۤءَ لَذَّةٍ لِّلشّٰرِبِيْنَۚ ',
		ayahNumber: 46,
		translationId: '(warnanya) putih bersih, sedap rasanya bagi orang-orang yang minum.',
	),
	Ayah(
		ayahId: 3835,
		ayahText: 'لَا فِيْهَا غَوْلٌ وَّلَا هُمْ عَنْهَا يُنْزَفُوْنَ',
		ayahNumber: 47,
		translationId: 'Tidak ada di dalamnya (unsur) yang memabukkan dan mereka tidak mabuk karenanya.',
	),
	Ayah(
		ayahId: 3836,
		ayahText: 'وَعِنْدَهُمْ قٰصِرٰتُ الطَّرْفِ عِيْنٌ ۙ',
		ayahNumber: 48,
		translationId: 'Dan di sisi mereka ada (bidadari-bidadari) yang bermata indah, dan membatasi pandangannya,',
	),
	Ayah(
		ayahId: 3837,
		ayahText: 'كَاَنَّهُنَّ بَيْضٌ مَّكْنُوْنٌ',
		ayahNumber: 49,
		translationId: 'seakan-akan mereka adalah telur yang tersimpan dengan baik.',
	),
	Ayah(
		ayahId: 3838,
		ayahText: 'فَاَقْبَلَ بَعْضُهُمْ عَلٰى بَعْضٍ يَّتَسَاۤءَلُوْنَ',
		ayahNumber: 50,
		translationId: 'Lalu mereka berhadap-hadapan satu sama lain sambil bercakap-cakap.',
	),
	Ayah(
		ayahId: 3839,
		ayahText: 'قَالَ قَاۤىِٕلٌ مِّنْهُمْ اِنِّيْ كَانَ لِيْ قَرِيْنٌۙ',
		ayahNumber: 51,
		translationId: 'Berkatalah salah seorang di antara mereka, “Sesungguhnya aku dahulu (di dunia) pernah mempunyai seorang teman,',
	),
	Ayah(
		ayahId: 3840,
		ayahText: 'يَّقُوْلُ اَىِٕنَّكَ لَمِنَ الْمُصَدِّقِيْنَ',
		ayahNumber: 52,
		translationId: 'yang berkata, “Apakah sesungguhnya kamu termasuk orang-orang yang membenarkan (hari berbangkit)?',
	),
	Ayah(
		ayahId: 3841,
		ayahText: 'ءَاِذَا مِتْنَا وَكُنَّا تُرَابًا وَّعِظَامًا ءَاِنَّا لَمَدِيْنُوْنَ',
		ayahNumber: 53,
		translationId: 'Apabila kita telah mati dan telah menjadi tanah dan tulang-belulang, apakah kita benar-benar (akan dibangkitkan) untuk diberi pembalasan?”',
	),
	Ayah(
		ayahId: 3842,
		ayahText: 'قَالَ هَلْ اَنْتُمْ مُّطَّلِعُوْنَ',
		ayahNumber: 54,
		translationId: 'Dia berkata, “Maukah kamu meninjau (temanku itu)?”',
	),
	Ayah(
		ayahId: 3843,
		ayahText: 'فَاطَّلَعَ فَرَاٰهُ فِيْ سَوَاۤءِ الْجَحِيْمِ',
		ayahNumber: 55,
		translationId: 'Maka dia meninjaunya, lalu dia melihat (teman)nya itu di tengah-tengah neraka yang menyala-nyala.',
	),
	Ayah(
		ayahId: 3844,
		ayahText: 'قَالَ تَاللّٰهِ اِنْ كِدْتَّ لَتُرْدِيْنِ ۙ',
		ayahNumber: 56,
		translationId: 'Dia berkata, “Demi Allah, engkau hampir saja mencelakakanku,',
	),
	Ayah(
		ayahId: 3845,
		ayahText: 'وَلَوْلَا نِعْمَةُ رَبِّيْ لَكُنْتُ مِنَ الْمُحْضَرِيْنَ',
		ayahNumber: 57,
		translationId: 'dan sekiranya bukan karena nikmat Tuhanku pastilah aku termasuk orang-orang yang diseret (ke neraka).”',
	),
	Ayah(
		ayahId: 3846,
		ayahText: 'اَفَمَا نَحْنُ بِمَيِّتِيْنَۙ',
		ayahNumber: 58,
		translationId: 'Maka apakah kita tidak akan mati?',
	),
	Ayah(
		ayahId: 3847,
		ayahText: 'اِلَّا مَوْتَتَنَا الْاُوْلٰى وَمَا نَحْنُ بِمُعَذَّبِيْنَ',
		ayahNumber: 59,
		translationId: 'Kecuali kematian kita yang pertama saja (di dunia), dan kita tidak akan diazab (di akhirat ini)?”',
	),
	Ayah(
		ayahId: 3848,
		ayahText: 'اِنَّ هٰذَا لَهُوَ الْفَوْزُ الْعَظِيْمُ',
		ayahNumber: 60,
		translationId: 'Sungguh, ini benar-benar kemenangan yang agung.',
	),
	Ayah(
		ayahId: 3849,
		ayahText: 'لِمِثْلِ هٰذَا فَلْيَعْمَلِ الْعٰمِلُوْنَ',
		ayahNumber: 61,
		translationId: 'Untuk (kemenangan) serupa ini, hendaklah beramal orang-orang yang mampu beramal.',
	),
	Ayah(
		ayahId: 3850,
		ayahText: 'اَذٰلِكَ خَيْرٌ نُّزُلًا اَمْ شَجَرَةُ الزَّقُّوْمِ',
		ayahNumber: 62,
		translationId: 'Apakah (makanan surga) itu hidangan yang lebih baik ataukah pohon zaqqum.',
	),
	Ayah(
		ayahId: 3851,
		ayahText: 'اِنَّا جَعَلْنٰهَا فِتْنَةً لِّلظّٰلِمِيْنَ',
		ayahNumber: 63,
		translationId: 'Sungguh, Kami menjadikannya (pohon zaqqum itu) sebagai azab bagi orang-orang zalim.',
	),
	Ayah(
		ayahId: 3852,
		ayahText: 'اِنَّهَا شَجَرَةٌ تَخْرُجُ فِيْٓ اَصْلِ الْجَحِيْمِۙ',
		ayahNumber: 64,
		translationId: 'Sungguh, itu adalah pohon yang keluar dari dasar neraka Jahim,',
	),
	Ayah(
		ayahId: 3853,
		ayahText: 'طَلْعُهَا كَاَنَّهٗ رُءُوْسُ الشَّيٰطِيْنِ',
		ayahNumber: 65,
		translationId: 'Mayangnya seperti kepala-kepala setan.',
	),
	Ayah(
		ayahId: 3854,
		ayahText: 'فَاِنَّهُمْ لَاٰكِلُوْنَ مِنْهَا فَمَالِـُٔوْنَ مِنْهَا الْبُطُوْنَۗ ',
		ayahNumber: 66,
		translationId: 'Maka sungguh, mereka benar-benar memakan sebagian darinya (buah pohon itu), dan mereka memenuhi perutnya dengan buahnya (zaqqum).',
	),
	Ayah(
		ayahId: 3855,
		ayahText: 'ثُمَّ اِنَّ لَهُمْ عَلَيْهَا لَشَوْبًا مِّنْ حَمِيْمٍۚ ',
		ayahNumber: 67,
		translationId: 'Kemudian sungguh, setelah makan (buah zaqqum) mereka mendapat minuman yang dicampur dengan air yang sangat panas.',
	),
	Ayah(
		ayahId: 3856,
		ayahText: 'ثُمَّ اِنَّ مَرْجِعَهُمْ لَاِلَى الْجَحِيْمِ',
		ayahNumber: 68,
		translationId: 'Kemudian pasti tempat kembali mereka ke neraka Jahim.',
	),
	Ayah(
		ayahId: 3857,
		ayahText: 'اِنَّهُمْ اَلْفَوْا اٰبَاۤءَهُمْ ضَاۤلِّيْنَۙ',
		ayahNumber: 69,
		translationId: 'Sesungguhnya mereka mendapati nenek moyang mereka dalam keadaan sesat, ',
	),
	Ayah(
		ayahId: 3858,
		ayahText: 'فَهُمْ عَلٰٓى اٰثٰرِهِمْ يُهْرَعُوْنَ',
		ayahNumber: 70,
		translationId: 'lalu mereka tergesa-gesa mengikuti jejak (nenek moyang) mereka.',
	),
	Ayah(
		ayahId: 3859,
		ayahText: 'وَلَقَدْ ضَلَّ قَبْلَهُمْ اَكْثَرُ الْاَوَّلِيْنَۙ',
		ayahNumber: 71,
		translationId: 'Dan sungguh, sebelum mereka (Suku Quraisy), telah sesat sebagian besar dari orang-orang yang dahulu,',
	),
	Ayah(
		ayahId: 3860,
		ayahText: 'وَلَقَدْ اَرْسَلْنَا فِيْهِمْ مُّنْذِرِيْنَ',
		ayahNumber: 72,
		translationId: 'dan sungguh, Kami telah mengutus (rasul) pemberi peringatan di kalangan mereka.',
	),
	Ayah(
		ayahId: 3861,
		ayahText: 'فَانْظُرْ كَيْفَ كَانَ عَاقِبَةُ الْمُنْذَرِيْنَۙ',
		ayahNumber: 73,
		translationId: 'Maka perhatikanlah bagaimana kesudahan orang-orang yang diberi peringatan itu,',
	),
	Ayah(
		ayahId: 3862,
		ayahText: 'اِلَّا عِبَادَ اللّٰهِ الْمُخْلَصِيْنَ ࣖ ',
		ayahNumber: 74,
		translationId: 'kecuali hamba-hamba Allah yang disucikan (dari dosa).',
	),
	Ayah(
		ayahId: 3863,
		ayahText: 'وَلَقَدْ نَادٰىنَا نُوْحٌ فَلَنِعْمَ الْمُجِيْبُوْنَۖ ',
		ayahNumber: 75,
		translationId: 'Dan sungguh, Nuh telah berdoa kepada Kami, maka sungguh, Kamilah sebaik-baik yang memperkenankan doa.',
	),
	Ayah(
		ayahId: 3864,
		ayahText: 'وَنَجَّيْنٰهُ وَاَهْلَهٗ مِنَ الْكَرْبِ الْعَظِيْمِۖ ',
		ayahNumber: 76,
		translationId: 'Kami telah menyelamatkan dia dan pengikutnya dari bencana yang besar.',
	),
	Ayah(
		ayahId: 3865,
		ayahText: 'وَجَعَلْنَا ذُرِّيَّتَهٗ هُمُ الْبٰقِيْنَ',
		ayahNumber: 77,
		translationId: 'Dan Kami jadikan anak cucunya orang-orang yang melanjutkan keturunan.',
	),
	Ayah(
		ayahId: 3866,
		ayahText: 'وَتَرَكْنَا عَلَيْهِ فِى الْاٰخِرِيْنَ ۖ ',
		ayahNumber: 78,
		translationId: 'Dan Kami abadikan untuk Nuh (pujian) di kalangan orang-orang yang datang kemudian;',
	),
	Ayah(
		ayahId: 3867,
		ayahText: 'سَلٰمٌ عَلٰى نُوْحٍ فِى الْعٰلَمِيْنَ',
		ayahNumber: 79,
		translationId: '”Kesejahteraan (Kami limpahkan) atas Nuh di seluruh alam.”',
	),
	Ayah(
		ayahId: 3868,
		ayahText: 'اِنَّا كَذٰلِكَ نَجْزِى الْمُحْسِنِيْنَ',
		ayahNumber: 80,
		translationId: 'Sungguh, demikianlah Kami memberi balasan kepada orang-orang yang berbuat baik.',
	),
	Ayah(
		ayahId: 3869,
		ayahText: 'اِنَّهٗ مِنْ عِبَادِنَا الْمُؤْمِنِيْنَ',
		ayahNumber: 81,
		translationId: 'Sungguh, dia termasuk di antara hamba-hamba Kami yang beriman.',
	),
	Ayah(
		ayahId: 3870,
		ayahText: 'ثُمَّ اَغْرَقْنَا الْاٰخَرِيْنَ',
		ayahNumber: 82,
		translationId: 'Kemudian Kami tenggelamkan yang lain.',
	),
	Ayah(
		ayahId: 3871,
		ayahText: 'وَاِنَّ مِنْ شِيْعَتِهٖ لَاِبْرٰهِيْمَ ۘ ',
		ayahNumber: 83,
		translationId: 'Dan sungguh, Ibrahim termasuk golongannya (Nuh).',
	),
	Ayah(
		ayahId: 3872,
		ayahText: 'اِذْ جَاۤءَ رَبَّهٗ بِقَلْبٍ سَلِيْمٍۙ',
		ayahNumber: 84,
		translationId: '(Ingatlah) ketika dia datang kepada Tuhannya dengan hati yang suci,',
	),
	Ayah(
		ayahId: 3873,
		ayahText: 'اِذْ قَالَ لِاَبِيْهِ وَقَوْمِهٖ مَاذَا تَعْبُدُوْنَ ۚ ',
		ayahNumber: 85,
		translationId: '(ingatlah) ketika dia berkata kepada ayahnya dan kaumnya, “Apakah yang kamu sembah itu?',
	),
	Ayah(
		ayahId: 3874,
		ayahText: 'اَىِٕفْكًا اٰلِهَةً دُوْنَ اللّٰهِ تُرِيْدُوْنَۗ ',
		ayahNumber: 86,
		translationId: 'Apakah kamu menghendaki kebohongan dengan sesembahan selain Allah itu?',
	),
	Ayah(
		ayahId: 3875,
		ayahText: 'فَمَا ظَنُّكُمْ بِرَبِّ الْعٰلَمِيْنَ',
		ayahNumber: 87,
		translationId: 'Maka bagaimana anggapanmu terhadap Tuhan seluruh alam?”',
	),
	Ayah(
		ayahId: 3876,
		ayahText: 'فَنَظَرَ نَظْرَةً فِى النُّجُوْمِۙ',
		ayahNumber: 88,
		translationId: 'Lalu dia memandang sekilas ke bintang-bintang,',
	),
	Ayah(
		ayahId: 3877,
		ayahText: 'فَقَالَ اِنِّيْ سَقِيْمٌ',
		ayahNumber: 89,
		translationId: 'kemudian dia (Ibrahim) berkata, “Sesungguhnya aku sakit.”',
	),
	Ayah(
		ayahId: 3878,
		ayahText: 'فَتَوَلَّوْا عَنْهُ مُدْبِرِيْنَ',
		ayahNumber: 90,
		translationId: 'Lalu mereka berpaling dari dia dan pergi meninggalkannya.',
	),
	Ayah(
		ayahId: 3879,
		ayahText: 'فَرَاغَ اِلٰٓى اٰلِهَتِهِمْ فَقَالَ اَلَا تَأْكُلُوْنَۚ ',
		ayahNumber: 91,
		translationId: 'Kemudian dia (Ibrahim) pergi dengan diam-diam kepada berhala-berhala mereka; lalu dia berkata, “Mengapa kamu tidak makan?',
	),
	Ayah(
		ayahId: 3880,
		ayahText: 'مَا لَكُمْ لَا تَنْطِقُوْنَ',
		ayahNumber: 92,
		translationId: 'Mengapa kamu tidak menjawab?”',
	),
	Ayah(
		ayahId: 3881,
		ayahText: 'فَرَاغَ عَلَيْهِمْ ضَرْبًا ۢبِالْيَمِيْنِ',
		ayahNumber: 93,
		translationId: 'Lalu dihadapinya (berhala-berhala) itu sambil memukulnya dengan tangan kanannya.',
	),
	Ayah(
		ayahId: 3882,
		ayahText: 'فَاَقْبَلُوْٓا اِلَيْهِ يَزِفُّوْنَ',
		ayahNumber: 94,
		translationId: 'Kemudian mereka (kaumnya) datang bergegas kepadanya.',
	),
	Ayah(
		ayahId: 3883,
		ayahText: 'قَالَ اَتَعْبُدُوْنَ مَا تَنْحِتُوْنَۙ',
		ayahNumber: 95,
		translationId: 'Dia (Ibrahim) berkata, “Apakah kamu menyembah patung-patung yang kamu pahat itu?',
	),
	Ayah(
		ayahId: 3884,
		ayahText: 'وَاللّٰهُ خَلَقَكُمْ وَمَا تَعْمَلُوْنَ',
		ayahNumber: 96,
		translationId: 'Padahal Allah-lah yang menciptakan kamu dan apa yang kamu perbuat itu.”',
	),
	Ayah(
		ayahId: 3885,
		ayahText: 'قَالُوا ابْنُوْا لَهٗ بُنْيَانًا فَاَلْقُوْهُ فِى الْجَحِيْمِ',
		ayahNumber: 97,
		translationId: 'Mereka berkata, “Buatlah bangunan (perapian) untuknya (membakar Ibrahim); lalu lemparkan dia ke dalam api yang menyala-nyala itu.”',
	),
	Ayah(
		ayahId: 3886,
		ayahText: 'فَاَرَادُوْا بِهٖ كَيْدًا فَجَعَلْنٰهُمُ الْاَسْفَلِيْنَ',
		ayahNumber: 98,
		translationId: 'Maka mereka bermaksud memperdayainya dengan (membakar)nya, (namun Allah menyelamatkannya), lalu Kami jadikan mereka orang-orang  yang hina.',
	),
	Ayah(
		ayahId: 3887,
		ayahText: 'وَقَالَ اِنِّيْ ذَاهِبٌ اِلٰى رَبِّيْ سَيَهْدِيْنِ',
		ayahNumber: 99,
		translationId: 'Dan dia (Ibrahim) berkata, “Sesungguhnya aku harus pergi (menghadap) kepada Tuhanku, Dia akan memberi petunjuk kepadaku.',
	),
	Ayah(
		ayahId: 3888,
		ayahText: 'رَبِّ هَبْ لِيْ مِنَ الصّٰلِحِيْنَ',
		ayahNumber: 100,
		translationId: 'Ya Tuhanku, anugerahkanlah kepadaku (seorang anak) yang termasuk orang yang saleh.”',
	),
	Ayah(
		ayahId: 3889,
		ayahText: 'فَبَشَّرْنٰهُ بِغُلٰمٍ حَلِيْمٍ',
		ayahNumber: 101,
		translationId: 'Maka Kami beri kabar gembira kepadanya dengan (kelahiran) seorang anak yang sangat sabar (Ismail).',
	),
	Ayah(
		ayahId: 3890,
		ayahText: 'فَلَمَّا بَلَغَ مَعَهُ السَّعْيَ قَالَ يٰبُنَيَّ اِنِّيْٓ اَرٰى فِى الْمَنَامِ اَنِّيْٓ اَذْبَحُكَ فَانْظُرْ مَاذَا تَرٰىۗ قَالَ يٰٓاَبَتِ افْعَلْ مَا تُؤْمَرُۖ سَتَجِدُنِيْٓ اِنْ شَاۤءَ اللّٰهُ مِنَ الصّٰبِرِيْنَ',
		ayahNumber: 102,
		translationId: 'Maka ketika anak itu sampai (pada umur) sanggup berusaha bersamanya, (Ibrahim) berkata, “Wahai anakku! Sesungguhnya aku bermimpi bahwa aku menyembelihmu. Maka pikirkanlah bagaimana pendapatmu!” Dia (Ismail) menjawab, “Wahai ayahku! Lakukanlah apa yang diperintahkan (Allah) kepadamu; insya Allah engkau akan mendapatiku termasuk orang yang sabar.”',
	),
	Ayah(
		ayahId: 3891,
		ayahText: 'فَلَمَّآ اَسْلَمَا وَتَلَّهٗ لِلْجَبِيْنِۚ ',
		ayahNumber: 103,
		translationId: 'Maka ketika keduanya telah berserah diri dan dia (Ibrahim) membaringkan anaknya atas pelipis(nya), (untuk melaksanakan perintah Allah).',
	),
	Ayah(
		ayahId: 3892,
		ayahText: 'وَنَادَيْنٰهُ اَنْ يّٰٓاِبْرٰهِيْمُ ۙ',
		ayahNumber: 104,
		translationId: 'Lalu Kami panggil dia, “Wahai Ibrahim!',
	),
	Ayah(
		ayahId: 3893,
		ayahText: 'قَدْ صَدَّقْتَ الرُّؤْيَا ۚاِنَّا كَذٰلِكَ نَجْزِى الْمُحْسِنِيْنَ',
		ayahNumber: 105,
		translationId: 'sungguh, engkau telah membenarkan mimpi itu.” Sungguh, demikianlah Kami memberi balasan kepada orang-orang yang berbuat baik.',
	),
	Ayah(
		ayahId: 3894,
		ayahText: 'اِنَّ هٰذَا لَهُوَ الْبَلٰۤؤُا الْمُبِيْنُ',
		ayahNumber: 106,
		translationId: 'Sesungguhnya ini benar-benar suatu ujian yang nyata.',
	),
	Ayah(
		ayahId: 3895,
		ayahText: 'وَفَدَيْنٰهُ بِذِبْحٍ عَظِيْمٍ',
		ayahNumber: 107,
		translationId: 'Dan Kami tebus anak itu dengan seekor sembelihan yang besar.',
	),
	Ayah(
		ayahId: 3896,
		ayahText: 'وَتَرَكْنَا عَلَيْهِ فِى الْاٰخِرِيْنَ ۖ ',
		ayahNumber: 108,
		translationId: 'Dan Kami abadikan untuk Ibrahim (pujian) di kalangan orang-orang yang  datang kemudian,',
	),
	Ayah(
		ayahId: 3897,
		ayahText: 'سَلٰمٌ عَلٰٓى اِبْرٰهِيْمَ',
		ayahNumber: 109,
		translationId: '”Selamat sejahtera bagi Ibrahim.”',
	),
	Ayah(
		ayahId: 3898,
		ayahText: 'كَذٰلِكَ نَجْزِى الْمُحْسِنِيْنَ',
		ayahNumber: 110,
		translationId: 'Demikianlah Kami memberi balasan kepada orang-orang yang berbuat baik.',
	),
	Ayah(
		ayahId: 3899,
		ayahText: 'اِنَّهٗ مِنْ عِبَادِنَا الْمُؤْمِنِيْنَ',
		ayahNumber: 111,
		translationId: 'Sungguh, dia termasuk hamba-hamba Kami yang beriman.',
	),
	Ayah(
		ayahId: 3900,
		ayahText: 'وَبَشَّرْنٰهُ بِاِسْحٰقَ نَبِيًّا مِّنَ الصّٰلِحِيْنَ',
		ayahNumber: 112,
		translationId: 'Dan Kami beri dia kabar gembira dengan (kelahiran) Ishak seorang nabi yang termasuk orang-orang yang saleh.',
	),
	Ayah(
		ayahId: 3901,
		ayahText: 'وَبٰرَكْنَا عَلَيْهِ وَعَلٰٓى اِسْحٰقَۗ وَمِنْ ذُرِّيَّتِهِمَا مُحْسِنٌ وَّظَالِمٌ لِّنَفْسِهٖ مُبِيْنٌ ࣖ',
		ayahNumber: 113,
		translationId: 'Dan Kami limpahkan keberkahan kepadanya dan kepada Ishak. Dan di antara keturunan keduanya ada yang berbuat baik dan ada (pula) yang terang-terangan berbuat zalim terhadap dirinya sendiri.',
	),
	Ayah(
		ayahId: 3902,
		ayahText: 'وَلَقَدْ مَنَنَّا عَلٰى مُوْسٰى وَهٰرُوْنَ ۚ ',
		ayahNumber: 114,
		translationId: 'Dan sungguh, Kami telah melimpahkan nikmat kepada Musa dan Harun.',
	),
	Ayah(
		ayahId: 3903,
		ayahText: 'وَنَجَّيْنٰهُمَا وَقَوْمَهُمَا مِنَ الْكَرْبِ الْعَظِيْمِۚ ',
		ayahNumber: 115,
		translationId: 'Dan Kami selamatkan keduanya dan kaumnya dari bencana yang besar,',
	),
	Ayah(
		ayahId: 3904,
		ayahText: 'وَنَصَرْنٰهُمْ فَكَانُوْا هُمُ الْغٰلِبِيْنَۚ ',
		ayahNumber: 116,
		translationId: 'dan Kami tolong mereka, sehingga jadilah mereka orang-orang yang menang.',
	),
	Ayah(
		ayahId: 3905,
		ayahText: 'وَاٰتَيْنٰهُمَا الْكِتٰبَ الْمُسْتَبِيْنَ ۚ ',
		ayahNumber: 117,
		translationId: 'Dan Kami berikan kepada keduanya Kitab yang sangat jelas,',
	),
	Ayah(
		ayahId: 3906,
		ayahText: 'وَهَدَيْنٰهُمَا الصِّرَاطَ الْمُسْتَقِيْمَۚ ',
		ayahNumber: 118,
		translationId: 'dan Kami tunjukkan keduanya jalan yang lurus.',
	),
	Ayah(
		ayahId: 3907,
		ayahText: 'وَتَرَكْنَا عَلَيْهِمَا فِى الْاٰخِرِيْنَ ۖ ',
		ayahNumber: 119,
		translationId: 'Dan Kami abadikan untuk keduanya (pujian) di kalangan orang-orang yang datang kemudian,',
	),
	Ayah(
		ayahId: 3908,
		ayahText: 'سَلٰمٌ عَلٰى مُوْسٰى وَهٰرُوْنَ',
		ayahNumber: 120,
		translationId: '”Selamat sejahtera bagi Musa dan Harun.”',
	),
	Ayah(
		ayahId: 3909,
		ayahText: 'اِنَّا كَذٰلِكَ نَجْزِى الْمُحْسِنِيْنَ',
		ayahNumber: 121,
		translationId: 'Demikianlah Kami memberi balasan kepada orang-orang yang berbuat baik.',
	),
	Ayah(
		ayahId: 3910,
		ayahText: 'اِنَّهُمَا مِنْ عِبَادِنَا الْمُؤْمِنِيْنَ',
		ayahNumber: 122,
		translationId: 'Sungguh, keduanya termasuk hamba-hamba Kami yang beriman.',
	),
	Ayah(
		ayahId: 3911,
		ayahText: 'وَاِنَّ اِلْيَاسَ لَمِنَ الْمُرْسَلِيْنَۗ ',
		ayahNumber: 123,
		translationId: 'Dan sungguh, Ilyas benar-benar termasuk salah seorang rasul.',
	),
	Ayah(
		ayahId: 3912,
		ayahText: 'اِذْ قَالَ لِقَوْمِهٖٓ اَلَا تَتَّقُوْنَ',
		ayahNumber: 124,
		translationId: '(Ingatlah) ketika dia berkata kepada kaumnya, “Mengapa kamu tidak bertakwa?',
	),
	Ayah(
		ayahId: 3913,
		ayahText: 'اَتَدْعُوْنَ بَعْلًا وَّتَذَرُوْنَ اَحْسَنَ الْخَالِقِيْنَۙ',
		ayahNumber: 125,
		translationId: 'Patutkah kamu menyembah Ba’l dan kamu tinggalkan (Allah) sebaik-baik pencipta.',
	),
	Ayah(
		ayahId: 3914,
		ayahText: 'اللّٰهَ رَبَّكُمْ وَرَبَّ اٰبَاۤىِٕكُمُ الْاَوَّلِيْنَ',
		ayahNumber: 126,
		translationId: '(Yaitu) Allah Tuhanmu dan Tuhan nenek moyangmu yang terdahulu?”',
	),
	Ayah(
		ayahId: 3915,
		ayahText: 'فَكَذَّبُوْهُ فَاِنَّهُمْ لَمُحْضَرُوْنَۙ',
		ayahNumber: 127,
		translationId: 'Tetapi mereka mendustakannya (Ilyas), maka sungguh, mereka akan diseret (ke neraka),',
	),
	Ayah(
		ayahId: 3916,
		ayahText: 'اِلَّا عِبَادَ اللّٰهِ الْمُخْلَصِيْنَ',
		ayahNumber: 128,
		translationId: 'kecuali hamba-hamba Allah yang disucikan (dari dosa),',
	),
	Ayah(
		ayahId: 3917,
		ayahText: 'وَتَرَكْنَا عَلَيْهِ فِى الْاٰخِرِيْنَ ۙ',
		ayahNumber: 129,
		translationId: 'Dan Kami abadikan untuk Ilyas (pujian) di kalangan orang-orang yang datang kemudian.',
	),
	Ayah(
		ayahId: 3918,
		ayahText: 'سَلٰمٌ عَلٰٓى اِلْ يَاسِيْنَ',
		ayahNumber: 130,
		translationId: '”Selamat sejahtera bagi Ilyas.”',
	),
	Ayah(
		ayahId: 3919,
		ayahText: 'اِنَّا كَذٰلِكَ نَجْزِى الْمُحْسِنِيْنَ',
		ayahNumber: 131,
		translationId: 'Demikianlah Kami memberi balasan kepada orang-orang yang berbuat baik.',
	),
	Ayah(
		ayahId: 3920,
		ayahText: 'اِنَّهٗ مِنْ عِبَادِنَا الْمُؤْمِنِيْنَ',
		ayahNumber: 132,
		translationId: 'Sungguh, dia termasuk hamba-hamba Kami yang beriman.',
	),
	Ayah(
		ayahId: 3921,
		ayahText: 'وَاِنَّ لُوْطًا لَّمِنَ الْمُرْسَلِيْنَۗ ',
		ayahNumber: 133,
		translationId: 'Dan sungguh, Lut benar-benar termasuk salah seorang rasul.',
	),
	Ayah(
		ayahId: 3922,
		ayahText: 'اِذْ نَجَّيْنٰهُ وَاَهْلَهٗٓ اَجْمَعِيْۙنَ',
		ayahNumber: 134,
		translationId: '(Ingatlah) ketika Kami telah menyelamatkan dia dan pengikutnya semua,',
	),
	Ayah(
		ayahId: 3923,
		ayahText: 'اِلَّا عَجُوْزًا فِى الْغٰبِرِيْنَ',
		ayahNumber: 135,
		translationId: 'kecuali seorang perempuan tua (istrinya) bersama-sama orang yang tinggal (di kota).',
	),
	Ayah(
		ayahId: 3924,
		ayahText: 'ثُمَّ دَمَّرْنَا الْاٰخَرِيْنَ',
		ayahNumber: 136,
		translationId: 'Kemudian Kami binasakan orang-orang yang lain.',
	),
	Ayah(
		ayahId: 3925,
		ayahText: 'وَاِنَّكُمْ لَتَمُرُّوْنَ عَلَيْهِمْ مُّصْبِحِيْنَۙ',
		ayahNumber: 137,
		translationId: 'Dan sesungguhnya kamu (penduduk Mekah) benar-benar akan melalui (bekas-bekas) mereka pada waktu pagi,',
	),
	Ayah(
		ayahId: 3926,
		ayahText: 'وَبِالَّيْلِۗ اَفَلَا تَعْقِلُوْنَ ࣖ ',
		ayahNumber: 138,
		translationId: 'dan pada waktu malam. Maka mengapa kamu tidak mengerti?',
	),
	Ayah(
		ayahId: 3927,
		ayahText: 'وَاِنَّ يُوْنُسَ لَمِنَ الْمُرْسَلِيْنَۗ ',
		ayahNumber: 139,
		translationId: 'Dan sungguh, Yunus benar-benar termasuk salah seorang rasul,',
	),
	Ayah(
		ayahId: 3928,
		ayahText: 'اِذْ اَبَقَ اِلَى الْفُلْكِ الْمَشْحُوْنِۙ',
		ayahNumber: 140,
		translationId: '(ingatlah) ketika dia lari, ke kapal yang penuh muatan,',
	),
	Ayah(
		ayahId: 3929,
		ayahText: 'فَسَاهَمَ فَكَانَ مِنَ الْمُدْحَضِيْنَۚ',
		ayahNumber: 141,
		translationId: 'kemudian dia ikut diundi ternyata dia termasuk orang-orang yang kalah (dalam undian).',
	),
	Ayah(
		ayahId: 3930,
		ayahText: 'فَالْتَقَمَهُ الْحُوْتُ وَهُوَ مُلِيْمٌ ',
		ayahNumber: 142,
		translationId: 'Maka dia ditelan oleh ikan besar dalam keadaan tercela.',
	),
	Ayah(
		ayahId: 3931,
		ayahText: 'فَلَوْلَآ اَنَّهٗ كَانَ مِنَ الْمُسَبِّحِيْنَ ۙ',
		ayahNumber: 143,
		translationId: 'Maka sekiranya dia tidak termasuk orang yang banyak berzikir (bertasbih) kepada Allah,',
	),
	Ayah(
		ayahId: 3932,
		ayahText: 'لَلَبِثَ فِيْ بَطْنِهٖٓ اِلٰى يَوْمِ يُبْعَثُوْنَۚ ',
		ayahNumber: 144,
		translationId: 'niscaya dia akan tetap tinggal di perut (ikan itu) sampai hari kebangkitan.',
	),
	Ayah(
		ayahId: 3933,
		ayahText: 'فَنَبَذْنٰهُ بِالْعَرَاۤءِ وَهُوَ سَقِيْمٌ ۚ ',
		ayahNumber: 145,
		translationId: 'Kemudian Kami lemparkan dia ke daratan yang tandus, sedang dia dalam keadaan sakit.',
	),
	Ayah(
		ayahId: 3934,
		ayahText: 'وَاَنْۢبَتْنَا عَلَيْهِ شَجَرَةً مِّنْ يَّقْطِيْنٍۚ ',
		ayahNumber: 146,
		translationId: 'Kemudian untuk dia Kami tumbuhkan sebatang pohon dari jenis labu.',
	),
	Ayah(
		ayahId: 3935,
		ayahText: 'وَاَرْسَلْنٰهُ اِلٰى مِائَةِ اَلْفٍ اَوْ يَزِيْدُوْنَۚ ',
		ayahNumber: 147,
		translationId: 'Dan Kami utus dia kepada seratus ribu (orang) atau lebih,',
	),
	Ayah(
		ayahId: 3936,
		ayahText: 'فَاٰمَنُوْا فَمَتَّعْنٰهُمْ اِلٰى حِيْنٍ',
		ayahNumber: 148,
		translationId: 'sehingga mereka beriman, karena itu Kami anugerahkan kenikmatan hidup kepada mereka hingga waktu tertentu.',
	),
	Ayah(
		ayahId: 3937,
		ayahText: 'فَاسْتَفْتِهِمْ اَلِرَبِّكَ الْبَنَاتُ وَلَهُمُ الْبَنُوْنَۚ ',
		ayahNumber: 149,
		translationId: 'Maka tanyakanlah (Muhammad) kepada mereka (orang-orang kafir Mekah), “Apakah anak-anak perempuan itu untuk Tuhanmu sedangkan untuk mereka anak-anak laki-laki?”',
	),
	Ayah(
		ayahId: 3938,
		ayahText: 'اَمْ خَلَقْنَا الْمَلٰۤىِٕكَةَ اِنَاثًا وَّهُمْ شَاهِدُوْنَ',
		ayahNumber: 150,
		translationId: 'atau apakah Kami menciptakan malaikat-malaikat berupa perempuan sedangkan mereka menyaksikan(nya)?',
	),
	Ayah(
		ayahId: 3939,
		ayahText: 'اَلَآ اِنَّهُمْ مِّنْ اِفْكِهِمْ لَيَقُوْلُوْنَۙ',
		ayahNumber: 151,
		translationId: 'Ingatlah, sesungguhnya di antara kebohongannya mereka benar-benar mengatakan,',
	),
	Ayah(
		ayahId: 3940,
		ayahText: 'وَلَدَ اللّٰهُ ۙوَاِنَّهُمْ لَكٰذِبُوْنَۙ',
		ayahNumber: 152,
		translationId: '”Allah mempunyai anak.” Dan sungguh, mereka benar-benar pendusta,',
	),
	Ayah(
		ayahId: 3941,
		ayahText: 'اَصْطَفَى الْبَنَاتِ عَلَى الْبَنِيْنَۗ ',
		ayahNumber: 153,
		translationId: 'apakah Dia (Allah) memilih anak-anak perempuan daripada anak-anak laki-laki?',
	),
	Ayah(
		ayahId: 3942,
		ayahText: 'مَا لَكُمْۗ  كَيْفَ تَحْكُمُوْنَ',
		ayahNumber: 154,
		translationId: 'Mengapa kamu ini? Bagaimana (caranya) kamu menetapkan?',
	),
	Ayah(
		ayahId: 3943,
		ayahText: 'اَفَلَا تَذَكَّرُوْنَۚ ',
		ayahNumber: 155,
		translationId: 'Maka mengapa kamu tidak memikirkan?',
	),
	Ayah(
		ayahId: 3944,
		ayahText: 'اَمْ لَكُمْ سُلْطٰنٌ مُّبِيْنٌۙ',
		ayahNumber: 156,
		translationId: 'Ataukah kamu mempunyai bukti yang jelas?',
	),
	Ayah(
		ayahId: 3945,
		ayahText: 'فَأْتُوْا بِكِتٰبِكُمْ اِنْ كُنْتُمْ صٰدِقِيْنَ',
		ayahNumber: 157,
		translationId: '(Kalau begitu) maka bawalah kitabmu jika kamu orang yang benar.',
	),
	Ayah(
		ayahId: 3946,
		ayahText: 'وَجَعَلُوْا بَيْنَهٗ وَبَيْنَ الْجِنَّةِ نَسَبًا ۗوَلَقَدْ عَلِمَتِ الْجِنَّةُ اِنَّهُمْ لَمُحْضَرُوْنَۙ',
		ayahNumber: 158,
		translationId: 'Dan mereka mengadakan (hubungan) nasab (keluarga) antara Dia (Allah) dan jin. Dan sungguh, jin telah mengetahui bahwa mereka pasti akan diseret (ke neraka),',
	),
	Ayah(
		ayahId: 3947,
		ayahText: 'سُبْحٰنَ اللّٰهِ عَمَّا يَصِفُوْنَۙ',
		ayahNumber: 159,
		translationId: 'Mahasuci Allah dari apa yang mereka sifatkan,',
	),
	Ayah(
		ayahId: 3948,
		ayahText: 'اِلَّا عِبَادَ اللّٰهِ الْمُخْلَصِيْنَ',
		ayahNumber: 160,
		translationId: 'kecuali hamba-hamba Allah yang disucikan (dari dosa).',
	),
	Ayah(
		ayahId: 3949,
		ayahText: 'فَاِنَّكُمْ وَمَا تَعْبُدُوْنَۙ',
		ayahNumber: 161,
		translationId: 'Maka sesungguhnya kamu dan apa yang kamu sembah itu,',
	),
	Ayah(
		ayahId: 3950,
		ayahText: 'مَآ اَنْتُمْ عَلَيْهِ بِفَاتِنِيْنَۙ',
		ayahNumber: 162,
		translationId: 'tidak akan dapat menyesatkan (seseorang) terhadap Allah,',
	),
	Ayah(
		ayahId: 3951,
		ayahText: 'اِلَّا مَنْ هُوَ صَالِ الْجَحِيْمِ',
		ayahNumber: 163,
		translationId: 'kecuali orang-orang yang akan masuk ke neraka Jahim.',
	),
	Ayah(
		ayahId: 3952,
		ayahText: 'وَمَا مِنَّآ اِلَّا لَهٗ مَقَامٌ مَّعْلُوْمٌۙ',
		ayahNumber: 164,
		translationId: 'Dan tidak satu pun di antara kami (malaikat) melainkan masing-masing mempunyai kedudukan tertentu,',
	),
	Ayah(
		ayahId: 3953,
		ayahText: 'وَاِنَّا لَنَحْنُ الصَّۤافُّوْنَۖ',
		ayahNumber: 165,
		translationId: 'dan sesungguhnya kami selalu teratur dalam barisan (dalam melaksanakan perintah Allah).',
	),
	Ayah(
		ayahId: 3954,
		ayahText: 'وَاِنَّا لَنَحْنُ الْمُسَبِّحُوْنَ',
		ayahNumber: 166,
		translationId: 'Dan sungguh, kami benar-benar terus bertasbih (kepada Allah).',
	),
	Ayah(
		ayahId: 3955,
		ayahText: 'وَاِنْ كَانُوْا لَيَقُوْلُوْنَۙ',
		ayahNumber: 167,
		translationId: 'Dan sesungguhnya mereka (orang kafir Mekah) benar-benar pernah berkata,',
	),
	Ayah(
		ayahId: 3956,
		ayahText: 'لَوْ اَنَّ عِنْدَنَا ذِكْرًا مِّنَ الْاَوَّلِيْنَۙ',
		ayahNumber: 168,
		translationId: '”Sekiranya di sisi kami ada sebuah kitab dari (kitab-kitab yang diturunkan) kepada orang-orang dahulu,',
	),
	Ayah(
		ayahId: 3957,
		ayahText: 'لَكُنَّا عِبَادَ اللّٰهِ الْمُخْلَصِيْنَ',
		ayahNumber: 169,
		translationId: 'tentu kami akan menjadi hamba Allah yang disucikan (dari dosa).”',
	),
	Ayah(
		ayahId: 3958,
		ayahText: 'فَكَفَرُوْا بِهٖۚ فَسَوْفَ يَعْلَمُوْنَ',
		ayahNumber: 170,
		translationId: "Tetapi ternyata mereka mengingkarinya (Al-Qur'an); maka kelak mereka akan mengetahui (akibat keingkarannya itu).",
	),
	Ayah(
		ayahId: 3959,
		ayahText: 'وَلَقَدْ سَبَقَتْ كَلِمَتُنَا لِعِبَادِنَا الْمُرْسَلِيْنَ ۖ',
		ayahNumber: 171,
		translationId: 'Dan sungguh, janji Kami telah tetap bagi hamba-hamba Kami yang menjadi rasul,',
	),
	Ayah(
		ayahId: 3960,
		ayahText: 'اِنَّهُمْ لَهُمُ الْمَنْصُوْرُوْنَۖ',
		ayahNumber: 172,
		translationId: '(yaitu) mereka itu pasti akan mendapat pertolongan.',
	),
	Ayah(
		ayahId: 3961,
		ayahText: 'وَاِنَّ جُنْدَنَا لَهُمُ الْغٰلِبُوْنَ',
		ayahNumber: 173,
		translationId: 'Dan sesungguhnya bala tentara Kami itulah yang pasti menang.',
	),
	Ayah(
		ayahId: 3962,
		ayahText: 'فَتَوَلَّ عَنْهُمْ حَتّٰى حِيْنٍۙ',
		ayahNumber: 174,
		translationId: 'Maka berpalinglah engkau (Muhammad) dari mereka sampai waktu tertentu,',
	),
	Ayah(
		ayahId: 3963,
		ayahText: 'وَّاَبْصِرْهُمْۗ فَسَوْفَ يُبْصِرُوْنَ',
		ayahNumber: 175,
		translationId: 'dan perlihatkanlah kepada mereka, maka kelak mereka akan melihat (azab itu).',
	),
	Ayah(
		ayahId: 3964,
		ayahText: 'اَفَبِعَذَابِنَا يَسْتَعْجِلُوْنَ',
		ayahNumber: 176,
		translationId: 'Maka apakah mereka meminta agar azab Kami disegerakan?',
	),
	Ayah(
		ayahId: 3965,
		ayahText: 'فَاِذَا نَزَلَ بِسَاحَتِهِمْ فَسَاۤءَ صَبَاحُ الْمُنْذَرِيْنَ',
		ayahNumber: 177,
		translationId: 'Maka apabila (siksaan) itu turun di halaman mereka, maka sangat buruklah pagi hari bagi orang-orang yang diperingatkan itu.',
	),
	Ayah(
		ayahId: 3966,
		ayahText: 'وَتَوَلَّ عَنْهُمْ حَتّٰى حِيْنٍۙ',
		ayahNumber: 178,
		translationId: 'Dan berpalinglah engkau dari mereka sampai waktu tertentu. ',
	),
	Ayah(
		ayahId: 3967,
		ayahText: 'وَّاَبْصِرْۗ فَسَوْفَ يُبْصِرُوْنَ',
		ayahNumber: 179,
		translationId: 'Dan perlihatkanlah, maka kelak mereka akan melihat (azab itu).',
	),
	Ayah(
		ayahId: 3968,
		ayahText: 'سُبْحٰنَ رَبِّكَ رَبِّ الْعِزَّةِ عَمَّا يَصِفُوْنَۚ',
		ayahNumber: 180,
		translationId: 'Mahasuci Tuhanmu, Tuhan Yang Mahaperkasa dari sifat yang mereka katakan.',
	),
	Ayah(
		ayahId: 3969,
		ayahText: 'وَسَلٰمٌ عَلَى الْمُرْسَلِيْنَۚ ',
		ayahNumber: 181,
		translationId: 'Dan selamat sejahtera bagi para rasul.',
	),
	Ayah(
		ayahId: 3970,
		ayahText: 'وَالْحَمْدُ لِلّٰهِ رَبِّ الْعٰلَمِيْنَ ࣖ',
		ayahNumber: 182,
		translationId: 'Dan segala puji bagi Allah Tuhan seluruh alam.',
	),
];
