// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah78 = [
	Ayah(
		ayahId: 5673,
		ayahText: 'عَمَّ يَتَسَاۤءَلُوْنَۚ ',
		ayahNumber: 1,
		translationId: 'Tentang apakah mereka saling bertanya-tanya?',
	),
	Ayah(
		ayahId: 5674,
		ayahText: 'عَنِ النَّبَاِ الْعَظِيْمِۙ ',
		ayahNumber: 2,
		translationId: 'Tentang berita yang besar (hari kebangkitan),',
	),
	Ayah(
		ayahId: 5675,
		ayahText: 'الَّذِيْ هُمْ فِيْهِ مُخْتَلِفُوْنَۗ ',
		ayahNumber: 3,
		translationId: 'yang dalam hal itu mereka berselisih.',
	),
	Ayah(
		ayahId: 5676,
		ayahText: 'كَلَّا سَيَعْلَمُوْنَۙ ',
		ayahNumber: 4,
		translationId: 'Tidak! Kelak mereka akan mengetahui,',
	),
	Ayah(
		ayahId: 5677,
		ayahText: 'ثُمَّ كَلَّا سَيَعْلَمُوْنَ',
		ayahNumber: 5,
		translationId: 'sekali lagi tidak! Kelak mereka akan mengetahui. ',
	),
	Ayah(
		ayahId: 5678,
		ayahText: 'اَلَمْ نَجْعَلِ الْاَرْضَ مِهٰدًاۙ',
		ayahNumber: 6,
		translationId: 'Bukankah Kami telah menjadikan bumi sebagai hamparan, ',
	),
	Ayah(
		ayahId: 5679,
		ayahText: 'وَّالْجِبَالَ اَوْتَادًاۖ',
		ayahNumber: 7,
		translationId: 'dan gunung-gunung sebagai pasak?',
	),
	Ayah(
		ayahId: 5680,
		ayahText: 'وَّخَلَقْنٰكُمْ اَزْوَاجًاۙ ',
		ayahNumber: 8,
		translationId: 'Dan Kami menciptakan kamu berpasang-pasangan,',
	),
	Ayah(
		ayahId: 5681,
		ayahText: 'وَّجَعَلْنَا نَوْمَكُمْ سُبَاتًاۙ ',
		ayahNumber: 9,
		translationId: 'dan Kami menjadikan tidurmu untuk istirahat,',
	),
	Ayah(
		ayahId: 5682,
		ayahText: 'وَّجَعَلْنَا الَّيْلَ لِبَاسًاۙ ',
		ayahNumber: 10,
		translationId: 'dan Kami menjadikan malam sebagai pakaian,',
	),
	Ayah(
		ayahId: 5683,
		ayahText: 'وَّجَعَلْنَا النَّهَارَ مَعَاشًاۚ',
		ayahNumber: 11,
		translationId: 'dan Kami menjadikan siang untuk mencari penghidupan,',
	),
	Ayah(
		ayahId: 5684,
		ayahText: 'وَبَنَيْنَا فَوْقَكُمْ سَبْعًا شِدَادًاۙ ',
		ayahNumber: 12,
		translationId: 'dan Kami membangun di atas kamu tujuh (langit) yang kokoh,',
	),
	Ayah(
		ayahId: 5685,
		ayahText: 'وَّجَعَلْنَا سِرَاجًا وَّهَّاجًاۖ',
		ayahNumber: 13,
		translationId: 'dan Kami menjadikan pelita yang terang-benderang (matahari),',
	),
	Ayah(
		ayahId: 5686,
		ayahText: 'وَّاَنْزَلْنَا مِنَ الْمُعْصِرٰتِ مَاۤءً ثَجَّاجًاۙ',
		ayahNumber: 14,
		translationId: 'dan Kami turunkan dari awan, air hujan yang tercurah dengan hebatnya,',
	),
	Ayah(
		ayahId: 5687,
		ayahText: 'لِّنُخْرِجَ بِهٖ حَبًّا وَّنَبَاتًاۙ',
		ayahNumber: 15,
		translationId: 'untuk Kami tumbuhkan dengan air itu biji-bijian dan tanam-tanaman,',
	),
	Ayah(
		ayahId: 5688,
		ayahText: 'وَّجَنّٰتٍ اَلْفَافًاۗ',
		ayahNumber: 16,
		translationId: 'dan kebun-kebun yang rindang.',
	),
	Ayah(
		ayahId: 5689,
		ayahText: 'اِنَّ يَوْمَ الْفَصْلِ كَانَ مِيْقَاتًاۙ',
		ayahNumber: 17,
		translationId: 'Sungguh, hari keputusan adalah suatu waktu yang telah ditetapkan,',
	),
	Ayah(
		ayahId: 5690,
		ayahText: 'يَّوْمَ يُنْفَخُ فِى الصُّوْرِ فَتَأْتُوْنَ اَفْوَاجًاۙ',
		ayahNumber: 18,
		translationId: '(yaitu) pada hari (ketika) sangkakala ditiup, lalu kamu datang berbondong-bondong,',
	),
	Ayah(
		ayahId: 5691,
		ayahText: 'وَّفُتِحَتِ السَّمَاۤءُ فَكَانَتْ اَبْوَابًاۙ',
		ayahNumber: 19,
		translationId: 'dan langit pun dibukalah, maka terdapatlah beberapa pintu,',
	),
	Ayah(
		ayahId: 5692,
		ayahText: 'وَّسُيِّرَتِ الْجِبَالُ فَكَانَتْ سَرَابًاۗ',
		ayahNumber: 20,
		translationId: 'dan gunung-gunung pun dijalankan sehingga menjadi fatamorgana.',
	),
	Ayah(
		ayahId: 5693,
		ayahText: 'اِنَّ جَهَنَّمَ كَانَتْ مِرْصَادًاۙ',
		ayahNumber: 21,
		translationId: 'Sungguh, (neraka) Jahanam itu (sebagai) tempat mengintai (bagi penjaga yang mengawasi isi neraka), ',
	),
	Ayah(
		ayahId: 5694,
		ayahText: 'لِّلطّٰغِيْنَ مَاٰبًاۙ',
		ayahNumber: 22,
		translationId: 'menjadi tempat kembali bagi orang-orang yang melampaui batas.',
	),
	Ayah(
		ayahId: 5695,
		ayahText: 'لّٰبِثِيْنَ فِيْهَآ اَحْقَابًاۚ',
		ayahNumber: 23,
		translationId: 'Mereka tinggal di sana dalam masa yang lama,',
	),
	Ayah(
		ayahId: 5696,
		ayahText: 'لَا يَذُوْقُوْنَ فِيْهَا بَرْدًا وَّلَا شَرَابًاۙ',
		ayahNumber: 24,
		translationId: 'mereka tidak merasakan kesejukan di dalamnya dan tidak (pula mendapat) minuman,',
	),
	Ayah(
		ayahId: 5697,
		ayahText: 'اِلَّا حَمِيْمًا وَّغَسَّاقًاۙ',
		ayahNumber: 25,
		translationId: 'selain air yang mendidih dan nanah,',
	),
	Ayah(
		ayahId: 5698,
		ayahText: 'جَزَاۤءً وِّفَاقًاۗ',
		ayahNumber: 26,
		translationId: 'sebagai pembalasan yang setimpal.',
	),
	Ayah(
		ayahId: 5699,
		ayahText: 'اِنَّهُمْ كَانُوْا لَا يَرْجُوْنَ حِسَابًاۙ',
		ayahNumber: 27,
		translationId: 'Sesungguhnya dahulu mereka tidak pernah mengharapkan perhitungan.',
	),
	Ayah(
		ayahId: 5700,
		ayahText: 'وَّكَذَّبُوْا بِاٰيٰتِنَا كِذَّابًاۗ',
		ayahNumber: 28,
		translationId: 'Dan mereka benar-benar mendustakan ayat-ayat Kami.',
	),
	Ayah(
		ayahId: 5701,
		ayahText: 'وَكُلَّ شَيْءٍ اَحْصَيْنٰهُ كِتٰبًاۙ',
		ayahNumber: 29,
		translationId: 'Dan segala sesuatu telah Kami catat dalam suatu Kitab (buku catatan amalan manusia). ',
	),
	Ayah(
		ayahId: 5702,
		ayahText: 'فَذُوْقُوْا فَلَنْ نَّزِيْدَكُمْ اِلَّا عَذَابًا ࣖ',
		ayahNumber: 30,
		translationId: 'Maka karena itu rasakanlah! Maka tidak ada yang akan Kami tambahkan kepadamu selain azab.',
	),
	Ayah(
		ayahId: 5703,
		ayahText: 'اِنَّ لِلْمُتَّقِيْنَ مَفَازًاۙ',
		ayahNumber: 31,
		translationId: 'Sungguh, orang-orang yang bertakwa mendapat kemenangan,',
	),
	Ayah(
		ayahId: 5704,
		ayahText: 'حَدَاۤىِٕقَ وَاَعْنَابًاۙ',
		ayahNumber: 32,
		translationId: '(yaitu) kebun-kebun dan buah anggur,',
	),
	Ayah(
		ayahId: 5705,
		ayahText: 'وَّكَوَاعِبَ اَتْرَابًاۙ',
		ayahNumber: 33,
		translationId: 'dan gadis-gadis montok yang sebaya,',
	),
	Ayah(
		ayahId: 5706,
		ayahText: 'وَّكَأْسًا دِهَاقًاۗ',
		ayahNumber: 34,
		translationId: 'dan gelas-gelas yang penuh (berisi minuman).',
	),
	Ayah(
		ayahId: 5707,
		ayahText: 'لَا يَسْمَعُوْنَ فِيْهَا لَغْوًا وَّلَا كِذَّابًا',
		ayahNumber: 35,
		translationId: 'Di sana mereka tidak mendengar percakapan yang sia-sia maupun (perkataan) dusta.',
	),
	Ayah(
		ayahId: 5708,
		ayahText: 'جَزَاۤءً مِّنْ رَّبِّكَ عَطَاۤءً حِسَابًاۙ',
		ayahNumber: 36,
		translationId: 'Sebagai balasan dan pemberian yang cukup banyak dari Tuhanmu,',
	),
	Ayah(
		ayahId: 5709,
		ayahText: 'رَّبِّ السَّمٰوٰتِ وَالْاَرْضِ وَمَا بَيْنَهُمَا الرَّحْمٰنِ لَا يَمْلِكُوْنَ مِنْهُ خِطَابًاۚ ',
		ayahNumber: 37,
		translationId: 'Tuhan (yang memelihara) langit dan bumi dan apa yang ada di antara keduanya; Yang Maha Pengasih, mereka tidak mampu berbicara dengan Dia.',
	),
	Ayah(
		ayahId: 5710,
		ayahText: 'يَوْمَ يَقُوْمُ الرُّوْحُ وَالْمَلٰۤىِٕكَةُ صَفًّاۙ  لَّا يَتَكَلَّمُوْنَ اِلَّا مَنْ اَذِنَ لَهُ الرَّحْمٰنُ وَقَالَ صَوَابًا',
		ayahNumber: 38,
		translationId: 'Pada hari, ketika ruh dan para malaikat berdiri bersaf-saf, mereka tidak berkata-kata, kecuali siapa yang telah diberi izin kepadanya oleh Tuhan Yang Maha Pengasih dan dia hanya mengatakan yang benar.',
	),
	Ayah(
		ayahId: 5711,
		ayahText: 'ذٰلِكَ الْيَوْمُ الْحَقُّۚ فَمَنْ شَاۤءَ اتَّخَذَ اِلٰى رَبِّهٖ مَاٰبًا',
		ayahNumber: 39,
		translationId: 'Itulah hari yang pasti terjadi. Maka barang siapa menghendaki, niscaya dia menempuh jalan kembali kepada Tuhannya.',
	),
	Ayah(
		ayahId: 5712,
		ayahText: 'اِنَّآ اَنْذَرْنٰكُمْ عَذَابًا قَرِيْبًا ەۙ يَّوْمَ يَنْظُرُ الْمَرْءُ مَا قَدَّمَتْ يَدَاهُ وَيَقُوْلُ الْكٰفِرُ يٰلَيْتَنِيْ كُنْتُ تُرَابًا ࣖ',
		ayahNumber: 40,
		translationId: 'Sesungguhnya Kami telah memperingatkan kepadamu (orang kafir) azab yang dekat, pada hari manusia melihat apa yang telah diperbuat oleh kedua tangannya; dan orang kafir berkata, “Alangkah baiknya seandainya dahulu aku jadi tanah.”',
	),
];
