// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah79 = [
	Ayah(
		ayahId: 5713,
		ayahText: 'وَالنّٰزِعٰتِ غَرْقًاۙ',
		ayahNumber: 1,
		translationId: 'Demi (malaikat) yang mencabut (nyawa) dengan keras.',
	),
	Ayah(
		ayahId: 5714,
		ayahText: 'وَّالنّٰشِطٰتِ نَشْطًاۙ',
		ayahNumber: 2,
		translationId: 'Demi (malaikat) yang mencabut (nyawa) dengan lemah lembut.',
	),
	Ayah(
		ayahId: 5715,
		ayahText: 'وَّالسّٰبِحٰتِ سَبْحًاۙ',
		ayahNumber: 3,
		translationId: 'Demi (malaikat) yang turun dari langit dengan cepat,',
	),
	Ayah(
		ayahId: 5716,
		ayahText: 'فَالسّٰبِقٰتِ سَبْقًاۙ',
		ayahNumber: 4,
		translationId: 'dan (malaikat) yang mendahului dengan kencang,',
	),
	Ayah(
		ayahId: 5717,
		ayahText: 'فَالْمُدَبِّرٰتِ اَمْرًاۘ',
		ayahNumber: 5,
		translationId: 'dan (malaikat) yang mengatur urusan (dunia).',
	),
	Ayah(
		ayahId: 5718,
		ayahText: 'يَوْمَ تَرْجُفُ الرَّاجِفَةُۙ',
		ayahNumber: 6,
		translationId: '(Sungguh, kamu akan dibangkitkan) pada hari ketika tiupan pertama mengguncangkan alam,',
	),
	Ayah(
		ayahId: 5719,
		ayahText: 'تَتْبَعُهَا الرَّادِفَةُ ۗ',
		ayahNumber: 7,
		translationId: '(tiupan pertama) itu diiringi oleh tiupan kedua.',
	),
	Ayah(
		ayahId: 5720,
		ayahText: 'قُلُوْبٌ يَّوْمَىِٕذٍ وَّاجِفَةٌۙ',
		ayahNumber: 8,
		translationId: 'Hati manusia pada waktu itu merasa sangat takut,',
	),
	Ayah(
		ayahId: 5721,
		ayahText: 'اَبْصَارُهَا خَاشِعَةٌ  ۘ',
		ayahNumber: 9,
		translationId: 'pandangannya tunduk.',
	),
	Ayah(
		ayahId: 5722,
		ayahText: 'يَقُوْلُوْنَ ءَاِنَّا لَمَرْدُوْدُوْنَ فِى الْحَافِرَةِۗ',
		ayahNumber: 10,
		translationId: '(Orang-orang kafir) berkata, “Apakah kita benar-benar akan dikembalikan kepada kehidupan yang semula?   ',
	),
	Ayah(
		ayahId: 5723,
		ayahText: 'ءَاِذَا كُنَّا عِظَامًا نَّخِرَةً ۗ',
		ayahNumber: 11,
		translationId: 'Apakah (akan dibangkitkan juga) apabila kita telah menjadi tulang belulang yang hancur?”',
	),
	Ayah(
		ayahId: 5724,
		ayahText: 'قَالُوْا تِلْكَ اِذًا كَرَّةٌ خَاسِرَةٌ  ۘ',
		ayahNumber: 12,
		translationId: 'Mereka berkata, “Kalau demikian, itu adalah suatu pengembalian yang merugikan.”',
	),
	Ayah(
		ayahId: 5725,
		ayahText: 'فَاِنَّمَا هِيَ زَجْرَةٌ وَّاحِدَةٌۙ',
		ayahNumber: 13,
		translationId: 'Maka pengembalian itu hanyalah dengan sekali tiupan saja.',
	),
	Ayah(
		ayahId: 5726,
		ayahText: 'فَاِذَا هُمْ بِالسَّاهِرَةِۗ',
		ayahNumber: 14,
		translationId: 'Maka seketika itu mereka hidup kembali di bumi (yang baru).',
	),
	Ayah(
		ayahId: 5727,
		ayahText: 'هَلْ اَتٰىكَ حَدِيْثُ مُوْسٰىۘ',
		ayahNumber: 15,
		translationId: 'Sudahkah sampai kepadamu (Muhammad) kisah Musa?',
	),
	Ayah(
		ayahId: 5728,
		ayahText: 'اِذْ نَادٰىهُ رَبُّهٗ بِالْوَادِ الْمُقَدَّسِ طُوًىۚ',
		ayahNumber: 16,
		translationId: 'Ketika Tuhan memanggilnya (Musa) di lembah suci yaitu Lembah Tuwa;',
	),
	Ayah(
		ayahId: 5729,
		ayahText: 'اِذْهَبْ اِلٰى فِرْعَوْنَ اِنَّهٗ طَغٰىۖ',
		ayahNumber: 17,
		translationId: 'pergilah engkau kepada Fir‘aun! Sesungguhnya dia telah melampaui batas,',
	),
	Ayah(
		ayahId: 5730,
		ayahText: 'فَقُلْ هَلْ لَّكَ اِلٰٓى اَنْ تَزَكّٰىۙ',
		ayahNumber: 18,
		translationId: 'Maka katakanlah (kepada Fir‘aun), “Adakah keinginanmu untuk membersihkan diri (dari kesesatan),',
	),
	Ayah(
		ayahId: 5731,
		ayahText: 'وَاَهْدِيَكَ اِلٰى رَبِّكَ فَتَخْشٰىۚ',
		ayahNumber: 19,
		translationId: 'dan engkau akan kupimpin ke jalan Tuhanmu agar engkau takut kepada-Nya?”',
	),
	Ayah(
		ayahId: 5732,
		ayahText: 'فَاَرٰىهُ الْاٰيَةَ الْكُبْرٰىۖ',
		ayahNumber: 20,
		translationId: 'Lalu (Musa) memperlihatkan kepadanya mukjizat yang besar.',
	),
	Ayah(
		ayahId: 5733,
		ayahText: 'فَكَذَّبَ وَعَصٰىۖ',
		ayahNumber: 21,
		translationId: 'Tetapi dia (Fir‘aun) mendustakan dan mendurhakai.',
	),
	Ayah(
		ayahId: 5734,
		ayahText: 'ثُمَّ اَدْبَرَ يَسْعٰىۖ',
		ayahNumber: 22,
		translationId: 'Kemudian dia berpaling seraya berusaha menantang (Musa).',
	),
	Ayah(
		ayahId: 5735,
		ayahText: 'فَحَشَرَ فَنَادٰىۖ',
		ayahNumber: 23,
		translationId: 'Kemudian dia mengumpulkan (pembesar-pembesarnya) lalu berseru (memanggil kaumnya).',
	),
	Ayah(
		ayahId: 5736,
		ayahText: 'فَقَالَ اَنَا۠ رَبُّكُمُ الْاَعْلٰىۖ',
		ayahNumber: 24,
		translationId: '(Seraya) berkata, “Akulah tuhanmu yang paling tinggi.”',
	),
	Ayah(
		ayahId: 5737,
		ayahText: 'فَاَخَذَهُ اللّٰهُ نَكَالَ الْاٰخِرَةِ وَالْاُوْلٰىۗ',
		ayahNumber: 25,
		translationId: 'Maka Allah menghukumnya dengan azab di akhirat dan siksaan di dunia.',
	),
	Ayah(
		ayahId: 5738,
		ayahText: 'اِنَّ فِيْ ذٰلِكَ لَعِبْرَةً لِّمَنْ يَّخْشٰى ۗ ࣖ',
		ayahNumber: 26,
		translationId: 'Sungguh, pada yang demikian itu terdapat pelajaran bagi orang yang takut (kepada Allah).',
	),
	Ayah(
		ayahId: 5739,
		ayahText: 'ءَاَنْتُمْ اَشَدُّ خَلْقًا اَمِ السَّمَاۤءُ ۚ بَنٰىهَاۗ',
		ayahNumber: 27,
		translationId: 'Apakah penciptaan kamu yang lebih hebat ataukah langit yang telah dibangun-Nya?',
	),
	Ayah(
		ayahId: 5740,
		ayahText: 'رَفَعَ سَمْكَهَا فَسَوّٰىهَاۙ',
		ayahNumber: 28,
		translationId: 'Dia telah meninggikan bangunannya lalu menyempurnakannya,',
	),
	Ayah(
		ayahId: 5741,
		ayahText: 'وَاَغْطَشَ لَيْلَهَا وَاَخْرَجَ ضُحٰىهَاۖ',
		ayahNumber: 29,
		translationId: 'dan Dia menjadikan malamnya (gelap gulita), dan menjadikan siangnya (terang benderang).',
	),
	Ayah(
		ayahId: 5742,
		ayahText: 'وَالْاَرْضَ بَعْدَ ذٰلِكَ دَحٰىهَاۗ',
		ayahNumber: 30,
		translationId: 'Dan setelah itu bumi Dia hamparkan. ',
	),
	Ayah(
		ayahId: 5743,
		ayahText: 'اَخْرَجَ مِنْهَا مَاۤءَهَا وَمَرْعٰىهَاۖ',
		ayahNumber: 31,
		translationId: 'Darinya Dia pancarkan mata air, dan (ditumbuhkan) tumbuh-tumbuhannya.',
	),
	Ayah(
		ayahId: 5744,
		ayahText: 'وَالْجِبَالَ اَرْسٰىهَاۙ',
		ayahNumber: 32,
		translationId: 'Dan gunung-gunung Dia pancangkan dengan teguh.',
	),
	Ayah(
		ayahId: 5745,
		ayahText: 'مَتَاعًا لَّكُمْ وَلِاَنْعَامِكُمْۗ',
		ayahNumber: 33,
		translationId: '(Semua itu) untuk kesenanganmu dan untuk hewan-hewan ternakmu.',
	),
	Ayah(
		ayahId: 5746,
		ayahText: 'فَاِذَا جَاۤءَتِ الطَّاۤمَّةُ الْكُبْرٰىۖ',
		ayahNumber: 34,
		translationId: 'Maka apabila malapetaka besar (hari Kiamat) telah datang,',
	),
	Ayah(
		ayahId: 5747,
		ayahText: 'يَوْمَ يَتَذَكَّرُ الْاِنْسَانُ مَا سَعٰىۙ',
		ayahNumber: 35,
		translationId: 'yaitu pada hari (ketika) manusia teringat akan apa yang telah dikerjakannya,',
	),
	Ayah(
		ayahId: 5748,
		ayahText: 'وَبُرِّزَتِ الْجَحِيْمُ لِمَنْ يَّرٰى',
		ayahNumber: 36,
		translationId: 'dan neraka diperlihatkan dengan jelas kepada setiap orang yang melihat.',
	),
	Ayah(
		ayahId: 5749,
		ayahText: 'فَاَمَّا مَنْ طَغٰىۖ',
		ayahNumber: 37,
		translationId: 'Maka adapun orang yang melampaui batas,',
	),
	Ayah(
		ayahId: 5750,
		ayahText: 'وَاٰثَرَ الْحَيٰوةَ الدُّنْيَاۙ',
		ayahNumber: 38,
		translationId: 'dan lebih mengutamakan kehidupan dunia,',
	),
	Ayah(
		ayahId: 5751,
		ayahText: 'فَاِنَّ الْجَحِيْمَ هِيَ الْمَأْوٰىۗ',
		ayahNumber: 39,
		translationId: 'maka sungguh, nerakalah tempat tinggalnya.',
	),
	Ayah(
		ayahId: 5752,
		ayahText: 'وَاَمَّا مَنْ خَافَ مَقَامَ رَبِّهٖ وَنَهَى النَّفْسَ عَنِ الْهَوٰىۙ',
		ayahNumber: 40,
		translationId: 'Dan adapun orang-orang yang takut kepada kebesaran Tuhannya dan menahan diri dari (keinginan) hawa nafsunya,',
	),
	Ayah(
		ayahId: 5753,
		ayahText: 'فَاِنَّ الْجَنَّةَ هِيَ الْمَأْوٰىۗ',
		ayahNumber: 41,
		translationId: 'maka sungguh, surgalah tempat tinggal(nya).',
	),
	Ayah(
		ayahId: 5754,
		ayahText: 'يَسْـَٔلُوْنَكَ عَنِ السَّاعَةِ اَيَّانَ مُرْسٰىهَاۗ',
		ayahNumber: 42,
		translationId: 'Mereka (orang-orang kafir) bertanya kepadamu (Muhammad) tentang hari Kiamat, “Kapankah terjadinya?” ',
	),
	Ayah(
		ayahId: 5755,
		ayahText: 'فِيْمَ اَنْتَ مِنْ ذِكْرٰىهَاۗ',
		ayahNumber: 43,
		translationId: 'Untuk apa engkau perlu menyebutkannya (waktunya)?',
	),
	Ayah(
		ayahId: 5756,
		ayahText: 'اِلٰى رَبِّكَ مُنْتَهٰىهَاۗ',
		ayahNumber: 44,
		translationId: 'Kepada Tuhanmulah (dikembalikan) kesudahannya (ketentuan waktunya).',
	),
	Ayah(
		ayahId: 5757,
		ayahText: 'اِنَّمَآ اَنْتَ مُنْذِرُ مَنْ يَّخْشٰىهَاۗ',
		ayahNumber: 45,
		translationId: 'Engkau (Muhammad) hanyalah pemberi peringatan bagi siapa yang takut kepadanya (hari Kiamat).',
	),
	Ayah(
		ayahId: 5758,
		ayahText: 'كَاَنَّهُمْ يَوْمَ يَرَوْنَهَا لَمْ يَلْبَثُوْٓا اِلَّا عَشِيَّةً اَوْ ضُحٰىهَا ࣖ',
		ayahNumber: 46,
		translationId: 'Pada hari ketika mereka melihat hari Kiamat itu (karena suasananya hebat), mereka merasa seakan-akan hanya (sebentar saja) tinggal (di dunia) pada waktu sore atau pagi hari.',
	),
];
