// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah53 = [
	Ayah(
		ayahId: 4785,
		ayahText: 'وَالنَّجْمِ اِذَا هَوٰىۙ ',
		ayahNumber: 1,
		translationId: 'Demi bintang ketika terbenam, ',
	),
	Ayah(
		ayahId: 4786,
		ayahText: 'مَا ضَلَّ صَاحِبُكُمْ وَمَا غَوٰىۚ ',
		ayahNumber: 2,
		translationId: 'kawanmu (Muhammad) tidak sesat dan tidak (pula) keliru,',
	),
	Ayah(
		ayahId: 4787,
		ayahText: 'وَمَا يَنْطِقُ عَنِ الْهَوٰى',
		ayahNumber: 3,
		translationId: "dan tidaklah yang diucapkannya itu (Al-Qur'an) menurut keinginannya. ",
	),
	Ayah(
		ayahId: 4788,
		ayahText: 'اِنْ هُوَ اِلَّا وَحْيٌ يُّوْحٰىۙ ',
		ayahNumber: 4,
		translationId: "Tidak lain (Al-Qur'an itu) adalah wahyu yang diwahyukan (kepadanya),",
	),
	Ayah(
		ayahId: 4789,
		ayahText: 'عَلَّمَهٗ شَدِيْدُ الْقُوٰىۙ ',
		ayahNumber: 5,
		translationId: 'yang diajarkan kepadanya oleh (Jibril) yang sangat kuat, ',
	),
	Ayah(
		ayahId: 4790,
		ayahText: 'ذُوْ مِرَّةٍۗ فَاسْتَوٰىۙ ',
		ayahNumber: 6,
		translationId: 'yang mempunyai keteguhan; maka (Jibril itu) menampakkan diri dengan rupa yang asli (rupa yang bagus dan perkasa)',
	),
	Ayah(
		ayahId: 4791,
		ayahText: 'وَهُوَ بِالْاُفُقِ الْاَعْلٰىۗ ',
		ayahNumber: 7,
		translationId: 'Sedang dia berada di ufuk yang tinggi.',
	),
	Ayah(
		ayahId: 4792,
		ayahText: 'ثُمَّ دَنَا فَتَدَلّٰىۙ  ',
		ayahNumber: 8,
		translationId: 'Kemudian dia mendekat (pada Muhammad), lalu bertambah dekat, ',
	),
	Ayah(
		ayahId: 4793,
		ayahText: 'فَكَانَ قَابَ قَوْسَيْنِ اَوْ اَدْنٰىۚ',
		ayahNumber: 9,
		translationId: 'sehingga jaraknya (sekitar) dua busur panah atau lebih dekat (lagi).',
	),
	Ayah(
		ayahId: 4794,
		ayahText: 'فَاَوْحٰىٓ اِلٰى عَبْدِهٖ مَآ اَوْحٰىۗ',
		ayahNumber: 10,
		translationId: 'Lalu disampaikannya wahyu kepada hamba-Nya (Muhammad) apa yang telah diwahyukan Allah. ',
	),
	Ayah(
		ayahId: 4795,
		ayahText: 'مَا كَذَبَ الْفُؤَادُ مَا رَاٰى',
		ayahNumber: 11,
		translationId: 'Hatinya tidak mendustakan apa yang telah dilihatnya. ',
	),
	Ayah(
		ayahId: 4796,
		ayahText: 'اَفَتُمٰرُوْنَهٗ عَلٰى مَا يَرٰى ',
		ayahNumber: 12,
		translationId: 'Maka apakah kamu (musyrikin Mekah) hendak membantahnya tentang apa yang dilihatnya itu?',
	),
	Ayah(
		ayahId: 4797,
		ayahText: 'وَلَقَدْ رَاٰهُ نَزْلَةً اُخْرٰىۙ',
		ayahNumber: 13,
		translationId: 'Dan sungguh, dia (Muhammad) telah melihatnya (dalam rupanya yang asli) pada waktu yang lain,',
	),
	Ayah(
		ayahId: 4798,
		ayahText: 'عِنْدَ سِدْرَةِ الْمُنْتَهٰى ',
		ayahNumber: 14,
		translationId: '(yaitu) di Sidratul Muntaha,',
	),
	Ayah(
		ayahId: 4799,
		ayahText: 'عِنْدَهَا جَنَّةُ الْمَأْوٰىۗ  ',
		ayahNumber: 15,
		translationId: 'di dekatnya ada surga tempat tinggal,',
	),
	Ayah(
		ayahId: 4800,
		ayahText: 'اِذْ يَغْشَى السِّدْرَةَ مَا يَغْشٰىۙ ',
		ayahNumber: 16,
		translationId: '(Muhammad melihat Jibril) ketika Sidratil muntaha diliputi oleh sesuatu yang meliputinya,',
	),
	Ayah(
		ayahId: 4801,
		ayahText: 'مَا زَاغَ الْبَصَرُ وَمَا طَغٰى',
		ayahNumber: 17,
		translationId: 'penglihatannya (Muhammad) tidak menyimpang dari yang dilihatnya itu dan tidak (pula) melampauinya.',
	),
	Ayah(
		ayahId: 4802,
		ayahText: 'لَقَدْ رَاٰى مِنْ اٰيٰتِ رَبِّهِ الْكُبْرٰى',
		ayahNumber: 18,
		translationId: 'Sungguh, dia telah melihat sebagian tanda-tanda (kebesaran) Tuhannya yang paling besar.          ',
	),
	Ayah(
		ayahId: 4803,
		ayahText: 'اَفَرَءَيْتُمُ اللّٰتَ وَالْعُزّٰى',
		ayahNumber: 19,
		translationId: 'Maka apakah patut kamu (orang-orang musyrik) menganggap (berhala) Al-Lata dan Al-‘Uzza,',
	),
	Ayah(
		ayahId: 4804,
		ayahText: 'وَمَنٰوةَ الثَّالِثَةَ الْاُخْرٰى ',
		ayahNumber: 20,
		translationId: 'dan Manat, yang ketiga (yang) kemudian (sebagai anak perempuan Allah).',
	),
	Ayah(
		ayahId: 4805,
		ayahText: 'اَلَكُمُ الذَّكَرُ وَلَهُ الْاُنْثٰى ',
		ayahNumber: 21,
		translationId: 'Apakah (pantas) untuk kamu yang laki-laki dan untuk-Nya yang perempuan?',
	),
	Ayah(
		ayahId: 4806,
		ayahText: 'تِلْكَ اِذًا قِسْمَةٌ ضِيْزٰى ',
		ayahNumber: 22,
		translationId: 'Yang demikian itu tentulah suatu pembagian yang tidak adil. ',
	),
	Ayah(
		ayahId: 4807,
		ayahText: 'اِنْ هِيَ اِلَّآ اَسْمَاۤءٌ سَمَّيْتُمُوْهَآ اَنْتُمْ وَاٰبَاۤؤُكُمْ مَّآ اَنْزَلَ اللّٰهُ بِهَا مِنْ سُلْطٰنٍۗ اِنْ يَّتَّبِعُوْنَ اِلَّا الظَّنَّ وَمَا تَهْوَى الْاَنْفُسُۚ وَلَقَدْ جَاۤءَهُمْ مِّنْ رَّبِّهِمُ الْهُدٰىۗ',
		ayahNumber: 23,
		translationId: 'Itu tidak lain hanyalah nama-nama yang kamu dan nenek moyangmu mengada-adakannya; Allah tidak menurunkan suatu keterangan apa pun untuk (menyembah)nya. Mereka hanya mengikuti dugaan, dan apa yang diingini oleh keinginannya. Padahal sungguh, telah datang petunjuk dari Tuhan mereka. ',
	),
	Ayah(
		ayahId: 4808,
		ayahText: 'اَمْ لِلْاِنْسَانِ مَا تَمَنّٰىۖ  ',
		ayahNumber: 24,
		translationId: 'Atau apakah manusia akan mendapat segala yang dicita-citakannya?',
	),
	Ayah(
		ayahId: 4809,
		ayahText: 'فَلِلّٰهِ الْاٰخِرَةُ وَالْاُوْلٰى ࣖ ',
		ayahNumber: 25,
		translationId: '(Tidak!) Maka milik Allah-lah kehidupan akhirat dan kehidupan dunia. ',
	),
	Ayah(
		ayahId: 4810,
		ayahText: 'وَكَمْ مِّنْ مَّلَكٍ فِى السَّمٰوٰتِ لَا تُغْنِيْ شَفَاعَتُهُمْ شَيْـًٔا اِلَّا مِنْۢ بَعْدِ اَنْ يَّأْذَنَ اللّٰهُ لِمَنْ يَّشَاۤءُ وَيَرْضٰى ',
		ayahNumber: 26,
		translationId: 'Dan betapa banyak malaikat di langit, syafaat (pertolongan) mereka sedikit pun tidak berguna kecuali apabila Allah telah mengizinkan (dan hanya) bagi siapa yang Dia kehendaki dan Dia ridai. ',
	),
	Ayah(
		ayahId: 4811,
		ayahText: 'اِنَّ الَّذِيْنَ لَا يُؤْمِنُوْنَ بِالْاٰخِرَةِ لَيُسَمُّوْنَ الْمَلٰۤىِٕكَةَ تَسْمِيَةَ الْاُنْثٰى ',
		ayahNumber: 27,
		translationId: 'Sesungguhnya orang-orang yang tidak beriman kepada kehidupan akhirat, sungguh mereka menamakan para malaikat dengan nama perempuan. ',
	),
	Ayah(
		ayahId: 4812,
		ayahText: 'وَمَا لَهُمْ بِهٖ مِنْ عِلْمٍۗ اِنْ يَّتَّبِعُوْنَ اِلَّا الظَّنَّ وَاِنَّ الظَّنَّ لَا يُغْنِيْ مِنَ الْحَقِّ شَيْـًٔاۚ ',
		ayahNumber: 28,
		translationId: 'Dan mereka tidak mempunyai ilmu tentang itu. Mereka tidak lain hanyalah mengikuti dugaan, dan sesungguhnya dugaan itu tidak berfaedah sedikit pun terhadap kebenaran. ',
	),
	Ayah(
		ayahId: 4813,
		ayahText: 'فَاَعْرِضْ عَنْ مَّنْ تَوَلّٰىۙ عَنْ ذِكْرِنَا وَلَمْ يُرِدْ اِلَّا الْحَيٰوةَ الدُّنْيَاۗ  ',
		ayahNumber: 29,
		translationId: 'Maka tinggalkanlah (Muhammad) orang yang berpaling dari peringatan Kami, dan dia hanya mengingini kehidupan dunia.',
	),
	Ayah(
		ayahId: 4814,
		ayahText: 'ذٰلِكَ مَبْلَغُهُمْ مِّنَ الْعِلْمِۗ اِنَّ رَبَّكَ هُوَ اَعْلَمُ بِمَنْ ضَلَّ عَنْ سَبِيْلِهٖۙ وَهُوَ اَعْلَمُ بِمَنِ اهْتَدٰى',
		ayahNumber: 30,
		translationId: 'Itulah kadar ilmu mereka. Sungguh, Tuhanmu, Dia lebih mengetahui siapa yang tersesat dari jalan-Nya dan Dia pula yang mengetahui siapa yang mendapat petunjuk. ',
	),
	Ayah(
		ayahId: 4815,
		ayahText: 'وَلِلّٰهِ مَا فِى السَّمٰوٰتِ وَمَا فِى الْاَرْضِۗ لِيَجْزِيَ الَّذِيْنَ اَسَاۤءُوْا بِمَا عَمِلُوْا وَيَجْزِيَ الَّذِيْنَ اَحْسَنُوْا بِالْحُسْنٰىۚ ',
		ayahNumber: 31,
		translationId: 'Dan milik Allah-lah apa yang ada di langit dan apa yang ada di bumi. (Dengan demikian) Dia akan memberi balasan kepada orang-orang yang berbuat jahat sesuai dengan apa yang telah mereka kerjakan dan Dia akan memberi balasan kepada orang-orang yang berbuat baik dengan pahala yang lebih baik (surga). ',
	),
	Ayah(
		ayahId: 4816,
		ayahText: 'اَلَّذِيْنَ يَجْتَنِبُوْنَ كَبٰۤىِٕرَ الْاِثْمِ وَالْفَوَاحِشَ اِلَّا اللَّمَمَۙ اِنَّ رَبَّكَ وَاسِعُ الْمَغْفِرَةِۗ هُوَ اَعْلَمُ بِكُمْ اِذْ اَنْشَاَكُمْ مِّنَ الْاَرْضِ وَاِذْ اَنْتُمْ اَجِنَّةٌ فِيْ بُطُوْنِ اُمَّهٰتِكُمْۗ فَلَا تُزَكُّوْٓا اَنْفُسَكُمْۗ  هُوَ اَعْلَمُ بِمَنِ اتَّقٰى ࣖ ',
		ayahNumber: 32,
		translationId: 'Yaitu) mereka yang menjauhi dosa-dosa besar dan perbuatan keji, kecuali kesalahan-kesalahan kecil. Sungguh, Tuhanmu Mahaluas ampunan-Nya. Dia mengetahui tentang kamu, sejak Dia menjadikan kamu dari tanah lalu ketika kamu masih janin dalam perut ibumu. Maka janganlah kamu menganggap dirimu suci. Dia mengetahui tentang orang yang bertakwa. ',
	),
	Ayah(
		ayahId: 4817,
		ayahText: 'اَفَرَءَيْتَ الَّذِيْ تَوَلّٰىۙ  ',
		ayahNumber: 33,
		translationId: "Maka tidakkah engkau melihat orang yang berpaling (dari Al-Qur'an)?",
	),
	Ayah(
		ayahId: 4818,
		ayahText: 'وَاَعْطٰى قَلِيْلًا وَّاَكْدٰى ',
		ayahNumber: 34,
		translationId: 'dan dia memberikan sedikit (dari apa yang dijanjikan) lalu menahan sisanya.',
	),
	Ayah(
		ayahId: 4819,
		ayahText: 'اَعِنْدَهٗ عِلْمُ الْغَيْبِ فَهُوَ يَرٰى ',
		ayahNumber: 35,
		translationId: 'Apakah dia mempunyai ilmu tentang yang gaib sehingga dia dapat melihat(nya)?',
	),
	Ayah(
		ayahId: 4820,
		ayahText: 'اَمْ لَمْ يُنَبَّأْ بِمَا فِيْ صُحُفِ مُوْسٰى  ',
		ayahNumber: 36,
		translationId: 'Ataukah belum diberitakan (kepadanya) apa yang ada dalam lembaran-lembaran (Kitab Suci yang diturunkan kepada) Musa?',
	),
	Ayah(
		ayahId: 4821,
		ayahText: 'وَاِبْرٰهِيْمَ الَّذِيْ وَفّٰىٓ ۙ ',
		ayahNumber: 37,
		translationId: 'Dan (lembaran-lembaran) Ibrahim yang selalu menyempurnakan janji?',
	),
	Ayah(
		ayahId: 4822,
		ayahText: 'اَلَّا تَزِرُ وَازِرَةٌ وِّزْرَ اُخْرٰىۙ  ',
		ayahNumber: 38,
		translationId: '(yaitu) bahwa seseorang yang berdosa tidak akan memikul dosa orang lain,',
	),
	Ayah(
		ayahId: 4823,
		ayahText: 'وَاَنْ لَّيْسَ لِلْاِنْسَانِ اِلَّا مَا سَعٰىۙ  ',
		ayahNumber: 39,
		translationId: 'dan bahwa manusia hanya memperoleh apa yang telah diusahakannya,',
	),
	Ayah(
		ayahId: 4824,
		ayahText: 'وَاَنَّ سَعْيَهٗ سَوْفَ يُرٰىۖ',
		ayahNumber: 40,
		translationId: 'dan sesungguhnya usahanya itu kelak akan diperlihatkan (kepadanya),',
	),
	Ayah(
		ayahId: 4825,
		ayahText: 'ثُمَّ يُجْزٰىهُ الْجَزَاۤءَ الْاَوْفٰىۙ ',
		ayahNumber: 41,
		translationId: 'kemudian akan diberi balasan kepadanya dengan balasan yang paling  sempurna,',
	),
	Ayah(
		ayahId: 4826,
		ayahText: 'وَاَنَّ اِلٰى رَبِّكَ الْمُنْتَهٰىۙ  ',
		ayahNumber: 42,
		translationId: 'dan sesungguhnya kepada Tuhanmulah kesudahannya (segala sesuatu),',
	),
	Ayah(
		ayahId: 4827,
		ayahText: 'وَاَنَّهٗ هُوَ اَضْحَكَ وَاَبْكٰى',
		ayahNumber: 43,
		translationId: 'dan sesungguhnya Dialah yang menjadikan orang tertawa dan menangis, ',
	),
	Ayah(
		ayahId: 4828,
		ayahText: 'وَاَنَّهٗ هُوَ اَمَاتَ وَاَحْيَاۙ  ',
		ayahNumber: 44,
		translationId: 'dan sesungguhnya Dialah yang mematikan dan menghidupkan, ',
	),
	Ayah(
		ayahId: 4829,
		ayahText: 'وَاَنَّهٗ خَلَقَ الزَّوْجَيْنِ الذَّكَرَ وَالْاُنْثٰى ',
		ayahNumber: 45,
		translationId: 'dan sesungguhnya Dialah yang men-ciptakan pasangan laki-laki dan perempuan,',
	),
	Ayah(
		ayahId: 4830,
		ayahText: 'مِنْ نُّطْفَةٍ اِذَا تُمْنٰىۙ  ',
		ayahNumber: 46,
		translationId: 'dari mani, apabila dipancarkan,',
	),
	Ayah(
		ayahId: 4831,
		ayahText: 'وَاَنَّ عَلَيْهِ النَّشْاَةَ الْاُخْرٰىۙ ',
		ayahNumber: 47,
		translationId: 'dan sesungguhnya Dialah yang menetapkan penciptaan yang lain (kebangkitan setelah mati),',
	),
	Ayah(
		ayahId: 4832,
		ayahText: 'وَاَنَّهٗ هُوَ اَغْنٰى وَاَقْنٰىۙ ',
		ayahNumber: 48,
		translationId: 'dan sesungguhnya Dialah yang memberikan kekayaan dan kecukupan. ',
	),
	Ayah(
		ayahId: 4833,
		ayahText: 'وَاَنَّهٗ هُوَ رَبُّ الشِّعْرٰىۙ',
		ayahNumber: 49,
		translationId: 'dan sesungguhnya Dialah Tuhan (yang memiliki) bintang Syi‘ra, ',
	),
	Ayah(
		ayahId: 4834,
		ayahText: 'وَاَنَّهٗٓ اَهْلَكَ عَادًا ۨالْاُوْلٰىۙ',
		ayahNumber: 50,
		translationId: 'dan sesungguhnya Dialah yang telah membinasakan kaum ‘Ad dahulu kala, ',
	),
	Ayah(
		ayahId: 4835,
		ayahText: 'وَثَمُوْدَا۟ فَمَآ اَبْقٰىۙ',
		ayahNumber: 51,
		translationId: 'dan kaum Samud, tidak seorang pun yang ditinggalkan-Nya (hidup), ',
	),
	Ayah(
		ayahId: 4836,
		ayahText: 'وَقَوْمَ نُوْحٍ مِّنْ قَبْلُۗ اِنَّهُمْ كَانُوْا هُمْ اَظْلَمَ وَاَطْغٰىۗ  ',
		ayahNumber: 52,
		translationId: 'dan (juga) kaum Nuh sebelum itu. Sungguh, mereka adalah orang-orang yang paling zalim dan paling durhaka.',
	),
	Ayah(
		ayahId: 4837,
		ayahText: 'وَالْمُؤْتَفِكَةَ اَهْوٰىۙ  ',
		ayahNumber: 53,
		translationId: 'Dan prahara angin telah meruntuhkan (negeri kaum Lut), ',
	),
	Ayah(
		ayahId: 4838,
		ayahText: 'فَغَشّٰىهَا مَا غَشّٰىۚ  ',
		ayahNumber: 54,
		translationId: 'lalu menimbuni negeri itu (sebagai azab) dengan (puing-puing) yang menimpanya. ',
	),
	Ayah(
		ayahId: 4839,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكَ تَتَمَارٰى',
		ayahNumber: 55,
		translationId: 'Maka terhadap nikmat Tuhanmu yang manakah yang masih kamu ragukan?',
	),
	Ayah(
		ayahId: 4840,
		ayahText: 'هٰذَا نَذِيْرٌ مِّنَ النُّذُرِ الْاُوْلٰى',
		ayahNumber: 56,
		translationId: 'Ini (Muhammad) salah seorang pemberi peringatan di antara para pemberi peringatan yang telah terdahulu. ',
	),
	Ayah(
		ayahId: 4841,
		ayahText: 'اَزِفَتِ الْاٰزِفةُ ۚ ',
		ayahNumber: 57,
		translationId: 'Yang dekat (hari Kiamat) telah makin mendekat. ',
	),
	Ayah(
		ayahId: 4842,
		ayahText: 'لَيْسَ لَهَا مِنْ دُوْنِ اللّٰهِ كَاشِفَةٌ  ۗ ',
		ayahNumber: 58,
		translationId: 'Tidak ada yang akan dapat mengungkapkan (terjadinya hari itu) selain Allah.',
	),
	Ayah(
		ayahId: 4843,
		ayahText: 'اَفَمِنْ هٰذَا الْحَدِيْثِ تَعْجَبُوْنَۙ  ',
		ayahNumber: 59,
		translationId: 'Maka apakah kamu merasa heran terhadap pemberitaan ini?',
	),
	Ayah(
		ayahId: 4844,
		ayahText: 'وَتَضْحَكُوْنَ وَلَا تَبْكُوْنَۙ  ',
		ayahNumber: 60,
		translationId: 'dan kamu tertawakan dan tidak menangis, ',
	),
	Ayah(
		ayahId: 4845,
		ayahText: 'وَاَنْتُمْ سَامِدُوْنَ ',
		ayahNumber: 61,
		translationId: 'sedang kamu lengah (darinya).',
	),
	Ayah(
		ayahId: 4846,
		ayahText: 'فَاسْجُدُوْا لِلّٰهِ وَاعْبُدُوْا ࣖ ۩ ',
		ayahNumber: 62,
		translationId: 'Maka bersujudlah kepada Allah dan sembahlah (Dia). ',
	),
];
