// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah70 = [
	Ayah(
		ayahId: 5376,
		ayahText: 'سَاَلَ سَاۤىِٕلٌۢ بِعَذَابٍ وَّاقِعٍۙ',
		ayahNumber: 1,
		translationId: 'Seseorang bertanya tentang azab yang pasti terjadi, ',
	),
	Ayah(
		ayahId: 5377,
		ayahText: 'لِّلْكٰفِرِيْنَ لَيْسَ لَهٗ دَافِعٌۙ',
		ayahNumber: 2,
		translationId: 'bagi orang-orang kafir, yang tidak seorang pun dapat menolaknya,',
	),
	Ayah(
		ayahId: 5378,
		ayahText: 'مِّنَ اللّٰهِ ذِى الْمَعَارِجِۗ',
		ayahNumber: 3,
		translationId: '(Azab) dari Allah, yang memiliki tempat-tempat naik.',
	),
	Ayah(
		ayahId: 5379,
		ayahText: 'تَعْرُجُ الْمَلٰۤىِٕكَةُ وَالرُّوْحُ اِلَيْهِ فِيْ يَوْمٍ كَانَ مِقْدَارُهٗ خَمْسِيْنَ اَلْفَ سَنَةٍۚ',
		ayahNumber: 4,
		translationId: 'Para malaikat dan Jibril naik (menghadap) kepada Tuhan, dalam sehari setara dengan lima puluh ribu tahun.',
	),
	Ayah(
		ayahId: 5380,
		ayahText: 'فَاصْبِرْ صَبْرًا جَمِيْلًا',
		ayahNumber: 5,
		translationId: 'Maka bersabarlah engkau (Muhammad) dengan kesabaran yang baik.',
	),
	Ayah(
		ayahId: 5381,
		ayahText: 'اِنَّهُمْ يَرَوْنَهٗ بَعِيْدًاۙ',
		ayahNumber: 6,
		translationId: 'Mereka memandang (azab) itu jauh (mustahil). ',
	),
	Ayah(
		ayahId: 5382,
		ayahText: 'وَّنَرٰىهُ قَرِيْبًاۗ',
		ayahNumber: 7,
		translationId: 'Sedangkan Kami memandangnya dekat (pasti terjadi). ',
	),
	Ayah(
		ayahId: 5383,
		ayahText: 'يَوْمَ تَكُوْنُ السَّمَاۤءُ كَالْمُهْلِۙ',
		ayahNumber: 8,
		translationId: '(Ingatlah) pada hari ketika langit men-jadi bagaikan cairan tembaga, ',
	),
	Ayah(
		ayahId: 5384,
		ayahText: 'وَتَكُوْنُ الْجِبَالُ كَالْعِهْنِۙ',
		ayahNumber: 9,
		translationId: 'dan gunung-gunung bagaikan bulu (yang beterbangan), ',
	),
	Ayah(
		ayahId: 5385,
		ayahText: 'وَلَا يَسْـَٔلُ حَمِيْمٌ حَمِيْمًاۚ ',
		ayahNumber: 10,
		translationId: 'dan tidak ada seorang teman karib pun menanyakan temannya,',
	),
	Ayah(
		ayahId: 5386,
		ayahText: 'يُبَصَّرُوْنَهُمْۗ يَوَدُّ الْمُجْرِمُ لَوْ يَفْتَدِيْ مِنْ عَذَابِ يَوْمِىِٕذٍۢ بِبَنِيْهِۙ',
		ayahNumber: 11,
		translationId: 'sedang mereka saling melihat. Pada hari itu, orang yang berdosa ingin sekiranya dia dapat menebus (dirinya) dari azab dengan anak-anaknya, ',
	),
	Ayah(
		ayahId: 5387,
		ayahText: 'وَصَاحِبَتِهٖ وَاَخِيْهِۙ',
		ayahNumber: 12,
		translationId: 'dan istrinya dan saudaranya, ',
	),
	Ayah(
		ayahId: 5388,
		ayahText: 'وَفَصِيْلَتِهِ الَّتِيْ تُـْٔوِيْهِۙ',
		ayahNumber: 13,
		translationId: 'dan keluarga yang melindunginya (di dunia),',
	),
	Ayah(
		ayahId: 5389,
		ayahText: 'وَمَنْ فِى الْاَرْضِ جَمِيْعًاۙ ثُمَّ يُنْجِيْهِۙ',
		ayahNumber: 14,
		translationId: 'dan orang-orang di bumi seluruhnya, kemudian mengharapkan (tebusan) itu dapat menyelamatkannya.',
	),
	Ayah(
		ayahId: 5390,
		ayahText: 'كَلَّاۗ اِنَّهَا لَظٰىۙ',
		ayahNumber: 15,
		translationId: 'Sama sekali tidak! Sungguh, neraka itu api yang bergejolak,',
	),
	Ayah(
		ayahId: 5391,
		ayahText: 'نَزَّاعَةً لِّلشَّوٰىۚ',
		ayahNumber: 16,
		translationId: 'yang mengelupaskan kulit kepala. ',
	),
	Ayah(
		ayahId: 5392,
		ayahText: 'تَدْعُوْا مَنْ اَدْبَرَ وَتَوَلّٰىۙ',
		ayahNumber: 17,
		translationId: 'Yang memanggil orang yang membelakangi dan yang berpaling (dari agama),',
	),
	Ayah(
		ayahId: 5393,
		ayahText: 'وَجَمَعَ فَاَوْعٰى ',
		ayahNumber: 18,
		translationId: 'dan orang yang mengumpulkan (harta benda) lalu menyimpannya. ',
	),
	Ayah(
		ayahId: 5394,
		ayahText: '۞ اِنَّ الْاِنْسَانَ خُلِقَ هَلُوْعًاۙ',
		ayahNumber: 19,
		translationId: 'Sungguh, manusia diciptakan bersifat suka mengeluh. ',
	),
	Ayah(
		ayahId: 5395,
		ayahText: 'اِذَا مَسَّهُ الشَّرُّ جَزُوْعًاۙ',
		ayahNumber: 20,
		translationId: 'Apabila dia ditimpa kesusahan dia berkeluh kesah, ',
	),
	Ayah(
		ayahId: 5396,
		ayahText: 'وَّاِذَا مَسَّهُ الْخَيْرُ مَنُوْعًاۙ',
		ayahNumber: 21,
		translationId: 'dan apabila mendapat kebaikan (harta) dia jadi kikir, ',
	),
	Ayah(
		ayahId: 5397,
		ayahText: 'اِلَّا الْمُصَلِّيْنَۙ',
		ayahNumber: 22,
		translationId: 'kecuali orang-orang yang melaksanakan salat, ',
	),
	Ayah(
		ayahId: 5398,
		ayahText: 'الَّذِيْنَ هُمْ عَلٰى صَلَاتِهِمْ دَاۤىِٕمُوْنَۖ',
		ayahNumber: 23,
		translationId: 'mereka yang tetap setia melaksanakan salatnya, ',
	),
	Ayah(
		ayahId: 5399,
		ayahText: 'وَالَّذِيْنَ فِيْٓ اَمْوَالِهِمْ حَقٌّ مَّعْلُوْمٌۖ',
		ayahNumber: 24,
		translationId: 'dan orang-orang yang dalam hartanya disiapkan bagian tertentu, ',
	),
	Ayah(
		ayahId: 5400,
		ayahText: 'لِّلسَّاۤىِٕلِ وَالْمَحْرُوْمِۖ',
		ayahNumber: 25,
		translationId: 'bagi orang (miskin) yang meminta dan yang tidak meminta, ',
	),
	Ayah(
		ayahId: 5401,
		ayahText: 'وَالَّذِيْنَ يُصَدِّقُوْنَ بِيَوْمِ الدِّيْنِۖ',
		ayahNumber: 26,
		translationId: 'dan orang-orang yang mempercayai hari pembalasan, ',
	),
	Ayah(
		ayahId: 5402,
		ayahText: 'وَالَّذِيْنَ هُمْ مِّنْ عَذَابِ رَبِّهِمْ مُّشْفِقُوْنَۚ',
		ayahNumber: 27,
		translationId: 'dan orang-orang yang takut terhadap azab Tuhannya, ',
	),
	Ayah(
		ayahId: 5403,
		ayahText: 'اِنَّ عَذَابَ رَبِّهِمْ غَيْرُ مَأْمُوْنٍۖ',
		ayahNumber: 28,
		translationId: 'sesungguhnya terhadap azab Tuhan mereka, tidak ada seseorang yang merasa aman (dari kedatangannya), ',
	),
	Ayah(
		ayahId: 5404,
		ayahText: 'وَّالَّذِيْنَ هُمْ لِفُرُوْجِهِمْ حٰفِظُوْنَۙ',
		ayahNumber: 29,
		translationId: 'dan orang-orang yang memelihara kemaluannya, ',
	),
	Ayah(
		ayahId: 5405,
		ayahText: 'اِلَّا عَلٰٓى اَزْوَاجِهِمْ اَوْ مَا مَلَكَتْ اَيْمَانُهُمْ فَاِنَّهُمْ غَيْرُ مَلُوْمِيْنَۚ',
		ayahNumber: 30,
		translationId: 'kecuali terhadap istri-istri mereka atau hamba sahaya yang mereka miliki maka sesungguhnya mereka tidak tercela. ',
	),
	Ayah(
		ayahId: 5406,
		ayahText: 'فَمَنِ ابْتَغٰى وَرَاۤءَ ذٰلِكَ فَاُولٰۤىِٕكَ هُمُ الْعٰدُوْنَۚ',
		ayahNumber: 31,
		translationId: 'Maka barangsiapa mencari di luar itu (seperti zina, homoseks dan lesbian), mereka itulah orang-orang yang melampaui batas. ',
	),
	Ayah(
		ayahId: 5407,
		ayahText: 'وَالَّذِيْنَ هُمْ لِاَمٰنٰتِهِمْ وَعَهْدِهِمْ رَاعُوْنَۖ',
		ayahNumber: 32,
		translationId: 'Dan orang-orang yang memelihara amanat dan janjinya, ',
	),
	Ayah(
		ayahId: 5408,
		ayahText: 'وَالَّذِيْنَ هُمْ بِشَهٰدٰتِهِمْ قَاۤىِٕمُوْنَۖ',
		ayahNumber: 33,
		translationId: 'dan orang-orang yang berpegang teguh pada kesaksiannya, ',
	),
	Ayah(
		ayahId: 5409,
		ayahText: 'وَالَّذِيْنَ هُمْ عَلٰى صَلَاتِهِمْ يُحَافِظُوْنَۖ',
		ayahNumber: 34,
		translationId: 'dan orang-orang yang memelihara salatnya.',
	),
	Ayah(
		ayahId: 5410,
		ayahText: 'اُولٰۤىِٕكَ فِيْ جَنّٰتٍ مُّكْرَمُوْنَ ۗ ࣖ',
		ayahNumber: 35,
		translationId: 'Mereka itu dimuliakan di dalam surga. ',
	),
	Ayah(
		ayahId: 5411,
		ayahText: 'فَمَالِ الَّذِيْنَ كَفَرُوْا قِبَلَكَ مُهْطِعِيْنَۙ',
		ayahNumber: 36,
		translationId: 'Maka mengapa orang-orang kafir itu datang bergegas ke hadapanmu (Muhammad), ',
	),
	Ayah(
		ayahId: 5412,
		ayahText: 'عَنِ الْيَمِيْنِ وَعَنِ الشِّمَالِ عِزِيْنَ ',
		ayahNumber: 37,
		translationId: 'dari kanan dan dari kiri dengan berkelompok-kelompok?',
	),
	Ayah(
		ayahId: 5413,
		ayahText: 'اَيَطْمَعُ كُلُّ امْرِئٍ مِّنْهُمْ اَنْ يُّدْخَلَ جَنَّةَ نَعِيْمٍۙ',
		ayahNumber: 38,
		translationId: 'Apakah setiap orang dari orang-orang kafir itu ingin masuk surga yang penuh kenikmatan?',
	),
	Ayah(
		ayahId: 5414,
		ayahText: 'كَلَّاۗ اِنَّا خَلَقْنٰهُمْ مِّمَّا يَعْلَمُوْنَ ',
		ayahNumber: 39,
		translationId: 'Tidak mungkin! Sesungguhnya Kami menciptakan mereka dari apa yang mereka ketahui.',
	),
	Ayah(
		ayahId: 5415,
		ayahText: 'فَلَآ اُقْسِمُ بِرَبِّ الْمَشَارِقِ وَالْمَغٰرِبِ اِنَّا لَقٰدِرُوْنَۙ',
		ayahNumber: 40,
		translationId: 'Maka Aku bersumpah demi Tuhan yang mengatur tempat-tempat terbit dan terbenamnya  (matahari, bulan dan bintang), sungguh, Kami pasti mampu, ',
	),
	Ayah(
		ayahId: 5416,
		ayahText: 'عَلٰٓى اَنْ نُّبَدِّلَ خَيْرًا مِّنْهُمْۙ وَمَا نَحْنُ بِمَسْبُوْقِيْنَ ',
		ayahNumber: 41,
		translationId: 'untuk mengganti (mereka) dengan kaum yang lebih baik dari mereka, dan Kami tidak dapat dikalahkan. ',
	),
	Ayah(
		ayahId: 5417,
		ayahText: 'فَذَرْهُمْ يَخُوْضُوْا وَيَلْعَبُوْا حَتّٰى يُلٰقُوْا يَوْمَهُمُ الَّذِيْ يُوْعَدُوْنَۙ',
		ayahNumber: 42,
		translationId: 'Maka biarkanlah mereka tenggelam dan bermain-main (dalam kesesatan) sampai mereka menjumpai hari yang diancamkan kepada mereka, ',
	),
	Ayah(
		ayahId: 5418,
		ayahText: 'يَوْمَ يَخْرُجُوْنَ مِنَ الْاَجْدَاثِ سِرَاعًا كَاَنَّهُمْ اِلٰى نُصُبٍ يُّوْفِضُوْنَۙ',
		ayahNumber: 43,
		translationId: '(yaitu) pada hari ketika mereka keluar dari kubur dengan cepat seakan-akan mereka pergi dengan segera kepada berhala-berhala (sewaktu di dunia),',
	),
	Ayah(
		ayahId: 5419,
		ayahText: 'خَاشِعَةً اَبْصَارُهُمْ تَرْهَقُهُمْ ذِلَّةٌ  ۗذٰلِكَ الْيَوْمُ الَّذِيْ كَانُوْا يُوْعَدُوْنَ ࣖ ',
		ayahNumber: 44,
		translationId: 'pandangan mereka tertunduk ke bawah diliputi kehinaan. Itulah hari yang diancamkan kepada mereka.',
	),
];
