// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah81 = [
	Ayah(
		ayahId: 5801,
		ayahText: 'اِذَا الشَّمْسُ كُوِّرَتْۖ',
		ayahNumber: 1,
		translationId: 'Apabila matahari digulung,',
	),
	Ayah(
		ayahId: 5802,
		ayahText: 'وَاِذَا النُّجُوْمُ انْكَدَرَتْۖ',
		ayahNumber: 2,
		translationId: 'dan apabila bintang-bintang berjatuhan,',
	),
	Ayah(
		ayahId: 5803,
		ayahText: 'وَاِذَا الْجِبَالُ سُيِّرَتْۖ',
		ayahNumber: 3,
		translationId: 'dan apabila gunung-gunung dihancurkan,',
	),
	Ayah(
		ayahId: 5804,
		ayahText: 'وَاِذَا الْعِشَارُ عُطِّلَتْۖ',
		ayahNumber: 4,
		translationId: 'dan apabila unta-unta yang bunting ditinggalkan (tidak terurus),',
	),
	Ayah(
		ayahId: 5805,
		ayahText: 'وَاِذَا الْوُحُوْشُ حُشِرَتْۖ',
		ayahNumber: 5,
		translationId: 'dan apabila binatang-binatang liar dikumpulkan,',
	),
	Ayah(
		ayahId: 5806,
		ayahText: 'وَاِذَا الْبِحَارُ سُجِّرَتْۖ',
		ayahNumber: 6,
		translationId: 'dan apabila lautan dipanaskan,',
	),
	Ayah(
		ayahId: 5807,
		ayahText: 'وَاِذَا النُّفُوْسُ زُوِّجَتْۖ',
		ayahNumber: 7,
		translationId: 'dan apabila roh-roh dipertemukan (dengan tubuh), ',
	),
	Ayah(
		ayahId: 5808,
		ayahText: 'وَاِذَا الْمَوْءٗدَةُ سُىِٕلَتْۖ ',
		ayahNumber: 8,
		translationId: 'dan apabila bayi-bayi perempuan yang dikubur hidup-hidup ditanya, ',
	),
	Ayah(
		ayahId: 5809,
		ayahText: 'بِاَيِّ ذَنْۢبٍ قُتِلَتْۚ',
		ayahNumber: 9,
		translationId: 'karena dosa apa dia dibunuh? ',
	),
	Ayah(
		ayahId: 5810,
		ayahText: 'وَاِذَا الصُّحُفُ نُشِرَتْۖ',
		ayahNumber: 10,
		translationId: 'Dan apabila lembaran-lembaran (catatan amal) telah dibuka lebar-lebar, ',
	),
	Ayah(
		ayahId: 5811,
		ayahText: 'وَاِذَا السَّمَاۤءُ كُشِطَتْۖ',
		ayahNumber: 11,
		translationId: 'dan apabila langit dilenyapkan, ',
	),
	Ayah(
		ayahId: 5812,
		ayahText: 'وَاِذَا الْجَحِيْمُ سُعِّرَتْۖ',
		ayahNumber: 12,
		translationId: 'dan apabila neraka Jahim dinyalakan, ',
	),
	Ayah(
		ayahId: 5813,
		ayahText: 'وَاِذَا الْجَنَّةُ اُزْلِفَتْۖ',
		ayahNumber: 13,
		translationId: 'dan apabila surga didekatkan, ',
	),
	Ayah(
		ayahId: 5814,
		ayahText: 'عَلِمَتْ نَفْسٌ مَّآ اَحْضَرَتْۗ',
		ayahNumber: 14,
		translationId: 'setiap jiwa akan mengetahui apa yang telah dikerjakannya. ',
	),
	Ayah(
		ayahId: 5815,
		ayahText: 'فَلَآ اُقْسِمُ بِالْخُنَّسِۙ',
		ayahNumber: 15,
		translationId: 'Aku bersumpah demi bintang-bintang,',
	),
	Ayah(
		ayahId: 5816,
		ayahText: 'الْجَوَارِ الْكُنَّسِۙ',
		ayahNumber: 16,
		translationId: 'yang beredar dan terbenam, ',
	),
	Ayah(
		ayahId: 5817,
		ayahText: 'وَالَّيْلِ اِذَا عَسْعَسَۙ',
		ayahNumber: 17,
		translationId: 'demi malam apabila telah larut, ',
	),
	Ayah(
		ayahId: 5818,
		ayahText: 'وَالصُّبْحِ اِذَا تَنَفَّسَۙ',
		ayahNumber: 18,
		translationId: 'dan demi subuh apabila fajar telah menyingsing, ',
	),
	Ayah(
		ayahId: 5819,
		ayahText: 'اِنَّهٗ لَقَوْلُ رَسُوْلٍ كَرِيْمٍۙ',
		ayahNumber: 19,
		translationId: "sesungguhnya (Al-Qur'an) itu benar-benar firman (Allah yang dibawa oleh) utusan yang mulia (Jibril),",
	),
	Ayah(
		ayahId: 5820,
		ayahText: 'ذِيْ قُوَّةٍ عِنْدَ ذِى الْعَرْشِ مَكِيْنٍۙ',
		ayahNumber: 20,
		translationId: 'yang memiliki kekuatan, memiliki kedudukan tinggi di sisi (Allah) yang memiliki ‘Arsy,',
	),
	Ayah(
		ayahId: 5821,
		ayahText: 'مُّطَاعٍ ثَمَّ اَمِيْنٍۗ',
		ayahNumber: 21,
		translationId: 'yang di sana (di alam malaikat) ditaati dan dipercaya.',
	),
	Ayah(
		ayahId: 5822,
		ayahText: 'وَمَا صَاحِبُكُمْ بِمَجْنُوْنٍۚ',
		ayahNumber: 22,
		translationId: 'Dan temanmu (Muhammad) itu bukanlah orang gila. ',
	),
	Ayah(
		ayahId: 5823,
		ayahText: 'وَلَقَدْ رَاٰهُ بِالْاُفُقِ الْمُبِيْنِۚ',
		ayahNumber: 23,
		translationId: 'Dan sungguh, dia (Muhammad) telah melihatnya (Jibril) di ufuk yang terang. ',
	),
	Ayah(
		ayahId: 5824,
		ayahText: 'وَمَا هُوَ عَلَى الْغَيْبِ بِضَنِيْنٍۚ',
		ayahNumber: 24,
		translationId: 'Dan dia (Muhammad) bukanlah seorang yang kikir (enggan) untuk menerangkan yang gaib.',
	),
	Ayah(
		ayahId: 5825,
		ayahText: 'وَمَا هُوَ بِقَوْلِ شَيْطٰنٍ رَّجِيْمٍۚ',
		ayahNumber: 25,
		translationId: "Dan (Al-Qur'an) itu bukanlah perkataan setan yang terkutuk,",
	),
	Ayah(
		ayahId: 5826,
		ayahText: 'فَاَيْنَ تَذْهَبُوْنَۗ',
		ayahNumber: 26,
		translationId: 'maka ke manakah kamu akan pergi?',
	),
	Ayah(
		ayahId: 5827,
		ayahText: 'اِنْ هُوَ اِلَّا ذِكْرٌ لِّلْعٰلَمِيْنَۙ',
		ayahNumber: 27,
		translationId: "(Al-Qur'an) itu tidak lain adalah peringatan bagi seluruh alam, ",
	),
	Ayah(
		ayahId: 5828,
		ayahText: 'لِمَنْ شَاۤءَ مِنْكُمْ اَنْ يَّسْتَقِيْمَۗ',
		ayahNumber: 28,
		translationId: '(yaitu) bagi siapa di antara kamu yang menghendaki menempuh jalan yang lurus. ',
	),
	Ayah(
		ayahId: 5829,
		ayahText: 'وَمَا تَشَاۤءُوْنَ اِلَّآ اَنْ يَّشَاۤءَ اللّٰهُ رَبُّ الْعٰلَمِيْنَ ࣖ',
		ayahNumber: 29,
		translationId: 'Dan kamu tidak dapat menghendaki (menempuh jalan itu) kecuali apabila dikehendaki Allah, Tuhan seluruh alam.',
	),
];
