// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah17 = [
	Ayah(
		ayahId: 2030,
		ayahText: 'سُبْحٰنَ الَّذِيْٓ اَسْرٰى بِعَبْدِهٖ لَيْلًا مِّنَ الْمَسْجِدِ الْحَرَامِ اِلَى الْمَسْجِدِ الْاَقْصَا الَّذِيْ بٰرَكْنَا حَوْلَهٗ لِنُرِيَهٗ مِنْ اٰيٰتِنَاۗ اِنَّهٗ هُوَ السَّمِيْعُ الْبَصِيْرُ',
		ayahNumber: 1,
		translationId: 'Mahasuci (Allah), yang telah memperjalankan hamba-Nya (Muhammad) pada malam hari dari Masjidilharam ke Masjidil Aqsa yang telah Kami berkahi sekelilingnya agar Kami perlihatkan kepadanya sebagian tanda-tanda (kebesaran) Kami. Sesungguhnya Dia Maha Mendengar, Maha Melihat.',
	),
	Ayah(
		ayahId: 2031,
		ayahText: 'وَاٰتَيْنَا مُوْسَى الْكِتٰبَ وَجَعَلْنٰهُ هُدًى لِّبَنِيْٓ اِسْرَاۤءِيْلَ اَلَّا تَتَّخِذُوْا مِنْ دُوْنِيْ وَكِيْلًاۗ ',
		ayahNumber: 2,
		translationId: 'Dan Kami berikan kepada Musa, Kitab (Taurat) dan Kami jadikannya petunjuk bagi Bani Israil (dengan firman), “Janganlah kamu mengambil (pelindung) selain Aku. ',
	),
	Ayah(
		ayahId: 2032,
		ayahText: 'ذُرِّيَّةَ مَنْ حَمَلْنَا مَعَ نُوْحٍۗ اِنَّهٗ كَانَ عَبْدًا شَكُوْرًا',
		ayahNumber: 3,
		translationId: '(Wahai) keturunan orang yang Kami bawa bersama Nuh. Sesungguhnya dia (Nuh) adalah hamba (Allah) yang banyak bersyukur.”',
	),
	Ayah(
		ayahId: 2033,
		ayahText: 'وَقَضَيْنَآ اِلٰى بَنِيْٓ اِسْرَاۤءِيْلَ فِى الْكِتٰبِ لَتُفْسِدُنَّ فِى الْاَرْضِ مَرَّتَيْنِ وَلَتَعْلُنَّ عُلُوًّا كَبِيْرًا',
		ayahNumber: 4,
		translationId: 'Dan Kami tetapkan terhadap Bani Israil dalam Kitab itu, “Kamu pasti akan berbuat kerusakan di bumi ini dua kali dan pasti kamu akan menyombongkan diri dengan kesombongan yang besar.”',
	),
	Ayah(
		ayahId: 2034,
		ayahText: 'فَاِذَا جَاۤءَ وَعْدُ اُوْلٰىهُمَا بَعَثْنَا عَلَيْكُمْ عِبَادًا لَّنَآ اُولِيْ بَأْسٍ شَدِيْدٍ فَجَاسُوْا خِلٰلَ الدِّيَارِۗ وَكَانَ وَعْدًا مَّفْعُوْلًا',
		ayahNumber: 5,
		translationId: 'Maka apabila datang saat hukuman bagi (kejahatan) yang pertama dari kedua (kejahatan) itu, Kami datangkan kepadamu hamba-hamba Kami yang perkasa, lalu mereka merajalela di kampung-kampung. Dan itulah ketetapan yang pasti terlaksana.',
	),
	Ayah(
		ayahId: 2035,
		ayahText: 'ثُمَّ رَدَدْنَا لَكُمُ الْكَرَّةَ عَلَيْهِمْ وَاَمْدَدْنٰكُمْ بِاَمْوَالٍ وَّبَنِيْنَ وَجَعَلْنٰكُمْ اَكْثَرَ نَفِيْرًا',
		ayahNumber: 6,
		translationId: 'Kemudian Kami berikan kepadamu giliran untuk mengalahkan mereka, Kami membantumu dengan harta kekayaan dan anak-anak dan Kami jadikan kamu kelompok yang lebih besar.',
	),
	Ayah(
		ayahId: 2036,
		ayahText: 'اِنْ اَحْسَنْتُمْ اَحْسَنْتُمْ لِاَنْفُسِكُمْ ۗوَاِنْ اَسَأْتُمْ فَلَهَاۗ فَاِذَا جَاۤءَ وَعْدُ الْاٰخِرَةِ لِيَسٗۤـُٔوْا وُجُوْهَكُمْ وَلِيَدْخُلُوا الْمَسْجِدَ كَمَا دَخَلُوْهُ اَوَّلَ مَرَّةٍ وَّلِيُتَبِّرُوْا مَا عَلَوْا تَتْبِيْرًا',
		ayahNumber: 7,
		translationId: 'Jika kamu berbuat baik (berarti) kamu berbuat baik untuk dirimu sendiri. Dan jika kamu berbuat jahat, maka (kerugian kejahatan) itu untuk dirimu sendiri. Apabila datang saat hukuman (kejahatan) yang kedua, (Kami bangkitkan musuhmu) untuk menyuramkan wajahmu lalu mereka masuk ke dalam masjid (Masjidil Aqsa), sebagaimana ketika mereka memasukinya pertama kali dan mereka membinasakan apa saja yang mereka kuasai.',
	),
	Ayah(
		ayahId: 2037,
		ayahText: 'عَسٰى رَبُّكُمْ اَنْ يَّرْحَمَكُمْۚ وَاِنْ عُدْتُّمْ عُدْنَاۘ وَجَعَلْنَا جَهَنَّمَ لِلْكٰفِرِيْنَ حَصِيْرًا ',
		ayahNumber: 8,
		translationId: 'Mudah-mudahan Tuhan kamu melimpahkan rahmat kepada kamu; tetapi jika kamu kembali (melakukan kejahatan), niscaya Kami kembali (mengazabmu). Dan Kami jadikan neraka Jahanam penjara bagi orang kafir.',
	),
	Ayah(
		ayahId: 2038,
		ayahText: 'اِنَّ هٰذَا الْقُرْاٰنَ يَهْدِيْ لِلَّتِيْ هِيَ اَقْوَمُ وَيُبَشِّرُ الْمُؤْمِنِيْنَ الَّذِيْنَ يَعْمَلُوْنَ الصّٰلِحٰتِ اَنَّ لَهُمْ اَجْرًا كَبِيْرًاۙ  ',
		ayahNumber: 9,
		translationId: "Sungguh, Al-Qur'an ini memberi petunjuk ke (jalan) yang paling lurus dan memberi kabar gembira kepada orang mukmin yang mengerjakan kebajikan, bahwa mereka akan mendapat pahala yang besar,",
	),
	Ayah(
		ayahId: 2039,
		ayahText: 'وَّاَنَّ الَّذِيْنَ لَا يُؤْمِنُوْنَ بِالْاٰخِرَةِ اَعْتَدْنَا لَهُمْ عَذَابًا اَلِيْمًا ࣖ',
		ayahNumber: 10,
		translationId: 'dan bahwa orang yang tidak beriman kepada kehidupan akhirat, Kami sediakan bagi mereka azab yang pedih.',
	),
	Ayah(
		ayahId: 2040,
		ayahText: 'وَيَدْعُ الْاِنْسَانُ بِالشَّرِّ دُعَاۤءَهٗ بِالْخَيْرِۗ وَكَانَ الْاِنْسَانُ عَجُوْلًا  ',
		ayahNumber: 11,
		translationId: 'Dan Manusia (seringkali) berdoa untuk kejahatan sebagaimana (biasanya) dia berdoa untuk kebaikan. Dan memang manusia bersifat tergesa-gesa.',
	),
	Ayah(
		ayahId: 2041,
		ayahText: 'وَجَعَلْنَا الَّيْلَ وَالنَّهَارَ اٰيَتَيْنِ فَمَحَوْنَآ اٰيَةَ الَّيْلِ وَجَعَلْنَآ اٰيَةَ النَّهَارِ مُبْصِرَةً لِّتَبْتَغُوْا فَضْلًا مِّنْ رَّبِّكُمْ وَلِتَعْلَمُوْا عَدَدَ السِّنِيْنَ وَالْحِسَابَۗ وَكُلَّ شَيْءٍ فَصَّلْنٰهُ تَفْصِيْلًا',
		ayahNumber: 12,
		translationId: 'Dan Kami jadikan malam dan siang sebagai dua tanda (kebesaran Kami), kemudian Kami hapuskan tanda malam dan Kami jadikan tanda siang itu terang benderang, agar kamu (dapat) mencari karunia dari Tuhanmu, dan agar kamu mengetahui bilangan tahun dan perhitungan (waktu). Dan segala sesuatu telah Kami terangkan dengan jelas.',
	),
	Ayah(
		ayahId: 2042,
		ayahText: 'وَكُلَّ اِنْسَانٍ اَلْزَمْنٰهُ طٰۤىِٕرَهٗ فِيْ عُنُقِهٖۗ وَنُخْرِجُ لَهٗ يَوْمَ الْقِيٰمَةِ كِتٰبًا يَّلْقٰىهُ مَنْشُوْرًا',
		ayahNumber: 13,
		translationId: 'Dan setiap manusia telah Kami kalungkan (catatan) amal perbuatannya di lehernya. Dan pada hari Kiamat Kami keluarkan baginya sebuah kitab dalam keadaan terbuka. ',
	),
	Ayah(
		ayahId: 2043,
		ayahText: 'اِقْرَأْ كِتَابَكَۗ  كَفٰى بِنَفْسِكَ الْيَوْمَ عَلَيْكَ حَسِيْبًاۗ',
		ayahNumber: 14,
		translationId: '“Bacalah kitabmu, cukuplah dirimu sendiri pada hari ini sebagai penghitung atas dirimu.”',
	),
	Ayah(
		ayahId: 2044,
		ayahText: 'مَنِ اهْتَدٰى فَاِنَّمَا يَهْتَدِيْ لِنَفْسِهٖۚ وَمَنْ ضَلَّ فَاِنَّمَا يَضِلُّ عَلَيْهَاۗ وَلَا تَزِرُ وَازِرَةٌ وِّزْرَ اُخْرٰىۗ وَمَا كُنَّا مُعَذِّبِيْنَ حَتّٰى نَبْعَثَ رَسُوْلًا',
		ayahNumber: 15,
		translationId: 'Barangsiapa berbuat sesuai dengan petunjuk (Allah), maka sesungguhnya itu untuk (keselamatan) dirinya sendiri; dan barang siapa tersesat maka sesungguhnya (kerugian) itu bagi dirinya sendiri. Dan seorang yang berdosa tidak dapat memikul dosa orang lain, tetapi Kami tidak akan menyiksa sebelum Kami mengutus seorang rasul.',
	),
	Ayah(
		ayahId: 2045,
		ayahText: 'وَاِذَآ اَرَدْنَآ اَنْ نُّهْلِكَ قَرْيَةً اَمَرْنَا مُتْرَفِيْهَا فَفَسَقُوْا فِيْهَا فَحَقَّ عَلَيْهَا الْقَوْلُ فَدَمَّرْنٰهَا تَدْمِيْرًا ',
		ayahNumber: 16,
		translationId: 'Dan jika Kami hendak membinasakan suatu negeri, maka Kami perintahkan kepada orang yang hidup mewah di negeri itu (agar menaati Allah), tetapi bila mereka melakukan kedurhakaan di dalam (negeri) itu, maka sepantasnya berlakulah terhadapnya perkataan (hukuman Kami), kemudian Kami binasakan sama sekali (negeri itu).',
	),
	Ayah(
		ayahId: 2046,
		ayahText: 'وَكَمْ اَهْلَكْنَا مِنَ الْقُرُوْنِ مِنْۢ بَعْدِ نُوْحٍۗ وَكَفٰى بِرَبِّكَ بِذُنُوْبِ عِبَادِهٖ خَبِيْرًاۢ بَصِيْرًا',
		ayahNumber: 17,
		translationId: 'Dan berapa banyak kaum setelah Nuh, yang telah Kami binasakan. Dan cukuplah Tuhanmu Yang Maha Mengetahui, Maha Melihat dosa hamba-hamba-Nya.',
	),
	Ayah(
		ayahId: 2047,
		ayahText: 'مَنْ كَانَ يُرِيْدُ الْعَاجِلَةَ عَجَّلْنَا لَهٗ فِيْهَا مَا نَشَاۤءُ لِمَنْ نُّرِيْدُ ثُمَّ جَعَلْنَا لَهٗ جَهَنَّمَۚ يَصْلٰىهَا مَذْمُوْمًا مَّدْحُوْرًا',
		ayahNumber: 18,
		translationId: 'Barangsiapa menghendaki kehidupan sekarang (duniawi), maka Kami segerakan baginya di (dunia) ini apa yang Kami kehendaki bagi orang yang Kami kehendaki. Kemudian Kami sediakan baginya (di akhirat) neraka Jahanam; dia akan memasukinya dalam keadaan tercela dan terusir.',
	),
	Ayah(
		ayahId: 2048,
		ayahText: 'وَمَنْ اَرَادَ الْاٰخِرَةَ وَسَعٰى لَهَا سَعْيَهَا وَهُوَ مُؤْمِنٌ فَاُولٰۤىِٕكَ كَانَ سَعْيُهُمْ مَّشْكُوْرًا',
		ayahNumber: 19,
		translationId: 'Dan barang siapa menghendaki kehidupan akhirat dan berusaha ke arah itu dengan sungguh-sungguh, sedangkan dia beriman, maka mereka itulah orang yang usahanya dibalas dengan baik.',
	),
	Ayah(
		ayahId: 2049,
		ayahText: 'كُلًّا نُّمِدُّ هٰٓؤُلَاۤءِ وَهٰٓؤُلَاۤءِ مِنْ عَطَاۤءِ رَبِّكَ ۗوَمَا كَانَ عَطَاۤءُ رَبِّكَ مَحْظُوْرًا ',
		ayahNumber: 20,
		translationId: 'Kepada masing-masing (golongan), baik (golongan) ini (yang menginginkan dunia) maupun (golongan) itu (yang menginginkan akhirat), Kami berikan bantuan dari kemurahan Tuhanmu. Dan kemurahan Tuhanmu tidak dapat dihalangi.',
	),
	Ayah(
		ayahId: 2050,
		ayahText: 'اُنْظُرْ كَيْفَ فَضَّلْنَا بَعْضَهُمْ عَلٰى بَعْضٍۗ وَلَلْاٰخِرَةُ اَكْبَرُ دَرَجٰتٍ وَّاَكْبَرُ تَفْضِيْلًا',
		ayahNumber: 21,
		translationId: 'Perhatikanlah bagaimana Kami melebihkan sebagian mereka atas sebagian (yang lain). Dan kehidupan akhirat lebih tinggi derajatnya dan lebih besar keutamaan.',
	),
	Ayah(
		ayahId: 2051,
		ayahText: 'لَا تَجْعَلْ مَعَ اللّٰهِ اِلٰهًا اٰخَرَ فَتَقْعُدَ مَذْمُوْمًا مَّخْذُوْلًا ࣖ ',
		ayahNumber: 22,
		translationId: 'Janganlah engkau mengadakan tuhan yang lain di samping Allah, nanti engkau menjadi tercela dan terhina.',
	),
	Ayah(
		ayahId: 2052,
		ayahText: '۞ وَقَضٰى رَبُّكَ اَلَّا تَعْبُدُوْٓا اِلَّآ اِيَّاهُ وَبِالْوَالِدَيْنِ اِحْسٰنًاۗ اِمَّا يَبْلُغَنَّ عِنْدَكَ الْكِبَرَ اَحَدُهُمَآ اَوْ كِلٰهُمَا فَلَا تَقُلْ لَّهُمَآ اُفٍّ وَّلَا تَنْهَرْهُمَا وَقُلْ لَّهُمَا قَوْلًا كَرِيْمًا',
		ayahNumber: 23,
		translationId: 'Dan Tuhanmu telah memerintahkan agar kamu jangan menyembah selain Dia dan hendaklah berbuat baik kepada ibu bapak. Jika salah seorang di antara keduanya atau kedua-duanya sampai berusia lanjut dalam pemeliharaanmu, maka sekali-kali janganlah engkau mengatakan kepada keduanya perkataan “ah” dan janganlah engkau membentak keduanya, dan ucapkanlah kepada keduanya perkataan yang baik.',
	),
	Ayah(
		ayahId: 2053,
		ayahText: 'وَاخْفِضْ لَهُمَا جَنَاحَ الذُّلِّ مِنَ الرَّحْمَةِ وَقُلْ رَّبِّ ارْحَمْهُمَا كَمَا رَبَّيٰنِيْ صَغِيْرًاۗ',
		ayahNumber: 24,
		translationId: 'Dan rendahkanlah dirimu terhadap keduanya dengan penuh kasih sayang dan ucapkanlah, “Wahai Tuhanku! Sayangilah keduanya sebagaimana mereka berdua telah mendidik aku pada waktu kecil.”',
	),
	Ayah(
		ayahId: 2054,
		ayahText: 'رَبُّكُمْ اَعْلَمُ بِمَا فِيْ نُفُوْسِكُمْ ۗاِنْ تَكُوْنُوْا صٰلِحِيْنَ فَاِنَّهٗ كَانَ لِلْاَوَّابِيْنَ غَفُوْرًا',
		ayahNumber: 25,
		translationId: 'Tuhanmu lebih mengetahui apa yang ada dalam hatimu; jika kamu orang yang baik, maka sungguh, Dia Maha Pengampun kepada orang yang bertobat.',
	),
	Ayah(
		ayahId: 2055,
		ayahText: 'وَاٰتِ ذَا الْقُرْبٰى حَقَّهٗ وَالْمِسْكِيْنَ وَابْنَ السَّبِيْلِ وَلَا تُبَذِّرْ تَبْذِيْرًا ',
		ayahNumber: 26,
		translationId: 'Dan berikanlah haknya kepada kerabat dekat, juga kepada orang miskin dan orang yang dalam perjalanan; dan janganlah kamu menghambur-hamburkan (hartamu) secara boros.',
	),
	Ayah(
		ayahId: 2056,
		ayahText: 'اِنَّ الْمُبَذِّرِيْنَ كَانُوْٓا اِخْوَانَ الشَّيٰطِيْنِ ۗوَكَانَ الشَّيْطٰنُ لِرَبِّهٖ كَفُوْرًا',
		ayahNumber: 27,
		translationId: 'Sesungguhnya orang-orang yang pemboros itu adalah saudara setan dan setan itu sangat ingkar kepada Tuhannya.',
	),
	Ayah(
		ayahId: 2057,
		ayahText: 'وَاِمَّا تُعْرِضَنَّ عَنْهُمُ ابْتِغَاۤءَ رَحْمَةٍ مِّنْ رَّبِّكَ تَرْجُوْهَا فَقُلْ لَّهُمْ قَوْلًا مَّيْسُوْرًا',
		ayahNumber: 28,
		translationId: 'Dan jika engkau berpaling dari mereka untuk memperoleh rahmat dari Tuhanmu yang engkau harapkan, maka katakanlah kepada mereka ucapan yang lemah lembut.',
	),
	Ayah(
		ayahId: 2058,
		ayahText: 'وَلَا تَجْعَلْ يَدَكَ مَغْلُوْلَةً اِلٰى عُنُقِكَ وَلَا تَبْسُطْهَا كُلَّ الْبَسْطِ فَتَقْعُدَ مَلُوْمًا مَّحْسُوْرًا ',
		ayahNumber: 29,
		translationId: 'Dan janganlah engkau jadikan tanganmu terbelenggu pada lehermu dan jangan (pula) engkau terlalu mengulurkannya (sangat pemurah) nanti kamu menjadi tercela dan menyesal.',
	),
	Ayah(
		ayahId: 2059,
		ayahText: 'اِنَّ رَبَّكَ يَبْسُطُ الرِّزْقَ لِمَنْ يَّشَاۤءُ وَيَقْدِرُ ۗاِنَّهٗ كَانَ بِعِبَادِهٖ خَبِيْرًاۢ بَصِيْرًا ࣖ',
		ayahNumber: 30,
		translationId: 'Sungguh, Tuhanmu melapangkan rezeki bagi siapa yang Dia kehendaki dan membatasi (bagi siapa yang Dia kehendaki); sungguh, Dia Maha Mengetahui, Maha Melihat hamba-hamba-Nya.',
	),
	Ayah(
		ayahId: 2060,
		ayahText: 'وَلَا تَقْتُلُوْٓا اَوْلَادَكُمْ خَشْيَةَ اِمْلَاقٍۗ نَحْنُ نَرْزُقُهُمْ وَاِيَّاكُمْۗ اِنَّ قَتْلَهُمْ كَانَ خِطْـًٔا كَبِيْرًا ',
		ayahNumber: 31,
		translationId: 'Dan janganlah kamu membunuh anak-anakmu karena takut miskin. Kamilah yang memberi rezeki kepada mereka dan kepadamu. Membunuh mereka itu sungguh suatu dosa yang besar.',
	),
	Ayah(
		ayahId: 2061,
		ayahText: 'وَلَا تَقْرَبُوا الزِّنٰىٓ اِنَّهٗ كَانَ فَاحِشَةً ۗوَسَاۤءَ سَبِيْلًا ',
		ayahNumber: 32,
		translationId: 'Dan janganlah kamu mendekati zina; (zina) itu sungguh suatu perbuatan keji, dan suatu jalan yang buruk.',
	),
	Ayah(
		ayahId: 2062,
		ayahText: 'وَلَا تَقْتُلُوا النَّفْسَ الَّتِيْ حَرَّمَ اللّٰهُ اِلَّا بِالْحَقِّۗ وَمَنْ قُتِلَ مَظْلُوْمًا فَقَدْ جَعَلْنَا لِوَلِيِّهٖ سُلْطٰنًا فَلَا يُسْرِفْ فِّى الْقَتْلِۗ اِنَّهٗ كَانَ مَنْصُوْرًا',
		ayahNumber: 33,
		translationId: 'Dan janganlah kamu membunuh orang yang diharamkan Allah (membunuhnya), kecuali dengan suatu (alasan) yang benar. Dan barang siapa dibunuh secara zalim, maka sungguh, Kami telah memberi kekuasaan kepada walinya, tetapi janganlah walinya itu melampaui batas dalam pembunuhan. Sesungguhnya dia adalah orang yang mendapat pertolongan.',
	),
	Ayah(
		ayahId: 2063,
		ayahText: 'وَلَا تَقْرَبُوْا مَالَ الْيَتِيْمِ اِلَّا بِالَّتِيْ هِيَ اَحْسَنُ حَتّٰى يَبْلُغَ اَشُدَّهٗۖ وَاَوْفُوْا بِالْعَهْدِۖ اِنَّ الْعَهْدَ كَانَ مَسْـُٔوْلًا',
		ayahNumber: 34,
		translationId: 'Dan janganlah kamu mendekati harta anak yatim, kecuali dengan cara yang lebih baik (bermanfaat) sampai dia dewasa, dan penuhilah janji, karena janji itu pasti diminta pertanggungjawabannya.',
	),
	Ayah(
		ayahId: 2064,
		ayahText: 'وَاَوْفُوا الْكَيْلَ اِذَا كِلْتُمْ وَزِنُوْا بِالْقِسْطَاسِ الْمُسْتَقِيْمِۗ ذٰلِكَ خَيْرٌ وَّاَحْسَنُ تَأْوِيْلًا',
		ayahNumber: 35,
		translationId: 'Dan sempurnakanlah takaran apabila kamu menakar, dan timbanglah dengan timbangan yang benar. Itulah yang lebih utama (bagimu) dan lebih baik akibatnya.',
	),
	Ayah(
		ayahId: 2065,
		ayahText: 'وَلَا تَقْفُ مَا لَيْسَ لَكَ بِهٖ عِلْمٌ ۗاِنَّ السَّمْعَ وَالْبَصَرَ وَالْفُؤَادَ كُلُّ اُولٰۤىِٕكَ كَانَ عَنْهُ مَسْـُٔوْلًا ',
		ayahNumber: 36,
		translationId: 'Dan janganlah kamu mengikuti sesuatu yang tidak kamu ketahui. Karena pendengaran, penglihatan dan hati nurani, semua itu akan diminta pertanggungjawabannya.',
	),
	Ayah(
		ayahId: 2066,
		ayahText: 'وَلَا تَمْشِ فِى الْاَرْضِ مَرَحًاۚ اِنَّكَ لَنْ تَخْرِقَ الْاَرْضَ وَلَنْ تَبْلُغَ الْجِبَالَ طُوْلًا',
		ayahNumber: 37,
		translationId: 'Dan janganlah engkau berjalan di bumi ini dengan sombong, karena sesungguhnya engkau tidak akan dapat menembus bumi dan tidak akan mampu menjulang setinggi gunung.',
	),
	Ayah(
		ayahId: 2067,
		ayahText: 'كُلُّ ذٰلِكَ كَانَ سَيِّئُهٗ عِنْدَ رَبِّكَ مَكْرُوْهًا ',
		ayahNumber: 38,
		translationId: 'Semua itu kejahatannya sangat dibenci di sisi Tuhanmu.',
	),
	Ayah(
		ayahId: 2068,
		ayahText: 'ذٰلِكَ مِمَّآ اَوْحٰٓى اِلَيْكَ رَبُّكَ مِنَ الْحِكْمَةِۗ وَلَا تَجْعَلْ مَعَ اللّٰهِ اِلٰهًا اٰخَرَ فَتُلْقٰى فِيْ جَهَنَّمَ مَلُوْمًا مَّدْحُوْرًا ',
		ayahNumber: 39,
		translationId: 'Itulah sebagian hikmah yang diwahyukan Tuhan kepadamu (Muhammad). Dan janganlah engkau mengadakan tuhan yang lain di samping Allah, nanti engkau dilemparkan ke dalam neraka dalam keadaan tercela dan dijauhkan (dari rahmat Allah).',
	),
	Ayah(
		ayahId: 2069,
		ayahText: 'اَفَاَصْفٰىكُمْ رَبُّكُمْ بِالْبَنِيْنَ وَاتَّخَذَ مِنَ الْمَلٰۤىِٕكَةِ اِنَاثًاۗ اِنَّكُمْ لَتَقُوْلُوْنَ قَوْلًا عَظِيْمًا ࣖ ',
		ayahNumber: 40,
		translationId: 'Maka apakah pantas Tuhan memilihkan anak laki-laki untukmu dan Dia mengambil anak perempuan dari malaikat? Sungguh, kamu benar-benar mengucapkan kata yang besar (dosanya).',
	),
	Ayah(
		ayahId: 2070,
		ayahText: 'وَلَقَدْ صَرَّفْنَا فِيْ هٰذَا الْقُرْاٰنِ لِيَذَّكَّرُوْاۗ وَمَا يَزِيْدُهُمْ اِلَّا نُفُوْرًا',
		ayahNumber: 41,
		translationId: "Dan sungguh, dalam Al-Qur'an ini telah Kami (jelaskan) berulang-ulang (peringatan), agar mereka selalu ingat. Tetapi (peringatan) itu hanya menambah mereka lari (dari kebenaran).",
	),
	Ayah(
		ayahId: 2071,
		ayahText: 'قُلْ لَّوْ كَانَ مَعَهٗ ٓ اٰلِهَةٌ كَمَا يَقُوْلُوْنَ اِذًا لَّابْتَغَوْا اِلٰى ذِى الْعَرْشِ سَبِيْلًا',
		ayahNumber: 42,
		translationId: 'Katakanlah (Muhammad), “Jika ada tuhan-tuhan di samping-Nya, sebagai-mana yang mereka katakan, niscaya tuhan-tuhan itu mencari jalan kepada Tuhan yang mempunyai ’Arsy.”',
	),
	Ayah(
		ayahId: 2072,
		ayahText: ' سُبْحٰنَهٗ وَتَعٰلٰى عَمَّا يَقُوْلُوْنَ عُلُوًّا كَبِيْرًا',
		ayahNumber: 43,
		translationId: 'Mahasuci dan Mahatinggi Dia dari apa yang mereka katakan, luhur dan agung (tidak ada bandingannya).',
	),
	Ayah(
		ayahId: 2073,
		ayahText: 'تُسَبِّحُ لَهُ السَّمٰوٰتُ السَّبْعُ وَالْاَرْضُ وَمَنْ فِيْهِنَّۗ وَاِنْ مِّنْ شَيْءٍ اِلَّا يُسَبِّحُ بِحَمْدِهٖ وَلٰكِنْ لَّا تَفْقَهُوْنَ تَسْبِيْحَهُمْۗ اِنَّهٗ كَانَ حَلِيْمًا غَفُوْرًا',
		ayahNumber: 44,
		translationId: 'Langit yang tujuh, bumi dan semua yang ada di dalamnya bertasbih kepada Allah. Dan tidak ada sesuatu pun melainkan bertasbih dengan memuji-Nya, tetapi kamu tidak mengerti tasbih mereka. Sungguh, Dia Maha Penyantun, Maha Pengampun.',
	),
	Ayah(
		ayahId: 2074,
		ayahText: 'وَاِذَا قَرَأْتَ الْقُرْاٰنَ جَعَلْنَا بَيْنَكَ وَبَيْنَ الَّذِيْنَ لَا يُؤْمِنُوْنَ بِالْاٰخِرَةِ حِجَابًا مَّسْتُوْرًاۙ  ',
		ayahNumber: 45,
		translationId: "Dan apabila engkau (Muhammad) membaca Al-Qur'an, Kami adakan suatu dinding yang tidak terlihat antara engkau dan orang-orang yang tidak beriman kepada kehidupan akhirat,",
	),
	Ayah(
		ayahId: 2075,
		ayahText: 'وَّجَعَلْنَا عَلٰى قُلُوْبِهِمْ اَكِنَّةً اَنْ يَّفْقَهُوْهُ وَفِيْٓ اٰذَانِهِمْ وَقْرًاۗ وَاِذَا ذَكَرْتَ رَبَّكَ فِى الْقُرْاٰنِ وَحْدَهٗ وَلَّوْا عَلٰٓى اَدْبَارِهِمْ نُفُوْرًا',
		ayahNumber: 46,
		translationId: "Dan Kami jadikan hati mereka tertutup dan telinga mereka tersumbat, agar mereka tidak dapat memahaminya. Dan apabila engkau menyebut Tuhanmu saja dalam Al-Qur'an, mereka berpaling ke belakang melarikan diri (karena benci).",
	),
	Ayah(
		ayahId: 2076,
		ayahText: 'نَحْنُ اَعْلَمُ بِمَا يَسْتَمِعُوْنَ بِهٖٓ اِذْ يَسْتَمِعُوْنَ اِلَيْكَ وَاِذْ هُمْ نَجْوٰٓى اِذْ يَقُوْلُ الظّٰلِمُوْنَ اِنْ تَتَّبِعُوْنَ اِلَّا رَجُلًا مَّسْحُوْرًا ',
		ayahNumber: 47,
		translationId: 'Kami lebih mengetahui dalam keadaan bagaimana mereka mendengarkan sewaktu mereka mendengarkan engkau (Muhammad), dan sewaktu mereka berbisik-bisik (yaitu) ketika orang zalim itu berkata, “Kamu hanyalah mengikuti seorang laki-laki yang kena sihir.”',
	),
	Ayah(
		ayahId: 2077,
		ayahText: 'اُنْظُرْ كَيْفَ ضَرَبُوْا لَكَ الْاَمْثَالَ فَضَلُّوْا فَلَا يَسْتَطِيْعُوْنَ سَبِيْلًا',
		ayahNumber: 48,
		translationId: 'Lihatlah bagaimana mereka membuat perumpamaan untukmu (Muhammad); karena itu mereka menjadi sesat dan tidak dapat lagi menemukan jalan (yang benar).',
	),
	Ayah(
		ayahId: 2078,
		ayahText: 'وَقَالُوْٓا ءَاِذَا كُنَّا عِظَامًا وَّرُفَاتًا ءَاِنَّا لَمَبْعُوْثُوْنَ خَلْقًا جَدِيْدًا ',
		ayahNumber: 49,
		translationId: 'Dan mereka berkata, “Apabila kami telah menjadi tulang-belulang dan benda-benda yang hancur, apakah kami benar-benar akan dibangkitkan kembali sebagai makhluk yang baru?”',
	),
	Ayah(
		ayahId: 2079,
		ayahText: '۞ قُلْ كُوْنُوْا حِجَارَةً اَوْ حَدِيْدًاۙ ',
		ayahNumber: 50,
		translationId: 'Katakanlah (Muhammad), “Jadilah kamu batu atau besi,',
	),
	Ayah(
		ayahId: 2080,
		ayahText: 'اَوْ خَلْقًا مِّمَّا يَكْبُرُ فِيْ صُدُوْرِكُمْ ۚفَسَيَقُوْلُوْنَ مَنْ يُّعِيْدُنَاۗ قُلِ الَّذِيْ فَطَرَكُمْ اَوَّلَ مَرَّةٍۗ فَسَيُنْغِضُوْنَ اِلَيْكَ رُءُوْسَهُمْ وَيَقُوْلُوْنَ مَتٰى هُوَۗ قُلْ عَسٰٓى اَنْ يَّكُوْنَ قَرِيْبًا',
		ayahNumber: 51,
		translationId: 'atau menjadi makhluk yang besar (yang tidak mungkin hidup kembali) menurut pikiranmu.” Maka mereka akan bertanya, “Siapa yang akan menghidupkan kami kembali?” Katakanlah, “Yang telah menciptakan kamu pertama kali.” Lalu mereka akan menggeleng-gelengkan kepalanya kepadamu dan berkata, “Kapan (Kiamat) itu (akan terjadi)?” Katakanlah, “Barang kali waktunya sudah dekat,”',
	),
	Ayah(
		ayahId: 2081,
		ayahText: 'يَوْمَ يَدْعُوْكُمْ فَتَسْتَجِيْبُوْنَ بِحَمْدِهٖ وَتَظُنُّوْنَ اِنْ لَّبِثْتُمْ اِلَّا قَلِيْلًا ࣖ ',
		ayahNumber: 52,
		translationId: 'yaitu pada hari (ketika) Dia memanggil kamu, dan kamu mematuhi-Nya sambil memuji-Nya dan kamu mengira, (rasanya) hanya sebentar saja kamu berdiam (di dalam kubur).',
	),
	Ayah(
		ayahId: 2082,
		ayahText: 'وَقُلْ لِّعِبَادِيْ يَقُوْلُوا الَّتِيْ هِيَ اَحْسَنُۗ اِنَّ الشَّيْطٰنَ يَنْزَغُ بَيْنَهُمْۗ اِنَّ الشَّيْطٰنَ كَانَ لِلْاِنْسَانِ عَدُوًّا مُّبِيْنًا',
		ayahNumber: 53,
		translationId: 'Dan katakanlah kepada hamba-hamba-Ku, “Hendaklah mereka mengucapkan perkataan yang lebih baik (benar). Sungguh, setan itu (selalu) menimbulkan perselisihan di antara mereka. Sungguh, setan adalah musuh yang nyata bagi manusia.',
	),
	Ayah(
		ayahId: 2083,
		ayahText: 'رَبُّكُمْ اَعْلَمُ بِكُمْ اِنْ يَّشَأْ يَرْحَمْكُمْ اَوْ اِنْ يَّشَأْ يُعَذِّبْكُمْۗ وَمَآ اَرْسَلْنٰكَ عَلَيْهِمْ وَكِيْلًا',
		ayahNumber: 54,
		translationId: 'Tuhanmu lebih mengetahui tentang kamu. Jika Dia menghendaki, niscaya Dia akan memberi rahmat kepadamu, dan jika Dia menghendaki, pasti Dia akan mengazabmu. Dan Kami tidaklah mengutusmu (Muhammad) untuk menjadi penjaga bagi mereka.',
	),
	Ayah(
		ayahId: 2084,
		ayahText: 'وَرَبُّكَ اَعْلَمُ بِمَنْ فِى السَّمٰوٰتِ وَالْاَرْضِۗ وَلَقَدْ فَضَّلْنَا بَعْضَ النَّبِيّٖنَ عَلٰى بَعْضٍ وَّاٰتَيْنَا دَاوٗدَ زَبُوْرًا',
		ayahNumber: 55,
		translationId: 'Dan Tuhanmu lebih mengetahui siapa yang di langit dan di bumi. Dan sungguh, Kami telah memberikan kelebihan kepada sebagian nabi-nabi atas sebagian (yang lain), dan Kami berikan Zabur kepada Dawud.',
	),
	Ayah(
		ayahId: 2085,
		ayahText: 'قُلِ ادْعُوا الَّذِيْنَ زَعَمْتُمْ مِّنْ دُوْنِهٖ فَلَا يَمْلِكُوْنَ كَشْفَ الضُّرِّ عَنْكُمْ وَلَا تَحْوِيْلًا',
		ayahNumber: 56,
		translationId: 'Katakanlah (Muhammad), “Panggillah mereka yang kamu anggap (tuhan) selain Allah, mereka tidak kuasa untuk menghilangkan bahaya darimu dan tidak (pula) mampu mengubahnya.”',
	),
	Ayah(
		ayahId: 2086,
		ayahText: 'اُولٰۤىِٕكَ الَّذِيْنَ يَدْعُوْنَ يَبْتَغُوْنَ اِلٰى رَبِّهِمُ الْوَسِيْلَةَ اَيُّهُمْ اَقْرَبُ وَيَرْجُوْنَ رَحْمَتَهٗ وَيَخَافُوْنَ عَذَابَهٗۗ اِنَّ عَذَابَ رَبِّكَ كَانَ مَحْذُوْرًا',
		ayahNumber: 57,
		translationId: 'Orang-orang yang mereka seru itu, mereka sendiri mencari jalan kepada Tuhan siapa di antara mereka yang lebih dekat (kepada Allah). Mereka mengharapkan rahmat-Nya dan takut akan azab-Nya. Sungguh, azab Tuhanmu itu sesuatu yang (harus) ditakuti.”',
	),
	Ayah(
		ayahId: 2087,
		ayahText: 'وَاِنْ مِّنْ قَرْيَةٍ اِلَّا نَحْنُ مُهْلِكُوْهَا قَبْلَ يَوْمِ الْقِيٰمَةِ اَوْ مُعَذِّبُوْهَا عَذَابًا شَدِيْدًاۗ كَانَ ذٰلِكَ فىِ الْكِتٰبِ مَسْطُوْرًا',
		ayahNumber: 58,
		translationId: 'Dan tidak ada suatu negeri pun (yang durhaka penduduknya), melainkan Kami membinasakannya sebelum hari Kiamat atau Kami siksa (penduduknya) dengan siksa yang sangat keras. Yang demikian itu telah tertulis di dalam Kitab (Lauh Mahfuzh).',
	),
	Ayah(
		ayahId: 2088,
		ayahText: 'وَمَا مَنَعَنَآ اَنْ نُّرْسِلَ بِالْاٰيٰتِ اِلَّآ اَنْ كَذَّبَ بِهَا الْاَوَّلُوْنَۗ وَاٰتَيْنَا ثَمُوْدَ النَّاقَةَ مُبْصِرَةً فَظَلَمُوْا بِهَاۗ وَمَا نُرْسِلُ بِالْاٰيٰتِ اِلَّا تَخْوِيْفًا',
		ayahNumber: 59,
		translationId: 'Dan tidak ada yang menghalangi Kami untuk mengirimkan (kepadamu) tanda-tanda (kekuasaan Kami), melainkan karena (tanda-tanda) itu telah didustakan oleh orang terdahulu. Dan telah Kami berikan kepada kaum samud unta betina (sebagai mukjizat) yang dapat dilihat, tetapi mereka menganiaya (unta betina itu). Dan Kami tidak mengirimkan tanda-tanda itu melainkan untuk menakut-nakuti.',
	),
	Ayah(
		ayahId: 2089,
		ayahText: 'وَاِذْ قُلْنَا لَكَ اِنَّ رَبَّكَ اَحَاطَ بِالنَّاسِۗ وَمَا جَعَلْنَا الرُّءْيَا الَّتِيْٓ اَرَيْنٰكَ اِلَّا فِتْنَةً لِّلنَّاسِ وَالشَّجَرَةَ الْمَلْعُوْنَةَ فِى الْقُرْاٰنِ ۗ وَنُخَوِّفُهُمْۙ فَمَا يَزِيْدُهُمْ اِلَّا طُغْيَانًا كَبِيْرًا ࣖ ',
		ayahNumber: 60,
		translationId: "Dan (ingatlah) ketika Kami wahyukan kepadamu, “Sungguh, (ilmu) Tuhanmu meliputi seluruh manusia.” Dan Kami tidak menjadikan mimpi yang telah Kami perlihatkan kepadamu, melainkan sebagai ujian bagi manusia dan (begitu pula) pohon yang terkutuk (zaqqum) dalam Al-Qur'an. Dan Kami menakut-nakuti mereka, tetapi yang demikian itu hanyalah menambah besar kedurhakaan mereka.",
	),
	Ayah(
		ayahId: 2090,
		ayahText: 'وَاِذْ قُلْنَا لِلْمَلٰۤىِٕكَةِ اسْجُدُوْا لِاٰدَمَ فَسَجَدُوْٓا اِلَّآ اِبْلِيْسَۗ قَالَ ءَاَسْجُدُ لِمَنْ خَلَقْتَ طِيْنًاۚ ',
		ayahNumber: 61,
		translationId: 'Dan (ingatlah), ketika Kami berfirman kepada para malaikat, “Sujudlah kamu semua kepada Adam,” lalu mereka sujud, kecuali Iblis. Ia (Iblis) berkata, “Apakah aku harus bersujud kepada orang yang Engkau ciptakan dari tanah?”',
	),
	Ayah(
		ayahId: 2091,
		ayahText: 'قَالَ اَرَاَيْتَكَ هٰذَا الَّذِيْ كَرَّمْتَ عَلَيَّ لَىِٕنْ اَخَّرْتَنِ اِلٰى يَوْمِ الْقِيٰمَةِ لَاَحْتَنِكَنَّ ذُرِّيَّتَهٗٓ اِلَّا قَلِيْلًا',
		ayahNumber: 62,
		translationId: ' Ia (Iblis) berkata, “Terangkanlah kepadaku, inikah yang lebih Engkau muliakan daripada aku? Sekiranya Engkau memberi waktu kepadaku sampai hari Kiamat, pasti akan aku sesatkan keturunannya, kecuali sebagian kecil.”',
	),
	Ayah(
		ayahId: 2092,
		ayahText: 'قَالَ اذْهَبْ فَمَنْ تَبِعَكَ مِنْهُمْ فَاِنَّ جَهَنَّمَ جَزَاۤؤُكُمْ جَزَاۤءً مَّوْفُوْرًا',
		ayahNumber: 63,
		translationId: 'Dia (Allah) berfirman, “Pergilah, tetapi barang siapa di antara mereka yang mengikuti kamu, maka sungguh, neraka Jahanamlah balasanmu semua, sebagai pembalasan yang cukup.',
	),
	Ayah(
		ayahId: 2093,
		ayahText: 'وَاسْتَفْزِزْ مَنِ اسْتَطَعْتَ مِنْهُمْ بِصَوْتِكَ وَاَجْلِبْ عَلَيْهِمْ بِخَيْلِكَ وَرَجِلِكَ وَشَارِكْهُمْ فِى الْاَمْوَالِ وَالْاَوْلَادِ وَعِدْهُمْۗ وَمَا يَعِدُهُمُ الشَّيْطٰنُ اِلَّا غُرُوْرًا',
		ayahNumber: 64,
		translationId: 'Dan perdayakanlah siapa saja di antara mereka yang engkau (Iblis) sanggup dengan suaramu (yang memukau), kerahkanlah pasukanmu terhadap mereka, yang berkuda dan yang berjalan kaki, dan bersekutulah dengan mereka pada harta dan anak-anak lalu beri janjilah kepada mereka.” Padahal setan itu hanya menjanjikan tipuan belaka kepada mereka.',
	),
	Ayah(
		ayahId: 2094,
		ayahText: 'اِنَّ عِبَادِيْ لَيْسَ لَكَ عَلَيْهِمْ سُلْطٰنٌۗ وَكَفٰى بِرَبِّكَ وَكِيْلًا',
		ayahNumber: 65,
		translationId: '“Sesungguhnya (terhadap) hamba-hamba-Ku, engkau (Iblis) tidaklah dapat berkuasa atas mereka. Dan cukuplah Tuhanmu sebagai penjaga.”',
	),
	Ayah(
		ayahId: 2095,
		ayahText: 'رَبُّكُمُ الَّذِيْ يُزْجِيْ لَكُمُ الْفُلْكَ فِى الْبَحْرِ لِتَبْتَغُوْا مِنْ فَضْلِهٖۗ اِنَّهٗ كَانَ بِكُمْ رَحِيْمًا',
		ayahNumber: 66,
		translationId: 'Tuhanmulah yang melayarkan kapal-kapal di lautan untukmu, agar kamu mencari karunia-Nya. Sungguh, Dia Maha Penyayang terhadapmu.',
	),
	Ayah(
		ayahId: 2096,
		ayahText: 'وَاِذَا مَسَّكُمُ الضُّرُّ فِى الْبَحْرِ ضَلَّ مَنْ تَدْعُوْنَ اِلَّآ اِيَّاهُۚ فَلَمَّا نَجّٰىكُمْ اِلَى الْبَرِّ اَعْرَضْتُمْۗ وَكَانَ الْاِنْسَانُ كَفُوْرًا',
		ayahNumber: 67,
		translationId: 'Dan apabila kamu ditimpa bahaya di lautan, niscaya hilang semua yang (bi-asa) kamu seru, kecuali Dia. Tetapi ketika Dia menyelamatkan kamu ke daratan, kamu berpaling (dari-Nya). Dan manusia memang selalu ingkar (tidak bersyukur).',
	),
	Ayah(
		ayahId: 2097,
		ayahText: 'اَفَاَمِنْتُمْ اَنْ يَّخْسِفَ بِكُمْ جَانِبَ الْبَرِّ اَوْ يُرْسِلَ عَلَيْكُمْ حَاصِبًا ثُمَّ لَا تَجِدُوْا لَكُمْ وَكِيْلًا ۙ ',
		ayahNumber: 68,
		translationId: 'Maka apakah kamu merasa aman bahwa Dia tidak akan membenamkan sebagian daratan bersama kamu atau Dia meniupkan (angin keras yang membawa) batu-batu kecil? Dan kamu tidak akan mendapat seorang pelindung pun,',
	),
	Ayah(
		ayahId: 2098,
		ayahText: 'اَمْ اَمِنْتُمْ اَنْ يُّعِيْدَكُمْ فِيْهِ تَارَةً اُخْرٰى فَيُرْسِلَ عَلَيْكُمْ قَاصِفًا مِّنَ الرِّيْحِ فَيُغْرِقَكُمْ بِمَا كَفَرْتُمْۙ ثُمَّ لَا تَجِدُوْا لَكُمْ عَلَيْنَا بِهٖ تَبِيْعًا',
		ayahNumber: 69,
		translationId: 'ataukah kamu merasa aman bahwa Dia tidak akan mengembalikan kamu ke laut sekali lagi, lalu Dia tiupkan angin topan kepada kamu dan ditenggelamkan-Nya kamu disebabkan kekafiranmu? Kemudian kamu tidak akan mendapatkan seorang penolong pun dalam menghadapi (siksaan) Kami.  ',
	),
	Ayah(
		ayahId: 2099,
		ayahText: '۞ وَلَقَدْ كَرَّمْنَا بَنِيْٓ اٰدَمَ وَحَمَلْنٰهُمْ فِى الْبَرِّ وَالْبَحْرِ وَرَزَقْنٰهُمْ مِّنَ الطَّيِّبٰتِ وَفَضَّلْنٰهُمْ عَلٰى كَثِيْرٍ مِّمَّنْ خَلَقْنَا تَفْضِيْلًا ࣖ ',
		ayahNumber: 70,
		translationId: 'Dan sungguh, Kami telah memuliakan anak cucu Adam, dan Kami angkut mereka di darat dan di laut, dan Kami beri mereka rezeki dari yang baik-baik dan Kami lebihkan mereka di atas banyak makhluk yang Kami ciptakan dengan kelebihan yang sempurna.',
	),
	Ayah(
		ayahId: 2100,
		ayahText: 'يَوْمَ نَدْعُوْا كُلَّ اُنَاسٍۢ بِاِمَامِهِمْۚ فَمَنْ اُوْتِيَ كِتٰبَهٗ بِيَمِيْنِهٖ فَاُولٰۤىِٕكَ يَقْرَءُوْنَ كِتٰبَهُمْ وَلَا يُظْلَمُوْنَ فَتِيْلًا',
		ayahNumber: 71,
		translationId: '(Ingatlah), pada hari (ketika) Kami panggil setiap umat dengan pemimpinnya; dan barang siapa diberikan catatan amalnya di tangan kanannya mereka akan membaca catatannya (dengan baik), dan mereka tidak akan dirugikan sedikit pun.',
	),
	Ayah(
		ayahId: 2101,
		ayahText: 'وَمَنْ كَانَ فِيْ هٰذِهٖٓ اَعْمٰى فَهُوَ فِى الْاٰخِرَةِ اَعْمٰى وَاَضَلُّ سَبِيْلًا',
		ayahNumber: 72,
		translationId: 'Dan barang siapa buta (hatinya) di dunia ini, maka di akhirat dia akan buta dan tersesat jauh dari jalan (yang benar).',
	),
	Ayah(
		ayahId: 2102,
		ayahText: 'وَاِنْ كَادُوْا لَيَفْتِنُوْنَكَ عَنِ الَّذِيْٓ اَوْحَيْنَآ اِلَيْكَ لِتَفْتَرِيَ عَلَيْنَا غَيْرَهٗۖ وَاِذًا لَّاتَّخَذُوْكَ خَلِيْلًا',
		ayahNumber: 73,
		translationId: 'Dan mereka hampir memalingkan engkau (Muhammad) dari apa yang telah Kami wahyukan kepadamu, agar engkau mengada-ada yang lain terhadap Kami; dan jika demikian tentu mereka menjadikan engkau sahabat yang setia.',
	),
	Ayah(
		ayahId: 2103,
		ayahText: 'وَلَوْلَآ اَنْ ثَبَّتْنٰكَ لَقَدْ كِدْتَّ تَرْكَنُ اِلَيْهِمْ شَيْـًٔا قَلِيْلًا ۙ  ',
		ayahNumber: 74,
		translationId: 'Dan sekiranya Kami tidak memperteguh (hati)mu, niscaya engkau hampir saja condong sedikit kepada mereka.',
	),
	Ayah(
		ayahId: 2104,
		ayahText: 'اِذًا لَّاَذَقْنٰكَ ضِعْفَ الْحَيٰوةِ وَضِعْفَ الْمَمَاتِ ثُمَّ لَا تَجِدُ لَكَ عَلَيْنَا نَصِيْرًا',
		ayahNumber: 75,
		translationId: 'Jika demikian, tentu akan Kami rasakan kepadamu (siksaan) dua kali lipat di dunia ini dan dua kali lipat setelah mati, dan engkau (Muhammad) tidak akan mendapat seorang penolong pun terhadap Kami.',
	),
	Ayah(
		ayahId: 2105,
		ayahText: 'وَاِنْ كَادُوْا لَيَسْتَفِزُّوْنَكَ مِنَ الْاَرْضِ لِيُخْرِجُوْكَ مِنْهَا وَاِذًا لَّا يَلْبَثُوْنَ خِلٰفَكَ اِلَّا قَلِيْلًا',
		ayahNumber: 76,
		translationId: 'Dan sungguh, mereka hampir membuatmu (Muhammad) gelisah di negeri (Mekah) karena engkau harus keluar dari negeri itu, dan kalau terjadi demikian, niscaya sepeninggalmu mereka tidak akan tinggal (di sana), melainkan sebentar saja.',
	),
	Ayah(
		ayahId: 2106,
		ayahText: 'سُنَّةَ مَنْ قَدْ اَرْسَلْنَا قَبْلَكَ مِنْ رُّسُلِنَا وَلَا تَجِدُ لِسُنَّتِنَا تَحْوِيْلًا ࣖ ',
		ayahNumber: 77,
		translationId: '(Yang demikian itu) merupakan ketetapan bagi para rasul Kami yang Kami utus sebelum engkau, dan tidak akan engkau dapati perubahan atas ketetapan Kami.',
	),
	Ayah(
		ayahId: 2107,
		ayahText: 'اَقِمِ الصَّلٰوةَ لِدُلُوْكِ الشَّمْسِ اِلٰى غَسَقِ الَّيْلِ وَقُرْاٰنَ الْفَجْرِۗ اِنَّ قُرْاٰنَ الْفَجْرِ كَانَ مَشْهُوْدًا ',
		ayahNumber: 78,
		translationId: 'Laksanakanlah salat sejak matahari tergelincir sampai gelapnya malam dan (laksanakan pula salat) Subuh. Sungguh, salat subuh itu disaksikan (oleh malaikat).',
	),
	Ayah(
		ayahId: 2108,
		ayahText: 'وَمِنَ الَّيْلِ فَتَهَجَّدْ بِهٖ نَافِلَةً لَّكَۖ عَسٰٓى اَنْ يَّبْعَثَكَ رَبُّكَ مَقَامًا مَّحْمُوْدًا',
		ayahNumber: 79,
		translationId: 'Dan pada sebagian malam, lakukanlah salat tahajud (sebagai suatu ibadah) tambahan bagimu: mudah-mudahan Tuhanmu mengangkatmu ke tempat yang terpuji.',
	),
	Ayah(
		ayahId: 2109,
		ayahText: 'وَقُلْ رَّبِّ اَدْخِلْنِيْ مُدْخَلَ صِدْقٍ وَّاَخْرِجْنِيْ مُخْرَجَ صِدْقٍ وَّاجْعَلْ لِّيْ مِنْ لَّدُنْكَ سُلْطٰنًا نَّصِيْرًا',
		ayahNumber: 80,
		translationId: 'Dan katakanlah (Muhammad), ya Tuhanku, masukkan aku ke tempat masuk yang benar dan keluarkan (pula) aku ke tempat keluar yang benar dan berikanlah kepadaku dari sisi-Mu kekuasaan yang dapat menolong(ku).',
	),
	Ayah(
		ayahId: 2110,
		ayahText: 'وَقُلْ جَاۤءَ الْحَقُّ وَزَهَقَ الْبَاطِلُ  ۖاِنَّ الْبَاطِلَ كَانَ زَهُوْقًا',
		ayahNumber: 81,
		translationId: 'Dan katakanlah, “Kebenaran telah datang dan yang batil telah lenyap.” Sungguh, yang batil itu pasti lenyap.',
	),
	Ayah(
		ayahId: 2111,
		ayahText: 'وَنُنَزِّلُ مِنَ الْقُرْاٰنِ مَا هُوَ شِفَاۤءٌ وَّرَحْمَةٌ لِّلْمُؤْمِنِيْنَۙ وَلَا يَزِيْدُ الظّٰلِمِيْنَ اِلَّا خَسَارًا',
		ayahNumber: 82,
		translationId: "Dan Kami turunkan dari Al-Qur'an (sesuatu) yang menjadi penawar dan rahmat bagi orang yang beriman, sedangkan bagi orang yang zalim (Al-Qur'an itu) hanya akan menambah kerugian.",
	),
	Ayah(
		ayahId: 2112,
		ayahText: 'وَاِذَآ اَنْعَمْنَا عَلَى الْاِنْسَانِ اَعْرَضَ وَنَاٰ بِجَانِبِهٖۚ وَاِذَا مَسَّهُ الشَّرُّ كَانَ يَـُٔوْسًا',
		ayahNumber: 83,
		translationId: 'Dan apabila Kami berikan kesenangan kepada manusia, niscaya dia berpaling dan menjauhkan diri dengan sombong; dan apabila dia ditimpa kesusahan, niscaya dia berputus asa.',
	),
	Ayah(
		ayahId: 2113,
		ayahText: 'قُلْ كُلٌّ يَّعْمَلُ عَلٰى شَاكِلَتِهٖۗ فَرَبُّكُمْ اَعْلَمُ بِمَنْ هُوَ اَهْدٰى سَبِيْلًا ࣖ',
		ayahNumber: 84,
		translationId: 'Katakanlah (Muhammad), “Setiap orang berbuat sesuai dengan pembawaannya masing-masing.” Maka Tuhanmu lebih mengetahui siapa yang lebih benar jalannya.',
	),
	Ayah(
		ayahId: 2114,
		ayahText: 'وَيَسْـَٔلُوْنَكَ عَنِ الرُّوْحِۗ قُلِ الرُّوْحُ مِنْ اَمْرِ رَبِّيْ وَمَآ اُوْتِيْتُمْ مِّنَ الْعِلْمِ اِلَّا قَلِيْلًا ',
		ayahNumber: 85,
		translationId: 'Dan mereka bertanya kepadamu (Muhammad) tentang ruh. Katakanlah, “Ruh itu termasuk urusan Tuhanku, sedangkan kamu diberi pengetahuan hanya sedikit.”',
	),
	Ayah(
		ayahId: 2115,
		ayahText: 'وَلَىِٕنْ شِئْنَا لَنَذْهَبَنَّ بِالَّذِيْٓ اَوْحَيْنَآ اِلَيْكَ ثُمَّ لَا تَجِدُ لَكَ بِهٖ عَلَيْنَا وَكِيْلًاۙ؉؉',
		ayahNumber: 86,
		translationId: 'Dan sesungguhnya jika Kami menghendaki, niscaya Kami lenyapkan apa yang telah Kami wahyukan kepadamu (Muhammad), dan engkau tidak akan mendapatkan seorang pembela pun terhadap Kami,',
	),
	Ayah(
		ayahId: 2116,
		ayahText: 'اِلَّا رَحْمَةً مِّنْ رَّبِّكَۗ اِنَّ فَضْلَهٗ كَانَ عَلَيْكَ كَبِيْرًا',
		ayahNumber: 87,
		translationId: 'kecuali karena rahmat dari Tuhanmu. Sungguh, karunia-Nya atasmu (Muhammad) sangat besar. ',
	),
	Ayah(
		ayahId: 2117,
		ayahText: 'قُلْ لَّىِٕنِ اجْتَمَعَتِ الْاِنْسُ وَالْجِنُّ عَلٰٓى اَنْ يَّأْتُوْا بِمِثْلِ هٰذَا الْقُرْاٰنِ لَا يَأْتُوْنَ بِمِثْلِهٖ وَلَوْ كَانَ بَعْضُهُمْ لِبَعْضٍ ظَهِيْرًا',
		ayahNumber: 88,
		translationId: "Katakanlah, “Sesungguhnya jika manusia dan jin berkumpul untuk membuat yang serupa (dengan) Al-Qur'an ini, mereka tidak akan dapat membuat yang serupa dengannya, sekalipun mereka saling membantu satu sama lain.”",
	),
	Ayah(
		ayahId: 2118,
		ayahText: 'وَلَقَدْ صَرَّفْنَا لِلنَّاسِ فِيْ هٰذَا الْقُرْاٰنِ مِنْ كُلِّ مَثَلٍۖ فَاَبٰىٓ اَكْثَرُ النَّاسِ اِلَّا كُفُوْرًا',
		ayahNumber: 89,
		translationId: " Dan sungguh, Kami telah menjelaskan berulang-ulang kepada manusia dalam Al-Qur'an ini dengan bermacam-macam perumpamaan, tetapi kebanyakan manusia tidak menyukainya bahkan mengingkari(nya).",
	),
	Ayah(
		ayahId: 2119,
		ayahText: 'وَقَالُوْا لَنْ نُّؤْمِنَ لَكَ حَتّٰى تَفْجُرَ لَنَا مِنَ الْاَرْضِ يَنْۢبُوْعًاۙ  ',
		ayahNumber: 90,
		translationId: 'Dan mereka berkata, “Kami tidak akan percaya kepadamu (Muhammad) sebelum engkau memancarkan mata air dari bumi untuk kami,',
	),
	Ayah(
		ayahId: 2120,
		ayahText: 'اَوْ تَكُوْنَ لَكَ جَنَّةٌ مِّنْ نَّخِيْلٍ وَّعِنَبٍ فَتُفَجِّرَ الْاَنْهٰرَ خِلٰلَهَا تَفْجِيْرًاۙ  ',
		ayahNumber: 91,
		translationId: 'atau engkau mempunyai sebuah kebun kurma dan anggur, lalu engkau alirkan di celah-celahnya sungai yang deras alirannya,',
	),
	Ayah(
		ayahId: 2121,
		ayahText: 'اَوْ تُسْقِطَ السَّمَاۤءَ كَمَا زَعَمْتَ عَلَيْنَا كِسَفًا اَوْ تَأْتِيَ بِاللّٰهِ وَالْمَلٰۤىِٕكَةِ قَبِيْلًاۙ  ',
		ayahNumber: 92,
		translationId: 'atau engkau jatuhkan langit berkeping-keping atas kami, sebagaimana engkau katakan, atau (sebelum) engkau datangkan Allah dan para malaikat berhadapan muka dengan kami,',
	),
	Ayah(
		ayahId: 2122,
		ayahText: 'اَوْ يَكُوْنَ لَكَ بَيْتٌ مِّنْ زُخْرُفٍ اَوْ تَرْقٰى فِى السَّمَاۤءِ ۗوَلَنْ نُّؤْمِنَ لِرُقِيِّكَ حَتّٰى تُنَزِّلَ عَلَيْنَا كِتٰبًا نَّقْرَؤُهٗۗ قُلْ سُبْحَانَ رَبِّيْ هَلْ كُنْتُ اِلَّا بَشَرًا رَّسُوْلًا ࣖ  ',
		ayahNumber: 93,
		translationId: 'atau engkau mempunyai sebuah rumah (terbuat) dari emas, atau engkau naik ke langit. Dan kami tidak akan mempercayai kenaikanmu itu sebelum engkau turunkan kepada kami sebuah kitab untuk kami baca.” Katakanlah (Muhammad), “Mahasuci Tuhanku, bukankah aku ini hanya seorang manusia yang menjadi rasul?”',
	),
	Ayah(
		ayahId: 2123,
		ayahText: 'وَمَا مَنَعَ النَّاسَ اَنْ يُّؤْمِنُوْٓا اِذْ جَاۤءَهُمُ الْهُدٰٓى اِلَّآ اَنْ قَالُوْٓا اَبَعَثَ اللّٰهُ بَشَرًا رَّسُوْلًا',
		ayahNumber: 94,
		translationId: 'Dan tidak ada sesuatu yang menghalangi manusia untuk beriman ketika petunjuk datang kepadanya, selain perkataan mereka, “Mengapa Allah mengutus seorang manusia menjadi rasul?”',
	),
	Ayah(
		ayahId: 2124,
		ayahText: 'قُلْ لَّوْ كَانَ فِى الْاَرْضِ مَلٰۤىِٕكَةٌ يَّمْشُوْنَ مُطْمَىِٕنِّيْنَ لَنَزَّلْنَا عَلَيْهِمْ مِّنَ السَّمَاۤءِ مَلَكًا رَّسُوْلًا',
		ayahNumber: 95,
		translationId: 'Katakanlah (Muhammad), “Sekiranya di bumi ada para malaikat, yang berjalan-jalan dengan tenang, niscaya Kami turunkan kepada mereka malaikat dari langit untuk menjadi rasul.”',
	),
	Ayah(
		ayahId: 2125,
		ayahText: 'قُلْ كَفٰى بِاللّٰهِ شَهِيْدًاۢ بَيْنِيْ وَبَيْنَكُمْۗ اِنَّهٗ كَانَ بِعِبَادِهٖ خَبِيْرًاۢ بَصِيْرًا',
		ayahNumber: 96,
		translationId: 'Katakanlah (Muhammad), “Cukuplah Allah menjadi saksi antara aku dan kamu sekalian. Sungguh, Dia Maha Mengetahui, Maha Melihat akan hamba-hamba-Nya.”',
	),
	Ayah(
		ayahId: 2126,
		ayahText: 'وَمَنْ يَّهْدِ اللّٰهُ فَهُوَ الْمُهْتَدِۚ وَمَنْ يُّضْلِلْ فَلَنْ تَجِدَ لَهُمْ اَوْلِيَاۤءَ مِنْ دُوْنِهٖۗ وَنَحْشُرُهُمْ يَوْمَ الْقِيٰمَةِ عَلٰى وُجُوْهِهِمْ عُمْيًا وَّبُكْمًا وَّصُمًّاۗ مَأْوٰىهُمْ جَهَنَّمُۗ  كُلَّمَا خَبَتْ زِدْنٰهُمْ سَعِيْرًا',
		ayahNumber: 97,
		translationId: 'Dan barang siapa diberi petunjuk oleh Allah, dialah yang mendapat petunjuk, dan barang siapa Dia sesatkan, maka engkau tidak akan mendapatkan penolong-penolong bagi mereka selain Dia. Dan Kami akan mengumpulkan mereka pada hari Kiamat dengan wajah tersungkur, dalam keadaan buta, bisu, dan tuli. Tempat kediaman mereka adalah neraka Jahanam. Setiap kali nyala api Jahanam itu akan padam, Kami tambah lagi nyalanya bagi mereka.',
	),
	Ayah(
		ayahId: 2127,
		ayahText: 'ذٰلِكَ جَزَاۤؤُهُمْ بِاَنَّهُمْ كَفَرُوْا بِاٰيٰتِنَا وَقَالُوْٓا ءَاِذَا كُنَّا عِظَامًا وَّرُفَاتًا ءَاِنَّا لَمَبْعُوْثُوْنَ خَلْقًا جَدِيْدًا ',
		ayahNumber: 98,
		translationId: 'Itulah balasan bagi mereka, karena sesungguhnya mereka kafir kepada ayat-ayat Kami dan (karena mereka) berkata, “Apabila kami telah menjadi tulang belulang dan benda-benda yang hancur, apakah kami benar-benar akan dibangkitkan kembali sebagai makhluk baru?”',
	),
	Ayah(
		ayahId: 2128,
		ayahText: '۞ اَوَلَمْ يَرَوْا اَنَّ اللّٰهَ الَّذِيْ خَلَقَ السَّمٰوٰتِ وَالْاَرْضَ قَادِرٌ عَلٰٓى اَنْ يَّخْلُقَ مِثْلَهُمْ وَجَعَلَ لَهُمْ اَجَلًا لَّا رَيْبَ فِيْهِۗ فَاَبَى الظّٰلِمُوْنَ اِلَّا كُفُوْرًا',
		ayahNumber: 99,
		translationId: 'Dan apakah mereka tidak memperhatikan bahwa Allah yang menciptakan langit dan bumi adalah Mahakuasa (pula) menciptakan yang serupa dengan mereka, dan Dia telah menetapkan waktu tertentu (mati atau dibangkitkan) bagi mereka, yang tidak diragukan lagi? Maka orang zalim itu tidak menolaknya kecuali dengan kekafiran.',
	),
	Ayah(
		ayahId: 2129,
		ayahText: 'قُلْ لَّوْ اَنْتُمْ تَمْلِكُوْنَ خَزَاۤىِٕنَ رَحْمَةِ رَبِّيْٓ اِذًا لَّاَمْسَكْتُمْ خَشْيَةَ الْاِنْفَاقِۗ وَكَانَ الْاِنْسَانُ قَتُوْرًا ࣖ',
		ayahNumber: 100,
		translationId: 'Katakanlah (Muhammad), “Sekiranya kamu menguasai perbendaharaan rahmat Tuhanku, niscaya (perbendaharaan) itu kamu tahan, karena takut membelanjakannya.” Dan manusia itu memang sangat kikir.',
	),
	Ayah(
		ayahId: 2130,
		ayahText: 'وَلَقَدْ اٰتَيْنَا مُوْسٰى تِسْعَ اٰيٰتٍۢ بَيِّنٰتٍ فَسْـَٔلْ بَنِيْٓ اِسْرَاۤءِيْلَ اِذْ جَاۤءَهُمْ فَقَالَ لَهٗ فِرْعَوْنُ اِنِّيْ لَاَظُنُّكَ يٰمُوْسٰى مَسْحُوْرًا ',
		ayahNumber: 101,
		translationId: 'Dan sungguh, Kami telah memberikan kepada Musa sembilan mukjizat yang nyata maka tanyakanlah kepada Bani Israil, ketika Musa datang kepada mereka lalu Fir‘aun berkata kepadanya, “Wahai Musa! Sesungguhnya aku benar-benar menduga engkau terkena sihir.”',
	),
	Ayah(
		ayahId: 2131,
		ayahText: 'قَالَ لَقَدْ عَلِمْتَ مَآ اَنْزَلَ هٰٓؤُلَاۤءِ اِلَّا رَبُّ السَّمٰوٰتِ وَالْاَرْضِ بَصَاۤىِٕرَۚ وَاِنِّيْ لَاَظُنُّكَ يٰفِرْعَوْنُ مَثْبُوْرًا ',
		ayahNumber: 102,
		translationId: 'Dia (Musa) menjawab, ”Sungguh, engkau telah mengetahui, bahwa tidak ada yang menurunkan (mukjizat-mukjizat) itu kecuali Tuhan (yang memelihara) langit dan bumi sebagai bukti-bukti yang nyata; dan sungguh, aku benar-benar menduga engkau akan binasa, wahai Fir‘aun.”',
	),
	Ayah(
		ayahId: 2132,
		ayahText: 'فَاَرَادَ اَنْ يَّسْتَفِزَّهُمْ مِّنَ الْاَرْضِ فَاَغْرَقْنٰهُ وَمَنْ مَّعَهٗ جَمِيْعًاۙ ',
		ayahNumber: 103,
		translationId: 'Kemudian dia (Fir‘aun) hendak mengusir mereka (Musa dan pengikutnya) dari bumi (Mesir), maka Kami tenggelamkan dia (Fir‘aun) beserta orang yang bersama dia seluruhnya.',
	),
	Ayah(
		ayahId: 2133,
		ayahText: 'وَّقُلْنَا مِنْۢ بَعْدِهٖ لِبَنِيْٓ اِسْرَاۤءِيْلَ اسْكُنُوا الْاَرْضَ فَاِذَا جَاۤءَ وَعْدُ الْاٰخِرَةِ جِئْنَا بِكُمْ لَفِيْفًاۗ   ',
		ayahNumber: 104,
		translationId: 'Dan setelah itu Kami berfirman kepada Bani Israil, “Tinggallah di negeri ini, tetapi apabila masa berbangkit datang, niscaya Kami kumpulkan kamu dalam keadaan bercampur baur.”',
	),
	Ayah(
		ayahId: 2134,
		ayahText: 'وَبِالْحَقِّ اَنْزَلْنٰهُ وَبِالْحَقِّ نَزَلَۗ وَمَآ اَرْسَلْنٰكَ اِلَّا مُبَشِّرًا وَّنَذِيْرًاۘ',
		ayahNumber: 105,
		translationId: "Dan Kami turunkan (Al-Qur'an) itu dengan sebenarnya dan (Al-Qur'an) itu turun dengan (membawa) kebenaran. Dan Kami mengutus engkau (Muhammad), hanya sebagai pembawa berita gembira dan pemberi peringatan.",
	),
	Ayah(
		ayahId: 2135,
		ayahText: 'وَقُرْاٰنًا فَرَقْنٰهُ لِتَقْرَاَهٗ عَلَى النَّاسِ عَلٰى مُكْثٍ وَّنَزَّلْنٰهُ تَنْزِيْلًا ',
		ayahNumber: 106,
		translationId: "Dan Al-Qur'an (Kami turunkan) berangsur-angsur agar engkau (Muhammad) membacakannya kepada manusia perlahan-lahan dan Kami menurunkannya secara bertahap.",
	),
	Ayah(
		ayahId: 2136,
		ayahText: 'قُلْ اٰمِنُوْا بِهٖٓ اَوْ لَا تُؤْمِنُوْاۗ اِنَّ الَّذِيْنَ اُوْتُوا الْعِلْمَ مِنْ قَبْلِهٖٓ اِذَا يُتْلٰى عَلَيْهِمْ يَخِرُّوْنَ لِلْاَذْقَانِ سُجَّدًاۙ',
		ayahNumber: 107,
		translationId: "Katakanlah (Muhammad), “Berimanlah kamu kepadanya (Al-Qur'an) atau tidak usah beriman (sama saja bagi Allah). Sesungguhnya orang yang telah diberi pengetahuan sebelumnya, apabila (Al-Qur'an) dibacakan kepada mereka, mereka menyungkurkan wajah, bersujud,”",
	),
	Ayah(
		ayahId: 2137,
		ayahText: 'وَّيَقُوْلُوْنَ سُبْحٰنَ رَبِّنَآ اِنْ كَانَ وَعْدُ رَبِّنَا لَمَفْعُوْلًا',
		ayahNumber: 108,
		translationId: 'dan mereka berkata, “Mahasuci Tuhan kami; sungguh, janji Tuhan kami pasti dipenuhi.”  ',
	),
	Ayah(
		ayahId: 2138,
		ayahText: 'وَيَخِرُّوْنَ لِلْاَذْقَانِ يَبْكُوْنَ وَيَزِيْدُهُمْ خُشُوْعًا ۩',
		ayahNumber: 109,
		translationId: 'Dan mereka menyungkurkan wajah sambil menangis dan mereka bertambah khusyuk.',
	),
	Ayah(
		ayahId: 2139,
		ayahText: 'قُلِ ادْعُوا اللّٰهَ اَوِ ادْعُوا الرَّحْمٰنَۗ اَيًّا مَّا تَدْعُوْا فَلَهُ الْاَسْمَاۤءُ الْحُسْنٰىۚ وَلَا تَجْهَرْ بِصَلَاتِكَ وَلَا تُخَافِتْ بِهَا وَابْتَغِ بَيْنَ ذٰلِكَ سَبِيْلًا',
		ayahNumber: 110,
		translationId: 'Katakanlah (Muhammad), “Serulah Allah atau serulah Ar-Rahman. Dengan nama yang mana saja kamu dapat menyeru, karena Dia mempunyai nama-nama yang terbaik (Asma‘ul husna) dan janganlah engkau mengeraskan suaramu dalam salat dan janganlah (pula) merendahkannya dan usahakan jalan tengah di antara kedua itu.”',
	),
	Ayah(
		ayahId: 2140,
		ayahText: 'وَقُلِ الْحَمْدُ لِلّٰهِ الَّذِيْ لَمْ يَتَّخِذْ وَلَدًا وَّلَمْ يَكُنْ لَّهٗ شَرِيْكٌ فِى الْمُلْكِ وَلَمْ يَكُنْ لَّهٗ وَلِيٌّ مِّنَ الذُّلِّ وَكَبِّرْهُ تَكْبِيْرًا ࣖ',
		ayahNumber: 111,
		translationId: 'Dan katakanlah, “Segala puji bagi Allah yang tidak mempunyai anak dan tidak (pula) mempunyai sekutu dalam kerajaan-Nya dan Dia tidak memerlukan penolong dari kehinaan dan agungkanlah Dia seagung-agungnya.',
	),
];
