// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah80 = [
	Ayah(
		ayahId: 5759,
		ayahText: 'عَبَسَ وَتَوَلّٰىٓۙ',
		ayahNumber: 1,
		translationId: 'Dia (Muhammad) berwajah masam dan berpaling,',
	),
	Ayah(
		ayahId: 5760,
		ayahText: 'اَنْ جَاۤءَهُ الْاَعْمٰىۗ',
		ayahNumber: 2,
		translationId: 'karena seorang buta telah datang kepadanya (Abdullah bin Ummi Maktum).',
	),
	Ayah(
		ayahId: 5761,
		ayahText: 'وَمَا يُدْرِيْكَ لَعَلَّهٗ يَزَّكّٰىٓۙ',
		ayahNumber: 3,
		translationId: 'Dan tahukah engkau (Muhammad) barangkali dia ingin menyucikan dirinya (dari dosa),',
	),
	Ayah(
		ayahId: 5762,
		ayahText: 'اَوْ يَذَّكَّرُ فَتَنْفَعَهُ الذِّكْرٰىۗ',
		ayahNumber: 4,
		translationId: 'atau dia (ingin) mendapatkan pengajaran, yang memberi manfaat kepadanya?',
	),
	Ayah(
		ayahId: 5763,
		ayahText: 'اَمَّا مَنِ اسْتَغْنٰىۙ',
		ayahNumber: 5,
		translationId: 'Adapun orang yang merasa dirinya serba cukup (pembesar-pembesar Quraisy),',
	),
	Ayah(
		ayahId: 5764,
		ayahText: 'فَاَنْتَ لَهٗ تَصَدّٰىۗ',
		ayahNumber: 6,
		translationId: 'maka engkau (Muhammad) memberi perhatian kepadanya,',
	),
	Ayah(
		ayahId: 5765,
		ayahText: 'وَمَا عَلَيْكَ اَلَّا يَزَّكّٰىۗ',
		ayahNumber: 7,
		translationId: 'padahal tidak ada (cela) atasmu kalau dia tidak menyucikan diri (beriman).',
	),
	Ayah(
		ayahId: 5766,
		ayahText: 'وَاَمَّا مَنْ جَاۤءَكَ يَسْعٰىۙ',
		ayahNumber: 8,
		translationId: 'Dan adapun orang yang datang kepadamu dengan bersegera (untuk mendapatkan pengajaran),',
	),
	Ayah(
		ayahId: 5767,
		ayahText: 'وَهُوَ يَخْشٰىۙ',
		ayahNumber: 9,
		translationId: 'sedang dia takut (kepada Allah),',
	),
	Ayah(
		ayahId: 5768,
		ayahText: 'فَاَنْتَ عَنْهُ تَلَهّٰىۚ',
		ayahNumber: 10,
		translationId: 'engkau (Muhammad) malah mengabaikannya.',
	),
	Ayah(
		ayahId: 5769,
		ayahText: 'كَلَّآ اِنَّهَا تَذْكِرَةٌ ۚ',
		ayahNumber: 11,
		translationId: 'Sekali-kali jangan (begitu)! Sungguh, (ajaran-ajaran Allah) itu suatu peringatan,',
	),
	Ayah(
		ayahId: 5770,
		ayahText: 'فَمَنْ شَاۤءَ ذَكَرَهٗ ۘ',
		ayahNumber: 12,
		translationId: 'maka barangsiapa menghendaki, tentulah dia akan memperhatikannya,',
	),
	Ayah(
		ayahId: 5771,
		ayahText: 'فِيْ صُحُفٍ مُّكَرَّمَةٍۙ',
		ayahNumber: 13,
		translationId: 'di dalam kitab-kitab yang dimuliakan (di sisi Allah),',
	),
	Ayah(
		ayahId: 5772,
		ayahText: 'مَّرْفُوْعَةٍ مُّطَهَّرَةٍ ۢ ۙ',
		ayahNumber: 14,
		translationId: 'yang ditinggikan (dan) disucikan,',
	),
	Ayah(
		ayahId: 5773,
		ayahText: 'بِاَيْدِيْ سَفَرَةٍۙ',
		ayahNumber: 15,
		translationId: 'di tangan para utusan (malaikat),',
	),
	Ayah(
		ayahId: 5774,
		ayahText: 'كِرَامٍۢ بَرَرَةٍۗ',
		ayahNumber: 16,
		translationId: 'yang mulia lagi berbakti.',
	),
	Ayah(
		ayahId: 5775,
		ayahText: 'قُتِلَ الْاِنْسَانُ مَآ اَكْفَرَهٗۗ',
		ayahNumber: 17,
		translationId: 'Celakalah manusia! Alangkah kufurnya dia!',
	),
	Ayah(
		ayahId: 5776,
		ayahText: 'مِنْ اَيِّ شَيْءٍ خَلَقَهٗۗ',
		ayahNumber: 18,
		translationId: 'Dari apakah Dia (Allah) menciptakannya?',
	),
	Ayah(
		ayahId: 5777,
		ayahText: 'مِنْ نُّطْفَةٍۗ خَلَقَهٗ فَقَدَّرَهٗۗ',
		ayahNumber: 19,
		translationId: 'Dari setetes mani, Dia menciptakannya lalu menentukannya.',
	),
	Ayah(
		ayahId: 5778,
		ayahText: 'ثُمَّ السَّبِيْلَ يَسَّرَهٗۙ',
		ayahNumber: 20,
		translationId: 'Kemudian jalannya Dia mudahkan,',
	),
	Ayah(
		ayahId: 5779,
		ayahText: 'ثُمَّ اَمَاتَهٗ فَاَقْبَرَهٗۙ',
		ayahNumber: 21,
		translationId: 'kemudian Dia mematikannya lalu menguburkannya,',
	),
	Ayah(
		ayahId: 5780,
		ayahText: 'ثُمَّ اِذَا شَاۤءَ اَنْشَرَهٗۗ',
		ayahNumber: 22,
		translationId: 'kemudian jika Dia menghendaki, Dia membangkitkannya kembali.',
	),
	Ayah(
		ayahId: 5781,
		ayahText: 'كَلَّا لَمَّا يَقْضِ مَآ اَمَرَهٗۗ',
		ayahNumber: 23,
		translationId: 'Sekali-kali jangan (begitu)! Dia (manusia) itu belum melaksanakan apa yang Dia (Allah) perintahkan kepadanya.',
	),
	Ayah(
		ayahId: 5782,
		ayahText: 'فَلْيَنْظُرِ الْاِنْسَانُ اِلٰى طَعَامِهٖٓ ۙ ',
		ayahNumber: 24,
		translationId: 'Maka hendaklah manusia itu memperhatikan makanannya.',
	),
	Ayah(
		ayahId: 5783,
		ayahText: 'اَنَّا صَبَبْنَا الْمَاۤءَ صَبًّاۙ',
		ayahNumber: 25,
		translationId: 'Kamilah yang telah mencurahkan air melimpah (dari langit),',
	),
	Ayah(
		ayahId: 5784,
		ayahText: 'ثُمَّ شَقَقْنَا الْاَرْضَ شَقًّاۙ',
		ayahNumber: 26,
		translationId: 'kemudian Kami belah bumi dengan sebaik-baiknya,',
	),
	Ayah(
		ayahId: 5785,
		ayahText: 'فَاَنْۢبَتْنَا فِيْهَا حَبًّاۙ',
		ayahNumber: 27,
		translationId: 'lalu di sana Kami tumbuhkan biji-bijian,',
	),
	Ayah(
		ayahId: 5786,
		ayahText: 'وَّعِنَبًا وَّقَضْبًاۙ',
		ayahNumber: 28,
		translationId: 'dan anggur dan sayur-sayuran,',
	),
	Ayah(
		ayahId: 5787,
		ayahText: 'وَّزَيْتُوْنًا وَّنَخْلًاۙ',
		ayahNumber: 29,
		translationId: 'dan zaitun dan pohon kurma,',
	),
	Ayah(
		ayahId: 5788,
		ayahText: 'وَّحَدَاۤئِقَ غُلْبًا',
		ayahNumber: 30,
		translationId: 'dan kebun-kebun (yang) rindang,',
	),
	Ayah(
		ayahId: 5789,
		ayahText: 'وَفَاكِهَةً وَّاَبًّا',
		ayahNumber: 31,
		translationId: 'dan buah-buahan serta rerumputan.',
	),
	Ayah(
		ayahId: 5790,
		ayahText: 'مَتَاعًا لَّكُمْ وَلِاَنْعَامِكُمْۗ',
		ayahNumber: 32,
		translationId: '(Semua itu) untuk kesenanganmu dan untuk hewan-hewan ternakmu.',
	),
	Ayah(
		ayahId: 5791,
		ayahText: 'فَاِذَا جَاۤءَتِ الصَّاۤخَّةُ ۖ',
		ayahNumber: 33,
		translationId: 'Maka apabila datang suara yang memekakkan (tiupan sangkakala yang kedua),',
	),
	Ayah(
		ayahId: 5792,
		ayahText: 'يَوْمَ يَفِرُّ الْمَرْءُ مِنْ اَخِيْهِۙ',
		ayahNumber: 34,
		translationId: 'pada hari itu manusia lari dari saudaranya,',
	),
	Ayah(
		ayahId: 5793,
		ayahText: 'وَاُمِّهٖ وَاَبِيْهِۙ',
		ayahNumber: 35,
		translationId: 'dan dari ibu dan bapaknya,',
	),
	Ayah(
		ayahId: 5794,
		ayahText: 'وَصَاحِبَتِهٖ وَبَنِيْهِۗ',
		ayahNumber: 36,
		translationId: 'dan dari istri dan anak-anaknya.',
	),
	Ayah(
		ayahId: 5795,
		ayahText: 'لِكُلِّ امْرِئٍ مِّنْهُمْ يَوْمَىِٕذٍ شَأْنٌ يُّغْنِيْهِۗ',
		ayahNumber: 37,
		translationId: 'Setiap orang dari mereka pada hari itu mempunyai urusan yang menyibukkannya.',
	),
	Ayah(
		ayahId: 5796,
		ayahText: 'وُجُوْهٌ يَّوْمَىِٕذٍ مُّسْفِرَةٌۙ',
		ayahNumber: 38,
		translationId: 'Pada hari itu ada wajah-wajah yang berseri-seri,',
	),
	Ayah(
		ayahId: 5797,
		ayahText: 'ضَاحِكَةٌ مُّسْتَبْشِرَةٌ ۚ',
		ayahNumber: 39,
		translationId: 'tertawa dan gembira ria,',
	),
	Ayah(
		ayahId: 5798,
		ayahText: 'وَوُجُوْهٌ يَّوْمَىِٕذٍ عَلَيْهَا غَبَرَةٌۙ',
		ayahNumber: 40,
		translationId: 'dan pada hari itu ada (pula) wajah-wajah yang tertutup debu (suram),',
	),
	Ayah(
		ayahId: 5799,
		ayahText: 'تَرْهَقُهَا قَتَرَةٌ ۗ',
		ayahNumber: 41,
		translationId: 'tertutup oleh kegelapan (ditimpa kehinaan dan kesusahan).',
	),
	Ayah(
		ayahId: 5800,
		ayahText: 'اُولٰۤىِٕكَ هُمُ الْكَفَرَةُ الْفَجَرَةُ ࣖ',
		ayahNumber: 42,
		translationId: 'Mereka itulah orang-orang kafir yang durhaka.',
	),
];
