// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah15 = [
	Ayah(
		ayahId: 1803,
		ayahText: 'الۤرٰ ۗتِلْكَ اٰيٰتُ الْكِتٰبِ وَقُرْاٰنٍ مُّبِيْنٍ  ۔',
		ayahNumber: 1,
		translationId: "Alif Lam Ra. (Surah) ini adalah (sebagian dari) ayat-ayat Kitab (yang sempurna) yaitu (ayat-ayat) Al-Qur'an yang memberi penjelasan.",
	),
	Ayah(
		ayahId: 1804,
		ayahText: 'رُبَمَا يَوَدُّ الَّذِيْنَ كَفَرُوْا لَوْ كَانُوْا مُسْلِمِيْنَ ',
		ayahNumber: 2,
		translationId: 'Orang kafir itu kadang-kadang (nanti di akhirat) menginginkan, sekiranya mereka dahulu (di dunia) menjadi orang Muslim.',
	),
	Ayah(
		ayahId: 1805,
		ayahText: 'ذَرْهُمْ يَأْكُلُوْا وَيَتَمَتَّعُوْا وَيُلْهِهِمُ الْاَمَلُ فَسَوْفَ يَعْلَمُوْنَ ',
		ayahNumber: 3,
		translationId: 'Biarkanlah mereka (di dunia ini) makan dan bersenang-senang dan dilalaikan oleh angan-angan (kosong) mereka, kelak mereka akan mengetahui (akibat perbuatannya).',
	),
	Ayah(
		ayahId: 1806,
		ayahText: 'وَمَآ اَهْلَكْنَا مِنْ قَرْيَةٍ اِلَّا وَلَهَا كِتَابٌ مَّعْلُوْمٌ ',
		ayahNumber: 4,
		translationId: 'Dan Kami tidak membinasakan suatu negeri, melainkan sudah ada ketentuan yang ditetapkan baginya.',
	),
	Ayah(
		ayahId: 1807,
		ayahText: 'مَا تَسْبِقُ مِنْ اُمَّةٍ اَجَلَهَا وَمَا يَسْتَأْخِرُوْنَ ',
		ayahNumber: 5,
		translationId: 'Tidak ada suatu umat pun yang dapat mendahului ajalnya, dan tidak (pula) dapat meminta penundaan(nya).',
	),
	Ayah(
		ayahId: 1808,
		ayahText: 'وَقَالُوْا يٰٓاَيُّهَا الَّذِيْ نُزِّلَ عَلَيْهِ الذِّكْرُ اِنَّكَ لَمَجْنُوْنٌ  ۗ  ',
		ayahNumber: 6,
		translationId: "Dan mereka berkata, “Wahai orang yang kepadanya diturunkan Al-Qur'an, sesungguhnya engkau (Muhammad) benar-benar orang gila.",
	),
	Ayah(
		ayahId: 1809,
		ayahText: 'لَوْمَا تَأْتِيْنَا بِالْمَلٰۤىِٕكَةِ اِنْ كُنْتَ مِنَ الصّٰدِقِيْنَ ',
		ayahNumber: 7,
		translationId: 'Mengapa engkau tidak mendatangkan malaikat kepada kami, jika engkau termasuk orang yang benar?”',
	),
	Ayah(
		ayahId: 1810,
		ayahText: 'مَا نُنَزِّلُ الْمَلٰۤىِٕكَةَ اِلَّا بِالْحَقِّ وَمَا كَانُوْٓا اِذًا مُّنْظَرِيْنَ ',
		ayahNumber: 8,
		translationId: 'Kami tidak menurunkan malaikat melainkan dengan kebenaran (untuk membawa azab) dan mereka ketika itu tidak diberikan penangguhan',
	),
	Ayah(
		ayahId: 1811,
		ayahText: 'اِنَّا نَحْنُ نَزَّلْنَا الذِّكْرَ وَاِنَّا لَهٗ لَحٰفِظُوْنَ ',
		ayahNumber: 9,
		translationId: "Sesungguhnya Kamilah yang menurunkan Al-Qur'an, dan pasti Kami (pula) yang memeliharanya.",
	),
	Ayah(
		ayahId: 1812,
		ayahText: 'وَلَقَدْ اَرْسَلْنَا مِنْ قَبْلِكَ فِيْ شِيَعِ الْاَوَّلِيْنَ ',
		ayahNumber: 10,
		translationId: 'Dan sungguh, Kami telah mengutus (beberapa rasul) sebelum engkau (Muhammad) kepada umat-umat terdahulu.',
	),
	Ayah(
		ayahId: 1813,
		ayahText: 'وَمَا يَأْتِيْهِمْ مِّنْ رَّسُوْلٍ اِلَّا كَانُوْا بِهٖ يَسْتَهْزِءُوْنَ ',
		ayahNumber: 11,
		translationId: 'Dan setiap kali seorang rasul datang kepada mereka, mereka selalu memperolok-olokannya.',
	),
	Ayah(
		ayahId: 1814,
		ayahText: 'كَذٰلِكَ نَسْلُكُهٗ فِيْ قُلُوْبِ الْمُجْرِمِيْنَۙ',
		ayahNumber: 12,
		translationId: 'Demikianlah, Kami memasukkannya (olok-olok itu) ke dalam hati orang yang berdosa,',
	),
	Ayah(
		ayahId: 1815,
		ayahText: 'لَا يُؤْمِنُوْنَ بِهٖ وَقَدْ خَلَتْ سُنَّةُ الْاَوَّلِيْنَ ',
		ayahNumber: 13,
		translationId: "mereka tidak beriman kepadanya (Al-Qur'an) padahal telah berlalu sunatullah terhadap orang-orang terdahulu.",
	),
	Ayah(
		ayahId: 1816,
		ayahText: 'وَلَوْ فَتَحْنَا عَلَيْهِمْ بَابًا مِّنَ السَّمَاۤءِ فَظَلُّوْا فِيْهِ يَعْرُجُوْنَۙ',
		ayahNumber: 14,
		translationId: 'Dan kalau Kami bukakan kepada mereka salah satu pintu langit, lalu mereka terus menerus naik ke atasnya,',
	),
	Ayah(
		ayahId: 1817,
		ayahText: 'لَقَالُوْٓا اِنَّمَا سُكِّرَتْ اَبْصَارُنَا بَلْ نَحْنُ قَوْمٌ مَّسْحُوْرُوْنَ ࣖ ',
		ayahNumber: 15,
		translationId: 'tentulah mereka berkata, “Sesungguhnya pandangan kamilah yang dikaburkan, bahkan kami adalah orang yang terkena sihir.”  ',
	),
	Ayah(
		ayahId: 1818,
		ayahText: 'وَلَقَدْ جَعَلْنَا فِى السَّمَاۤءِ بُرُوْجًا وَّزَيَّنّٰهَا لِلنّٰظِرِيْنَۙ',
		ayahNumber: 16,
		translationId: 'Dan sungguh, Kami telah menciptakan gugusan bintang di langit dan men-jadikannya terasa indah bagi orang yang memandang(nya),',
	),
	Ayah(
		ayahId: 1819,
		ayahText: 'وَحَفِظْنٰهَا مِنْ كُلِّ شَيْطٰنٍ رَّجِيْمٍۙ',
		ayahNumber: 17,
		translationId: 'dan Kami menjaganya dari setiap (gangguan) setan yang terkutuk,',
	),
	Ayah(
		ayahId: 1820,
		ayahText: 'اِلَّا مَنِ اسْتَرَقَ السَّمْعَ فَاَتْبَعَهٗ شِهَابٌ مُّبِيْنٌ ',
		ayahNumber: 18,
		translationId: 'kecuali (setan) yang mencuri-curi (berita) yang dapat didengar (dari malaikat) lalu dikejar oleh semburan api yang terang.',
	),
	Ayah(
		ayahId: 1821,
		ayahText: 'وَالْاَرْضَ مَدَدْنٰهَا وَاَلْقَيْنَا فِيْهَا رَوَاسِيَ وَاَنْۢبَتْنَا فِيْهَا مِنْ كُلِّ شَيْءٍ مَّوْزُوْنٍ',
		ayahNumber: 19,
		translationId: 'Dan Kami telah menghamparkan bumi dan Kami pancangkan padanya gunung-gunung serta Kami tumbuhkan di sana segala sesuatu menurut ukuran.',
	),
	Ayah(
		ayahId: 1822,
		ayahText: 'وَجَعَلْنَا لَكُمْ فِيْهَا مَعَايِشَ وَمَنْ لَّسْتُمْ لَهٗ بِرَازِقِيْنَ ',
		ayahNumber: 20,
		translationId: 'Dan Kami telah menjadikan padanya sumber-sumber kehidupan untuk keperluanmu, dan (Kami ciptakan pula) makhluk-makhluk yang bukan kamu pemberi rezekinya.',
	),
	Ayah(
		ayahId: 1823,
		ayahText: 'وَاِنْ مِّنْ شَيْءٍ اِلَّا عِنْدَنَا خَزَاۤىِٕنُهٗ وَمَا نُنَزِّلُهٗٓ اِلَّا بِقَدَرٍ مَّعْلُوْمٍ ',
		ayahNumber: 21,
		translationId: 'Dan tidak ada sesuatu pun, melainkan pada sisi Kamilah khazanahnya; Kami tidak menurunkannya melainkan dengan ukuran tertentu.',
	),
	Ayah(
		ayahId: 1824,
		ayahText: 'وَاَرْسَلْنَا الرِّيٰحَ لَوَاقِحَ فَاَنْزَلْنَا مِنَ السَّمَاۤءِ مَاۤءً فَاَسْقَيْنٰكُمُوْهُۚ وَمَآ اَنْتُمْ لَهٗ بِخَازِنِيْنَ',
		ayahNumber: 22,
		translationId: 'Dan Kami telah meniupkan angin untuk mengawinkan dan Kami turunkan hujan dari langit, lalu Kami beri minum kamu dengan (air) itu, dan bukanlah kamu yang menyimpannya.',
	),
	Ayah(
		ayahId: 1825,
		ayahText: 'وَاِنَّا لَنَحْنُ نُحْيٖ وَنُمِيْتُ وَنَحْنُ الْوَارِثُوْنَ ',
		ayahNumber: 23,
		translationId: 'Dan sungguh, Kamilah yang menghidupkan dan mematikan dan Kami (pulalah) yang mewarisi.',
	),
	Ayah(
		ayahId: 1826,
		ayahText: 'وَلَقَدْ عَلِمْنَا الْمُسْتَقْدِمِيْنَ مِنْكُمْ وَلَقَدْ عَلِمْنَا الْمُسْتَأْخِرِيْنَ ',
		ayahNumber: 24,
		translationId: 'Dan sungguh, Kami mengetahui orang yang terdahulu sebelum kamu dan Kami mengetahui pula orang yang terkemudian.',
	),
	Ayah(
		ayahId: 1827,
		ayahText: 'وَاِنَّ رَبَّكَ هُوَ يَحْشُرُهُمْۗ اِنَّهٗ حَكِيْمٌ عَلِيْمٌ ࣖ ',
		ayahNumber: 25,
		translationId: 'Dan sesungguhnya Tuhanmu, Dialah yang akan mengumpulkan mereka. Sungguh, Dia Mahabijaksana, Maha Mengetahui.',
	),
	Ayah(
		ayahId: 1828,
		ayahText: 'وَلَقَدْ خَلَقْنَا الْاِنْسَانَ مِنْ صَلْصَالٍ مِّنْ حَمَاٍ مَّسْنُوْنٍۚ  ',
		ayahNumber: 26,
		translationId: 'Dan sungguh, Kami telah menciptakan manusia (Adam) dari tanah liat kering dari lumpur hitam yang diberi bentuk.',
	),
	Ayah(
		ayahId: 1829,
		ayahText: 'وَالْجَاۤنَّ خَلَقْنٰهُ مِنْ قَبْلُ مِنْ نَّارِ السَّمُوْمِ  ',
		ayahNumber: 27,
		translationId: 'Dan Kami telah menciptakan jin sebelum (Adam) dari api yang sangat panas.',
	),
	Ayah(
		ayahId: 1830,
		ayahText: 'وَاِذْ قَالَ رَبُّكَ لِلْمَلٰۤىِٕكَةِ اِنِّيْ خَالِقٌۢ بَشَرًا مِّنْ صَلْصَالٍ مِّنْ حَمَاٍ مَّسْنُوْنٍۚ  ',
		ayahNumber: 28,
		translationId: 'Dan (ingatlah), ketika Tuhanmu berfirman kepada para malaikat, “Sungguh, Aku akan menciptakan seorang manusia dari tanah liat kering dari lumpur hitam yang diberi bentuk.',
	),
	Ayah(
		ayahId: 1831,
		ayahText: 'فَاِذَا سَوَّيْتُهٗ وَنَفَخْتُ فِيْهِ مِنْ رُّوْحِيْ فَقَعُوْا لَهٗ سٰجِدِيْنَ ',
		ayahNumber: 29,
		translationId: 'Maka apabila Aku telah menyempurnakan (kejadian)nya, dan Aku telah meniupkan roh (ciptaan)-Ku ke dalamnya, maka tunduklah kamu kepadanya dengan bersujud.”',
	),
	Ayah(
		ayahId: 1832,
		ayahText: 'فَسَجَدَ الْمَلٰۤىِٕكَةُ كُلُّهُمْ اَجْمَعُوْنَۙ',
		ayahNumber: 30,
		translationId: 'Maka bersujudlah para malaikat itu semuanya bersama-sama,',
	),
	Ayah(
		ayahId: 1833,
		ayahText: 'اِلَّآ اِبْلِيْسَۗ اَبٰىٓ اَنْ يَّكُوْنَ مَعَ السّٰجِدِيْنَ ',
		ayahNumber: 31,
		translationId: 'kecuali Iblis. Ia enggan ikut bersama-sama para (malaikat) yang sujud itu.',
	),
	Ayah(
		ayahId: 1834,
		ayahText: 'قَالَ يٰٓاِبْلِيْسُ مَا لَكَ اَلَّا تَكُوْنَ مَعَ السّٰجِدِيْنَ ',
		ayahNumber: 32,
		translationId: 'Dia (Allah) berfirman, “Wahai Iblis! Apa sebabnya kamu (tidak ikut) sujud bersama mereka?”',
	),
	Ayah(
		ayahId: 1835,
		ayahText: 'قَالَ لَمْ اَكُنْ لِّاَسْجُدَ لِبَشَرٍ خَلَقْتَهٗ مِنْ صَلْصَالٍ مِّنْ حَمَاٍ مَّسْنُوْنٍ ',
		ayahNumber: 33,
		translationId: 'Ia (Iblis) berkata, “Aku sekali-kali tidak akan sujud kepada manusia yang Engkau telah menciptakannya dari tanah liat kering dari lumpur hitam yang diberi bentuk.”',
	),
	Ayah(
		ayahId: 1836,
		ayahText: 'قَالَ فَاخْرُجْ مِنْهَا فَاِنَّكَ رَجِيْمٌۙ',
		ayahNumber: 34,
		translationId: 'Dia (Allah) berfirman, “(Kalau begitu) keluarlah dari surga, karena sesungguhnya kamu terkutuk,',
	),
	Ayah(
		ayahId: 1837,
		ayahText: 'وَّاِنَّ عَلَيْكَ اللَّعْنَةَ اِلٰى يَوْمِ الدِّيْنِ ',
		ayahNumber: 35,
		translationId: ' dan sesungguhnya kutukan itu tetap menimpamu sampai hari Kiamat.” ',
	),
	Ayah(
		ayahId: 1838,
		ayahText: 'قَالَ رَبِّ فَاَنْظِرْنِيْٓ اِلٰى يَوْمِ يُبْعَثُوْنَ ',
		ayahNumber: 36,
		translationId: 'Ia (Iblis) berkata, “Ya Tuhanku,  (kalau begitu) maka berilah penangguhan kepadaku sampai hari (manusia) dibangkitkan.”',
	),
	Ayah(
		ayahId: 1839,
		ayahText: 'قَالَ فَاِنَّكَ مِنَ الْمُنْظَرِيْنَۙ',
		ayahNumber: 37,
		translationId: ' Allah berfirman, “(Baiklah) maka sesungguhnya kamu termasuk yang diberi penangguhan,',
	),
	Ayah(
		ayahId: 1840,
		ayahText: 'اِلٰى يَوْمِ الْوَقْتِ الْمَعْلُوْمِ ',
		ayahNumber: 38,
		translationId: 'sampai hari yang telah ditentukan (kiamat).”',
	),
	Ayah(
		ayahId: 1841,
		ayahText: 'قَالَ رَبِّ بِمَآ اَغْوَيْتَنِيْ لَاُزَيِّنَنَّ لَهُمْ فِى الْاَرْضِ وَلَاُغْوِيَنَّهُمْ اَجْمَعِيْنَۙ  ',
		ayahNumber: 39,
		translationId: 'Ia (Iblis) berkata, “Tuhanku, oleh karena Engkau telah memutuskan bahwa aku sesat, aku pasti akan jadikan (kejahatan) terasa indah bagi mereka di bumi, dan aku akan menyesatkan mereka semuanya,',
	),
	Ayah(
		ayahId: 1842,
		ayahText: 'اِلَّا عِبَادَكَ مِنْهُمُ الْمُخْلَصِيْنَ ',
		ayahNumber: 40,
		translationId: ' kecuali hamba-hamba-Mu yang terpilih di antara mereka.”',
	),
	Ayah(
		ayahId: 1843,
		ayahText: 'قَالَ هٰذَا صِرَاطٌ عَلَيَّ مُسْتَقِيْمٌ ',
		ayahNumber: 41,
		translationId: 'Dia (Allah) berfirman, “Ini adalah jalan yang lurus (menuju) kepada-Ku.”',
	),
	Ayah(
		ayahId: 1844,
		ayahText: 'اِنَّ عِبَادِيْ لَيْسَ لَكَ عَلَيْهِمْ سُلْطٰنٌ اِلَّا مَنِ اتَّبَعَكَ مِنَ الْغٰوِيْنَ ',
		ayahNumber: 42,
		translationId: 'Sesungguhnya kamu (Iblis) tidak kuasa atas hamba-hamba-Ku, kecuali mereka yang mengikutimu, yaitu orang yang sesat.',
	),
	Ayah(
		ayahId: 1845,
		ayahText: 'وَاِنَّ جَهَنَّمَ لَمَوْعِدُهُمْ اَجْمَعِيْنَۙ',
		ayahNumber: 43,
		translationId: 'Dan sungguh, Jahanam itu benar-benar (tempat) yang telah dijanjikan untuk mereka (pengikut setan) semuanya.',
	),
	Ayah(
		ayahId: 1846,
		ayahText: 'لَهَا سَبْعَةُ اَبْوَابٍۗ لِكُلِّ بَابٍ مِّنْهُمْ جُزْءٌ مَّقْسُوْمٌ ࣖ  ',
		ayahNumber: 44,
		translationId: '(Jahanam) itu mempunyai tujuh pintu. Setiap pintu (telah ditetapkan) untuk golongan tertentu dari mereka.',
	),
	Ayah(
		ayahId: 1847,
		ayahText: 'اِنَّ الْمُتَّقِيْنَ فِيْ جَنّٰتٍ وَّعُيُوْنٍۗ  ',
		ayahNumber: 45,
		translationId: 'Sesungguhnya orang yang bertakwa itu berada dalam surga-surga (taman-taman), dan (di dekat) mata air (yang mengalir).',
	),
	Ayah(
		ayahId: 1848,
		ayahText: 'اُدْخُلُوْهَا بِسَلٰمٍ اٰمِنِيْنَ ',
		ayahNumber: 46,
		translationId: '(Allah berfirman), “Masuklah ke dalamnya dengan sejahtera dan aman.”',
	),
	Ayah(
		ayahId: 1849,
		ayahText: 'وَنَزَعْنَا مَا فِيْ صُدُوْرِهِمْ مِّنْ غِلٍّ اِخْوَانًا عَلٰى سُرُرٍ مُّتَقٰبِلِيْنَ ',
		ayahNumber: 47,
		translationId: 'Dan Kami lenyapkan segala rasa dendam yang ada dalam hati mereka; mereka merasa bersaudara, duduk berhadap-hadapan di atas dipan-dipan.',
	),
	Ayah(
		ayahId: 1850,
		ayahText: 'لَا يَمَسُّهُمْ فِيْهَا نَصَبٌ وَّمَا هُمْ مِّنْهَا بِمُخْرَجِيْنَ ',
		ayahNumber: 48,
		translationId: 'Mereka tidak merasa lelah di dalamnya dan mereka tidak akan dikeluarkan darinya.',
	),
	Ayah(
		ayahId: 1851,
		ayahText: '۞ نَبِّئْ عِبَادِيْٓ اَنِّيْٓ اَنَا الْغَفُوْرُ الرَّحِيْمُۙ',
		ayahNumber: 49,
		translationId: 'Kabarkanlah kepada hamba-hamba-Ku, bahwa Akulah Yang Maha Pengampun, Maha Penyayang,',
	),
	Ayah(
		ayahId: 1852,
		ayahText: 'وَاَنَّ عَذَابِيْ هُوَ الْعَذَابُ الْاَلِيْمُ ',
		ayahNumber: 50,
		translationId: 'dan sesungguhnya azab-Ku adalah azab yang sangat pedih.',
	),
	Ayah(
		ayahId: 1853,
		ayahText: 'وَنَبِّئْهُمْ عَنْ ضَيْفِ اِبْرٰهِيْمَۘ ',
		ayahNumber: 51,
		translationId: 'Dan kabarkanlah (Muhammad) kepada mereka tentang tamu Ibrahim (malaikat).',
	),
	Ayah(
		ayahId: 1854,
		ayahText: 'اِذْ دَخَلُوْا عَلَيْهِ فَقَالُوْا سَلٰمًاۗ قَالَ اِنَّا مِنْكُمْ وَجِلُوْنَ ',
		ayahNumber: 52,
		translationId: 'Ketika mereka masuk ke tempatnya, lalu mereka mengucapkan, “Salam.” Dia (Ibrahim) berkata, “Kami benar-benar merasa takut kepadamu.” ',
	),
	Ayah(
		ayahId: 1855,
		ayahText: 'قَالُوْا لَا تَوْجَلْ اِنَّا نُبَشِّرُكَ بِغُلٰمٍ عَلِيْمٍ ',
		ayahNumber: 53,
		translationId: '(Mereka) berkata, “Janganlah engkau merasa takut, sesungguhnya kami memberi kabar gembira kepadamu dengan (kelahiran seorang) anak laki-laki (yang akan menjadi) orang yang pandai (Ishak).”  ',
	),
	Ayah(
		ayahId: 1856,
		ayahText: 'قَالَ اَبَشَّرْتُمُوْنِيْ عَلٰٓى اَنْ مَّسَّنِيَ الْكِبَرُ فَبِمَ تُبَشِّرُوْنَ ',
		ayahNumber: 54,
		translationId: 'Dia (Ibrahim) berkata, “Benarkah kamu memberi kabar gembira kepadaku padahal usiaku telah lanjut, lalu (dengan cara) bagaimana kamu memberi (kabar gembira) tersebut?”',
	),
	Ayah(
		ayahId: 1857,
		ayahText: 'قَالُوْا بَشَّرْنٰكَ بِالْحَقِّ فَلَا تَكُنْ مِّنَ الْقٰنِطِيْنَ ',
		ayahNumber: 55,
		translationId: '(Mereka) menjawab, “Kami menyampaikan kabar gembira kepadamu dengan benar, maka janganlah engkau termasuk orang yang berputus asa.”',
	),
	Ayah(
		ayahId: 1858,
		ayahText: 'قَالَ وَمَنْ يَّقْنَطُ مِنْ رَّحْمَةِ رَبِّهٖٓ اِلَّا الضَّاۤلُّوْنَ ',
		ayahNumber: 56,
		translationId: 'Dia (Ibrahim) berkata, “Tidak ada yang berputus asa dari rahmat Tuhannya, kecuali orang yang sesat.”',
	),
	Ayah(
		ayahId: 1859,
		ayahText: 'قَالَ فَمَا خَطْبُكُمْ اَيُّهَا الْمُرْسَلُوْنَ ',
		ayahNumber: 57,
		translationId: ' Dia (Ibrahim) berkata, “Apakah urusanmu yang penting, wahai para utusan?”',
	),
	Ayah(
		ayahId: 1860,
		ayahText: 'قَالُوْٓا اِنَّآ اُرْسِلْنَآ اِلٰى قَوْمٍ مُّجْرِمِيْنَۙ',
		ayahNumber: 58,
		translationId: '(Mereka) menjawab, “Sesungguhnya kami diutus kepada kaum yang berdosa,',
	),
	Ayah(
		ayahId: 1861,
		ayahText: 'اِلَّآ اٰلَ لُوْطٍۗ اِنَّا لَمُنَجُّوْهُمْ اَجْمَعِيْنَۙ',
		ayahNumber: 59,
		translationId: 'kecuali para pengikut Lut. Sesungguhnya kami pasti menyelamatkan mereka semuanya,',
	),
	Ayah(
		ayahId: 1862,
		ayahText: 'اِلَّا امْرَاَتَهٗ قَدَّرْنَآ اِنَّهَا لَمِنَ الْغٰبِرِيْنَ ࣖ ',
		ayahNumber: 60,
		translationId: 'kecuali istrinya, kami telah menentukan, bahwa dia termasuk orang yang tertinggal (bersama orang kafir lainnya).”',
	),
	Ayah(
		ayahId: 1863,
		ayahText: 'فَلَمَّا جَاۤءَ اٰلَ لُوْطِ ِۨالْمُرْسَلُوْنَۙ',
		ayahNumber: 61,
		translationId: 'Maka ketika utusan itu datang kepada para pengikut Lut,',
	),
	Ayah(
		ayahId: 1864,
		ayahText: 'قَالَ اِنَّكُمْ قَوْمٌ مُّنْكَرُوْنَ ',
		ayahNumber: 62,
		translationId: 'dia (Lut) berkata, “Sesungguhnya kamu orang yang tidak kami kenal.” ',
	),
	Ayah(
		ayahId: 1865,
		ayahText: 'قَالُوْا بَلْ جِئْنٰكَ بِمَا كَانُوْا فِيْهِ يَمْتَرُوْنَ ',
		ayahNumber: 63,
		translationId: '(Para utusan) menjawab, “Sebenarnya kami ini datang kepadamu membawa azab yang selalu mereka dustakan.',
	),
	Ayah(
		ayahId: 1866,
		ayahText: 'وَاَتَيْنٰكَ بِالْحَقِّ وَاِنَّا لَصٰدِقُوْنَ ',
		ayahNumber: 64,
		translationId: 'Dan kami datang kepadamu membawa kebenaran dan sungguh, kami orang yang benar.',
	),
	Ayah(
		ayahId: 1867,
		ayahText: 'فَاَسْرِ بِاَهْلِكَ بِقِطْعٍ مِّنَ الَّيْلِ وَاتَّبِعْ اَدْبَارَهُمْ وَلَا يَلْتَفِتْ مِنْكُمْ اَحَدٌ وَّامْضُوْا حَيْثُ تُؤْمَرُوْنَ ',
		ayahNumber: 65,
		translationId: 'Maka pergilah kamu pada akhir malam beserta keluargamu, dan ikutilah mereka dari belakang. Jangan ada di antara kamu yang menoleh ke belakang dan teruskanlah perjalanan ke tempat yang diperintahkan kepadamu.”  ',
	),
	Ayah(
		ayahId: 1868,
		ayahText: 'وَقَضَيْنَآ اِلَيْهِ ذٰلِكَ الْاَمْرَ اَنَّ دَابِرَ هٰٓؤُلَاۤءِ مَقْطُوْعٌ مُّصْبِحِيْنَ ',
		ayahNumber: 66,
		translationId: 'Dan telah Kami tetapkan kepadanya (Lut) keputusan itu, bahwa akhirnya mereka akan ditumpas habis pada waktu subuh.',
	),
	Ayah(
		ayahId: 1869,
		ayahText: 'وَجَاۤءَ اَهْلُ الْمَدِيْنَةِ يَسْتَبْشِرُوْنَ ',
		ayahNumber: 67,
		translationId: 'Dan datanglah penduduk kota itu (ke rumah Lut) dengan gembira (karena kedatangan tamu itu).',
	),
	Ayah(
		ayahId: 1870,
		ayahText: 'قَالَ اِنَّ هٰٓؤُلَاۤءِ ضَيْفِيْ فَلَا تَفْضَحُوْنِۙ',
		ayahNumber: 68,
		translationId: 'Dia (Lut) berkata, “Sesungguhnya mereka adalah tamuku; maka jangan kamu mempermalukan aku,',
	),
	Ayah(
		ayahId: 1871,
		ayahText: 'وَاتَّقُوا اللّٰهَ وَلَا تُخْزُوْنِ ',
		ayahNumber: 69,
		translationId: 'Dan bertakwalah kepada Allah dan janganlah kamu membuat aku terhina.” ',
	),
	Ayah(
		ayahId: 1872,
		ayahText: 'قَالُوْٓا اَوَلَمْ نَنْهَكَ عَنِ الْعٰلَمِيْنَ ',
		ayahNumber: 70,
		translationId: ' (Mereka) berkata, “Bukankah kami telah melarangmu dari (melindungi) manusia?”',
	),
	Ayah(
		ayahId: 1873,
		ayahText: 'قَالَ هٰٓؤُلَاۤءِ بَنٰتِيْٓ اِنْ كُنْتُمْ فٰعِلِيْنَۗ ',
		ayahNumber: 71,
		translationId: 'Dia (Lut) berkata, “Mereka itulah putri-putri (negeri)ku (nikahlah dengan mereka), jika kamu hendak berbuat.”',
	),
	Ayah(
		ayahId: 1874,
		ayahText: 'لَعَمْرُكَ اِنَّهُمْ لَفِيْ سَكْرَتِهِمْ يَعْمَهُوْنَ ',
		ayahNumber: 72,
		translationId: '(Allah berfirman), “Demi umurmu (Muhammad), sungguh, mereka terombang-ambing dalam kemabukan (kesesatan).”',
	),
	Ayah(
		ayahId: 1875,
		ayahText: 'فَاَخَذَتْهُمُ الصَّيْحَةُ مُشْرِقِيْنَۙ',
		ayahNumber: 73,
		translationId: 'Maka mereka dibinasakan oleh suara keras yang mengguntur, ketika matahari akan terbit.',
	),
	Ayah(
		ayahId: 1876,
		ayahText: 'فَجَعَلْنَا عَالِيَهَا سَافِلَهَا وَاَمْطَرْنَا عَلَيْهِمْ حِجَارَةً مِّنْ سِجِّيْلٍ ',
		ayahNumber: 74,
		translationId: 'Maka Kami jungkirbalikkan (negeri itu) dan Kami hujani mereka dengan batu dari tanah yang keras.',
	),
	Ayah(
		ayahId: 1877,
		ayahText: 'اِنَّ فِيْ ذٰلِكَ لَاٰيٰتٍ لِّلْمُتَوَسِّمِيْنَۙ',
		ayahNumber: 75,
		translationId: 'Sungguh, pada yang demikian itu benar-benar terdapat tanda-tanda (kekuasaan Allah) bagi orang yang memperhatikan tanda-tanda,',
	),
	Ayah(
		ayahId: 1878,
		ayahText: 'وَاِنَّهَا لَبِسَبِيْلٍ مُّقِيْمٍ ',
		ayahNumber: 76,
		translationId: 'dan sungguh, (negeri) itu benar-benar terletak di jalan yang masih tetap (dilalui manusia).',
	),
	Ayah(
		ayahId: 1879,
		ayahText: 'اِنَّ فِيْ ذٰلِكَ لَاٰيَةً لِّلْمُؤْمِنِيْنَۗ  ',
		ayahNumber: 77,
		translationId: 'Sungguh, pada yang demikian itu benar-benar terdapat tanda (kekuasaan Allah) bagi orang yang beriman.',
	),
	Ayah(
		ayahId: 1880,
		ayahText: 'وَاِنْ كَانَ اَصْحٰبُ الْاَيْكَةِ لَظٰلِمِيْنَۙ',
		ayahNumber: 78,
		translationId: 'Dan sesungguhnya penduduk Aikah itu benar-benar kaum yang zalim,',
	),
	Ayah(
		ayahId: 1881,
		ayahText: 'فَانْتَقَمْنَا مِنْهُمْۘ وَاِنَّهُمَا لَبِاِمَامٍ مُّبِيْنٍۗ  ࣖ  ',
		ayahNumber: 79,
		translationId: 'maka Kami membinasakan mereka. Dan sesungguhnya kedua (negeri) itu terletak di satu jalur jalan raya.',
	),
	Ayah(
		ayahId: 1882,
		ayahText: 'وَلَقَدْ كَذَّبَ اَصْحٰبُ الْحِجْرِ الْمُرْسَلِيْنَۙ',
		ayahNumber: 80,
		translationId: 'Dan sesungguhnya penduduk negeri Hijr benar-benar telah mendustakan para rasul (mereka),',
	),
	Ayah(
		ayahId: 1883,
		ayahText: 'وَاٰتَيْنٰهُمْ اٰيٰتِنَا فَكَانُوْا عَنْهَا مُعْرِضِيْنَۙ',
		ayahNumber: 81,
		translationId: 'dan Kami telah mendatangkan kepada mereka tanda-tanda (kekuasaan) Kami, tetapi mereka selalu berpaling darinya, ',
	),
	Ayah(
		ayahId: 1884,
		ayahText: 'وَكَانُوْا يَنْحِتُوْنَ مِنَ الْجِبَالِ بُيُوْتًا اٰمِنِيْنَ ',
		ayahNumber: 82,
		translationId: 'dan mereka memahat rumah-rumah dari gunung batu, (yang didiami) dengan rasa aman.',
	),
	Ayah(
		ayahId: 1885,
		ayahText: 'فَاَخَذَتْهُمُ الصَّيْحَةُ مُصْبِحِيْنَۙ',
		ayahNumber: 83,
		translationId: 'Kemudian mereka dibinasakan oleh suara keras yang mengguntur pada pagi hari,',
	),
	Ayah(
		ayahId: 1886,
		ayahText: 'فَمَآ اَغْنٰى عَنْهُمْ مَّا كَانُوْا يَكْسِبُوْنَۗ  ',
		ayahNumber: 84,
		translationId: 'sehingga tidak berguna bagi mereka, apa yang telah mereka usahakan. ',
	),
	Ayah(
		ayahId: 1887,
		ayahText: 'وَمَا خَلَقْنَا السَّمٰوٰتِ وَالْاَرْضَ وَمَا بَيْنَهُمَآ اِلَّا بِالْحَقِّۗ وَاِنَّ السَّاعَةَ لَاٰتِيَةٌ فَاصْفَحِ الصَّفْحَ الْجَمِيْلَ ',
		ayahNumber: 85,
		translationId: 'Dan Kami tidak menciptakan langit dan bumi serta apa yang ada di antara keduanya, melainkan dengan kebenaran. Dan sungguh, Kiamat pasti akan datang, maka maafkanlah (mereka) dengan cara yang baik.',
	),
	Ayah(
		ayahId: 1888,
		ayahText: 'اِنَّ رَبَّكَ هُوَ الْخَلّٰقُ الْعَلِيْمُ ',
		ayahNumber: 86,
		translationId: 'Sungguh, Tuhanmu, Dialah Yang Maha Pencipta, Maha Mengetahui.',
	),
	Ayah(
		ayahId: 1889,
		ayahText: 'وَلَقَدْ اٰتَيْنٰكَ سَبْعًا مِّنَ الْمَثَانِيْ وَالْقُرْاٰنَ الْعَظِيْمَ ',
		ayahNumber: 87,
		translationId: "Dan sungguh, Kami telah memberikan kepadamu tujuh (ayat) yang (dibaca) berulang-ulang dan Al-Qur'an yang agung.",
	),
	Ayah(
		ayahId: 1890,
		ayahText: 'لَا تَمُدَّنَّ عَيْنَيْكَ اِلٰى مَا مَتَّعْنَا بِهٖٓ اَزْوَاجًا مِّنْهُمْ وَلَا تَحْزَنْ عَلَيْهِمْ وَاخْفِضْ جَنَاحَكَ لِلْمُؤْمِنِيْنَ ',
		ayahNumber: 88,
		translationId: 'Jangan sekali-kali engkau (Muhammad) tujukan pandanganmu kepada kenikmatan hidup yang telah Kami berikan kepada beberapa golongan di antara mereka (orang kafir), dan jangan engkau bersedih hati terhadap mereka dan berendah hatilah engkau terhadap orang yang beriman.',
	),
	Ayah(
		ayahId: 1891,
		ayahText: 'وَقُلْ اِنِّيْٓ اَنَا النَّذِيْرُ الْمُبِيْنُۚ  ',
		ayahNumber: 89,
		translationId: 'Dan katakanlah (Muhammad), “Sesungguhnya aku adalah pemberi peringatan yang jelas.”',
	),
	Ayah(
		ayahId: 1892,
		ayahText: 'كَمَآ اَنْزَلْنَا عَلَى الْمُقْتَسِمِيْنَۙ',
		ayahNumber: 90,
		translationId: 'Sebagaimana (Kami telah memberi peringatan), Kami telah menurunkan (azab) kepada orang yang memilah-milah (Kitab Allah),',
	),
	Ayah(
		ayahId: 1893,
		ayahText: 'الَّذِيْنَ جَعَلُوا الْقُرْاٰنَ عِضِيْنَ ',
		ayahNumber: 91,
		translationId: "(yaitu) orang-orang yang telah menjadikan Al-Qur'an itu terbagi-bagi.",
	),
	Ayah(
		ayahId: 1894,
		ayahText: 'فَوَرَبِّكَ لَنَسْـَٔلَنَّهُمْ اَجْمَعِيْنَۙ',
		ayahNumber: 92,
		translationId: 'Maka demi Tuhanmu, Kami pasti akan menanyai mereka semua,',
	),
	Ayah(
		ayahId: 1895,
		ayahText: 'عَمَّا كَانُوْا يَعْمَلُوْنَ ',
		ayahNumber: 93,
		translationId: 'tentang apa yang telah mereka kerjakan dahulu. ',
	),
	Ayah(
		ayahId: 1896,
		ayahText: 'فَاصْدَعْ بِمَا تُؤْمَرُ وَاَعْرِضْ عَنِ الْمُشْرِكِيْنَ ',
		ayahNumber: 94,
		translationId: 'Maka sampaikanlah (Muhammad) secara terang-terangan segala apa yang diperintahkan (kepadamu) dan berpalinglah dari orang yang musyrik.',
	),
	Ayah(
		ayahId: 1897,
		ayahText: 'اِنَّا كَفَيْنٰكَ الْمُسْتَهْزِءِيْنَۙ',
		ayahNumber: 95,
		translationId: 'Sesungguhnya Kami memelihara engkau (Muhammad) dari (kejahatan) orang yang memperolok-olokkan (engkau),',
	),
	Ayah(
		ayahId: 1898,
		ayahText: 'الَّذِيْنَ يَجْعَلُوْنَ مَعَ اللّٰهِ اِلٰهًا اٰخَرَۚ فَسَوْفَ يَعْلَمُوْنَ ',
		ayahNumber: 96,
		translationId: ' (yaitu) orang yang menganggap adanya tuhan selain Allah; mereka kelak akan mengetahui (akibatnya).',
	),
	Ayah(
		ayahId: 1899,
		ayahText: 'وَلَقَدْ نَعْلَمُ اَنَّكَ يَضِيْقُ صَدْرُكَ بِمَا يَقُوْلُوْنَۙ',
		ayahNumber: 97,
		translationId: 'Dan sungguh, Kami mengetahui bahwa dadamu menjadi sempit disebabkan apa yang mereka ucapkan, ',
	),
	Ayah(
		ayahId: 1900,
		ayahText: 'فَسَبِّحْ بِحَمْدِ رَبِّكَ وَكُنْ مِّنَ السَّاجِدِيْنَۙ',
		ayahNumber: 98,
		translationId: 'maka bertasbihlah dengan memuji Tuhanmu dan jadilah engkau di antara orang yang bersujud (salat), ',
	),
	Ayah(
		ayahId: 1901,
		ayahText: 'وَاعْبُدْ رَبَّكَ حَتّٰى يَأْتِيَكَ الْيَقِيْنُ ࣖࣖ ',
		ayahNumber: 99,
		translationId: 'Dan sembahlah Tuhanmu sampai yakin (ajal) datang kepadamu.',
	),
];
