// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah54 = [
	Ayah(
		ayahId: 4847,
		ayahText: 'اِقْتَرَبَتِ السَّاعَةُ وَانْشَقَّ الْقَمَرُ ',
		ayahNumber: 1,
		translationId: ' Saat (hari Kiamat) semakin dekat, bulan pun terbelah. ',
	),
	Ayah(
		ayahId: 4848,
		ayahText: 'وَاِنْ يَّرَوْا اٰيَةً يُّعْرِضُوْا وَيَقُوْلُوْا سِحْرٌ مُّسْتَمِرٌّ',
		ayahNumber: 2,
		translationId: 'Dan jika mereka (orang-orang musyrikin) melihat suatu tanda (mukjizat), mereka berpaling dan berkata, “(Ini adalah) sihir yang terus menerus.” ',
	),
	Ayah(
		ayahId: 4849,
		ayahText: 'وَكَذَّبُوْا وَاتَّبَعُوْٓا اَهْوَاۤءَهُمْ وَكُلُّ اَمْرٍ مُّسْتَقِرٌّ',
		ayahNumber: 3,
		translationId: 'Dan mereka mendustakan (Muhammad) dan mengikuti keinginannya, padahal setiap urusan telah ada ketetapannya.',
	),
	Ayah(
		ayahId: 4850,
		ayahText: 'وَلَقَدْ جَاۤءَهُمْ مِّنَ الْاَنْبَاۤءِ مَا فِيْهِ مُزْدَجَرٌۙ  ',
		ayahNumber: 4,
		translationId: 'Dan sungguh, telah datang kepada mereka beberapa kisah yang di dalamnya terdapat ancaman (terhadap kekafiran),',
	),
	Ayah(
		ayahId: 4851,
		ayahText: 'حِكْمَةٌ ۢ بَالِغَةٌ فَمَا تُغْنِ النُّذُرُۙ  ',
		ayahNumber: 5,
		translationId: '(itulah) suatu hikmah yang sempurna, tetapi peringatan-peringatan itu tidak berguna (bagi mereka),',
	),
	Ayah(
		ayahId: 4852,
		ayahText: 'فَتَوَلَّ عَنْهُمْ ۘ يَوْمَ يَدْعُ الدَّاعِ اِلٰى شَيْءٍ نُّكُرٍۙ  ',
		ayahNumber: 6,
		translationId: 'maka berpalinglah engkau (Muhammad) dari mereka pada hari (ketika) penyeru (malaikat) mengajak (mereka) kepada sesuatu yang tidak menyenangkan (hari pembalasan), ',
	),
	Ayah(
		ayahId: 4853,
		ayahText: 'خُشَّعًا اَبْصَارُهُمْ يَخْرُجُوْنَ مِنَ الْاَجْدَاثِ كَاَنَّهُمْ جَرَادٌ مُّنْتَشِرٌۙ  ',
		ayahNumber: 7,
		translationId: 'pandangan mereka tertunduk, ketika mereka keluar dari kuburan, seakan-akan mereka belalang yang beterbangan,',
	),
	Ayah(
		ayahId: 4854,
		ayahText: 'مُّهْطِعِيْنَ اِلَى الدَّاعِۗ يَقُوْلُ الْكٰفِرُوْنَ هٰذَا يَوْمٌ عَسِرٌ ',
		ayahNumber: 8,
		translationId: 'dengan patuh mereka segera datang kepada penyeru itu. Orang-orang kafir berkata, “Ini adalah hari yang sulit.” ',
	),
	Ayah(
		ayahId: 4855,
		ayahText: '۞ كَذَّبَتْ قَبْلَهُمْ قَوْمُ نُوْحٍ فَكَذَّبُوْا عَبْدَنَا وَقَالُوْا مَجْنُوْنٌ وَّازْدُجِرَ',
		ayahNumber: 9,
		translationId: 'Sebelum mereka, kaum Nuh juga telah mendustakan (rasul), maka mereka mendustakan hamba Kami (Nuh) dan mengatakan, “Dia orang gila!” Lalu diusirnya dengan ancaman. ',
	),
	Ayah(
		ayahId: 4856,
		ayahText: 'فَدَعَا رَبَّهٗٓ اَنِّيْ مَغْلُوْبٌ فَانْتَصِرْ',
		ayahNumber: 10,
		translationId: 'Maka dia (Nuh) mengadu kepada Tuhannya, “Sesungguhnya aku telah dikalahkan, maka tolonglah (aku).”',
	),
	Ayah(
		ayahId: 4857,
		ayahText: 'فَفَتَحْنَآ اَبْوَابَ السَّمَاۤءِ بِمَاۤءٍ مُّنْهَمِرٍۖ  ',
		ayahNumber: 11,
		translationId: 'Lalu Kami bukakan pintu-pintu langit dengan (menurunkan) air yang tercurah,',
	),
	Ayah(
		ayahId: 4858,
		ayahText: 'وَّفَجَّرْنَا الْاَرْضَ عُيُوْنًا فَالْتَقَى الْمَاۤءُ عَلٰٓى اَمْرٍ قَدْ قُدِرَ ۚ',
		ayahNumber: 12,
		translationId: 'dan Kami jadikan bumi menyemburkan mata-mata air maka bertemulah (air-air) itu sehingga (meluap menimbulkan) keadaan (bencana) yang telah ditetapkan. ',
	),
	Ayah(
		ayahId: 4859,
		ayahText: 'وَحَمَلْنٰهُ عَلٰى ذَاتِ اَلْوَاحٍ وَّدُسُرٍۙ  ',
		ayahNumber: 13,
		translationId: 'Dan Kami angkut dia (Nuh) ke atas (kapal) yang terbuat dari papan dan pasak, ',
	),
	Ayah(
		ayahId: 4860,
		ayahText: 'تَجْرِيْ بِاَعْيُنِنَاۚ جَزَاۤءً لِّمَنْ كَانَ كُفِرَ ',
		ayahNumber: 14,
		translationId: 'yang berlayar dengan pemeliharaan (pengawasan) Kami sebagai balasan bagi orang yang telah diingkari (kaumnya).',
	),
	Ayah(
		ayahId: 4861,
		ayahText: 'وَلَقَدْ تَّرَكْنٰهَآ اٰيَةً فَهَلْ مِنْ مُّدَّكِرٍ',
		ayahNumber: 15,
		translationId: 'Dan sungguh, kapal itu telah Kami jadikan sebagai tanda (pelajaran). Maka adakah orang yang mau mengambil pelajaran?',
	),
	Ayah(
		ayahId: 4862,
		ayahText: 'فَكَيْفَ كَانَ عَذَابِيْ وَنُذُرِ ',
		ayahNumber: 16,
		translationId: 'Maka betapa dahsyatnya azab-Ku dan peringatan-Ku! ',
	),
	Ayah(
		ayahId: 4863,
		ayahText: 'وَلَقَدْ يَسَّرْنَا الْقُرْاٰنَ لِلذِّكْرِ فَهَلْ مِنْ مُّدَّكِرٍ ',
		ayahNumber: 17,
		translationId: "Dan sungguh, telah Kami mudahkan Al-Qur'an untuk peringatan, maka adakah orang yang mau mengambil pelajaran?",
	),
	Ayah(
		ayahId: 4864,
		ayahText: 'كَذَّبَتْ عَادٌ فَكَيْفَ كَانَ عَذَابِيْ وَنُذُرِ ',
		ayahNumber: 18,
		translationId: 'Kaum ‘Ad pun telah mendustakan. Maka betapa dahsyatnya azab-Ku dan peringatan-Ku! ',
	),
	Ayah(
		ayahId: 4865,
		ayahText: 'اِنَّآ اَرْسَلْنَا عَلَيْهِمْ رِيْحًا صَرْصَرًا فِيْ يَوْمِ نَحْسٍ مُّسْتَمِرٍّۙ  ',
		ayahNumber: 19,
		translationId: 'Sesungguhnya Kami telah menghembuskan angin yang sangat kencang kepada mereka pada hari nahas yang terus menerus, ',
	),
	Ayah(
		ayahId: 4866,
		ayahText: 'تَنْزِعُ النَّاسَۙ كَاَنَّهُمْ اَعْجَازُ نَخْلٍ مُّنْقَعِرٍ ',
		ayahNumber: 20,
		translationId: 'yang membuat manusia bergelimpangan, mereka bagaikan pohon-pohon kurma yang tumbang dengan akar-akarnya. ',
	),
	Ayah(
		ayahId: 4867,
		ayahText: 'فَكَيْفَ كَانَ عَذَابِيْ وَنُذُرِ',
		ayahNumber: 21,
		translationId: 'Maka betapa dahsyatnya azab-Ku dan peringatan-Ku! ',
	),
	Ayah(
		ayahId: 4868,
		ayahText: 'وَلَقَدْ يَسَّرْنَا الْقُرْاٰنَ لِلذِّكْرِ فَهَلْ مِنْ مُّدَّكِرٍ ࣖ ',
		ayahNumber: 22,
		translationId: "Dan sungguh, telah Kami mudahkan Al-Qur'an untuk peringatan, maka adakah orang yang mau mengambil pelajaran?",
	),
	Ayah(
		ayahId: 4869,
		ayahText: 'كَذَّبَتْ ثَمُوْدُ بِالنُّذُرِ',
		ayahNumber: 23,
		translationId: 'Kaum Samud pun telah mendustakan peringatan itu.',
	),
	Ayah(
		ayahId: 4870,
		ayahText: 'فَقَالُوْٓا اَبَشَرًا مِّنَّا وَاحِدًا نَّتَّبِعُهٗٓ  ۙاِنَّآ اِذًا لَّفِيْ ضَلٰلٍ وَّسُعُرٍ',
		ayahNumber: 24,
		translationId: 'Maka mereka berkata, “Bagaimana kita akan mengikuti seorang manusia (biasa) di antara kita? Sungguh, kalau begitu kita benar-benar telah sesat dan gila. ',
	),
	Ayah(
		ayahId: 4871,
		ayahText: 'ءَاُلْقِيَ الذِّكْرُ عَلَيْهِ مِنْۢ بَيْنِنَا بَلْ هُوَ كَذَّابٌ اَشِرٌ ',
		ayahNumber: 25,
		translationId: 'Apakah wahyu itu diturunkan kepadanya di antara kita? Pastilah dia (Saleh) seorang yang sangat pendusta (dan) sombong.” ',
	),
	Ayah(
		ayahId: 4872,
		ayahText: 'سَيَعْلَمُوْنَ غَدًا مَّنِ الْكَذَّابُ الْاَشِرُ ',
		ayahNumber: 26,
		translationId: 'Kelak mereka akan mengetahui siapa yang sebenarnya sangat pendusta (dan) sombong itu.',
	),
	Ayah(
		ayahId: 4873,
		ayahText: 'اِنَّا مُرْسِلُوا النَّاقَةِ فِتْنَةً لَّهُمْ فَارْتَقِبْهُمْ وَاصْطَبِرْۖ  ',
		ayahNumber: 27,
		translationId: 'Sesungguhnya Kami akan mengirimkan unta betina sebagai cobaan bagi mereka, maka tunggulah mereka dan bersabarlah (Saleh).',
	),
	Ayah(
		ayahId: 4874,
		ayahText: 'وَنَبِّئْهُمْ اَنَّ الْمَاۤءَ قِسْمَةٌ ۢ بَيْنَهُمْۚ  كُلُّ شِرْبٍ مُّحْتَضَرٌ ',
		ayahNumber: 28,
		translationId: 'Dan beritahukanlah kepada mereka bahwa air itu dibagi di antara mereka (dengan unta betina itu); setiap orang berhak mendapat giliran minum.',
	),
	Ayah(
		ayahId: 4875,
		ayahText: 'فَنَادَوْا صَاحِبَهُمْ فَتَعَاطٰى فَعَقَرَ ',
		ayahNumber: 29,
		translationId: 'Maka mereka memanggil kawannya, lalu dia menangkap (unta itu) dan memotongnya. ',
	),
	Ayah(
		ayahId: 4876,
		ayahText: 'فَكَيْفَ كَانَ عَذَابِيْ وَنُذُرِ ',
		ayahNumber: 30,
		translationId: 'Maka betapa dahsyatnya azab-Ku dan peringatan-Ku!',
	),
	Ayah(
		ayahId: 4877,
		ayahText: 'اِنَّآ اَرْسَلْنَا عَلَيْهِمْ صَيْحَةً وَّاحِدَةً فَكَانُوْا كَهَشِيْمِ الْمُحْتَظِرِ',
		ayahNumber: 31,
		translationId: 'Kami kirimkan atas mereka satu suara yang keras mengguntur, maka jadilah mereka seperti batang-batang kering yang lapuk. ',
	),
	Ayah(
		ayahId: 4878,
		ayahText: 'وَلَقَدْ يَسَّرْنَا الْقُرْاٰنَ لِلذِّكْرِ فَهَلْ مِنْ مُّدَّكِرٍ ',
		ayahNumber: 32,
		translationId: "Dan sungguh, telah Kami mudahkan Al-Qur'an untuk peringatan, maka adakah orang yang mau mengambil pelajaran?",
	),
	Ayah(
		ayahId: 4879,
		ayahText: 'كَذَّبَتْ قَوْمُ لُوْطٍ ۢبِالنُّذُرِ ',
		ayahNumber: 33,
		translationId: 'Kaum Lut pun telah mendustakan peringatan itu. ',
	),
	Ayah(
		ayahId: 4880,
		ayahText: 'اِنَّآ اَرْسَلْنَا عَلَيْهِمْ حَاصِبًا اِلَّآ اٰلَ لُوْطٍ ۗنَجَّيْنٰهُمْ بِسَحَرٍۙ',
		ayahNumber: 34,
		translationId: 'Sesungguhnya Kami kirimkan kepada mereka badai yang membawa batu-batu (yang menimpa mereka), kecuali keluarga Lut. Kami selamatkan mereka sebelum fajar menyingsing,',
	),
	Ayah(
		ayahId: 4881,
		ayahText: 'نِّعْمَةً مِّنْ عِنْدِنَاۗ  كَذٰلِكَ نَجْزِيْ مَنْ شَكَرَ ',
		ayahNumber: 35,
		translationId: 'sebagai nikmat dari Kami. Demikianlah Kami memberi balasan kepada orang-orang yang bersyukur. ',
	),
	Ayah(
		ayahId: 4882,
		ayahText: 'وَلَقَدْ اَنْذَرَهُمْ بَطْشَتَنَا فَتَمَارَوْا بِالنُّذُرِ ',
		ayahNumber: 36,
		translationId: 'Dan sungguh, dia (Lut) telah memperingatkan mereka akan hukuman Kami, tetapi mereka mendustakan peringatan-Ku. ',
	),
	Ayah(
		ayahId: 4883,
		ayahText: 'وَلَقَدْ رَاوَدُوْهُ عَنْ ضَيْفِهٖ فَطَمَسْنَآ اَعْيُنَهُمْ فَذُوْقُوْا عَذَابِيْ وَنُذُرِ ',
		ayahNumber: 37,
		translationId: 'Dan sungguh, mereka telah membujuknya (agar menyerahkan) tamunya (kepada mereka), lalu Kami butakan mata mereka, maka rasakanlah azab-Ku dan peringatan-Ku!',
	),
	Ayah(
		ayahId: 4884,
		ayahText: 'وَلَقَدْ صَبَّحَهُمْ بُكْرَةً عَذَابٌ مُّسْتَقِرٌّۚ  ',
		ayahNumber: 38,
		translationId: 'Dan sungguh, pada esok harinya mereka benar-benar ditimpa azab yang tetap.',
	),
	Ayah(
		ayahId: 4885,
		ayahText: 'فَذُوْقُوْا عَذَابِيْ وَنُذُرِ ',
		ayahNumber: 39,
		translationId: 'Maka rasakanlah azab-Ku dan peringatan-Ku!',
	),
	Ayah(
		ayahId: 4886,
		ayahText: 'وَلَقَدْ يَسَّرْنَا الْقُرْاٰنَ لِلذِّكْرِ فَهَلْ مِنْ مُّدَّكِرٍ ࣖ',
		ayahNumber: 40,
		translationId: "Dan sungguh, telah Kami mudahkan Al-Qur'an untuk peringatan, maka adakah orang yang mau mengambil pelajaran? ",
	),
	Ayah(
		ayahId: 4887,
		ayahText: 'وَلَقَدْ جَاۤءَ اٰلَ فِرْعَوْنَ النُّذُرُۚ  ',
		ayahNumber: 41,
		translationId: 'Dan sungguh, peringatan telah datang kepada keluarga Fir‘aun. ',
	),
	Ayah(
		ayahId: 4888,
		ayahText: 'كَذَّبُوْا بِاٰيٰتِنَا كُلِّهَا فَاَخَذْنٰهُمْ اَخْذَ عَزِيْزٍ مُّقْتَدِرٍ ',
		ayahNumber: 42,
		translationId: 'Mereka mendustakan mukjizat-mukjizat Kami semuanya, maka Kami azab mereka dengan azab dari Yang Mahaperkasa, Mahakuasa.',
	),
	Ayah(
		ayahId: 4889,
		ayahText: 'اَكُفَّارُكُمْ خَيْرٌ مِّنْ اُولٰۤىِٕكُمْ اَمْ لَكُمْ بَرَاۤءَةٌ فِى الزُّبُرِۚ',
		ayahNumber: 43,
		translationId: 'Apakah orang-orang kafir di lingkunganmu (kaum musyrikin) lebih baik dari mereka, ataukah kamu telah mempunyai jaminan kebebasan (dari azab) dalam kitab-kitab terdahulu? ',
	),
	Ayah(
		ayahId: 4890,
		ayahText: 'اَمْ يَقُوْلُوْنَ نَحْنُ جَمِيْعٌ مُّنْتَصِرٌ ',
		ayahNumber: 44,
		translationId: 'Atau mereka mengatakan, “Kami ini golongan yang bersatu yang pasti menang.” ',
	),
	Ayah(
		ayahId: 4891,
		ayahText: 'سَيُهْزَمُ الْجَمْعُ وَيُوَلُّوْنَ الدُّبُرَ',
		ayahNumber: 45,
		translationId: 'Golongan itu pasti akan dikalahkan dan mereka akan mundur ke belakang. ',
	),
	Ayah(
		ayahId: 4892,
		ayahText: 'بَلِ السَّاعَةُ مَوْعِدُهُمْ وَالسَّاعَةُ اَدْهٰى وَاَمَرُّ ',
		ayahNumber: 46,
		translationId: 'Bahkan hari Kiamat itulah hari yang dijanjikan kepada mereka dan hari Kiamat itu lebih dahsyat dan lebih pahit. ',
	),
	Ayah(
		ayahId: 4893,
		ayahText: 'اِنَّ الْمُجْرِمِيْنَ فِيْ ضَلٰلٍ وَّسُعُرٍۘ ',
		ayahNumber: 47,
		translationId: 'Sungguh, orang-orang yang berdosa berada dalam kesesatan (di dunia) dan akan berada dalam neraka (di akhirat). ',
	),
	Ayah(
		ayahId: 4894,
		ayahText: 'يَوْمَ يُسْحَبُوْنَ فِى النَّارِ عَلٰى وُجُوْهِهِمْۗ ذُوْقُوْا مَسَّ سَقَرَ',
		ayahNumber: 48,
		translationId: 'Pada hari mereka diseret ke neraka pada wajahnya. (Dikatakan kepada mereka), “Rasakanlah sentuhan api neraka.”',
	),
	Ayah(
		ayahId: 4895,
		ayahText: 'اِنَّا كُلَّ شَيْءٍ خَلَقْنٰهُ بِقَدَرٍ ',
		ayahNumber: 49,
		translationId: 'Sungguh, Kami menciptakan segala sesuatu menurut ukuran. ',
	),
	Ayah(
		ayahId: 4896,
		ayahText: 'وَمَآ اَمْرُنَآ اِلَّا وَاحِدَةٌ كَلَمْحٍ ۢبِالْبَصَرِ ',
		ayahNumber: 50,
		translationId: 'Dan perintah Kami hanyalah (dengan) satu perkataan seperti kejapan mata. ',
	),
	Ayah(
		ayahId: 4897,
		ayahText: 'وَلَقَدْ اَهْلَكْنَآ اَشْيَاعَكُمْ فَهَلْ مِنْ مُّدَّكِرٍ ',
		ayahNumber: 51,
		translationId: 'Dan sungguh, telah Kami binasakan orang yang serupa dengan kamu (kekafirannya). Maka adakah orang yang mau mengambil pelajaran?',
	),
	Ayah(
		ayahId: 4898,
		ayahText: 'وَكُلُّ شَيْءٍ فَعَلُوْهُ فِى الزُّبُرِ ',
		ayahNumber: 52,
		translationId: 'Dan segala sesuatu yang telah mereka perbuat tercatat dalam buku-buku catatan.',
	),
	Ayah(
		ayahId: 4899,
		ayahText: 'وَكُلُّ صَغِيْرٍ وَّكَبِيْرٍ مُّسْتَطَرٌ ',
		ayahNumber: 53,
		translationId: 'Dan segala (sesuatu) yang kecil maupun yang besar (semuanya) tertulis. ',
	),
	Ayah(
		ayahId: 4900,
		ayahText: 'اِنَّ الْمُتَّقِيْنَ فِيْ جَنّٰتٍ وَّنَهَرٍۙ  ',
		ayahNumber: 54,
		translationId: 'Sungguh, orang-orang yang bertakwa berada di taman-taman dan sungai-sungai,',
	),
	Ayah(
		ayahId: 4901,
		ayahText: 'فِيْ مَقْعَدِ صِدْقٍ عِنْدَ مَلِيْكٍ مُّقْتَدِرٍ ࣖ ',
		ayahNumber: 55,
		translationId: 'di tempat yang disenangi di sisi Tuhan Yang Mahakuasa.',
	),
];
