// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah26 = [
	Ayah(
		ayahId: 2933,
		ayahText: 'طٰسۤمّۤ ',
		ayahNumber: 1,
		translationId: 'Tha Sin Mim',
	),
	Ayah(
		ayahId: 2934,
		ayahText: 'تِلْكَ اٰيٰتُ الْكِتٰبِ الْمُبِيْنِ',
		ayahNumber: 2,
		translationId: "Inilah ayat-ayat Kitab (Al-Qur'an) yang jelas.",
	),
	Ayah(
		ayahId: 2935,
		ayahText: 'لَعَلَّكَ بَاخِعٌ نَّفْسَكَ اَلَّا يَكُوْنُوْا مُؤْمِنِيْنَ ',
		ayahNumber: 3,
		translationId: 'Boleh jadi engkau (Muhammad) akan membinasakan dirimu (dengan kesedihan), karena mereka (penduduk Mekah) tidak beriman.',
	),
	Ayah(
		ayahId: 2936,
		ayahText: 'اِنْ نَّشَأْ نُنَزِّلْ عَلَيْهِمْ مِّنَ السَّمَاۤءِ اٰيَةً فَظَلَّتْ اَعْنَاقُهُمْ لَهَا خَاضِعِيْنَ ',
		ayahNumber: 4,
		translationId: 'Jika Kami menghendaki, niscaya Kami turunkan kepada mereka mukjizat dari langit, yang akan membuat tengkuk mereka tunduk dengan rendah hati kepadanya.',
	),
	Ayah(
		ayahId: 2937,
		ayahText: 'وَمَا يَأْتِيْهِمْ مِّنْ ذِكْرٍ مِّنَ الرَّحْمٰنِ مُحْدَثٍ اِلَّا كَانُوْا عَنْهُ مُعْرِضِيْنَ ',
		ayahNumber: 5,
		translationId: "Dan setiap kali disampaikan kepada mereka suatu peringatan baru (ayat Al-Qur'an yang diturunkan) dari Tuhan Yang Maha Pengasih, mereka selalu berpaling darinya.",
	),
	Ayah(
		ayahId: 2938,
		ayahText: 'فَقَدْ كَذَّبُوْا فَسَيَأْتِيْهِمْ اَنْۢبـٰۤؤُا مَا كَانُوْا بِهٖ يَسْتَهْزِءُوْنَ ',
		ayahNumber: 6,
		translationId: "Sungguh, mereka telah mendustakan (Al-Qur'an), maka kelak akan datang kepada mereka (kebenaran) berita-berita mengenai apa (azab) yang dulu mereka perolok-olokkan.",
	),
	Ayah(
		ayahId: 2939,
		ayahText: 'اَوَلَمْ يَرَوْا اِلَى الْاَرْضِ كَمْ اَنْۢبَتْنَا فِيْهَا مِنْ كُلِّ زَوْجٍ كَرِيْمٍ ',
		ayahNumber: 7,
		translationId: 'Dan apakah mereka tidak memperhatikan bumi, betapa banyak Kami tumbuhkan di bumi itu berbagai macam pasangan (tumbuh-tumbuhan) yang baik?',
	),
	Ayah(
		ayahId: 2940,
		ayahText: 'اِنَّ فِيْ ذٰلِكَ لَاٰيَةًۗ وَمَا كَانَ اَكْثَرُهُمْ مُّؤْمِنِيْنَ ',
		ayahNumber: 8,
		translationId: 'Sungguh, pada yang demikian itu terdapat tanda (kebesaran Allah), tetapi kebanyakan mereka tidak beriman.',
	),
	Ayah(
		ayahId: 2941,
		ayahText: 'وَاِنَّ رَبَّكَ لَهُوَ الْعَزِيْزُ الرَّحِيْمُ ࣖ ',
		ayahNumber: 9,
		translationId: 'Dan sungguh, Tuhanmu Dialah Yang Mahaperkasa, Maha Penyayang.',
	),
	Ayah(
		ayahId: 2942,
		ayahText: 'وَاِذْ نَادٰى رَبُّكَ مُوْسٰٓى اَنِ ائْتِ الْقَوْمَ الظّٰلِمِيْنَ ۙ',
		ayahNumber: 10,
		translationId: 'Dan (ingatlah) ketika Tuhanmu menyeru Musa (dengan firman-Nya), “Datangilah kaum yang zalim itu,',
	),
	Ayah(
		ayahId: 2943,
		ayahText: 'قَوْمَ فِرْعَوْنَ ۗ اَلَا يَتَّقُوْنَ  ',
		ayahNumber: 11,
		translationId: '(yaitu) kaum Fir‘aun. Mengapa mereka tidak bertakwa?”',
	),
	Ayah(
		ayahId: 2944,
		ayahText: 'قَالَ رَبِّ اِنِّيْٓ اَخَافُ اَنْ يُّكَذِّبُوْنِ ۗ',
		ayahNumber: 12,
		translationId: 'Dia (Musa) berkata, “Ya Tuhanku, sungguh, aku takut mereka akan mendustakan aku,',
	),
	Ayah(
		ayahId: 2945,
		ayahText: 'وَيَضِيْقُ صَدْرِيْ وَلَا يَنْطَلِقُ لِسَانِيْ فَاَرْسِلْ اِلٰى هٰرُوْنَ ',
		ayahNumber: 13,
		translationId: 'sehingga dadaku terasa sempit dan lidahku tidak lancar, maka utuslah Harun (bersamaku).',
	),
	Ayah(
		ayahId: 2946,
		ayahText: 'وَلَهُمْ عَلَيَّ ذَنْۢبٌ فَاَخَافُ اَنْ يَّقْتُلُوْنِ  ۚ',
		ayahNumber: 14,
		translationId: 'Sebab aku berdosa terhadap mereka, maka aku takut mereka akan membunuhku.”',
	),
	Ayah(
		ayahId: 2947,
		ayahText: 'قَالَ كَلَّاۚ فَاذْهَبَا بِاٰيٰتِنَآ اِنَّا مَعَكُمْ مُّسْتَمِعُوْنَ ۙ ',
		ayahNumber: 15,
		translationId: '(Allah) berfirman, “Jangan takut (mereka tidak akan dapat membunuhmu)! Maka pergilah kamu berdua dengan membawa ayat-ayat Kami (mukjizat-mukjizat); sungguh, Kami bersamamu mendengarkan (apa yang mereka katakan),',
	),
	Ayah(
		ayahId: 2948,
		ayahText: 'فَأْتِيَا فِرْعَوْنَ فَقُوْلَآ اِنَّا رَسُوْلُ رَبِّ الْعٰلَمِيْنَ ۙ',
		ayahNumber: 16,
		translationId: 'maka datanglah kamu berdua kepada Fir‘aun dan katakan, “Sesungguhnya kami adalah rasul-rasul Tuhan seluruh alam,',
	),
	Ayah(
		ayahId: 2949,
		ayahText: 'اَنْ اَرْسِلْ مَعَنَا بَنِيْٓ اِسْرَاۤءِيْلَ ۗ ',
		ayahNumber: 17,
		translationId: 'lepaskanlah Bani Israil (pergi) bersama kami.”',
	),
	Ayah(
		ayahId: 2950,
		ayahText: 'قَالَ اَلَمْ نُرَبِّكَ فِيْنَا وَلِيْدًا وَّلَبِثْتَ فِيْنَا مِنْ عُمُرِكَ سِنِيْنَ ۗ ',
		ayahNumber: 18,
		translationId: 'Dia (Fir‘aun) menjawab, “Bukankah kami telah mengasuhmu dalam lingkungan (keluarga) kami, waktu engkau masih kanak-kanak dan engkau tinggal bersama kami beberapa tahun dari umurmu.',
	),
	Ayah(
		ayahId: 2951,
		ayahText: 'وَفَعَلْتَ فَعْلَتَكَ الَّتِيْ فَعَلْتَ وَاَنْتَ مِنَ الْكٰفِرِيْنَ  ',
		ayahNumber: 19,
		translationId: 'Dan engkau (Musa) telah melakukan (kesalahan dari) perbuatan yang telah engkau lakukan dan engkau termasuk orang yang tidak tahu berterima kasih.”',
	),
	Ayah(
		ayahId: 2952,
		ayahText: 'قَالَ فَعَلْتُهَآ اِذًا وَّاَنَا۠ مِنَ الضَّاۤلِّيْنَ  ',
		ayahNumber: 20,
		translationId: 'Dia (Musa) berkata, “Aku telah melakukannya, dan ketika itu aku termasuk orang yang khilaf.',
	),
	Ayah(
		ayahId: 2953,
		ayahText: 'فَفَرَرْتُ مِنْكُمْ لَمَّا خِفْتُكُمْ فَوَهَبَ لِيْ رَبِّيْ حُكْمًا وَّجَعَلَنِيْ مِنَ الْمُرْسَلِيْنَ  ',
		ayahNumber: 21,
		translationId: 'Lalu aku lari darimu karena aku takut kepadamu, kemudian Tuhanku menganugerahkan ilmu kepadaku serta Dia menjadikan aku salah seorang di antara rasul-rasul.',
	),
	Ayah(
		ayahId: 2954,
		ayahText: 'وَتِلْكَ نِعْمَةٌ تَمُنُّهَا عَلَيَّ اَنْ عَبَّدْتَّ بَنِيْٓ اِسْرَاۤءِيْلَ ۗ',
		ayahNumber: 22,
		translationId: 'Dan itulah kebaikan yang telah engkau berikan kepadaku, (sementara) itu engkau telah memperbudak Bani Israil.”',
	),
	Ayah(
		ayahId: 2955,
		ayahText: 'قَالَ فِرْعَوْنُ وَمَا رَبُّ الْعٰلَمِيْنَ ۗ ',
		ayahNumber: 23,
		translationId: 'Fir‘aun bertanya, “Siapa Tuhan seluruh alam itu?”',
	),
	Ayah(
		ayahId: 2956,
		ayahText: 'قَالَ رَبُّ السَّمٰوٰتِ وَالْاَرْضِ وَمَا بَيْنَهُمَاۗ اِنْ كُنْتُمْ مُّوْقِنِيْنَ ',
		ayahNumber: 24,
		translationId: 'Dia (Musa) menjawab, “Tuhan pencipta langit dan bumi dan apa yang ada di antara keduanya (itulah Tuhanmu), jika kamu mempercayai-Nya.”',
	),
	Ayah(
		ayahId: 2957,
		ayahText: 'قَالَ لِمَنْ حَوْلَهٗٓ اَلَا تَسْتَمِعُوْنَ ',
		ayahNumber: 25,
		translationId: 'Dia (Fir‘aun) berkata kepada orang-orang di sekelilingnya, “Apakah kamu tidak mendengar (apa yang dikatakannya)?”',
	),
	Ayah(
		ayahId: 2958,
		ayahText: 'قَالَ رَبُّكُمْ وَرَبُّ اٰبَاۤىِٕكُمُ الْاَوَّلِيْنَ ',
		ayahNumber: 26,
		translationId: 'Dia (Musa) berkata, “(Dia) Tuhanmu dan juga Tuhan nenek moyangmu terdahulu.”',
	),
	Ayah(
		ayahId: 2959,
		ayahText: 'قَالَ اِنَّ رَسُوْلَكُمُ الَّذِيْٓ اُرْسِلَ اِلَيْكُمْ لَمَجْنُوْنٌ ',
		ayahNumber: 27,
		translationId: 'Dia (Fir‘aun) berkata, “Sungguh, Rasulmu yang diutus kepada kamu benar-benar orang gila.” ',
	),
	Ayah(
		ayahId: 2960,
		ayahText: 'قَالَ رَبُّ الْمَشْرِقِ وَالْمَغْرِبِ وَمَا بَيْنَهُمَاۗ اِنْ كُنْتُمْ تَعْقِلُوْنَ  ',
		ayahNumber: 28,
		translationId: 'Dia (Musa) berkata, “(Dialah) Tuhan (yang menguasai) timur dan barat dan apa yang ada di antara keduanya; jika kamu mengerti.”',
	),
	Ayah(
		ayahId: 2961,
		ayahText: 'قَالَ لَىِٕنِ اتَّخَذْتَ اِلٰهًا غَيْرِيْ لَاَجْعَلَنَّكَ مِنَ الْمَسْجُوْنِيْنَ ',
		ayahNumber: 29,
		translationId: 'Dia (Fir‘aun) berkata, “Sungguh, jika engkau menyembah Tuhan selain aku, pasti aku masukkan engkau ke dalam penjara.”',
	),
	Ayah(
		ayahId: 2962,
		ayahText: 'قَالَ اَوَلَوْ جِئْتُكَ بِشَيْءٍ مُّبِيْنٍ ',
		ayahNumber: 30,
		translationId: 'Dia (Musa) berkata, “Apakah (engkau akan melakukan itu) sekalipun aku tunjukkan kepadamu sesuatu (bukti) yang nyata?”',
	),
	Ayah(
		ayahId: 2963,
		ayahText: 'قَالَ فَأْتِ بِهٖٓ اِنْ كُنْتَ مِنَ الصّٰدِقِيْنَ',
		ayahNumber: 31,
		translationId: 'Dia (Fir‘aun) berkata, “Tunjukkan sesuatu (bukti yang nyata) itu, jika engkau termasuk orang yang benar!”',
	),
	Ayah(
		ayahId: 2964,
		ayahText: 'فَاَلْقٰى عَصَاهُ فَاِذَا هِيَ ثُعْبَانٌ مُّبِيْنٌ ۚ ',
		ayahNumber: 32,
		translationId: 'Maka dia (Musa) melemparkan tongkatnya, tiba-tiba tongkat itu menjadi ular besar yang sebenarnya.',
	),
	Ayah(
		ayahId: 2965,
		ayahText: 'وَنَزَعَ يَدَهٗ فَاِذَا هِيَ بَيْضَاۤءُ لِلنّٰظِرِيْنَ ࣖ ',
		ayahNumber: 33,
		translationId: 'Dan dia mengeluarkan tangannya (dari dalam bajunya), tiba-tiba tangan itu menjadi putih (bercahaya) bagi orang-orang yang melihatnya.',
	),
	Ayah(
		ayahId: 2966,
		ayahText: 'قَالَ لِلْمَلَاِ حَوْلَهٗٓ اِنَّ هٰذَا لَسٰحِرٌ عَلِيْمٌ ۙ ',
		ayahNumber: 34,
		translationId: 'Dia (Fir‘aun) berkata kepada para pemuka di sekelilingnya, “Sesungguhnya dia (Musa) ini pasti seorang pesihir yang pandai,',
	),
	Ayah(
		ayahId: 2967,
		ayahText: 'يُّرِيْدُ اَنْ يُّخْرِجَكُمْ مِّنْ اَرْضِكُمْ بِسِحْرِهٖۖ فَمَاذَا تَأْمُرُوْنَ ',
		ayahNumber: 35,
		translationId: 'dia hendak mengusir kamu dari negerimu dengan sihirnya; karena itu apakah yang kamu sarankan?”',
	),
	Ayah(
		ayahId: 2968,
		ayahText: 'قَالُوْٓا اَرْجِهْ وَاَخَاهُ وَابْعَثْ فِى الْمَدَاۤىِٕنِ حٰشِرِيْنَ ۙ ',
		ayahNumber: 36,
		translationId: 'Mereka menjawab, “Tahanlah (untuk sementara) dia dan saudaranya, dan utuslah ke seluruh negeri orang-orang yang akan mengumpulkan (pesihir),',
	),
	Ayah(
		ayahId: 2969,
		ayahText: 'يَأْتُوْكَ بِكُلِّ سَحَّارٍ عَلِيْمٍ ',
		ayahNumber: 37,
		translationId: 'niscaya mereka akan mendatangkan semua pesihir yang pandai kepadamu.” ',
	),
	Ayah(
		ayahId: 2970,
		ayahText: 'فَجُمِعَ السَّحَرَةُ لِمِيْقَاتِ يَوْمٍ مَّعْلُوْمٍ ۙ ',
		ayahNumber: 38,
		translationId: 'Lalu dikumpulkanlah para pesihir pada waktu (yang ditetapkan) pada hari yang telah ditentukan, ',
	),
	Ayah(
		ayahId: 2971,
		ayahText: 'وَّقِيْلَ لِلنَّاسِ هَلْ اَنْتُمْ مُّجْتَمِعُوْنَ ۙ ',
		ayahNumber: 39,
		translationId: 'dan diumumkan kepada orang banyak, “Berkumpullah kamu semua,',
	),
	Ayah(
		ayahId: 2972,
		ayahText: 'لَعَلَّنَا نَتَّبِعُ السَّحَرَةَ اِنْ كَانُوْا هُمُ الْغٰلِبِيْنَ  ',
		ayahNumber: 40,
		translationId: 'agar kita mengikuti para pesihir itu, jika mereka yang menang.”',
	),
	Ayah(
		ayahId: 2973,
		ayahText: 'فَلَمَّا جَاۤءَ السَّحَرَةُ قَالُوْا لِفِرْعَوْنَ اَىِٕنَّ لَنَا لَاَجْرًا اِنْ كُنَّا نَحْنُ الْغٰلِبِيْنَ  ',
		ayahNumber: 41,
		translationId: 'Maka ketika para pesihir datang, mereka berkata kepada Fir‘aun, “Apakah kami benar-benar akan mendapat imbalan yang besar jika kami yang menang?”',
	),
	Ayah(
		ayahId: 2974,
		ayahText: 'قَالَ نَعَمْ وَاِنَّكُمْ اِذًا لَّمِنَ الْمُقَرَّبِيْنَ ',
		ayahNumber: 42,
		translationId: 'Dia (Fir‘aun) menjawab, “Ya, dan bahkan kamu pasti akan mendapat kedudukan yang dekat (kepadaku).”',
	),
	Ayah(
		ayahId: 2975,
		ayahText: 'قَالَ لَهُمْ مُّوْسٰٓى اَلْقُوْا مَآ اَنْتُمْ مُّلْقُوْنَ  ',
		ayahNumber: 43,
		translationId: 'Dia (Musa) berkata kepada mereka, “Lemparkanlah apa yang hendak kamu lemparkan.”',
	),
	Ayah(
		ayahId: 2976,
		ayahText: 'فَاَلْقَوْا حِبَالَهُمْ وَعِصِيَّهُمْ وَقَالُوْا بِعِزَّةِ فِرْعَوْنَ اِنَّا لَنَحْنُ الْغٰلِبُوْنَ  ',
		ayahNumber: 44,
		translationId: 'Lalu mereka melemparkan tali temali dan tongkat-tongkat mereka seraya berkata, “Demi kekuasaan Fir‘aun, pasti kamilah yang akan menang.”',
	),
	Ayah(
		ayahId: 2977,
		ayahText: 'فَاَلْقٰى مُوْسٰى عَصَاهُ فَاِذَا هِيَ تَلْقَفُ مَا يَأْفِكُوْنَ ۚ ',
		ayahNumber: 45,
		translationId: 'Kemudian Musa melemparkan tongkatnya, maka tiba-tiba ia menelan benda-benda palsu yang mereka ada-adakan itu.',
	),
	Ayah(
		ayahId: 2978,
		ayahText: 'فَاُلْقِيَ السَّحَرَةُ سٰجِدِيْنَ ۙ ',
		ayahNumber: 46,
		translationId: 'Maka menyungkurlah para pesihir itu, bersujud.',
	),
	Ayah(
		ayahId: 2979,
		ayahText: 'قَالُوْٓا اٰمَنَّا بِرَبِّ الْعٰلَمِيْنَ ۙ ',
		ayahNumber: 47,
		translationId: 'Mereka berkata, “Kami beriman kepada Tuhan seluruh alam,',
	),
	Ayah(
		ayahId: 2980,
		ayahText: 'رَبِّ مُوْسٰى وَهٰرُوْنَ  ',
		ayahNumber: 48,
		translationId: '(yaitu) Tuhannya Musa dan Harun.”',
	),
	Ayah(
		ayahId: 2981,
		ayahText: 'قَالَ اٰمَنْتُمْ لَهٗ قَبْلَ اَنْ اٰذَنَ لَكُمْۚ اِنَّهٗ لَكَبِيْرُكُمُ الَّذِيْ عَلَّمَكُمُ السِّحْرَۚ فَلَسَوْفَ تَعْلَمُوْنَ ەۗ لَاُقَطِّعَنَّ اَيْدِيَكُمْ وَاَرْجُلَكُمْ مِّنْ خِلَافٍ وَّلَاُصَلِّبَنَّكُمْ اَجْمَعِيْنَۚ',
		ayahNumber: 49,
		translationId: 'Dia (Fir‘aun) berkata, “Mengapa kamu beriman kepada Musa sebelum aku memberi izin kepadamu? Sesungguhnya dia pemimpinmu yang mengajarkan sihir kepadamu. Nanti kamu pasti akan tahu (akibat perbuatanmu). Pasti akan kupotong tangan dan kakimu bersilang dan sungguh, akan kusalib kamu semuanya.”',
	),
	Ayah(
		ayahId: 2982,
		ayahText: 'قَالُوْا لَا ضَيْرَ ۖاِنَّآ اِلٰى رَبِّنَا مُنْقَلِبُوْنَ ۚ  ',
		ayahNumber: 50,
		translationId: 'Mereka berkata, “Tidak ada yang kami takutkan, karena kami akan kembali kepada Tuhan kami.',
	),
	Ayah(
		ayahId: 2983,
		ayahText: ' اِنَّا نَطْمَعُ اَنْ يَّغْفِرَ لَنَا رَبُّنَا خَطٰيٰنَآ اَنْ كُنَّآ اَوَّلَ الْمُؤْمِنِيْنَ ۗ ࣖ',
		ayahNumber: 51,
		translationId: 'Sesungguhnya kami sangat menginginkan sekiranya Tuhan kami akan mengampuni kesalahan kami, karena kami menjadi orang yang pertama-tama beriman.”',
	),
	Ayah(
		ayahId: 2984,
		ayahText: '۞ وَاَوْحَيْنَآ اِلٰى مُوْسٰٓى اَنْ اَسْرِ بِعِبَادِيْٓ اِنَّكُمْ مُّتَّبَعُوْنَ  ',
		ayahNumber: 52,
		translationId: 'Dan Kami wahyukan (perintahkan) kepada Musa, “Pergilah pada malam hari dengan membawa hamba-hamba-Ku (Bani Israil), sebab pasti kamu akan dikejar.”',
	),
	Ayah(
		ayahId: 2985,
		ayahText: 'فَاَرْسَلَ فِرْعَوْنُ فِى الْمَدَاۤىِٕنِ حٰشِرِيْنَ ۚ ',
		ayahNumber: 53,
		translationId: 'Kemudian Fir‘aun mengirimkan orang ke kota-kota (untuk mengumpulkan bala tentaranya).',
	),
	Ayah(
		ayahId: 2986,
		ayahText: 'اِنَّ هٰٓؤُلَاۤءِ لَشِرْذِمَةٌ قَلِيْلُوْنَۙ ',
		ayahNumber: 54,
		translationId: '(Fir‘aun berkata), “Sesungguhnya mereka (Bani Israil) hanya sekelompok kecil,',
	),
	Ayah(
		ayahId: 2987,
		ayahText: 'وَاِنَّهُمْ لَنَا لَغَاۤىِٕظُوْنَ ۙ  ',
		ayahNumber: 55,
		translationId: 'dan sesungguhnya mereka telah berbuat hal-hal yang menimbulkan amarah kita,',
	),
	Ayah(
		ayahId: 2988,
		ayahText: 'وَاِنَّا لَجَمِيْعٌ حٰذِرُوْنَ ۗ ',
		ayahNumber: 56,
		translationId: 'dan sesungguhnya kita semua tanpa kecuali harus selalu waspada.”',
	),
	Ayah(
		ayahId: 2989,
		ayahText: 'فَاَخْرَجْنٰهُمْ مِّنْ جَنّٰتٍ وَّعُيُوْنٍ ۙ ',
		ayahNumber: 57,
		translationId: 'Kemudian, Kami keluarkan mereka (Fir‘aun dan kaumnya) dari taman-taman dan mata air,',
	),
	Ayah(
		ayahId: 2990,
		ayahText: 'وَّكُنُوْزٍ وَّمَقَامٍ كَرِيْمٍ ۙ ',
		ayahNumber: 58,
		translationId: 'dan (dari) harta kekayaan dan kedudukan yang mulia, ',
	),
	Ayah(
		ayahId: 2991,
		ayahText: 'كَذٰلِكَۚ وَاَوْرَثْنٰهَا بَنِيْٓ اِسْرَاۤءِيْلَ ۗ ',
		ayahNumber: 59,
		translationId: 'demikianlah, dan Kami anugerahkan semuanya (itu) kepada Bani Israil.',
	),
	Ayah(
		ayahId: 2992,
		ayahText: 'فَاَتْبَعُوْهُمْ مُّشْرِقِيْنَ  ',
		ayahNumber: 60,
		translationId: 'Lalu (Fir‘aun dan bala tentaranya) dapat menyusul mereka pada waktu matahari terbit.',
	),
	Ayah(
		ayahId: 2993,
		ayahText: 'فَلَمَّا تَرَاۤءَ الْجَمْعٰنِ قَالَ اَصْحٰبُ مُوْسٰٓى اِنَّا لَمُدْرَكُوْنَ ۚ  ',
		ayahNumber: 61,
		translationId: 'Maka ketika kedua golongan itu saling melihat, berkatalah pengikut-pengikut Musa, “Kita benar-benar akan tersusul.”',
	),
	Ayah(
		ayahId: 2994,
		ayahText: 'قَالَ كَلَّاۗ اِنَّ مَعِيَ رَبِّيْ سَيَهْدِيْنِ  ',
		ayahNumber: 62,
		translationId: 'Dia (Musa) menjawab, “Sekali-kali tidak akan (tersusul); sesungguhnya Tuhanku bersamaku, Dia akan memberi petunjuk kepadaku.”',
	),
	Ayah(
		ayahId: 2995,
		ayahText: 'فَاَوْحَيْنَآ اِلٰى مُوْسٰٓى اَنِ اضْرِبْ بِّعَصَاكَ الْبَحْرَۗ فَانْفَلَقَ فَكَانَ كُلُّ فِرْقٍ كَالطَّوْدِ الْعَظِيْمِ ۚ ',
		ayahNumber: 63,
		translationId: 'Lalu Kami wahyukan kepada Musa, “Pukullah laut itu dengan tongkatmu.” Maka terbelahlah lautan itu, dan setiap belahan seperti gunung yang besar.',
	),
	Ayah(
		ayahId: 2996,
		ayahText: 'وَاَزْلَفْنَا ثَمَّ الْاٰخَرِيْنَ ۚ ',
		ayahNumber: 64,
		translationId: 'Dan di sanalah Kami dekatkan golongan yang lain. ',
	),
	Ayah(
		ayahId: 2997,
		ayahText: 'وَاَنْجَيْنَا مُوْسٰى وَمَنْ مَّعَهٗٓ اَجْمَعِيْنَ ۚ ',
		ayahNumber: 65,
		translationId: 'Dan Kami selamatkan Musa dan orang-orang yang bersamanya.',
	),
	Ayah(
		ayahId: 2998,
		ayahText: 'ثُمَّ اَغْرَقْنَا الْاٰخَرِيْنَ ۗ ',
		ayahNumber: 66,
		translationId: 'Kemudian Kami tenggelamkan golongan yang lain.',
	),
	Ayah(
		ayahId: 2999,
		ayahText: 'اِنَّ فِيْ ذٰلِكَ لَاٰيَةً ۗوَمَا كَانَ اَكْثَرُهُمْ مُّؤْمِنِيْنَ  ',
		ayahNumber: 67,
		translationId: 'Sungguh, pada yang demikian itu terdapat suatu tanda (kekuasaan Allah), tetapi kebanyakan mereka tidak beriman.',
	),
	Ayah(
		ayahId: 3000,
		ayahText: 'وَاِنَّ رَبَّكَ لَهُوَ الْعَزِيْزُ الرَّحِيْمُ ࣖ',
		ayahNumber: 68,
		translationId: 'Dan sesungguhnya Tuhanmu Dialah Yang Mahaperkasa, Maha Penyayang.',
	),
	Ayah(
		ayahId: 3001,
		ayahText: 'وَاتْلُ عَلَيْهِمْ نَبَاَ اِبْرٰهِيْمَ ۘ ',
		ayahNumber: 69,
		translationId: 'Dan bacakanlah kepada mereka kisah Ibrahim.',
	),
	Ayah(
		ayahId: 3002,
		ayahText: 'اِذْ قَالَ لِاَبِيْهِ وَقَوْمِهٖ مَا تَعْبُدُوْنَ ',
		ayahNumber: 70,
		translationId: 'Ketika dia (Ibrahim) berkata kepada ayahnya dan kaumnya, “Apakah yang kamu sembah?”',
	),
	Ayah(
		ayahId: 3003,
		ayahText: 'قَالُوْا نَعْبُدُ اَصْنَامًا فَنَظَلُّ لَهَا عٰكِفِيْنَ  ',
		ayahNumber: 71,
		translationId: 'Mereka menjawab, “Kami menyembah berhala-berhala dan kami senantiasa tekun menyembahnya.”',
	),
	Ayah(
		ayahId: 3004,
		ayahText: 'قَالَ هَلْ يَسْمَعُوْنَكُمْ اِذْ تَدْعُوْنَ ۙ  ',
		ayahNumber: 72,
		translationId: 'Dia (Ibrahim) berkata, “Apakah mereka mendengarmu ketika kamu berdoa (kepadanya)?',
	),
	Ayah(
		ayahId: 3005,
		ayahText: 'اَوْ يَنْفَعُوْنَكُمْ اَوْ يَضُرُّوْنَ  ',
		ayahNumber: 73,
		translationId: 'Atau (dapatkah) mereka memberi manfaat atau mencelakakan kamu?”',
	),
	Ayah(
		ayahId: 3006,
		ayahText: 'قَالُوْا بَلْ وَجَدْنَآ اٰبَاۤءَنَا كَذٰلِكَ يَفْعَلُوْنَ  ',
		ayahNumber: 74,
		translationId: 'Mereka menjawab, “Tidak, tetapi kami dapati nenek moyang kami berbuat begitu.”',
	),
	Ayah(
		ayahId: 3007,
		ayahText: 'قَالَ اَفَرَءَيْتُمْ مَّا كُنْتُمْ تَعْبُدُوْنَ ۙ ',
		ayahNumber: 75,
		translationId: 'Dia (Ibrahim) berkata, “Apakah kamu memperhatikan apa yang kamu sembah,',
	),
	Ayah(
		ayahId: 3008,
		ayahText: 'اَنْتُمْ وَاٰبَاۤؤُكُمُ الْاَقْدَمُوْنَ ۙ  ',
		ayahNumber: 76,
		translationId: 'kamu dan nenek moyang kamu yang terdahulu?',
	),
	Ayah(
		ayahId: 3009,
		ayahText: 'فَاِنَّهُمْ عَدُوٌّ لِّيْٓ اِلَّا رَبَّ الْعٰلَمِيْنَ ۙ ',
		ayahNumber: 77,
		translationId: 'Sesungguhnya mereka (apa yang kamu sembah) itu musuhku, lain halnya Tuhan seluruh alam,',
	),
	Ayah(
		ayahId: 3010,
		ayahText: 'الَّذِيْ خَلَقَنِيْ فَهُوَ يَهْدِيْنِ ۙ ',
		ayahNumber: 78,
		translationId: '(yaitu) Yang telah menciptakan aku, maka Dia yang memberi petunjuk kepadaku,',
	),
	Ayah(
		ayahId: 3011,
		ayahText: 'وَالَّذِيْ هُوَ يُطْعِمُنِيْ وَيَسْقِيْنِ ۙ ',
		ayahNumber: 79,
		translationId: 'dan Yang memberi makan dan minum kepadaku;',
	),
	Ayah(
		ayahId: 3012,
		ayahText: 'وَاِذَا مَرِضْتُ فَهُوَ يَشْفِيْنِ ۙ  ',
		ayahNumber: 80,
		translationId: 'dan apabila aku sakit, Dialah yang menyembuhkan aku, ',
	),
	Ayah(
		ayahId: 3013,
		ayahText: 'وَالَّذِيْ يُمِيْتُنِيْ ثُمَّ يُحْيِيْنِ ۙ ',
		ayahNumber: 81,
		translationId: 'dan Yang akan mematikan aku, kemudian akan menghidupkan aku (kembali),',
	),
	Ayah(
		ayahId: 3014,
		ayahText: 'وَالَّذِيْٓ اَطْمَعُ اَنْ يَّغْفِرَ لِيْ خَطِيْۤـَٔتِيْ يَوْمَ الدِّيْنِ ۗ',
		ayahNumber: 82,
		translationId: 'dan Yang sangat kuinginkan akan mengampuni kesalahanku pada hari Kiamat.”',
	),
	Ayah(
		ayahId: 3015,
		ayahText: 'رَبِّ هَبْ لِيْ حُكْمًا وَّاَلْحِقْنِيْ بِالصّٰلِحِيْنَ ۙ',
		ayahNumber: 83,
		translationId: 'Ibrahim berdoa), “Ya Tuhanku, berikanlah kepadaku ilmu dan masukkanlah aku ke dalam golongan orang-orang yang saleh,',
	),
	Ayah(
		ayahId: 3016,
		ayahText: 'وَاجْعَلْ لِّيْ لِسَانَ صِدْقٍ فِى الْاٰخِرِيْنَ ۙ ',
		ayahNumber: 84,
		translationId: 'dan jadikanlah aku buah tutur yang baik bagi orang-orang (yang datang) kemudian,',
	),
	Ayah(
		ayahId: 3017,
		ayahText: 'وَاجْعَلْنِيْ مِنْ وَّرَثَةِ جَنَّةِ النَّعِيْمِ ۙ',
		ayahNumber: 85,
		translationId: 'dan jadikanlah aku termasuk orang yang mewarisi surga yang penuh kenikmatan,',
	),
	Ayah(
		ayahId: 3018,
		ayahText: 'وَاغْفِرْ لِاَبِيْٓ اِنَّهٗ كَانَ مِنَ الضَّاۤلِّيْنَ ۙ ',
		ayahNumber: 86,
		translationId: 'dan ampunilah ayahku, sesungguhnya dia termasuk orang yang sesat,',
	),
	Ayah(
		ayahId: 3019,
		ayahText: 'وَلَا تُخْزِنِيْ يَوْمَ يُبْعَثُوْنَۙ',
		ayahNumber: 87,
		translationId: 'dan janganlah Engkau hinakan aku pada hari mereka dibangkitkan,',
	),
	Ayah(
		ayahId: 3020,
		ayahText: 'يَوْمَ لَا يَنْفَعُ مَالٌ وَّلَا بَنُوْنَ ۙ  ',
		ayahNumber: 88,
		translationId: '(yaitu) pada hari (ketika) harta dan anak-anak  tidak berguna,',
	),
	Ayah(
		ayahId: 3021,
		ayahText: 'اِلَّا مَنْ اَتَى اللّٰهَ بِقَلْبٍ سَلِيْمٍ ۗ ',
		ayahNumber: 89,
		translationId: 'kecuali orang-orang yang menghadap Allah dengan hati yang bersih,',
	),
	Ayah(
		ayahId: 3022,
		ayahText: 'وَاُزْلِفَتِ الْجَنَّةُ لِلْمُتَّقِيْنَ ۙ ',
		ayahNumber: 90,
		translationId: 'dan surga didekatkan kepada orang-orang yang bertakwa,',
	),
	Ayah(
		ayahId: 3023,
		ayahText: 'وَبُرِّزَتِ الْجَحِيْمُ لِلْغٰوِيْنَ ۙ ',
		ayahNumber: 91,
		translationId: 'dan neraka Jahim diperlihatkan dengan jelas kepada orang-orang yang sesat,”',
	),
	Ayah(
		ayahId: 3024,
		ayahText: 'وَقِيْلَ لَهُمْ اَيْنَ مَا كُنْتُمْ تَعْبُدُوْنَ ۙ ',
		ayahNumber: 92,
		translationId: 'dan dikatakan kepada mereka, “Di mana berhala-berhala yang dahulu kamu sembah,',
	),
	Ayah(
		ayahId: 3025,
		ayahText: 'مِنْ دُوْنِ اللّٰهِ ۗهَلْ يَنْصُرُوْنَكُمْ اَوْ يَنْتَصِرُوْنَ ۗ  ',
		ayahNumber: 93,
		translationId: 'selain Allah? Dapatkah mereka menolong kamu atau menolong diri mereka sendiri?”',
	),
	Ayah(
		ayahId: 3026,
		ayahText: 'فَكُبْكِبُوْا فِيْهَا هُمْ وَالْغَاوٗنَ ۙ ',
		ayahNumber: 94,
		translationId: 'Maka mereka (sesembahan itu) dijungkirkan ke dalam neraka bersama orang-orang yang sesat,',
	),
	Ayah(
		ayahId: 3027,
		ayahText: 'وَجُنُوْدُ اِبْلِيْسَ اَجْمَعُوْنَ ۗ  ',
		ayahNumber: 95,
		translationId: 'dan bala tentara Iblis semuanya.',
	),
	Ayah(
		ayahId: 3028,
		ayahText: 'قَالُوْا وَهُمْ فِيْهَا يَخْتَصِمُوْنَ  ',
		ayahNumber: 96,
		translationId: 'Mereka berkata sambil bertengkar di dalamnya (neraka),',
	),
	Ayah(
		ayahId: 3029,
		ayahText: 'تَاللّٰهِ اِنْ كُنَّا لَفِيْ ضَلٰلٍ مُّبِيْنٍ ۙ ',
		ayahNumber: 97,
		translationId: '”Demi Allah, sesungguhnya kita dahulu (di dunia) dalam kesesatan yang nyata,',
	),
	Ayah(
		ayahId: 3030,
		ayahText: 'اِذْ نُسَوِّيْكُمْ بِرَبِّ الْعٰلَمِيْنَ ',
		ayahNumber: 98,
		translationId: 'karena kita mempersamakan kamu (berhala-berhala) dengan Tuhan seluruh alam.',
	),
	Ayah(
		ayahId: 3031,
		ayahText: 'وَمَآ اَضَلَّنَآ اِلَّا الْمُجْرِمُوْنَ ',
		ayahNumber: 99,
		translationId: 'Dan tidak ada yang menyesatkan kita kecuali orang-orang yang berdosa.',
	),
	Ayah(
		ayahId: 3032,
		ayahText: 'فَمَا لَنَا مِنْ شَافِعِيْنَ ۙ ',
		ayahNumber: 100,
		translationId: 'Maka sehingga (sekarang) kita tidak mempunyai pemberi syafaat (penolong),',
	),
	Ayah(
		ayahId: 3033,
		ayahText: 'وَلَا صَدِيْقٍ حَمِيْمٍ  ',
		ayahNumber: 101,
		translationId: 'dan tidak pula mempunyai teman yang akrab,',
	),
	Ayah(
		ayahId: 3034,
		ayahText: 'فَلَوْ اَنَّ لَنَا كَرَّةً فَنَكُوْنَ مِنَ الْمُؤْمِنِيْنَ  ',
		ayahNumber: 102,
		translationId: 'Maka seandainya kita dapat kembali (ke dunia) niscaya kita menjadi orang-orang yang beriman.”',
	),
	Ayah(
		ayahId: 3035,
		ayahText: 'اِنَّ فِيْ ذٰلِكَ لَاٰيَةً ۗوَمَا كَانَ اَكْثَرُهُمْ مُّؤْمِنِيْنَ  ',
		ayahNumber: 103,
		translationId: 'Sungguh, pada yang demikian itu terdapat tanda (kekuasaan Allah), tetapi kebanyakan mereka tidak beriman.',
	),
	Ayah(
		ayahId: 3036,
		ayahText: 'وَاِنَّ رَبَّكَ لَهُوَ الْعَزِيْزُ الرَّحِيْمُ ࣖ ',
		ayahNumber: 104,
		translationId: 'Dan sungguh, Tuhanmu benar-benar Dialah Mahaperkasa, Maha Penyayang.',
	),
	Ayah(
		ayahId: 3037,
		ayahText: 'كَذَّبَتْ قَوْمُ نُوْحِ ِۨالْمُرْسَلِيْنَ ۚ ',
		ayahNumber: 105,
		translationId: 'Kaum Nuh telah mendustakan para rasul.',
	),
	Ayah(
		ayahId: 3038,
		ayahText: 'اِذْ قَالَ لَهُمْ اَخُوْهُمْ نُوْحٌ اَلَا تَتَّقُوْنَ ۚ ',
		ayahNumber: 106,
		translationId: 'Ketika saudara mereka (Nuh) berkata kepada mereka, “Mengapa kamu tidak bertakwa?',
	),
	Ayah(
		ayahId: 3039,
		ayahText: 'اِنِّيْ لَكُمْ رَسُوْلٌ اَمِيْنٌ ۙ  ',
		ayahNumber: 107,
		translationId: 'Sesungguhnya aku ini seorang rasul kepercayaan (yang diutus) kepadamu,',
	),
	Ayah(
		ayahId: 3040,
		ayahText: 'فَاتَّقُوا اللّٰهَ وَاَطِيْعُوْنِۚ  ',
		ayahNumber: 108,
		translationId: 'Maka bertakwalah kamu kepada Allah dan taatlah kepadaku.',
	),
	Ayah(
		ayahId: 3041,
		ayahText: 'وَمَآ اَسْـَٔلُكُمْ عَلَيْهِ مِنْ اَجْرٍۚ اِنْ اَجْرِيَ اِلَّا عَلٰى رَبِّ الْعٰلَمِيْنَ ۚ ',
		ayahNumber: 109,
		translationId: 'Dan aku tidak meminta imbalan kepadamu atas ajakan itu; imbalanku hanyalah dari Tuhan seluruh alam.',
	),
	Ayah(
		ayahId: 3042,
		ayahText: 'فَاتَّقُوا اللّٰهَ وَاَطِيْعُوْنِ  ',
		ayahNumber: 110,
		translationId: 'Maka bertakwalah kamu kepada Allah dan taatlah kepadaku.”',
	),
	Ayah(
		ayahId: 3043,
		ayahText: '۞ قَالُوْٓا اَنُؤْمِنُ لَكَ وَاتَّبَعَكَ الْاَرْذَلُوْنَ ۗ ',
		ayahNumber: 111,
		translationId: 'Mereka berkata, “Apakah kami harus beriman kepadamu, padahal pengikut-pengikutmu orang-orang yang hina?”',
	),
	Ayah(
		ayahId: 3044,
		ayahText: 'قَالَ وَمَا عِلْمِيْ بِمَا كَانُوْا يَعْمَلُوْنَ ۚ  ',
		ayahNumber: 112,
		translationId: 'Dia (Nuh) menjawab, “Tidak ada pengetahuanku tentang apa yang mereka kerjakan.',
	),
	Ayah(
		ayahId: 3045,
		ayahText: 'اِنْ حِسَابُهُمْ اِلَّا عَلٰى رَبِّيْ لَوْ تَشْعُرُوْنَ ۚ  ',
		ayahNumber: 113,
		translationId: 'Perhitungan (amal perbuatan) mereka tidak lain hanyalah kepada Tuhanku, jika kamu menyadari.',
	),
	Ayah(
		ayahId: 3046,
		ayahText: 'وَمَآ اَنَا۠ بِطَارِدِ الْمُؤْمِنِيْنَ ۚ ',
		ayahNumber: 114,
		translationId: 'Dan aku tidak akan mengusir orang-orang yang beriman.',
	),
	Ayah(
		ayahId: 3047,
		ayahText: 'اِنْ اَنَا۠ اِلَّا نَذِيْرٌ مُّبِيْنٌ ۗ ',
		ayahNumber: 115,
		translationId: 'Aku (ini) hanyalah pemberi peringatan yang jelas.”',
	),
	Ayah(
		ayahId: 3048,
		ayahText: 'قَالُوْا لَىِٕنْ لَّمْ تَنْتَهِ يٰنُوْحُ لَتَكُوْنَنَّ مِنَ الْمَرْجُوْمِيْنَۗ  ',
		ayahNumber: 116,
		translationId: 'Mereka berkata, “Wahai Nuh! Sungguh, jika engkau tidak (mau) berhenti, niscaya engkau termasuk orang yang dirajam (dilempari batu sampai mati).”',
	),
	Ayah(
		ayahId: 3049,
		ayahText: 'قَالَ رَبِّ اِنَّ قَوْمِيْ كَذَّبُوْنِۖ ',
		ayahNumber: 117,
		translationId: 'Dia (Nuh) berkata, “Ya Tuhanku, sungguh kaumku telah mendustakan aku;',
	),
	Ayah(
		ayahId: 3050,
		ayahText: 'فَافْتَحْ بَيْنِيْ وَبَيْنَهُمْ فَتْحًا وَّنَجِّنِيْ وَمَنْ مَّعِيَ مِنَ الْمُؤْمِنِيْنَ  ',
		ayahNumber: 118,
		translationId: 'maka berilah keputusan antara aku dengan mereka, dan selamatkanlah aku dan mereka yang beriman bersamaku.” ',
	),
	Ayah(
		ayahId: 3051,
		ayahText: 'فَاَنْجَيْنٰهُ وَمَنْ مَّعَهٗ فِى الْفُلْكِ الْمَشْحُوْنِ  ',
		ayahNumber: 119,
		translationId: 'Kemudian Kami menyelamatkannya Nuh dan orang-orang yang bersamanya di dalam kapal yang penuh muatan.',
	),
	Ayah(
		ayahId: 3052,
		ayahText: 'ثُمَّ اَغْرَقْنَا بَعْدُ الْبٰقِيْنَ  ',
		ayahNumber: 120,
		translationId: 'Kemudian setelah itu Kami tenggelamkan orang-orang yang tinggal.',
	),
	Ayah(
		ayahId: 3053,
		ayahText: 'اِنَّ فِيْ ذٰلِكَ لَاٰيَةً ۗوَمَا كَانَ اَكْثَرُهُمْ مُّؤْمِنِيْنَ  ',
		ayahNumber: 121,
		translationId: 'Sungguh, pada yang demikian itu benar-benar terdapat tanda (kekuasaan Allah), tetapi kebanyakan mereka tidak beriman.',
	),
	Ayah(
		ayahId: 3054,
		ayahText: 'وَاِنَّ رَبَّكَ لَهُوَ الْعَزِيْزُ الرَّحِيْمُ ࣖ ',
		ayahNumber: 122,
		translationId: 'Dan sungguh, Tuhanmu, Dialah Yang Mahaperkasa, Maha Penyayang.',
	),
	Ayah(
		ayahId: 3055,
		ayahText: 'كَذَّبَتْ عَادُ ِۨالْمُرْسَلِيْنَ ۖ ',
		ayahNumber: 123,
		translationId: '(Kaum) ‘Ad telah mendustakan para rasul.',
	),
	Ayah(
		ayahId: 3056,
		ayahText: 'اِذْ قَالَ لَهُمْ اَخُوْهُمْ هُوْدٌ اَلَا تَتَّقُوْنَ ۚ ',
		ayahNumber: 124,
		translationId: 'Ketika saudara mereka Hud berkata kepada mereka, “Mengapa kamu tidak bertakwa?',
	),
	Ayah(
		ayahId: 3057,
		ayahText: 'اِنِّيْ لَكُمْ رَسُوْلٌ اَمِيْنٌ ۙ ',
		ayahNumber: 125,
		translationId: 'Sungguh, aku ini seorang rasul kepercayaan (yang diutus) kepadamu,',
	),
	Ayah(
		ayahId: 3058,
		ayahText: 'فَاتَّقُوا اللّٰهَ وَاَطِيْعُوْنِ ۚ ',
		ayahNumber: 126,
		translationId: 'karena itu bertakwalah kepada Allah dan taatlah kepadaku.',
	),
	Ayah(
		ayahId: 3059,
		ayahText: 'وَمَآ اَسْـَٔلُكُمْ عَلَيْهِ مِنْ اَجْرٍۚ اِنْ اَجْرِيَ اِلَّا عَلٰى رَبِّ الْعٰلَمِيْنَ ۗ ',
		ayahNumber: 127,
		translationId: 'Dan aku tidak meminta imbalan kepadamu atas ajakan itu; imbalanku hanyalah dari Tuhan seluruh alam.',
	),
	Ayah(
		ayahId: 3060,
		ayahText: 'اَتَبْنُوْنَ بِكُلِّ رِيْعٍ اٰيَةً تَعْبَثُوْنَ ۙ ',
		ayahNumber: 128,
		translationId: 'Apakah kamu mendirikan istana-istana pada setiap tanah yang tinggi untuk kemegahan tanpa ditempati, ',
	),
	Ayah(
		ayahId: 3061,
		ayahText: 'وَتَتَّخِذُوْنَ مَصَانِعَ لَعَلَّكُمْ تَخْلُدُوْنَۚ  ',
		ayahNumber: 129,
		translationId: 'dan kamu membuat benteng-benteng dengan harapan kamu hidup kekal?',
	),
	Ayah(
		ayahId: 3062,
		ayahText: 'وَاِذَا بَطَشْتُمْ بَطَشْتُمْ جَبَّارِيْنَۚ  ',
		ayahNumber: 130,
		translationId: 'Dan apabila kamu menyiksa, maka kamu lakukan secara kejam dan bengis.',
	),
	Ayah(
		ayahId: 3063,
		ayahText: 'فَاتَّقُوا اللّٰهَ وَاَطِيْعُوْنِۚ  ',
		ayahNumber: 131,
		translationId: 'Maka bertakwalah kepada Allah dan taatlah kepadaku,',
	),
	Ayah(
		ayahId: 3064,
		ayahText: 'وَاتَّقُوا الَّذِيْٓ اَمَدَّكُمْ بِمَا تَعْلَمُوْنَ  ۚ',
		ayahNumber: 132,
		translationId: 'dan tetaplah kamu bertakwa kepada-Nya yang telah menganugerahkan kepadamu apa yang kamu ketahui.',
	),
	Ayah(
		ayahId: 3065,
		ayahText: 'اَمَدَّكُمْ بِاَنْعَامٍ وَّبَنِيْنَۙ  ',
		ayahNumber: 133,
		translationId: 'Dia (Allah) telah menganugerahkan kepadamu hewan ternak dan anak-anak,',
	),
	Ayah(
		ayahId: 3066,
		ayahText: 'وَجَنّٰتٍ وَّعُيُوْنٍۚ  ',
		ayahNumber: 134,
		translationId: 'dan kebun-kebun, dan mata air,',
	),
	Ayah(
		ayahId: 3067,
		ayahText: 'اِنِّيْٓ اَخَافُ عَلَيْكُمْ عَذَابَ يَوْمٍ عَظِيْمٍ ۗ ',
		ayahNumber: 135,
		translationId: 'sesungguhnya aku takut kamu akan ditimpa azab pada hari yang besar.” ',
	),
	Ayah(
		ayahId: 3068,
		ayahText: 'قَالُوْا سَوَاۤءٌ عَلَيْنَآ اَوَعَظْتَ اَمْ لَمْ تَكُنْ مِّنَ الْوَاعِظِيْنَ ۙ ',
		ayahNumber: 136,
		translationId: 'Mereka menjawab, “Sama saja bagi kami, apakah engkau memberi nasihat atau tidak memberi nasihat,',
	),
	Ayah(
		ayahId: 3069,
		ayahText: 'اِنْ هٰذَآ اِلَّا خُلُقُ الْاَوَّلِيْنَ ۙ ',
		ayahNumber: 137,
		translationId: '(agama kami) ini tidak lain hanyalah adat kebiasaan orang-orang terdahulu,',
	),
	Ayah(
		ayahId: 3070,
		ayahText: 'وَمَا نَحْنُ بِمُعَذَّبِيْنَ ۚ ',
		ayahNumber: 138,
		translationId: 'dan kami (sama sekali) tidak akan diazab.”',
	),
	Ayah(
		ayahId: 3071,
		ayahText: 'فَكَذَّبُوْهُ فَاَهْلَكْنٰهُمْۗ اِنَّ فِيْ ذٰلِكَ لَاٰيَةً ۗوَمَا كَانَ اَكْثَرُهُمْ مُّؤْمِنِيْنَ  ',
		ayahNumber: 139,
		translationId: 'Maka mereka mendustakannya (Hud), lalu Kami binasakan mereka. Sungguh, pada yang demikian itu terdapat tanda (kekuasaan Allah), tetapi kebanyakan mereka tidak beriman.',
	),
	Ayah(
		ayahId: 3072,
		ayahText: 'وَاِنَّ رَبَّكَ لَهُوَ الْعَزِيْزُ الرَّحِيْمُ ࣖ',
		ayahNumber: 140,
		translationId: 'Dan sungguh, Tuhanmu, Dialah Yang Mahaperkasa, Maha Penyayang.',
	),
	Ayah(
		ayahId: 3073,
		ayahText: 'كَذَّبَتْ ثَمُوْدُ الْمُرْسَلِيْنَ  ۖ ',
		ayahNumber: 141,
		translationId: 'Kaum Samud telah mendustakan para rasul.',
	),
	Ayah(
		ayahId: 3074,
		ayahText: 'اِذْ قَالَ لَهُمْ اَخُوْهُمْ صٰلِحٌ اَلَا تَتَّقُوْنَ ۚ ',
		ayahNumber: 142,
		translationId: 'Ketika saudara mereka Saleh berkata kepada mereka, “Mengapa kamu tidak bertakwa?',
	),
	Ayah(
		ayahId: 3075,
		ayahText: 'اِنِّيْ لَكُمْ رَسُوْلٌ اَمِيْنٌ ۙ  ',
		ayahNumber: 143,
		translationId: 'Sungguh, aku ini seorang rasul kepercayaan (yang diutus) kepadamu,',
	),
	Ayah(
		ayahId: 3076,
		ayahText: 'فَاتَّقُوا اللّٰهَ وَاَطِيْعُوْنِ ۚ  ',
		ayahNumber: 144,
		translationId: 'karena itu bertakwalah kepada Allah dan taatlah kepadaku.',
	),
	Ayah(
		ayahId: 3077,
		ayahText: 'وَمَآ اَسْـَٔلُكُمْ عَلَيْهِ مِنْ اَجْرٍۚ اِنْ اَجْرِيَ اِلَّا عَلٰى رَبِّ الْعٰلَمِيْنَ ۗ ',
		ayahNumber: 145,
		translationId: 'Dan aku tidak meminta sesuatu imbalan kepadamu atas ajakan itu, imbalanku hanyalah dari Tuhan seluruh alam.',
	),
	Ayah(
		ayahId: 3078,
		ayahText: 'اَتُتْرَكُوْنَ فِيْ مَا هٰهُنَآ اٰمِنِيْنَ ۙ ',
		ayahNumber: 146,
		translationId: 'Apakah kamu (mengira) akan dibiarkan tinggal di sini (di negeri kamu ini) dengan aman,',
	),
	Ayah(
		ayahId: 3079,
		ayahText: 'فِيْ جَنّٰتٍ وَّعُيُوْنٍ ۙ ',
		ayahNumber: 147,
		translationId: 'di dalam kebun-kebun dan mata air,',
	),
	Ayah(
		ayahId: 3080,
		ayahText: 'وَّزُرُوْعٍ وَّنَخْلٍ طَلْعُهَا هَضِيْمٌ ۚ ',
		ayahNumber: 148,
		translationId: 'dan tanaman-tanaman dan pohon-pohon kurma yang mayangnya lembut.',
	),
	Ayah(
		ayahId: 3081,
		ayahText: 'وَتَنْحِتُوْنَ مِنَ الْجِبَالِ بُيُوْتًا فٰرِهِيْنَ ',
		ayahNumber: 149,
		translationId: 'Dan kamu pahat dengan terampil sebagian gunung-gunung untuk dijadikan rumah-rumah;',
	),
	Ayah(
		ayahId: 3082,
		ayahText: 'فَاتَّقُوا اللّٰهَ وَاَطِيْعُوْنِ ۚ ',
		ayahNumber: 150,
		translationId: 'maka bertakwalah kepada Allah dan taatlah kepadaku;',
	),
	Ayah(
		ayahId: 3083,
		ayahText: 'وَلَا تُطِيْعُوْٓا اَمْرَ الْمُسْرِفِيْنَ ۙ ',
		ayahNumber: 151,
		translationId: 'dan janganlah kamu menaati perintah orang-orang yang melampaui batas,',
	),
	Ayah(
		ayahId: 3084,
		ayahText: 'الَّذِيْنَ يُفْسِدُوْنَ فِى الْاَرْضِ وَلَا يُصْلِحُوْنَ  ',
		ayahNumber: 152,
		translationId: 'yang berbuat kerusakan di bumi dan tidak mengadakan perbaikan.”',
	),
	Ayah(
		ayahId: 3085,
		ayahText: 'قَالُوْٓا اِنَّمَآ اَنْتَ مِنَ الْمُسَحَّرِيْنَ ۙ ',
		ayahNumber: 153,
		translationId: 'Mereka berkata, “Sungguh, engkau hanyalah termasuk orang yang kena sihir;',
	),
	Ayah(
		ayahId: 3086,
		ayahText: 'مَآ اَنْتَ اِلَّا بَشَرٌ مِّثْلُنَاۙ فَأْتِ بِاٰيَةٍ اِنْ كُنْتَ مِنَ الصّٰدِقِيْنَ  ',
		ayahNumber: 154,
		translationId: 'engkau hanyalah manusia seperti kami; maka datangkanlah sesuatu mukjizat jika engkau termasuk orang yang benar.”',
	),
	Ayah(
		ayahId: 3087,
		ayahText: 'قَالَ هٰذِهٖ نَاقَةٌ لَّهَا شِرْبٌ وَّلَكُمْ شِرْبُ يَوْمٍ مَّعْلُوْمٍ ۚ ',
		ayahNumber: 155,
		translationId: 'Dia (Saleh) menjawab, “Ini seekor unta betina, yang berhak mendapatkan (giliran) minum, dan kamu juga berhak mendapatkan minum pada hari yang ditentukan.',
	),
	Ayah(
		ayahId: 3088,
		ayahText: 'وَلَا تَمَسُّوْهَا بِسُوْۤءٍ فَيَأْخُذَكُمْ عَذَابُ يَوْمٍ عَظِيْمٍ  ',
		ayahNumber: 156,
		translationId: 'Dan jangan kamu menyentuhnya (unta itu) dengan sesuatu kejahatan, nanti kamu akan ditimpa azab pada hari yang dahsyat.”',
	),
	Ayah(
		ayahId: 3089,
		ayahText: 'فَعَقَرُوْهَا فَاَصْبَحُوْا نٰدِمِيْنَ ۙ ',
		ayahNumber: 157,
		translationId: 'Kemudian mereka membunuhnya, lalu mereka merasa menyesal,',
	),
	Ayah(
		ayahId: 3090,
		ayahText: 'فَاَخَذَهُمُ الْعَذَابُۗ اِنَّ فِيْ ذٰلِكَ لَاٰيَةً ۗوَمَا كَانَ اَكْثَرُهُمْ مُّؤْمِنِيْنَ  ',
		ayahNumber: 158,
		translationId: 'maka mereka ditimpa azab. Sungguh, pada yang demikian itu terdapat tanda (kekuasaan Allah), tetapi kebanyakan mereka tidak beriman.',
	),
	Ayah(
		ayahId: 3091,
		ayahText: 'وَاِنَّ رَبَّكَ لَهُوَ الْعَزِيْزُ الرَّحِيْمُ ࣖ ',
		ayahNumber: 159,
		translationId: 'Dan sungguh, Tuhanmu, Dialah Yang Mahaperkasa, Maha Penyayang.',
	),
	Ayah(
		ayahId: 3092,
		ayahText: 'كَذَّبَتْ قَوْمُ لُوْطِ ِۨالْمُرْسَلِيْنَ ۖ ',
		ayahNumber: 160,
		translationId: 'Kaum Lut telah mendustakan para rasul,',
	),
	Ayah(
		ayahId: 3093,
		ayahText: 'اِذْ قَالَ لَهُمْ اَخُوْهُمْ لُوْطٌ اَلَا تَتَّقُوْنَ ۚ  ',
		ayahNumber: 161,
		translationId: 'ketika saudara mereka Lut berkata kepada mereka, “Mengapa kamu tidak bertakwa?”',
	),
	Ayah(
		ayahId: 3094,
		ayahText: 'اِنِّيْ لَكُمْ رَسُوْلٌ اَمِيْنٌ ۙ ',
		ayahNumber: 162,
		translationId: 'Sungguh, aku ini seorang rasul kepercayaan (yang diutus) kepadamu,',
	),
	Ayah(
		ayahId: 3095,
		ayahText: 'فَاتَّقُوا اللّٰهَ وَاَطِيْعُوْنِ ۚ ',
		ayahNumber: 163,
		translationId: 'maka bertakwalah kepada Allah dan taatlah kepadaku.',
	),
	Ayah(
		ayahId: 3096,
		ayahText: 'وَمَآ اَسْـَٔلُكُمْ عَلَيْهِ مِنْ اَجْرٍ اِنْ اَجْرِيَ اِلَّا عَلٰى رَبِّ الْعٰلَمِيْنَ ۗ ',
		ayahNumber: 164,
		translationId: 'Dan aku tidak meminta imbalan kepadamu atas ajakan itu; imbalanku hanyalah dari Tuhan seluruh alam.',
	),
	Ayah(
		ayahId: 3097,
		ayahText: 'اَتَأْتُوْنَ الذُّكْرَانَ مِنَ الْعٰلَمِيْنَ ۙ ',
		ayahNumber: 165,
		translationId: 'Mengapa kamu mendatangi jenis laki-laki di antara manusia (berbuat homoseks),',
	),
	Ayah(
		ayahId: 3098,
		ayahText: 'وَتَذَرُوْنَ مَا خَلَقَ لَكُمْ رَبُّكُمْ مِّنْ اَزْوَاجِكُمْۗ بَلْ اَنْتُمْ قَوْمٌ عٰدُوْنَ  ',
		ayahNumber: 166,
		translationId: 'dan kamu tinggalkan (perempuan) yang diciptakan Tuhan untuk menjadi istri-istri kamu? Kamu (memang) orang-orang yang melampaui batas.” ',
	),
	Ayah(
		ayahId: 3099,
		ayahText: 'قَالُوْا لَىِٕنْ لَّمْ تَنْتَهِ يٰلُوْطُ لَتَكُوْنَنَّ مِنَ الْمُخْرَجِيْنَ  ',
		ayahNumber: 167,
		translationId: 'Mereka menjawab, “Wahai Lut! Jika engkau tidak berhenti, engkau termasuk orang-orang yang terusir.”',
	),
	Ayah(
		ayahId: 3100,
		ayahText: 'قَالَ ِانِّيْ لِعَمَلِكُمْ مِّنَ الْقَالِيْنَ  ۗ',
		ayahNumber: 168,
		translationId: 'Dia (Lut) berkata, “Aku sungguh benci kepada perbuatanmu.”',
	),
	Ayah(
		ayahId: 3101,
		ayahText: 'رَبِّ نَجِّنِيْ وَاَهْلِيْ مِمَّا يَعْمَلُوْنَ  ',
		ayahNumber: 169,
		translationId: '(Lut berdoa), “Ya Tuhanku, selamatkanlah aku dan keluargaku dari (akibat) perbuatan yang mereka kerjakan.”',
	),
	Ayah(
		ayahId: 3102,
		ayahText: 'فَنَجَّيْنٰهُ وَاَهْلَهٗٓ اَجْمَعِيْنَ ۙ ',
		ayahNumber: 170,
		translationId: 'Lalu Kami selamatkan dia bersama keluarganya semua,',
	),
	Ayah(
		ayahId: 3103,
		ayahText: 'اِلَّا عَجُوْزًا فِى الْغٰبِرِيْنَ ۚ  ',
		ayahNumber: 171,
		translationId: 'kecuali seorang perempuan tua (istrinya), yang termasuk dalam golongan yang tinggal.',
	),
	Ayah(
		ayahId: 3104,
		ayahText: 'ثُمَّ دَمَّرْنَا الْاٰخَرِيْنَ ۚ ',
		ayahNumber: 172,
		translationId: 'Kemudian Kami binasakan yang lain.',
	),
	Ayah(
		ayahId: 3105,
		ayahText: 'وَاَمْطَرْنَا عَلَيْهِمْ مَّطَرًاۚ فَسَاۤءَ مَطَرُ الْمُنْذَرِيْنَ ',
		ayahNumber: 173,
		translationId: 'Dan Kami hujani mereka (dengan hujan batu), maka betapa buruk hujan yang menimpa orang-orang yang telah diberi peringatan itu.',
	),
	Ayah(
		ayahId: 3106,
		ayahText: 'اِنَّ فِيْ ذٰلِكَ لَاٰيَةً ۗوَمَا كَانَ اَكْثَرُهُمْ مُّؤْمِنِيْنَ  ',
		ayahNumber: 174,
		translationId: 'Sungguh, pada yang demikian itu terdapat tanda (kekuasaan Allah), tetapi kebanyakan mereka tidak beriman.',
	),
	Ayah(
		ayahId: 3107,
		ayahText: 'وَاِنَّ رَبَّكَ لَهُوَ الْعَزِيْزُ الرَّحِيْمُ ࣖ',
		ayahNumber: 175,
		translationId: 'Dan sungguh, Tuhanmu, Dialah Yang Mahaperkasa, Maha Penyayang.',
	),
	Ayah(
		ayahId: 3108,
		ayahText: 'كَذَّبَ اَصْحٰبُ لْـَٔيْكَةِ الْمُرْسَلِيْنَ ۖ ',
		ayahNumber: 176,
		translationId: 'Penduduk Aikah telah mendustakan para rasul;',
	),
	Ayah(
		ayahId: 3109,
		ayahText: 'اِذْ قَالَ لَهُمْ شُعَيْبٌ اَلَا تَتَّقُوْنَ ۚ ',
		ayahNumber: 177,
		translationId: 'ketika Syuaib berkata kepada mereka, “Mengapa kamu tidak bertakwa?',
	),
	Ayah(
		ayahId: 3110,
		ayahText: 'اِنِّيْ لَكُمْ رَسُوْلٌ اَمِيْنٌ ۙ ',
		ayahNumber: 178,
		translationId: 'Sungguh, aku adalah rasul kepercayaan (yang diutus) kepadamu,',
	),
	Ayah(
		ayahId: 3111,
		ayahText: 'فَاتَّقُوا اللّٰهَ وَاَطِيْعُوْنِ ۚ ',
		ayahNumber: 179,
		translationId: 'maka bertakwalah kepada Allah dan taatlah kepadaku;',
	),
	Ayah(
		ayahId: 3112,
		ayahText: 'وَمَآ اَسْـَٔلُكُمْ عَلَيْهِ مِنْ اَجْرٍ اِنْ اَجْرِيَ اِلَّا عَلٰى رَبِّ الْعٰلَمِيْنَ ۗ ',
		ayahNumber: 180,
		translationId: 'Dan aku tidak meminta imbalan kepadamu atas ajakan itu; imbalanku hanyalah dari Tuhan seluruh alam.',
	),
	Ayah(
		ayahId: 3113,
		ayahText: '۞ اَوْفُوا الْكَيْلَ وَلَا تَكُوْنُوْا مِنَ الْمُخْسِرِيْنَ ۚ ',
		ayahNumber: 181,
		translationId: 'Sempurnakanlah takaran dan janganlah kamu merugikan orang lain.',
	),
	Ayah(
		ayahId: 3114,
		ayahText: 'وَزِنُوْا بِالْقِسْطَاسِ الْمُسْتَقِيْمِ ۚ ',
		ayahNumber: 182,
		translationId: 'Dan timbanglah dengan timbangan yang benar.',
	),
	Ayah(
		ayahId: 3115,
		ayahText: 'وَلَا تَبْخَسُوا النَّاسَ اَشْيَاۤءَهُمْ وَلَا تَعْثَوْا فِى الْاَرْضِ مُفْسِدِيْنَ ۚ ',
		ayahNumber: 183,
		translationId: 'Dan janganlah kamu merugikan manusia dengan mengurangi hak-haknya dan janganlah membuat kerusakan di bumi;',
	),
	Ayah(
		ayahId: 3116,
		ayahText: 'وَاتَّقُوا الَّذِيْ خَلَقَكُمْ وَالْجِبِلَّةَ الْاَوَّلِيْنَ ۗ ',
		ayahNumber: 184,
		translationId: 'dan bertakwalah kepada Allah yang telah menciptakan kamu dan umat-umat yang terdahulu.”',
	),
	Ayah(
		ayahId: 3117,
		ayahText: 'قَالُوْٓا اِنَّمَآ اَنْتَ مِنَ الْمُسَحَّرِيْنَ ۙ ',
		ayahNumber: 185,
		translationId: 'Mereka berkata, “Engkau tidak lain hanyalah orang-orang yang kena sihir.',
	),
	Ayah(
		ayahId: 3118,
		ayahText: 'وَمَآ اَنْتَ اِلَّا بَشَرٌ مِّثْلُنَا وَاِنْ نَّظُنُّكَ لَمِنَ الْكٰذِبِيْنَ ۚ ',
		ayahNumber: 186,
		translationId: 'Dan engkau hanyalah manusia seperti kami, dan sesungguhnya kami yakin engkau termasuk orang-orang yang berdusta.',
	),
	Ayah(
		ayahId: 3119,
		ayahText: 'فَاَسْقِطْ عَلَيْنَا كِسَفًا مِّنَ السَّمَاۤءِ اِنْ كُنْتَ مِنَ الصّٰدِقِيْنَ ۗ ',
		ayahNumber: 187,
		translationId: 'Maka jatuhkanlah kepada kami gumpalan dari langit, jika engkau termasuk orang-orang yang benar.”',
	),
	Ayah(
		ayahId: 3120,
		ayahText: 'قَالَ رَبِّيْٓ اَعْلَمُ بِمَا تَعْمَلُوْنَ  ',
		ayahNumber: 188,
		translationId: 'Dia (Syuaib) berkata, “Tuhanku lebih mengetahui apa yang kamu kerjakan.”',
	),
	Ayah(
		ayahId: 3121,
		ayahText: 'فَكَذَّبُوْهُ فَاَخَذَهُمْ عَذَابُ يَوْمِ الظُّلَّةِ ۗاِنَّهٗ كَانَ عَذَابَ يَوْمٍ عَظِيْمٍ ',
		ayahNumber: 189,
		translationId: 'Kemudian mereka mendustakannya (Syuaib), lalu mereka ditimpa azab pada hari yang gelap. Sungguh, itulah azab pada hari yang dahsyat.',
	),
	Ayah(
		ayahId: 3122,
		ayahText: 'اِنَّ فِيْ ذٰلِكَ لَاٰيَةً ۗوَمَا كَانَ اَكْثَرُهُمْ مُّؤْمِنِيْنَ  ',
		ayahNumber: 190,
		translationId: 'Sungguh, pada yang demikian itu benar-benar terdapat tanda (kekuasaan Allah), tetapi kebanyakan mereka tidak beriman.',
	),
	Ayah(
		ayahId: 3123,
		ayahText: 'وَاِنَّ رَبَّكَ لَهُوَ الْعَزِيْزُ الرَّحِيْمُ ࣖ ',
		ayahNumber: 191,
		translationId: 'Dan sungguh, Tuhanmu, Dialah yang Mahaperkasa, Maha Penyayang.',
	),
	Ayah(
		ayahId: 3124,
		ayahText: 'وَاِنَّهٗ لَتَنْزِيْلُ رَبِّ الْعٰلَمِيْنَ ۗ  ',
		ayahNumber: 192,
		translationId: "Dan sungguh, (Al-Qur'an) ini benar-benar diturunkan oleh Tuhan seluruh alam,",
	),
	Ayah(
		ayahId: 3125,
		ayahText: 'نَزَلَ بِهِ الرُّوْحُ الْاَمِيْنُ ۙ ',
		ayahNumber: 193,
		translationId: 'Yang dibawa turun oleh ar-Ruh al-Amin (Jibril), ',
	),
	Ayah(
		ayahId: 3126,
		ayahText: 'عَلٰى قَلْبِكَ لِتَكُوْنَ مِنَ الْمُنْذِرِيْنَ ۙ  ',
		ayahNumber: 194,
		translationId: 'ke dalam hatimu (Muhammad) agar engkau termasuk orang yang memberi peringatan,',
	),
	Ayah(
		ayahId: 3127,
		ayahText: 'بِلِسَانٍ عَرَبِيٍّ مُّبِيْنٍ ۗ ',
		ayahNumber: 195,
		translationId: 'dengan bahasa Arab yang jelas.',
	),
	Ayah(
		ayahId: 3128,
		ayahText: 'وَاِنَّهٗ لَفِيْ زُبُرِ الْاَوَّلِيْنَ  ',
		ayahNumber: 196,
		translationId: "Dan sungguh, (Al-Qur'an) itu (disebut) dalam kitab-kitab orang yang terdahulu.",
	),
	Ayah(
		ayahId: 3129,
		ayahText: 'اَوَلَمْ يَكُنْ لَّهُمْ اٰيَةً اَنْ يَّعْلَمَهٗ عُلَمٰۤؤُا بَنِيْٓ اِسْرَاۤءِيْلَ  ',
		ayahNumber: 197,
		translationId: 'Apakah tidak (cukup) menjadi bukti bagi mereka, bahwa para ulama Bani Israil mengetahuinya?',
	),
	Ayah(
		ayahId: 3130,
		ayahText: 'وَلَوْ نَزَّلْنٰهُ عَلٰى بَعْضِ الْاَعْجَمِيْنَ ۙ ',
		ayahNumber: 198,
		translationId: "Dan seandainya (Al-Qur'an) itu Kami turunkan kepada sebagian dari golongan bukan Arab,",
	),
	Ayah(
		ayahId: 3131,
		ayahText: 'فَقَرَاَهٗ عَلَيْهِمْ مَّا كَانُوْا بِهٖ مُؤْمِنِيْنَ ۗ  ',
		ayahNumber: 199,
		translationId: 'lalu dia membacakannya kepada mereka (orang-orang kafir); niscaya mereka tidak juga akan beriman kepadanya.',
	),
	Ayah(
		ayahId: 3132,
		ayahText: 'كَذٰلِكَ سَلَكْنٰهُ فِيْ قُلُوْبِ الْمُجْرِمِيْنَ ۗ  ',
		ayahNumber: 200,
		translationId: 'Demikianlah, Kami masukkan (sifat dusta dan ingkar) ke dalam hati orang-orang yang berdosa,',
	),
	Ayah(
		ayahId: 3133,
		ayahText: 'لَا يُؤْمِنُوْنَ بِهٖ حَتّٰى يَرَوُا الْعَذَابَ الْاَلِيْمَ  ',
		ayahNumber: 201,
		translationId: 'mereka tidak akan beriman kepadanya, hingga mereka melihat azab yang pedih,',
	),
	Ayah(
		ayahId: 3134,
		ayahText: 'فَيَأْتِيَهُمْ بَغْتَةً وَّهُمْ لَا يَشْعُرُوْنَ ۙ  ',
		ayahNumber: 202,
		translationId: 'maka datang azab kepada mereka secara mendadak, ketika mereka tidak menyadarinya,',
	),
	Ayah(
		ayahId: 3135,
		ayahText: 'فَيَقُوْلُوْا هَلْ نَحْنُ مُنْظَرُوْنَ ۗ ',
		ayahNumber: 203,
		translationId: 'lalu mereka berkata, “Apakah kami diberi penangguhan waktu?” ',
	),
	Ayah(
		ayahId: 3136,
		ayahText: 'اَفَبِعَذَابِنَا يَسْتَعْجِلُوْنَ  ',
		ayahNumber: 204,
		translationId: 'Bukankah mereka yang meminta agar azab Kami dipercepat?',
	),
	Ayah(
		ayahId: 3137,
		ayahText: 'اَفَرَءَيْتَ اِنْ مَّتَّعْنٰهُمْ سِنِيْنَ ۙ  ',
		ayahNumber: 205,
		translationId: 'Maka bagaimana pendapatmu jika kepada mereka Kami berikan kenikmatan hidup beberapa tahun,',
	),
	Ayah(
		ayahId: 3138,
		ayahText: 'ثُمَّ جَاۤءَهُمْ مَّا كَانُوْا يُوْعَدُوْنَ ۙ  ',
		ayahNumber: 206,
		translationId: 'kemudian datang kepada mereka azab yang diancamkan kepada mereka,',
	),
	Ayah(
		ayahId: 3139,
		ayahText: 'مَآ اَغْنٰى عَنْهُمْ مَّا كَانُوْا يُمَتَّعُوْنَ ۗ ',
		ayahNumber: 207,
		translationId: 'niscaya tidak berguna bagi mereka kenikmatan yang mereka rasakan.',
	),
	Ayah(
		ayahId: 3140,
		ayahText: 'وَمَآ اَهْلَكْنَا مِنْ قَرْيَةٍ اِلَّا لَهَا مُنْذِرُوْنَ ۖ  ',
		ayahNumber: 208,
		translationId: 'Dan Kami tidak membinasakan sesuatu negeri, kecuali setelah ada orang-orang yang memberi peringatan kepadanya;',
	),
	Ayah(
		ayahId: 3141,
		ayahText: 'ذِكْرٰىۚ وَمَا كُنَّا ظٰلِمِيْنَ  ',
		ayahNumber: 209,
		translationId: 'untuk (menjadi) peringatan. Dan Kami tidak berlaku zalim. ',
	),
	Ayah(
		ayahId: 3142,
		ayahText: 'وَمَا تَنَزَّلَتْ بِهِ الشَّيٰطِيْنُ  ',
		ayahNumber: 210,
		translationId: "Dan (Al-Qur'an) itu tidaklah dibawa turun oleh setan-setan.",
	),
	Ayah(
		ayahId: 3143,
		ayahText: 'وَمَا يَنْۢبَغِيْ لَهُمْ وَمَا يَسْتَطِيْعُوْنَ ۗ  ',
		ayahNumber: 211,
		translationId: "Dan tidaklah pantas bagi mereka (Al-Qur'an itu), dan mereka pun tidak akan sanggup.",
	),
	Ayah(
		ayahId: 3144,
		ayahText: 'اِنَّهُمْ عَنِ السَّمْعِ لَمَعْزُوْلُوْنَ ۗ ',
		ayahNumber: 212,
		translationId: 'Sesungguhnya untuk mendengarkannya pun mereka dijauhkan.',
	),
	Ayah(
		ayahId: 3145,
		ayahText: 'فَلَا تَدْعُ مَعَ اللّٰهِ اِلٰهًا اٰخَرَ فَتَكُوْنَ مِنَ الْمُعَذَّبِيْنَ',
		ayahNumber: 213,
		translationId: 'Maka janganlah kamu menyeru (menyembah) tuhan selain Allah, nanti kamu termasuk orang-orang yang diazab.',
	),
	Ayah(
		ayahId: 3146,
		ayahText: 'وَاَنْذِرْ عَشِيْرَتَكَ الْاَقْرَبِيْنَ ۙ ',
		ayahNumber: 214,
		translationId: 'Dan berilah peringatan kepada kerabat-kerabatmu (Muhammad) yang terdekat,',
	),
	Ayah(
		ayahId: 3147,
		ayahText: 'وَاخْفِضْ جَنَاحَكَ لِمَنِ اتَّبَعَكَ مِنَ الْمُؤْمِنِيْنَ ۚ  ',
		ayahNumber: 215,
		translationId: 'dan rendahkanlah dirimu terhadap orang-orang yang beriman yang mengikutimu.',
	),
	Ayah(
		ayahId: 3148,
		ayahText: 'فَاِنْ عَصَوْكَ فَقُلْ اِنِّيْ بَرِيْۤءٌ مِّمَّا تَعْمَلُوْنَ ۚ ',
		ayahNumber: 216,
		translationId: 'Kemudian jika mereka mendurhakaimu maka katakanlah (Muhammad), “Sesungguhnya aku tidak bertanggung jawab terhadap apa yang kamu kerjakan.”',
	),
	Ayah(
		ayahId: 3149,
		ayahText: 'وَتَوَكَّلْ عَلَى الْعَزِيْزِ الرَّحِيْمِ ۙ ',
		ayahNumber: 217,
		translationId: 'Dan bertawakallah kepada (Allah) Yang Mahaperkasa, Maha Penyayang.',
	),
	Ayah(
		ayahId: 3150,
		ayahText: 'الَّذِيْ يَرٰىكَ حِيْنَ تَقُوْمُ  ',
		ayahNumber: 218,
		translationId: 'Yang melihat engkau ketika engkau berdiri (untuk salat),',
	),
	Ayah(
		ayahId: 3151,
		ayahText: 'وَتَقَلُّبَكَ فِى السّٰجِدِيْنَ  ',
		ayahNumber: 219,
		translationId: 'dan (melihat) perubahan gerakan badanmu di antara orang-orang yang sujud.',
	),
	Ayah(
		ayahId: 3152,
		ayahText: 'اِنَّهٗ هُوَ السَّمِيْعُ الْعَلِيْمُ  ',
		ayahNumber: 220,
		translationId: 'Sungguh, Dia Maha Mendengar, Maha Mengetahui.',
	),
	Ayah(
		ayahId: 3153,
		ayahText: 'هَلْ اُنَبِّئُكُمْ عَلٰى مَنْ تَنَزَّلُ الشَّيٰطِيْنُ ۗ  ',
		ayahNumber: 221,
		translationId: 'Maukah Aku beritakan kepadamu, kepada siapa setan-setan itu turun?',
	),
	Ayah(
		ayahId: 3154,
		ayahText: 'تَنَزَّلُ عَلٰى كُلِّ اَفَّاكٍ اَثِيْمٍ ۙ ',
		ayahNumber: 222,
		translationId: 'Mereka (setan) turun kepada setiap pendusta yang banyak berdosa,',
	),
	Ayah(
		ayahId: 3155,
		ayahText: 'يُّلْقُوْنَ السَّمْعَ وَاَكْثَرُهُمْ كٰذِبُوْنَ ۗ  ',
		ayahNumber: 223,
		translationId: 'mereka menyampaikan hasil pendengaran mereka, sedangkan kebanyakan mereka orang-orang pendusta.',
	),
	Ayah(
		ayahId: 3156,
		ayahText: 'وَالشُّعَرَاۤءُ يَتَّبِعُهُمُ الْغَاوٗنَ ۗ ',
		ayahNumber: 224,
		translationId: 'Dan penyair-penyair itu diikuti oleh orang-orang yang sesat.',
	),
	Ayah(
		ayahId: 3157,
		ayahText: 'اَلَمْ تَرَ اَنَّهُمْ فِيْ كُلِّ وَادٍ يَّهِيْمُوْنَ ۙ ',
		ayahNumber: 225,
		translationId: 'Tidakkah engkau melihat bahwa mereka mengembara di setiap lembah,',
	),
	Ayah(
		ayahId: 3158,
		ayahText: 'وَاَنَّهُمْ يَقُوْلُوْنَ مَا لَا يَفْعَلُوْنَ ۙ  ',
		ayahNumber: 226,
		translationId: 'dan bahwa mereka mengatakan apa yang mereka sendiri tidak mengerjakan(nya)?',
	),
	Ayah(
		ayahId: 3159,
		ayahText: 'اِلَّا الَّذِيْنَ اٰمَنُوْا وَعَمِلُوا الصّٰلِحٰتِ وَذَكَرُوا اللّٰهَ كَثِيْرًا وَّانْتَصَرُوْا مِنْۢ بَعْدِ مَا ظُلِمُوْا ۗوَسَيَعْلَمُ الَّذِيْنَ ظَلَمُوْٓا اَيَّ مُنْقَلَبٍ يَّنْقَلِبُوْنَ ࣖ ',
		ayahNumber: 227,
		translationId: 'Kecuali orang-orang (penyair-penyair) yang beriman dan berbuat kebajikan dan banyak mengingat Allah dan mendapat kemenangan setelah terzalimi (karena menjawab puisi-puisi orang-orang kafir). Dan orang-orang yang zalim kelak akan tahu ke tempat mana mereka akan kembali.',
	),
];
