// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah69 = [
	Ayah(
		ayahId: 5324,
		ayahText: 'اَلْحَاۤقَّةُۙ',
		ayahNumber: 1,
		translationId: 'Hari Kiamat,',
	),
	Ayah(
		ayahId: 5325,
		ayahText: 'مَا الْحَاۤقَّةُ ۚ ',
		ayahNumber: 2,
		translationId: 'apakah hari Kiamat itu?',
	),
	Ayah(
		ayahId: 5326,
		ayahText: 'وَمَآ اَدْرٰىكَ مَا الْحَاۤقَّةُ ۗ ',
		ayahNumber: 3,
		translationId: 'Dan tahukah kamu apakah hari Kiamat itu?',
	),
	Ayah(
		ayahId: 5327,
		ayahText: 'كَذَّبَتْ ثَمُوْدُ وَعَادٌ ۢبِالْقَارِعَةِ ',
		ayahNumber: 4,
		translationId: 'Kaum Samud, dan ‘Ad telah mendustakan hari Kiamat.',
	),
	Ayah(
		ayahId: 5328,
		ayahText: 'فَاَمَّا ثَمُوْدُ فَاُهْلِكُوْا بِالطَّاغِيَةِ ',
		ayahNumber: 5,
		translationId: 'Maka adapun kaum Samud, mereka telah dibinasakan dengan suara yang sangat keras,',
	),
	Ayah(
		ayahId: 5329,
		ayahText: 'وَاَمَّا عَادٌ فَاُهْلِكُوْا بِرِيْحٍ صَرْصَرٍ عَاتِيَةٍۙ',
		ayahNumber: 6,
		translationId: 'sedangkan kaum ‘Ad, mereka telah dibinasakan dengan angin topan yang sangat dingin,',
	),
	Ayah(
		ayahId: 5330,
		ayahText: 'سَخَّرَهَا عَلَيْهِمْ سَبْعَ لَيَالٍ وَّثَمٰنِيَةَ اَيَّامٍۙ حُسُوْمًا فَتَرَى الْقَوْمَ فِيْهَا صَرْعٰىۙ  كَاَنَّهُمْ اَعْجَازُ نَخْلٍ خَاوِيَةٍۚ',
		ayahNumber: 7,
		translationId: 'Allah menimpakan angin itu kepada mereka selama tujuh malam delapan hari terus-menerus; maka kamu melihat kaum ‘Ad pada waktu itu mati bergelimpangan seperti batang-batang pohon kurma yang telah kosong (lapuk).',
	),
	Ayah(
		ayahId: 5331,
		ayahText: 'فَهَلْ تَرٰى لَهُمْ مِّنْۢ بَاقِيَةٍ ',
		ayahNumber: 8,
		translationId: 'Maka adakah kamu melihat seorang pun yang masih tersisa di antara mereka?',
	),
	Ayah(
		ayahId: 5332,
		ayahText: 'وَجَاۤءَ فِرْعَوْنُ وَمَنْ قَبْلَهٗ وَالْمُؤْتَفِكٰتُ بِالْخَاطِئَةِۚ',
		ayahNumber: 9,
		translationId: 'Kemudian datang Fir‘aun dan orang-orang yang sebelumnya dan (penduduk) negeri-negeri yang dijungkirbalikkan karena kesalahan yang besar.',
	),
	Ayah(
		ayahId: 5333,
		ayahText: 'فَعَصَوْا رَسُوْلَ رَبِّهِمْ فَاَخَذَهُمْ اَخْذَةً رَّابِيَةً ',
		ayahNumber: 10,
		translationId: 'Maka mereka mendurhakai utusan Tuhannya, Allah menyiksa mereka dengan siksaan yang sangat keras. ',
	),
	Ayah(
		ayahId: 5334,
		ayahText: 'اِنَّا لَمَّا طَغَا الْمَاۤءُ حَمَلْنٰكُمْ فِى الْجَارِيَةِۙ',
		ayahNumber: 11,
		translationId: 'Sesungguhnya ketika air naik (sampai ke gunung), Kami membawa (nenek moyang) kamu ke dalam kapal, ',
	),
	Ayah(
		ayahId: 5335,
		ayahText: 'لِنَجْعَلَهَا لَكُمْ تَذْكِرَةً وَّتَعِيَهَآ اُذُنٌ وَّاعِيَةٌ ',
		ayahNumber: 12,
		translationId: 'agar Kami jadikan (peristiwa itu) sebagai peringatan bagi kamu dan agar diperhatikan oleh telinga yang mau mendengar. ',
	),
	Ayah(
		ayahId: 5336,
		ayahText: 'فَاِذَا نُفِخَ فِى الصُّوْرِ نَفْخَةٌ وَّاحِدَةٌ ۙ',
		ayahNumber: 13,
		translationId: 'Maka apabila sangkakala ditiup sekali tiup,',
	),
	Ayah(
		ayahId: 5337,
		ayahText: 'وَّحُمِلَتِ الْاَرْضُ وَالْجِبَالُ فَدُكَّتَا دَكَّةً وَّاحِدَةًۙ',
		ayahNumber: 14,
		translationId: 'dan diangkatlah bumi dan gunung-gunung, lalu dibenturkan keduanya sekali benturan.',
	),
	Ayah(
		ayahId: 5338,
		ayahText: 'فَيَوْمَىِٕذٍ وَّقَعَتِ الْوَاقِعَةُۙ',
		ayahNumber: 15,
		translationId: 'Maka pada hari itu terjadilah hari Kiamat, ',
	),
	Ayah(
		ayahId: 5339,
		ayahText: 'وَانْشَقَّتِ السَّمَاۤءُ فَهِيَ يَوْمَىِٕذٍ وَّاهِيَةٌۙ',
		ayahNumber: 16,
		translationId: 'dan terbelahlah langit, karena pada hari itu langit menjadi rapuh.',
	),
	Ayah(
		ayahId: 5340,
		ayahText: 'وَّالْمَلَكُ عَلٰٓى اَرْجَاۤىِٕهَاۗ وَيَحْمِلُ عَرْشَ رَبِّكَ فَوْقَهُمْ يَوْمَىِٕذٍ ثَمٰنِيَةٌ  ۗ',
		ayahNumber: 17,
		translationId: 'Dan para malaikat berada di berbagai penjuru langit. Pada hari itu delapan malaikat menjunjung ‘Arsy (singgasana) Tuhanmu di atas (kepala) mereka. ',
	),
	Ayah(
		ayahId: 5341,
		ayahText: 'يَوْمَىِٕذٍ تُعْرَضُوْنَ لَا تَخْفٰى مِنْكُمْ خَافِيَةٌ ',
		ayahNumber: 18,
		translationId: 'Pada hari itu kamu dihadapkan (kepada Tuhanmu), tidak ada sesuatu pun dari kamu yang tersembunyi (bagi Allah). ',
	),
	Ayah(
		ayahId: 5342,
		ayahText: 'فَاَمَّا مَنْ اُوْتِيَ كِتٰبَهٗ بِيَمِيْنِهٖ فَيَقُوْلُ هَاۤؤُمُ اقْرَءُوْا كِتٰبِيَهْۚ ',
		ayahNumber: 19,
		translationId: 'Adapun orang yang kitabnya  diberikan di tangan kanannya, maka dia berkata, “Ambillah, bacalah kitabku (ini).” ',
	),
	Ayah(
		ayahId: 5343,
		ayahText: 'اِنِّيْ ظَنَنْتُ اَنِّيْ مُلٰقٍ حِسَابِيَهْۚ',
		ayahNumber: 20,
		translationId: 'Sesungguhnya aku yakin, bahwa (suatu saat) aku akan menerima perhitungan terhadap diriku. ',
	),
	Ayah(
		ayahId: 5344,
		ayahText: 'فَهُوَ فِيْ عِيْشَةٍ رَّاضِيَةٍۚ',
		ayahNumber: 21,
		translationId: 'Maka orang itu berada dalam kehidupan yang diridai,',
	),
	Ayah(
		ayahId: 5345,
		ayahText: 'فِيْ جَنَّةٍ عَالِيَةٍۙ',
		ayahNumber: 22,
		translationId: 'dalam surga yang tinggi, ',
	),
	Ayah(
		ayahId: 5346,
		ayahText: 'قُطُوْفُهَا دَانِيَةٌ ',
		ayahNumber: 23,
		translationId: 'buah-buahannya dekat,',
	),
	Ayah(
		ayahId: 5347,
		ayahText: 'كُلُوْا وَاشْرَبُوْا هَنِيْۤـًٔا ۢبِمَآ اَسْلَفْتُمْ فِى الْاَيَّامِ الْخَالِيَةِ ',
		ayahNumber: 24,
		translationId: '(kepada mereka dikatakan), “Makan dan minumlah dengan nikmat karena amal yang telah kamu kerjakan pada hari-hari yang telah lalu.” ',
	),
	Ayah(
		ayahId: 5348,
		ayahText: 'وَاَمَّا مَنْ اُوْتِيَ كِتٰبَهٗ بِشِمَالِهٖ ەۙ فَيَقُوْلُ يٰلَيْتَنِيْ لَمْ اُوْتَ كِتٰبِيَهْۚ',
		ayahNumber: 25,
		translationId: 'Dan adapun orang yang kitabnya diberikan di tangan kirinya, maka dia berkata, “Alangkah baiknya jika kitabku (ini) tidak diberikan kepadaku.',
	),
	Ayah(
		ayahId: 5349,
		ayahText: 'وَلَمْ اَدْرِ مَا حِسَابِيَهْۚ',
		ayahNumber: 26,
		translationId: 'Sehingga aku tidak mengetahui bagaimana perhitunganku. ',
	),
	Ayah(
		ayahId: 5350,
		ayahText: 'يٰلَيْتَهَا كَانَتِ الْقَاضِيَةَۚ',
		ayahNumber: 27,
		translationId: 'Wahai, kiranya (kematian) itulah yang menyudahi segala sesuatu. ',
	),
	Ayah(
		ayahId: 5351,
		ayahText: 'مَآ اَغْنٰى عَنِّيْ مَالِيَهْۚ ',
		ayahNumber: 28,
		translationId: 'Hartaku sama sekali tidak berguna bagiku. ',
	),
	Ayah(
		ayahId: 5352,
		ayahText: 'هَلَكَ عَنِّيْ سُلْطٰنِيَهْۚ',
		ayahNumber: 29,
		translationId: 'Kekuasaanku telah hilang dariku.”',
	),
	Ayah(
		ayahId: 5353,
		ayahText: 'خُذُوْهُ فَغُلُّوْهُۙ',
		ayahNumber: 30,
		translationId: '(Allah berfirman), “Tangkaplah dia lalu belenggulah tangannya ke lehernya.” ',
	),
	Ayah(
		ayahId: 5354,
		ayahText: 'ثُمَّ الْجَحِيْمَ صَلُّوْهُۙ',
		ayahNumber: 31,
		translationId: 'Kemudian masukkanlah dia ke dalam api neraka yang menyala-nyala. ',
	),
	Ayah(
		ayahId: 5355,
		ayahText: 'ثُمَّ فِيْ سِلْسِلَةٍ ذَرْعُهَا سَبْعُوْنَ ذِرَاعًا فَاسْلُكُوْهُۗ',
		ayahNumber: 32,
		translationId: 'Kemudian belitlah dia dengan rantai yang panjangnya tujuh puluh hasta. ',
	),
	Ayah(
		ayahId: 5356,
		ayahText: 'اِنَّهٗ كَانَ لَا يُؤْمِنُ بِاللّٰهِ الْعَظِيْمِۙ',
		ayahNumber: 33,
		translationId: 'Sesungguhnya dialah orang yang tidak beriman kepada Allah Yang Mahabesar. ',
	),
	Ayah(
		ayahId: 5357,
		ayahText: 'وَلَا يَحُضُّ عَلٰى طَعَامِ الْمِسْكِيْنِۗ',
		ayahNumber: 34,
		translationId: 'Dan juga dia tidak mendorong (orang lain) untuk memberi makan orang miskin. ',
	),
	Ayah(
		ayahId: 5358,
		ayahText: 'فَلَيْسَ لَهُ الْيَوْمَ هٰهُنَا حَمِيْمٌۙ',
		ayahNumber: 35,
		translationId: 'Maka pada hari ini di sini tidak ada seorang teman pun baginya. ',
	),
	Ayah(
		ayahId: 5359,
		ayahText: 'وَّلَا طَعَامٌ اِلَّا مِنْ غِسْلِيْنٍۙ',
		ayahNumber: 36,
		translationId: 'Dan tidak ada makanan (baginya) kecuali dari darah dan nanah. ',
	),
	Ayah(
		ayahId: 5360,
		ayahText: 'لَّا يَأْكُلُهٗٓ اِلَّا الْخَاطِـُٔوْنَ ࣖ ',
		ayahNumber: 37,
		translationId: 'Tidak ada yang memakannya kecuali orang-orang yang berdosa. ',
	),
	Ayah(
		ayahId: 5361,
		ayahText: 'فَلَآ اُقْسِمُ بِمَا تُبْصِرُوْنَۙ',
		ayahNumber: 38,
		translationId: 'Maka Aku bersumpah demi apa yang kamu lihat, ',
	),
	Ayah(
		ayahId: 5362,
		ayahText: 'وَمَا لَا تُبْصِرُوْنَۙ',
		ayahNumber: 39,
		translationId: 'dan demi apa yang tidak kamu lihat.',
	),
	Ayah(
		ayahId: 5363,
		ayahText: 'اِنَّهٗ لَقَوْلُ رَسُوْلٍ كَرِيْمٍۙ',
		ayahNumber: 40,
		translationId: "Sesungguhnya ia (Al-Qur'an) itu benar-benar wahyu (yang diturunkan kepada) Rasul yang mulia,",
	),
	Ayah(
		ayahId: 5364,
		ayahText: 'وَّمَا هُوَ بِقَوْلِ شَاعِرٍۗ قَلِيْلًا مَّا تُؤْمِنُوْنَۙ',
		ayahNumber: 41,
		translationId: "dan ia (Al-Qur'an) bukanlah perkataan seorang penyair. Sedikit sekali kamu beriman kepadanya. ",
	),
	Ayah(
		ayahId: 5365,
		ayahText: 'وَلَا بِقَوْلِ كَاهِنٍۗ قَلِيْلًا مَّا تَذَكَّرُوْنَۗ',
		ayahNumber: 42,
		translationId: 'Dan bukan pula perkataan tukang tenung. Sedikit sekali kamu mengambil pelajaran darinya. ',
	),
	Ayah(
		ayahId: 5366,
		ayahText: 'تَنْزِيْلٌ مِّنْ رَّبِّ الْعٰلَمِيْنَ ',
		ayahNumber: 43,
		translationId: "Ia (Al-Qur'an) adalah wahyu yang diturunkan dari Tuhan seluruh alam. ",
	),
	Ayah(
		ayahId: 5367,
		ayahText: 'وَلَوْ تَقَوَّلَ عَلَيْنَا بَعْضَ الْاَقَاوِيْلِۙ',
		ayahNumber: 44,
		translationId: 'Dan sekiranya dia (Muhammad) mengada-adakan sebagian perkataan atas (nama) Kami, ',
	),
	Ayah(
		ayahId: 5368,
		ayahText: 'لَاَخَذْنَا مِنْهُ بِالْيَمِيْنِۙ',
		ayahNumber: 45,
		translationId: 'pasti Kami pegang dia pada tangan kanannya. ',
	),
	Ayah(
		ayahId: 5369,
		ayahText: 'ثُمَّ لَقَطَعْنَا مِنْهُ الْوَتِيْنَۖ',
		ayahNumber: 46,
		translationId: 'Kemudian Kami potong pembuluh jantungnya. ',
	),
	Ayah(
		ayahId: 5370,
		ayahText: 'فَمَا مِنْكُمْ مِّنْ اَحَدٍ عَنْهُ حَاجِزِيْنَۙ',
		ayahNumber: 47,
		translationId: 'Maka tidak seorang pun dari kamu yang dapat menghalangi (Kami untuk menghukumnya). ',
	),
	Ayah(
		ayahId: 5371,
		ayahText: 'وَاِنَّهٗ لَتَذْكِرَةٌ لِّلْمُتَّقِيْنَ ',
		ayahNumber: 48,
		translationId: "Dan sungguh, (Al-Qur'an) itu pelajaran bagi orang-orang yang bertakwa. ",
	),
	Ayah(
		ayahId: 5372,
		ayahText: 'وَاِنَّا لَنَعْلَمُ اَنَّ مِنْكُمْ مُّكَذِّبِيْنَۗ',
		ayahNumber: 49,
		translationId: 'Dan sungguh, Kami mengetahui bahwa di antara kamu ada orang yang mendustakan.',
	),
	Ayah(
		ayahId: 5373,
		ayahText: 'وَاِنَّهٗ لَحَسْرَةٌ عَلَى الْكٰفِرِيْنَۚ',
		ayahNumber: 50,
		translationId: "Dan sungguh, (Al-Qur'an) itu akan menimbulkan penyesalan bagi orang-orang kafir (di akhirat).",
	),
	Ayah(
		ayahId: 5374,
		ayahText: 'وَاِنَّهٗ لَحَقُّ الْيَقِيْنِ ',
		ayahNumber: 51,
		translationId: "Dan Sungguh, (Al-Qur'an) itu kebenaran yang meyakinkan. ",
	),
	Ayah(
		ayahId: 5375,
		ayahText: 'فَسَبِّحْ بِاسْمِ رَبِّكَ الْعَظِيْمِ ࣖ',
		ayahNumber: 52,
		translationId: 'Maka bertasbihlah dengan (menyebut) nama Tuhanmu Yang Mahaagung. ',
	),
];
