// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah21 = [
	Ayah(
		ayahId: 2484,
		ayahText: 'اِقْتَرَبَ لِلنَّاسِ حِسَابُهُمْ وَهُمْ فِيْ غَفْلَةٍ مُّعْرِضُوْنَ ۚ ',
		ayahNumber: 1,
		translationId: 'Telah semakin dekat kepada manusia perhitungan amal mereka, sedang mereka dalam keadaan lalai (dengan dunia), berpaling (dari akhirat).',
	),
	Ayah(
		ayahId: 2485,
		ayahText: 'مَا يَأْتِيْهِمْ مِّنْ ذِكْرٍ مِّنْ رَّبِّهِمْ مُّحْدَثٍ اِلَّا اسْتَمَعُوْهُ وَهُمْ يَلْعَبُوْنَ ۙ',
		ayahNumber: 2,
		translationId: 'Setiap diturunkan kepada mereka ayat-ayat yang baru dari Tuhan, mereka mendengarkannya sambil bermain-main.',
	),
	Ayah(
		ayahId: 2486,
		ayahText: 'لَاهِيَةً قُلُوْبُهُمْۗ وَاَسَرُّوا النَّجْوَىۖ الَّذِيْنَ ظَلَمُوْاۖ هَلْ هٰذَآ اِلَّا بَشَرٌ مِّثْلُكُمْۚ اَفَتَأْتُوْنَ السِّحْرَ وَاَنْتُمْ تُبْصِرُوْنَ ',
		ayahNumber: 3,
		translationId: 'Hati mereka dalam keadaan lalai. Dan orang-orang yang zalim itu merahasiakan pembicaraan mereka, “(Orang) ini (Muhammad) tidak lain hanyalah seorang manusia (juga) seperti kamu. Apakah kamu menerima sihir itu padahal kamu menyaksikannya?”',
	),
	Ayah(
		ayahId: 2487,
		ayahText: 'قٰلَ رَبِّيْ يَعْلَمُ الْقَوْلَ فِى السَّمَاۤءِ وَالْاَرْضِۖ وَهُوَ السَّمِيْعُ الْعَلِيْمُ ',
		ayahNumber: 4,
		translationId: 'Dia (Muhammad) berkata, “Tuhanku mengetahui (semua) perkataan di langit dan di bumi, dan Dia Maha Mendengar, Maha Mengetahui!”',
	),
	Ayah(
		ayahId: 2488,
		ayahText: 'بَلْ قَالُوْٓا اَضْغَاثُ اَحْلَامٍۢ بَلِ افْتَرٰىهُ بَلْ هُوَ شَاعِرٌۚ فَلْيَأْتِنَا بِاٰيَةٍ كَمَآ اُرْسِلَ الْاَوَّلُوْنَ ',
		ayahNumber: 5,
		translationId: " Bahkan mereka mengatakan, “(Al-Qur'an itu buah) mimpi-mimpi yang kacau, atau hasil rekayasanya (Muhammad), atau bahkan dia hanya seorang penyair, cobalah dia datangkan kepada kita suatu tanda (bukti), seperti halnya rasul-rasul yang diutus terdahulu.”",
	),
	Ayah(
		ayahId: 2489,
		ayahText: 'مَآ اٰمَنَتْ قَبْلَهُمْ مِّنْ قَرْيَةٍ اَهْلَكْنٰهَاۚ اَفَهُمْ يُؤْمِنُوْنَ ',
		ayahNumber: 6,
		translationId: ' Penduduk suatu negeri sebelum mereka, yang telah Kami binasakan, mereka itu tidak beriman (padahal telah Kami kirimkan bukti). Apakah mereka akan beriman?',
	),
	Ayah(
		ayahId: 2490,
		ayahText: 'وَمَآ اَرْسَلْنَا قَبْلَكَ اِلَّا رِجَالًا نُّوْحِيْٓ اِلَيْهِمْ فَسْـَٔلُوْٓا اَهْلَ الذِّكْرِ اِنْ كُنْتُمْ لَا تَعْلَمُوْنَ ',
		ayahNumber: 7,
		translationId: 'Dan Kami tidak mengutus (rasul-rasul) sebelum engkau (Muhammad), melainkan beberapa orang laki-laki yang Kami beri wahyu kepada mereka, maka tanyakanlah kepada orang yang berilmu, jika kamu tidak mengetahui.',
	),
	Ayah(
		ayahId: 2491,
		ayahText: 'وَمَا جَعَلْنٰهُمْ جَسَدًا لَّا يَأْكُلُوْنَ الطَّعَامَ وَمَا كَانُوْا خٰلِدِيْنَ ',
		ayahNumber: 8,
		translationId: 'Dan Kami tidak menjadikan mereka (rasul-rasul) suatu tubuh yang tidak memakan makanan dan mereka tidak (pula) hidup kekal.',
	),
	Ayah(
		ayahId: 2492,
		ayahText: 'ثُمَّ صَدَقْنٰهُمُ الْوَعْدَ فَاَنْجَيْنٰهُمْ وَمَنْ نَّشَاۤءُ وَاَهْلَكْنَا الْمُسْرِفِيْنَ ',
		ayahNumber: 9,
		translationId: 'Kemudian Kami tepati janji (yang telah Kami janjikan) kepada mereka. Maka Kami selamatkan mereka dan orang-orang yang Kami kehendaki, dan Kami binasakan orang-orang yang melampaui batas.',
	),
	Ayah(
		ayahId: 2493,
		ayahText: 'لَقَدْ اَنْزَلْنَآ اِلَيْكُمْ كِتٰبًا فِيْهِ ذِكْرُكُمْۗ اَفَلَا تَعْقِلُوْنَ ࣖ',
		ayahNumber: 10,
		translationId: " Sungguh, telah Kami turunkan kepadamu sebuah Kitab (Al-Qur'an) yang di dalamnya terdapat peringatan bagimu. Maka apakah kamu tidak mengerti?",
	),
	Ayah(
		ayahId: 2494,
		ayahText: 'وَكَمْ قَصَمْنَا مِنْ قَرْيَةٍ كَانَتْ ظَالِمَةً وَّاَنْشَأْنَا بَعْدَهَا قَوْمًا اٰخَرِيْنَ ',
		ayahNumber: 11,
		translationId: ' Dan berapa banyak (penduduk) negeri yang zalim yang telah Kami binasakan, dan Kami jadikan generasi yang lain setelah mereka itu (sebagai penggantinya).',
	),
	Ayah(
		ayahId: 2495,
		ayahText: 'فَلَمَّآ اَحَسُّوْا بَأْسَنَآ اِذَا هُمْ مِّنْهَا يَرْكُضُوْنَ ۗ',
		ayahNumber: 12,
		translationId: ' Maka ketika mereka merasakan azab Kami, tiba-tiba mereka melarikan diri dari (negerinya) itu.',
	),
	Ayah(
		ayahId: 2496,
		ayahText: 'لَا تَرْكُضُوْا وَارْجِعُوْٓا اِلٰى مَآ اُتْرِفْتُمْ فِيْهِ وَمَسٰكِنِكُمْ لَعَلَّكُمْ تُسْـَٔلُوْنَ ',
		ayahNumber: 13,
		translationId: 'Janganlah kamu lari tergesa-gesa; kembalilah kamu kepada kesenangan hidupmu dan tempat-tempat kediamanmu (yang baik), agar kamu dapat ditanya.',
	),
	Ayah(
		ayahId: 2497,
		ayahText: 'قَالُوْا يٰوَيْلَنَآ اِنَّا كُنَّا ظٰلِمِيْنَ ',
		ayahNumber: 14,
		translationId: 'Mereka berkata, “Betapa celaka kami, sungguh, kami orang-orang yang zalim.”',
	),
	Ayah(
		ayahId: 2498,
		ayahText: 'فَمَا زَالَتْ تِّلْكَ دَعْوٰىهُمْ حَتّٰى جَعَلْنٰهُمْ حَصِيْدًا خَامِدِيْنَ ',
		ayahNumber: 15,
		translationId: ' Maka demikianlah keluhan mereka berkepanjangan, sehingga mereka Kami jadikan sebagai tanaman yang telah dituai, yang tidak dapat hidup lagi.',
	),
	Ayah(
		ayahId: 2499,
		ayahText: 'وَمَا خَلَقْنَا السَّمَاۤءَ وَالْاَرْضَ وَمَا بَيْنَهُمَا لٰعِبِيْنَ ',
		ayahNumber: 16,
		translationId: 'Dan Kami tidak menciptakan langit dan bumi dan segala apa yang ada di antara keduanya dengan main-main.',
	),
	Ayah(
		ayahId: 2500,
		ayahText: 'لَوْ اَرَدْنَآ اَنْ نَّتَّخِذَ لَهْوًا لَّاتَّخَذْنٰهُ مِنْ لَّدُنَّآ  ۖاِنْ كُنَّا فٰعِلِيْنَ ',
		ayahNumber: 17,
		translationId: ' Seandainya Kami hendak membuat suatu permainan (istri dan anak), tentulah Kami membuatnya dari sisi Kami, jika Kami benar-benar menghendaki berbuat demikian.',
	),
	Ayah(
		ayahId: 2501,
		ayahText: 'بَلْ نَقْذِفُ بِالْحَقِّ عَلَى الْبَاطِلِ فَيَدْمَغُهٗ فَاِذَا هُوَ زَاهِقٌۗ وَلَكُمُ الْوَيْلُ مِمَّا تَصِفُوْنَ ',
		ayahNumber: 18,
		translationId: 'Sebenarnya Kami melemparkan yang hak (kebenaran) kepada yang batil (tidak benar) lalu yang hak itu menghancurkannya, maka seketika itu (yang batil) lenyap. Dan celaka kamu karena kamu menyifati (Allah dengan sifat-sifat yang tidak pantas bagi-Nya).',
	),
	Ayah(
		ayahId: 2502,
		ayahText: 'وَلَهٗ مَنْ فِى السَّمٰوٰتِ وَالْاَرْضِۗ وَمَنْ عِنْدَهٗ لَا يَسْتَكْبِرُوْنَ عَنْ عِبَادَتِهٖ وَلَا يَسْتَحْسِرُوْنَ ۚ',
		ayahNumber: 19,
		translationId: 'Dan milik-Nya siapa yang di langit dan di bumi. Dan (malaikat-malaikat) yang di sisi-Nya, tidak mempunyai rasa angkuh untuk menyembah-Nya dan tidak (pula) merasa letih.',
	),
	Ayah(
		ayahId: 2503,
		ayahText: 'يُسَبِّحُوْنَ الَّيْلَ وَالنَّهَارَ لَا يَفْتُرُوْنَ ',
		ayahNumber: 20,
		translationId: 'Mereka (malaikat-malaikat) bertasbih tidak henti-hentinya malam dan siang.',
	),
	Ayah(
		ayahId: 2504,
		ayahText: 'اَمِ اتَّخَذُوْٓا اٰلِهَةً مِّنَ الْاَرْضِ هُمْ يُنْشِرُوْنَ ',
		ayahNumber: 21,
		translationId: 'Apakah mereka mengambil tuhan-tuhan dari bumi, yang dapat menghidupkan (orang-orang yang mati)?',
	),
	Ayah(
		ayahId: 2505,
		ayahText: 'لَوْ كَانَ فِيْهِمَآ اٰلِهَةٌ اِلَّا اللّٰهُ لَفَسَدَتَاۚ فَسُبْحٰنَ اللّٰهِ رَبِّ الْعَرْشِ عَمَّا يَصِفُوْنَ ',
		ayahNumber: 22,
		translationId: 'Seandainya pada keduanya (di langit dan di bumi) ada tuhan-tuhan selain Allah, tentu keduanya telah binasa. Mahasuci Allah yang memiliki ‘Arsy, dari apa yang mereka sifatkan.',
	),
	Ayah(
		ayahId: 2506,
		ayahText: 'لَا يُسْـَٔلُ عَمَّا يَفْعَلُ وَهُمْ يُسْـَٔلُوْنَ ',
		ayahNumber: 23,
		translationId: 'Dia (Allah) tidak ditanya tentang apa yang dikerjakan, tetapi merekalah yang akan ditanya.',
	),
	Ayah(
		ayahId: 2507,
		ayahText: 'اَمِ اتَّخَذُوْا مِنْ دُوْنِهٖٓ اٰلِهَةً ۗقُلْ هَاتُوْا بُرْهَانَكُمْۚ هٰذَا ذِكْرُ مَنْ مَّعِيَ وَذِكْرُ مَنْ قَبْلِيْۗ بَلْ اَكْثَرُهُمْ لَا يَعْلَمُوْنَۙ الْحَقَّ فَهُمْ مُّعْرِضُوْنَ ',
		ayahNumber: 24,
		translationId: "Atau apakah mereka mengambil tuhan-tuhan selain Dia? Katakanlah (Muhammad), “Kemukakanlah alasan-alasanmu! (Al-Qur'an) ini adalah peringatan bagi orang yang bersamaku, dan peringatan bagi orang sebelumku.” Tetapi kebanyakan mereka tidak mengetahui yang hak (kebenaran), karena itu mereka berpaling.",
	),
	Ayah(
		ayahId: 2508,
		ayahText: 'وَمَآ اَرْسَلْنَا مِنْ قَبْلِكَ مِنْ رَّسُوْلٍ اِلَّا نُوْحِيْٓ اِلَيْهِ اَنَّهٗ لَآ اِلٰهَ اِلَّآ اَنَا۠ فَاعْبُدُوْنِ ',
		ayahNumber: 25,
		translationId: 'Dan Kami tidak mengutus seorang rasul pun sebelum engkau (Muhammad), melainkan Kami wahyukan kepadanya, bahwa tidak ada tuhan (yang berhak disembah) selain Aku, maka sembahlah Aku.',
	),
	Ayah(
		ayahId: 2509,
		ayahText: 'وَقَالُوا اتَّخَذَ الرَّحْمٰنُ وَلَدًا سُبْحٰنَهٗ ۗبَلْ عِبَادٌ مُّكْرَمُوْنَ ۙ',
		ayahNumber: 26,
		translationId: 'Dan mereka berkata, “Tuhan Yang Maha Pengasih telah menjadikan (malaikat) sebagai anak.” Mahasuci Dia. Sebenarnya mereka (para malaikat itu) adalah hamba-hamba yang dimuliakan,',
	),
	Ayah(
		ayahId: 2510,
		ayahText: 'لَا يَسْبِقُوْنَهٗ بِالْقَوْلِ وَهُمْ بِاَمْرِهٖ يَعْمَلُوْنَ ',
		ayahNumber: 27,
		translationId: 'mereka tidak berbicara mendahului-Nya dan mereka mengerjakan perintah-perintah-Nya.',
	),
	Ayah(
		ayahId: 2511,
		ayahText: 'يَعْلَمُ مَا بَيْنَ اَيْدِيْهِمْ وَمَا خَلْفَهُمْ وَلَا يَشْفَعُوْنَۙ اِلَّا لِمَنِ ارْتَضٰى وَهُمْ مِّنْ خَشْيَتِهٖ مُشْفِقُوْنَ ',
		ayahNumber: 28,
		translationId: 'Dia (Allah) mengetahui segala sesuatu yang di hadapan mereka (malaikat) dan yang di belakang mereka, dan mereka tidak memberi syafaat melainkan kepada orang yang diridai (Allah), dan mereka selalu berhati-hati karena takut kepada-Nya.',
	),
	Ayah(
		ayahId: 2512,
		ayahText: '۞ وَمَنْ يَّقُلْ مِنْهُمْ اِنِّيْٓ اِلٰهٌ مِّنْ دُوْنِهٖ فَذٰلِكَ نَجْزِيْهِ جَهَنَّمَۗ  كَذٰلِكَ نَجْزِى الظّٰلِمِيْنَ ࣖ',
		ayahNumber: 29,
		translationId: 'Dan barangsiapa di antara mereka berkata, “Sungguh, aku adalah tuhan selain Allah,” maka orang itu Kami beri balasan dengan Jahanam. Demikianlah Kami memberikan balasan kepada orang-orang yang zalim.',
	),
	Ayah(
		ayahId: 2513,
		ayahText: 'اَوَلَمْ يَرَ الَّذِيْنَ كَفَرُوْٓا اَنَّ السَّمٰوٰتِ وَالْاَرْضَ كَانَتَا رَتْقًا فَفَتَقْنٰهُمَاۗ وَجَعَلْنَا مِنَ الْمَاۤءِ كُلَّ شَيْءٍ حَيٍّۗ  اَفَلَا يُؤْمِنُوْنَ ',
		ayahNumber: 30,
		translationId: 'Dan apakah orang-orang kafir tidak mengetahui bahwa langit dan bumi keduanya dahulunya menyatu, kemudian Kami pisahkan antara keduanya; dan Kami jadikan segala sesuatu yang hidup berasal dari air; maka mengapa mereka tidak beriman?',
	),
	Ayah(
		ayahId: 2514,
		ayahText: 'وَجَعَلْنَا فِى الْاَرْضِ رَوَاسِيَ اَنْ تَمِيْدَ بِهِمْۖ وَجَعَلْنَا فِيْهَا فِجَاجًا سُبُلًا لَّعَلَّهُمْ يَهْتَدُوْنَ ',
		ayahNumber: 31,
		translationId: 'Dan Kami telah menjadikan di bumi ini gunung-gunung yang kokoh agar ia (tidak) guncang bersama mereka, dan Kami jadikan (pula) di sana jalan-jalan yang luas, agar mereka mendapat petunjuk.',
	),
	Ayah(
		ayahId: 2515,
		ayahText: 'وَجَعَلْنَا السَّمَاۤءَ سَقْفًا مَّحْفُوْظًاۚ وَهُمْ عَنْ اٰيٰتِهَا مُعْرِضُوْنَ ',
		ayahNumber: 32,
		translationId: 'Dan Kami menjadikan langit sebagai atap yang terpelihara, namun mereka tetap berpaling dari tanda-tanda (kebesaran Allah) itu (matahari, bulan, angin, awan, dan lain-lain).',
	),
	Ayah(
		ayahId: 2516,
		ayahText: 'وَهُوَ الَّذِيْ خَلَقَ الَّيْلَ وَالنَّهَارَ وَالشَّمْسَ وَالْقَمَرَۗ  كُلٌّ فِيْ فَلَكٍ يَّسْبَحُوْنَ ',
		ayahNumber: 33,
		translationId: 'Dan Dialah yang telah menciptakan malam dan siang, matahari dan bulan. Masing-masing beredar pada garis edarnya.',
	),
	Ayah(
		ayahId: 2517,
		ayahText: 'وَمَا جَعَلْنَا لِبَشَرٍ مِّنْ قَبْلِكَ الْخُلْدَۗ اَفَا۟ىِٕنْ مِّتَّ فَهُمُ الْخٰلِدُوْنَ ',
		ayahNumber: 34,
		translationId: 'Dan Kami tidak menjadikan hidup abadi bagi seorang manusia sebelum engkau (Muhammad); maka jika engkau wafat, apakah mereka akan kekal?',
	),
	Ayah(
		ayahId: 2518,
		ayahText: 'كُلُّ نَفْسٍ ذَاۤىِٕقَةُ الْمَوْتِۗ وَنَبْلُوْكُمْ بِالشَّرِّ وَالْخَيْرِ فِتْنَةً ۗوَاِلَيْنَا تُرْجَعُوْنَ ',
		ayahNumber: 35,
		translationId: 'Setiap yang bernyawa akan merasakan mati. Kami akan menguji kamu dengan keburukan dan kebaikan sebagai cobaan. Dan kamu akan dikembalikan hanya kepada Kami.',
	),
	Ayah(
		ayahId: 2519,
		ayahText: 'وَاِذَا رَاٰكَ الَّذِيْنَ كَفَرُوْٓا اِنْ يَّتَّخِذُوْنَكَ اِلَّا هُزُوًاۗ اَهٰذَا الَّذِيْ يَذْكُرُ اٰلِهَتَكُمْۚ وَهُمْ بِذِكْرِ الرَّحْمٰنِ هُمْ كٰفِرُوْنَ  ',
		ayahNumber: 36,
		translationId: 'Dan apabila orang-orang kafir itu melihat engkau (Muhammad), mereka hanya memperlakukan engkau menjadi bahan ejekan. (Mereka mengatakan), “Apakah ini orang yang mencela tuhan-tuhanmu?” Padahal mereka orang yang ingkar mengingat Allah Yang Maha Pengasih.',
	),
	Ayah(
		ayahId: 2520,
		ayahText: 'خُلِقَ الْاِنْسَانُ مِنْ عَجَلٍۗ سَاُورِيْكُمْ اٰيٰتِيْ فَلَا تَسْتَعْجِلُوْنِ ',
		ayahNumber: 37,
		translationId: 'Manusia diciptakan (bersifat) tergesa-gesa. Kelak akan Aku perlihatkan kepadamu tanda-tanda (kekuasaan)-Ku. Maka janganlah kamu meminta Aku menyegerakannya.',
	),
	Ayah(
		ayahId: 2521,
		ayahText: 'وَيَقُوْلُوْنَ مَتٰى هٰذَا الْوَعْدُ اِنْ كُنْتُمْ صٰدِقِيْنَ ',
		ayahNumber: 38,
		translationId: 'Dan mereka berkata, “Kapankah janji itu (akan datang), jika kamu orang yang benar?”',
	),
	Ayah(
		ayahId: 2522,
		ayahText: 'لَوْ يَعْلَمُ الَّذِيْنَ كَفَرُوْا حِيْنَ لَا يَكُفُّوْنَ عَنْ وُّجُوْهِهِمُ النَّارَ وَلَا عَنْ ظُهُوْرِهِمْ وَلَا هُمْ يُنْصَرُوْنَ ',
		ayahNumber: 39,
		translationId: 'Seandainya orang kafir itu mengetahui, ketika mereka itu tidak mampu mengelakkan api neraka dari wajah dan punggung mereka, sedang mereka tidak mendapat pertolongan (tentulah mereka tidak meminta disegerakan).',
	),
	Ayah(
		ayahId: 2523,
		ayahText: 'بَلْ تَأْتِيْهِمْ بَغْتَةً فَتَبْهَتُهُمْ فَلَا يَسْتَطِيْعُوْنَ رَدَّهَا وَلَا هُمْ يُنْظَرُوْنَ ',
		ayahNumber: 40,
		translationId: ' Sebenarnya (hari Kiamat) itu akan datang kepada mereka secara tiba-tiba, lalu mereka menjadi panik; maka mereka tidak sanggup menolaknya dan tidak (pula) diberi penangguhan (waktu).',
	),
	Ayah(
		ayahId: 2524,
		ayahText: 'وَلَقَدِ اسْتُهْزِئَ بِرُسُلٍ مِّنْ قَبْلِكَ فَحَاقَ بِالَّذِيْنَ سَخِرُوْا مِنْهُمْ مَّا كَانُوْا بِهٖ يَسْتَهْزِءُوْنَ ࣖ',
		ayahNumber: 41,
		translationId: 'Dan sungguh, rasul-rasul sebelum engkau (Muhammad) pun telah diperolok-olokkan, maka turunlah (siksaan) kepada orang-orang yang mencemoohkan apa (rasul-rasul) yang selalu mereka perolok-olokkan.',
	),
	Ayah(
		ayahId: 2525,
		ayahText: 'قُلْ مَنْ يَّكْلَؤُكُمْ بِالَّيْلِ وَالنَّهَارِ مِنَ الرَّحْمٰنِۗ  بَلْ هُمْ عَنْ ذِكْرِ رَبِّهِمْ مُّعْرِضُوْنَ ',
		ayahNumber: 42,
		translationId: 'Katakanlah, “Siapakah yang akan menjaga kamu pada waktu malam dan siang dari (siksaan) Allah Yang Maha Pengasih?” Tetapi mereka enggan mengingat Tuhan mereka.',
	),
	Ayah(
		ayahId: 2526,
		ayahText: 'اَمْ لَهُمْ اٰلِهَةٌ تَمْنَعُهُمْ مِّنْ دُوْنِنَاۗ  لَا يَسْتَطِيْعُوْنَ نَصْرَ اَنْفُسِهِمْ وَلَا هُمْ مِّنَّا يُصْحَبُوْنَ',
		ayahNumber: 43,
		translationId: 'Ataukah mereka mempunyai tuhan-tuhan yang dapat memelihara mereka dari (azab) Kami? Tuhan-tuhan mereka itu tidak sanggup menolong diri mereka sendiri dan tidak (pula) mereka dilindungi dari (azab) Kami.',
	),
	Ayah(
		ayahId: 2527,
		ayahText: 'بَلْ مَتَّعْنَا هٰٓؤُلَاۤءِ وَاٰبَاۤءَهُمْ حَتّٰى طَالَ عَلَيْهِمُ الْعُمُرُۗ اَفَلَا يَرَوْنَ اَنَّا نَأْتِى الْاَرْضَ نَنْقُصُهَا مِنْ اَطْرَافِهَاۗ اَفَهُمُ الْغٰلِبُوْنَ ',
		ayahNumber: 44,
		translationId: 'Sebenarnya Kami telah memberi mereka dan nenek moyang mereka kenikmatan (hidup di dunia) hingga panjang usia mereka. Maka apakah mereka tidak melihat bahwa Kami mendatangi negeri (yang berada di bawah kekuasaan orang kafir), lalu Kami kurangi luasnya dari ujung-ujung negeri. Apakah mereka yang menang?',
	),
	Ayah(
		ayahId: 2528,
		ayahText: 'قُلْ اِنَّمَآ اُنْذِرُكُمْ بِالْوَحْيِۖ وَلَا يَسْمَعُ الصُّمُّ الدُّعَاۤءَ اِذَا مَا يُنْذَرُوْنَ ',
		ayahNumber: 45,
		translationId: 'Katakanlah (Muhammad), “Sesungguhnya aku hanya memberimu peringatan sesuai dengan wahyu.” Tetapi orang tuli tidak mendengar seruan apabila mereka diberi peringatan.',
	),
	Ayah(
		ayahId: 2529,
		ayahText: 'وَلَىِٕنْ مَّسَّتْهُمْ نَفْحَةٌ مِّنْ عَذَابِ رَبِّكَ لَيَقُوْلُنَّ يٰوَيْلَنَآ اِنَّا كُنَّا ظٰلِمِيْنَ ',
		ayahNumber: 46,
		translationId: 'Dan jika mereka ditimpa sedikit saja azab Tuhanmu, pastilah mereka berkata, “Celakalah kami! Sesungguhnya kami termasuk orang yang selalu menzalimi (diri sendiri).”',
	),
	Ayah(
		ayahId: 2530,
		ayahText: 'وَنَضَعُ الْمَوَازِيْنَ الْقِسْطَ لِيَوْمِ الْقِيٰمَةِ فَلَا تُظْلَمُ نَفْسٌ شَيْـًٔاۗ وَاِنْ كَانَ مِثْقَالَ حَبَّةٍ مِّنْ خَرْدَلٍ اَتَيْنَا بِهَاۗ وَكَفٰى بِنَا حَاسِبِيْنَ ',
		ayahNumber: 47,
		translationId: 'Dan Kami akan memasang timbangan yang tepat pada hari Kiamat, maka tidak seorang pun dirugikan walau sedikit; sekalipun hanya seberat biji sawi, pasti Kami mendatangkannya (pahala). Dan cukuplah Kami yang membuat perhitungan.',
	),
	Ayah(
		ayahId: 2531,
		ayahText: 'وَلَقَدْ اٰتَيْنَا مُوْسٰى وَهٰرُوْنَ الْفُرْقَانَ وَضِيَاۤءً وَّذِكْرًا لِّلْمُتَّقِيْنَ ۙ',
		ayahNumber: 48,
		translationId: 'Dan sungguh, Kami telah memberikan kepada Musa dan Harun, Furqan (Kitab Taurat) dan penerangan serta pelajaran bagi orang-orang yang bertakwa.',
	),
	Ayah(
		ayahId: 2532,
		ayahText: 'الَّذِيْنَ يَخْشَوْنَ رَبَّهُمْ بِالْغَيْبِ وَهُمْ مِّنَ السَّاعَةِ مُشْفِقُوْنَ ',
		ayahNumber: 49,
		translationId: '(Yaitu) orang-orang yang takut (azab) Tuhannya, sekalipun mereka tidak melihat-Nya, dan mereka merasa takut akan (tibanya) hari Kiamat.',
	),
	Ayah(
		ayahId: 2533,
		ayahText: 'وَهٰذَا ذِكْرٌ مُّبٰرَكٌ اَنْزَلْنٰهُۗ اَفَاَنْتُمْ لَهٗ مُنْكِرُوْنَ ࣖ',
		ayahNumber: 50,
		translationId: "Dan ini (Al-Qur'an) adalah suatu peringatan yang mempunyai berkah yang telah Kami turunkan. Maka apakah kamu mengingkarinya?",
	),
	Ayah(
		ayahId: 2534,
		ayahText: '۞ وَلَقَدْ اٰتَيْنَآ اِبْرٰهِيْمَ رُشْدَهٗ مِنْ قَبْلُ وَكُنَّا بِهٖ عٰلِمِيْنَ ',
		ayahNumber: 51,
		translationId: 'Dan sungguh, sebelum dia (Musa dan Harun) telah Kami berikan kepada Ibrahim petunjuk, dan Kami telah mengetahui dia.',
	),
	Ayah(
		ayahId: 2535,
		ayahText: 'اِذْ قَالَ لِاَبِيْهِ وَقَوْمِهٖ مَا هٰذِهِ التَّمَاثِيْلُ الَّتِيْٓ اَنْتُمْ لَهَا عَاكِفُوْنَ ',
		ayahNumber: 52,
		translationId: '(Ingatlah), ketika dia (Ibrahim) berkata kepada ayahnya dan kaumnya, “Patung-patung apakah ini yang kamu tekun menyembahnya?”',
	),
	Ayah(
		ayahId: 2536,
		ayahText: 'قَالُوْا وَجَدْنَآ اٰبَاۤءَنَا لَهَا عٰبِدِيْنَ ',
		ayahNumber: 53,
		translationId: 'Mereka menjawab, “Kami mendapati nenek moyang kami menyembahnya.”',
	),
	Ayah(
		ayahId: 2537,
		ayahText: 'قَالَ لَقَدْ كُنْتُمْ اَنْتُمْ وَاٰبَاۤؤُكُمْ فِيْ ضَلٰلٍ مُّبِيْنٍ ',
		ayahNumber: 54,
		translationId: 'Dia (Ibrahim) berkata, “Sesungguhnya kamu dan nenek moyang kamu berada dalam kesesatan yang nyata.”',
	),
	Ayah(
		ayahId: 2538,
		ayahText: 'قَالُوْٓا اَجِئْتَنَا بِالْحَقِّ اَمْ اَنْتَ مِنَ اللّٰعِبِيْنَ ',
		ayahNumber: 55,
		translationId: 'Mereka berkata, “Apakah engkau da-tang kepada kami membawa kebenaran atau engkau main-main?”',
	),
	Ayah(
		ayahId: 2539,
		ayahText: 'قَالَ بَلْ رَّبُّكُمْ رَبُّ السَّمٰوٰتِ وَالْاَرْضِ الَّذِيْ فَطَرَهُنَّۖ وَاَنَا۠ عَلٰى ذٰلِكُمْ مِّنَ الشّٰهِدِيْنَ ',
		ayahNumber: 56,
		translationId: 'Dia (Ibrahim) menjawab, “Sebenarnya Tuhan kamu ialah Tuhan (pemilik) langit dan bumi; (Dialah) yang telah menciptakannya; dan aku termasuk orang yang dapat bersaksi atas itu.”',
	),
	Ayah(
		ayahId: 2540,
		ayahText: 'وَتَاللّٰهِ لَاَكِيْدَنَّ اَصْنَامَكُمْ بَعْدَ اَنْ تُوَلُّوْا مُدْبِرِيْنَ ',
		ayahNumber: 57,
		translationId: 'Dan demi Allah, sungguh, aku akan melakukan tipu daya terhadap berhala-berhalamu setelah kamu pergi meninggalkannya.',
	),
	Ayah(
		ayahId: 2541,
		ayahText: 'فَجَعَلَهُمْ جُذَاذًا اِلَّا كَبِيْرًا لَّهُمْ لَعَلَّهُمْ اِلَيْهِ يَرْجِعُوْنَ ',
		ayahNumber: 58,
		translationId: 'Maka dia (Ibrahim) menghancurkan (berhala-berhala itu) berkeping-keping, kecuali yang terbesar (induknya); agar mereka kembali (untuk bertanya) kepadanya.',
	),
	Ayah(
		ayahId: 2542,
		ayahText: 'قَالُوْا مَنْ فَعَلَ هٰذَا بِاٰلِهَتِنَآ اِنَّهٗ لَمِنَ الظّٰلِمِيْنَ ',
		ayahNumber: 59,
		translationId: 'Mereka berkata, “Siapakah yang melakukan (perbuatan) ini terhadap tuhan-tuhan kami? Sungguh, dia termasuk orang yang zalim.”',
	),
	Ayah(
		ayahId: 2543,
		ayahText: 'قَالُوْا سَمِعْنَا فَتًى يَّذْكُرُهُمْ يُقَالُ لَهٗٓ اِبْرٰهِيْمُ ۗ',
		ayahNumber: 60,
		translationId: 'Mereka (yang lain) berkata, “Kami mendengar ada seorang pemuda yang mencela (berhala-berhala ini), namanya Ibrahim.”',
	),
	Ayah(
		ayahId: 2544,
		ayahText: 'قَالُوْا فَأْتُوْا بِهٖ عَلٰٓى اَعْيُنِ النَّاسِ لَعَلَّهُمْ يَشْهَدُوْنَ ',
		ayahNumber: 61,
		translationId: 'Mereka berkata, “(Kalau demikian) bawalah dia dengan diperlihatkan kepada orang banyak, agar mereka menyaksikan.”',
	),
	Ayah(
		ayahId: 2545,
		ayahText: 'قَالُوْٓا ءَاَنْتَ فَعَلْتَ هٰذَا بِاٰلِهَتِنَا يٰٓاِبْرٰهِيْمُ ۗ',
		ayahNumber: 62,
		translationId: ' Mereka bertanya, “Apakah engkau yang melakukan (perbuatan) ini terhadap tuhan-tuhan kami, wahai Ibrahim?”',
	),
	Ayah(
		ayahId: 2546,
		ayahText: 'قَالَ بَلْ فَعَلَهٗ كَبِيْرُهُمْ هٰذَا فَسْـَٔلُوْهُمْ اِنْ كَانُوْا يَنْطِقُوْنَ ',
		ayahNumber: 63,
		translationId: 'Dia (Ibrahim) menjawab, “Sebenarnya (patung) besar itu yang melakukannya, maka tanyakanlah kepada mereka, jika mereka dapat berbicara.”',
	),
	Ayah(
		ayahId: 2547,
		ayahText: 'فَرَجَعُوْٓا اِلٰٓى اَنْفُسِهِمْ فَقَالُوْٓا اِنَّكُمْ اَنْتُمُ الظّٰلِمُوْنَ ۙ',
		ayahNumber: 64,
		translationId: 'Maka mereka kembali kepada kesadaran mereka dan berkata, “Sesungguhnya kamulah yang menzalimi (diri sendiri).”',
	),
	Ayah(
		ayahId: 2548,
		ayahText: 'ثُمَّ نُكِسُوْا عَلٰى رُءُوْسِهِمْۚ  لَقَدْ عَلِمْتَ مَا هٰٓؤُلَاۤءِ يَنْطِقُوْنَ ',
		ayahNumber: 65,
		translationId: 'Kemudian mereka menundukkan kepala (lalu berkata), “Engkau (Ibrahim) pasti tahu bahwa (berhala-berhala) itu tidak dapat berbicara.”',
	),
	Ayah(
		ayahId: 2549,
		ayahText: 'قَالَ اَفَتَعْبُدُوْنَ مِنْ دُوْنِ اللّٰهِ مَا لَا يَنْفَعُكُمْ شَيْـًٔا وَّلَا يَضُرُّكُمْ ۗ',
		ayahNumber: 66,
		translationId: 'Dia (Ibrahim) berkata, “Mengapa kamu menyembah selain Allah, sesuatu yang tidak dapat memberi manfaat sedikit pun, dan tidak (pula) mendatangkan mudarat kepada kamu?',
	),
	Ayah(
		ayahId: 2550,
		ayahText: 'اُفٍّ لَّكُمْ وَلِمَا تَعْبُدُوْنَ مِنْ دُوْنِ اللّٰهِ ۗاَفَلَا تَعْقِلُوْنَ ',
		ayahNumber: 67,
		translationId: 'Celakalah kamu dan apa yang kamu sembah selain Allah! Tidakkah kamu mengerti?”',
	),
	Ayah(
		ayahId: 2551,
		ayahText: 'قَالُوْا حَرِّقُوْهُ وَانْصُرُوْٓا اٰلِهَتَكُمْ اِنْ كُنْتُمْ فٰعِلِيْنَ ',
		ayahNumber: 68,
		translationId: ' Mereka berkata, “Bakarlah dia dan bantulah tuhan-tuhan kamu, jika kamu benar-benar hendak berbuat.”',
	),
	Ayah(
		ayahId: 2552,
		ayahText: 'قُلْنَا يَا نَارُ كُوْنِيْ بَرْدًا وَّسَلٰمًا عَلٰٓى اِبْرٰهِيْمَ ۙ',
		ayahNumber: 69,
		translationId: 'Kami (Allah) berfirman, “Wahai api! Jadilah kamu dingin, dan penyelamat bagi Ibrahim!”',
	),
	Ayah(
		ayahId: 2553,
		ayahText: 'وَاَرَادُوْا بِهٖ كَيْدًا فَجَعَلْنٰهُمُ الْاَخْسَرِيْنَ ۚ',
		ayahNumber: 70,
		translationId: 'Dan mereka hendak berbuat jahat terhadap Ibrahim, maka Kami menjadikan mereka itu orang-orang yang paling rugi.',
	),
	Ayah(
		ayahId: 2554,
		ayahText: 'وَنَجَّيْنٰهُ وَلُوْطًا اِلَى الْاَرْضِ الَّتِيْ بٰرَكْناَ فِيْهَا لِلْعٰلَمِيْنَ ',
		ayahNumber: 71,
		translationId: 'Dan Kami selamatkan dia (Ibrahim) dan Lut ke sebuah negeri yang telah Kami berkahi untuk seluruh alam.',
	),
	Ayah(
		ayahId: 2555,
		ayahText: 'وَوَهَبْنَا لَهٗٓ اِسْحٰقَ وَيَعْقُوْبَ نَافِلَةً ۗوَكُلًّا جَعَلْنَا صٰلِحِيْنَ ',
		ayahNumber: 72,
		translationId: 'Dan Kami menganugerahkan kepadanya (Ibrahim) Ishak dan Yakub, sebagai suatu anugerah. Dan masing-masing Kami jadikan orang yang saleh.',
	),
	Ayah(
		ayahId: 2556,
		ayahText: 'وَجَعَلْنٰهُمْ اَىِٕمَّةً يَّهْدُوْنَ بِاَمْرِنَا وَاَوْحَيْنَآ اِلَيْهِمْ فِعْلَ الْخَيْرٰتِ وَاِقَامَ الصَّلٰوةِ وَاِيْتَاۤءَ الزَّكٰوةِۚ وَكَانُوْا لَنَا عٰبِدِيْنَ ۙ',
		ayahNumber: 73,
		translationId: 'Dan Kami menjadikan mereka itu sebagai pemimpin-pemimpin yang memberi petunjuk dengan perintah Kami dan Kami wahyukan kepada mereka agar berbuat kebaikan, melaksanakan salat dan menunaikan zakat, dan hanya kepada Kami mereka menyembah.',
	),
	Ayah(
		ayahId: 2557,
		ayahText: 'وَلُوْطًا اٰتَيْنٰهُ حُكْمًا وَّعِلْمًا وَّنَجَّيْنٰهُ مِنَ الْقَرْيَةِ الَّتِيْ كَانَتْ تَّعْمَلُ الْخَبٰۤىِٕثَ ۗاِنَّهُمْ كَانُوْا قَوْمَ سَوْءٍ فٰسِقِيْنَۙ',
		ayahNumber: 74,
		translationId: 'Kepada Lut, Kami berikan hikmah dan ilmu, dan Kami selamatkan dia dari (azab yang telah menimpa penduduk) kota yang melakukan perbuatan keji. Sungguh, mereka orang-orang yang jahat lagi fasik.  ',
	),
	Ayah(
		ayahId: 2558,
		ayahText: 'وَاَدْخَلْنٰهُ فِيْ رَحْمَتِنَاۗ اِنَّهٗ مِنَ الصّٰلِحِيْنَ ࣖ ',
		ayahNumber: 75,
		translationId: ' Dan Kami masukkan dia ke dalam rahmat Kami; sesungguhnya dia termasuk golongan orang yang saleh.',
	),
	Ayah(
		ayahId: 2559,
		ayahText: 'وَنُوْحًا اِذْ نَادٰى مِنْ قَبْلُ فَاسْتَجَبْنَا لَهٗ فَنَجَّيْنٰهُ وَاَهْلَهٗ مِنَ الْكَرْبِ الْعَظِيْمِ ۚ',
		ayahNumber: 76,
		translationId: 'Dan (ingatlah kisah) Nuh, sebelum itu, ketika dia berdoa. Kami perkenankan (doa)nya, lalu Kami selamatkan dia bersama pengikutnya dari bencana yang besar.',
	),
	Ayah(
		ayahId: 2560,
		ayahText: 'وَنَصَرْنٰهُ مِنَ الْقَوْمِ الَّذِيْنَ كَذَّبُوْا بِاٰيٰتِنَاۗ اِنَّهُمْ كَانُوْا قَوْمَ سَوْءٍ فَاَغْرَقْنٰهُمْ اَجْمَعِيْنَ ',
		ayahNumber: 77,
		translationId: ' Dan Kami menolongnya dari orang-orang yang telah mendustakan ayat-ayat Kami. Sesungguhnya mereka adalah orang-orang yang jahat, maka Kami tenggelamkan mereka semuanya.',
	),
	Ayah(
		ayahId: 2561,
		ayahText: 'وَدَاوٗدَ وَسُلَيْمٰنَ اِذْ يَحْكُمٰنِ فِى الْحَرْثِ اِذْ نَفَشَتْ فِيْهِ غَنَمُ الْقَوْمِۚ وَكُنَّا لِحُكْمِهِمْ شٰهِدِيْنَ ۖ',
		ayahNumber: 78,
		translationId: ' Dan (ingatlah kisah) Dawud dan Sulaiman, ketika keduanya memberikan keputusan mengenai ladang, karena (ladang itu) dirusak oleh kambing-kambing milik kaumnya. Dan Kami menyaksikan keputusan (yang diberikan) oleh mereka itu.',
	),
	Ayah(
		ayahId: 2562,
		ayahText: 'فَفَهَّمْنٰهَا سُلَيْمٰنَۚ وَكُلًّا اٰتَيْنَا حُكْمًا وَّعِلْمًاۖ وَّسَخَّرْنَا مَعَ دَاوٗدَ الْجِبَالَ يُسَبِّحْنَ وَالطَّيْرَۗ وَكُنَّا فٰعِلِيْنَ',
		ayahNumber: 79,
		translationId: ' Dan Kami memberikan pengertian kepada Sulaiman (tentang hukum yang lebih tepat); dan kepada masing-masing Kami berikan hikmah dan ilmu, dan Kami tundukkan gunung-gunung dan burung-burung, semua bertasbih bersama Dawud. Dan Kamilah yang melakukannya.',
	),
	Ayah(
		ayahId: 2563,
		ayahText: 'وَعَلَّمْنٰهُ صَنْعَةَ لَبُوْسٍ لَّكُمْ لِتُحْصِنَكُمْ مِّنْۢ بَأْسِكُمْۚ فَهَلْ اَنْتُمْ شَاكِرُوْنَ',
		ayahNumber: 80,
		translationId: 'Dan Kami ajarkan (pula) kepada Dawud cara membuat baju besi untukmu, guna melindungi kamu dalam peperangan. Apakah kamu bersyukur (kepada Allah)?',
	),
	Ayah(
		ayahId: 2564,
		ayahText: 'وَلِسُلَيْمٰنَ الرِّيْحَ عَاصِفَةً تَجْرِيْ بِاَمْرِهٖٓ اِلَى الْاَرْضِ الَّتِيْ بٰرَكْنَا فِيْهَاۗ وَكُنَّا بِكُلِّ شَيْءٍ عٰلِمِيْنَ',
		ayahNumber: 81,
		translationId: 'Dan (Kami tundukkan) untuk Sulaiman angin yang sangat kencang tiupannya yang berhembus dengan perintahnya ke negeri yang Kami beri berkah padanya. Dan Kami Maha Mengetahui segala sesuatu.',
	),
	Ayah(
		ayahId: 2565,
		ayahText: 'وَمِنَ الشَّيٰطِيْنِ مَنْ يَّغُوْصُوْنَ لَهٗ وَيَعْمَلُوْنَ عَمَلًا دُوْنَ ذٰلِكَۚ وَكُنَّا لَهُمْ حٰفِظِيْنَ ۙ',
		ayahNumber: 82,
		translationId: 'Dan (Kami tundukkan pula kepada Sulaiman) segolongan setan-setan yang menyelam (ke dalam laut) untuknya dan mereka mengerjakan pekerjaan selain  itu; dan  Kami yang memelihara mereka itu.',
	),
	Ayah(
		ayahId: 2566,
		ayahText: '۞ وَاَيُّوْبَ اِذْ نَادٰى رَبَّهٗٓ اَنِّيْ مَسَّنِيَ الضُّرُّ وَاَنْتَ اَرْحَمُ الرَّاحِمِيْنَ ۚ',
		ayahNumber: 83,
		translationId: 'Dan (ingatlah kisah) Ayub, ketika dia berdoa kepada Tuhannya, “(Ya Tuhanku), sungguh, aku telah ditimpa penyakit, padahal Engkau Tuhan Yang Maha Penyayang dari semua yang penyayang.”',
	),
	Ayah(
		ayahId: 2567,
		ayahText: 'فَاسْتَجَبْنَا لَهٗ فَكَشَفْنَا مَا بِهٖ مِنْ ضُرٍّ وَّاٰتَيْنٰهُ اَهْلَهٗ وَمِثْلَهُمْ مَّعَهُمْ رَحْمَةً مِّنْ عِنْدِنَا وَذِكْرٰى لِلْعٰبِدِيْنَ ۚ',
		ayahNumber: 84,
		translationId: 'Maka Kami kabulkan (doa)nya, lalu Kami lenyapkan penyakit yang ada padanya dan Kami kembalikan keluarganya kepadanya, dan (Kami lipat gandakan jumlah mereka) sebagai suatu rahmat dari Kami, dan untuk menjadi peringatan bagi semua yang menyembah Kami.',
	),
	Ayah(
		ayahId: 2568,
		ayahText: 'وَاِسْمٰعِيْلَ وَاِدْرِيْسَ وَذَا الْكِفْلِۗ  كُلٌّ مِّنَ الصّٰبِرِيْنَ ۙ',
		ayahNumber: 85,
		translationId: ' Dan (ingatlah kisah) Ismail, Idris dan Zulkifli. Mereka semua termasuk orang-orang yang sabar.',
	),
	Ayah(
		ayahId: 2569,
		ayahText: 'وَاَدْخَلْنٰهُمْ فِيْ رَحْمَتِنَاۗ اِنَّهُمْ مِّنَ الصّٰلِحِيْنَ ',
		ayahNumber: 86,
		translationId: 'Dan Kami masukkan mereka ke dalam rahmat Kami. Sungguh, mereka termasuk orang-orang yang saleh.',
	),
	Ayah(
		ayahId: 2570,
		ayahText: 'وَذَا النُّوْنِ اِذْ ذَّهَبَ مُغَاضِبًا فَظَنَّ اَنْ لَّنْ نَّقْدِرَ عَلَيْهِ فَنَادٰى فِى الظُّلُمٰتِ اَنْ لَّآ اِلٰهَ اِلَّآ اَنْتَ سُبْحٰنَكَ اِنِّيْ كُنْتُ مِنَ الظّٰلِمِيْنَ ۚ',
		ayahNumber: 87,
		translationId: 'Dan (ingatlah kisah) Zun Nun (Yunus), ketika dia pergi dalam keadaan marah, lalu dia menyangka bahwa Kami tidak akan menyulitkannya, maka dia berdoa dalam keadaan yang sangat gelap, ”Tidak ada tuhan selain Engkau, Mahasuci Engkau. Sungguh, aku  termasuk orang-orang yang zalim.”',
	),
	Ayah(
		ayahId: 2571,
		ayahText: 'فَاسْتَجَبْنَا لَهٗۙ وَنَجَّيْنٰهُ مِنَ الْغَمِّۗ وَكَذٰلِكَ نُـْۨجِى الْمُؤْمِنِيْنَ ',
		ayahNumber: 88,
		translationId: 'Maka Kami kabulkan (doa)nya dan Kami selamatkan dia dari kedukaan. Dan demikianlah Kami menyelamatkan orang-orang yang beriman.',
	),
	Ayah(
		ayahId: 2572,
		ayahText: 'وَزَكَرِيَّآ اِذْ نَادٰى رَبَّهٗ رَبِّ لَا تَذَرْنِيْ فَرْدًا وَّاَنْتَ خَيْرُ الْوٰرِثِيْنَ ۚ',
		ayahNumber: 89,
		translationId: ' Dan (ingatlah kisah) Zakaria, ketika dia berdoa kepada Tuhannya, “Ya Tuhanku, janganlah Engkau biarkan aku hidup seorang diri (tanpa keturunan) dan Engkaulah ahli waris yang terbaik.',
	),
	Ayah(
		ayahId: 2573,
		ayahText: 'فَاسْتَجَبْنَا لَهٗ  ۖوَوَهَبْنَا لَهٗ يَحْيٰى وَاَصْلَحْنَا لَهٗ زَوْجَهٗۗ اِنَّهُمْ كَانُوْا يُسٰرِعُوْنَ فِى الْخَيْرٰتِ وَيَدْعُوْنَنَا رَغَبًا وَّرَهَبًاۗ وَكَانُوْا لَنَا خٰشِعِيْنَ ',
		ayahNumber: 90,
		translationId: 'Maka Kami kabulkan (doa)nya, dan Kami anugerahkan kepadanya Yahya, dan Kami jadikan istrinya (dapat mengandung). Sungguh, mereka selalu bersegera dalam (mengerjakan) kebaikan, dan mereka berdoa kepada Kami dengan penuh harap dan cemas. Dan mereka orang-orang yang khusyuk kepada Kami.',
	),
	Ayah(
		ayahId: 2574,
		ayahText: 'وَالَّتِيْٓ اَحْصَنَتْ فَرْجَهَا فَنَفَخْنَا فِيْهَا مِنْ رُّوْحِنَا وَجَعَلْنٰهَا وَابْنَهَآ اٰيَةً لِّلْعٰلَمِيْنَ ',
		ayahNumber: 91,
		translationId: 'Dan (ingatlah kisah Maryam) yang memelihara kehormatannya, lalu Kami tiupkan (roh) dari Kami ke dalam (tubuh)nya; Kami jadikan dia dan anaknya sebagai tanda (kebesaran Allah)  bagi seluruh alam.',
	),
	Ayah(
		ayahId: 2575,
		ayahText: 'اِنَّ هٰذِهٖٓ اُمَّتُكُمْ اُمَّةً وَّاحِدَةًۖ وَّاَنَا۠ رَبُّكُمْ فَاعْبُدُوْنِ ',
		ayahNumber: 92,
		translationId: 'Sungguh, (agama tauhid) inilah agama kamu, agama yang satu, dan Aku adalah Tuhanmu, maka sembahlah Aku.',
	),
	Ayah(
		ayahId: 2576,
		ayahText: 'وَتَقَطَّعُوْٓا اَمْرَهُمْ بَيْنَهُمْۗ كُلٌّ اِلَيْنَا رَاجِعُوْنَ ࣖ',
		ayahNumber: 93,
		translationId: 'Tetapi mereka terpecah belah dalam urusan (agama) mereka di antara mereka. Masing-masing (golongan itu semua) akan kembali kepada Kami.',
	),
	Ayah(
		ayahId: 2577,
		ayahText: 'فَمَنْ يَّعْمَلْ مِنَ الصّٰلِحٰتِ وَهُوَ مُؤْمِنٌ فَلَا كُفْرَانَ لِسَعْيِهٖۚ وَاِنَّا لَهٗ كَاتِبُوْنَ ',
		ayahNumber: 94,
		translationId: 'Barangsiapa mengerjakan kebajikan, dan dia beriman, maka usahanya tidak akan diingkari (disia-siakan), dan sungguh, Kamilah yang mencatat untuknya.',
	),
	Ayah(
		ayahId: 2578,
		ayahText: 'وَحَرَامٌ عَلٰى قَرْيَةٍ اَهْلَكْنٰهَآ اَنَّهُمْ لَا يَرْجِعُوْنَ ',
		ayahNumber: 95,
		translationId: 'Dan tidak mungkin bagi (penduduk) suatu negeri yang telah Kami binasakan, bahwa mereka tidak akan kembali (kepada Kami).',
	),
	Ayah(
		ayahId: 2579,
		ayahText: 'حَتّٰىٓ اِذَا فُتِحَتْ يَأْجُوْجُ وَمَأْجُوْجُ وَهُمْ مِّنْ كُلِّ حَدَبٍ يَّنْسِلُوْنَ ',
		ayahNumber: 96,
		translationId: 'Hingga apabila (tembok) Yakjuj dan Makjuj dibukakan dan mereka turun dengan cepat dari seluruh tempat yang tinggi.',
	),
	Ayah(
		ayahId: 2580,
		ayahText: 'وَاقْتَرَبَ الْوَعْدُ الْحَقُّ فَاِذَا هِيَ شَاخِصَةٌ اَبْصَارُ الَّذِيْنَ كَفَرُوْاۗ يٰوَيْلَنَا قَدْ كُنَّا فِيْ غَفْلَةٍ مِّنْ هٰذَا بَلْ كُنَّا ظٰلِمِيْنَ ',
		ayahNumber: 97,
		translationId: 'Dan (apabila) janji yang benar (hari berbangkit) telah dekat, maka tiba-tiba mata orang-orang yang kafir terbelalak. (Mereka berkata), ”Alangkah celakanya kami! Kami benar-benar lengah tentang ini, bahkan kami benar-benar orang yang zalim.”',
	),
	Ayah(
		ayahId: 2581,
		ayahText: 'اِنَّكُمْ وَمَا تَعْبُدُوْنَ مِنْ دُوْنِ اللّٰهِ حَصَبُ جَهَنَّمَۗ اَنْتُمْ لَهَا وَارِدُوْنَ ',
		ayahNumber: 98,
		translationId: 'Sungguh, kamu (orang kafir) dan apa yang kamu sembah selain Allah, adalah bahan bakar Jahanam. Kamu (pasti) masuk ke dalamnya.',
	),
	Ayah(
		ayahId: 2582,
		ayahText: 'لَوْ كَانَ هٰٓؤُلَاۤءِ اٰلِهَةً مَّا وَرَدُوْهَاۗ وَكُلٌّ فِيْهَا خٰلِدُوْنَ ',
		ayahNumber: 99,
		translationId: 'Seandainya (berhala-berhala) itu tuhan, tentu mereka tidak akan memasukinya (neraka). Tetapi semuanya akan kekal di dalamnya.',
	),
	Ayah(
		ayahId: 2583,
		ayahText: 'لَهُمْ فِيْهَا زَفِيْرٌ وَّهُمْ فِيْهَا لَا يَسْمَعُوْنَ ',
		ayahNumber: 100,
		translationId: 'Mereka merintih dan menjerit di dalamnya (neraka), dan mereka di dalamnya tidak dapat mendengar.',
	),
	Ayah(
		ayahId: 2584,
		ayahText: 'اِنَّ الَّذِيْنَ سَبَقَتْ لَهُمْ مِّنَّا الْحُسْنٰىٓۙ اُولٰۤىِٕكَ عَنْهَا مُبْعَدُوْنَ ۙ',
		ayahNumber: 101,
		translationId: 'Sungguh, sejak dahulu bagi orang-orang yang telah ada (ketetapan) yang baik dari Kami, mereka itu akan dijauhkan (dari neraka).',
	),
	Ayah(
		ayahId: 2585,
		ayahText: 'لَا يَسْمَعُوْنَ حَسِيْسَهَاۚ وَهُمْ فِيْ مَا اشْتَهَتْ اَنْفُسُهُمْ خٰلِدُوْنَ ۚ',
		ayahNumber: 102,
		translationId: 'Mereka tidak mendengar bunyi desis (api neraka), dan mereka kekal dalam (menikmati) semua yang mereka ingini.  ',
	),
	Ayah(
		ayahId: 2586,
		ayahText: 'لَا يَحْزُنُهُمُ الْفَزَعُ الْاَكْبَرُ وَتَتَلَقّٰىهُمُ الْمَلٰۤىِٕكَةُۗ هٰذَا يَوْمُكُمُ الَّذِيْ كُنْتُمْ تُوْعَدُوْنَ ',
		ayahNumber: 103,
		translationId: 'Kejutan yang dahsyat tidak membuat mereka merasa sedih, dan para malaikat akan menyambut mereka (dengan ucapan), “Inilah harimu yang telah dijanjikan kepadamu.”',
	),
	Ayah(
		ayahId: 2587,
		ayahText: 'يَوْمَ نَطْوِى السَّمَاۤءَ كَطَيِّ السِّجِلِّ لِلْكُتُبِۗ  كَمَا بَدَأْنَآ اَوَّلَ خَلْقٍ نُّعِيْدُهٗۗ وَعْدًا عَلَيْنَاۗ اِنَّا كُنَّا فٰعِلِيْنَ ',
		ayahNumber: 104,
		translationId: '(Ingatlah) pada hari langit Kami gulung seperti menggulung lembaran-lembaran kertas. Sebagaimana Kami telah memulai penciptaan pertama, begitulah Kami akan mengulanginya lagi. (Suatu) janji yang pasti Kami tepati; sungguh, Kami akan melaksanakannya.',
	),
	Ayah(
		ayahId: 2588,
		ayahText: 'وَلَقَدْ كَتَبْنَا فِى الزَّبُوْرِ مِنْۢ بَعْدِ الذِّكْرِ اَنَّ الْاَرْضَ يَرِثُهَا عِبَادِيَ الصّٰلِحُوْنَ ',
		ayahNumber: 105,
		translationId: 'Dan sungguh, telah Kami tulis di dalam Zabur setelah (tertulis) di dalam Az-Zikr (Lauh Mahfuzh), bahwa bumi ini akan diwarisi oleh hamba-hamba-Ku yang saleh.',
	),
	Ayah(
		ayahId: 2589,
		ayahText: 'اِنَّ فِيْ هٰذَا لَبَلٰغًا لِّقَوْمٍ عٰبِدِيْنَ ۗ',
		ayahNumber: 106,
		translationId: "Sungguh, (apa yang disebutkan) di dalam (Al-Qur'an) ini, benar-benar menjadi petunjuk (yang lengkap) bagi orang-orang yang menyembah (Allah).",
	),
	Ayah(
		ayahId: 2590,
		ayahText: 'وَمَآ اَرْسَلْنٰكَ اِلَّا رَحْمَةً لِّلْعٰلَمِيْنَ ',
		ayahNumber: 107,
		translationId: 'Dan Kami tidak mengutus engkau (Muhammad) melainkan untuk (menjadi) rahmat bagi seluruh alam.',
	),
	Ayah(
		ayahId: 2591,
		ayahText: 'قُلْ اِنَّمَا يُوْحٰٓى اِلَيَّ اَنَّمَآ اِلٰهُكُمْ اِلٰهٌ وَّاحِدٌۚ فَهَلْ اَنْتُمْ مُّسْلِمُوْنَ',
		ayahNumber: 108,
		translationId: 'Katakanlah (Muhammad), “Sungguh, apa yang diwahyukan kepadaku ialah bahwa Tuhanmu adalah Tuhan Yang Esa, maka apakah kamu telah berserah diri (kepada-Nya)?”',
	),
	Ayah(
		ayahId: 2592,
		ayahText: 'فَاِنْ تَوَلَّوْا فَقُلْ اٰذَنْتُكُمْ عَلٰى سَوَاۤءٍۗ وَاِنْ اَدْرِيْٓ اَقَرِيْبٌ اَمْ بَعِيْدٌ مَّا تُوْعَدُوْنَ ',
		ayahNumber: 109,
		translationId: 'Maka jika mereka berpaling, maka katakanlah (Muhammad), “Aku telah menyampaikan kepadamu (ajaran) yang sama (antara kita) dan aku tidak tahu apakah yang diancamkan kepadamu itu sudah dekat atau masih jauh.”',
	),
	Ayah(
		ayahId: 2593,
		ayahText: 'اِنَّهٗ يَعْلَمُ الْجَهْرَ مِنَ الْقَوْلِ وَيَعْلَمُ مَا تَكْتُمُوْنَ ',
		ayahNumber: 110,
		translationId: 'Sungguh, Dia (Allah) mengetahui perkataan (yang kamu ucapkan) dengan terang-terangan, dan mengetahui (pula) apa yang kamu rahasiakan.',
	),
	Ayah(
		ayahId: 2594,
		ayahText: 'وَاِنْ اَدْرِيْ لَعَلَّهٗ فِتْنَةٌ لَّكُمْ وَمَتَاعٌ اِلٰى حِيْنٍ ',
		ayahNumber: 111,
		translationId: 'Dan aku tidak tahu, boleh jadi hal itu cobaan bagi kamu dan kesenangan sampai waktu yang ditentukan.',
	),
	Ayah(
		ayahId: 2595,
		ayahText: 'قَالَ رَبِّ احْكُمْ بِالْحَقِّۗ وَرَبُّنَا الرَّحْمٰنُ الْمُسْتَعَانُ عَلٰى مَا تَصِفُوْنَ ࣖ',
		ayahNumber: 112,
		translationId: 'Dia (Muhammad) berkata, “Ya Tuhanku, berilah keputusan dengan adil. Dan Tuhan kami Maha Pengasih, tempat memohon segala pertolongan atas semua yang kamu katakan.”',
	),
];
