// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah38 = [
	Ayah(
		ayahId: 3971,
		ayahText: 'صۤ ۗوَالْقُرْاٰنِ ذِى الذِّكْرِۗ',
		ayahNumber: 1,
		translationId: "Shad, demi Al-Qur'an yang mengandung peringatan. ",
	),
	Ayah(
		ayahId: 3972,
		ayahText: 'بَلِ الَّذِيْنَ كَفَرُوْا فِيْ عِزَّةٍ وَّشِقَاقٍ',
		ayahNumber: 2,
		translationId: 'Tetapi orang-orang yang kafir (berada) dalam kesombongan dan permusuhan.',
	),
	Ayah(
		ayahId: 3973,
		ayahText: 'كَمْ اَهْلَكْنَا مِنْ قَبْلِهِمْ مِّنْ قَرْنٍ فَنَادَوْا وَّلَاتَ حِيْنَ مَنَاصٍ',
		ayahNumber: 3,
		translationId: 'Betapa banyak umat sebelum mereka yang telah Kami binasakan, lalu mereka meminta tolong padahal (waktu itu) bukanlah saat untuk lari melepaskan diri.',
	),
	Ayah(
		ayahId: 3974,
		ayahText: 'وَعَجِبُوْٓا اَنْ جَاۤءَهُمْ مُّنْذِرٌ مِّنْهُمْ ۖوَقَالَ الْكٰفِرُوْنَ هٰذَا سٰحِرٌ كَذَّابٌۚ',
		ayahNumber: 4,
		translationId: 'Dan mereka heran karena mereka kedatangan seorang pemberi peringatan (rasul) dari kalangan mereka; dan orang-orang kafir berkata, “Orang ini adalah pesihir yang banyak berdusta.”',
	),
	Ayah(
		ayahId: 3975,
		ayahText: 'اَجَعَلَ الْاٰلِهَةَ اِلٰهًا وَّاحِدًا ۖاِنَّ هٰذَا لَشَيْءٌ عُجَابٌ',
		ayahNumber: 5,
		translationId: 'Apakah dia menjadikan tuhan-tuhan itu Tuhan yang satu saja? Sungguh, ini benar-benar sesuatu yang sangat mengherankan.',
	),
	Ayah(
		ayahId: 3976,
		ayahText: 'وَانْطَلَقَ الْمَلَاُ مِنْهُمْ اَنِ امْشُوْا وَاصْبِرُوْا عَلٰٓى اٰلِهَتِكُمْ ۖاِنَّ هٰذَا لَشَيْءٌ يُّرَادُ ۖ',
		ayahNumber: 6,
		translationId: 'Lalu pergilah pemimpin-pemimpin mereka (seraya berkata), “Pergilah kamu dan tetaplah  (menyembah) tuhan-tuhanmu, sesungguhnya ini benar-benar suatu hal yang dikehendaki.',
	),
	Ayah(
		ayahId: 3977,
		ayahText: 'مَا سَمِعْنَا بِهٰذَا فِى الْمِلَّةِ الْاٰخِرَةِ ۖاِنْ هٰذَآ اِلَّا اخْتِلَاقٌۚ',
		ayahNumber: 7,
		translationId: 'Kami tidak pernah mendengar hal ini dalam agama yang terakhir; ini (mengesakan Allah), tidak lain hanyalah (dusta) yang diada-adakan,',
	),
	Ayah(
		ayahId: 3978,
		ayahText: 'اَؤُنْزِلَ عَلَيْهِ الذِّكْرُ مِنْۢ بَيْنِنَا ۗبَلْ هُمْ فِيْ شَكٍّ مِّنْ ذِكْرِيْۚ بَلْ لَّمَّا يَذُوْقُوْا عَذَابِ ۗ',
		ayahNumber: 8,
		translationId: "mengapa Al-Qur'an itu diturunkan kepada dia di antara kita?” Sebenarnya mereka ragu-ragu terhadap Al-Qur'an-Ku, tetapi mereka belum merasakan azab(-Ku).",
	),
	Ayah(
		ayahId: 3979,
		ayahText: 'اَمْ عِنْدَهُمْ خَزَاۤىِٕنُ رَحْمَةِ رَبِّكَ الْعَزِيْزِ الْوَهَّابِۚ',
		ayahNumber: 9,
		translationId: 'Atau apakah mereka itu mempunyai perbendaharaan rahmat Tuhanmu Yang Mahaperkasa, Maha Pemberi?]',
	),
	Ayah(
		ayahId: 3980,
		ayahText: 'اَمْ لَهُمْ مُّلْكُ السَّمٰوٰتِ وَالْاَرْضِ وَمَا بَيْنَهُمَا ۗفَلْيَرْتَقُوْا فِى الْاَسْبَابِ',
		ayahNumber: 10,
		translationId: 'Atau apakah mereka mempunyai kerajaan langit dan bumi dan apa yang ada di antara keduanya? (Jika ada), maka biarlah mereka menaiki tangga-tangga (ke langit).',
	),
	Ayah(
		ayahId: 3981,
		ayahText: 'جُنْدٌ مَّا هُنَالِكَ مَهْزُوْمٌ مِّنَ الْاَحْزَابِ',
		ayahNumber: 11,
		translationId: '(Mereka itu) kelompok besar bala tentara yang berada di sana yang akan dikalahkan.',
	),
	Ayah(
		ayahId: 3982,
		ayahText: 'كَذَّبَتْ قَبْلَهُمْ قَوْمُ نُوْحٍ وَّعَادٌ وَّفِرْعَوْنُ ذُو الْاَوْتَادِۙ',
		ayahNumber: 12,
		translationId: 'Sebelum mereka itu, kaum Nuh, ‘Ad dan Fir’aun yang mempunyai bala tentara yang banyak, juga telah mendustakan (rasul-rasul),',
	),
	Ayah(
		ayahId: 3983,
		ayahText: 'وَثَمُوْدُ وَقَوْمُ لُوْطٍ وَّاَصْحٰبُ لْـَٔيْكَةِ ۗ اُولٰۤىِٕكَ الْاَحْزَابُ',
		ayahNumber: 13,
		translationId: 'dan (begitu juga) Samud, kaum Lut dan penduduk Aikah. Mereka itulah golongan-golongan yang bersekutu (menentang rasul-rasul).',
	),
	Ayah(
		ayahId: 3984,
		ayahText: 'اِنْ كُلٌّ اِلَّا كَذَّبَ الرُّسُلَ فَحَقَّ عِقَابِ ࣖ',
		ayahNumber: 14,
		translationId: 'Semua mereka itu mendustakan rasul-rasul, maka pantas mereka merasakan azab-Ku.',
	),
	Ayah(
		ayahId: 3985,
		ayahText: 'وَمَا يَنْظُرُ هٰٓؤُلَاۤءِ اِلَّا صَيْحَةً وَّاحِدَةً مَّا لَهَا مِنْ فَوَاقٍ',
		ayahNumber: 15,
		translationId: 'Dan sebenarnya yang mereka tunggu adalah satu teriakan saja, yang tidak ada selanya.',
	),
	Ayah(
		ayahId: 3986,
		ayahText: 'وَقَالُوْا رَبَّنَا عَجِّلْ لَّنَا قِطَّنَا قَبْلَ يَوْمِ الْحِسَابِ',
		ayahNumber: 16,
		translationId: 'Dan mereka berkata, “Ya Tuhan kami, segerakanlah azab yang diperuntukkan bagi kami sebelum hari perhitungan.”',
	),
	Ayah(
		ayahId: 3987,
		ayahText: 'اِصْبِرْ عَلٰى مَا يَقُوْلُوْنَ وَاذْكُرْ عَبْدَنَا دَاوٗدَ ذَا الْاَيْدِۚ اِنَّهٗٓ اَوَّابٌ',
		ayahNumber: 17,
		translationId: 'Bersabarlah atas apa yang mereka katakan; dan ingatlah akan hamba Kami Dawud yang mempunyai kekuatan; sungguh dia sangat taat (kepada Allah).',
	),
	Ayah(
		ayahId: 3988,
		ayahText: 'اِنَّا سَخَّرْنَا الْجِبَالَ مَعَهٗ يُسَبِّحْنَ بِالْعَشِيِّ وَالْاِشْرَاقِۙ',
		ayahNumber: 18,
		translationId: 'Sungguh, Kamilah yang menundukkan gunung-gunung untuk bertasbih bersama dia (Dawud) pada waktu petang dan pagi,',
	),
	Ayah(
		ayahId: 3989,
		ayahText: 'وَالطَّيْرَمَحْشُوْرَةً ۗ كُلٌّ لَهٗٓ اَوَّابٌ',
		ayahNumber: 19,
		translationId: 'dan (Kami tundukkan pula) burung-burung dalam keadaan terkumpul. Masing-masing sangat taat (kepada Allah).',
	),
	Ayah(
		ayahId: 3990,
		ayahText: 'وَشَدَدْنَا مُلْكَهٗ وَاٰتَيْنٰهُ الْحِكْمَةَ وَفَصْلَ الْخِطَابِ',
		ayahNumber: 20,
		translationId: 'Dan Kami kuatkan kerajaannya dan Kami berikan hikmah kepadanya serta kebijaksanaan dalam memutuskan perkara.',
	),
	Ayah(
		ayahId: 3991,
		ayahText: 'وَهَلْ اَتٰىكَ نَبَؤُ الْخَصْمِۘ اِذْ تَسَوَّرُوا الْمِحْرَابَۙ',
		ayahNumber: 21,
		translationId: 'Dan apakah telah sampai kepadamu berita orang-orang yang berselisih ketika mereka memanjat dinding mihrab?',
	),
	Ayah(
		ayahId: 3992,
		ayahText: 'اِذْ دَخَلُوْا عَلٰى دَاوٗدَ فَفَزِعَ مِنْهُمْ قَالُوْا لَا تَخَفْۚ خَصْمٰنِ بَغٰى بَعْضُنَا عَلٰى بَعْضٍ فَاحْكُمْ بَيْنَنَا بِالْحَقِّ وَلَا تُشْطِطْ وَاهْدِنَآ اِلٰى سَوَاۤءِ الصِّرَاطِ',
		ayahNumber: 22,
		translationId: 'ketika mereka masuk menemui Dawud lalu dia terkejut karena (kedatangan) mereka. Mereka berkata, “Janganlah takut! (Kami) berdua sedang berselisih, sebagian dari kami berbuat zalim kepada yang lain; maka berilah keputusan di antara kami secara adil dan janganlah menyimpang dari kebenaran serta tunjukilah kami ke jalan yang lurus.',
	),
	Ayah(
		ayahId: 3993,
		ayahText: 'اِنَّ هٰذَآ اَخِيْ ۗ لَهٗ تِسْعٌ وَّتِسْعُوْنَ نَعْجَةً وَّلِيَ نَعْجَةٌ وَّاحِدَةٌ ۗفَقَالَ اَكْفِلْنِيْهَا وَعَزَّنِيْ فِى الْخِطَابِ',
		ayahNumber: 23,
		translationId: 'Sesungguhnya saudaraku ini mempunyai sembilan puluh sembilan ekor kambing betina dan aku mempunyai seekor saja, lalu dia berkata, “Serahkanlah (kambingmu) itu kepadaku! Dan dia mengalahkan aku dalam perdebatan.”',
	),
	Ayah(
		ayahId: 3994,
		ayahText: 'قَالَ لَقَدْ ظَلَمَكَ بِسُؤَالِ نَعْجَتِكَ اِلٰى نِعَاجِهٖۗ وَاِنَّ كَثِيْرًا مِّنَ الْخُلَطَاۤءِ لَيَبْغِيْ بَعْضُهُمْ عَلٰى بَعْضٍ اِلَّا الَّذِيْنَ اٰمَنُوْا وَعَمِلُوا الصّٰلِحٰتِ وَقَلِيْلٌ مَّا هُمْۗ وَظَنَّ دَاوٗدُ اَنَّمَا فَتَنّٰهُ فَاسْتَغْفَرَ رَبَّهٗ وَخَرَّ رَاكِعًا وَّاَنَابَ ۩ ',
		ayahNumber: 24,
		translationId: 'Dia (Dawud) berkata, “Sungguh, dia telah berbuat zalim kepadamu dengan meminta kambingmu itu untuk (ditambahkan) kepada kambingnya. Memang banyak di antara orang-orang yang bersekutu itu berbuat zalim kepada yang lain, kecuali orang-orang yang beriman dan mengerjakan kebajikan; dan hanya sedikitlah mereka yang begitu.” Dan Dawud menduga bahwa Kami mengujinya; maka dia memohon ampunan kepada Tuhannya lalu menyungkur sujud dan bertobat.',
	),
	Ayah(
		ayahId: 3995,
		ayahText: 'فَغَفَرْنَا لَهٗ ذٰلِكَۗ وَاِنَّ لَهٗ عِنْدَنَا لَزُلْفٰى وَحُسْنَ مَاٰبٍ',
		ayahNumber: 25,
		translationId: 'Lalu Kami mengampuni (kesalahannya) itu. Dan sungguh, dia mempunyai kedudukan yang benar-benar dekat di sisi Kami dan tempat kembali yang baik.',
	),
	Ayah(
		ayahId: 3996,
		ayahText: 'يٰدَاوٗدُ اِنَّا جَعَلْنٰكَ خَلِيْفَةً فِى الْاَرْضِ فَاحْكُمْ بَيْنَ النَّاسِ بِالْحَقِّ وَلَا تَتَّبِعِ الْهَوٰى فَيُضِلَّكَ عَنْ سَبِيْلِ اللّٰهِ ۗاِنَّ الَّذِيْنَ يَضِلُّوْنَ عَنْ سَبِيْلِ اللّٰهِ لَهُمْ عَذَابٌ شَدِيْدٌ ۢبِمَا نَسُوْا يَوْمَ الْحِسَابِ ࣖ ',
		ayahNumber: 26,
		translationId: '(Allah berfirman), “Wahai Dawud! Sesungguhnya engkau Kami jadikan khalifah (penguasa) di bumi, maka berilah keputusan (perkara) di antara manusia dengan adil dan janganlah engkau mengikuti hawa nafsu, karena akan menyesatkan engkau dari jalan Allah. Sungguh, orang-orang yang sesat dari jalan Allah akan mendapat azab yang berat, karena mereka melupakan hari perhitungan.”',
	),
	Ayah(
		ayahId: 3997,
		ayahText: 'وَمَا خَلَقْنَا السَّمَاۤءَ وَالْاَرْضَ وَمَا بَيْنَهُمَا بَاطِلًا ۗذٰلِكَ ظَنُّ الَّذِيْنَ كَفَرُوْا فَوَيْلٌ لِّلَّذِيْنَ كَفَرُوْا مِنَ النَّارِۗ',
		ayahNumber: 27,
		translationId: 'Dan Kami tidak menciptakan langit dan bumi dan apa yang ada di antara keduanya dengan sia-sia. Itu anggapan orang-orang kafir, maka celakalah orang-orang yang kafir itu karena mereka akan masuk neraka.',
	),
	Ayah(
		ayahId: 3998,
		ayahText: 'اَمْ نَجْعَلُ الَّذِيْنَ اٰمَنُوْا وَعَمِلُوا الصّٰلِحٰتِ كَالْمُفْسِدِيْنَ فِى الْاَرْضِۖ اَمْ نَجْعَلُ الْمُتَّقِيْنَ كَالْفُجَّارِ',
		ayahNumber: 28,
		translationId: 'Pantaskah Kami memperlakukan orang-orang yang beriman dan mengerjakan kebajikan sama dengan orang-orang yang berbuat kerusakan di bumi? Atau pantaskah Kami menganggap orang-orang yang bertakwa sama dengan orang-orang yang jahat?',
	),
	Ayah(
		ayahId: 3999,
		ayahText: 'كِتٰبٌ اَنْزَلْنٰهُ اِلَيْكَ مُبٰرَكٌ لِّيَدَّبَّرُوْٓا اٰيٰتِهٖ وَلِيَتَذَكَّرَ اُولُوا الْاَلْبَابِ',
		ayahNumber: 29,
		translationId: "Kitab (Al-Qur'an) yang Kami turunkan kepadamu penuh berkah agar mereka menghayati ayat-ayatnya dan agar orang-orang yang berakal sehat mendapat pelajaran.",
	),
	Ayah(
		ayahId: 4000,
		ayahText: 'وَوَهَبْنَا لِدَاوٗدَ سُلَيْمٰنَۗ نِعْمَ الْعَبْدُ ۗاِنَّهٗٓ اَوَّابٌۗ',
		ayahNumber: 30,
		translationId: 'Dan kepada Dawud Kami karuniakan (anak bernama) Sulaiman; dia adalah sebaik-baik hamba. Sungguh, dia sangat taat (kepada Allah).',
	),
	Ayah(
		ayahId: 4001,
		ayahText: 'اِذْ عُرِضَ عَلَيْهِ بِالْعَشِيِّ الصّٰفِنٰتُ الْجِيَادُۙ',
		ayahNumber: 31,
		translationId: '(Ingatlah) ketika pada suatu sore dipertunjukkan kepadanya (kuda-kuda) yang jinak, (tetapi) sangat cepat larinya,',
	),
	Ayah(
		ayahId: 4002,
		ayahText: 'فَقَالَ اِنِّيْٓ اَحْبَبْتُ حُبَّ الْخَيْرِ عَنْ ذِكْرِ رَبِّيْۚ حَتّٰى تَوَارَتْ بِالْحِجَابِۗ',
		ayahNumber: 32,
		translationId: 'maka dia berkata, “Sesungguhnya aku menyukai segala yang baik (kuda), yang membuat aku ingat akan (kebesaran) Tuhanku, sampai matahari terbenam.”',
	),
	Ayah(
		ayahId: 4003,
		ayahText: 'رُدُّوْهَا عَلَيَّ ۚفَطَفِقَ مَسْحًا ۢبِالسُّوْقِ وَالْاَعْنَاقِ',
		ayahNumber: 33,
		translationId: '”Bawalah semua kuda itu kembali kepadaku.” Lalu dia mengusap-usap kaki dan leher kuda itu.',
	),
	Ayah(
		ayahId: 4004,
		ayahText: 'وَلَقَدْ فَتَنَّا سُلَيْمٰنَ وَاَلْقَيْنَا عَلٰى كُرْسِيِّهٖ جَسَدًا ثُمَّ اَنَابَ',
		ayahNumber: 34,
		translationId: 'Dan sungguh, Kami telah menguji Sulaiman dan Kami jadikan (dia) tergeletak di atas kursinya sebagai tubuh (yang lemah karena sakit), kemudian dia bertobat.',
	),
	Ayah(
		ayahId: 4005,
		ayahText: 'قَالَ رَبِّ اغْفِرْ لِيْ وَهَبْ لِيْ مُلْكًا لَّا يَنْۢبَغِيْ لِاَحَدٍ مِّنْۢ بَعْدِيْۚ اِنَّكَ اَنْتَ الْوَهَّابُ',
		ayahNumber: 35,
		translationId: 'Dia berkata, “Ya Tuhanku, ampunilah aku dan anugerahkanlah kepadaku kerajaan yang tidak dimiliki oleh siapa pun setelahku. Sungguh, Engkaulah Yang Maha Pemberi.”',
	),
	Ayah(
		ayahId: 4006,
		ayahText: 'فَسَخَّرْنَا لَهُ الرِّيْحَ تَجْرِيْ بِاَمْرِهٖ رُخَاۤءً حَيْثُ اَصَابَۙ',
		ayahNumber: 36,
		translationId: 'Kemudian Kami tundukkan kepadanya angin yang berhembus dengan baik menurut perintahnya ke mana saja yang dikehendakinya,',
	),
	Ayah(
		ayahId: 4007,
		ayahText: 'وَالشَّيٰطِيْنَ كُلَّ بَنَّاۤءٍ وَّغَوَّاصٍۙ',
		ayahNumber: 37,
		translationId: 'dan (Kami tundukkan pula kepadanya) setan-setan, semuanya ahli bangunan dan penyelam,',
	),
	Ayah(
		ayahId: 4008,
		ayahText: 'وَّاٰخَرِيْنَ مُقَرَّنِيْنَ فِى الْاَصْفَادِ',
		ayahNumber: 38,
		translationId: 'dan (setan) yang lain yang terikat dalam belenggu.',
	),
	Ayah(
		ayahId: 4009,
		ayahText: 'هٰذَا عَطَاۤؤُنَا فَامْنُنْ اَوْ اَمْسِكْ بِغَيْرِ حِسَابٍ',
		ayahNumber: 39,
		translationId: 'Inilah anugerah Kami; maka berikanlah (kepada orang lain) atau tahanlah (untuk dirimu sendiri) tanpa perhitungan.',
	),
	Ayah(
		ayahId: 4010,
		ayahText: 'وَاِنَّ لَهٗ عِنْدَنَا لَزُلْفٰى وَحُسْنَ مَاٰبٍ ࣖ',
		ayahNumber: 40,
		translationId: 'Dan sungguh, dia mempunyai kedudukan yang dekat pada sisi Kami dan tempat kembali yang baik.',
	),
	Ayah(
		ayahId: 4011,
		ayahText: 'وَاذْكُرْ عَبْدَنَآ اَيُّوْبَۘ اِذْ نَادٰى رَبَّهٗٓ اَنِّيْ مَسَّنِيَ الشَّيْطٰنُ بِنُصْبٍ وَّعَذَابٍۗ',
		ayahNumber: 41,
		translationId: 'Dan ingatlah akan hamba Kami Ayyub ketika dia menyeru Tuhannya, “Sesungguhnya aku diganggu setan dengan penderitaan dan bencana.”',
	),
	Ayah(
		ayahId: 4012,
		ayahText: 'اُرْكُضْ بِرِجْلِكَۚ هٰذَا مُغْتَسَلٌۢ بَارِدٌ وَّشَرَابٌ',
		ayahNumber: 42,
		translationId: 'Allah berfirman), “Hentakkanlah kakimu; inilah air yang sejuk untuk mandi dan untuk minum.”',
	),
	Ayah(
		ayahId: 4013,
		ayahText: 'وَوَهَبْنَا لَهٗٓ اَهْلَهٗ وَمِثْلَهُمْ مَّعَهُمْ رَحْمَةً مِّنَّا وَذِكْرٰى لِاُولِى الْاَلْبَابِ',
		ayahNumber: 43,
		translationId: 'Dan Kami anugerahi dia (dengan mengumpulkan kembali) keluarganya dan Kami lipatgandakan jumlah mereka, sebagai rahmat dari Kami dan pelajaran bagi orang-orang yang berpikiran sehat.',
	),
	Ayah(
		ayahId: 4014,
		ayahText: 'وَخُذْ بِيَدِكَ ضِغْثًا فَاضْرِبْ بِّهٖ وَلَا تَحْنَثْ ۗاِنَّا وَجَدْنٰهُ صَابِرًا ۗنِعْمَ الْعَبْدُ ۗاِنَّهٗٓ اَوَّابٌ',
		ayahNumber: 44,
		translationId: 'Dan ambillah seikat (rumput) dengan tanganmu, lalu pukullah dengan itu dan janganlah engkau melanggar sumpah. Sesungguhnya Kami dapati dia (Ayyub) seorang yang sabar. Dialah sebaik-baik hamba. Sungguh, dia sangat taat (kepada Allah).',
	),
	Ayah(
		ayahId: 4015,
		ayahText: 'وَاذْكُرْ عِبٰدَنَآ اِبْرٰهِيْمَ وَاِسْحٰقَ وَيَعْقُوْبَ اُولِى الْاَيْدِيْ وَالْاَبْصَارِ',
		ayahNumber: 45,
		translationId: 'Dan ingatlah hamba-hamba Kami: Ibrahim, Ishak dan Yakub yang mempunyai kekuatan-kekuatan yang besar dan ilmu-ilmu (yang tinggi).',
	),
	Ayah(
		ayahId: 4016,
		ayahText: 'اِنَّآ اَخْلَصْنٰهُمْ بِخَالِصَةٍ ذِكْرَى الدَّارِۚ ',
		ayahNumber: 46,
		translationId: 'Sungguh, Kami telah menyucikan mereka dengan (menganugerahkan) akhlak yang tinggi kepadanya yaitu selalu mengingatkan (manusia) kepada negeri akhirat.',
	),
	Ayah(
		ayahId: 4017,
		ayahText: 'وَاِنَّهُمْ عِنْدَنَا لَمِنَ الْمُصْطَفَيْنَ الْاَخْيَارِۗ',
		ayahNumber: 47,
		translationId: 'Dan sungguh, di sisi Kami mereka termasuk orang-orang pilihan yang paling baik.',
	),
	Ayah(
		ayahId: 4018,
		ayahText: 'وَاذْكُرْ اِسْمٰعِيْلَ وَالْيَسَعَ وَذَا الْكِفْلِ ۗوَكُلٌّ مِّنَ الْاَخْيَارِۗ',
		ayahNumber: 48,
		translationId: 'Dan ingatlah Ismail, Ilyasa‘ dan Zulkifli. Semuanya termasuk orang-orang yang paling baik.',
	),
	Ayah(
		ayahId: 4019,
		ayahText: 'هٰذَا ذِكْرٌ ۗوَاِنَّ لِلْمُتَّقِيْنَ لَحُسْنَ مَاٰبٍۙ ',
		ayahNumber: 49,
		translationId: 'Ini adalah kehormatan (bagi mereka). Dan sungguh, bagi orang-orang yang bertakwa (disediakan) tempat kembali yang terbaik,',
	),
	Ayah(
		ayahId: 4020,
		ayahText: 'جَنّٰتِ عَدْنٍ مُّفَتَّحَةً لَّهُمُ الْاَبْوَابُۚ',
		ayahNumber: 50,
		translationId: '(yaitu) surga ’Adn yang pintu-pintunya terbuka bagi mereka,',
	),
	Ayah(
		ayahId: 4021,
		ayahText: 'مُتَّكِـِٕيْنَ فِيْهَا يَدْعُوْنَ فِيْهَا بِفَاكِهَةٍ كَثِيْرَةٍ وَّشَرَابٍ',
		ayahNumber: 51,
		translationId: 'di dalamnya mereka bersandar (di atas dipan-dipan) sambil meminta buah-buahan yang banyak dan minuman (di surga itu).',
	),
	Ayah(
		ayahId: 4022,
		ayahText: 'وَعِنْدَهُمْ قٰصِرٰتُ الطَّرْفِ اَتْرَابٌ',
		ayahNumber: 52,
		translationId: 'dan di samping mereka (ada bidadari-bidadari) yang redup pandangannya dan sebaya umurnya.',
	),
	Ayah(
		ayahId: 4023,
		ayahText: 'هٰذَا مَا تُوْعَدُوْنَ لِيَوْمِ الْحِسَابِ',
		ayahNumber: 53,
		translationId: 'Inilah apa yang dijanjikan kepadamu pada hari perhitungan.',
	),
	Ayah(
		ayahId: 4024,
		ayahText: 'اِنَّ هٰذَا لَرِزْقُنَا مَا لَهٗ مِنْ نَّفَادٍۚ',
		ayahNumber: 54,
		translationId: 'Sungguh, inilah rezeki dari Kami yang tidak ada habis-habisnya.',
	),
	Ayah(
		ayahId: 4025,
		ayahText: 'هٰذَا ۗوَاِنَّ لِلطّٰغِيْنَ لَشَرَّ مَاٰبٍۙ',
		ayahNumber: 55,
		translationId: 'Beginilah (keadaan mereka). Dan sungguh, bagi orang-orang yang durhaka pasti (disediakan) tempat kembali yang buruk,',
	),
	Ayah(
		ayahId: 4026,
		ayahText: 'جَهَنَّمَۚ يَصْلَوْنَهَاۚ فَبِئْسَ الْمِهَادُ',
		ayahNumber: 56,
		translationId: '(yaitu) neraka Jahanam yang mereka masuki; maka itulah seburuk-buruk tempat tinggal.',
	),
	Ayah(
		ayahId: 4027,
		ayahText: 'هٰذَاۙ فَلْيَذُوْقُوْهُ حَمِيْمٌ وَّغَسَّاقٌۙ',
		ayahNumber: 57,
		translationId: 'Inilah (azab neraka), maka biarlah mereka merasakannya, (minuman mereka) air yang sangat panas dan air yang sangat dingin,',
	),
	Ayah(
		ayahId: 4028,
		ayahText: 'وَّاٰخَرُ مِنْ شَكْلِهٖٓ اَزْوَاجٌۗ',
		ayahNumber: 58,
		translationId: 'dan berbagai macam (azab) yang lain yang serupa itu.',
	),
	Ayah(
		ayahId: 4029,
		ayahText: 'هٰذَا فَوْجٌ مُّقْتَحِمٌ مَّعَكُمْۚ  لَا مَرْحَبًا ۢبِهِمْ ۗ اِنَّهُمْ صَالُوا النَّارِ',
		ayahNumber: 59,
		translationId: '(Dikatakan kepada mereka), “Ini rombongan besar (pengikut-pengikutmu) yang masuk berdesak-desak bersama kamu (ke neraka).” Tidak ada ucapan selamat datang bagi mereka karena sesungguhnya mereka akan masuk neraka (kata pemimpin-pemimpin mereka).',
	),
	Ayah(
		ayahId: 4030,
		ayahText: 'قَالُوْا بَلْ اَنْتُمْ لَا مَرْحَبًاۢ بِكُمْ ۗ اَنْتُمْ قَدَّمْتُمُوْهُ لَنَاۚ فَبِئْسَ الْقَرَارُ',
		ayahNumber: 60,
		translationId: '(Para pengikut mereka menjawab), “Sebenarnya kamulah yang (lebih pan-tas) tidak menerima ucapan selamat datang, karena kamulah yang menjerumuskan kami ke dalam azab, maka itulah seburuk-buruk tempat menetap.”',
	),
	Ayah(
		ayahId: 4031,
		ayahText: 'قَالُوْا رَبَّنَا مَنْ قَدَّمَ لَنَا هٰذَا فَزِدْهُ عَذَابًا ضِعْفًا فِى النَّارِ',
		ayahNumber: 61,
		translationId: 'Mereka berkata (lagi), “Ya Tuhan kami, barangsiapa menjerumuskan kami ke dalam (azab) ini, maka tambahkanlah azab kepadanya dua kali lipat di dalam neraka.”',
	),
	Ayah(
		ayahId: 4032,
		ayahText: 'وَقَالُوْا مَا لَنَا لَا نَرٰى رِجَالًا كُنَّا نَعُدُّهُمْ مِّنَ الْاَشْرَارِ',
		ayahNumber: 62,
		translationId: 'Dan (orang-orang durhaka) berkata, “Mengapa kami tidak melihat orang-orang yang dahulu (di dunia) kami anggap sebagai orang-orang yang jahat (hina).',
	),
	Ayah(
		ayahId: 4033,
		ayahText: 'اَتَّخَذْنٰهُمْ سِخْرِيًّا اَمْ زَاغَتْ عَنْهُمُ الْاَبْصَارُ',
		ayahNumber: 63,
		translationId: 'Dahulu kami menjadikan mereka olok-olokan, ataukah karena penglihatan kami yang tidak melihat mereka?”',
	),
	Ayah(
		ayahId: 4034,
		ayahText: 'اِنَّ ذٰلِكَ لَحَقٌّ تَخَاصُمُ اَهْلِ النَّارِ ࣖ',
		ayahNumber: 64,
		translationId: 'Sungguh, yang demikian benar-benar terjadi, (yaitu) pertengkaran di antara penghuni neraka.',
	),
	Ayah(
		ayahId: 4035,
		ayahText: 'قُلْ اِنَّمَآ اَنَا۠ مُنْذِرٌ ۖوَّمَا مِنْ اِلٰهٍ اِلَّا اللّٰهُ الْوَاحِدُ الْقَهَّارُ',
		ayahNumber: 65,
		translationId: 'Katakanlah (Muhammad), “Sesungguhnya aku hanya seorang pemberi peringatan, tidak ada tuhan selain Allah Yang Maha Esa, Mahaperkasa,',
	),
	Ayah(
		ayahId: 4036,
		ayahText: 'رَبُّ السَّمٰوٰتِ وَالْاَرْضِ وَمَا بَيْنَهُمَا الْعَزِيْزُ الْغَفَّارُ',
		ayahNumber: 66,
		translationId: '(yaitu) Tuhan langit dan bumi dan apa yang ada di antara keduanya, Yang Mahaperkasa, Maha Pengampun.”',
	),
	Ayah(
		ayahId: 4037,
		ayahText: 'قُلْ هُوَ نَبَؤٌا عَظِيْمٌۙ',
		ayahNumber: 67,
		translationId: "Katakanlah, “Itu (Al-Qur'an) adalah berita besar,",
	),
	Ayah(
		ayahId: 4038,
		ayahText: 'اَنْتُمْ عَنْهُ مُعْرِضُوْنَ',
		ayahNumber: 68,
		translationId: 'yang kamu berpaling darinya.',
	),
	Ayah(
		ayahId: 4039,
		ayahText: 'مَا كَانَ لِيَ مِنْ عِلْمٍۢ بِالْمَلَاِ الْاَعْلٰٓى اِذْ يَخْتَصِمُوْنَ',
		ayahNumber: 69,
		translationId: 'Aku tidak mempunyai pengetahuan sedikit pun tentang al-mala’ul a’la (malaikat) itu ketika mereka berbantah-bantahan.',
	),
	Ayah(
		ayahId: 4040,
		ayahText: 'اِنْ يُّوْحٰىٓ اِلَيَّ اِلَّآ اَنَّمَآ اَنَا۠ نَذِيْرٌ مُّبِيْنٌ',
		ayahNumber: 70,
		translationId: 'Yang diwahyukan kepadaku, bahwa aku hanyalah seorang pemberi peringatan yang nyata.”',
	),
	Ayah(
		ayahId: 4041,
		ayahText: 'اِذْ قَالَ رَبُّكَ لِلْمَلٰۤىِٕكَةِ اِنِّيْ خَالِقٌۢ بَشَرًا مِّنْ طِيْنٍ',
		ayahNumber: 71,
		translationId: '(Ingatlah) ketika Tuhanmu berfirman kepada malaikat, “Sesungguhnya Aku akan menciptakan manusia dari tanah.',
	),
	Ayah(
		ayahId: 4042,
		ayahText: 'فَاِذَا سَوَّيْتُهٗ وَنَفَخْتُ فِيْهِ مِنْ رُّوْحِيْ فَقَعُوْا لَهٗ سٰجِدِيْنَ',
		ayahNumber: 72,
		translationId: 'Kemudian apabila telah Aku sempurnakan kejadiannya dan Aku tiupkan roh (ciptaan)-Ku kepadanya; maka tunduklah kamu dengan bersujud kepadanya.”',
	),
	Ayah(
		ayahId: 4043,
		ayahText: 'فَسَجَدَ الْمَلٰۤىِٕكَةُ كُلُّهُمْ اَجْمَعُوْنَۙ',
		ayahNumber: 73,
		translationId: 'Lalu para malaikat itu bersujud semuanya,',
	),
	Ayah(
		ayahId: 4044,
		ayahText: 'اِلَّآ اِبْلِيْسَۗ اِسْتَكْبَرَ وَكَانَ مِنَ الْكٰفِرِيْنَ',
		ayahNumber: 74,
		translationId: 'kecuali Iblis; ia menyombongkan diri dan ia termasuk golongan yang kafir.',
	),
	Ayah(
		ayahId: 4045,
		ayahText: 'قَالَ يٰٓاِبْلِيْسُ مَا مَنَعَكَ اَنْ تَسْجُدَ لِمَا خَلَقْتُ بِيَدَيَّ ۗ اَسْتَكْبَرْتَ اَمْ كُنْتَ مِنَ الْعَالِيْنَ',
		ayahNumber: 75,
		translationId: '(Allah) berfirman, “Wahai Iblis, apakah yang menghalangi kamu sujud kepada yang telah Aku ciptakan dengan kekuasaan-Ku. Apakah kamu menyombongkan diri atau kamu (merasa) termasuk golongan yang (lebih) tinggi?”',
	),
	Ayah(
		ayahId: 4046,
		ayahText: 'قَالَ اَنَا۠ خَيْرٌ مِّنْهُ خَلَقْتَنِيْ مِنْ نَّارٍ وَّخَلَقْتَهٗ مِنْ طِيْنٍ',
		ayahNumber: 76,
		translationId: '(Iblis) berkata, “Aku lebih baik daripadanya, karena Engkau ciptakan aku dari api, sedangkan dia Engkau ciptakan dari tanah.”',
	),
	Ayah(
		ayahId: 4047,
		ayahText: 'قَالَ فَاخْرُجْ مِنْهَا فَاِنَّكَ رَجِيْمٌۖ',
		ayahNumber: 77,
		translationId: '(Allah) berfirman, “Kalau begitu keluarlah kamu dari surga! Sesungguhnya kamu adalah makhluk yang terkutuk.',
	),
	Ayah(
		ayahId: 4048,
		ayahText: 'وَّاِنَّ عَلَيْكَ لَعْنَتِيْٓ اِلٰى يَوْمِ الدِّيْنِ',
		ayahNumber: 78,
		translationId: 'Dan sungguh, kutukan-Ku tetap atasmu sampai hari pembalasan.”',
	),
	Ayah(
		ayahId: 4049,
		ayahText: 'قَالَ رَبِّ فَاَنْظِرْنِيْٓ اِلٰى يَوْمِ يُبْعَثُوْنَ',
		ayahNumber: 79,
		translationId: '(Iblis) berkata, “Ya Tuhanku, tangguhkanlah aku sampai pada hari mereka dibangkitkan.”',
	),
	Ayah(
		ayahId: 4050,
		ayahText: 'قَالَ فَاِنَّكَ مِنَ الْمُنْظَرِيْنَۙ',
		ayahNumber: 80,
		translationId: '(Allah) berfirman, “Maka sesungguhnya kamu termasuk golongan yang diberi penangguhan,',
	),
	Ayah(
		ayahId: 4051,
		ayahText: 'اِلٰى يَوْمِ الْوَقْتِ الْمَعْلُوْمِ',
		ayahNumber: 81,
		translationId: 'sampai pada hari yang telah ditentukan waktunya (hari Kiamat).”',
	),
	Ayah(
		ayahId: 4052,
		ayahText: 'قَالَ فَبِعِزَّتِكَ لَاُغْوِيَنَّهُمْ اَجْمَعِيْنَۙ',
		ayahNumber: 82,
		translationId: '(Iblis) menjawab, “Demi kemuliaan-Mu, pasti aku akan menyesatkan mereka semuanya,',
	),
	Ayah(
		ayahId: 4053,
		ayahText: 'اِلَّا عِبَادَكَ مِنْهُمُ الْمُخْلَصِيْنَ',
		ayahNumber: 83,
		translationId: 'kecuali hamba-hamba-Mu yang terpilih di antara mereka.”',
	),
	Ayah(
		ayahId: 4054,
		ayahText: 'قَالَ فَالْحَقُّۖ وَالْحَقَّ اَقُوْلُۚ',
		ayahNumber: 84,
		translationId: '(Allah) berfirman, “Maka yang benar (adalah sumpahku), dan hanya kebenaran itulah yang Aku katakan.',
	),
	Ayah(
		ayahId: 4055,
		ayahText: 'لَاَمْلَئَنَّ جَهَنَّمَ مِنْكَ وَمِمَّنْ تَبِعَكَ مِنْهُمْ اَجْمَعِيْنَ',
		ayahNumber: 85,
		translationId: 'Sungguh, Aku akan memenuhi neraka Jahanam dengan kamu dan dengan orang-orang yang mengikutimu di antara mereka semuanya.”',
	),
	Ayah(
		ayahId: 4056,
		ayahText: 'قُلْ مَآ اَسْـَٔلُكُمْ عَلَيْهِ مِنْ اَجْرٍ وَّمَآ اَنَا۠ مِنَ الْمُتَكَلِّفِيْنَ',
		ayahNumber: 86,
		translationId: 'Katakanlah (Muhammad), “Aku tidak meminta imbalan sedikit pun kepadamu atasnya (dakwahku); dan aku bukanlah termasuk orang yang mengada-ada.',
	),
	Ayah(
		ayahId: 4057,
		ayahText: 'اِنْ هُوَ اِلَّا ذِكْرٌ لِّلْعٰلَمِيْنَ',
		ayahNumber: 87,
		translationId: "(Al-Qur'an) ini tidak lain hanyalah peringatan bagi seluruh alam.",
	),
	Ayah(
		ayahId: 4058,
		ayahText: 'وَلَتَعْلَمُنَّ نَبَاَهٗ بَعْدَ حِيْنٍ ࣖ',
		ayahNumber: 88,
		translationId: "Dan sungguh, kamu akan mengetahui (kebenaran) beritanya (Al-Qur'an) setelah beberapa waktu lagi.”",
	),
];
