// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah50 = [
	Ayah(
		ayahId: 4631,
		ayahText: ' قۤ  ۗوَالْقُرْاٰنِ الْمَجِيْدِ  ۖ ',
		ayahNumber: 1,
		translationId: "Qaf. Demi Al-Qur'an yang mulia. ",
	),
	Ayah(
		ayahId: 4632,
		ayahText: 'بَلْ عَجِبُوْٓا اَنْ جَاۤءَهُمْ مُّنْذِرٌ مِّنْهُمْ فَقَالَ الْكٰفِرُوْنَ هٰذَا شَيْءٌ عَجِيْبٌ ۚ',
		ayahNumber: 2,
		translationId: '(Mereka tidak menerimanya) bahkan mereka tercengang karena telah datang kepada mereka seorang pemberi peringatan dari (kalangan) mereka sendiri, maka berkatalah orang-orang kafir, “Ini adalah suatu yang sangat ajaib.” ',
	),
	Ayah(
		ayahId: 4633,
		ayahText: 'ءَاِذَا مِتْنَا وَكُنَّا تُرَابًا ۚ ذٰلِكَ رَجْعٌۢ بَعِيْدٌ ',
		ayahNumber: 3,
		translationId: 'Apakah apabila kami telah mati dan sudah menjadi tanah (akan kembali lagi)? Itu adalah suatu pengembalian yang tidak mungkin. ',
	),
	Ayah(
		ayahId: 4634,
		ayahText: 'قَدْ عَلِمْنَا مَا تَنْقُصُ الْاَرْضُ مِنْهُمْ ۚوَعِنْدَنَا كِتٰبٌ حَفِيْظٌ ',
		ayahNumber: 4,
		translationId: 'Sungguh, Kami telah mengetahui apa yang ditelan bumi dari (tubuh) mereka, sebab pada Kami ada kitab (catatan) yang terpelihara baik. ',
	),
	Ayah(
		ayahId: 4635,
		ayahText: 'بَلْ كَذَّبُوْا بِالْحَقِّ لَمَّا جَاۤءَهُمْ فَهُمْ فِيْٓ اَمْرٍ مَّرِيْجٍ ',
		ayahNumber: 5,
		translationId: 'Bahkan mereka telah mendustakan kebenaran ketika (kebenaran itu) datang kepada mereka, maka mereka berada dalam keadaan kacau balau. ',
	),
	Ayah(
		ayahId: 4636,
		ayahText: 'اَفَلَمْ يَنْظُرُوْٓا اِلَى السَّمَاۤءِ فَوْقَهُمْ كَيْفَ بَنَيْنٰهَا وَزَيَّنّٰهَا وَمَا لَهَا مِنْ فُرُوْجٍ ',
		ayahNumber: 6,
		translationId: 'Maka tidakkah mereka memperhatikan langit yang ada di atas mereka, bagaimana cara Kami membangunnya dan menghiasinya dan tidak terdapat retak-retak sedikit pun? ',
	),
	Ayah(
		ayahId: 4637,
		ayahText: 'وَالْاَرْضَ مَدَدْنٰهَا وَاَلْقَيْنَا فِيْهَا رَوَاسِيَ وَاَنْۢبَتْنَا فِيْهَا مِنْ كُلِّ زَوْجٍۢ بَهِيْجٍۙ ',
		ayahNumber: 7,
		translationId: 'Dan bumi yang Kami hamparkan dan Kami pancangkan di atasnya gunung-gunung yang kokoh dan Kami tumbuhkan di atasnya tanam-tanaman yang indah, ',
	),
	Ayah(
		ayahId: 4638,
		ayahText: 'تَبْصِرَةً وَّذِكْرٰى لِكُلِّ عَبْدٍ مُّنِيْبٍ ',
		ayahNumber: 8,
		translationId: 'untuk menjadi pelajaran dan peringatan bagi setiap hamba yang kembali (tunduk kepada Allah). ',
	),
	Ayah(
		ayahId: 4639,
		ayahText: 'وَنَزَّلْنَا مِنَ السَّمَاۤءِ مَاۤءً مُّبٰرَكًا فَاَنْۢبَتْنَا بِهٖ جَنّٰتٍ وَّحَبَّ الْحَصِيْدِۙ',
		ayahNumber: 9,
		translationId: 'Dan dari langit Kami turunkan air yang memberi berkah lalu Kami tumbuhkan dengan (air) itu pepohonan yang rindang dan biji-bijian yang dapat dipanen. ',
	),
	Ayah(
		ayahId: 4640,
		ayahText: 'وَالنَّخْلَ بٰسِقٰتٍ لَّهَا طَلْعٌ نَّضِيْدٌۙ',
		ayahNumber: 10,
		translationId: 'Dan pohon kurma yang tinggi-tinggi yang mempunyai mayang yang bersusun-susun, ',
	),
	Ayah(
		ayahId: 4641,
		ayahText: 'رِّزْقًا لِّلْعِبَادِۙ وَاَحْيَيْنَا بِهٖ بَلْدَةً مَّيْتًاۗ  كَذٰلِكَ الْخُرُوْجُ  ',
		ayahNumber: 11,
		translationId: '(sebagai) rezeki bagi hamba-hamba (Kami), dan Kami hidupkan dengan (air) itu negeri yang mati (tandus). Seperti itulah terjadinya kebangkitan (dari kubur). ',
	),
	Ayah(
		ayahId: 4642,
		ayahText: 'كَذَّبَتْ قَبْلَهُمْ قَوْمُ نُوْحٍ وَّاَصْحٰبُ الرَّسِّ وَثَمُوْدُ ',
		ayahNumber: 12,
		translationId: 'Sebelum mereka, kaum Nuh, penduduk Rass dan Samud telah mendustakan (rasul-rasul), ',
	),
	Ayah(
		ayahId: 4643,
		ayahText: 'وَعَادٌ وَّفِرْعَوْنُ وَاِخْوَانُ لُوْطٍۙ',
		ayahNumber: 13,
		translationId: 'dan (demikian juga) kaum  ‘Ad, kaum Fir‘aun dan kaum Lut, ',
	),
	Ayah(
		ayahId: 4644,
		ayahText: 'وَّاَصْحٰبُ الْاَيْكَةِ وَقَوْمُ تُبَّعٍۗ كُلٌّ كَذَّبَ الرُّسُلَ فَحَقَّ وَعِيْدِ',
		ayahNumber: 14,
		translationId: 'dan (juga) penduduk Aikah serta kaum Tubba‘. Semuanya telah mendustakan rasul-rasul maka berlakulah ancaman-Ku (atas mereka). ',
	),
	Ayah(
		ayahId: 4645,
		ayahText: 'اَفَعَيِيْنَا بِالْخَلْقِ الْاَوَّلِۗ بَلْ هُمْ فِيْ لَبْسٍ مِّنْ خَلْقٍ جَدِيْدٍ ࣖ',
		ayahNumber: 15,
		translationId: 'Maka apakah Kami letih dengan penciptaan yang pertama? (Sama sekali tidak) bahkan mereka dalam keadaan ragu-ragu tentang penciptaan yang baru. ',
	),
	Ayah(
		ayahId: 4646,
		ayahText: 'وَلَقَدْ خَلَقْنَا الْاِنْسَانَ وَنَعْلَمُ مَا تُوَسْوِسُ بِهٖ نَفْسُهٗ ۖوَنَحْنُ اَقْرَبُ اِلَيْهِ مِنْ حَبْلِ الْوَرِيْدِ ',
		ayahNumber: 16,
		translationId: 'Dan sungguh, Kami telah menciptakan manusia dan mengetahui apa yang dibisikkan oleh hatinya, dan Kami lebih dekat kepadanya daripada urat lehernya. ',
	),
	Ayah(
		ayahId: 4647,
		ayahText: 'اِذْ يَتَلَقَّى الْمُتَلَقِّيٰنِ عَنِ الْيَمِيْنِ وَعَنِ الشِّمَالِ قَعِيْدٌ ',
		ayahNumber: 17,
		translationId: '(Ingatlah) ketika dua malaikat mencatat (perbuatannya), yang satu duduk di sebelah kanan dan yang lain di sebelah kiri. ',
	),
	Ayah(
		ayahId: 4648,
		ayahText: 'مَا يَلْفِظُ مِنْ قَوْلٍ اِلَّا لَدَيْهِ رَقِيْبٌ عَتِيْدٌ ',
		ayahNumber: 18,
		translationId: 'Tidak ada suatu kata yang diucapkannya melainkan ada di sisinya malaikat pengawas yang selalu siap (mencatat). ',
	),
	Ayah(
		ayahId: 4649,
		ayahText: 'وَجَاۤءَتْ سَكْرَةُ الْمَوْتِ بِالْحَقِّ ۗذٰلِكَ مَا كُنْتَ مِنْهُ تَحِيْدُ',
		ayahNumber: 19,
		translationId: 'Dan datanglah sakaratul maut dengan sebenar-benarnya. Itulah yang dahulu hendak kamu hindari. ',
	),
	Ayah(
		ayahId: 4650,
		ayahText: 'وَنُفِخَ فِى الصُّوْرِۗ ذٰلِكَ يَوْمُ الْوَعِيْدِ ',
		ayahNumber: 20,
		translationId: 'Dan ditiuplah sangkakala. Itulah hari yang diancamkan. ',
	),
	Ayah(
		ayahId: 4651,
		ayahText: 'وَجَاۤءَتْ كُلُّ نَفْسٍ مَّعَهَا سَاۤىِٕقٌ وَّشَهِيْدٌ ',
		ayahNumber: 21,
		translationId: 'Setiap orang akan datang bersama (malaikat) penggiring dan (malaikat) saksi. ',
	),
	Ayah(
		ayahId: 4652,
		ayahText: 'لَقَدْ كُنْتَ فِيْ غَفْلَةٍ مِّنْ هٰذَا فَكَشَفْنَا عَنْكَ غِطَاۤءَكَ فَبَصَرُكَ الْيَوْمَ حَدِيْدٌ ',
		ayahNumber: 22,
		translationId: 'Sungguh, kamu dahulu lalai tentang (peristiwa) ini, maka Kami singkapkan tutup (yang menutupi) matamu, sehingga penglihatanmu pada hari ini sangat tajam. ',
	),
	Ayah(
		ayahId: 4653,
		ayahText: 'وَقَالَ قَرِيْنُهٗ هٰذَا مَا لَدَيَّ عَتِيْدٌۗ',
		ayahNumber: 23,
		translationId: 'Dan (malaikat) yang menyertainya berkata, “Inilah (catatan perbuatan) yang ada padaku.” ',
	),
	Ayah(
		ayahId: 4654,
		ayahText: 'اَلْقِيَا فِيْ جَهَنَّمَ كُلَّ كَفَّارٍ عَنِيْدٍ ',
		ayahNumber: 24,
		translationId: '(Allah berfirman), “Lemparkanlah olehmu berdua ke dalam neraka Jahanam semua orang yang sangat ingkar dan keras kepala, ',
	),
	Ayah(
		ayahId: 4655,
		ayahText: 'مَنَّاعٍ لِّلْخَيْرِ مُعْتَدٍ مُّرِيْبٍۙ',
		ayahNumber: 25,
		translationId: 'yang sangat enggan melakukan kebajikan, melampaui batas dan bersikap ragu-ragu, ',
	),
	Ayah(
		ayahId: 4656,
		ayahText: ' ۨالَّذِيْ جَعَلَ مَعَ اللّٰهِ اِلٰهًا اٰخَرَ فَاَلْقِيٰهُ فِى الْعَذَابِ الشَّدِيْدِ ',
		ayahNumber: 26,
		translationId: 'yang mempersekutukan Allah dengan tuhan lain, maka lemparkanlah dia ke dalam azab yang keras.” ',
	),
	Ayah(
		ayahId: 4657,
		ayahText: '۞ قَالَ قَرِيْنُهٗ رَبَّنَا مَآ اَطْغَيْتُهٗ وَلٰكِنْ كَانَ فِيْ ضَلٰلٍۢ بَعِيْدٍ ',
		ayahNumber: 27,
		translationId: '(Setan) yang menyertainya berkata (pula), “Ya Tuhan kami, aku tidak menyesatkannya tetapi dia sendiri yang berada dalam kesesatan yang jauh.” ',
	),
	Ayah(
		ayahId: 4658,
		ayahText: 'قَالَ لَا تَخْتَصِمُوْا لَدَيَّ وَقَدْ قَدَّمْتُ اِلَيْكُمْ بِالْوَعِيْدِ ',
		ayahNumber: 28,
		translationId: '(Allah) berfirman, “Janganlah kamu bertengkar di hadapan-Ku, dan sungguh, dahulu Aku telah memberikan ancaman kepadamu. ',
	),
	Ayah(
		ayahId: 4659,
		ayahText: 'مَا يُبَدَّلُ الْقَوْلُ لَدَيَّ وَمَآ اَنَا۠ بِظَلَّامٍ لِّلْعَبِيْدِ ࣖ ',
		ayahNumber: 29,
		translationId: 'Keputusan-Ku tidak dapat diubah dan Aku tidak menzalimi hamba-hamba-Ku.” ',
	),
	Ayah(
		ayahId: 4660,
		ayahText: 'يَوْمَ نَقُوْلُ لِجَهَنَّمَ هَلِ امْتَلَـْٔتِ وَتَقُوْلُ هَلْ مِنْ مَّزِيْدٍ ',
		ayahNumber: 30,
		translationId: '(Ingatlah) pada hari (ketika) Kami bertanya kepada Jahanam, “Apakah kamu sudah penuh?”  Ia menjawab, “Masih adakah tambahan?” ',
	),
	Ayah(
		ayahId: 4661,
		ayahText: 'وَاُزْلِفَتِ الْجَنَّةُ لِلْمُتَّقِيْنَ غَيْرَ بَعِيْدٍ ',
		ayahNumber: 31,
		translationId: 'Sedangkan surga didekatkan kepada orang-orang yang bertakwa pada tempat yang tidak jauh (dari mereka). ',
	),
	Ayah(
		ayahId: 4662,
		ayahText: 'هٰذَا مَا تُوْعَدُوْنَ لِكُلِّ اَوَّابٍ حَفِيْظٍۚ',
		ayahNumber: 32,
		translationId: '(Kepada mereka dikatakan), “Inilah nikmat yang dijanjikan kepadamu, (yaitu) kepada setiap hamba yang senantiasa bertobat (kepada Allah) dan memelihara (semua peraturan-peraturan-Nya). ',
	),
	Ayah(
		ayahId: 4663,
		ayahText: 'مَنْ خَشِيَ الرَّحْمٰنَ بِالْغَيْبِ وَجَاۤءَ بِقَلْبٍ مُّنِيْبٍۙ',
		ayahNumber: 33,
		translationId: '(Yaitu) orang yang takut kepada Allah Yang Maha Pengasih sekalipun tidak kelihatan (olehnya) dan dia datang dengan hati yang bertobat, ',
	),
	Ayah(
		ayahId: 4664,
		ayahText: ' ۨادْخُلُوْهَا بِسَلٰمٍ ۗذٰلِكَ يَوْمُ الْخُلُوْدِ ',
		ayahNumber: 34,
		translationId: 'masuklah ke (dalam surga) dengan aman dan damai. Itulah hari yang abadi.” ',
	),
	Ayah(
		ayahId: 4665,
		ayahText: 'لَهُمْ مَّا يَشَاۤءُوْنَ فِيْهَا وَلَدَيْنَا مَزِيْدٌ ',
		ayahNumber: 35,
		translationId: 'Mereka di dalamnya memperoleh apa yang mereka kehendaki, dan pada Kami ada tambahannya. ',
	),
	Ayah(
		ayahId: 4666,
		ayahText: 'وَكَمْ اَهْلَكْنَا قَبْلَهُمْ مِّنْ قَرْنٍ هُمْ اَشَدُّ مِنْهُمْ بَطْشًا فَنَقَّبُوْا فِى الْبِلَادِۗ هَلْ مِنْ مَّحِيْصٍ ',
		ayahNumber: 36,
		translationId: 'Dan betapa banyak umat yang telah Kami binasakan sebelum mereka, (padahal) mereka lebih hebat kekuatannya daripada mereka (umat yang belakangan) ini. Mereka pernah menjelajah di beberapa negeri. Adakah tempat pelarian (dari kebinasaan bagi mereka)? ',
	),
	Ayah(
		ayahId: 4667,
		ayahText: 'اِنَّ فِيْ ذٰلِكَ لَذِكْرٰى لِمَنْ كَانَ لَهٗ قَلْبٌ اَوْ اَلْقَى السَّمْعَ وَهُوَ شَهِيْدٌ ',
		ayahNumber: 37,
		translationId: 'Sungguh, pada yang demikian itu pasti terdapat peringatan bagi orang-orang yang mempunyai hati atau yang menggunakan pendengarannya, sedang dia menyaksikannya. ',
	),
	Ayah(
		ayahId: 4668,
		ayahText: 'وَلَقَدْ خَلَقْنَا السَّمٰوٰتِ وَالْاَرْضَ وَمَا بَيْنَهُمَا فِيْ سِتَّةِ اَيَّامٍۖ وَّمَا مَسَّنَا مِنْ لُّغُوْبٍ ',
		ayahNumber: 38,
		translationId: 'Dan sungguh, Kami telah menciptakan langit dan bumi dan apa yang ada antara keduanya dalam enam masa, dan Kami tidak merasa letih sedikit pun. ',
	),
	Ayah(
		ayahId: 4669,
		ayahText: 'فَاصْبِرْ عَلٰى مَا يَقُوْلُوْنَ وَسَبِّحْ بِحَمْدِ رَبِّكَ قَبْلَ طُلُوْعِ الشَّمْسِ وَقَبْلَ الْغُرُوْبِ ',
		ayahNumber: 39,
		translationId: 'Maka bersabarlah engkau (Muhammad) terhadap apa yang mereka katakan dan bertasbihlah dengan memuji Tuhanmu sebelum matahari terbit dan sebelum terbenam. ',
	),
	Ayah(
		ayahId: 4670,
		ayahText: 'وَمِنَ الَّيْلِ فَسَبِّحْهُ وَاَدْبَارَ السُّجُوْدِ ',
		ayahNumber: 40,
		translationId: 'Dan bertasbihlah kepada-Nya pada malam hari dan setiap selesai salat. ',
	),
	Ayah(
		ayahId: 4671,
		ayahText: 'وَاسْتَمِعْ يَوْمَ يُنَادِ الْمُنَادِ مِنْ مَّكَانٍ قَرِيْبٍ ',
		ayahNumber: 41,
		translationId: 'Dan dengarkanlah (seruan) pada hari (ketika) penyeru (malaikat) menyeru dari tempat yang dekat. ',
	),
	Ayah(
		ayahId: 4672,
		ayahText: 'يَوْمَ يَسْمَعُوْنَ الصَّيْحَةَ بِالْحَقِّ ۗذٰلِكَ يَوْمُ الْخُرُوْجِ ',
		ayahNumber: 42,
		translationId: '(Yaitu) pada hari (ketika) mereka men-dengar suara dahsyat dengan sebenarnya. Itulah hari keluar (dari kubur). ',
	),
	Ayah(
		ayahId: 4673,
		ayahText: 'اِنَّا نَحْنُ نُحْيٖ وَنُمِيْتُ وَاِلَيْنَا الْمَصِيْرُۙ',
		ayahNumber: 43,
		translationId: 'Sungguh, Kami yang menghidupkan dan mematikan dan kepada Kami tempat kembali (semua makhluk). ',
	),
	Ayah(
		ayahId: 4674,
		ayahText: 'يَوْمَ تَشَقَّقُ الْاَرْضُ عَنْهُمْ سِرَاعًا ۗذٰلِكَ حَشْرٌ عَلَيْنَا يَسِيْرٌ ',
		ayahNumber: 44,
		translationId: '(Yaitu) pada hari (ketika) bumi terbelah, mereka keluar dengan cepat. Yang demikian itu adalah pengumpulan yang mudah bagi Kami. ',
	),
	Ayah(
		ayahId: 4675,
		ayahText: 'نَحْنُ اَعْلَمُ بِمَا يَقُوْلُوْنَ وَمَآ اَنْتَ عَلَيْهِمْ بِجَبَّارٍۗ فَذَكِّرْ بِالْقُرْاٰنِ مَنْ يَّخَافُ وَعِيْدِ ࣖ ',
		ayahNumber: 45,
		translationId: "Kami lebih mengetahui tentang apa yang mereka katakan, dan engkau (Muhammad) bukanlah seorang pemaksa terhadap mereka. Maka berilah peringatan dengan Al-Qur'an kepada siapa pun yang takut kepada ancaman-Ku. ",
	),
];
