// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah56 = [
	Ayah(
		ayahId: 4980,
		ayahText: 'اِذَا وَقَعَتِ الْوَاقِعَةُۙ ',
		ayahNumber: 1,
		translationId: 'Apabila terjadi hari Kiamat,',
	),
	Ayah(
		ayahId: 4981,
		ayahText: 'لَيْسَ لِوَقْعَتِهَا كَاذِبَةٌ  ۘ ',
		ayahNumber: 2,
		translationId: 'terjadinya tidak dapat didustakan (disangkal).',
	),
	Ayah(
		ayahId: 4982,
		ayahText: 'خَافِضَةٌ رَّافِعَةٌ ',
		ayahNumber: 3,
		translationId: '(Kejadian itu) merendahkan (satu golongan) dan meninggikan (golongan yang lain).',
	),
	Ayah(
		ayahId: 4983,
		ayahText: 'اِذَا رُجَّتِ الْاَرْضُ رَجًّاۙ ',
		ayahNumber: 4,
		translationId: 'Apabila bumi diguncangkan sedahsyat-dahsyatnya,',
	),
	Ayah(
		ayahId: 4984,
		ayahText: 'وَّبُسَّتِ الْجِبَالُ بَسًّاۙ  ',
		ayahNumber: 5,
		translationId: 'dan gunung-gunung dihancurluluhkan sehancur-hancurnya,',
	),
	Ayah(
		ayahId: 4985,
		ayahText: 'فَكَانَتْ هَبَاۤءً مُّنْۢبَثًّاۙ ',
		ayahNumber: 6,
		translationId: 'maka jadilah ia debu yang beterbangan,',
	),
	Ayah(
		ayahId: 4986,
		ayahText: 'وَّكُنْتُمْ اَزْوَاجًا ثَلٰثَةً ۗ',
		ayahNumber: 7,
		translationId: 'dan kamu menjadi tiga golongan,',
	),
	Ayah(
		ayahId: 4987,
		ayahText: 'فَاَصْحٰبُ الْمَيْمَنَةِ ەۙ مَآ اَصْحٰبُ الْمَيْمَنَةِ ۗ',
		ayahNumber: 8,
		translationId: 'yaitu golongan kanan, alangkah mulianya golongan kanan itu,',
	),
	Ayah(
		ayahId: 4988,
		ayahText: 'وَاَصْحٰبُ الْمَشْـَٔمَةِ ەۙ مَآ اَصْحٰبُ الْمَشْـَٔمَةِ ۗ',
		ayahNumber: 9,
		translationId: 'dan golongan kiri, alangkah sengsaranya golongan kiri itu,',
	),
	Ayah(
		ayahId: 4989,
		ayahText: 'وَالسّٰبِقُوْنَ السّٰبِقُوْنَۙ  ',
		ayahNumber: 10,
		translationId: 'dan orang-orang yang paling dahulu (beriman), merekalah yang paling dahulu (masuk surga).',
	),
	Ayah(
		ayahId: 4990,
		ayahText: 'اُولٰۤىِٕكَ الْمُقَرَّبُوْنَۚ ',
		ayahNumber: 11,
		translationId: 'Mereka itulah orang yang dekat (kepada Allah),',
	),
	Ayah(
		ayahId: 4991,
		ayahText: 'فِيْ جَنّٰتِ النَّعِيْمِ ',
		ayahNumber: 12,
		translationId: 'Berada dalam surga kenikmatan,',
	),
	Ayah(
		ayahId: 4992,
		ayahText: 'ثُلَّةٌ مِّنَ الْاَوَّلِيْنَۙ  ',
		ayahNumber: 13,
		translationId: 'segolongan besar dari orang-orang yang terdahulu,',
	),
	Ayah(
		ayahId: 4993,
		ayahText: 'وَقَلِيْلٌ مِّنَ الْاٰخِرِيْنَۗ  ',
		ayahNumber: 14,
		translationId: 'dan segolongan kecil dari orang-orang yang kemudian.',
	),
	Ayah(
		ayahId: 4994,
		ayahText: 'عَلٰى سُرُرٍ مَّوْضُوْنَةٍۙ  ',
		ayahNumber: 15,
		translationId: 'Mereka berada di atas dipan-dipan yang bertahtakan emas dan permata,',
	),
	Ayah(
		ayahId: 4995,
		ayahText: 'مُّتَّكِـِٕيْنَ عَلَيْهَا مُتَقٰبِلِيْنَ',
		ayahNumber: 16,
		translationId: 'mereka bersandar di atasnya berhadap-hadapan.',
	),
	Ayah(
		ayahId: 4996,
		ayahText: 'يَطُوْفُ عَلَيْهِمْ وِلْدَانٌ مُّخَلَّدُوْنَۙ  ',
		ayahNumber: 17,
		translationId: 'Mereka dikelilingi oleh anak-anak muda yang tetap muda,',
	),
	Ayah(
		ayahId: 4997,
		ayahText: 'بِاَكْوَابٍ وَّاَبَارِيْقَۙ وَكَأْسٍ مِّنْ مَّعِيْنٍۙ  ',
		ayahNumber: 18,
		translationId: 'dengan membawa gelas, cerek dan sloki (piala) berisi minuman yang diambil dari air yang mengalir,',
	),
	Ayah(
		ayahId: 4998,
		ayahText: 'لَّا يُصَدَّعُوْنَ عَنْهَا وَلَا يُنْزِفُوْنَۙ  ',
		ayahNumber: 19,
		translationId: 'mereka tidak pening karenanya dan tidak pula mabuk,',
	),
	Ayah(
		ayahId: 4999,
		ayahText: 'وَفَاكِهَةٍ مِّمَّا يَتَخَيَّرُوْنَۙ  ',
		ayahNumber: 20,
		translationId: 'dan buah-buahan apa pun yang mereka pilih,',
	),
	Ayah(
		ayahId: 5000,
		ayahText: 'وَلَحْمِ طَيْرٍ مِّمَّا يَشْتَهُوْنَۗ  ',
		ayahNumber: 21,
		translationId: 'dan daging burung apa pun yang mereka inginkan.',
	),
	Ayah(
		ayahId: 5001,
		ayahText: 'وَحُوْرٌ عِيْنٌۙ  ',
		ayahNumber: 22,
		translationId: 'Dan ada bidadari-bidadari yang bermata indah,',
	),
	Ayah(
		ayahId: 5002,
		ayahText: 'كَاَمْثَالِ اللُّؤْلُؤِ الْمَكْنُوْنِۚ  ',
		ayahNumber: 23,
		translationId: 'laksana mutiara yang tersimpan baik.',
	),
	Ayah(
		ayahId: 5003,
		ayahText: 'جَزَاۤءًۢ بِمَا كَانُوْا يَعْمَلُوْنَ',
		ayahNumber: 24,
		translationId: 'Sebagai balasan atas apa yang mereka kerjakan.',
	),
	Ayah(
		ayahId: 5004,
		ayahText: 'لَا يَسْمَعُوْنَ فِيْهَا لَغْوًا وَّلَا تَأْثِيْمًاۙ  ',
		ayahNumber: 25,
		translationId: 'Di sana mereka tidak mendengar percakapan yang sia-sia maupun yang menimbulkan dosa,',
	),
	Ayah(
		ayahId: 5005,
		ayahText: 'اِلَّا قِيْلًا سَلٰمًا سَلٰمًا ',
		ayahNumber: 26,
		translationId: 'tetapi mereka mendengar ucapan salam.',
	),
	Ayah(
		ayahId: 5006,
		ayahText: 'وَاَصْحٰبُ الْيَمِينِ ەۙ مَآ اَصْحٰبُ الْيَمِيْنِۗ',
		ayahNumber: 27,
		translationId: 'Dan golongan kanan, siapakah golongan kanan itu.',
	),
	Ayah(
		ayahId: 5007,
		ayahText: 'فِيْ سِدْرٍ مَّخْضُوْدٍۙ  ',
		ayahNumber: 28,
		translationId: '(Mereka) berada di antara pohon bidara yang tidak berduri,',
	),
	Ayah(
		ayahId: 5008,
		ayahText: 'وَّطَلْحٍ مَّنْضُوْدٍۙ  ',
		ayahNumber: 29,
		translationId: 'dan pohon pisang yang bersusun-susun (buahnya),',
	),
	Ayah(
		ayahId: 5009,
		ayahText: 'وَّظِلٍّ مَّمْدُوْدٍۙ  ',
		ayahNumber: 30,
		translationId: 'dan naungan yang terbentang luas,',
	),
	Ayah(
		ayahId: 5010,
		ayahText: 'وَّمَاۤءٍ مَّسْكُوْبٍۙ  ',
		ayahNumber: 31,
		translationId: 'dan air yang mengalir terus-menerus,',
	),
	Ayah(
		ayahId: 5011,
		ayahText: 'وَّفَاكِهَةٍ كَثِيْرَةٍۙ  ',
		ayahNumber: 32,
		translationId: 'dan buah-buahan yang banyak,',
	),
	Ayah(
		ayahId: 5012,
		ayahText: 'لَّا مَقْطُوْعَةٍ وَّلَا مَمْنُوْعَةٍۙ  ',
		ayahNumber: 33,
		translationId: 'yang tidak berhenti berbuah dan tidak terlarang mengambilnya,',
	),
	Ayah(
		ayahId: 5013,
		ayahText: 'وَّفُرُشٍ مَّرْفُوْعَةٍۗ  ',
		ayahNumber: 34,
		translationId: 'dan kasur-kasur yang tebal lagi empuk.',
	),
	Ayah(
		ayahId: 5014,
		ayahText: 'اِنَّآ اَنْشَأْنٰهُنَّ اِنْشَاۤءًۙ  ',
		ayahNumber: 35,
		translationId: 'Kami menciptakan mereka (bidadari-bidadari itu) secara langsung,',
	),
	Ayah(
		ayahId: 5015,
		ayahText: 'فَجَعَلْنٰهُنَّ اَبْكَارًاۙ  ',
		ayahNumber: 36,
		translationId: 'lalu Kami jadikan mereka perawan-perawan,',
	),
	Ayah(
		ayahId: 5016,
		ayahText: 'عُرُبًا اَتْرَابًاۙ  ',
		ayahNumber: 37,
		translationId: 'yang penuh cinta (dan) sebaya umurnya,',
	),
	Ayah(
		ayahId: 5017,
		ayahText: 'لِّاَصْحٰبِ الْيَمِيْنِۗ  ࣖ ',
		ayahNumber: 38,
		translationId: 'untuk golongan kanan,',
	),
	Ayah(
		ayahId: 5018,
		ayahText: 'ثُلَّةٌ مِّنَ الْاَوَّلِيْنَۙ  ',
		ayahNumber: 39,
		translationId: 'segolongan besar dari orang-orang yang terdahulu,',
	),
	Ayah(
		ayahId: 5019,
		ayahText: 'وَثُلَّةٌ مِّنَ الْاٰخِرِيْنَۗ  ',
		ayahNumber: 40,
		translationId: 'dan segolongan besar pula dari orang yang kemudian.',
	),
	Ayah(
		ayahId: 5020,
		ayahText: 'وَاَصْحٰبُ الشِّمَالِ ەۙ مَآ اَصْحٰبُ الشِّمَالِۗ',
		ayahNumber: 41,
		translationId: 'Dan golongan kiri, alangkah sengsaranya golongan kiri itu.',
	),
	Ayah(
		ayahId: 5021,
		ayahText: 'فِيْ سَمُوْمٍ وَّحَمِيْمٍۙ  ',
		ayahNumber: 42,
		translationId: '(Mereka) dalam siksaan angin yang sangat panas dan air yang mendidih,',
	),
	Ayah(
		ayahId: 5022,
		ayahText: 'وَّظِلٍّ مِّنْ يَّحْمُوْمٍۙ  ',
		ayahNumber: 43,
		translationId: 'dan naungan asap yang hitam,',
	),
	Ayah(
		ayahId: 5023,
		ayahText: 'لَّا بَارِدٍ وَّلَا كَرِيْمٍ ',
		ayahNumber: 44,
		translationId: 'tidak sejuk dan tidak menyenangkan.',
	),
	Ayah(
		ayahId: 5024,
		ayahText: 'اِنَّهُمْ كَانُوْا قَبْلَ ذٰلِكَ مُتْرَفِيْنَۚ ',
		ayahNumber: 45,
		translationId: 'Sesungguhnya mereka sebelum itu (dahulu) hidup bermewah-mewah,',
	),
	Ayah(
		ayahId: 5025,
		ayahText: 'وَكَانُوْا يُصِرُّوْنَ عَلَى الْحِنْثِ الْعَظِيْمِۚ  ',
		ayahNumber: 46,
		translationId: 'dan mereka terus-menerus mengerjakan dosa yang besar,',
	),
	Ayah(
		ayahId: 5026,
		ayahText: 'وَكَانُوْا يَقُوْلُوْنَ ەۙ اَىِٕذَا مِتْنَا وَكُنَّا تُرَابًا وَّعِظَامًا ءَاِنَّا لَمَبْعُوْثُوْنَۙ',
		ayahNumber: 47,
		translationId: 'dan mereka berkata, “Apabila kami sudah mati, menjadi tanah dan tulang-belulang, apakah kami benar-benar akan dibangkitkan kembali?',
	),
	Ayah(
		ayahId: 5027,
		ayahText: 'اَوَاٰبَاۤؤُنَا الْاَوَّلُوْنَ ',
		ayahNumber: 48,
		translationId: 'Apakah nenek moyang kami yang terdahulu (dibangkitkan pula)?”',
	),
	Ayah(
		ayahId: 5028,
		ayahText: 'قُلْ اِنَّ الْاَوَّلِيْنَ وَالْاٰخِرِيْنَۙ ',
		ayahNumber: 49,
		translationId: 'Katakanlah, “(Ya), sesungguhnya orang-orang yang terdahulu dan yang kemudian,',
	),
	Ayah(
		ayahId: 5029,
		ayahText: 'لَمَجْمُوْعُوْنَۙ اِلٰى مِيْقَاتِ يَوْمٍ مَّعْلُوْمٍ ',
		ayahNumber: 50,
		translationId: 'pasti semua akan dikumpulkan pada waktu tertentu, pada hari yang sudah dimaklumi.',
	),
	Ayah(
		ayahId: 5030,
		ayahText: 'ثُمَّ اِنَّكُمْ اَيُّهَا الضَّاۤ لُّوْنَ الْمُكَذِّبُوْنَۙ  ',
		ayahNumber: 51,
		translationId: 'Kemudian sesungguhnya kamu, wahai orang-orang yang sesat lagi mendustakan!',
	),
	Ayah(
		ayahId: 5031,
		ayahText: 'لَاٰكِلُوْنَ مِنْ شَجَرٍ مِّنْ زَقُّوْمٍۙ  ',
		ayahNumber: 52,
		translationId: 'pasti akan memakan pohon zaqqum,',
	),
	Ayah(
		ayahId: 5032,
		ayahText: 'فَمَالِـُٔوْنَ مِنْهَا الْبُطُوْنَۚ  ',
		ayahNumber: 53,
		translationId: 'maka akan penuh perutmu dengannya.',
	),
	Ayah(
		ayahId: 5033,
		ayahText: 'فَشَارِبُوْنَ عَلَيْهِ مِنَ الْحَمِيْمِۚ  ',
		ayahNumber: 54,
		translationId: 'Setelah itu kamu akan meminum air yang sangat panas.',
	),
	Ayah(
		ayahId: 5034,
		ayahText: 'فَشَارِبُوْنَ شُرْبَ الْهِيْمِۗ  ',
		ayahNumber: 55,
		translationId: 'Maka kamu minum seperti unta (yang sangat haus) minum.',
	),
	Ayah(
		ayahId: 5035,
		ayahText: 'هٰذَا نُزُلُهُمْ يَوْمَ الدِّيْنِۗ  ',
		ayahNumber: 56,
		translationId: 'Itulah hidangan untuk mereka pada hari pembalasan.”',
	),
	Ayah(
		ayahId: 5036,
		ayahText: 'نَحْنُ خَلَقْنٰكُمْ فَلَوْلَا تُصَدِّقُوْنَ ',
		ayahNumber: 57,
		translationId: 'Kami telah menciptakan kamu, mengapa kamu tidak membenarkan (hari berbangkit)?',
	),
	Ayah(
		ayahId: 5037,
		ayahText: 'اَفَرَءَيْتُمْ مَّا تُمْنُوْنَۗ  ',
		ayahNumber: 58,
		translationId: 'Maka adakah kamu perhatikan, tentang (benih manusia) yang kamu pancarkan.',
	),
	Ayah(
		ayahId: 5038,
		ayahText: 'ءَاَنْتُمْ تَخْلُقُوْنَهٗٓ اَمْ نَحْنُ الْخَالِقُوْنَ ',
		ayahNumber: 59,
		translationId: 'Kamukah yang menciptakannya, ataukah Kami penciptanya?',
	),
	Ayah(
		ayahId: 5039,
		ayahText: 'نَحْنُ قَدَّرْنَا بَيْنَكُمُ الْمَوْتَ وَمَا نَحْنُ بِمَسْبُوْقِيْنَۙ  ',
		ayahNumber: 60,
		translationId: 'Kami telah menentukan kematian masing-masing kamu dan Kami tidak lemah,',
	),
	Ayah(
		ayahId: 5040,
		ayahText: 'عَلٰٓى اَنْ نُّبَدِّلَ اَمْثَالَكُمْ وَنُنْشِئَكُمْ فِيْ مَا لَا تَعْلَمُوْنَ',
		ayahNumber: 61,
		translationId: 'untuk menggantikan kamu dengan orang-orang yang seperti kamu (di dunia) dan membangkitkan kamu kelak (di akhirat) dalam keadaan yang tidak kamu ketahui.',
	),
	Ayah(
		ayahId: 5041,
		ayahText: 'وَلَقَدْ عَلِمْتُمُ النَّشْاَةَ الْاُوْلٰى فَلَوْلَا تَذَكَّرُوْنَ ',
		ayahNumber: 62,
		translationId: 'Dan sungguh, kamu telah tahu penciptaan yang pertama, mengapa kamu tidak mengambil pelajaran?',
	),
	Ayah(
		ayahId: 5042,
		ayahText: 'اَفَرَءَيْتُمْ مَّا تَحْرُثُوْنَۗ  ',
		ayahNumber: 63,
		translationId: 'Pernahkah kamu perhatikan benih yang kamu tanam?',
	),
	Ayah(
		ayahId: 5043,
		ayahText: 'ءَاَنْتُمْ تَزْرَعُوْنَهٗٓ اَمْ نَحْنُ الزَّارِعُوْنَ ',
		ayahNumber: 64,
		translationId: 'Kamukah yang menumbuhkannya ataukah Kami yang menumbuhkan?',
	),
	Ayah(
		ayahId: 5044,
		ayahText: 'لَوْ نَشَاۤءُ لَجَعَلْنٰهُ حُطَامًا فَظَلْتُمْ تَفَكَّهُوْنَۙ  ',
		ayahNumber: 65,
		translationId: 'Sekiranya Kami kehendaki, niscaya Kami hancurkan sampai lumat; maka kamu akan heran tercengang,',
	),
	Ayah(
		ayahId: 5045,
		ayahText: 'اِنَّا لَمُغْرَمُوْنَۙ  ',
		ayahNumber: 66,
		translationId: '(sambil berkata), “Sungguh, kami benar-benar menderita kerugian,',
	),
	Ayah(
		ayahId: 5046,
		ayahText: 'بَلْ نَحْنُ مَحْرُوْمُوْنَ ',
		ayahNumber: 67,
		translationId: 'bahkan kami tidak mendapat hasil apa pun.”',
	),
	Ayah(
		ayahId: 5047,
		ayahText: 'اَفَرَءَيْتُمُ الْمَاۤءَ الَّذِيْ تَشْرَبُوْنَۗ  ',
		ayahNumber: 68,
		translationId: 'Pernahkah kamu memperhatikan air yang kamu minum?',
	),
	Ayah(
		ayahId: 5048,
		ayahText: 'ءَاَنْتُمْ اَنْزَلْتُمُوْهُ مِنَ الْمُزْنِ اَمْ نَحْنُ الْمُنْزِلُوْنَ ',
		ayahNumber: 69,
		translationId: 'Kamukah yang menurunkannya dari awan ataukah Kami yang menurunkan?',
	),
	Ayah(
		ayahId: 5049,
		ayahText: 'لَوْ نَشَاۤءُ جَعَلْنٰهُ اُجَاجًا فَلَوْلَا تَشْكُرُوْنَ ',
		ayahNumber: 70,
		translationId: 'Sekiranya Kami menghendaki, niscaya Kami menjadikannya asin, mengapa kamu tidak bersyukur?',
	),
	Ayah(
		ayahId: 5050,
		ayahText: 'اَفَرَءَيْتُمُ النَّارَ الَّتِيْ تُوْرُوْنَۗ  ',
		ayahNumber: 71,
		translationId: 'Maka pernahkah kamu memperhatikan tentang api yang kamu nyalakan (dengan kayu)?',
	),
	Ayah(
		ayahId: 5051,
		ayahText: 'ءَاَنْتُمْ اَنْشَأْتُمْ شَجَرَتَهَآ اَمْ نَحْنُ الْمُنْشِـُٔوْنَ ',
		ayahNumber: 72,
		translationId: 'Kamukah yang menumbuhkan kayu itu ataukah Kami yang menumbuhkan?',
	),
	Ayah(
		ayahId: 5052,
		ayahText: 'نَحْنُ جَعَلْنٰهَا تَذْكِرَةً وَّمَتَاعًا لِّلْمُقْوِيْنَۚ ',
		ayahNumber: 73,
		translationId: 'Kami menjadikannya (api itu) untuk peringatan dan bahan yang berguna bagi musafir.',
	),
	Ayah(
		ayahId: 5053,
		ayahText: 'فَسَبِّحْ بِاسْمِ رَبِّكَ الْعَظِيْمِ ࣖ ',
		ayahNumber: 74,
		translationId: 'Maka bertasbihlah dengan (menyebut) nama Tuhanmu Yang Mahabesar.',
	),
	Ayah(
		ayahId: 5054,
		ayahText: 'فَلَآ اُقْسِمُ بِمَوٰقِعِ النُّجُوْمِ ',
		ayahNumber: 75,
		translationId: 'Lalu Aku bersumpah dengan tempat beredarnya bintang-bintang.',
	),
	Ayah(
		ayahId: 5055,
		ayahText: 'وَاِنَّهٗ لَقَسَمٌ لَّوْ تَعْلَمُوْنَ عَظِيْمٌۙ  ',
		ayahNumber: 76,
		translationId: 'Dan sesungguhnya itu benar-benar sumpah yang besar sekiranya kamu mengetahui,',
	),
	Ayah(
		ayahId: 5056,
		ayahText: 'اِنَّهٗ لَقُرْاٰنٌ كَرِيْمٌۙ  ',
		ayahNumber: 77,
		translationId: "dan (ini) sesungguhnya Al-Qur'an yang sangat mulia,",
	),
	Ayah(
		ayahId: 5057,
		ayahText: 'فِيْ كِتٰبٍ مَّكْنُوْنٍۙ ',
		ayahNumber: 78,
		translationId: 'dalam Kitab yang terpelihara (Lauh Mahfuzh),',
	),
	Ayah(
		ayahId: 5058,
		ayahText: 'لَّا يَمَسُّهٗٓ اِلَّا الْمُطَهَّرُوْنَۙ  ',
		ayahNumber: 79,
		translationId: 'tidak ada yang menyentuhnya selain hamba-hamba yang disucikan.',
	),
	Ayah(
		ayahId: 5059,
		ayahText: 'تَنْزِيْلٌ مِّنْ رَّبِّ الْعٰلَمِيْنَ ',
		ayahNumber: 80,
		translationId: 'Diturunkan dari Tuhan seluruh alam.',
	),
	Ayah(
		ayahId: 5060,
		ayahText: 'اَفَبِهٰذَا الْحَدِيْثِ اَنْتُمْ مُّدْهِنُوْنَ ',
		ayahNumber: 81,
		translationId: "Apakah kamu menganggap remeh berita ini (Al-Qur'an),",
	),
	Ayah(
		ayahId: 5061,
		ayahText: 'وَتَجْعَلُوْنَ رِزْقَكُمْ اَنَّكُمْ تُكَذِّبُوْنَ ',
		ayahNumber: 82,
		translationId: 'dan kamu menjadikan rezeki yang kamu terima (dari Allah) justru untuk mendustakan(-Nya).',
	),
	Ayah(
		ayahId: 5062,
		ayahText: 'فَلَوْلَآ اِذَا بَلَغَتِ الْحُلْقُوْمَۙ  ',
		ayahNumber: 83,
		translationId: 'Maka kalau begitu mengapa (tidak mencegah) ketika (nyawa) telah sampai di kerongkongan,',
	),
	Ayah(
		ayahId: 5063,
		ayahText: 'وَاَنْتُمْ حِيْنَىِٕذٍ تَنْظُرُوْنَۙ  ',
		ayahNumber: 84,
		translationId: 'dan kamu ketika itu melihat,',
	),
	Ayah(
		ayahId: 5064,
		ayahText: 'وَنَحْنُ اَقْرَبُ اِلَيْهِ مِنْكُمْ وَلٰكِنْ لَّا تُبْصِرُوْنَ ',
		ayahNumber: 85,
		translationId: 'dan Kami lebih dekat kepadanya daripada kamu, tetapi kamu tidak melihat,',
	),
	Ayah(
		ayahId: 5065,
		ayahText: 'فَلَوْلَآ اِنْ كُنْتُمْ غَيْرَ مَدِيْنِيْنَۙ  ',
		ayahNumber: 86,
		translationId: 'maka mengapa jika kamu memang tidak dikuasai (oleh Allah),',
	),
	Ayah(
		ayahId: 5066,
		ayahText: 'تَرْجِعُوْنَهَآ اِنْ كُنْتُمْ صٰدِقِيْنَ',
		ayahNumber: 87,
		translationId: 'kamu tidak mengembalikannya (nyawa itu) jika kamu orang yang benar?',
	),
	Ayah(
		ayahId: 5067,
		ayahText: 'فَاَمَّآ اِنْ كَانَ مِنَ الْمُقَرَّبِيْنَۙ  ',
		ayahNumber: 88,
		translationId: 'Jika dia (orang yang mati) itu termasuk yang didekatkan (kepada Allah),',
	),
	Ayah(
		ayahId: 5068,
		ayahText: 'فَرَوْحٌ وَّرَيْحَانٌ ەۙ وَّجَنَّتُ نَعِيْمٍ',
		ayahNumber: 89,
		translationId: 'maka dia memperoleh ketenteraman dan rezeki serta surga (yang penuh) kenikmatan.',
	),
	Ayah(
		ayahId: 5069,
		ayahText: 'وَاَمَّآ اِنْ كَانَ مِنْ اَصْحٰبِ الْيَمِيْنِۙ  ',
		ayahNumber: 90,
		translationId: 'Dan adapun jika dia termasuk golongan kanan,',
	),
	Ayah(
		ayahId: 5070,
		ayahText: 'فَسَلٰمٌ لَّكَ مِنْ اَصْحٰبِ الْيَمِيْنِۗ  ',
		ayahNumber: 91,
		translationId: 'maka, “Salam bagimu (wahai) dari golongan kanan!” (sambut malaikat).',
	),
	Ayah(
		ayahId: 5071,
		ayahText: 'وَاَمَّآ اِنْ كَانَ مِنَ الْمُكَذِّبِيْنَ الضَّاۤلِّيْنَۙ  ',
		ayahNumber: 92,
		translationId: 'Dan adapun jika dia termasuk golongan orang yang mendustakan dan sesat,',
	),
	Ayah(
		ayahId: 5072,
		ayahText: 'فَنُزُلٌ مِّنْ حَمِيْمٍۙ  ',
		ayahNumber: 93,
		translationId: 'maka dia disambut siraman air yang mendidih,',
	),
	Ayah(
		ayahId: 5073,
		ayahText: 'وَّتَصْلِيَةُ جَحِيْمٍ ',
		ayahNumber: 94,
		translationId: 'dan dibakar di dalam neraka.',
	),
	Ayah(
		ayahId: 5074,
		ayahText: 'اِنَّ هٰذَا لَهُوَ حَقُّ الْيَقِيْنِۚ  ',
		ayahNumber: 95,
		translationId: 'Sungguh, inilah keyakinan yang benar.',
	),
	Ayah(
		ayahId: 5075,
		ayahText: 'فَسَبِّحْ بِاسْمِ رَبِّكَ الْعَظِيْمِ ࣖ ',
		ayahNumber: 96,
		translationId: 'Maka bertasbihlah dengan (menyebut) nama Tuhanmu Yang Mahabesar.',
	),
];
