// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah55 = [
	Ayah(
		ayahId: 4902,
		ayahText: 'اَلرَّحْمٰنُۙ  ',
		ayahNumber: 1,
		translationId: '(Allah) Yang Maha Pengasih,',
	),
	Ayah(
		ayahId: 4903,
		ayahText: 'عَلَّمَ الْقُرْاٰنَۗ ',
		ayahNumber: 2,
		translationId: "Yang telah mengajarkan Al-Qur'an.",
	),
	Ayah(
		ayahId: 4904,
		ayahText: 'خَلَقَ الْاِنْسَانَۙ ',
		ayahNumber: 3,
		translationId: 'Dia menciptakan manusia, ',
	),
	Ayah(
		ayahId: 4905,
		ayahText: 'عَلَّمَهُ الْبَيَانَ ',
		ayahNumber: 4,
		translationId: 'mengajarnya pandai berbicara.',
	),
	Ayah(
		ayahId: 4906,
		ayahText: 'اَلشَّمْسُ وَالْقَمَرُ بِحُسْبَانٍۙ ',
		ayahNumber: 5,
		translationId: 'Matahari dan bulan beredar menurut perhitungan,',
	),
	Ayah(
		ayahId: 4907,
		ayahText: 'وَّالنَّجْمُ وَالشَّجَرُ يَسْجُدَانِ ',
		ayahNumber: 6,
		translationId: 'dan tetumbuhan dan pepohonan, keduanya tunduk (kepada-Nya). ',
	),
	Ayah(
		ayahId: 4908,
		ayahText: 'وَالسَّمَاۤءَ رَفَعَهَا وَوَضَعَ الْمِيْزَانَۙ  ',
		ayahNumber: 7,
		translationId: 'Dan langit telah ditinggikan-Nya dan Dia ciptakan keseimbangan,',
	),
	Ayah(
		ayahId: 4909,
		ayahText: 'اَلَّا تَطْغَوْا فِى الْمِيْزَانِ ',
		ayahNumber: 8,
		translationId: 'agar kamu jangan merusak keseimbangan itu, ',
	),
	Ayah(
		ayahId: 4910,
		ayahText: 'وَاَقِيْمُوا الْوَزْنَ بِالْقِسْطِ وَلَا تُخْسِرُوا الْمِيْزَانَ ',
		ayahNumber: 9,
		translationId: 'dan tegakkanlah keseimbangan itu dengan adil dan janganlah kamu mengurangi keseimbangan itu. ',
	),
	Ayah(
		ayahId: 4911,
		ayahText: 'وَالْاَرْضَ وَضَعَهَا لِلْاَنَامِۙ  ',
		ayahNumber: 10,
		translationId: 'Dan bumi telah dibentangkan-Nya untuk makhluk(-Nya), ',
	),
	Ayah(
		ayahId: 4912,
		ayahText: 'فِيْهَا فَاكِهَةٌ وَّالنَّخْلُ ذَاتُ الْاَكْمَامِۖ  ',
		ayahNumber: 11,
		translationId: 'di dalamnya ada buah-buahan dan pohon kurma yang mempunyai kelopak mayang, ',
	),
	Ayah(
		ayahId: 4913,
		ayahText: 'وَالْحَبُّ ذُو الْعَصْفِ وَالرَّيْحَانُۚ  ',
		ayahNumber: 12,
		translationId: 'dan biji-bijian yang berkulit dan bunga-bunga yang harum baunya. ',
	),
	Ayah(
		ayahId: 4914,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِ ',
		ayahNumber: 13,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan? ',
	),
	Ayah(
		ayahId: 4915,
		ayahText: 'خَلَقَ الْاِنْسَانَ مِنْ صَلْصَالٍ كَالْفَخَّارِ ',
		ayahNumber: 14,
		translationId: 'Dia menciptakan manusia dari tanah kering seperti tembikar,',
	),
	Ayah(
		ayahId: 4916,
		ayahText: 'وَخَلَقَ الْجَاۤنَّ مِنْ مَّارِجٍ مِّنْ نَّارٍۚ  ',
		ayahNumber: 15,
		translationId: 'dan Dia menciptakan jin dari nyala api tanpa asap.',
	),
	Ayah(
		ayahId: 4917,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِ ',
		ayahNumber: 16,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4918,
		ayahText: 'رَبُّ الْمَشْرِقَيْنِ وَرَبُّ الْمَغْرِبَيْنِۚ ',
		ayahNumber: 17,
		translationId: 'Tuhan (yang memelihara) dua timur dan Tuhan (yang memelihara) dua barat.',
	),
	Ayah(
		ayahId: 4919,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِ ',
		ayahNumber: 18,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4920,
		ayahText: 'مَرَجَ الْبَحْرَيْنِ يَلْتَقِيٰنِۙ',
		ayahNumber: 19,
		translationId: 'Dia membiarkan dua laut mengalir yang (kemudian) keduanya bertemu, ',
	),
	Ayah(
		ayahId: 4921,
		ayahText: 'بَيْنَهُمَا بَرْزَخٌ لَّا يَبْغِيٰنِۚ',
		ayahNumber: 20,
		translationId: 'di antara keduanya ada batas yang tidak dilampaui oleh masing-masing.',
	),
	Ayah(
		ayahId: 4922,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِ ',
		ayahNumber: 21,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4923,
		ayahText: 'يَخْرُجُ مِنْهُمَا اللُّؤْلُؤُ وَالْمَرْجَانُۚ',
		ayahNumber: 22,
		translationId: 'Dari keduanya keluar mutiara dan marjan.',
	),
	Ayah(
		ayahId: 4924,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِ ',
		ayahNumber: 23,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan? ',
	),
	Ayah(
		ayahId: 4925,
		ayahText: 'وَلَهُ الْجَوَارِ الْمُنْشَاٰتُ فِى الْبَحْرِ كَالْاَعْلَامِۚ  ',
		ayahNumber: 24,
		translationId: 'Milik-Nyalah kapal-kapal yang berlayar di lautan bagaikan gunung-gunung.',
	),
	Ayah(
		ayahId: 4926,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِ ࣖ ',
		ayahNumber: 25,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan? ',
	),
	Ayah(
		ayahId: 4927,
		ayahText: 'كُلُّ مَنْ عَلَيْهَا فَانٍۖ  ',
		ayahNumber: 26,
		translationId: 'Semua yang ada di bumi itu akan binasa, ',
	),
	Ayah(
		ayahId: 4928,
		ayahText: 'وَّيَبْقٰى وَجْهُ رَبِّكَ ذُو الْجَلٰلِ وَالْاِكْرَامِۚ  ',
		ayahNumber: 27,
		translationId: 'tetapi wajah Tuhanmu yang memiliki kebesaran dan kemuliaan tetap kekal. ',
	),
	Ayah(
		ayahId: 4929,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِ ',
		ayahNumber: 28,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4930,
		ayahText: 'يَسْـَٔلُهٗ مَنْ فِى السَّمٰوٰتِ وَالْاَرْضِۗ  كُلَّ يَوْمٍ هُوَ فِيْ شَأْنٍۚ',
		ayahNumber: 29,
		translationId: 'Apa yang di langit dan di bumi selalu meminta kepada-Nya. Setiap waktu Dia dalam kesibukan. ',
	),
	Ayah(
		ayahId: 4931,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِ ',
		ayahNumber: 30,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4932,
		ayahText: 'سَنَفْرُغُ لَكُمْ اَيُّهَ الثَّقَلٰنِۚ  ',
		ayahNumber: 31,
		translationId: 'Kami akan memberi perhatian sepenuhnya kepadamu wahai (golongan) manusia dan jin! ',
	),
	Ayah(
		ayahId: 4933,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِ ',
		ayahNumber: 32,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4934,
		ayahText: 'يٰمَعْشَرَ الْجِنِّ وَالْاِنْسِ اِنِ اسْتَطَعْتُمْ اَنْ تَنْفُذُوْا مِنْ اَقْطَارِ السَّمٰوٰتِ وَالْاَرْضِ فَانْفُذُوْاۗ  لَا تَنْفُذُوْنَ اِلَّا بِسُلْطٰنٍۚ ',
		ayahNumber: 33,
		translationId: 'Wahai golongan jin dan manusia! Jika kamu sanggup menembus (melintasi) penjuru langit dan bumi, maka tembuslah. Kamu tidak akan mampu menembusnya kecuali dengan kekuatan (dari Allah). ',
	),
	Ayah(
		ayahId: 4935,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِ ',
		ayahNumber: 34,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4936,
		ayahText: 'يُرْسَلُ عَلَيْكُمَا شُوَاظٌ مِّنْ نَّارٍۙ وَّنُحَاسٌ فَلَا تَنْتَصِرَانِۚ ',
		ayahNumber: 35,
		translationId: 'Kepada kamu (jin dan manusia), akan dikirim nyala api dan cairan tembaga (panas) sehingga kamu tidak dapat menyelamatkan diri (darinya).',
	),
	Ayah(
		ayahId: 4937,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِ ',
		ayahNumber: 36,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4938,
		ayahText: 'فَاِذَا انْشَقَّتِ السَّمَاۤءُ فَكَانَتْ وَرْدَةً كَالدِّهَانِۚ ',
		ayahNumber: 37,
		translationId: 'Maka apabila langit telah terbelah dan menjadi merah mawar seperti (kilauan) minyak. ',
	),
	Ayah(
		ayahId: 4939,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِ ',
		ayahNumber: 38,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4940,
		ayahText: 'فَيَوْمَئِذٍ لَّا يُسْـَٔلُ عَنْ ذَنْۢبِهٖٓ اِنْسٌ وَّلَا جَاۤنٌّۚ  ',
		ayahNumber: 39,
		translationId: 'Maka pada hari itu manusia dan jin tidak ditanya tentang dosanya. ',
	),
	Ayah(
		ayahId: 4941,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِ  ',
		ayahNumber: 40,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4942,
		ayahText: 'يُعْرَفُ الْمُجْرِمُوْنَ بِسِيْمٰهُمْ فَيُؤْخَذُ بِالنَّوَاصِيْ وَالْاَقْدَامِۚ  ',
		ayahNumber: 41,
		translationId: 'Orang-orang yang berdosa itu diketahui dengan tanda-tandanya, lalu direnggut ubun-ubun dan kakinya.',
	),
	Ayah(
		ayahId: 4943,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِ ',
		ayahNumber: 42,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4944,
		ayahText: 'هٰذِهٖ جَهَنَّمُ الَّتِيْ يُكَذِّبُ بِهَا الْمُجْرِمُوْنَۘ ',
		ayahNumber: 43,
		translationId: 'Inilah neraka Jahanam yang didustakan oleh orang-orang yang berdosa.',
	),
	Ayah(
		ayahId: 4945,
		ayahText: 'يَطُوْفُوْنَ بَيْنَهَا وَبَيْنَ حَمِيْمٍ اٰنٍۚ  ',
		ayahNumber: 44,
		translationId: 'Mereka berkeliling di sana dan di antara air yang mendidih. ',
	),
	Ayah(
		ayahId: 4946,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِ ࣖ',
		ayahNumber: 45,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4947,
		ayahText: 'وَلِمَنْ خَافَ مَقَامَ رَبِّهٖ جَنَّتٰنِۚ',
		ayahNumber: 46,
		translationId: 'Dan bagi siapa yang takut akan saat menghadap Tuhannya ada dua surga.',
	),
	Ayah(
		ayahId: 4948,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِۙ ',
		ayahNumber: 47,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4949,
		ayahText: 'ذَوَاتَآ اَفْنَانٍۚ ',
		ayahNumber: 48,
		translationId: 'kedua surga itu mempunyai aneka pepohonan dan buah-buahan.',
	),
	Ayah(
		ayahId: 4950,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِ ',
		ayahNumber: 49,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4951,
		ayahText: 'فِيْهِمَا عَيْنٰنِ تَجْرِيٰنِۚ ',
		ayahNumber: 50,
		translationId: 'Di dalam kedua surga itu ada dua buah mata air yang memancar.',
	),
	Ayah(
		ayahId: 4952,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِ ',
		ayahNumber: 51,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4953,
		ayahText: 'فِيْهِمَا مِنْ كُلِّ فَاكِهَةٍ زَوْجٰنِۚ ',
		ayahNumber: 52,
		translationId: 'Di dalam kedua surga itu terdapat aneka buah-buahan yang berpasang-pasangan. ',
	),
	Ayah(
		ayahId: 4954,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِۚ ',
		ayahNumber: 53,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4955,
		ayahText: 'مُتَّكِـِٕيْنَ عَلٰى فُرُشٍۢ بَطَاۤىِٕنُهَا مِنْ اِسْتَبْرَقٍۗ وَجَنَا الْجَنَّتَيْنِ دَانٍۚ ',
		ayahNumber: 54,
		translationId: 'Mereka bersandar di atas permadani yang bagian dalamnya dari sutera tebal. Dan buah-buahan di kedua surga itu dapat (dipetik) dari dekat. ',
	),
	Ayah(
		ayahId: 4956,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِ ',
		ayahNumber: 55,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4957,
		ayahText: 'فِيْهِنَّ قٰصِرٰتُ الطَّرْفِۙ لَمْ يَطْمِثْهُنَّ اِنْسٌ قَبْلَهُمْ وَلَا جَاۤنٌّۚ  ',
		ayahNumber: 56,
		translationId: 'Di dalam surga itu ada bidadari-bidadari yang membatasi pandangan, yang tidak pernah disentuh oleh manusia maupun jin sebelumnya. ',
	),
	Ayah(
		ayahId: 4958,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِۚ ',
		ayahNumber: 57,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4959,
		ayahText: 'كَاَنَّهُنَّ الْيَاقُوْتُ وَالْمَرْجَانُۚ ',
		ayahNumber: 58,
		translationId: 'Seakan-akan mereka itu permata yakut dan marjan. ',
	),
	Ayah(
		ayahId: 4960,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِ',
		ayahNumber: 59,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4961,
		ayahText: 'هَلْ جَزَاۤءُ الْاِحْسَانِ اِلَّا الْاِحْسَانُۚ ',
		ayahNumber: 60,
		translationId: 'Tidak ada balasan untuk kebaikan selain kebaikan (pula).',
	),
	Ayah(
		ayahId: 4962,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِ ',
		ayahNumber: 61,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4963,
		ayahText: 'وَمِنْ دُوْنِهِمَا جَنَّتٰنِۚ ',
		ayahNumber: 62,
		translationId: 'Dan selain dari dua surga itu ada dua surga lagi.',
	),
	Ayah(
		ayahId: 4964,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِۙ ',
		ayahNumber: 63,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan,',
	),
	Ayah(
		ayahId: 4965,
		ayahText: 'مُدْهَاۤمَّتٰنِۚ  ',
		ayahNumber: 64,
		translationId: 'kedua surga itu (kelihatan) hijau tua warnanya.',
	),
	Ayah(
		ayahId: 4966,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِ ',
		ayahNumber: 65,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4967,
		ayahText: 'فِيْهِمَا عَيْنٰنِ نَضَّاخَتٰنِۚ ',
		ayahNumber: 66,
		translationId: 'Di dalam keduanya (surga itu) ada dua buah mata air yang memancar.',
	),
	Ayah(
		ayahId: 4968,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِۚ  ',
		ayahNumber: 67,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4969,
		ayahText: 'فِيْهِمَا فَاكِهَةٌ وَّنَخْلٌ وَّرُمَّانٌۚ  ',
		ayahNumber: 68,
		translationId: 'Di dalam kedua surga itu ada buah-buahan, kurma dan delima.',
	),
	Ayah(
		ayahId: 4970,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِۚ ',
		ayahNumber: 69,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4971,
		ayahText: 'فِيْهِنَّ خَيْرٰتٌ حِسَانٌۚ  ',
		ayahNumber: 70,
		translationId: 'Di dalam surga-surga itu ada bidadari-bidadari yang baik-baik dan jelita.',
	),
	Ayah(
		ayahId: 4972,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِۚ ',
		ayahNumber: 71,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4973,
		ayahText: 'حُوْرٌ مَّقْصُوْرٰتٌ فِى الْخِيَامِۚ  ',
		ayahNumber: 72,
		translationId: 'Bidadari-bidadari yang dipelihara di dalam kemah-kemah.',
	),
	Ayah(
		ayahId: 4974,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِۚ  ',
		ayahNumber: 73,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4975,
		ayahText: 'لَمْ يَطْمِثْهُنَّ اِنْسٌ قَبْلَهُمْ وَلَا جَاۤنٌّۚ  ',
		ayahNumber: 74,
		translationId: 'Mereka tidak pernah disentuh oleh manusia maupun oleh jin sebelumnya.',
	),
	Ayah(
		ayahId: 4976,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِۚ  ',
		ayahNumber: 75,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4977,
		ayahText: 'مُتَّكِـِٕيْنَ عَلٰى رَفْرَفٍ خُضْرٍ وَّعَبْقَرِيٍّ حِسَانٍۚ  ',
		ayahNumber: 76,
		translationId: 'Mereka bersandar pada bantal-bantal yang hijau dan permadani-permadani yang indah.',
	),
	Ayah(
		ayahId: 4978,
		ayahText: 'فَبِاَيِّ اٰلَاۤءِ رَبِّكُمَا تُكَذِّبٰنِۚ ',
		ayahNumber: 77,
		translationId: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
	),
	Ayah(
		ayahId: 4979,
		ayahText: 'تَبٰرَكَ اسْمُ رَبِّكَ ذِى الْجَلٰلِ وَالْاِكْرَامِ ࣖ ',
		ayahNumber: 78,
		translationId: 'Mahasuci nama Tuhanmu Pemilik Keagungan dan Kemuliaan.',
	),
];
