// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah75 = [
	Ayah(
		ayahId: 5552,
		ayahText: 'لَآ اُقْسِمُ بِيَوْمِ الْقِيٰمَةِۙ',
		ayahNumber: 1,
		translationId: 'Aku bersumpah dengan hari Kiamat,',
	),
	Ayah(
		ayahId: 5553,
		ayahText: 'وَلَآ اُقْسِمُ بِالنَّفْسِ اللَّوَّامَةِ ',
		ayahNumber: 2,
		translationId: 'dan aku bersumpah demi jiwa yang selalu menyesali (dirinya sendiri).',
	),
	Ayah(
		ayahId: 5554,
		ayahText: 'اَيَحْسَبُ الْاِنْسَانُ اَلَّنْ نَّجْمَعَ عِظَامَهٗ ۗ',
		ayahNumber: 3,
		translationId: 'Apakah manusia mengira bahwa Kami tidak akan mengumpulkan (kembali) tulang-belulangnya?',
	),
	Ayah(
		ayahId: 5555,
		ayahText: 'بَلٰى قَادِرِيْنَ عَلٰٓى اَنْ نُّسَوِّيَ بَنَانَهٗ ',
		ayahNumber: 4,
		translationId: '(Bahkan) Kami mampu menyusun (kembali) jari-jemarinya dengan sempurna. ',
	),
	Ayah(
		ayahId: 5556,
		ayahText: 'بَلْ يُرِيْدُ الْاِنْسَانُ لِيَفْجُرَ اَمَامَهٗۚ',
		ayahNumber: 5,
		translationId: 'Tetapi manusia hendak membuat maksiat terus-menerus. ',
	),
	Ayah(
		ayahId: 5557,
		ayahText: 'يَسْـَٔلُ اَيَّانَ يَوْمُ الْقِيٰمَةِۗ',
		ayahNumber: 6,
		translationId: 'Dia bertanya, “Kapankah hari Kiamat itu?”',
	),
	Ayah(
		ayahId: 5558,
		ayahText: 'فَاِذَا بَرِقَ الْبَصَرُۙ',
		ayahNumber: 7,
		translationId: 'Maka apabila mata terbelalak (ketakutan), ',
	),
	Ayah(
		ayahId: 5559,
		ayahText: 'وَخَسَفَ الْقَمَرُۙ',
		ayahNumber: 8,
		translationId: 'dan bulan pun telah hilang cahayanya,',
	),
	Ayah(
		ayahId: 5560,
		ayahText: 'وَجُمِعَ الشَّمْسُ وَالْقَمَرُۙ',
		ayahNumber: 9,
		translationId: 'lalu matahari dan bulan dikumpulkan, ',
	),
	Ayah(
		ayahId: 5561,
		ayahText: 'يَقُوْلُ الْاِنْسَانُ يَوْمَىِٕذٍ اَيْنَ الْمَفَرُّۚ',
		ayahNumber: 10,
		translationId: 'pada hari itu manusia berkata, “Ke mana tempat lari?”',
	),
	Ayah(
		ayahId: 5562,
		ayahText: 'كَلَّا لَا وَزَرَۗ',
		ayahNumber: 11,
		translationId: 'Tidak! Tidak ada tempat berlindung!',
	),
	Ayah(
		ayahId: 5563,
		ayahText: 'اِلٰى رَبِّكَ يَوْمَىِٕذِ ِۨالْمُسْتَقَرُّۗ',
		ayahNumber: 12,
		translationId: 'Hanya kepada Tuhanmu tempat kembali pada hari itu.',
	),
	Ayah(
		ayahId: 5564,
		ayahText: 'يُنَبَّؤُا الْاِنْسَانُ يَوْمَىِٕذٍۢ بِمَا قَدَّمَ وَاَخَّرَۗ',
		ayahNumber: 13,
		translationId: 'Pada hari itu diberitakan kepada manusia apa yang telah dikerjakannya dan apa yang dilalaikannya.',
	),
	Ayah(
		ayahId: 5565,
		ayahText: 'بَلِ الْاِنْسَانُ عَلٰى نَفْسِهٖ بَصِيْرَةٌۙ',
		ayahNumber: 14,
		translationId: 'Bahkan manusia menjadi saksi atas dirinya sendiri,',
	),
	Ayah(
		ayahId: 5566,
		ayahText: 'وَّلَوْ اَلْقٰى مَعَاذِيْرَهٗۗ',
		ayahNumber: 15,
		translationId: 'dan meskipun dia mengemukakan alasan-alasannya.',
	),
	Ayah(
		ayahId: 5567,
		ayahText: 'لَا تُحَرِّكْ بِهٖ لِسَانَكَ لِتَعْجَلَ بِهٖۗ',
		ayahNumber: 16,
		translationId: "Jangan engkau (Muhammad) gerakkan lidahmu (untuk membaca Al-Qur'an) karena hendak cepat-cepat (menguasai)nya.",
	),
	Ayah(
		ayahId: 5568,
		ayahText: 'اِنَّ عَلَيْنَا جَمْعَهٗ وَقُرْاٰنَهٗ ۚ',
		ayahNumber: 17,
		translationId: 'Sesungguhnya Kami yang akan mengumpulkannya (di dadamu) dan membacakannya. ',
	),
	Ayah(
		ayahId: 5569,
		ayahText: 'فَاِذَا قَرَأْنٰهُ فَاتَّبِعْ قُرْاٰنَهٗ ۚ',
		ayahNumber: 18,
		translationId: 'Apabila Kami telah selesai membacakannya maka ikutilah bacaannya itu. ',
	),
	Ayah(
		ayahId: 5570,
		ayahText: 'ثُمَّ اِنَّ عَلَيْنَا بَيَانَهٗ ۗ',
		ayahNumber: 19,
		translationId: 'Kemudian sesungguhnya Kami yang akan menjelaskannya. ',
	),
	Ayah(
		ayahId: 5571,
		ayahText: 'كَلَّا بَلْ تُحِبُّوْنَ الْعَاجِلَةَۙ',
		ayahNumber: 20,
		translationId: 'Tidak! Bahkan kamu mencintai kehidupan dunia, ',
	),
	Ayah(
		ayahId: 5572,
		ayahText: 'وَتَذَرُوْنَ الْاٰخِرَةَۗ',
		ayahNumber: 21,
		translationId: 'dan mengabaikan (kehidupan) akhirat. ',
	),
	Ayah(
		ayahId: 5573,
		ayahText: 'وُجُوْهٌ يَّوْمَىِٕذٍ نَّاضِرَةٌۙ',
		ayahNumber: 22,
		translationId: 'Wajah-wajah (orang mukmin) pada hari itu berseri-seri,',
	),
	Ayah(
		ayahId: 5574,
		ayahText: 'اِلٰى رَبِّهَا نَاظِرَةٌ ۚ',
		ayahNumber: 23,
		translationId: 'memandang Tuhannya. ',
	),
	Ayah(
		ayahId: 5575,
		ayahText: 'وَوُجُوْهٌ يَّوْمَىِٕذٍۢ بَاسِرَةٌۙ',
		ayahNumber: 24,
		translationId: 'Dan wajah-wajah (orang kafir) pada hari itu muram, ',
	),
	Ayah(
		ayahId: 5576,
		ayahText: 'تَظُنُّ اَنْ يُّفْعَلَ بِهَا فَاقِرَةٌ ۗ',
		ayahNumber: 25,
		translationId: 'mereka yakin bahwa akan ditimpakan kepadanya malapetaka yang sangat dahsyat.',
	),
	Ayah(
		ayahId: 5577,
		ayahText: 'كَلَّآ اِذَا بَلَغَتِ التَّرَاقِيَۙ',
		ayahNumber: 26,
		translationId: 'Tidak! Apabila (nyawa) telah sampai ke kerongkongan,',
	),
	Ayah(
		ayahId: 5578,
		ayahText: 'وَقِيْلَ مَنْ ۜرَاقٍۙ',
		ayahNumber: 27,
		translationId: 'dan dikatakan (kepadanya), “Siapa yang dapat menyembuhkan?”',
	),
	Ayah(
		ayahId: 5579,
		ayahText: 'وَّظَنَّ اَنَّهُ الْفِرَاقُۙ',
		ayahNumber: 28,
		translationId: 'Dan dia yakin bahwa itulah waktu perpisahan (dengan dunia), ',
	),
	Ayah(
		ayahId: 5580,
		ayahText: 'وَالْتَفَّتِ السَّاقُ بِالسَّاقِۙ',
		ayahNumber: 29,
		translationId: 'dan bertaut betis (kiri) dengan betis (kanan),',
	),
	Ayah(
		ayahId: 5581,
		ayahText: 'اِلٰى رَبِّكَ يَوْمَىِٕذِ ِۨالْمَسَاقُ ۗ ࣖ',
		ayahNumber: 30,
		translationId: 'kepada Tuhanmulah pada hari itu kamu dihalau. ',
	),
	Ayah(
		ayahId: 5582,
		ayahText: 'فَلَا صَدَّقَ وَلَا صَلّٰىۙ',
		ayahNumber: 31,
		translationId: "Karena dia (dahulu) tidak mau membenarkan (Al-Qur'an dan Rasul) dan tidak mau melaksanakan salat, ",
	),
	Ayah(
		ayahId: 5583,
		ayahText: 'وَلٰكِنْ كَذَّبَ وَتَوَلّٰىۙ',
		ayahNumber: 32,
		translationId: 'tetapi justru dia mendustakan (Rasul) dan berpaling (dari kebenaran), ',
	),
	Ayah(
		ayahId: 5584,
		ayahText: 'ثُمَّ ذَهَبَ اِلٰٓى اَهْلِهٖ يَتَمَطّٰىۗ',
		ayahNumber: 33,
		translationId: 'kemudian dia pergi kepada keluarganya dengan sombong.',
	),
	Ayah(
		ayahId: 5585,
		ayahText: 'اَوْلٰى لَكَ فَاَوْلٰىۙ',
		ayahNumber: 34,
		translationId: 'Celakalah kamu! Maka celakalah! ',
	),
	Ayah(
		ayahId: 5586,
		ayahText: 'ثُمَّ اَوْلٰى لَكَ فَاَوْلٰىۗ',
		ayahNumber: 35,
		translationId: 'Sekali lagi, celakalah kamu (manusia)! Maka celakalah! ',
	),
	Ayah(
		ayahId: 5587,
		ayahText: 'اَيَحْسَبُ الْاِنْسَانُ اَنْ يُّتْرَكَ سُدًىۗ',
		ayahNumber: 36,
		translationId: 'Apakah manusia mengira, dia akan dibiarkan begitu saja (tanpa pertanggungjawaban)?',
	),
	Ayah(
		ayahId: 5588,
		ayahText: 'اَلَمْ يَكُ نُطْفَةً مِّنْ مَّنِيٍّ يُّمْنٰى ',
		ayahNumber: 37,
		translationId: 'Bukankah dia mulanya hanya setetes mani yang ditumpahkan (ke dalam rahim), ',
	),
	Ayah(
		ayahId: 5589,
		ayahText: 'ثُمَّ كَانَ عَلَقَةً فَخَلَقَ فَسَوّٰىۙ',
		ayahNumber: 38,
		translationId: 'kemudian (mani itu) menjadi sesuatu yang melekat, lalu Allah menciptakannya dan menyempurnakannya, ',
	),
	Ayah(
		ayahId: 5590,
		ayahText: 'فَجَعَلَ مِنْهُ الزَّوْجَيْنِ الذَّكَرَ وَالْاُنْثٰىۗ',
		ayahNumber: 39,
		translationId: 'lalu Dia menjadikan darinya sepasang laki-laki dan perempuan. ',
	),
	Ayah(
		ayahId: 5591,
		ayahText: 'اَلَيْسَ ذٰلِكَ بِقٰدِرٍ عَلٰٓى اَنْ يُّحْيِ َۧ الْمَوْتٰى ࣖ',
		ayahNumber: 40,
		translationId: 'Bukankah (Allah yang berbuat) demikian berkuasa (pula) menghidupkan orang mati?',
	),
];
