// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah76 = [
	Ayah(
		ayahId: 5592,
		ayahText: 'هَلْ اَتٰى عَلَى الْاِنْسَانِ حِيْنٌ مِّنَ الدَّهْرِ لَمْ يَكُنْ شَيْـًٔا مَّذْكُوْرًا ',
		ayahNumber: 1,
		translationId: 'Bukankah pernah datang kepada manusia waktu dari masa, yang ketika itu belum merupakan sesuatu yang dapat disebut?',
	),
	Ayah(
		ayahId: 5593,
		ayahText: 'اِنَّا خَلَقْنَا الْاِنْسَانَ مِنْ نُّطْفَةٍ اَمْشَاجٍۖ نَّبْتَلِيْهِ فَجَعَلْنٰهُ سَمِيْعًاۢ بَصِيْرًا ',
		ayahNumber: 2,
		translationId: 'Sungguh, Kami telah menciptakan manusia dari setetes mani yang bercampur yang Kami hendak mengujinya (dengan perintah dan larangan), karena itu Kami jadikan dia mendengar dan melihat.',
	),
	Ayah(
		ayahId: 5594,
		ayahText: 'اِنَّا هَدَيْنٰهُ السَّبِيْلَ اِمَّا شَاكِرًا وَّاِمَّا كَفُوْرًا ',
		ayahNumber: 3,
		translationId: 'Sungguh, Kami telah menunjukkan kepadanya jalan yang lurus; ada yang bersyukur dan ada pula yang kufur. ',
	),
	Ayah(
		ayahId: 5595,
		ayahText: 'اِنَّآ اَعْتَدْنَا لِلْكٰفِرِيْنَ سَلٰسِلَا۟ وَاَغْلٰلًا وَّسَعِيْرًا ',
		ayahNumber: 4,
		translationId: 'Sungguh, Kami telah menyediakan bagi orang-orang kafir rantai, belenggu dan neraka yang menyala-nyala. ',
	),
	Ayah(
		ayahId: 5596,
		ayahText: 'اِنَّ الْاَبْرَارَ يَشْرَبُوْنَ مِنْ كَأْسٍ كَانَ مِزَاجُهَا كَافُوْرًاۚ',
		ayahNumber: 5,
		translationId: 'Sungguh, orang-orang yang berbuat kebajikan akan minum dari gelas (berisi minuman) yang campurannya adalah air kafur, ',
	),
	Ayah(
		ayahId: 5597,
		ayahText: 'عَيْنًا يَّشْرَبُ بِهَا عِبَادُ اللّٰهِ يُفَجِّرُوْنَهَا تَفْجِيْرًا ',
		ayahNumber: 6,
		translationId: '(yaitu) mata air (dalam surga) yang diminum oleh hamba-hamba Allah dan mereka dapat memancarkannya dengan sebaik-baiknya.',
	),
	Ayah(
		ayahId: 5598,
		ayahText: 'يُوْفُوْنَ بِالنَّذْرِ وَيَخَافُوْنَ يَوْمًا كَانَ شَرُّهٗ مُسْتَطِيْرًا ',
		ayahNumber: 7,
		translationId: 'Mereka memenuhi nazar dan takut akan suatu hari yang azabnya merata di mana-mana. ',
	),
	Ayah(
		ayahId: 5599,
		ayahText: 'وَيُطْعِمُوْنَ الطَّعَامَ عَلٰى حُبِّهٖ مِسْكِيْنًا وَّيَتِيْمًا وَّاَسِيْرًا ',
		ayahNumber: 8,
		translationId: 'Dan mereka memberikan makanan yang disukainya kepada orang miskin, anak yatim dan orang yang ditawan, ',
	),
	Ayah(
		ayahId: 5600,
		ayahText: 'اِنَّمَا نُطْعِمُكُمْ لِوَجْهِ اللّٰهِ لَا نُرِيْدُ مِنْكُمْ جَزَاۤءً وَّلَا شُكُوْرًا ',
		ayahNumber: 9,
		translationId: '(sambil berkata), “Sesungguhnya kami memberi makanan kepadamu hanyalah karena mengharapkan keridaan Allah, kami tidak mengharap balasan dan terima kasih dari kamu.',
	),
	Ayah(
		ayahId: 5601,
		ayahText: 'اِنَّا نَخَافُ مِنْ رَّبِّنَا يَوْمًا عَبُوْسًا قَمْطَرِيْرًا ',
		ayahNumber: 10,
		translationId: 'Sungguh, kami takut akan (azab) Tuhan pada hari (ketika) orang-orang berwajah masam penuh kesulitan.”',
	),
	Ayah(
		ayahId: 5602,
		ayahText: 'فَوَقٰىهُمُ اللّٰهُ شَرَّ ذٰلِكَ الْيَوْمِ وَلَقّٰىهُمْ نَضْرَةً وَّسُرُوْرًاۚ',
		ayahNumber: 11,
		translationId: 'Maka Allah melindungi mereka dari kesusahan hari itu, dan memberikan kepada mereka keceriaan dan kegembiraan.',
	),
	Ayah(
		ayahId: 5603,
		ayahText: 'وَجَزٰىهُمْ بِمَا صَبَرُوْا جَنَّةً وَّحَرِيْرًاۙ',
		ayahNumber: 12,
		translationId: 'Dan Dia memberi balasan kepada mereka karena kesabarannya (berupa) surga dan (pakaian) sutera.',
	),
	Ayah(
		ayahId: 5604,
		ayahText: 'مُّتَّكِـِٕيْنَ فِيْهَا عَلَى الْاَرَاۤىِٕكِۚ  لَا يَرَوْنَ فِيْهَا شَمْسًا وَّلَا زَمْهَرِيْرًاۚ',
		ayahNumber: 13,
		translationId: 'Di sana mereka duduk bersandar di atas dipan, di sana mereka tidak melihat (merasakan teriknya) matahari dan tidak pula dingin yang berlebihan.',
	),
	Ayah(
		ayahId: 5605,
		ayahText: 'وَدَانِيَةً عَلَيْهِمْ ظِلٰلُهَا وَذُلِّلَتْ قُطُوْفُهَا تَذْلِيْلًا ',
		ayahNumber: 14,
		translationId: 'Dan naungan (pepohonan)nya dekat di atas mereka dan dimudahkan semudah-mudahnya untuk memetik (buah)nya.',
	),
	Ayah(
		ayahId: 5606,
		ayahText: 'وَيُطَافُ عَلَيْهِمْ بِاٰنِيَةٍ مِّنْ فِضَّةٍ وَّاَكْوَابٍ كَانَتْ قَوَارِيْرَا۠ ',
		ayahNumber: 15,
		translationId: 'Dan kepada mereka diedarkan bejana-bejana dari perak dan piala-piala yang bening laksana kristal,',
	),
	Ayah(
		ayahId: 5607,
		ayahText: 'قَوَارِيْرَا۟ مِنْ فِضَّةٍ قَدَّرُوْهَا تَقْدِيْرًا ',
		ayahNumber: 16,
		translationId: 'kristal yang jernih terbuat dari perak, mereka tentukan ukurannya yang sesuai (dengan kehendak mereka). ',
	),
	Ayah(
		ayahId: 5608,
		ayahText: 'وَيُسْقَوْنَ فِيْهَا كَأْسًا كَانَ مِزَاجُهَا زَنْجَبِيْلًاۚ',
		ayahNumber: 17,
		translationId: 'Dan di sana mereka diberi segelas minuman bercampur jahe.',
	),
	Ayah(
		ayahId: 5609,
		ayahText: 'عَيْنًا فِيْهَا تُسَمّٰى سَلْسَبِيْلًا ',
		ayahNumber: 18,
		translationId: '(Yang didatangkan dari) sebuah mata air (di surga) yang dinamakan Salsabil.',
	),
	Ayah(
		ayahId: 5610,
		ayahText: '۞ وَيَطُوْفُ عَلَيْهِمْ وِلْدَانٌ مُّخَلَّدُوْنَۚ اِذَا رَاَيْتَهُمْ حَسِبْتَهُمْ لُؤْلُؤًا مَّنْثُوْرًا',
		ayahNumber: 19,
		translationId: 'Dan mereka dikelilingi oleh para pemuda yang tetap muda. Apabila kamu melihatnya, akan kamu kira mereka, mutiara yang bertaburan.',
	),
	Ayah(
		ayahId: 5611,
		ayahText: 'وَاِذَا رَاَيْتَ ثَمَّ رَاَيْتَ نَعِيْمًا وَّمُلْكًا كَبِيْرًا ',
		ayahNumber: 20,
		translationId: 'Dan apabila engkau melihat (keadaan) di sana (surga), niscaya engkau akan melihat berbagai macam kenikmatan dan kerajaan yang besar.',
	),
	Ayah(
		ayahId: 5612,
		ayahText: 'عٰلِيَهُمْ ثِيَابُ سُنْدُسٍ خُضْرٌ وَّاِسْتَبْرَقٌۖ وَّحُلُّوْٓا اَسَاوِرَ مِنْ فِضَّةٍۚ وَسَقٰىهُمْ رَبُّهُمْ شَرَابًا طَهُوْرًا ',
		ayahNumber: 21,
		translationId: 'Mereka berpakaian sutera halus yang hijau dan sutera tebal dan memakai gelang terbuat dari perak, dan Tuhan memberikan kepada mereka minuman yang bersih (dan suci).',
	),
	Ayah(
		ayahId: 5613,
		ayahText: 'اِنَّ هٰذَا كَانَ لَكُمْ جَزَاۤءً وَّكَانَ سَعْيُكُمْ مَّشْكُوْرًا ࣖ ',
		ayahNumber: 22,
		translationId: 'Inilah balasan untukmu, dan segala usahamu diterima dan diakui (Allah).',
	),
	Ayah(
		ayahId: 5614,
		ayahText: 'اِنَّا نَحْنُ نَزَّلْنَا عَلَيْكَ الْقُرْاٰنَ تَنْزِيْلًاۚ',
		ayahNumber: 23,
		translationId: "Sesungguhnya Kamilah yang menurunkan Al-Qur'an kepadamu (Muhammad) secara berangsur-angsur.",
	),
	Ayah(
		ayahId: 5615,
		ayahText: 'فَاصْبِرْ لِحُكْمِ رَبِّكَ وَلَا تُطِعْ مِنْهُمْ اٰثِمًا اَوْ كَفُوْرًاۚ',
		ayahNumber: 24,
		translationId: 'Maka bersabarlah untuk (melaksanakan) ketetapan Tuhanmu, dan janganlah engkau ikuti orang yang berdosa dan orang yang kafir di antara mereka.',
	),
	Ayah(
		ayahId: 5616,
		ayahText: 'وَاذْكُرِ اسْمَ رَبِّكَ بُكْرَةً وَّاَصِيْلًاۚ',
		ayahNumber: 25,
		translationId: 'Dan sebutlah nama Tuhanmu pada (waktu) pagi dan petang.',
	),
	Ayah(
		ayahId: 5617,
		ayahText: 'وَمِنَ الَّيْلِ فَاسْجُدْ لَهٗ وَسَبِّحْهُ لَيْلًا طَوِيْلًا ',
		ayahNumber: 26,
		translationId: 'Dan pada sebagian dari malam, maka bersujudlah kepada-Nya dan bertasbihlah kepada-Nya pada bagian yang panjang di malam hari.',
	),
	Ayah(
		ayahId: 5618,
		ayahText: 'اِنَّ هٰٓؤُلَاۤءِ يُحِبُّوْنَ الْعَاجِلَةَ وَيَذَرُوْنَ وَرَاۤءَهُمْ يَوْمًا ثَقِيْلًا ',
		ayahNumber: 27,
		translationId: 'Sesungguhnya mereka (orang kafir) itu mencintai kehidupan (dunia) dan meninggalkan hari yang berat (hari akhirat) di belakangnya.',
	),
	Ayah(
		ayahId: 5619,
		ayahText: 'نَحْنُ خَلَقْنٰهُمْ وَشَدَدْنَآ اَسْرَهُمْۚ وَاِذَا شِئْنَا بَدَّلْنَآ اَمْثَالَهُمْ تَبْدِيْلًا ',
		ayahNumber: 28,
		translationId: 'Kami telah menciptakan mereka dan menguatkan persendian tubuh mereka. Tetapi, jika Kami menghendaki, Kami dapat mengganti dengan yang serupa mereka.',
	),
	Ayah(
		ayahId: 5620,
		ayahText: 'اِنَّ هٰذِهٖ تَذْكِرَةٌ ۚ فَمَنْ شَاۤءَ اتَّخَذَ اِلٰى رَبِّهٖ سَبِيْلًا ',
		ayahNumber: 29,
		translationId: 'Sungguh, (ayat-ayat) ini adalah peringatan, maka barangsiapa menghendaki (kebaikan bagi dirinya) tentu dia mengambil jalan menuju kepada Tuhannya.',
	),
	Ayah(
		ayahId: 5621,
		ayahText: 'وَمَا تَشَاۤءُوْنَ اِلَّآ اَنْ يَّشَاۤءَ اللّٰهُ ۗاِنَّ اللّٰهَ كَانَ عَلِيْمًا حَكِيْمًاۖ',
		ayahNumber: 30,
		translationId: 'Tetapi kamu tidak mampu (menempuh jalan itu), kecuali apabila Allah kehendaki Allah. Sungguh, Allah Maha Mengetahui, Mahabijaksana. ',
	),
	Ayah(
		ayahId: 5622,
		ayahText: 'يُّدْخِلُ مَنْ يَّشَاۤءُ فِيْ رَحْمَتِهٖۗ وَالظّٰلِمِيْنَ اَعَدَّ لَهُمْ عَذَابًا اَلِيْمًا ࣖ',
		ayahNumber: 31,
		translationId: 'Dia memasukkan siapa pun yang Dia kehendaki ke dalam rahmat-Nya (surga). Adapun bagi orang-orang zalim disediakan-Nya azab yang pedih.',
	),
];
