// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah52 = [
	Ayah(
		ayahId: 4736,
		ayahText: 'وَالطُّوْرِۙ  ',
		ayahNumber: 1,
		translationId: 'Demi gunung (Sinai),',
	),
	Ayah(
		ayahId: 4737,
		ayahText: 'وَكِتٰبٍ مَّسْطُوْرٍۙ  ',
		ayahNumber: 2,
		translationId: 'dan demi Kitab yang ditulis, ',
	),
	Ayah(
		ayahId: 4738,
		ayahText: 'فِيْ رَقٍّ مَّنْشُوْرٍۙ  ',
		ayahNumber: 3,
		translationId: 'pada lembaran yang terbuka,',
	),
	Ayah(
		ayahId: 4739,
		ayahText: 'وَّالْبَيْتِ الْمَعْمُوْرِۙ  ',
		ayahNumber: 4,
		translationId: 'demi Baitulma‘mur (Ka‘bah),',
	),
	Ayah(
		ayahId: 4740,
		ayahText: 'وَالسَّقْفِ الْمَرْفُوْعِۙ  ',
		ayahNumber: 5,
		translationId: 'demi atap yang ditinggikan (langit),',
	),
	Ayah(
		ayahId: 4741,
		ayahText: 'وَالْبَحْرِ الْمَسْجُوْرِۙ ',
		ayahNumber: 6,
		translationId: 'demi lautan yang penuh gelombang, ',
	),
	Ayah(
		ayahId: 4742,
		ayahText: 'اِنَّ عَذَابَ رَبِّكَ لَوَاقِعٌۙ  ',
		ayahNumber: 7,
		translationId: 'sungguh, azab Tuhanmu pasti terjadi, ',
	),
	Ayah(
		ayahId: 4743,
		ayahText: 'مَّا لَهٗ مِنْ دَافِعٍۙ  ',
		ayahNumber: 8,
		translationId: 'tidak sesuatu pun yang dapat menolaknya, ',
	),
	Ayah(
		ayahId: 4744,
		ayahText: 'يَّوْمَ تَمُوْرُ السَّمَاۤءُ مَوْرًاۙ ',
		ayahNumber: 9,
		translationId: 'pada hari (ketika) langit berguncang sekeras-kerasnya,',
	),
	Ayah(
		ayahId: 4745,
		ayahText: 'وَّتَسِيْرُ الْجِبَالُ سَيْرًاۗ  ',
		ayahNumber: 10,
		translationId: 'dan gunung berjalan (berpindah-pindah).',
	),
	Ayah(
		ayahId: 4746,
		ayahText: 'فَوَيْلٌ يَّوْمَىِٕذٍ لِّلْمُكَذِّبِيْنَۙ  ',
		ayahNumber: 11,
		translationId: 'Maka celakalah pada hari itu bagi orang-orang yang mendustakan.',
	),
	Ayah(
		ayahId: 4747,
		ayahText: 'الَّذِيْنَ هُمْ فِيْ خَوْضٍ يَّلْعَبُوْنَۘ  ',
		ayahNumber: 12,
		translationId: 'Orang-orang yang bermain-main dalam kebatilan (perbuatan dosa),',
	),
	Ayah(
		ayahId: 4748,
		ayahText: 'يَوْمَ يُدَعُّوْنَ اِلٰى نَارِ جَهَنَّمَ دَعًّاۗ',
		ayahNumber: 13,
		translationId: 'pada hari (ketika) itu mereka didorong ke neraka Jahanam dengan sekuat-kuatnya.',
	),
	Ayah(
		ayahId: 4749,
		ayahText: 'هٰذِهِ النَّارُ الَّتِيْ كُنْتُمْ بِهَا تُكَذِّبُوْنَ ',
		ayahNumber: 14,
		translationId: '(Dikatakan kepada mereka), “Inilah neraka yang dahulu kamu mendustakannya.” ',
	),
	Ayah(
		ayahId: 4750,
		ayahText: 'اَفَسِحْرٌ هٰذَآ اَمْ اَنْتُمْ لَا تُبْصِرُوْنَ ',
		ayahNumber: 15,
		translationId: 'Maka apakah ini sihir? Ataukah kamu tidak melihat?',
	),
	Ayah(
		ayahId: 4751,
		ayahText: 'اِصْلَوْهَا فَاصْبِرُوْٓا اَوْ لَا تَصْبِرُوْاۚ سَوَاۤءٌ عَلَيْكُمْۗ  اِنَّمَا تُجْزَوْنَ مَا كُنْتُمْ تَعْمَلُوْنَ ',
		ayahNumber: 16,
		translationId: 'Masuklah ke dalamnya (rasakanlah panas apinya); baik kamu bersabar atau tidak, sama saja bagimu; sesungguhnya kamu hanya diberi balasan atas apa yang telah kamu kerjakan. ',
	),
	Ayah(
		ayahId: 4752,
		ayahText: 'اِنَّ الْمُتَّقِيْنَ فِيْ جَنّٰتٍ وَّنَعِيْمٍۙ  ',
		ayahNumber: 17,
		translationId: 'Sesungguhnya orang-orang yang bertakwa berada dalam surga dan kenikmatan,',
	),
	Ayah(
		ayahId: 4753,
		ayahText: 'فَاكِهِيْنَ بِمَآ اٰتٰىهُمْ رَبُّهُمْۚ وَوَقٰىهُمْ رَبُّهُمْ عَذَابَ الْجَحِيْمِ',
		ayahNumber: 18,
		translationId: 'mereka bersuka ria dengan apa yang diberikan Tuhan kepada mereka; dan Tuhan memelihara mereka dari azab neraka.',
	),
	Ayah(
		ayahId: 4754,
		ayahText: 'كُلُوْا وَاشْرَبُوْا هَنِيْۤئًا ۢبِمَا كُنْتُمْ تَعْمَلُوْنَۙ  ',
		ayahNumber: 19,
		translationId: '(Dikatakan kepada mereka), “Makan dan minumlah dengan rasa nikmat sebagai balasan dari apa yang telah kamu kerjakan.” ',
	),
	Ayah(
		ayahId: 4755,
		ayahText: 'مُتَّكِـِٕيْنَ عَلٰى سُرُرٍ مَّصْفُوْفَةٍۚ وَزَوَّجْنٰهُمْ بِحُوْرٍ عِيْنٍ',
		ayahNumber: 20,
		translationId: 'Mereka bersandar di atas dipan-dipan yang tersusun dan Kami berikan kepada mereka pasangan bidadari yang bermata indah. ',
	),
	Ayah(
		ayahId: 4756,
		ayahText: 'وَالَّذِيْنَ اٰمَنُوْا وَاتَّبَعَتْهُمْ ذُرِّيَّتُهُمْ بِاِيْمَانٍ اَلْحَقْنَا بِهِمْ ذُرِّيَّتَهُمْ وَمَآ اَلَتْنٰهُمْ مِّنْ عَمَلِهِمْ مِّنْ شَيْءٍۚ  كُلُّ امْرِئٍ ۢبِمَا كَسَبَ رَهِيْنٌ ',
		ayahNumber: 21,
		translationId: 'Dan orang-orang yang beriman, beserta anak cucu mereka yang mengikuti mereka dalam keimanan, Kami pertemukan mereka dengan anak cucu mereka (di dalam surga), dan Kami tidak mengurangi sedikit pun pahala amal (kebajikan) mereka. Setiap orang terikat dengan apa yang dikerjakannya. ',
	),
	Ayah(
		ayahId: 4757,
		ayahText: 'وَاَمْدَدْنٰهُمْ بِفَاكِهَةٍ وَّلَحْمٍ مِّمَّا يَشْتَهُوْنَ ',
		ayahNumber: 22,
		translationId: 'Dan Kami berikan kepada mereka tambahan berupa buah-buahan dan daging dari segala jenis yang mereka ingini. ',
	),
	Ayah(
		ayahId: 4758,
		ayahText: 'يَتَنَازَعُوْنَ فِيْهَا كَأْسًا لَّا لَغْوٌ فِيْهَا وَلَا تَأْثِيْمٌ ',
		ayahNumber: 23,
		translationId: '(Di dalam surga itu) mereka saling mengulurkan gelas yang isinya tidak (menimbulkan) ucapan yang tidak berfaedah ataupun perbuatan dosa. ',
	),
	Ayah(
		ayahId: 4759,
		ayahText: 'وَيَطُوْفُ عَلَيْهِمْ غِلْمَانٌ لَّهُمْ كَاَنَّهُمْ لُؤْلُؤٌ مَّكْنُوْنٌۚ  ',
		ayahNumber: 24,
		translationId: 'Dan di sekitar mereka ada anak-anak muda yang berkeliling untuk (melayani) mereka, seakan-akan mereka itu mutiara yang tersimpan. ',
	),
	Ayah(
		ayahId: 4760,
		ayahText: 'وَاَقْبَلَ بَعْضُهُمْ عَلٰى بَعْضٍ يَّتَسَاۤءَلُوْنَ ',
		ayahNumber: 25,
		translationId: 'Dan sebagian mereka berhadap-hadapan satu sama lain saling bertegur sapa. ',
	),
	Ayah(
		ayahId: 4761,
		ayahText: 'قَالُوْٓا اِنَّا كُنَّا قَبْلُ فِيْٓ اَهْلِنَا مُشْفِقِيْنَ ',
		ayahNumber: 26,
		translationId: 'Mereka berkata, “Sesungguhnya kami dahulu, sewaktu berada di tengah-tengah keluarga kami merasa takut (akan diazab). ',
	),
	Ayah(
		ayahId: 4762,
		ayahText: 'فَمَنَّ اللّٰهُ عَلَيْنَا وَوَقٰىنَا عَذَابَ السَّمُوْمِ ',
		ayahNumber: 27,
		translationId: 'Maka Allah memberikan karunia kepada kami dan memelihara kami dari azab neraka. ',
	),
	Ayah(
		ayahId: 4763,
		ayahText: 'اِنَّا كُنَّا مِنْ قَبْلُ نَدْعُوْهُۗ اِنَّهٗ هُوَ الْبَرُّ الرَّحِيْمُ ',
		ayahNumber: 28,
		translationId: 'Sesungguhnya kami menyembah-Nya sejak dahulu. Dialah Yang Maha Melimpahkan Kebaikan, Maha Penyayang.” ',
	),
	Ayah(
		ayahId: 4764,
		ayahText: 'فَذَكِّرْ فَمَآ اَنْتَ بِنِعْمَتِ رَبِّكَ بِكَاهِنٍ وَّلَا مَجْنُوْنٍۗ ',
		ayahNumber: 29,
		translationId: 'Maka peringatkanlah, karena dengan nikmat Tuhanmu engkau (Muhammad) bukanlah seorang tukang tenung dan bukan pula orang gila.',
	),
	Ayah(
		ayahId: 4765,
		ayahText: 'اَمْ يَقُوْلُوْنَ شَاعِرٌ نَّتَرَبَّصُ بِهٖ رَيْبَ الْمَنُوْنِ ',
		ayahNumber: 30,
		translationId: 'Bahkan mereka berkata, “Dia adalah seorang penyair yang kami tunggu-tunggu kecelakaan menimpanya.” ',
	),
	Ayah(
		ayahId: 4766,
		ayahText: 'قُلْ تَرَبَّصُوْا فَاِنِّيْ مَعَكُمْ مِّنَ الْمُتَرَبِّصِيْنَۗ  ',
		ayahNumber: 31,
		translationId: 'Katakanlah (Muhammad), “Tunggulah! Sesungguhnya aku pun termasuk orang yang sedang menunggu bersama kamu.” ',
	),
	Ayah(
		ayahId: 4767,
		ayahText: 'اَمْ تَأْمُرُهُمْ اَحْلَامُهُمْ بِهٰذَآ اَمْ هُمْ قَوْمٌ طَاغُوْنَۚ ',
		ayahNumber: 32,
		translationId: 'Apakah mereka diperintah oleh pikiran-pikiran mereka untuk mengucapkan (tuduhan-tuduhan) ini ataukah mereka kaum yang melampaui batas?',
	),
	Ayah(
		ayahId: 4768,
		ayahText: 'اَمْ يَقُوْلُوْنَ تَقَوَّلَهٗۚ بَلْ لَّا يُؤْمِنُوْنَۚ ',
		ayahNumber: 33,
		translationId: 'Ataukah mereka berkata, “Dia (Muhammad) mereka-rekanya.” Tidak! Merekalah yang tidak beriman. ',
	),
	Ayah(
		ayahId: 4769,
		ayahText: 'فَلْيَأْتُوْا بِحَدِيْثٍ مِّثْلِهٖٓ اِنْ كَانُوْا صٰدِقِيْنَۗ  ',
		ayahNumber: 34,
		translationId: "Maka cobalah mereka membuat yang semisal dengannya (Al-Qur'an) jika mereka orang-orang yang benar. ",
	),
	Ayah(
		ayahId: 4770,
		ayahText: 'اَمْ خُلِقُوْا مِنْ غَيْرِ شَيْءٍ اَمْ هُمُ الْخَالِقُوْنَۗ  ',
		ayahNumber: 35,
		translationId: 'Atau apakah mereka tercipta tanpa asal-usul ataukah mereka yang menciptakan (diri mereka sendiri)?',
	),
	Ayah(
		ayahId: 4771,
		ayahText: 'اَمْ خَلَقُوا السَّمٰوٰتِ وَالْاَرْضَۚ بَلْ لَّا يُوْقِنُوْنَۗ  ',
		ayahNumber: 36,
		translationId: 'Ataukah mereka telah menciptakan langit dan bumi? Sebenarnya mereka tidak meyakini (apa yang mereka katakan).',
	),
	Ayah(
		ayahId: 4772,
		ayahText: 'اَمْ عِنْدَهُمْ خَزَاۤىِٕنُ رَبِّكَ اَمْ هُمُ الْمُصَۣيْطِرُوْنَۗ  ',
		ayahNumber: 37,
		translationId: 'Ataukah di sisi mereka ada perbendaharaan Tuhanmu ataukah mereka yang berkuasa?',
	),
	Ayah(
		ayahId: 4773,
		ayahText: 'اَمْ لَهُمْ سُلَّمٌ يَّسْتَمِعُوْنَ فِيْهِۚ فَلْيَأْتِ مُسْتَمِعُهُمْ بِسُلْطٰنٍ مُّبِيْنٍۗ  ',
		ayahNumber: 38,
		translationId: 'Atau apakah mereka mempunyai tangga (ke langit) untuk mendengarkan (hal-hal yang gaib)? Maka hendaklah orang yang mendengarkan di antara mereka itu datang membawa keterangan yang nyata. ',
	),
	Ayah(
		ayahId: 4774,
		ayahText: 'اَمْ لَهُ الْبَنٰتُ وَلَكُمُ الْبَنُوْنَۗ  ',
		ayahNumber: 39,
		translationId: 'Ataukah (pantas) untuk Dia anak-anak perempuan sedangkan untuk kamu anak-anak laki-laki?',
	),
	Ayah(
		ayahId: 4775,
		ayahText: 'اَمْ تَسْـَٔلُهُمْ اَجْرًا فَهُمْ مِّنْ مَّغْرَمٍ مُّثْقَلُوْنَۗ  ',
		ayahNumber: 40,
		translationId: 'Ataukah engkau (Muhamamd) meminta imbalan kepada mereka sehingga mereka dibebani dengan utang?',
	),
	Ayah(
		ayahId: 4776,
		ayahText: 'اَمْ عِنْدَهُمُ الْغَيْبُ فَهُمْ يَكْتُبُوْنَۗ ',
		ayahNumber: 41,
		translationId: 'Ataukah di sisi mereka mempunyai (pengetahuan) tentang yang gaib lalu mereka menuliskannya?',
	),
	Ayah(
		ayahId: 4777,
		ayahText: 'اَمْ يُرِيْدُوْنَ كَيْدًاۗ فَالَّذِيْنَ كَفَرُوْا هُمُ الْمَكِيْدُوْنَۗ  ',
		ayahNumber: 42,
		translationId: 'Ataukah mereka hendak melakukan tipu daya? Tetapi orang-orang yang kafir itu, justru merekalah yang terkena tipu daya.',
	),
	Ayah(
		ayahId: 4778,
		ayahText: 'اَمْ لَهُمْ اِلٰهٌ غَيْرُ اللّٰهِ ۗسُبْحٰنَ اللّٰهِ عَمَّا يُشْرِكُوْنَ  ',
		ayahNumber: 43,
		translationId: 'Ataukah mereka mempunyai tuhan selain Allah? Mahasuci Allah dari apa yang mereka persekutukan.',
	),
	Ayah(
		ayahId: 4779,
		ayahText: 'وَاِنْ يَّرَوْا كِسْفًا مِّنَ السَّمَاۤءِ سَاقِطًا يَّقُوْلُوْا سَحَابٌ مَّرْكُوْمٌ ',
		ayahNumber: 44,
		translationId: 'Dan jika mereka melihat gumpalan-gumpalan awan berjatuhan dari langit, mereka berkata, “Itu adalah awan yang bertumpuk-tumpuk.” ',
	),
	Ayah(
		ayahId: 4780,
		ayahText: 'فَذَرْهُمْ حَتّٰى يُلٰقُوْا يَوْمَهُمُ الَّذِيْ فِيْهِ يُصْعَقُوْنَۙ  ',
		ayahNumber: 45,
		translationId: 'Maka biarkanlah mereka hingga mereka menemui hari (yang dijanjikan kepada) mereka, pada hari itu mereka dibinasakan, ',
	),
	Ayah(
		ayahId: 4781,
		ayahText: 'يَوْمَ لَا يُغْنِيْ عَنْهُمْ كَيْدُهُمْ شَيْـًٔا وَّلَا هُمْ يُنْصَرُوْنَۗ  ',
		ayahNumber: 46,
		translationId: '(yaitu) pada hari (ketika) tipu daya mereka tidak berguna sedikit pun bagi mereka dan mereka tidak akan diberi pertolongan.',
	),
	Ayah(
		ayahId: 4782,
		ayahText: 'وَاِنَّ لِلَّذِيْنَ ظَلَمُوْا عَذَابًا دُوْنَ ذٰلِكَ وَلٰكِنَّ اَكْثَرَهُمْ لَا يَعْلَمُوْنَ ',
		ayahNumber: 47,
		translationId: 'Dan sesungguhnya bagi orang-orang yang zalim masih ada azab selain itu. Tetapi kebanyakan mereka tidak mengetahui.',
	),
	Ayah(
		ayahId: 4783,
		ayahText: 'وَاصْبِرْ لِحُكْمِ رَبِّكَ فَاِنَّكَ بِاَعْيُنِنَا وَسَبِّحْ بِحَمْدِ رَبِّكَ حِيْنَ تَقُوْمُۙ  ',
		ayahNumber: 48,
		translationId: 'Dan bersabarlah (Muhammad) menunggu ketetapan Tuhanmu, karena sesungguhnya engkau berada dalam pengawasan Kami, dan bertasbihlah dengan memuji Tuhanmu ketika engkau bangun, ',
	),
	Ayah(
		ayahId: 4784,
		ayahText: 'وَمِنَ الَّيْلِ فَسَبِّحْهُ وَاِدْبَارَ النُّجُوْمِ ࣖ',
		ayahNumber: 49,
		translationId: 'dan pada sebagian malam bertasbihlah kepada-Nya dan (juga) pada waktu terbenamnya bintang-bintang (pada waktu fajar).',
	),
];
