// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah23 = [
	Ayah(
		ayahId: 2674,
		ayahText: ' قَدْ اَفْلَحَ الْمُؤْمِنُوْنَ ۙ',
		ayahNumber: 1,
		translationId: 'Sungguh beruntung orang-orang yang beriman,',
	),
	Ayah(
		ayahId: 2675,
		ayahText: ' الَّذِيْنَ هُمْ فِيْ صَلٰو تِهِمْ خَاشِعُوْنَ',
		ayahNumber: 2,
		translationId: '(yaitu) orang yang khusyuk dalam salatnya,',
	),
	Ayah(
		ayahId: 2676,
		ayahText: 'وَالَّذِيْنَ هُمْ عَنِ اللَّغْوِ مُعْرِضُوْنَ ۙ',
		ayahNumber: 3,
		translationId: 'dan orang yang menjauhkan diri dari (perbuatan dan perkataan) yang tidak berguna,',
	),
	Ayah(
		ayahId: 2677,
		ayahText: 'وَالَّذِيْنَ هُمْ لِلزَّكٰوةِ فَاعِلُوْنَ ۙ',
		ayahNumber: 4,
		translationId: 'dan orang yang menunaikan zakat,',
	),
	Ayah(
		ayahId: 2678,
		ayahText: ' وَالَّذِيْنَ هُمْ لِفُرُوْجِهِمْ حٰفِظُوْنَ ۙ',
		ayahNumber: 5,
		translationId: 'dan orang yang memelihara kemaluannya,',
	),
	Ayah(
		ayahId: 2679,
		ayahText: 'اِلَّا عَلٰٓى اَزْوَاجِهِمْ اَوْ مَا مَلَكَتْ اَيْمَانُهُمْ فَاِنَّهُمْ غَيْرُ مَلُوْمِيْنَۚ',
		ayahNumber: 6,
		translationId: 'kecuali terhadap istri-istri mereka atau hamba sahaya yang mereka miliki; maka sesungguhnya mereka tidak tercela.',
	),
	Ayah(
		ayahId: 2680,
		ayahText: 'فَمَنِ ابْتَغٰى وَرَاۤءَ ذٰلِكَ فَاُولٰۤىِٕكَ هُمُ الْعٰدُوْنَ ۚ',
		ayahNumber: 7,
		translationId: 'Tetapi barang siapa mencari di balik itu (zina, dan sebagainya), maka mereka itulah orang-orang yang melampaui batas.',
	),
	Ayah(
		ayahId: 2681,
		ayahText: 'وَالَّذِيْنَ هُمْ لِاَمٰنٰتِهِمْ وَعَهْدِهِمْ رَاعُوْنَ ۙ',
		ayahNumber: 8,
		translationId: 'Dan (sungguh beruntung) orang yang memelihara amanat-amanat dan janjinya,',
	),
	Ayah(
		ayahId: 2682,
		ayahText: 'وَالَّذِيْنَ هُمْ عَلٰى صَلَوٰتِهِمْ يُحَافِظُوْنَ ۘ',
		ayahNumber: 9,
		translationId: 'serta orang yang memelihara salatnya.',
	),
	Ayah(
		ayahId: 2683,
		ayahText: 'اُولٰۤىِٕكَ هُمُ الْوَارِثُوْنَ ۙ',
		ayahNumber: 10,
		translationId: 'Mereka itulah orang yang akan mewarisi,',
	),
	Ayah(
		ayahId: 2684,
		ayahText: 'الَّذِيْنَ يَرِثُوْنَ الْفِرْدَوْسَۗ هُمْ فِيْهَا خٰلِدُوْنَ ',
		ayahNumber: 11,
		translationId: '(yakni) yang akan mewarisi (surga) Firdaus. Mereka kekal di dalamnya.',
	),
	Ayah(
		ayahId: 2685,
		ayahText: 'وَلَقَدْ خَلَقْنَا الْاِنْسَانَ مِنْ سُلٰلَةٍ مِّنْ طِيْنٍ ۚ',
		ayahNumber: 12,
		translationId: 'Dan sungguh, Kami telah menciptakan manusia dari saripati (berasal) dari tanah.',
	),
	Ayah(
		ayahId: 2686,
		ayahText: 'ثُمَّ جَعَلْنٰهُ نُطْفَةً فِيْ قَرَارٍ مَّكِيْنٍ ۖ',
		ayahNumber: 13,
		translationId: 'Kemudian Kami menjadikannya air mani (yang disimpan) dalam tempat yang kokoh (rahim).',
	),
	Ayah(
		ayahId: 2687,
		ayahText: 'ثُمَّ خَلَقْنَا النُّطْفَةَ عَلَقَةً فَخَلَقْنَا الْعَلَقَةَ مُضْغَةً فَخَلَقْنَا الْمُضْغَةَ عِظٰمًا فَكَسَوْنَا الْعِظٰمَ لَحْمًا ثُمَّ اَنْشَأْنٰهُ خَلْقًا اٰخَرَۗ فَتَبَارَكَ اللّٰهُ اَحْسَنُ الْخَالِقِيْنَۗ ',
		ayahNumber: 14,
		translationId: 'Kemudian, air mani itu Kami jadikan sesuatu yang melekat, lalu sesuatu yang melekat itu Kami jadikan segumpal daging, dan segumpal daging itu Kami jadikan tulang belulang, lalu tulang belulang itu Kami bungkus dengan daging. Kemudian, Kami menjadikannya makhluk yang (berbentuk) lain. Mahasuci Allah, Pencipta yang paling baik.',
	),
	Ayah(
		ayahId: 2688,
		ayahText: ' ثُمَّ اِنَّكُمْ بَعْدَ ذٰلِكَ لَمَيِّتُوْنَ ۗ',
		ayahNumber: 15,
		translationId: 'Kemudian setelah itu, sesungguhnya kamu pasti mati.',
	),
	Ayah(
		ayahId: 2689,
		ayahText: 'ثُمَّ اِنَّكُمْ يَوْمَ الْقِيٰمَةِ تُبْعَثُوْنَ',
		ayahNumber: 16,
		translationId: 'Kemudian, sesungguhnya kamu akan dibangkitkan (dari kuburmu) pada hari Kiamat.',
	),
	Ayah(
		ayahId: 2690,
		ayahText: 'وَلَقَدْ خَلَقْنَا فَوْقَكُمْ سَبْعَ طَرَاۤىِٕقَۖ وَمَا كُنَّا عَنِ الْخَلْقِ غٰفِلِيْنَ',
		ayahNumber: 17,
		translationId: 'Dan sungguh, Kami telah menciptakan tujuh (lapis) langit di atas kamu, dan Kami tidaklah lengah terhadap ciptaan (Kami).',
	),
	Ayah(
		ayahId: 2691,
		ayahText: 'وَاَنْزَلْنَا مِنَ السَّمَاۤءِ مَاۤءًۢ بِقَدَرٍ فَاَسْكَنّٰهُ فِى الْاَرْضِۖ وَاِنَّا عَلٰى ذَهَابٍۢ بِهٖ لَقٰدِرُوْنَ ۚ',
		ayahNumber: 18,
		translationId: 'Dan Kami turunkan air dari langit dengan suatu ukuran; lalu Kami jadikan air itu menetap di bumi, dan pasti Kami berkuasa melenyapkannya. ',
	),
	Ayah(
		ayahId: 2692,
		ayahText: 'فَاَنْشَأْنَا لَكُمْ بِهٖ جَنّٰتٍ مِّنْ نَّخِيْلٍ وَّاَعْنَابٍۘ لَكُمْ فِيْهَا فَوَاكِهُ كَثِيْرَةٌ وَّمِنْهَا تَأْكُلُوْنَ ۙ',
		ayahNumber: 19,
		translationId: 'Lalu dengan (air) itu, Kami tumbuhkan untukmu kebun-kebun kurma dan anggur; di sana kamu memperoleh buah-buahan yang banyak dan sebagian dari (buah-buahan) itu kamu makan, ',
	),
	Ayah(
		ayahId: 2693,
		ayahText: 'وَشَجَرَةً تَخْرُجُ مِنْ طُوْرِ سَيْنَاۤءَ تَنْۢبُتُ بِالدُّهْنِ وَصِبْغٍ لِّلْاٰكِلِيْنَ ',
		ayahNumber: 20,
		translationId: 'dan (Kami tumbuhkan) pohon (zaitun) yang tumbuh dari gunung Sinai, yang menghasilkan minyak, dan bahan pembangkit selera bagi orang-orang yang makan. ',
	),
	Ayah(
		ayahId: 2694,
		ayahText: 'وَاِنَّ لَكُمْ فِى الْاَنْعَامِ لَعِبْرَةًۗ  نُسْقِيْكُمْ مِّمَّا فِيْ بُطُوْنِهَا وَلَكُمْ فِيْهَا مَنَافِعُ كَثِيْرَةٌ وَّمِنْهَا تَأْكُلُوْنَ ۙ ',
		ayahNumber: 21,
		translationId: 'Dan sesungguhnya pada hewan-hewan ternak terdapat suatu pelajaran bagimu. Kami memberi minum kamu dari (air susu) yang ada dalam perutnya, dan padanya juga terdapat banyak manfaat untukmu, dan sebagian darinya kamu makan,',
	),
	Ayah(
		ayahId: 2695,
		ayahText: 'وَعَلَيْهَا وَعَلَى الْفُلْكِ تُحْمَلُوْنَ ࣖ',
		ayahNumber: 22,
		translationId: 'di atasnya (hewan-hewan ternak) dan di atas kapal-kapal kamu diangkut.',
	),
	Ayah(
		ayahId: 2696,
		ayahText: 'وَلَقَدْ اَرْسَلْنَا نُوْحًا اِلٰى قَوْمِهٖ فَقَالَ يٰقَوْمِ اعْبُدُوا اللّٰهَ مَا لَكُمْ مِّنْ اِلٰهٍ غَيْرُهٗۗ اَفَلَا تَتَّقُوْنَ ',
		ayahNumber: 23,
		translationId: 'Dan sungguh, Kami telah mengutus Nuh kepada kaumnya, lalu dia berkata, “Wahai kaumku! Sembahlah Allah, (karena) tidak ada tuhan (yang berhak disembah) bagimu selain Dia. Maka mengapa kamu tidak bertakwa (kepada-Nya)?”',
	),
	Ayah(
		ayahId: 2697,
		ayahText: 'فَقَالَ الْمَلَؤُا الَّذِيْنَ كَفَرُوْا مِنْ قَوْمِهٖ مَا هٰذَآ اِلَّا بَشَرٌ مِّثْلُكُمْۙ يُرِيْدُ اَنْ يَّتَفَضَّلَ عَلَيْكُمْۗ وَلَوْ شَاۤءَ اللّٰهُ لَاَنْزَلَ مَلٰۤىِٕكَةً  ۖمَّا سَمِعْنَا بِهٰذَا فِيْٓ اٰبَاۤىِٕنَا الْاَوَّلِيْنَ ۚ',
		ayahNumber: 24,
		translationId: 'Maka berkatalah para pemuka orang kafir dari kaumnya, “Orang ini tidak lain hanyalah manusia seperti kamu, yang ingin menjadi orang yang lebih mulia daripada kamu. Dan seandainya Allah menghendaki, tentu Dia mengutus malaikat. Belum pernah kami mendengar (seruan yang seperti) ini pada (masa) nenek moyang kami dahulu.',
	),
	Ayah(
		ayahId: 2698,
		ayahText: 'اِنْ هُوَ اِلَّا رَجُلٌۢ بِهٖ جِنَّةٌ فَتَرَبَّصُوْا بِهٖ حَتّٰى حِيْنٍ',
		ayahNumber: 25,
		translationId: 'Dia hanyalah seorang laki-laki yang gila, maka tunggulah (sabarlah) terhadapnya sampai waktu yang ditentukan.”',
	),
	Ayah(
		ayahId: 2699,
		ayahText: 'قَالَ رَبِّ انْصُرْنِيْ بِمَا كَذَّبُوْنِ ',
		ayahNumber: 26,
		translationId: 'Dia (Nuh) berdoa, “Ya Tuhanku, tolonglah aku karena mereka mendustakan aku.”',
	),
	Ayah(
		ayahId: 2700,
		ayahText: 'فَاَوْحَيْنَآ اِلَيْهِ اَنِ اصْنَعِ الْفُلْكَ بِاَعْيُنِنَا وَوَحْيِنَا فَاِذَا جَاۤءَ اَمْرُنَا وَفَارَ التَّنُّوْرُۙ فَاسْلُكْ فِيْهَا مِنْ كُلٍّ زَوْجَيْنِ اثْنَيْنِ وَاَهْلَكَ اِلَّا مَنْ سَبَقَ عَلَيْهِ الْقَوْلُ مِنْهُمْۚ وَلَا تُخَاطِبْنِيْ فِى الَّذِيْنَ ظَلَمُوْاۚ اِنَّهُمْ مُّغْرَقُوْنَ',
		ayahNumber: 27,
		translationId: 'Lalu Kami wahyukan kepadanya, “Buatlah kapal di bawah pengawasan dan petunjuk Kami, maka apabila perintah Kami datang dan tanur (dapur) telah memancarkan air, maka masukkanlah ke dalam (kapal) itu sepasang-sepasang dari setiap jenis, juga keluargamu, kecuali orang yang lebih dahulu ditetapkan (akan ditimpa siksaan) di antara mereka. Dan janganlah engkau bicarakan dengan-Ku tentang orang-orang yang zalim, sesungguhnya mereka itu akan ditenggelamkan.',
	),
	Ayah(
		ayahId: 2701,
		ayahText: 'فَاِذَا اسْتَوَيْتَ اَنْتَ وَمَنْ مَّعَكَ عَلَى الْفُلْكِ فَقُلِ الْحَمْدُ لِلّٰهِ الَّذِيْ نَجّٰىنَا مِنَ الْقَوْمِ الظّٰلِمِيْنَ',
		ayahNumber: 28,
		translationId: 'Dan apabila engkau dan orang-orang yang bersamamu telah berada di atas kapal, maka ucapkanlah, “Segala puji bagi Allah yang telah menyelamatkan kami dari orang-orang yang zalim.”',
	),
	Ayah(
		ayahId: 2702,
		ayahText: 'وَقُلْ رَّبِّ اَنْزِلْنِيْ مُنْزَلًا مُّبٰرَكًا وَّاَنْتَ خَيْرُ الْمُنْزِلِيْنَ',
		ayahNumber: 29,
		translationId: 'Dan berdoalah, “Ya Tuhanku, tempatkanlah aku pada tempat yang diberkahi, dan Engkau adalah sebaik-baik pemberi tempat.”',
	),
	Ayah(
		ayahId: 2703,
		ayahText: 'اِنَّ فِيْ ذٰلِكَ لَاٰيٰتٍ وَّاِنْ كُنَّا لَمُبْتَلِيْنَ',
		ayahNumber: 30,
		translationId: 'Sungguh, pada (kejadian) itu benar-benar terdapat tanda-tanda (kebesaran Allah); dan sesungguhnya Kami benar-benar menimpakan siksaan (kepada kaum Nuh itu).',
	),
	Ayah(
		ayahId: 2704,
		ayahText: 'ثُمَّ اَنْشَأْنَا مِنْۢ بَعْدِهِمْ قَرْنًا اٰخَرِيْنَ ۚ',
		ayahNumber: 31,
		translationId: 'Kemudian setelah mereka, Kami ciptakan umat yang lain (kaum ‘Ad).',
	),
	Ayah(
		ayahId: 2705,
		ayahText: 'فَاَرْسَلْنَا فِيْهِمْ رَسُوْلًا مِّنْهُمْ اَنِ اعْبُدُوا اللّٰهَ مَا لَكُمْ مِّنْ اِلٰهٍ غَيْرُهٗۗ اَفَلَا تَتَّقُوْنَ ࣖ ',
		ayahNumber: 32,
		translationId: 'Lalu Kami utus kepada mereka, seorang rasul dari kalangan mereka sendiri (yang berkata), “Sembahlah Allah! Tidak ada tuhan (yang berhak disembah) bagimu selain Dia. Maka mengapa kamu tidak bertakwa (kepada-Nya)?”',
	),
	Ayah(
		ayahId: 2706,
		ayahText: 'وَقَالَ الْمَلَاُ مِنْ قَوْمِهِ الَّذِيْنَ كَفَرُوْا وَكَذَّبُوْا بِلِقَاۤءِ الْاٰخِرَةِ وَاَتْرَفْنٰهُمْ فِى الْحَيٰوةِ الدُّنْيَاۙ مَا هٰذَآ اِلَّا بَشَرٌ مِّثْلُكُمْۙ يَأْكُلُ مِمَّا تَأْكُلُوْنَ مِنْهُ وَيَشْرَبُ مِمَّا تَشْرَبُوْنَ ',
		ayahNumber: 33,
		translationId: 'Dan berkatalah para pemuka orang kafir dari kaumnya dan yang mendustakan pertemuan hari akhirat serta mereka yang telah Kami beri kemewahan dan kesenangan dalam kehidupan di dunia, “(Orang) ini tidak lain hanyalah manusia seperti kamu, dia makan apa yang kamu makan, dan dia minum apa yang kamu minum.”',
	),
	Ayah(
		ayahId: 2707,
		ayahText: 'وَلَىِٕنْ اَطَعْتُمْ بَشَرًا مِّثْلَكُمْ اِنَّكُمْ اِذًا لَّخٰسِرُوْنَ ۙ',
		ayahNumber: 34,
		translationId: 'Dan sungguh, jika kamu menaati manusia seperti kamu, niscaya kamu pasti rugi.',
	),
	Ayah(
		ayahId: 2708,
		ayahText: 'اَيَعِدُكُمْ اَنَّكُمْ اِذَا مِتُّمْ وَكُنْتُمْ تُرَابًا وَّعِظَامًا اَنَّكُمْ مُّخْرَجُوْنَ ۖ ',
		ayahNumber: 35,
		translationId: 'Adakah dia menjanjikan kepada kamu, bahwa apabila kamu telah mati dan menjadi tanah dan tulang belulang, sesungguhnya kamu akan dikeluarkan (dari kuburmu)?',
	),
	Ayah(
		ayahId: 2709,
		ayahText: '۞ هَيْهَاتَ هَيْهَاتَ لِمَا تُوْعَدُوْنَ ۖ ',
		ayahNumber: 36,
		translationId: 'Jauh! Jauh sekali (dari kebenaran) apa yang diancamkan kepada kamu, ',
	),
	Ayah(
		ayahId: 2710,
		ayahText: 'اِنْ هِيَ اِلَّا حَيَاتُنَا الدُّنْيَا نَمُوْتُ وَنَحْيَا وَمَا نَحْنُ بِمَبْعُوْثِيْنَ ۖ ',
		ayahNumber: 37,
		translationId: '(kehidupan itu) tidak lain hanyalah kehidupan kita di dunia ini, (di sanalah) kita mati dan hidup dan tidak akan dibangkitkan (lagi),',
	),
	Ayah(
		ayahId: 2711,
		ayahText: 'اِنْ هُوَ اِلَّا رَجُلُ ِۨافْتَرٰى عَلَى اللّٰهِ كَذِبًا وَّمَا نَحْنُ لَهٗ بِمُؤْمِنِيْنَ',
		ayahNumber: 38,
		translationId: 'Dia tidak lain hanyalah seorang laki-laki yang mengada-adakan kebohongan terhadap Allah, dan kita tidak akan mempercayainya.',
	),
	Ayah(
		ayahId: 2712,
		ayahText: 'قَالَ رَبِّ انْصُرْنِيْ بِمَا كَذَّبُوْنِ',
		ayahNumber: 39,
		translationId: 'Dia (Hud) berdoa, “Ya Tuhanku, tolonglah aku karena mereka mendustakan aku.”',
	),
	Ayah(
		ayahId: 2713,
		ayahText: 'قَالَ عَمَّا قَلِيْلٍ لَّيُصْبِحُنَّ نٰدِمِيْنَ ۚ ',
		ayahNumber: 40,
		translationId: 'Dia (Allah) berfirman, “Tidak lama lagi mereka pasti akan menyesal.”',
	),
	Ayah(
		ayahId: 2714,
		ayahText: 'فَاَخَذَتْهُمُ الصَّيْحَةُ بِالْحَقِّ فَجَعَلْنٰهُمْ غُثَاۤءًۚ فَبُعْدًا لِّلْقَوْمِ الظّٰلِمِيْنَ',
		ayahNumber: 41,
		translationId: 'Lalu mereka benar-benar dimusnahkan oleh suara yang mengguntur, dan Kami jadikan mereka (seperti) sampah yang dibawa banjir. Maka binasalah bagi orang-orang yang zalim. ',
	),
	Ayah(
		ayahId: 2715,
		ayahText: 'ثُمَّ اَنْشَأْنَا مِنْۢ بَعْدِهِمْ قُرُوْنًا اٰخَرِيْنَ ۗ',
		ayahNumber: 42,
		translationId: 'Kemudian setelah mereka Kami ciptakan umat-umat yang lain.',
	),
	Ayah(
		ayahId: 2716,
		ayahText: 'مَا تَسْبِقُ مِنْ اُمَّةٍ اَجَلَهَا وَمَا يَسْتَأْخِرُوْنَ ۗ',
		ayahNumber: 43,
		translationId: 'Tidak ada satu umat pun yang dapat menyegerakan ajalnya, dan tidak (pula) menangguhkannya.',
	),
	Ayah(
		ayahId: 2717,
		ayahText: 'ثُمَّ اَرْسَلْنَا رُسُلَنَا تَتْرَاۗ  كُلَّمَا جَاۤءَ اُمَّةً رَّسُوْلُهَا كَذَّبُوْهُ فَاَتْبَعْنَا بَعْضَهُمْ بَعْضًا وَّجَعَلْنٰهُمْ اَحَادِيْثَۚ فَبُعْدًا لِّقَوْمٍ لَّا يُؤْمِنُوْنَ ',
		ayahNumber: 44,
		translationId: 'Kemudian, Kami utus rasul-rasul Kami berturut-turut. Setiap kali seorang rasul datang kepada suatu umat, mereka mendustakannya, maka Kami silihgantikan sebagian mereka dengan sebagian yang lain (dalam kebinasaan). Dan Kami jadikan mereka bahan cerita (bagi manusia). Maka kebinasaanlah bagi kaum yang tidak beriman.',
	),
	Ayah(
		ayahId: 2718,
		ayahText: 'ثُمَّ اَرْسَلْنَا مُوْسٰى وَاَخَاهُ هٰرُوْنَ ەۙ بِاٰيٰتِنَا وَسُلْطٰنٍ مُّبِيْنٍۙ',
		ayahNumber: 45,
		translationId: 'Kemudian Kami utus Musa dan saudaranya Harun dengan membawa tanda-tanda (kebesaran) Kami, dan bukti yang nyata,',
	),
	Ayah(
		ayahId: 2719,
		ayahText: 'اِلٰى فِرْعَوْنَ وَمَلَا۟ىِٕهٖ فَاسْتَكْبَرُوْا وَكَانُوْا قَوْمًا عَالِيْنَ ۚ',
		ayahNumber: 46,
		translationId: 'kepada Fir‘aun dan para pemuka kaumnya, tetapi mereka angkuh dan mereka memang kaum yang sombong.',
	),
	Ayah(
		ayahId: 2720,
		ayahText: 'فَقَالُوْٓا اَنُؤْمِنُ لِبَشَرَيْنِ مِثْلِنَا وَقَوْمُهُمَا لَنَا عٰبِدُوْنَ ۚ',
		ayahNumber: 47,
		translationId: 'Maka mereka berkata, “Apakah (pantas) kita percaya kepada dua orang manusia seperti kita, padahal kaum mereka (Bani Israil) adalah orang-orang yang menghambakan diri kepada kita?”',
	),
	Ayah(
		ayahId: 2721,
		ayahText: 'فَكَذَّبُوْهُمَا فَكَانُوْا مِنَ الْمُهْلَكِيْنَ ',
		ayahNumber: 48,
		translationId: 'Maka mereka mendustakan keduanya, sebab itu mereka termasuk orang yang dibinasakan.',
	),
	Ayah(
		ayahId: 2722,
		ayahText: 'وَلَقَدْ اٰتَيْنَا مُوْسَى الْكِتٰبَ لَعَلَّهُمْ يَهْتَدُوْنَ ',
		ayahNumber: 49,
		translationId: 'Dan sungguh, telah Kami anugerahi kepada Musa Kitab (Taurat), agar mereka (Bani Israil) mendapat petunjuk.',
	),
	Ayah(
		ayahId: 2723,
		ayahText: 'وَجَعَلْنَا ابْنَ مَرْيَمَ وَاُمَّهٗٓ اٰيَةً وَّاٰوَيْنٰهُمَآ اِلٰى رَبْوَةٍ ذَاتِ قَرَارٍ وَّمَعِيْنٍ ࣖ',
		ayahNumber: 50,
		translationId: 'Dan telah Kami jadikan (Isa) putra Maryam bersama ibunya sebagai suatu bukti yang nyata bagi (kebesaran Kami), dan Kami melindungi mereka di sebuah dataran tinggi, (tempat yang tenang, rindang dan banyak buah-buahan) dengan mata air yang mengalir.',
	),
	Ayah(
		ayahId: 2724,
		ayahText: 'يٰٓاَيُّهَا الرُّسُلُ كُلُوْا مِنَ الطَّيِّبٰتِ وَاعْمَلُوْا صَالِحًاۗ اِنِّيْ بِمَا تَعْمَلُوْنَ عَلِيْمٌ ۗ',
		ayahNumber: 51,
		translationId: 'Allah berfirman, “Wahai para rasul! Makanlah dari (makanan) yang baik-baik, dan kerjakanlah kebajikan. Sungguh, Aku Maha Mengetahui apa yang kamu kerjakan.',
	),
	Ayah(
		ayahId: 2725,
		ayahText: 'وَاِنَّ هٰذِهٖٓ اُمَّتُكُمْ اُمَّةً وَّاحِدَةً وَّاَنَا۠ رَبُّكُمْ فَاتَّقُوْنِ',
		ayahNumber: 52,
		translationId: 'Dan sungguh, (agama tauhid) inilah agama kamu, agama yang satu dan Aku adalah Tuhanmu, maka bertakwalah kepada-Ku.”',
	),
	Ayah(
		ayahId: 2726,
		ayahText: 'فَتَقَطَّعُوْٓا اَمْرَهُمْ بَيْنَهُمْ زُبُرًاۗ  كُلُّ حِزْبٍۢ بِمَا لَدَيْهِمْ فَرِحُوْنَ ',
		ayahNumber: 53,
		translationId: 'Kemudian mereka terpecah belah dalam urusan (agama)nya menjadi beberapa golongan. Setiap golongan (merasa) bangga dengan apa yang ada pada mereka (masing-masing).',
	),
	Ayah(
		ayahId: 2727,
		ayahText: 'فَذَرْهُمْ فِيْ غَمْرَتِهِمْ حَتّٰى حِيْنٍ ',
		ayahNumber: 54,
		translationId: 'Maka biarkanlah mereka dalam kesesatannya sampai waktu yang ditentukan.',
	),
	Ayah(
		ayahId: 2728,
		ayahText: 'اَيَحْسَبُوْنَ اَنَّمَا نُمِدُّهُمْ بِهٖ مِنْ مَّالٍ وَّبَنِيْنَ ۙ',
		ayahNumber: 55,
		translationId: 'Apakah mereka mengira bahwa Kami memberikan harta dan anak-anak kepada mereka itu (berarti bahwa),',
	),
	Ayah(
		ayahId: 2729,
		ayahText: 'نُسَارِعُ لَهُمْ فِى الْخَيْرٰتِۗ بَلْ لَّا يَشْعُرُوْنَ',
		ayahNumber: 56,
		translationId: 'Kami segera memberikan kebaikan-kebaikan kepada mereka? (Tidak), tetapi mereka tidak menyadarinya.',
	),
	Ayah(
		ayahId: 2730,
		ayahText: 'اِنَّ الَّذِيْنَ هُمْ مِّنْ خَشْيَةِ رَبِّهِمْ مُّشْفِقُوْنَ ۙ',
		ayahNumber: 57,
		translationId: 'Sungguh, orang-orang yang karena takut (azab) Tuhannya, mereka sangat berhati-hati,',
	),
	Ayah(
		ayahId: 2731,
		ayahText: 'وَالَّذِيْنَ هُمْ بِاٰيٰتِ رَبِّهِمْ يُؤْمِنُوْنَ ۙ',
		ayahNumber: 58,
		translationId: 'dan mereka yang beriman dengan tanda-tanda (kekuasaan) Tuhannya,',
	),
	Ayah(
		ayahId: 2732,
		ayahText: 'وَالَّذِيْنَ هُمْ بِرَبِّهِمْ لَا يُشْرِكُوْنَ ۙ',
		ayahNumber: 59,
		translationId: 'dan mereka yang tidak mempersekutukan Tuhannya,',
	),
	Ayah(
		ayahId: 2733,
		ayahText: 'وَالَّذِيْنَ يُؤْتُوْنَ مَآ اٰتَوْا وَّقُلُوْبُهُمْ وَجِلَةٌ اَنَّهُمْ اِلٰى رَبِّهِمْ رٰجِعُوْنَ ۙ',
		ayahNumber: 60,
		translationId: 'dan mereka yang memberikan apa yang mereka berikan (sedekah) dengan hati penuh rasa takut (karena mereka tahu) bahwa sesungguhnya mereka akan kembali kepada Tuhannya,',
	),
	Ayah(
		ayahId: 2734,
		ayahText: 'اُولٰۤىِٕكَ يُسَارِعُوْنَ فِى الْخَيْرٰتِ وَهُمْ لَهَا سٰبِقُوْنَ',
		ayahNumber: 61,
		translationId: 'mereka itu bersegera dalam kebaikan-kebaikan, dan merekalah orang-orang yang lebih dahulu memperolehnya.',
	),
	Ayah(
		ayahId: 2735,
		ayahText: 'وَلَا نُكَلِّفُ نَفْسًا اِلَّا وُسْعَهَاۖ وَلَدَيْنَا كِتٰبٌ يَّنْطِقُ بِالْحَقِّ وَهُمْ لَا يُظْلَمُوْنَ ',
		ayahNumber: 62,
		translationId: 'Dan Kami tidak membebani seseorang melainkan menurut kesanggupannya, dan pada Kami ada suatu catatan yang menuturkan dengan sebenarnya, dan mereka tidak dizalimi (dirugikan). ',
	),
	Ayah(
		ayahId: 2736,
		ayahText: 'بَلْ قُلُوْبُهُمْ فِيْ غَمْرَةٍ مِّنْ هٰذَا وَلَهُمْ اَعْمَالٌ مِّنْ دُوْنِ ذٰلِكَ هُمْ لَهَا عَامِلُوْنَ',
		ayahNumber: 63,
		translationId: "Tetapi, hati mereka (orang-orang kafir) itu dalam kesesatan dari (memahami Al-Qur'an) ini, dan mereka mempunyai (kebiasaan banyak mengerjakan) perbuatan-perbuatan lain (buruk) yang terus mereka kerjakan.",
	),
	Ayah(
		ayahId: 2737,
		ayahText: 'حَتّٰٓى اِذَآ اَخَذْنَا مُتْرَفِيْهِمْ بِالْعَذَابِ اِذَا هُمْ يَجْـَٔرُوْنَ ۗ',
		ayahNumber: 64,
		translationId: 'Sehingga apabila Kami timpakan siksaan kepada orang-orang yang hidup bermewah-mewah di antara mereka, seketika itu mereka berteriak-teriak meminta tolong.',
	),
	Ayah(
		ayahId: 2738,
		ayahText: 'لَا تَجْـَٔرُوا الْيَوْمَۖ اِنَّكُمْ مِّنَّا لَا تُنْصَرُوْنَ ',
		ayahNumber: 65,
		translationId: 'Janganlah kamu berteriak-teriak meminta tolong pada hari ini! Sungguh, kamu tidak akan mendapat pertolongan dari Kami.',
	),
	Ayah(
		ayahId: 2739,
		ayahText: 'قَدْ كَانَتْ اٰيٰتِيْ تُتْلٰى عَلَيْكُمْ فَكُنْتُمْ عَلٰٓى اَعْقَابِكُمْ تَنْكِصُوْنَ ۙ',
		ayahNumber: 66,
		translationId: "Sesungguhnya ayat-ayat-Ku (Al-Qur'an) selalu dibacakan kepada kamu, tetapi kamu selalu berpaling ke belakang,",
	),
	Ayah(
		ayahId: 2740,
		ayahText: 'مُسْتَكْبِرِيْنَۙ بِهٖ سٰمِرًا تَهْجُرُوْنَ ',
		ayahNumber: 67,
		translationId: "dengan menyombongkan diri dan mengucapkan perkataan-perkataan keji terhadapnya (Al-Qur'an) pada waktu kamu bercakap-cakap pada malam hari.",
	),
	Ayah(
		ayahId: 2741,
		ayahText: 'اَفَلَمْ يَدَّبَّرُوا الْقَوْلَ اَمْ جَاۤءَهُمْ مَّا لَمْ يَأْتِ اٰبَاۤءَهُمُ الْاَوَّلِيْنَ ۖ',
		ayahNumber: 68,
		translationId: 'Maka tidakkah mereka menghayati firman (Allah), atau adakah telah datang kepada mereka apa yang tidak pernah datang kepada nenek moyang mereka terdahulu?',
	),
	Ayah(
		ayahId: 2742,
		ayahText: 'اَمْ لَمْ يَعْرِفُوْا رَسُوْلَهُمْ فَهُمْ لَهٗ مُنْكِرُوْنَ ۖ',
		ayahNumber: 69,
		translationId: 'Ataukah mereka tidak mengenal Rasul mereka (Muhammad), karena itu mereka mengingkarinya?',
	),
	Ayah(
		ayahId: 2743,
		ayahText: 'اَمْ يَقُوْلُوْنَ بِهٖ جِنَّةٌ ۗ بَلْ جَاۤءَهُمْ بِالْحَقِّ وَاَكْثَرُهُمْ لِلْحَقِّ كٰرِهُوْنَ ',
		ayahNumber: 70,
		translationId: 'Atau mereka berkata, “Orang itu (Muhammad) gila.” Padahal, dia telah datang membawa kebenaran kepada mereka, tetapi kebanyakan mereka membenci kebenaran. ',
	),
	Ayah(
		ayahId: 2744,
		ayahText: 'وَلَوِ اتَّبَعَ الْحَقُّ اَهْوَاۤءَهُمْ لَفَسَدَتِ السَّمٰوٰتُ وَالْاَرْضُ وَمَنْ فِيْهِنَّۗ بَلْ اَتَيْنٰهُمْ بِذِكْرِهِمْ فَهُمْ عَنْ ذِكْرِهِمْ مُّعْرِضُوْنَ ۗ',
		ayahNumber: 71,
		translationId: 'Dan seandainya kebenaran itu menuruti keinginan mereka, pasti binasalah langit dan bumi, dan semua yang ada di dalamnya. Bahkan Kami telah memberikan peringatan kepada mereka, tetapi mereka berpaling dari peringatan itu.',
	),
	Ayah(
		ayahId: 2745,
		ayahText: 'اَمْ تَسْـَٔلُهُمْ خَرْجًا فَخَرَاجُ رَبِّكَ خَيْرٌ ۖوَّهُوَ خَيْرُ الرّٰزِقِيْنَ',
		ayahNumber: 72,
		translationId: 'Atau engkau (Muhammad) meminta imbalan kepada mereka? Sedangkan imbalan dari Tuhanmu lebih baik, karena Dia pemberi rezeki yang terbaik.',
	),
	Ayah(
		ayahId: 2746,
		ayahText: 'وَاِنَّكَ لَتَدْعُوْهُمْ اِلٰى صِرَاطٍ مُّسْتَقِيْمٍ ',
		ayahNumber: 73,
		translationId: 'Dan sesungguhnya engkau pasti telah menyeru mereka kepada jalan yang lurus.',
	),
	Ayah(
		ayahId: 2747,
		ayahText: 'وَاِنَّ الَّذِيْنَ لَا يُؤْمِنُوْنَ بِالْاٰخِرَةِ عَنِ الصِّرَاطِ لَنَاكِبُوْنَ ',
		ayahNumber: 74,
		translationId: 'Dan sesungguhnya orang-orang yang tidak beriman kepada akhirat benar-benar telah menyimpang jauh dari jalan (yang lurus).',
	),
	Ayah(
		ayahId: 2748,
		ayahText: '۞ وَلَوْ رَحِمْنٰهُمْ وَكَشَفْنَا مَا بِهِمْ مِّنْ ضُرٍّ لَّلَجُّوْا فِيْ طُغْيَانِهِمْ يَعْمَهُوْنَ',
		ayahNumber: 75,
		translationId: 'Dan seandainya mereka Kami kasihani, dan Kami lenyapkan malapetaka yang menimpa mereka, pasti mereka akan terus-menerus terombang-ambing dalam kesesatan mereka.',
	),
	Ayah(
		ayahId: 2749,
		ayahText: 'وَلَقَدْ اَخَذْنٰهُمْ بِالْعَذَابِ فَمَا اسْتَكَانُوْا لِرَبِّهِمْ وَمَا يَتَضَرَّعُوْنَ',
		ayahNumber: 76,
		translationId: 'Dan sungguh Kami telah menimpakan siksaan kepada mereka, tetapi mereka tidak mau tunduk kepada Tuhannya, dan (juga) tidak merendahkan diri.',
	),
	Ayah(
		ayahId: 2750,
		ayahText: 'حَتّٰٓى اِذَا فَتَحْنَا عَلَيْهِمْ بَابًا ذَا عَذَابٍ شَدِيْدٍ اِذَا هُمْ فِيْهِ مُبْلِسُوْنَ ࣖ ',
		ayahNumber: 77,
		translationId: 'Sehingga apabila Kami bukakan untuk mereka pintu azab yang sangat keras, seketika itu mereka menjadi putus asa.',
	),
	Ayah(
		ayahId: 2751,
		ayahText: 'وَهُوَ الَّذِيْٓ اَنْشَاَ لَكُمُ السَّمْعَ وَالْاَبْصَارَ وَالْاَفْـِٕدَةَۗ قَلِيْلًا مَّا تَشْكُرُوْنَ',
		ayahNumber: 78,
		translationId: 'Dan Dialah yang telah menciptakan bagimu pendengaran, penglihatan dan hati nurani, tetapi sedikit sekali kamu bersyukur.',
	),
	Ayah(
		ayahId: 2752,
		ayahText: 'وَهُوَ الَّذِيْ ذَرَاَكُمْ فِى الْاَرْضِ وَاِلَيْهِ تُحْشَرُوْنَ',
		ayahNumber: 79,
		translationId: 'Dan Dialah yang menciptakan dan mengembangbiakkan kamu di bumi dan kepada-Nyalah kamu akan dikumpulkan.',
	),
	Ayah(
		ayahId: 2753,
		ayahText: 'وَهُوَ الَّذِيْ يُحْيٖ وَيُمِيْتُ وَلَهُ اخْتِلَافُ الَّيْلِ وَالنَّهَارِۗ اَفَلَا تَعْقِلُوْنَ',
		ayahNumber: 80,
		translationId: 'Dan Dialah yang menghidupkan dan mematikan, dan Dialah yang (mengatur) pergantian malam dan siang. Tidakkah kamu mengerti?',
	),
	Ayah(
		ayahId: 2754,
		ayahText: 'بَلْ قَالُوْا مِثْلَ مَا قَالَ الْاَوَّلُوْنَ',
		ayahNumber: 81,
		translationId: 'Bahkan mereka mengucapkan perkataan yang serupa dengan apa yang diucapkan oleh orang-orang terdahulu.',
	),
	Ayah(
		ayahId: 2755,
		ayahText: 'قَالُوْٓا ءَاِذَا مِتْنَا وَكُنَّا تُرَابًا وَّعِظَامًا ءَاِنَّا لَمَبْعُوْثُوْنَ',
		ayahNumber: 82,
		translationId: 'Mereka berkata, “Apakah betul, apabila kami telah mati dan telah menjadi tanah dan tulang belulang, kami benar-benar akan dibangkitkan kembali?  ',
	),
	Ayah(
		ayahId: 2756,
		ayahText: 'لَقَدْ وُعِدْنَا نَحْنُ وَاٰبَاۤؤُنَا هٰذَا مِنْ قَبْلُ اِنْ هٰذَآ اِلَّآ اَسَاطِيْرُ الْاَوَّلِيْنَ ',
		ayahNumber: 83,
		translationId: 'Sungguh, yang demikian ini sudah dijanjikan kepada kami dan kepada nenek moyang kami dahulu, ini hanyalah dongeng orang-orang terdahulu!”',
	),
	Ayah(
		ayahId: 2757,
		ayahText: 'قُلْ لِّمَنِ الْاَرْضُ وَمَنْ فِيْهَآ اِنْ كُنْتُمْ تَعْلَمُوْنَ ',
		ayahNumber: 84,
		translationId: 'Katakanlah (Muhammad), “Milik siapakah bumi, dan semua yang ada di dalamnya, jika kamu mengetahui?”',
	),
	Ayah(
		ayahId: 2758,
		ayahText: 'سَيَقُوْلُوْنَ لِلّٰهِ ۗقُلْ اَفَلَا تَذَكَّرُوْنَ ',
		ayahNumber: 85,
		translationId: 'Mereka akan menjawab, “Milik Allah.” Katakanlah, “Maka apakah kamu tidak ingat?”',
	),
	Ayah(
		ayahId: 2759,
		ayahText: 'قُلْ مَنْ رَّبُّ السَّمٰوٰتِ السَّبْعِ وَرَبُّ الْعَرْشِ الْعَظِيْمِ',
		ayahNumber: 86,
		translationId: 'Katakanlah, “Siapakah Tuhan yang memiliki langit yang tujuh dan yang memiliki ‘Arsy yang agung?”',
	),
	Ayah(
		ayahId: 2760,
		ayahText: 'سَيَقُوْلُوْنَ لِلّٰهِ ۗقُلْ اَفَلَا تَتَّقُوْنَ',
		ayahNumber: 87,
		translationId: 'Mereka akan menjawab, “(Milik) Allah.” Katakanlah, “Maka mengapa kamu tidak bertakwa?”',
	),
	Ayah(
		ayahId: 2761,
		ayahText: 'قُلْ مَنْۢ بِيَدِهٖ مَلَكُوْتُ كُلِّ شَيْءٍ وَّهُوَ يُجِيْرُ وَلَا يُجَارُ عَلَيْهِ اِنْ كُنْتُمْ تَعْلَمُوْنَ ',
		ayahNumber: 88,
		translationId: 'Katakanlah, “Siapakah yang di tangan-Nya berada kekuasaan segala sesuatu. Dia melindungi, dan tidak ada yang dapat dilindungi dari (azab-Nya), jika kamu mengetahui?”',
	),
	Ayah(
		ayahId: 2762,
		ayahText: 'سَيَقُوْلُوْنَ لِلّٰهِ ۗقُلْ فَاَنّٰى تُسْحَرُوْنَ',
		ayahNumber: 89,
		translationId: 'Mereka akan menjawab, “(Milik) Allah.” Katakanlah, “(Kalau demikian), maka bagaimana kamu sampai tertipu?”',
	),
	Ayah(
		ayahId: 2763,
		ayahText: 'بَلْ اَتَيْنٰهُمْ بِالْحَقِّ وَاِنَّهُمْ لَكٰذِبُوْنَ',
		ayahNumber: 90,
		translationId: 'Padahal Kami telah membawa kebenaran kepada mereka, tetapi mere-ka benar-benar pendusta.',
	),
	Ayah(
		ayahId: 2764,
		ayahText: 'مَا اتَّخَذَ اللّٰهُ مِنْ وَّلَدٍ وَّمَا كَانَ مَعَهٗ مِنْ اِلٰهٍ اِذًا لَّذَهَبَ كُلُّ اِلٰهٍۢ بِمَا خَلَقَ وَلَعَلَا بَعْضُهُمْ عَلٰى بَعْضٍۗ سُبْحٰنَ اللّٰهِ عَمَّا يَصِفُوْنَ ۙ',
		ayahNumber: 91,
		translationId: 'Allah tidak mempunyai anak, dan tidak ada tuhan (yang lain) bersama-Nya, (sekiranya tuhan banyak), maka masing-masing tuhan itu akan membawa apa (makhluk) yang diciptakannya, dan sebagian dari tuhan-tuhan itu akan mengalahkan sebagian yang lain. Mahasuci Allah dari apa yang mereka sifatkan itu,',
	),
	Ayah(
		ayahId: 2765,
		ayahText: 'عٰلِمِ الْغَيْبِ وَالشَّهَادَةِ فَتَعٰلٰى عَمَّا يُشْرِكُوْنَ ࣖ',
		ayahNumber: 92,
		translationId: '(Dialah Tuhan) yang mengetahui semua yang gaib dan semua yang tampak. Mahatinggi (Allah) dari apa yang mereka persekutukan.',
	),
	Ayah(
		ayahId: 2766,
		ayahText: 'قُلْ رَّبِّ اِمَّا تُرِيَنِّيْ مَا يُوْعَدُوْنَ ۙ',
		ayahNumber: 93,
		translationId: 'Katakanlah (Muhammad), “Ya Tuhanku, seandainya Engkau hendak memperlihatkan kepadaku apa (azab) yang diancamkan kepada mereka,',
	),
	Ayah(
		ayahId: 2767,
		ayahText: 'رَبِّ فَلَا تَجْعَلْنِيْ فِى الْقَوْمِ الظّٰلِمِيْنَ',
		ayahNumber: 94,
		translationId: 'Ya Tuhanku, maka janganlah Engkau jadikan aku dalam golongan orang-orang zalim.”',
	),
	Ayah(
		ayahId: 2768,
		ayahText: 'وَاِنَّا عَلٰٓى اَنْ نُّرِيَكَ مَا نَعِدُهُمْ لَقٰدِرُوْنَ',
		ayahNumber: 95,
		translationId: 'Dan sungguh, Kami kuasa untuk memperlihatkan kepadamu (Muhammad) apa yang Kami ancamkan kepada mereka.',
	),
	Ayah(
		ayahId: 2769,
		ayahText: 'اِدْفَعْ بِالَّتِيْ هِيَ اَحْسَنُ السَّيِّئَةَۗ  نَحْنُ اَعْلَمُ بِمَا يَصِفُوْنَ ',
		ayahNumber: 96,
		translationId: 'Tolaklah perbuatan buruk mereka dengan (cara) yang lebih baik, Kami lebih mengetahui apa yang mereka sifatkan (kepada Allah).',
	),
	Ayah(
		ayahId: 2770,
		ayahText: 'وَقُلْ رَّبِّ اَعُوْذُ بِكَ مِنْ هَمَزٰتِ الشَّيٰطِيْنِ ۙ',
		ayahNumber: 97,
		translationId: 'Dan katakanlah, “Ya Tuhanku, aku berlindung kepada Engkau dari bisikan-bisikan setan,',
	),
	Ayah(
		ayahId: 2771,
		ayahText: 'وَاَعُوْذُ بِكَ رَبِّ اَنْ يَّحْضُرُوْنِ ',
		ayahNumber: 98,
		translationId: 'dan aku berlindung (pula) kepada Engkau ya Tuhanku, agar mereka tidak mendekati aku.”',
	),
	Ayah(
		ayahId: 2772,
		ayahText: 'حَتّٰٓى اِذَا جَاۤءَ اَحَدَهُمُ الْمَوْتُ قَالَ رَبِّ ارْجِعُوْنِ ۙ',
		ayahNumber: 99,
		translationId: '(Demikianlah keadaan orang-orang kafir itu), hingga apabila datang kematian kepada seseorang dari mereka, dia berkata, “Ya Tuhanku, kembalikanlah aku (ke dunia),',
	),
	Ayah(
		ayahId: 2773,
		ayahText: 'لَعَلِّيْٓ اَعْمَلُ صَالِحًا فِيْمَا تَرَكْتُ كَلَّاۗ اِنَّهَا كَلِمَةٌ هُوَ قَاۤىِٕلُهَاۗ وَمِنْ وَّرَاۤىِٕهِمْ بَرْزَخٌ اِلٰى يَوْمِ يُبْعَثُوْنَ ',
		ayahNumber: 100,
		translationId: 'agar aku dapat berbuat kebajikan yang telah aku tinggalkan.” Sekali-kali tidak! Sesungguhnya itu adalah dalih yang diucapkannya saja. Dan di hadapan mereka ada barzakh sampai pada hari mereka dibangkitkan.',
	),
	Ayah(
		ayahId: 2774,
		ayahText: 'فَاِذَا نُفِخَ فِى الصُّوْرِ فَلَآ اَنْسَابَ بَيْنَهُمْ يَوْمَىِٕذٍ وَّلَا يَتَسَاۤءَلُوْنَ',
		ayahNumber: 101,
		translationId: 'Apabila sangkakala ditiup maka tidak ada lagi pertalian keluarga di antara mereka pada hari itu (hari Kiamat), dan tidak (pula) mereka saling bertanya.',
	),
	Ayah(
		ayahId: 2775,
		ayahText: 'فَمَنْ ثَقُلَتْ مَوَازِيْنُهٗ فَاُولٰۤىِٕكَ هُمُ الْمُفْلِحُوْنَ ',
		ayahNumber: 102,
		translationId: 'Barangsiapa berat timbangan (kebaikan)nya, maka mereka itulah orang-orang yang beruntung.',
	),
	Ayah(
		ayahId: 2776,
		ayahText: 'وَمَنْ خَفَّتْ مَوَازِيْنُهٗ فَاُولٰۤىِٕكَ الَّذِيْنَ خَسِرُوْٓا اَنْفُسَهُمْ فِيْ جَهَنَّمَ خٰلِدُوْنَ ۚ',
		ayahNumber: 103,
		translationId: 'Dan barang siapa ringan timbangan (kebaikan)nya, maka mereka itulah orang-orang yang merugikan dirinya sendiri, mereka kekal di dalam neraka Jahanam',
	),
	Ayah(
		ayahId: 2777,
		ayahText: 'تَلْفَحُ وُجُوْهَهُمُ النَّارُ وَهُمْ فِيْهَا كَالِحُوْنَ ',
		ayahNumber: 104,
		translationId: 'Wajah mereka dibakar api neraka, dan mereka di neraka dalam keadaan muram dengan bibir yang cacat.',
	),
	Ayah(
		ayahId: 2778,
		ayahText: 'اَلَمْ تَكُنْ اٰيٰتِيْ تُتْلٰى عَلَيْكُمْ فَكُنْتُمْ بِهَا تُكَذِّبُوْنَ',
		ayahNumber: 105,
		translationId: 'Bukankah ayat-ayat-Ku telah dibacakan kepadamu, tetapi kamu selalu mendustakannya?',
	),
	Ayah(
		ayahId: 2779,
		ayahText: 'قَالُوْا رَبَّنَا غَلَبَتْ عَلَيْنَا شِقْوَتُنَا وَكُنَّا قَوْمًا ضَاۤلِّيْنَ',
		ayahNumber: 106,
		translationId: 'Mereka berkata, “Ya Tuhan kami, kami telah dikuasai oleh kejahatan kami, dan kami adalah orang-orang yang sesat.',
	),
	Ayah(
		ayahId: 2780,
		ayahText: 'رَبَّنَآ اَخْرِجْنَا مِنْهَا فَاِنْ عُدْنَا فَاِنَّا ظٰلِمُوْنَ',
		ayahNumber: 107,
		translationId: 'Ya Tuhan kami, keluarkanlah kami darinya (kembalikanlah kami ke dunia), jika kami masih juga kembali (kepada kekafiran), sungguh, kami adalah orang-orang yang zalim.”',
	),
	Ayah(
		ayahId: 2781,
		ayahText: 'قَالَ اخْسَـُٔوْا فِيْهَا وَلَا تُكَلِّمُوْنِ',
		ayahNumber: 108,
		translationId: 'Dia (Allah) berfirman, “Tinggallah dengan hina di dalamnya, dan janganlah kamu berbicara dengan Aku.”',
	),
	Ayah(
		ayahId: 2782,
		ayahText: 'اِنَّهٗ كَانَ فَرِيْقٌ مِّنْ عِبَادِيْ يَقُوْلُوْنَ رَبَّنَآ اٰمَنَّا فَاغْفِرْ لَنَا وَارْحَمْنَا وَاَنْتَ خَيْرُ الرّٰحِمِيْنَ ۚ',
		ayahNumber: 109,
		translationId: 'Sesungguhnya ada segolongan dari hamba-hamba-Ku berdoa, “Ya Tuhan kami, kami telah beriman, maka ampunilah kami dan berilah kami rahmat, Engkau adalah pemberi rahmat yang terbaik.”',
	),
	Ayah(
		ayahId: 2783,
		ayahText: 'فَاتَّخَذْتُمُوْهُمْ سِخْرِيًّا حَتّٰٓى اَنْسَوْكُمْ ذِكْرِيْ وَكُنْتُمْ مِّنْهُمْ تَضْحَكُوْنَ',
		ayahNumber: 110,
		translationId: 'Lalu kamu jadikan mereka buah ejekan, sehingga kamu lupa mengingat Aku, dan kamu (selalu) menertawakan mereka,',
	),
	Ayah(
		ayahId: 2784,
		ayahText: 'اِنِّيْ جَزَيْتُهُمُ الْيَوْمَ بِمَا صَبَرُوْٓاۙ اَنَّهُمْ هُمُ الْفَاۤىِٕزُوْنَ',
		ayahNumber: 111,
		translationId: 'sesungguhnya pada hari ini Aku memberi balasan kepada mereka, karena kesabaran mereka; sesungguhnya mereka itulah orang-orang yang memperoleh kemenangan.',
	),
	Ayah(
		ayahId: 2785,
		ayahText: 'قٰلَ كَمْ لَبِثْتُمْ فِى الْاَرْضِ عَدَدَ سِنِيْنَ',
		ayahNumber: 112,
		translationId: 'Dia (Allah) berfirman, “Berapa tahunkah lamanya kamu tinggal di bumi?”',
	),
	Ayah(
		ayahId: 2786,
		ayahText: 'قَالُوْا لَبِثْنَا يَوْمًا اَوْ بَعْضَ يَوْمٍ فَسْـَٔلِ الْعَاۤدِّيْنَ ',
		ayahNumber: 113,
		translationId: 'Mereka menjawab, “Kami tinggal (di bumi) sehari atau setengah hari, maka tanyakanlah kepada mereka yang menghitung.”',
	),
	Ayah(
		ayahId: 2787,
		ayahText: 'قٰلَ اِنْ لَّبِثْتُمْ اِلَّا قَلِيْلًا لَّوْ اَنَّكُمْ كُنْتُمْ تَعْلَمُوْنَ',
		ayahNumber: 114,
		translationId: 'Dia (Allah) berfirman, “Kamu tinggal (di bumi) hanya sebentar saja, jika kamu benar-benar mengetahui.” ',
	),
	Ayah(
		ayahId: 2788,
		ayahText: 'اَفَحَسِبْتُمْ اَنَّمَا خَلَقْنٰكُمْ عَبَثًا وَّاَنَّكُمْ اِلَيْنَا لَا تُرْجَعُوْنَ',
		ayahNumber: 115,
		translationId: 'Maka apakah kamu mengira, bahwa Kami menciptakan kamu main-main (tanpa ada maksud) dan bahwa kamu tidak akan dikembalikan kepada Kami?',
	),
	Ayah(
		ayahId: 2789,
		ayahText: 'فَتَعٰلَى اللّٰهُ الْمَلِكُ الْحَقُّۚ  لَآ اِلٰهَ اِلَّا هُوَۚ رَبُّ الْعَرْشِ الْكَرِيْمِ',
		ayahNumber: 116,
		translationId: 'Maka Mahatinggi Allah, Raja yang sebenarnya; tidak ada tuhan (yang berhak disembah) selain Dia, Tuhan (yang memiliki) ‘Arsy yang mulia.',
	),
	Ayah(
		ayahId: 2790,
		ayahText: 'وَمَنْ يَّدْعُ مَعَ اللّٰهِ اِلٰهًا اٰخَرَ لَا بُرْهَانَ لَهٗ بِهٖۙ فَاِنَّمَا حِسَابُهٗ عِنْدَ رَبِّهٖۗ اِنَّهٗ لَا يُفْلِحُ الْكٰفِرُوْنَ',
		ayahNumber: 117,
		translationId: 'Dan barang siapa menyembah tuhan yang lain selain Allah, padahal tidak ada suatu bukti pun baginya tentang itu, maka perhitungannya hanya pada Tuhannya. Sesungguhnya orang-orang kafir itu tidak akan beruntung.',
	),
	Ayah(
		ayahId: 2791,
		ayahText: 'وَقُلْ رَّبِّ اغْفِرْ وَارْحَمْ وَاَنْتَ خَيْرُ الرّٰحِمِيْنَ ࣖ',
		ayahNumber: 118,
		translationId: 'Dan katakanlah (Muhammad), “Ya Tuhanku, berilah ampunan dan (berilah) rahmat, Engkaulah pemberi rahmat yang terbaik.”',
	),
];
