// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah68 = [
	Ayah(
		ayahId: 5272,
		ayahText: 'نۤ ۚوَالْقَلَمِ وَمَا يَسْطُرُوْنَۙ',
		ayahNumber: 1,
		translationId: 'Nun. Demi pena dan apa yang mereka tuliskan, ',
	),
	Ayah(
		ayahId: 5273,
		ayahText: 'مَآ اَنْتَ بِنِعْمَةِ رَبِّكَ بِمَجْنُوْنٍ ',
		ayahNumber: 2,
		translationId: 'dengan karunia Tuhanmu engkau (Muhammad) bukanlah orang gila. ',
	),
	Ayah(
		ayahId: 5274,
		ayahText: 'وَاِنَّ لَكَ لَاَجْرًا غَيْرَ مَمْنُوْنٍۚ',
		ayahNumber: 3,
		translationId: 'Dan sesungguhnya engkau pasti mendapat pahala yang besar yang tidak putus-putusnya. ',
	),
	Ayah(
		ayahId: 5275,
		ayahText: 'وَاِنَّكَ لَعَلٰى خُلُقٍ عَظِيْمٍ ',
		ayahNumber: 4,
		translationId: 'Dan sesungguhnya engkau benar-benar berbudi pekerti yang luhur. ',
	),
	Ayah(
		ayahId: 5276,
		ayahText: 'فَسَتُبْصِرُ وَيُبْصِرُوْنَۙ',
		ayahNumber: 5,
		translationId: 'Maka kelak engkau akan melihat dan mereka (orang-orang kafir) pun akan melihat, ',
	),
	Ayah(
		ayahId: 5277,
		ayahText: 'بِاَيِّىكُمُ الْمَفْتُوْنُ ',
		ayahNumber: 6,
		translationId: 'siapa di antara kamu yang gila? ',
	),
	Ayah(
		ayahId: 5278,
		ayahText: 'اِنَّ رَبَّكَ هُوَ اَعْلَمُ بِمَنْ ضَلَّ عَنْ سَبِيْلِهٖۖ وَهُوَ اَعْلَمُ بِالْمُهْتَدِيْنَ ',
		ayahNumber: 7,
		translationId: 'Sungguh, Tuhanmu, Dialah yang paling mengetahui siapa yang sesat dari jalan-Nya; dan Dialah yang paling mengetahui siapa orang yang mendapat petunjuk. ',
	),
	Ayah(
		ayahId: 5279,
		ayahText: 'فَلَا تُطِعِ الْمُكَذِّبِيْنَ ',
		ayahNumber: 8,
		translationId: 'Maka janganlah engkau patuhi orang-orang yang mendustakan (ayat-ayat Allah).',
	),
	Ayah(
		ayahId: 5280,
		ayahText: 'وَدُّوْا لَوْ تُدْهِنُ فَيُدْهِنُوْنَۚ',
		ayahNumber: 9,
		translationId: 'Mereka menginginkan agar engkau bersikap lunak maka mereka bersikap lunak (pula). ',
	),
	Ayah(
		ayahId: 5281,
		ayahText: 'وَلَا تُطِعْ كُلَّ حَلَّافٍ مَّهِيْنٍۙ',
		ayahNumber: 10,
		translationId: 'Dan janganlah engkau patuhi setiap orang yang suka bersumpah dan suka menghina,',
	),
	Ayah(
		ayahId: 5282,
		ayahText: 'هَمَّازٍ مَّشَّاۤءٍۢ بِنَمِيْمٍۙ',
		ayahNumber: 11,
		translationId: 'suka mencela, yang kian ke mari menyebarkan fitnah, ',
	),
	Ayah(
		ayahId: 5283,
		ayahText: 'مَّنَّاعٍ لِّلْخَيْرِ مُعْتَدٍ اَثِيْمٍۙ',
		ayahNumber: 12,
		translationId: 'yang merintangi segala yang baik, yang melampaui batas dan banyak dosa, ',
	),
	Ayah(
		ayahId: 5284,
		ayahText: 'عُتُلٍّۢ بَعْدَ ذٰلِكَ زَنِيْمٍۙ',
		ayahNumber: 13,
		translationId: 'yang bertabiat kasar, selain itu juga terkenal kejahatannya,',
	),
	Ayah(
		ayahId: 5285,
		ayahText: 'اَنْ كَانَ ذَا مَالٍ وَّبَنِيْنَۗ',
		ayahNumber: 14,
		translationId: 'karena dia kaya dan banyak anak.',
	),
	Ayah(
		ayahId: 5286,
		ayahText: 'اِذَا تُتْلٰى عَلَيْهِ اٰيٰتُنَا قَالَ اَسَاطِيْرُ الْاَوَّلِيْنَۗ',
		ayahNumber: 15,
		translationId: 'Apabila ayat-ayat Kami dibacakan kepadanya, dia berkata, “(Ini adalah) dongeng-dongeng orang dahulu.” ',
	),
	Ayah(
		ayahId: 5287,
		ayahText: 'سَنَسِمُهٗ عَلَى الْخُرْطُوْمِ ',
		ayahNumber: 16,
		translationId: 'Kelak dia akan Kami beri tanda pada belalai(nya). ',
	),
	Ayah(
		ayahId: 5288,
		ayahText: 'اِنَّا بَلَوْنٰهُمْ كَمَا بَلَوْنَآ اَصْحٰبَ الْجَنَّةِۚ اِذْ اَقْسَمُوْا لَيَصْرِمُنَّهَا مُصْبِحِيْنَۙ',
		ayahNumber: 17,
		translationId: 'Sungguh, Kami telah menguji mereka (orang musyrik Mekah) sebagaimana Kami telah menguji pemilik-pemilik kebun, ketika mereka bersumpah pasti akan memetik (hasil)nya pada pagi hari,',
	),
	Ayah(
		ayahId: 5289,
		ayahText: 'وَلَا يَسْتَثْنُوْنَ ',
		ayahNumber: 18,
		translationId: 'tetapi mereka tidak menyisihkan (dengan mengucapkan, “Insya Allah”).',
	),
	Ayah(
		ayahId: 5290,
		ayahText: 'فَطَافَ عَلَيْهَا طَاۤىِٕفٌ مِّنْ رَّبِّكَ وَهُمْ نَاۤىِٕمُوْنَ ',
		ayahNumber: 19,
		translationId: 'Lalu kebun itu ditimpa bencana (yang datang) dari Tuhanmu ketika mereka sedang tidur.',
	),
	Ayah(
		ayahId: 5291,
		ayahText: 'فَاَصْبَحَتْ كَالصَّرِيْمِۙ',
		ayahNumber: 20,
		translationId: 'Maka jadilah kebun itu hitam seperti malam yang gelap gulita,',
	),
	Ayah(
		ayahId: 5292,
		ayahText: 'فَتَنَادَوْا مُصْبِحِيْنَۙ',
		ayahNumber: 21,
		translationId: 'lalu pada pagi hari mereka saling memanggil.',
	),
	Ayah(
		ayahId: 5293,
		ayahText: 'اَنِ اغْدُوْا عَلٰى حَرْثِكُمْ اِنْ كُنْتُمْ صَارِمِيْنَ ',
		ayahNumber: 22,
		translationId: '”Pergilah pagi-pagi ke kebunmu jika kamu hendak memetik hasil.” ',
	),
	Ayah(
		ayahId: 5294,
		ayahText: 'فَانْطَلَقُوْا وَهُمْ يَتَخَافَتُوْنَۙ',
		ayahNumber: 23,
		translationId: 'Maka mereka pun berangkat sambil berbisik-bisik. ',
	),
	Ayah(
		ayahId: 5295,
		ayahText: 'اَنْ لَّا يَدْخُلَنَّهَا الْيَوْمَ عَلَيْكُمْ مِّسْكِيْنٌۙ',
		ayahNumber: 24,
		translationId: '”Pada hari ini jangan sampai ada orang miskin masuk ke dalam kebunmu.” ',
	),
	Ayah(
		ayahId: 5296,
		ayahText: 'وَّغَدَوْا عَلٰى حَرْدٍ قَادِرِيْنَ ',
		ayahNumber: 25,
		translationId: 'Dan berangkatlah mereka pada pagi hari dengan niat menghalangi (orang-orang miskin) padahal mereka mampu (menolongnya). ',
	),
	Ayah(
		ayahId: 5297,
		ayahText: 'فَلَمَّا رَاَوْهَا قَالُوْٓا اِنَّا لَضَاۤلُّوْنَۙ',
		ayahNumber: 26,
		translationId: 'Maka ketika mereka melihat kebun itu, mereka berkata, “Sungguh, kita ini benar-benar orang-orang yang sesat,',
	),
	Ayah(
		ayahId: 5298,
		ayahText: 'بَلْ نَحْنُ مَحْرُوْمُوْنَ ',
		ayahNumber: 27,
		translationId: 'bahkan kita tidak memperoleh apa pun,”',
	),
	Ayah(
		ayahId: 5299,
		ayahText: 'قَالَ اَوْسَطُهُمْ اَلَمْ اَقُلْ لَّكُمْ لَوْلَا تُسَبِّحُوْنَ ',
		ayahNumber: 28,
		translationId: 'berkatalah seorang yang paling bijak di antara mereka, “Bukankah aku telah mengatakan kepadamu, mengapa kamu tidak bertasbih (kepada Tuhanmu).”',
	),
	Ayah(
		ayahId: 5300,
		ayahText: 'قَالُوْا سُبْحٰنَ رَبِّنَآ اِنَّا كُنَّا ظٰلِمِيْنَ ',
		ayahNumber: 29,
		translationId: 'Mereka mengucapkan, “Mahasuci Tuhan kami, sungguh, kami adalah orang-orang yang zalim.” ',
	),
	Ayah(
		ayahId: 5301,
		ayahText: 'فَاَقْبَلَ بَعْضُهُمْ عَلٰى بَعْضٍ يَّتَلَاوَمُوْنَ ',
		ayahNumber: 30,
		translationId: 'Lalu mereka saling berhadapan dan saling menyalahkan.',
	),
	Ayah(
		ayahId: 5302,
		ayahText: 'قَالُوْا يٰوَيْلَنَآ اِنَّا كُنَّا طٰغِيْنَ ',
		ayahNumber: 31,
		translationId: 'Mereka berkata, “Celaka kita! Sesungguhnya kita orang-orang yang melampaui batas. ',
	),
	Ayah(
		ayahId: 5303,
		ayahText: 'عَسٰى رَبُّنَآ اَنْ يُّبْدِلَنَا خَيْرًا مِّنْهَآ اِنَّآ اِلٰى رَبِّنَا رَاغِبُوْنَ ',
		ayahNumber: 32,
		translationId: 'Mudah-mudahan Tuhan memberikan ganti kepada kita dengan (kebun) yang lebih baik daripada yang ini, sungguh, kita mengharapkan ampunan dari Tuhan kita.” ',
	),
	Ayah(
		ayahId: 5304,
		ayahText: 'كَذٰلِكَ الْعَذَابُۗ وَلَعَذَابُ الْاٰخِرَةِ اَكْبَرُۘ لَوْ كَانُوْا يَعْلَمُوْنَ ࣖ ',
		ayahNumber: 33,
		translationId: 'Seperti itulah azab (di dunia). Dan sungguh, azab akhirat lebih besar se-kiranya mereka mengetahui.',
	),
	Ayah(
		ayahId: 5305,
		ayahText: 'اِنَّ لِلْمُتَّقِيْنَ عِنْدَ رَبِّهِمْ جَنّٰتِ النَّعِيْمِ ',
		ayahNumber: 34,
		translationId: 'Sungguh, bagi orang-orang yang bertakwa (disediakan) surga yang penuh kenikmatan di sisi Tuhannya.',
	),
	Ayah(
		ayahId: 5306,
		ayahText: 'اَفَنَجْعَلُ الْمُسْلِمِيْنَ كَالْمُجْرِمِيْنَۗ',
		ayahNumber: 35,
		translationId: 'Apakah patut Kami memperlakukan orang-orang Islam itu seperti orang-orang yang berdosa (orang kafir)?',
	),
	Ayah(
		ayahId: 5307,
		ayahText: 'مَا لَكُمْۗ  كَيْفَ تَحْكُمُوْنَۚ',
		ayahNumber: 36,
		translationId: 'Mengapa kamu (berbuat demikian)? Bagaimana kamu mengambil keputusan?',
	),
	Ayah(
		ayahId: 5308,
		ayahText: 'اَمْ لَكُمْ كِتٰبٌ فِيْهِ تَدْرُسُوْنَۙ',
		ayahNumber: 37,
		translationId: 'Atau apakah kamu mempunyai kitab (yang diturunkan Allah) yang kamu pelajari?  ',
	),
	Ayah(
		ayahId: 5309,
		ayahText: 'اِنَّ لَكُمْ فِيْهِ لَمَا تَخَيَّرُوْنَۚ',
		ayahNumber: 38,
		translationId: 'sesungguhnya kamu dapat memilih apa saja yang ada di dalamnya.',
	),
	Ayah(
		ayahId: 5310,
		ayahText: 'اَمْ لَكُمْ اَيْمَانٌ عَلَيْنَا بَالِغَةٌ اِلٰى يَوْمِ الْقِيٰمَةِۙ اِنَّ لَكُمْ لَمَا تَحْكُمُوْنَۚ',
		ayahNumber: 39,
		translationId: 'Atau apakah kamu memperoleh (janji-janji yang diperkuat dengan) sumpah dari Kami, yang tetap berlaku sampai hari Kiamat; bahwa kamu dapat mengambil keputusan (sekehendakmu)? ',
	),
	Ayah(
		ayahId: 5311,
		ayahText: 'سَلْهُمْ اَيُّهُمْ بِذٰلِكَ زَعِيْمٌۚ',
		ayahNumber: 40,
		translationId: 'Tanyakanlah kepada mereka, “Siapakah di antara mereka yang bertanggung jawab terhadap (keputusan yang diambil itu)?”',
	),
	Ayah(
		ayahId: 5312,
		ayahText: 'اَمْ لَهُمْ شُرَكَاۤءُۚ فَلْيَأْتُوْا بِشُرَكَاۤىِٕهِمْ اِنْ كَانُوْا صٰدِقِيْنَ ',
		ayahNumber: 41,
		translationId: 'Atau apakah mereka mempunyai sekutu-sekutu? Kalau begitu hendaklah mereka mendatangkan sekutu-sekutunya jika mereka orang-orang yang benar.',
	),
	Ayah(
		ayahId: 5313,
		ayahText: 'يَوْمَ يُكْشَفُ عَنْ سَاقٍ وَّيُدْعَوْنَ اِلَى السُّجُوْدِ فَلَا يَسْتَطِيْعُوْنَۙ',
		ayahNumber: 42,
		translationId: '(Ingatlah) pada hari ketika betis disingkapkan dan mereka diseru untuk bersujud; maka mereka tidak mampu,',
	),
	Ayah(
		ayahId: 5314,
		ayahText: 'خَاشِعَةً اَبْصَارُهُمْ تَرْهَقُهُمْ ذِلَّةٌ  ۗوَقَدْ كَانُوْا يُدْعَوْنَ اِلَى السُّجُوْدِ وَهُمْ سَالِمُوْنَ ',
		ayahNumber: 43,
		translationId: 'pandangan mereka tertunduk ke bawah, diliputi kehinaan. Dan sungguh, dahulu (di dunia) mereka telah diseru untuk bersujud pada waktu mereka sehat (tetapi mereka tidak melakukan). ',
	),
	Ayah(
		ayahId: 5315,
		ayahText: 'فَذَرْنِيْ وَمَنْ يُّكَذِّبُ بِهٰذَا الْحَدِيْثِۗ سَنَسْتَدْرِجُهُمْ مِّنْ حَيْثُ لَا يَعْلَمُوْنَۙ',
		ayahNumber: 44,
		translationId: "Maka serahkanlah kepada-Ku (urusannya) dan orang-orang yang mendustakan perkataan ini (Al-Qur'an). Kelak akan Kami hukum mereka berangsur-angsur dari arah yang tidak mereka ketahui, ",
	),
	Ayah(
		ayahId: 5316,
		ayahText: 'وَاُمْلِيْ لَهُمْۗ اِنَّ كَيْدِيْ مَتِيْنٌ ',
		ayahNumber: 45,
		translationId: 'dan Aku memberi tenggang waktu kepada mereka. Sungguh, rencana-Ku sangat teguh. ',
	),
	Ayah(
		ayahId: 5317,
		ayahText: 'اَمْ تَسْـَٔلُهُمْ اَجْرًا فَهُمْ مِّنْ مَّغْرَمٍ مُّثْقَلُوْنَۚ ',
		ayahNumber: 46,
		translationId: 'Ataukah engkau (Muhammad) meminta imbalan kepada mereka, sehingga mereka dibebani dengan utang?',
	),
	Ayah(
		ayahId: 5318,
		ayahText: 'اَمْ عِنْدَهُمُ الْغَيْبُ فَهُمْ يَكْتُبُوْنَ ',
		ayahNumber: 47,
		translationId: 'Ataukah mereka mengetahui yang gaib, lalu mereka menuliskannya?',
	),
	Ayah(
		ayahId: 5319,
		ayahText: 'فَاصْبِرْ لِحُكْمِ رَبِّكَ وَلَا تَكُنْ كَصَاحِبِ الْحُوْتِۘ اِذْ نَادٰى وَهُوَ مَكْظُوْمٌۗ',
		ayahNumber: 48,
		translationId: 'Maka bersabarlah engkau (Muhammad) terhadap ketetapan Tuhanmu, dan janganlah engkau seperti (Yunus) orang yang berada dalam (perut) ikan ketika dia berdoa dengan hati sedih.',
	),
	Ayah(
		ayahId: 5320,
		ayahText: 'لَوْلَآ اَنْ تَدَارَكَهٗ نِعْمَةٌ مِّنْ رَّبِّهٖ لَنُبِذَ بِالْعَرَاۤءِ وَهُوَ مَذْمُوْمٌ ',
		ayahNumber: 49,
		translationId: 'Sekiranya dia tidak segera mendapat nikmat dari Tuhannya, pastilah dia dicampakkan ke tanah tandus dalam keadaan tercela. ',
	),
	Ayah(
		ayahId: 5321,
		ayahText: 'فَاجْتَبٰىهُ رَبُّهٗ فَجَعَلَهٗ مِنَ الصّٰلِحِيْنَ ',
		ayahNumber: 50,
		translationId: 'Lalu Tuhannya memilihnya dan menjadikannya termasuk orang yang saleh. ',
	),
	Ayah(
		ayahId: 5322,
		ayahText: 'وَاِنْ يَّكَادُ الَّذِيْنَ كَفَرُوْا لَيُزْلِقُوْنَكَ بِاَبْصَارِهِمْ لَمَّا سَمِعُوا الذِّكْرَ وَيَقُوْلُوْنَ اِنَّهٗ لَمَجْنُوْنٌ ۘ',
		ayahNumber: 51,
		translationId: "Dan sungguh, orang-orang kafir itu hampir-hampir menggelincirkanmu dengan pandangan mata mereka, ketika mereka mendengar Al-Qur'an dan mereka berkata, “Dia (Muhammad) itu benar-benar orang gila.”",
	),
	Ayah(
		ayahId: 5323,
		ayahText: 'وَمَا هُوَ اِلَّا ذِكْرٌ لِّلْعٰلَمِيْنَ ࣖ ',
		ayahNumber: 52,
		translationId: "Padahal (Al-Qur'an) itu tidak lain adalah peringatan bagi seluruh alam.",
	),
];
