// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah20 = [
	Ayah(
		ayahId: 2349,
		ayahText: 'طٰهٰ ۚ',
		ayahNumber: 1,
		translationId: 'Thaha',
	),
	Ayah(
		ayahId: 2350,
		ayahText: 'مَآ اَنْزَلْنَا عَلَيْكَ الْقُرْاٰنَ لِتَشْقٰٓى ۙ',
		ayahNumber: 2,
		translationId: " Kami tidak menurunkan Al-Qur'an ini kepadamu (Muhammad) agar engkau menjadi susah;",
	),
	Ayah(
		ayahId: 2351,
		ayahText: 'اِلَّا تَذْكِرَةً لِّمَنْ يَّخْشٰى ۙ',
		ayahNumber: 3,
		translationId: ' melainkan sebagai peringatan bagi orang yang takut (kepada Allah),',
	),
	Ayah(
		ayahId: 2352,
		ayahText: 'تَنْزِيْلًا مِّمَّنْ خَلَقَ الْاَرْضَ وَالسَّمٰوٰتِ الْعُلٰى ۗ',
		ayahNumber: 4,
		translationId: 'diturunkan dari (Allah) yang menciptakan bumi dan langit yang tinggi,',
	),
	Ayah(
		ayahId: 2353,
		ayahText: 'اَلرَّحْمٰنُ عَلَى الْعَرْشِ اسْتَوٰى ',
		ayahNumber: 5,
		translationId: '(yaitu) Yang Maha Pengasih, yang bersemayam di atas ‘Arsy.',
	),
	Ayah(
		ayahId: 2354,
		ayahText: 'لَهٗ مَا فِى السَّمٰوٰتِ وَمَا فِى الْاَرْضِ وَمَا بَيْنَهُمَا وَمَا تَحْتَ الثَّرٰى ',
		ayahNumber: 6,
		translationId: 'Milik-Nyalah apa yang ada di langit, apa yang ada di bumi, apa yang ada di antara keduanya, dan apa yang ada di bawah tanah.',
	),
	Ayah(
		ayahId: 2355,
		ayahText: 'وَاِنْ تَجْهَرْ بِالْقَوْلِ فَاِنَّهٗ يَعْلَمُ السِّرَّ وَاَخْفٰى ',
		ayahNumber: 7,
		translationId: 'Dan jika engkau mengeraskan ucapanmu, sungguh, Dia mengetahui rahasia dan yang lebih tersembunyi.',
	),
	Ayah(
		ayahId: 2356,
		ayahText: 'اَللّٰهُ لَآ اِلٰهَ اِلَّا هُوَۗ  لَهُ الْاَسْمَاۤءُ الْحُسْنٰى ',
		ayahNumber: 8,
		translationId: '(Dialah) Allah, tidak ada tuhan selain Dia, yang mempunyai nama-nama yang terbaik.',
	),
	Ayah(
		ayahId: 2357,
		ayahText: 'وَهَلْ اَتٰىكَ حَدِيْثُ مُوْسٰى ۘ',
		ayahNumber: 9,
		translationId: ' Dan apakah telah sampai kepadamu kisah Musa?',
	),
	Ayah(
		ayahId: 2358,
		ayahText: 'اِذْ رَاٰ نَارًا فَقَالَ لِاَهْلِهِ امْكُثُوْٓا اِنِّيْ اٰنَسْتُ نَارًا لَّعَلِّيْٓ اٰتِيْكُمْ مِّنْهَا بِقَبَسٍ اَوْ اَجِدُ عَلَى النَّارِ هُدًى ',
		ayahNumber: 10,
		translationId: ' Ketika dia (Musa) melihat api, lalu dia berkata kepada keluarganya, “Tinggallah kamu (di sini), sesungguhnya aku melihat api, mudah-mudahan aku dapat membawa sedikit nyala api kepadamu atau aku akan mendapat petunjuk di tempat api itu.”',
	),
	Ayah(
		ayahId: 2359,
		ayahText: 'فَلَمَّآ اَتٰىهَا نُوْدِيَ يٰمُوْسٰٓى ۙ',
		ayahNumber: 11,
		translationId: 'Maka ketika dia mendatanginya (ke tempat api itu) dia dipanggil, “Wahai Musa!',
	),
	Ayah(
		ayahId: 2360,
		ayahText: 'اِنِّيْٓ اَنَا۠ رَبُّكَ فَاخْلَعْ نَعْلَيْكَۚ اِنَّكَ بِالْوَادِ الْمُقَدَّسِ طُوًى ۗ',
		ayahNumber: 12,
		translationId: 'Sungguh, Aku adalah Tuhanmu, maka lepaskan kedua terompahmu. Karena sesungguhnya engkau berada di lembah yang suci, Tuwa.',
	),
	Ayah(
		ayahId: 2361,
		ayahText: 'وَاَنَا اخْتَرْتُكَ فَاسْتَمِعْ لِمَا يُوْحٰى ',
		ayahNumber: 13,
		translationId: ' Dan Aku telah memilih engkau, maka dengarkanlah apa yang akan diwahyukan (kepadamu).',
	),
	Ayah(
		ayahId: 2362,
		ayahText: 'اِنَّنِيْٓ اَنَا اللّٰهُ لَآ اِلٰهَ اِلَّآ اَنَا۠ فَاعْبُدْنِيْۙ وَاَقِمِ الصَّلٰوةَ لِذِكْرِيْ ',
		ayahNumber: 14,
		translationId: ' Sungguh, Aku ini Allah, tidak ada tuhan selain Aku, maka sembahlah Aku dan laksanakanlah salat untuk mengingat Aku.',
	),
	Ayah(
		ayahId: 2363,
		ayahText: 'اِنَّ السَّاعَةَ اٰتِيَةٌ اَكَادُ اُخْفِيْهَا لِتُجْزٰى كُلُّ نَفْسٍۢ بِمَا تَسْعٰى ',
		ayahNumber: 15,
		translationId: 'Sungguh, hari Kiamat itu akan datang, Aku merahasiakan (waktunya) agar setiap orang dibalas sesuai dengan apa yang telah dia usahakan.',
	),
	Ayah(
		ayahId: 2364,
		ayahText: 'فَلَا يَصُدَّنَّكَ عَنْهَا مَنْ لَّا يُؤْمِنُ بِهَا وَاتَّبَعَ هَوٰىهُ فَتَرْدٰى ',
		ayahNumber: 16,
		translationId: ' Maka janganlah engkau dipalingkan dari (Kiamat itu) oleh orang yang tidak beriman kepadanya dan oleh orang yang mengikuti keinginannya, yang menyebabkan engkau binasa.”',
	),
	Ayah(
		ayahId: 2365,
		ayahText: 'وَمَا تِلْكَ بِيَمِيْنِكَ يٰمُوْسٰى ',
		ayahNumber: 17,
		translationId: '”Dan apakah yang ada di tangan kananmu, wahai Musa? ”',
	),
	Ayah(
		ayahId: 2366,
		ayahText: 'قَالَ هِيَ عَصَايَۚ اَتَوَكَّؤُا عَلَيْهَا وَاَهُشُّ بِهَا عَلٰى غَنَمِيْ وَلِيَ فِيْهَا مَاٰرِبُ اُخْرٰى ',
		ayahNumber: 18,
		translationId: 'Dia (Musa) berkata, “Ini adalah tongkatku, aku bertumpu padanya, dan aku merontokkan (daun-daun) dengannya untuk (makanan) kambingku, dan bagiku masih ada lagi manfaat yang lain.”',
	),
	Ayah(
		ayahId: 2367,
		ayahText: 'قَالَ اَلْقِهَا يٰمُوْسٰى ',
		ayahNumber: 19,
		translationId: 'Dia (Allah) berfirman, “Lemparkanlah ia, wahai Musa!”',
	),
	Ayah(
		ayahId: 2368,
		ayahText: 'فَاَلْقٰىهَا فَاِذَا هِيَ حَيَّةٌ تَسْعٰى ',
		ayahNumber: 20,
		translationId: ' Lalu (Musa) melemparkan tongkat itu, maka tiba-tiba ia menjadi seekor ular yang merayap dengan cepat.',
	),
	Ayah(
		ayahId: 2369,
		ayahText: 'قَالَ خُذْهَا وَلَا تَخَفْۗ سَنُعِيْدُهَا سِيْرَتَهَا الْاُوْلٰى ',
		ayahNumber: 21,
		translationId: 'Dia (Allah) berfirman, “Peganglah ia dan jangan takut, Kami akan mengembalikannya kepada keadaannya semula,',
	),
	Ayah(
		ayahId: 2370,
		ayahText: 'وَاضْمُمْ يَدَكَ اِلٰى جَنَاحِكَ تَخْرُجْ بَيْضَاۤءَ مِنْ غَيْرِ سُوْۤءٍ اٰيَةً اُخْرٰىۙ ',
		ayahNumber: 22,
		translationId: 'dan kepitlah tanganmu ke ketiakmu, niscaya ia keluar menjadi putih (bercahaya) tanpa cacat, sebagai mukjizat yang lain,',
	),
	Ayah(
		ayahId: 2371,
		ayahText: 'لِنُرِيَكَ مِنْ اٰيٰتِنَا الْكُبْرٰى ۚ',
		ayahNumber: 23,
		translationId: 'untuk Kami perlihatkan kepadamu (sebagian) dari tanda-tanda kebesaran Kami yang sangat besar,',
	),
	Ayah(
		ayahId: 2372,
		ayahText: 'اِذْهَبْ اِلٰى فِرْعَوْنَ اِنَّهٗ طَغٰى ࣖ',
		ayahNumber: 24,
		translationId: 'Pergilah kepada Fir‘aun; dia benar-benar telah melampaui batas.”',
	),
	Ayah(
		ayahId: 2373,
		ayahText: 'قَالَ رَبِّ اشْرَحْ لِيْ صَدْرِيْ ۙ',
		ayahNumber: 25,
		translationId: ' Dia (Musa) berkata, “Ya Tuhanku, lapangkanlah dadaku,',
	),
	Ayah(
		ayahId: 2374,
		ayahText: 'وَيَسِّرْ لِيْٓ اَمْرِيْ ۙ',
		ayahNumber: 26,
		translationId: 'dan mudahkanlah untukku urusanku, ',
	),
	Ayah(
		ayahId: 2375,
		ayahText: 'وَاحْلُلْ عُقْدَةً مِّنْ لِّسَانِيْ ۙ',
		ayahNumber: 27,
		translationId: 'dan lepaskanlah kekakuan dari lidahku,',
	),
	Ayah(
		ayahId: 2376,
		ayahText: 'يَفْقَهُوْا قَوْلِيْ  ۖ',
		ayahNumber: 28,
		translationId: 'agar mereka mengerti perkataanku,',
	),
	Ayah(
		ayahId: 2377,
		ayahText: 'وَاجْعَلْ لِّيْ وَزِيْرًا مِّنْ اَهْلِيْ ۙ',
		ayahNumber: 29,
		translationId: 'dan jadikanlah untukku seorang pembantu dari keluargaku,',
	),
	Ayah(
		ayahId: 2378,
		ayahText: 'هٰرُوْنَ اَخِى ۙ',
		ayahNumber: 30,
		translationId: '(yaitu) Harun, saudaraku,',
	),
	Ayah(
		ayahId: 2379,
		ayahText: 'اشْدُدْ بِهٖٓ اَزْرِيْ ۙ',
		ayahNumber: 31,
		translationId: 'teguhkanlah kekuatanku dengan (adanya) dia,',
	),
	Ayah(
		ayahId: 2380,
		ayahText: 'وَاَشْرِكْهُ فِيْٓ اَمْرِيْ ۙ',
		ayahNumber: 32,
		translationId: 'dan jadikanlah dia teman dalam urusanku,',
	),
	Ayah(
		ayahId: 2381,
		ayahText: 'كَيْ نُسَبِّحَكَ كَثِيْرًا ۙ',
		ayahNumber: 33,
		translationId: 'agar kami banyak bertasbih kepada-Mu,',
	),
	Ayah(
		ayahId: 2382,
		ayahText: 'وَّنَذْكُرَكَ كَثِيْرًا ۗ',
		ayahNumber: 34,
		translationId: 'dan banyak mengingat-Mu,',
	),
	Ayah(
		ayahId: 2383,
		ayahText: 'اِنَّكَ كُنْتَ بِنَا بَصِيْرًا ',
		ayahNumber: 35,
		translationId: 'sesungguhnya Engkau Maha Melihat (keadaan) kami.”',
	),
	Ayah(
		ayahId: 2384,
		ayahText: 'قَالَ قَدْ اُوْتِيْتَ سُؤْلَكَ يٰمُوْسٰى ',
		ayahNumber: 36,
		translationId: 'Dia (Allah) berfirman, “Sungguh, telah diperkenankan permintaanmu, wahai Musa!',
	),
	Ayah(
		ayahId: 2385,
		ayahText: 'وَلَقَدْ مَنَنَّا عَلَيْكَ مَرَّةً اُخْرٰىٓ ۙ',
		ayahNumber: 37,
		translationId: 'Dan sungguh, Kami telah memberi nikmat kepadamu pada kesempatan yang lain (sebelum ini),',
	),
	Ayah(
		ayahId: 2386,
		ayahText: 'اِذْ اَوْحَيْنَآ اِلٰٓى اُمِّكَ مَا يُوْحٰىٓ ۙ',
		ayahNumber: 38,
		translationId: '(yaitu) ketika Kami mengilhamkan kepada ibumu sesuatu yang diilhamkan,',
	),
	Ayah(
		ayahId: 2387,
		ayahText: 'اَنِ اقْذِفِيْهِ فِى التَّابُوْتِ فَاقْذِفِيْهِ فِى الْيَمِّ فَلْيُلْقِهِ الْيَمُّ بِالسَّاحِلِ يَأْخُذْهُ عَدُوٌّ لِّيْ وَعَدُوٌّ لَّهٗ  ۗوَاَلْقَيْتُ عَلَيْكَ مَحَبَّةً مِّنِّيْ ەۚ وَلِتُصْنَعَ عَلٰى عَيْنِيْ ۘ',
		ayahNumber: 39,
		translationId: '(yaitu), letakkanlah dia (Musa) di dalam peti, kemudian hanyutkanlah dia ke sungai (Nil), maka biarlah (arus) sungai itu membawanya ke tepi, dia akan diambil oleh (Fir‘aun) musuh-Ku dan musuhnya. Aku telah melimpahkan kepadamu kasih sayang yang datang dari-Ku; dan agar engkau diasuh di bawah pengawasan-Ku.',
	),
	Ayah(
		ayahId: 2388,
		ayahText: 'اِذْ تَمْشِيْٓ اُخْتُكَ فَتَقُوْلُ هَلْ اَدُلُّكُمْ عَلٰى مَنْ يَّكْفُلُهٗ ۗفَرَجَعْنٰكَ اِلٰٓى اُمِّكَ كَيْ تَقَرَّ عَيْنُهَا وَلَا تَحْزَنَ ەۗ وَقَتَلْتَ نَفْسًا فَنَجَّيْنٰكَ مِنَ الْغَمِّ وَفَتَنّٰكَ فُتُوْنًا ەۗ فَلَبِثْتَ سِنِيْنَ فِيْٓ اَهْلِ مَدْيَنَ ەۙ ثُمَّ جِئْتَ عَلٰى قَدَرٍ يّٰمُوْسٰى',
		ayahNumber: 40,
		translationId: '(Yaitu) ketika saudara perempuanmu berjalan, lalu dia berkata (kepada keluarga Fir‘aun), ‘Bolehkah saya menunjukkan kepadamu orang yang akan memeliharanya?’ Maka Kami mengembalikanmu kepada ibumu, agar senang hatinya dan tidak bersedih hati. Dan engkau pernah membunuh seseorang, lalu Kami selamatkan engkau dari kesulitan (yang besar) dan Kami telah mencobamu dengan beberapa cobaan (yang berat); lalu engkau tinggal beberapa tahun di antara penduduk Madyan, kemudian engkau, wahai Musa, datang menurut waktu yang ditetapkan,',
	),
	Ayah(
		ayahId: 2389,
		ayahText: 'وَاصْطَنَعْتُكَ لِنَفْسِيْۚ  ',
		ayahNumber: 41,
		translationId: 'dan Aku telah memilihmu (menjadi rasul) untuk diri-Ku.',
	),
	Ayah(
		ayahId: 2390,
		ayahText: 'اِذْهَبْ اَنْتَ وَاَخُوْكَ بِاٰيٰتِيْ وَلَا تَنِيَا فِيْ ذِكْرِيْۚ  ',
		ayahNumber: 42,
		translationId: 'Pergilah engkau beserta saudaramu dengan membawa tanda-tanda (kekuasaan)-Ku, dan janganlah kamu berdua lalai mengingat-Ku;',
	),
	Ayah(
		ayahId: 2391,
		ayahText: 'اِذْهَبَآ اِلٰى فِرْعَوْنَ اِنَّهٗ طَغٰىۚ ',
		ayahNumber: 43,
		translationId: 'pergilah kamu berdua kepada Fir‘aun, karena dia benar-benar telah melampaui batas;',
	),
	Ayah(
		ayahId: 2392,
		ayahText: 'فَقُوْلَا لَهٗ قَوْلًا لَّيِّنًا لَّعَلَّهٗ يَتَذَكَّرُ اَوْ يَخْشٰى ',
		ayahNumber: 44,
		translationId: 'maka berbicaralah kamu berdua kepadanya (Fir‘aun) dengan kata-kata yang lemah lembut, mudah-mudahan dia sadar atau takut.',
	),
	Ayah(
		ayahId: 2393,
		ayahText: 'قَالَا رَبَّنَآ اِنَّنَا نَخَافُ اَنْ يَّفْرُطَ عَلَيْنَآ اَوْ اَنْ يَّطْغٰى ',
		ayahNumber: 45,
		translationId: 'Keduanya berkata, “Ya Tuhan kami, sungguh, kami khawatir dia akan segera menyiksa kami atau akan bertambah melampaui batas,”',
	),
	Ayah(
		ayahId: 2394,
		ayahText: 'قَالَ لَا تَخَافَآ اِنَّنِيْ مَعَكُمَآ اَسْمَعُ وَاَرٰى ',
		ayahNumber: 46,
		translationId: 'Dia (Allah) berfirman, “Janganlah kamu berdua khawatir, sesungguhnya Aku bersama kamu berdua, Aku mendengar dan melihat.',
	),
	Ayah(
		ayahId: 2395,
		ayahText: 'فَأْتِيٰهُ فَقُوْلَآ اِنَّا رَسُوْلَا رَبِّكَ فَاَرْسِلْ مَعَنَا بَنِيْٓ اِسْرَاۤءِيْلَ ەۙ وَلَا تُعَذِّبْهُمْۗ قَدْ جِئْنٰكَ بِاٰيَةٍ مِّنْ رَّبِّكَ ۗوَالسَّلٰمُ عَلٰى مَنِ اتَّبَعَ الْهُدٰى',
		ayahNumber: 47,
		translationId: 'Maka pergilah kamu berdua kepadanya (Fir‘aun) dan katakanlah, “Sungguh, kami berdua adalah utusan Tuhanmu, maka lepaskanlah Bani Israil bersama kami dan janganlah engkau menyiksa mereka. Sungguh, kami datang kepadamu dengan membawa bukti (atas kerasulan kami) dari Tuhanmu. Dan keselamatan itu dilimpahkan kepada orang yang mengikuti petunjuk.',
	),
	Ayah(
		ayahId: 2396,
		ayahText: 'اِنَّا قَدْ اُوْحِيَ اِلَيْنَآ اَنَّ الْعَذَابَ عَلٰى مَنْ كَذَّبَ وَتَوَلّٰى ',
		ayahNumber: 48,
		translationId: 'Sungguh, telah diwahyukan kepada kami bahwa siksa itu (ditimpakan) pada siapa pun yang mendustakan (ajaran agama yang kami bawa) dan berpaling (tidak mempedulikannya).”',
	),
	Ayah(
		ayahId: 2397,
		ayahText: 'قَالَ فَمَنْ رَّبُّكُمَا يٰمُوْسٰى ',
		ayahNumber: 49,
		translationId: 'Dia (Fir‘aun) berkata, “Siapakah Tuhanmu berdua, wahai Musa?”',
	),
	Ayah(
		ayahId: 2398,
		ayahText: 'قَالَ رَبُّنَا الَّذِيْٓ اَعْطٰى كُلَّ شَيْءٍ خَلْقَهٗ ثُمَّ هَدٰى ',
		ayahNumber: 50,
		translationId: 'Dia (Musa) menjawab, “Tuhan kami ialah (Tuhan) yang telah memberikan bentuk kejadian kepada segala sesuatu, kemudian memberinya petunjuk.”',
	),
	Ayah(
		ayahId: 2399,
		ayahText: 'قَالَ فَمَا بَالُ الْقُرُوْنِ الْاُوْلٰى ',
		ayahNumber: 51,
		translationId: 'Dia (Fir‘aun) berkata, “Jadi bagaimana keadaan umat-umat yang dahulu?”',
	),
	Ayah(
		ayahId: 2400,
		ayahText: 'قَالَ عِلْمُهَا عِنْدَ رَبِّيْ فِيْ كِتٰبٍۚ  لَا يَضِلُّ رَبِّيْ وَلَا يَنْسَىۖ ',
		ayahNumber: 52,
		translationId: 'Dia (Musa) menjawab, “Pengetahuan tentang itu ada pada Tuhanku, di dalam sebuah Kitab (Lauh Mahfuzh), Tuhanku tidak akan salah ataupun lupa;',
	),
	Ayah(
		ayahId: 2401,
		ayahText: 'الَّذِيْ جَعَلَ لَكُمُ الْاَرْضَ مَهْدًا وَّسَلَكَ لَكُمْ فِيْهَا سُبُلًا وَّاَنْزَلَ مِنَ السَّمَاۤءِ مَاۤءًۗ فَاَخْرَجْنَا بِهٖٓ اَزْوَاجًا مِّنْ نَّبَاتٍ شَتّٰى ',
		ayahNumber: 53,
		translationId: '(Tuhan) yang telah menjadikan bumi sebagai hamparan bagimu, dan menjadikan jalan-jalan di atasnya bagimu, dan yang menurunkan air (hujan) dari langit.” Kemudian Kami tumbuhkan dengannya (air hujan itu) berjenis-jenis aneka macam tumbuh-tumbuhan.',
	),
	Ayah(
		ayahId: 2402,
		ayahText: 'كُلُوْا وَارْعَوْا اَنْعَامَكُمْ ۗاِنَّ فِيْ ذٰلِكَ لَاٰيٰتٍ لِّاُولِى النُّهٰى ࣖ',
		ayahNumber: 54,
		translationId: 'Makanlah dan gembalakanlah hewan-hewanmu. Sungguh, pada yang demikian itu, terdapat tanda-tanda (kebesaran Allah) bagi orang yang berakal.',
	),
	Ayah(
		ayahId: 2403,
		ayahText: '۞ مِنْهَا خَلَقْنٰكُمْ وَفِيْهَا نُعِيْدُكُمْ وَمِنْهَا نُخْرِجُكُمْ تَارَةً اُخْرٰى ',
		ayahNumber: 55,
		translationId: 'Darinya (tanah) itulah Kami menciptakan kamu dan kepadanyalah Kami akan mengembalikan kamu dan dari sanalah Kami akan mengeluarkan kamu pada waktu yang lain.',
	),
	Ayah(
		ayahId: 2404,
		ayahText: 'وَلَقَدْ اَرَيْنٰهُ اٰيٰتِنَا كُلَّهَا فَكَذَّبَ وَاَبٰى ',
		ayahNumber: 56,
		translationId: 'Dan sungguh, Kami telah memperlihatkan kepadanya (Fir‘aun) tanda-tanda (kebesaran) Kami semuanya, ternyata dia mendustakan dan enggan (menerima kebenaran).',
	),
	Ayah(
		ayahId: 2405,
		ayahText: 'قَالَ اَجِئْتَنَا لِتُخْرِجَنَا مِنْ اَرْضِنَا بِسِحْرِكَ يٰمُوْسٰى ',
		ayahNumber: 57,
		translationId: 'Dia (Fir‘aun) berkata, “Apakah engkau datang kepada kami untuk mengusir kami dari negeri kami dengan sihirmu, wahai Musa?',
	),
	Ayah(
		ayahId: 2406,
		ayahText: 'فَلَنَأْتِيَنَّكَ بِسِحْرٍ مِّثْلِهٖ فَاجْعَلْ بَيْنَنَا وَبَيْنَكَ مَوْعِدًا لَّا نُخْلِفُهٗ نَحْنُ وَلَآ اَنْتَ مَكَانًا سُوًى ',
		ayahNumber: 58,
		translationId: 'Maka kami pun pasti akan mendatangkan sihir semacam itu kepadamu, maka buatlah suatu perjanjian untuk pertemuan antara kami dan engkau yang kami tidak akan menyalahinya dan tidak (pula) engkau, di suatu tempat yang terbuka.”',
	),
	Ayah(
		ayahId: 2407,
		ayahText: 'قَالَ مَوْعِدُكُمْ يَوْمُ الزِّيْنَةِ وَاَنْ يُّحْشَرَ النَّاسُ ضُحًى ',
		ayahNumber: 59,
		translationId: 'Dia (Musa) berkata, “(Perjanjian) waktu (untuk pertemuan kami dengan kamu itu) ialah pada hari raya dan hendaklah orang-orang dikumpulkan pada pagi hari (duha).”',
	),
	Ayah(
		ayahId: 2408,
		ayahText: 'فَتَوَلّٰى فِرْعَوْنُ فَجَمَعَ كَيْدَهٗ ثُمَّ اَتٰى ',
		ayahNumber: 60,
		translationId: 'Maka Fir‘aun meninggalkan (tempat itu), lalu mengatur tipu dayanya, kemudian dia datang kembali (pada hari yang ditentukan).',
	),
	Ayah(
		ayahId: 2409,
		ayahText: 'قَالَ لَهُمْ مُّوْسٰى وَيْلَكُمْ لَا تَفْتَرُوْا عَلَى اللّٰهِ كَذِبًا فَيُسْحِتَكُمْ بِعَذَابٍۚ وَقَدْ خَابَ مَنِ افْتَرٰى ',
		ayahNumber: 61,
		translationId: 'Musa berkata kepada mereka (para pesihir), “Celakalah kamu! Janganlah kamu mengada-adakan kedustaan terhadap Allah, nanti Dia membinasakan kamu dengan azab.” Dan sungguh rugi orang yang mengada-adakan kedustaan.',
	),
	Ayah(
		ayahId: 2410,
		ayahText: 'فَتَنَازَعُوْٓا اَمْرَهُمْ بَيْنَهُمْ وَاَسَرُّوا النَّجْوٰى ',
		ayahNumber: 62,
		translationId: 'Maka mereka berbantah-bantahan tentang urusan mereka dan mereka merahasiakan percakapan (mereka).',
	),
	Ayah(
		ayahId: 2411,
		ayahText: 'قَالُوْٓا اِنْ هٰذٰنِ لَسٰحِرَانِ يُرِيْدَانِ اَنْ يُّخْرِجٰكُمْ مِّنْ اَرْضِكُمْ بِسِحْرِهِمَا وَيَذْهَبَا بِطَرِيْقَتِكُمُ الْمُثْلٰى ',
		ayahNumber: 63,
		translationId: 'Mereka (para pesihir) berkata, “Sesungguhnya dua orang ini adalah pesihir yang hendak mengusirmu (Fir‘aun) dari negerimu dengan sihir mereka berdua, dan hendak melenyapkan adat kebiasaanmu yang utama.',
	),
	Ayah(
		ayahId: 2412,
		ayahText: 'فَاَجْمِعُوْا كَيْدَكُمْ ثُمَّ ائْتُوْا صَفًّاۚ وَقَدْ اَفْلَحَ الْيَوْمَ مَنِ اسْتَعْلٰى ',
		ayahNumber: 64,
		translationId: 'Maka kumpulkanlah segala tipu daya (sihir) kamu, kemudian datanglah dengan berbaris, dan sungguh, beruntung orang yang menang pada hari ini.”',
	),
	Ayah(
		ayahId: 2413,
		ayahText: 'قَالُوْا يٰمُوْسٰٓى اِمَّآ اَنْ تُلْقِيَ وَاِمَّآ اَنْ نَّكُوْنَ اَوَّلَ مَنْ اَلْقٰى ',
		ayahNumber: 65,
		translationId: 'Mereka berkata, “Wahai Musa! Apakah engkau yang melemparkan (dahulu) atau kami yang lebih dahulu melemparkan?”',
	),
	Ayah(
		ayahId: 2414,
		ayahText: 'قَالَ بَلْ اَلْقُوْاۚ فَاِذَا حِبَالُهُمْ وَعِصِيُّهُمْ يُخَيَّلُ اِلَيْهِ مِنْ سِحْرِهِمْ اَنَّهَا تَسْعٰى',
		ayahNumber: 66,
		translationId: 'Dia (Musa) berkata, “Silakan kamu melemparkan!” Maka tiba-tiba tali-tali dan tongkat-tongkat mereka terbayang olehnya (Musa) seakan-akan ia merayap cepat, karena sihir mereka.',
	),
	Ayah(
		ayahId: 2415,
		ayahText: 'فَاَوْجَسَ فِيْ نَفْسِهٖ خِيْفَةً مُّوْسٰى ',
		ayahNumber: 67,
		translationId: 'Maka Musa merasa takut dalam hatinya.',
	),
	Ayah(
		ayahId: 2416,
		ayahText: 'قُلْنَا لَا تَخَفْ اِنَّكَ اَنْتَ الْاَعْلٰى ',
		ayahNumber: 68,
		translationId: 'Kami berfirman, “Jangan takut! Sungguh, engkaulah yang unggul (menang).',
	),
	Ayah(
		ayahId: 2417,
		ayahText: 'وَاَلْقِ مَا فِيْ يَمِيْنِكَ تَلْقَفْ مَا صَنَعُوْاۗ اِنَّمَا صَنَعُوْا كَيْدُ سٰحِرٍۗ وَلَا يُفْلِحُ السّٰحِرُ حَيْثُ اَتٰى ',
		ayahNumber: 69,
		translationId: 'Dan lemparkan apa yang ada di tangan kananmu, niscaya ia akan menelan apa yang mereka buat. Apa yang mereka buat itu hanyalah tipu daya pesihir (belaka). Dan tidak akan menang pesihir itu, dari mana pun ia datang.”',
	),
	Ayah(
		ayahId: 2418,
		ayahText: 'فَاُلْقِيَ السَّحَرَةُ سُجَّدًا قَالُوْٓا اٰمَنَّا بِرَبِّ هٰرُوْنَ وَمُوْسٰى ',
		ayahNumber: 70,
		translationId: 'Lalu para pesihir itu merunduk bersujud, seraya berkata, “Kami telah percaya kepada Tuhannya Harun dan Musa.”',
	),
	Ayah(
		ayahId: 2419,
		ayahText: 'قَالَ اٰمَنْتُمْ لَهٗ قَبْلَ اَنْ اٰذَنَ لَكُمْۗ اِنَّهٗ لَكَبِيْرُكُمُ الَّذِيْ عَلَّمَكُمُ السِّحْرَۚ فَلَاُقَطِّعَنَّ اَيْدِيَكُمْ وَاَرْجُلَكُمْ مِّنْ خِلَافٍ وَّلَاُصَلِّبَنَّكُمْ فِيْ جُذُوْعِ النَّخْلِۖ وَلَتَعْلَمُنَّ اَيُّنَآ اَشَدُّ عَذَابًا وَّاَبْقٰى ',
		ayahNumber: 71,
		translationId: 'Dia (Fir‘aun) berkata, “Apakah kamu telah beriman kepadanya (Musa) sebelum aku memberi izin kepadamu? Sesungguhnya dia itu pemimpinmu yang mengajarkan sihir kepadamu. Maka sungguh, akan kupotong tangan dan kakimu secara bersilang, dan sungguh, akan aku salib kamu pada pangkal pohon kurma dan sungguh, kamu pasti akan mengetahui siapa di antara kita yang lebih pedih dan lebih kekal siksaannya.”',
	),
	Ayah(
		ayahId: 2420,
		ayahText: 'قَالُوْا لَنْ نُّؤْثِرَكَ عَلٰى مَا جَاۤءَنَا مِنَ الْبَيِّنٰتِ وَالَّذِيْ فَطَرَنَا فَاقْضِ مَآ اَنْتَ قَاضٍۗ اِنَّمَا تَقْضِيْ هٰذِهِ الْحَيٰوةَ الدُّنْيَا ۗ',
		ayahNumber: 72,
		translationId: 'Mereka (para pesihir) berkata, “Kami tidak akan memilih (tunduk) kepadamu atas bukti-bukti nyata (mukjizat), yang telah datang kepada kami dan atas (Allah) yang telah menciptakan kami. Maka putuskanlah yang hendak engkau putuskan. Sesungguhnya engkau hanya dapat memutuskan pada kehidupan di dunia ini.',
	),
	Ayah(
		ayahId: 2421,
		ayahText: 'اِنَّآ اٰمَنَّا بِرَبِّنَا لِيَغْفِرَ لَنَا خَطٰيٰنَا وَمَآ اَكْرَهْتَنَا عَلَيْهِ مِنَ السِّحْرِۗ وَاللّٰهُ خَيْرٌ وَّاَبْقٰى ',
		ayahNumber: 73,
		translationId: 'Kami benar-benar telah beriman kepada Tuhan kami, agar Dia mengampuni kesalahan-kesalahan kami dan sihir yang telah engkau paksakan kepada kami. Dan Allah lebih baik (pahala-Nya) dan lebih kekal (azab-Nya).”',
	),
	Ayah(
		ayahId: 2422,
		ayahText: 'اِنَّهٗ مَنْ يَّأْتِ رَبَّهٗ مُجْرِمًا فَاِنَّ لَهٗ جَهَنَّمَ ۗ لَا يَمُوْتُ فِيْهَا وَلَا يَحْيٰى ',
		ayahNumber: 74,
		translationId: 'Sesungguhnya barang siapa datang kepada Tuhannya dalam keadaan berdosa, maka sungguh, baginya adalah neraka Jahanam. Dia tidak mati (terus merasakan azab) di dalamnya dan tidak (pula) hidup (tidak dapat bertobat).',
	),
	Ayah(
		ayahId: 2423,
		ayahText: 'وَمَنْ يَّأْتِهٖ مُؤْمِنًا قَدْ عَمِلَ الصّٰلِحٰتِ فَاُولٰۤىِٕكَ لَهُمُ الدَّرَجٰتُ الْعُلٰى ۙ',
		ayahNumber: 75,
		translationId: 'Tetapi barang siapa datang kepada-Nya dalam keadaan beriman, dan telah mengerjakan kebajikan, maka mereka itulah orang yang memperoleh derajat yang tinggi (mulia),',
	),
	Ayah(
		ayahId: 2424,
		ayahText: 'جَنّٰتُ عَدْنٍ تَجْرِيْ مِنْ تَحْتِهَا الْاَنْهٰرُ خٰلِدِيْنَ فِيْهَا ۗوَذٰلِكَ جَزٰۤؤُا مَنْ تَزَكّٰى ࣖ',
		ayahNumber: 76,
		translationId: '(yaitu) surga-surga ‘Adn, yang mengalir di bawahnya sungai-sungai, mereka kekal di dalamnya. Itulah balasan bagi orang yang menyucikan diri.',
	),
	Ayah(
		ayahId: 2425,
		ayahText: 'وَلَقَدْ اَوْحَيْنَآ اِلٰى مُوْسٰٓى اَنْ اَسْرِ بِعِبَادِيْ فَاضْرِبْ لَهُمْ طَرِيْقًا فِى الْبَحْرِ يَبَسًاۙ  لَّا تَخٰفُ دَرَكًا وَّلَا تَخْشٰى ',
		ayahNumber: 77,
		translationId: 'Dan sungguh, telah Kami wahyukan kepada Musa, “Pergilah bersama hamba-hamba-Ku (Bani Israil) pada malam hari, dan pukullah (buatlah) untuk mereka jalan yang kering di laut itu, (engkau) tidak perlu takut akan tersusul dan tidak perlu khawatir (akan tenggelam).”',
	),
	Ayah(
		ayahId: 2426,
		ayahText: 'فَاَتْبَعَهُمْ فِرْعَوْنُ بِجُنُوْدِهٖ فَغَشِيَهُمْ مِّنَ الْيَمِّ مَا غَشِيَهُمْ ۗ',
		ayahNumber: 78,
		translationId: 'Kemudian Fir‘aun dengan bala tentaranya mengejar mereka, tetapi mereka digulung ombak laut yang menenggelamkan mereka.',
	),
	Ayah(
		ayahId: 2427,
		ayahText: 'وَاَضَلَّ فِرْعَوْنُ قَوْمَهٗ وَمَا هَدٰى ',
		ayahNumber: 79,
		translationId: 'Dan Fir‘aun telah menyesatkan kaumnya dan tidak memberi petunjuk.',
	),
	Ayah(
		ayahId: 2428,
		ayahText: 'يٰبَنِيْٓ اِسْرَاۤءِيْلَ قَدْ اَنْجَيْنٰكُمْ مِّنْ عَدُوِّكُمْ وَوٰعَدْنٰكُمْ جَانِبَ الطُّوْرِ الْاَيْمَنَ وَنَزَّلْنَا عَلَيْكُمُ الْمَنَّ وَالسَّلْوٰى ',
		ayahNumber: 80,
		translationId: 'Wahai Bani Israil! Sungguh, Kami telah menyelamatkan kamu dari musuhmu, dan Kami telah mengadakan perjanjian dengan kamu (untuk bermunajat) di sebelah kanan gunung itu (gunung Sinai) dan Kami telah menurunkan kepada kamu mann dan salwa.',
	),
	Ayah(
		ayahId: 2429,
		ayahText: 'كُلُوْا مِنْ طَيِّبٰتِ مَا رَزَقْنٰكُمْۙ وَلَا تَطْغَوْا فِيْهِ فَيَحِلَّ عَلَيْكُمْ غَضَبِيْۚ وَمَنْ يَّحْلِلْ عَلَيْهِ غَضَبِيْ فَقَدْ هَوٰى ',
		ayahNumber: 81,
		translationId: 'Makanlah dari rezeki yang baik-baik yang telah Kami berikan kepadamu, dan janganlah melampaui batas, yang menyebabkan kemurkaan-Ku menimpamu. Barangsiapa ditimpa kemurkaan-Ku, maka sungguh, binasalah dia.',
	),
	Ayah(
		ayahId: 2430,
		ayahText: 'وَاِنِّي لَغَفَّارٌ لِّمَنْ تَابَ وَاٰمَنَ وَعَمِلَ صَالِحًا ثُمَّ اهْتَدٰى ',
		ayahNumber: 82,
		translationId: 'Dan sungguh, Aku Maha Pengampun bagi yang bertobat, beriman dan berbuat kebajikan, kemudian tetap dalam petunjuk.',
	),
	Ayah(
		ayahId: 2431,
		ayahText: '۞ وَمَآ اَعْجَلَكَ عَنْ قَوْمِكَ يٰمُوْسٰى ',
		ayahNumber: 83,
		translationId: '“Dan mengapa engkau datang lebih cepat daripada kaummu, wahai Musa?”',
	),
	Ayah(
		ayahId: 2432,
		ayahText: 'قَالَ هُمْ اُولَاۤءِ عَلٰٓى اَثَرِيْ وَعَجِلْتُ اِلَيْكَ رَبِّ لِتَرْضٰى ',
		ayahNumber: 84,
		translationId: 'Dia (Musa) berkata, “Itu mereka sedang menyusul aku dan aku bersegera kepada-Mu, Ya Tuhanku, agar Engkau rida (kepadaku).”',
	),
	Ayah(
		ayahId: 2433,
		ayahText: 'قَالَ فَاِنَّا قَدْ فَتَنَّا قَوْمَكَ مِنْۢ بَعْدِكَ وَاَضَلَّهُمُ السَّامِرِيُّ ',
		ayahNumber: 85,
		translationId: 'Dia (Allah) berfirman, “Sungguh, Kami telah menguji kaummu setelah engkau tinggalkan, dan mereka telah disesatkan oleh Samiri.” ',
	),
	Ayah(
		ayahId: 2434,
		ayahText: 'فَرَجَعَ مُوْسٰٓى اِلٰى قَوْمِهٖ غَضْبَانَ اَسِفًا ەۚ قَالَ يٰقَوْمِ اَلَمْ يَعِدْكُمْ رَبُّكُمْ وَعْدًا حَسَنًا ەۗ اَفَطَالَ عَلَيْكُمُ الْعَهْدُ اَمْ اَرَدْتُّمْ اَنْ يَّحِلَّ عَلَيْكُمْ غَضَبٌ مِّنْ رَّبِّكُمْ فَاَخْلَفْتُمْ مَّوْعِدِيْ',
		ayahNumber: 86,
		translationId: 'Kemudian Musa kembali kepada kaumnya dengan marah dan bersedih hati. Dia (Musa) berkata, “Wahai kaumku! Bukankah Tuhanmu telah menjanjikan kepadamu suatu janji yang baik? Apakah terlalu lama masa perjanjian itu bagimu atau kamu menghendaki agar kemurkaan Tuhan menimpamu, mengapa kamu melanggar perjanjianmu dengan aku?”',
	),
	Ayah(
		ayahId: 2435,
		ayahText: 'قَالُوْا مَآ اَخْلَفْنَا مَوْعِدَكَ بِمَلْكِنَا وَلٰكِنَّا حُمِّلْنَآ اَوْزَارًا مِّنْ زِيْنَةِ الْقَوْمِ فَقَذَفْنٰهَا فَكَذٰلِكَ اَلْقَى السَّامِرِيُّ ۙ',
		ayahNumber: 87,
		translationId: 'Mereka berkata, “Kami tidak melanggar perjanjianmu dengan kemauan kami sendiri, tetapi kami harus membawa beban berat dari perhiasan kaum (Fir‘aun) itu, kemudian kami melemparkannya (ke dalam api), dan demikian pula Samiri melemparkannya,',
	),
	Ayah(
		ayahId: 2436,
		ayahText: 'فَاَخْرَجَ لَهُمْ عِجْلًا جَسَدًا لَّهٗ خُوَارٌ فَقَالُوْا هٰذَآ اِلٰهُكُمْ وَاِلٰهُ مُوْسٰى ەۙ فَنَسِيَ ۗ',
		ayahNumber: 88,
		translationId: 'kemudian (dari lubang api itu) dia (Samiri) mengeluarkan (patung) anak sapi yang bertubuh dan bersuara untuk mereka, maka mereka berkata, “Inilah Tuhanmu dan Tuhannya Musa, tetapi dia (Musa) telah lupa.”',
	),
	Ayah(
		ayahId: 2437,
		ayahText: 'اَفَلَا يَرَوْنَ اَلَّا يَرْجِعُ اِلَيْهِمْ قَوْلًا ەۙ وَّلَا يَمْلِكُ لَهُمْ ضَرًّا وَّلَا نَفْعًا ࣖ',
		ayahNumber: 89,
		translationId: 'Maka tidakkah mereka memperhatikan bahwa (patung anak sapi itu) tidak dapat memberi jawaban kepada mereka, dan tidak kuasa menolak mudarat mau-pun mendatangkan manfaat kepada mereka?',
	),
	Ayah(
		ayahId: 2438,
		ayahText: 'وَلَقَدْ قَالَ لَهُمْ هٰرُوْنُ مِنْ قَبْلُ يٰقَوْمِ اِنَّمَا فُتِنْتُمْ بِهٖۚ وَاِنَّ رَبَّكُمُ الرَّحْمٰنُ فَاتَّبِعُوْنِيْ وَاَطِيْعُوْٓا اَمْرِيْ ',
		ayahNumber: 90,
		translationId: 'Dan sungguh, sebelumnya Harun telah berkata kepada mereka, “Wahai kaumku! Sesungguhnya kamu hanya sekedar diberi cobaan (dengan patung anak sapi) itu dan sungguh, Tuhanmu ialah (Allah) Yang Maha Pengasih, maka ikutilah aku dan taatilah perintahku.”',
	),
	Ayah(
		ayahId: 2439,
		ayahText: 'قَالُوْا لَنْ نَّبْرَحَ عَلَيْهِ عٰكِفِيْنَ حَتّٰى يَرْجِعَ اِلَيْنَا مُوْسٰى ',
		ayahNumber: 91,
		translationId: 'Mereka menjawab, “Kami tidak akan meninggalkannya (dan) tetap menyembahnya (patung anak sapi) sampai Musa kembali kepada kami.”',
	),
	Ayah(
		ayahId: 2440,
		ayahText: 'قَالَ يٰهٰرُوْنُ مَا مَنَعَكَ اِذْ رَاَيْتَهُمْ ضَلُّوْٓا ۙ',
		ayahNumber: 92,
		translationId: 'Dia (Musa) berkata, “Wahai Harun! Apa yang menghalangimu ketika engkau melihat mereka telah sesat,',
	),
	Ayah(
		ayahId: 2441,
		ayahText: 'اَلَّا تَتَّبِعَنِۗ اَفَعَصَيْتَ اَمْرِيْ ',
		ayahNumber: 93,
		translationId: '(sehingga) engkau tidak mengikuti aku? Apakah engkau telah (sengaja) melanggar perintahku?”',
	),
	Ayah(
		ayahId: 2442,
		ayahText: 'قَالَ يَبْنَؤُمَّ لَا تَأْخُذْ بِلِحْيَتِيْ وَلَا بِرَأْسِيْۚ اِنِّيْ خَشِيْتُ اَنْ تَقُوْلَ فَرَّقْتَ بَيْنَ بَنِيْٓ اِسْرَاۤءِيْلَ وَلَمْ تَرْقُبْ قَوْلِيْ ',
		ayahNumber: 94,
		translationId: 'Dia (Harun) menjawab, “Wahai putra ibuku! Janganlah engkau pegang janggutku dan jangan (pula) kepalaku. Aku sungguh khawatir engkau akan berkata (kepadaku), ‘Engkau telah memecah belah antara Bani Israil dan engkau tidak memelihara amanatku.’” ',
	),
	Ayah(
		ayahId: 2443,
		ayahText: 'قَالَ فَمَا خَطْبُكَ يٰسَامِرِيُّ ',
		ayahNumber: 95,
		translationId: 'Dia (Musa) berkata, “Apakah yang mendorongmu (berbuat demikian) wahai Samiri?”',
	),
	Ayah(
		ayahId: 2444,
		ayahText: 'قَالَ بَصُرْتُ بِمَا لَمْ يَبْصُرُوْا بِهٖ فَقَبَضْتُ قَبْضَةً مِّنْ اَثَرِ الرَّسُوْلِ فَنَبَذْتُهَا وَكَذٰلِكَ سَوَّلَتْ لِيْ نَفْسِيْ ',
		ayahNumber: 96,
		translationId: 'Dia (Samiri) menjawab, “Aku mengetahui sesuatu yang tidak mereka ketahui, jadi aku ambil segenggam (tanah dari) jejak rasul lalu aku melemparkannya (ke dalam api itu), demikianlah nafsuku membujukku.”',
	),
	Ayah(
		ayahId: 2445,
		ayahText: 'قَالَ فَاذْهَبْ فَاِنَّ لَكَ فِى الْحَيٰوةِ اَنْ تَقُوْلَ لَا مِسَاسَۖ وَاِنَّ لَكَ مَوْعِدًا لَّنْ تُخْلَفَهٗۚ وَانْظُرْ اِلٰٓى اِلٰهِكَ الَّذِيْ ظَلْتَ عَلَيْهِ عَاكِفًا ۗ  لَنُحَرِّقَنَّهٗ ثُمَّ لَنَنْسِفَنَّهٗ فِى الْيَمِّ نَسْفًا ',
		ayahNumber: 97,
		translationId: 'Dia (Musa) berkata, “Pergilah kau! Maka sesungguhnya di dalam kehidupan (di dunia) engkau (hanya dapat) mengatakan, ‘Janganlah menyentuh (aku),’. Dan engkau pasti mendapat (hukuman) yang telah dijanjikan (di akhirat) yang tidak akan dapat engkau hindari, dan lihatlah tuhanmu itu yang engkau tetap menyembahnya. Kami pasti akan membakarnya, kemudian sungguh kami akan menghamburkannya (abunya) ke dalam laut (berserakan).',
	),
	Ayah(
		ayahId: 2446,
		ayahText: 'اِنَّمَآ اِلٰهُكُمُ اللّٰهُ الَّذِيْ لَآ اِلٰهَ اِلَّا هُوَۗ وَسِعَ كُلَّ شَيْءٍ عِلْمًا ',
		ayahNumber: 98,
		translationId: ' Sungguh, Tuhanmu hanyalah Allah, tidak ada tuhan selain Dia. Pengetahuan-Nya meliputi segala sesuatu.”',
	),
	Ayah(
		ayahId: 2447,
		ayahText: 'كَذٰلِكَ نَقُصُّ عَلَيْكَ مِنْ اَنْۢبَاۤءِ مَا قَدْ سَبَقَۚ وَقَدْ اٰتَيْنٰكَ مِنْ لَّدُنَّا ذِكْرًا ۚ',
		ayahNumber: 99,
		translationId: "Demikianlah Kami kisahkan kepadamu (Muhammad) sebagian kisah (umat) yang telah lalu, dan sungguh, telah Kami berikan kepadamu suatu peringatan (Al-Qur'an) dari sisi Kami.",
	),
	Ayah(
		ayahId: 2448,
		ayahText: 'مَنْ اَعْرَضَ عَنْهُ فَاِنَّهٗ يَحْمِلُ يَوْمَ الْقِيٰمَةِ وِزْرًا ',
		ayahNumber: 100,
		translationId: "Barangsiapa berpaling darinya (Al-Qur'an), maka sesungguhnya dia akan memikul beban yang berat (dosa) pada hari Kiamat, ",
	),
	Ayah(
		ayahId: 2449,
		ayahText: 'خٰلِدِيْنَ فِيْهِ ۗوَسَاۤءَ لَهُمْ يَوْمَ الْقِيٰمَةِ حِمْلًاۙ ',
		ayahNumber: 101,
		translationId: 'mereka kekal di dalam keadaan itu. Dan sungguh buruk beban dosa itu bagi mereka pada hari Kiamat, ',
	),
	Ayah(
		ayahId: 2450,
		ayahText: 'يَّوْمَ يُنْفَخُ فِى الصُّوْرِ وَنَحْشُرُ الْمُجْرِمِيْنَ يَوْمَىِٕذٍ زُرْقًا ۖ',
		ayahNumber: 102,
		translationId: 'pada hari (Kiamat) sangkakala ditiup (yang kedua kali) dan pada hari itu Kami kumpulkan orang-orang yang berdosa dengan (wajah) biru muram,',
	),
	Ayah(
		ayahId: 2451,
		ayahText: 'يَّتَخَافَتُوْنَ بَيْنَهُمْ اِنْ لَّبِثْتُمْ اِلَّا عَشْرًا ',
		ayahNumber: 103,
		translationId: 'mereka saling berbisik satu sama lain, “Kamu tinggal (di dunia) tidak lebih dari sepuluh (hari).”',
	),
	Ayah(
		ayahId: 2452,
		ayahText: 'نَحْنُ اَعْلَمُ بِمَا يَقُوْلُوْنَ اِذْ يَقُوْلُ اَمْثَلُهُمْ طَرِيْقَةً اِنْ لَّبِثْتُمْ اِلَّا يَوْمًا ࣖ',
		ayahNumber: 104,
		translationId: 'Kami lebih mengetahui apa yang akan mereka katakan, ketika orang yang paling lurus jalannya mengatakan, “Kamu tinggal (di dunia), tidak lebih dari sehari saja.”',
	),
	Ayah(
		ayahId: 2453,
		ayahText: 'وَيَسْـَٔلُوْنَكَ عَنِ الْجِبَالِ فَقُلْ يَنْسِفُهَا رَبِّيْ نَسْفًا ۙ',
		ayahNumber: 105,
		translationId: 'Dan mereka bertanya kepadamu (Muhammad) tentang gunung-gunung, maka katakanlah, “Tuhanku akan menghancurkannya (pada hari Kiamat) sehancur-hancurnya,',
	),
	Ayah(
		ayahId: 2454,
		ayahText: 'فَيَذَرُهَا قَاعًا صَفْصَفًا ۙ',
		ayahNumber: 106,
		translationId: 'kemudian Dia akan menjadikan (bekas gunung-gunung) itu rata sama sekali, ',
	),
	Ayah(
		ayahId: 2455,
		ayahText: 'لَّا تَرٰى فِيْهَا عِوَجًا وَّلَآ اَمْتًا ۗ',
		ayahNumber: 107,
		translationId: '(sehingga) kamu tidak akan melihat lagi ada tempat yang rendah dan yang tinggi di sana.” ',
	),
	Ayah(
		ayahId: 2456,
		ayahText: 'يَوْمَىِٕذٍ يَّتَّبِعُوْنَ الدَّاعِيَ لَا عِوَجَ لَهٗ ۚوَخَشَعَتِ الْاَصْوَاتُ لِلرَّحْمٰنِ فَلَا تَسْمَعُ اِلَّا هَمْسًا ',
		ayahNumber: 108,
		translationId: 'Pada hari itu mereka mengikuti (panggilan) penyeru (malaikat) tanpa berbelok-belok (membantah); dan semua suara tunduk merendah kepada Tuhan Yang Maha Pengasih, sehingga yang kamu dengar hanyalah bisik-bisik.',
	),
	Ayah(
		ayahId: 2457,
		ayahText: 'يَوْمَىِٕذٍ لَّا تَنْفَعُ الشَّفَاعَةُ اِلَّا مَنْ اَذِنَ لَهُ الرَّحْمٰنُ وَرَضِيَ لَهٗ قَوْلًا ',
		ayahNumber: 109,
		translationId: 'Pada hari itu tidak berguna syafaat (pertolongan), kecuali dari orang yang telah diberi izin oleh Tuhan Yang Maha Pengasih, dan Dia ridai perkataannya.',
	),
	Ayah(
		ayahId: 2458,
		ayahText: 'يَعْلَمُ مَا بَيْنَ اَيْدِيْهِمْ وَمَا خَلْفَهُمْ وَلَا يُحِيْطُوْنَ بِهٖ عِلْمًا ',
		ayahNumber: 110,
		translationId: ' Dia (Allah) mengetahui apa yang di hadapan mereka (yang akan terjadi) dan apa yang di belakang mereka (yang telah terjadi), sedang ilmu mereka tidak dapat meliputi ilmu-Nya.',
	),
	Ayah(
		ayahId: 2459,
		ayahText: '۞ وَعَنَتِ الْوُجُوْهُ لِلْحَيِّ الْقَيُّوْمِۗ وَقَدْ خَابَ مَنْ حَمَلَ ظُلْمًا ',
		ayahNumber: 111,
		translationId: 'Dan semua wajah tertunduk di hadapan (Allah) Yang Hidup dan Yang Berdiri Sendiri. Sungguh rugi orang yang melakukan kezaliman.',
	),
	Ayah(
		ayahId: 2460,
		ayahText: 'وَمَنْ يَّعْمَلْ مِنَ الصّٰلِحٰتِ وَهُوَ مُؤْمِنٌ فَلَا يَخٰفُ ظُلْمًا وَّلَا هَضْمًا ',
		ayahNumber: 112,
		translationId: 'Dan barang siapa mengerjakan kebajikan sedang dia (dalam keadaan) beriman, maka dia tidak khawatir akan perlakuan zalim (terhadapnya) dan tidak (pula khawatir) akan pengurangan haknya.',
	),
	Ayah(
		ayahId: 2461,
		ayahText: 'وَكَذٰلِكَ اَنْزَلْنٰهُ قُرْاٰنًا عَرَبِيًّا وَّصَرَّفْنَا فِيْهِ مِنَ الْوَعِيْدِ لَعَلَّهُمْ يَتَّقُوْنَ اَوْ يُحْدِثُ لَهُمْ ذِكْرًا ',
		ayahNumber: 113,
		translationId: "Dan demikianlah Kami menurunkan Al-Qur'an dalam bahasa Arab, dan Kami telah menjelaskan berulang-ulang di dalamnya sebagian dari ancaman, agar mereka bertakwa, atau agar (Al-Qur'an) itu memberi pengajaran bagi mereka.",
	),
	Ayah(
		ayahId: 2462,
		ayahText: 'فَتَعٰلَى اللّٰهُ الْمَلِكُ الْحَقُّۚ وَلَا تَعْجَلْ بِالْقُرْاٰنِ مِنْ قَبْلِ اَنْ يُّقْضٰٓى اِلَيْكَ وَحْيُهٗ ۖوَقُلْ رَّبِّ زِدْنِيْ عِلْمًا ',
		ayahNumber: 114,
		translationId: "Maka Mahatinggi Allah, Raja yang sebenar-benarnya. Dan janganlah engkau (Muhammad) tergesa-gesa (membaca) Al-Qur'an sebelum selesai diwahyukan kepadamu, dan katakanlah, “Ya Tuhanku, tambahkanlah ilmu kepadaku. ”",
	),
	Ayah(
		ayahId: 2463,
		ayahText: 'وَلَقَدْ عَهِدْنَآ اِلٰٓى اٰدَمَ مِنْ قَبْلُ فَنَسِيَ وَلَمْ نَجِدْ لَهٗ عَزْمًا ࣖ',
		ayahNumber: 115,
		translationId: 'Dan sungguh telah Kami pesankan kepada Adam dahulu, tetapi dia lupa, dan Kami tidak dapati kemauan yang kuat padanya.',
	),
	Ayah(
		ayahId: 2464,
		ayahText: 'وَاِذْ قُلْنَا لِلْمَلٰۤىِٕكَةِ اسْجُدُوْا لِاٰدَمَ فَسَجَدُوْٓا اِلَّآ اِبْلِيْسَ اَبٰى ۗ',
		ayahNumber: 116,
		translationId: 'Dan (ingatlah) ketika Kami berfirman kepada para malaikat, “Sujudlah kamu kepada Adam!” Lalu mereka pun sujud kecuali Iblis; dia menolak.',
	),
	Ayah(
		ayahId: 2465,
		ayahText: 'فَقُلْنَا يٰٓاٰدَمُ اِنَّ هٰذَا عَدُوٌّ لَّكَ وَلِزَوْجِكَ فَلَا يُخْرِجَنَّكُمَا مِنَ الْجَنَّةِ فَتَشْقٰى ',
		ayahNumber: 117,
		translationId: 'Kemudian Kami berfirman, “Wahai Adam! Sungguh ini (Iblis) musuh bagimu dan bagi istrimu, maka sekali-kali jangan sampai dia mengeluarkan kamu berdua dari surga, nanti kamu celaka.',
	),
	Ayah(
		ayahId: 2466,
		ayahText: 'اِنَّ لَكَ اَلَّا تَجُوْعَ فِيْهَا وَلَا تَعْرٰى ۙ',
		ayahNumber: 118,
		translationId: 'Sungguh, ada (jaminan) untukmu di sana, engkau tidak akan kelaparan dan tidak akan telanjang.',
	),
	Ayah(
		ayahId: 2467,
		ayahText: 'وَاَنَّكَ لَا تَظْمَؤُا فِيْهَا وَلَا تَضْحٰى ',
		ayahNumber: 119,
		translationId: 'Dan sungguh, di sana engkau tidak akan merasa dahaga dan tidak akan ditimpa panas matahari.” ',
	),
	Ayah(
		ayahId: 2468,
		ayahText: 'فَوَسْوَسَ اِلَيْهِ الشَّيْطٰنُ قَالَ يٰٓاٰدَمُ هَلْ اَدُلُّكَ عَلٰى شَجَرَةِ الْخُلْدِ وَمُلْكٍ لَّا يَبْلٰى ',
		ayahNumber: 120,
		translationId: ' Kemudian setan membisikkan (pikiran jahat) kepadanya, dengan berkata, “Wahai Adam! Maukah aku tunjukkan kepadamu pohon keabadian (khuldi) dan kerajaan yang tidak akan binasa?”',
	),
	Ayah(
		ayahId: 2469,
		ayahText: 'فَاَكَلَا مِنْهَا فَبَدَتْ لَهُمَا سَوْاٰتُهُمَا وَطَفِقَا يَخْصِفٰنِ عَلَيْهِمَا مِنْ وَّرَقِ الْجَنَّةِۚ وَعَصٰٓى اٰدَمُ رَبَّهٗ فَغَوٰى ۖ',
		ayahNumber: 121,
		translationId: 'Lalu keduanya memakannya, lalu tampaklah oleh keduanya aurat mereka dan mulailah keduanya menutupinya dengan daun-daun (yang ada di) surga, dan telah durhakalah Adam kepada Tuhannya, dan sesatlah dia.',
	),
	Ayah(
		ayahId: 2470,
		ayahText: 'ثُمَّ اجْتَبٰىهُ رَبُّهٗ فَتَابَ عَلَيْهِ وَهَدٰى ',
		ayahNumber: 122,
		translationId: 'Kemudian Tuhannya memilih dia, maka Dia menerima tobatnya dan memberinya petunjuk.',
	),
	Ayah(
		ayahId: 2471,
		ayahText: 'قَالَ اهْبِطَا مِنْهَا جَمِيعًاۢ بَعْضُكُمْ لِبَعْضٍ عَدُوٌّ ۚفَاِمَّا يَأْتِيَنَّكُمْ مِّنِّيْ هُدًى ەۙ فَمَنِ اتَّبَعَ هُدٰيَ فَلَا يَضِلُّ وَلَا يَشْقٰى',
		ayahNumber: 123,
		translationId: 'Dia (Allah) berfirman, “Turunlah kamu berdua dari surga bersama-sama, sebagian kamu menjadi musuh bagi sebagian yang lain. Jika datang kepadamu petunjuk dari-Ku, maka (ketahuilah) barang siapa mengikuti petunjuk-Ku, dia tidak akan sesat dan tidak akan celaka.',
	),
	Ayah(
		ayahId: 2472,
		ayahText: 'وَمَنْ اَعْرَضَ عَنْ ذِكْرِيْ فَاِنَّ لَهٗ مَعِيْشَةً ضَنْكًا وَّنَحْشُرُهٗ يَوْمَ الْقِيٰمَةِ اَعْمٰى ',
		ayahNumber: 124,
		translationId: 'Dan barang siapa berpaling dari peringatan-Ku, maka sungguh, dia akan menjalani kehidupan yang sempit, dan Kami akan mengumpulkannya pada hari Kiamat dalam keadaan buta.”',
	),
	Ayah(
		ayahId: 2473,
		ayahText: 'قَالَ رَبِّ لِمَ حَشَرْتَنِيْٓ اَعْمٰى وَقَدْ كُنْتُ بَصِيْرًا ',
		ayahNumber: 125,
		translationId: 'Dia berkata, “Ya Tuhanku, mengapa Engkau kumpulkan aku dalam keadaan buta, padahal dahulu aku dapat melihat?”',
	),
	Ayah(
		ayahId: 2474,
		ayahText: 'قَالَ كَذٰلِكَ اَتَتْكَ اٰيٰتُنَا فَنَسِيْتَهَاۚ وَكَذٰلِكَ الْيَوْمَ تُنْسٰى ',
		ayahNumber: 126,
		translationId: 'Dia (Allah) berfirman, “Demikianlah, dahulu telah datang kepadamu ayat-ayat Kami, dan kamu mengabaikannya, jadi begitu (pula) pada hari ini kamu diabaikan.”',
	),
	Ayah(
		ayahId: 2475,
		ayahText: 'وَكَذٰلِكَ نَجْزِيْ مَنْ اَسْرَفَ وَلَمْ يُؤْمِنْۢ بِاٰيٰتِ رَبِّهٖۗ وَلَعَذَابُ الْاٰخِرَةِ اَشَدُّ وَاَبْقٰى ',
		ayahNumber: 127,
		translationId: 'Dan demikianlah Kami membalas orang yang melampaui batas dan tidak percaya kepada ayat-ayat Tuhannya. Sungguh, azab di akhirat itu lebih berat dan lebih kekal. ',
	),
	Ayah(
		ayahId: 2476,
		ayahText: 'اَفَلَمْ يَهْدِ لَهُمْ كَمْ اَهْلَكْنَا قَبْلَهُمْ مِّنَ الْقُرُوْنِ يَمْشُوْنَ فِيْ مَسٰكِنِهِمْۗ اِنَّ فِيْ ذٰلِكَ لَاٰيٰتٍ لِّاُولِى النُّهٰى ࣖ',
		ayahNumber: 128,
		translationId: 'Maka tidakkah menjadi petunjuk bagi mereka (orang-orang musyrik) berapa banyak (generasi) sebelum mereka yang telah Kami binasakan, padahal mereka melewati (bekas-bekas) tempat tinggal mereka (umat-umat itu)? Sungguh, pada yang demikian itu terdapat tanda-tanda (kekuasaan Allah) bagi orang-orang yang berakal.',
	),
	Ayah(
		ayahId: 2477,
		ayahText: 'وَلَوْلَا كَلِمَةٌ سَبَقَتْ مِنْ رَّبِّكَ لَكَانَ لِزَامًا وَّاَجَلٌ مُّسَمًّى ۗ',
		ayahNumber: 129,
		translationId: 'Dan kalau tidak ada suatu ketetapan terdahulu dari Tuhanmu serta tidak ada batas yang telah ditentukan (ajal), pasti (siksaan itu) menimpa mereka.',
	),
	Ayah(
		ayahId: 2478,
		ayahText: 'فَاصْبِرْ عَلٰى مَا يَقُوْلُوْنَ وَسَبِّحْ بِحَمْدِ رَبِّكَ قَبْلَ طُلُوْعِ الشَّمْسِ وَقَبْلَ غُرُوْبِهَا ۚوَمِنْ اٰنَاۤئِ الَّيْلِ فَسَبِّحْ وَاَطْرَافَ النَّهَارِ لَعَلَّكَ تَرْضٰى',
		ayahNumber: 130,
		translationId: 'Maka sabarlah engkau (Muhammad) atas apa yang mereka katakan, dan bertasbihlah dengan memuji Tuhanmu, sebelum matahari terbit, dan sebelum terbenam; dan bertasbihlah (pula) pada waktu tengah malam dan di ujung siang hari, agar engkau merasa tenang.',
	),
	Ayah(
		ayahId: 2479,
		ayahText: 'وَلَا تَمُدَّنَّ عَيْنَيْكَ اِلٰى مَا مَتَّعْنَا بِهٖٓ اَزْوَاجًا مِّنْهُمْ زَهْرَةَ الْحَيٰوةِ الدُّنْيَا ەۙ لِنَفْتِنَهُمْ فِيْهِ ۗوَرِزْقُ رَبِّكَ خَيْرٌ وَّاَبْقٰى',
		ayahNumber: 131,
		translationId: 'Dan janganlah engkau tujukan pandangan matamu kepada kenikmatan yang telah Kami berikan kepada beberapa golongan dari mereka, (sebagai) bunga kehidupan dunia agar Kami uji mereka dengan (kesenangan) itu. Karunia Tuhanmu lebih baik dan lebih kekal.',
	),
	Ayah(
		ayahId: 2480,
		ayahText: 'وَأْمُرْ اَهْلَكَ بِالصَّلٰوةِ وَاصْطَبِرْ عَلَيْهَاۗ  لَا نَسْـَٔلُكَ رِزْقًاۗ نَحْنُ نَرْزُقُكَۗ وَالْعَاقِبَةُ لِلتَّقْوٰى ',
		ayahNumber: 132,
		translationId: 'Dan perintahkanlah keluargamu melaksanakan salat dan sabar dalam mengerjakannya. Kami tidak meminta rezeki kepadamu, Kamilah yang memberi rezeki kepadamu. Dan akibat (yang baik di akhirat) adalah bagi orang yang bertakwa.',
	),
	Ayah(
		ayahId: 2481,
		ayahText: 'وَقَالُوْا لَوْلَا يَأْتِيْنَا بِاٰيَةٍ مِّنْ رَّبِّهٖۗ اَوَلَمْ تَأْتِهِمْ بَيِّنَةُ مَا فِى الصُّحُفِ الْاُولٰى ',
		ayahNumber: 133,
		translationId: 'Dan mereka berkata, “Mengapa dia tidak membawa tanda (bukti) kepada kami dari Tuhannya?” Bukankah telah datang kepada mereka bukti (yang nyata) sebagaimana yang tersebut di dalam kitab-kitab yang dahulu?',
	),
	Ayah(
		ayahId: 2482,
		ayahText: 'وَلَوْ اَنَّآ اَهْلَكْنٰهُمْ بِعَذَابٍ مِّنْ قَبْلِهٖ لَقَالُوْا رَبَّنَا لَوْلَآ اَرْسَلْتَ اِلَيْنَا رَسُوْلًا فَنَتَّبِعَ اٰيٰتِكَ مِنْ قَبْلِ اَنْ نَّذِلَّ وَنَخْزٰى ',
		ayahNumber: 134,
		translationId: "Dan kalau mereka Kami binasakan dengan suatu siksaan sebelumnya (Al-Qur'an itu diturunkan), tentulah mereka berkata, “Ya Tuhan kami, mengapa tidak Engkau utus seorang rasul kepada kami, sehingga kami mengikuti ayat-ayat-Mu sebelum kami menjadi hina dan rendah?”",
	),
	Ayah(
		ayahId: 2483,
		ayahText: 'قُلْ كُلٌّ مُّتَرَبِّصٌ فَتَرَبَّصُوْاۚ فَسَتَعْلَمُوْنَ مَنْ اَصْحٰبُ الصِّرَاطِ السَّوِيِّ وَمَنِ اهْتَدٰى ࣖ    ۔',
		ayahNumber: 135,
		translationId: 'Katakanlah (Muhammad), “Masing-masing (kita) menanti, maka nantikanlah olehmu! Dan kelak kamu akan mengetahui, siapa yang menempuh jalan yang lurus, dan siapa yang telah mendapat petunjuk.”',
	),
];
