// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah44 = [
	Ayah(
		ayahId: 4415,
		ayahText: 'حٰمۤ  ۚ ',
		ayahNumber: 1,
		translationId: 'Ha Mim',
	),
	Ayah(
		ayahId: 4416,
		ayahText: 'وَالْكِتٰبِ الْمُبِيْنِۙ ',
		ayahNumber: 2,
		translationId: "Demi Kitab (Al-Qur'an) yang jelas,",
	),
	Ayah(
		ayahId: 4417,
		ayahText: 'اِنَّآ اَنْزَلْنٰهُ فِيْ لَيْلَةٍ مُّبٰرَكَةٍ اِنَّا كُنَّا مُنْذِرِيْنَ',
		ayahNumber: 3,
		translationId: 'sesungguhnya Kami menurunkannya pada malam yang diberkahi. ) Sungguh, Kamilah yang memberi peringatan.',
	),
	Ayah(
		ayahId: 4418,
		ayahText: 'فِيْهَا يُفْرَقُ كُلُّ اَمْرٍ حَكِيْمٍۙ ',
		ayahNumber: 4,
		translationId: 'Pada (malam itu) dijelaskan segala urusan yang penuh hikmah,',
	),
	Ayah(
		ayahId: 4419,
		ayahText: 'اَمْرًا مِّنْ عِنْدِنَاۗ اِنَّا كُنَّا مُرْسِلِيْنَۖ ',
		ayahNumber: 5,
		translationId: '(yaitu) urusan dari sisi Kami. Sungguh, Kamilah yang mengutus rasul-rasul,',
	),
	Ayah(
		ayahId: 4420,
		ayahText: 'رَحْمَةً مِّنْ رَّبِّكَ ۗاِنَّهٗ هُوَ السَّمِيْعُ الْعَلِيْمُۗ ',
		ayahNumber: 6,
		translationId: 'sebagai rahmat dari Tuhanmu. Sungguh, Dia Maha Mendengar, Maha Mengetahui,',
	),
	Ayah(
		ayahId: 4421,
		ayahText: 'رَبِّ السَّمٰوٰتِ وَالْاَرْضِ وَمَا بَيْنَهُمَاۘ اِنْ كُنْتُمْ مُّوْقِنِيْنَ',
		ayahNumber: 7,
		translationId: 'Tuhan (yang memelihara) langit dan bumi dan apa yang ada di antara keduanya; jika kamu orang-orang yang meyakini.',
	),
	Ayah(
		ayahId: 4422,
		ayahText: 'لَآ اِلٰهَ اِلَّا هُوَ يُحْيٖ وَيُمِيْتُ ۗرَبُّكُمْ وَرَبُّ اٰبَاۤىِٕكُمُ الْاَوَّلِيْنَ',
		ayahNumber: 8,
		translationId: 'Tidak ada tuhan selain Dia, Dia yang menghidupkan dan mematikan. (Dialah) Tuhanmu dan Tuhan nenek moyangmu dahulu.',
	),
	Ayah(
		ayahId: 4423,
		ayahText: 'بَلْ هُمْ فِيْ شَكٍّ يَّلْعَبُوْنَ',
		ayahNumber: 9,
		translationId: 'Tetapi mereka dalam keraguan, mereka  bermain-main.',
	),
	Ayah(
		ayahId: 4424,
		ayahText: 'فَارْتَقِبْ يَوْمَ تَأْتِى السَّمَاۤءُ بِدُخَانٍ مُّبِيْنٍ ',
		ayahNumber: 10,
		translationId: 'Maka tunggulah pada hari ketika langit membawa kabut yang tampak jelas,',
	),
	Ayah(
		ayahId: 4425,
		ayahText: 'يَغْشَى النَّاسَۗ هٰذَا عَذَابٌ اَلِيْمٌ ',
		ayahNumber: 11,
		translationId: 'yang meliputi manusia. Inilah azab yang pedih.',
	),
	Ayah(
		ayahId: 4426,
		ayahText: 'رَبَّنَا اكْشِفْ عَنَّا الْعَذَابَ اِنَّا مُؤْمِنُوْنَ ',
		ayahNumber: 12,
		translationId: '(Mereka berdoa), “Ya Tuhan kami, lenyapkanlah azab itu dari kami. Sungguh, kami akan beriman.”',
	),
	Ayah(
		ayahId: 4427,
		ayahText: 'اَنّٰى لَهُمُ الذِّكْرٰى وَقَدْ جَاۤءَهُمْ رَسُوْلٌ مُّبِيْنٌۙ ',
		ayahNumber: 13,
		translationId: 'Bagaimana mereka dapat menerima peringatan, padahal (sebelumnya pun) seorang Rasul telah datang memberi penjelasan kepada mereka,',
	),
	Ayah(
		ayahId: 4428,
		ayahText: 'ثُمَّ تَوَلَّوْا عَنْهُ وَقَالُوْا مُعَلَّمٌ مَّجْنُوْنٌۘ ',
		ayahNumber: 14,
		translationId: 'kemudian mereka berpaling darinya dan berkata, “Dia itu orang yang menerima ajaran (dari orang lain) dan orang gila.”',
	),
	Ayah(
		ayahId: 4429,
		ayahText: 'اِنَّا كَاشِفُوا الْعَذَابِ قَلِيْلًا اِنَّكُمْ عَاۤىِٕدُوْنَۘ ',
		ayahNumber: 15,
		translationId: 'Sungguh (kalau) Kami melenyapkan azab itu sedikit saja, tentu kamu akan kembali (ingkar).',
	),
	Ayah(
		ayahId: 4430,
		ayahText: 'يَوْمَ نَبْطِشُ الْبَطْشَةَ الْكُبْرٰىۚ اِنَّا مُنْتَقِمُوْنَ',
		ayahNumber: 16,
		translationId: '(Ingatlah) pada hari (ketika) Kami menghantam mereka dengan keras. Kami pasti memberi balasan.',
	),
	Ayah(
		ayahId: 4431,
		ayahText: '۞ وَلَقَدْ فَتَنَّا قَبْلَهُمْ قَوْمَ فِرْعَوْنَ وَجَاۤءَهُمْ رَسُوْلٌ كَرِيْمٌۙ ',
		ayahNumber: 17,
		translationId: 'Dan sungguh, sebelum mereka Kami benar-benar telah menguji kaum Fir’aun dan telah datang kepada mereka seorang Rasul yang mulia,',
	),
	Ayah(
		ayahId: 4432,
		ayahText: 'اَنْ اَدُّوْٓا اِلَيَّ عِبَادَ اللّٰهِ ۗاِنِّيْ لَكُمْ رَسُوْلٌ اَمِيْنٌۙ ',
		ayahNumber: 18,
		translationId: '(dengan berkata), “Serahkanlah kepadaku hamba-hamba Allah (Bani Israil). Sesungguhnya aku adalah utusan (Allah) yang dapat kamu percaya,',
	),
	Ayah(
		ayahId: 4433,
		ayahText: 'وَّاَنْ لَّا تَعْلُوْا عَلَى اللّٰهِ ۚاِنِّيْٓ اٰتِيْكُمْ بِسُلْطٰنٍ مُّبِيْنٍۚ ',
		ayahNumber: 19,
		translationId: 'dan janganlah kamu menyombongkan diri terhadap Allah. Sungguh, aku datang kepadamu dengan membawa bukti yang nyata.',
	),
	Ayah(
		ayahId: 4434,
		ayahText: 'وَاِنِّيْ عُذْتُ بِرَبِّيْ وَرَبِّكُمْ اَنْ تَرْجُمُوْنِۚ ',
		ayahNumber: 20,
		translationId: 'Dan sesungguhnya aku berlindung kepada Tuhanku dan Tuhanmu, dari ancamanmu untuk merajamku,',
	),
	Ayah(
		ayahId: 4435,
		ayahText: 'وَاِنْ لَّمْ تُؤْمِنُوْا لِيْ فَاعْتَزِلُوْنِ ',
		ayahNumber: 21,
		translationId: 'dan jika kamu tidak beriman kepadaku maka biarkanlah aku (memimpin Bani Israil).”',
	),
	Ayah(
		ayahId: 4436,
		ayahText: 'فَدَعَا رَبَّهٗٓ اَنَّ هٰٓؤُلَاۤءِ قَوْمٌ مُّجْرِمُوْنَ ',
		ayahNumber: 22,
		translationId: 'Kemudian dia (Musa) berdoa kepada Tuhannya, “Sungguh, mereka ini adalah kaum yang berdosa (segerakanlah azab kepada mereka).”',
	),
	Ayah(
		ayahId: 4437,
		ayahText: 'فَاَسْرِ بِعِبَادِيْ لَيْلًا اِنَّكُمْ مُّتَّبَعُوْنَۙ ',
		ayahNumber: 23,
		translationId: '(Allah berfirman), “Karena itu berjalanlah dengan hamba-hamba-Ku pada malam hari, sesungguhnya kamu akan dikejar,',
	),
	Ayah(
		ayahId: 4438,
		ayahText: 'وَاتْرُكِ الْبَحْرَ رَهْوًاۗ اِنَّهُمْ جُنْدٌ مُّغْرَقُوْنَ ',
		ayahNumber: 24,
		translationId: 'dan biarkanlah laut itu terbelah. Sesungguhnya mereka, bala tentara yang akan ditenggelamkan.”',
	),
	Ayah(
		ayahId: 4439,
		ayahText: 'كَمْ تَرَكُوْا مِنْ جَنّٰتٍ وَّعُيُوْنٍۙ ',
		ayahNumber: 25,
		translationId: 'Betapa banyak taman-taman dan mata air-mata air yang mereka tinggalkan,',
	),
	Ayah(
		ayahId: 4440,
		ayahText: 'وَّزُرُوْعٍ وَّمَقَامٍ كَرِيْمٍۙ ',
		ayahNumber: 26,
		translationId: 'juga kebun-kebun serta tempat-tempat kediaman yang indah,',
	),
	Ayah(
		ayahId: 4441,
		ayahText: 'وَّنَعْمَةٍ كَانُوْا فِيْهَا فٰكِهِيْنَۙ ',
		ayahNumber: 27,
		translationId: 'dan kesenangan-kesenangan yang dapat mereka nikmati di sana,',
	),
	Ayah(
		ayahId: 4442,
		ayahText: 'كَذٰلِكَ ۗوَاَوْرَثْنٰهَا قَوْمًا اٰخَرِيْنَۚ',
		ayahNumber: 28,
		translationId: 'demikianlah, dan Kami wariskan (semua) itu kepada kaum yang lain.',
	),
	Ayah(
		ayahId: 4443,
		ayahText: 'فَمَا بَكَتْ عَلَيْهِمُ السَّمَاۤءُ وَالْاَرْضُۗ وَمَا كَانُوْا مُنْظَرِيْنَ ࣖ',
		ayahNumber: 29,
		translationId: 'Maka langit dan bumi tidak menangisi mereka dan mereka pun tidak diberi penangguhan waktu.',
	),
	Ayah(
		ayahId: 4444,
		ayahText: 'وَلَقَدْ نَجَّيْنَا بَنِيْٓ اِسْرَاۤءِيْلَ مِنَ الْعَذَابِ الْمُهِيْنِۙ ',
		ayahNumber: 30,
		translationId: 'Dan sungguh, telah Kami selamatkan Bani Israil dari siksaan yang menghinakan,',
	),
	Ayah(
		ayahId: 4445,
		ayahText: 'مِنْ فِرْعَوْنَ ۗاِنَّهٗ كَانَ عَالِيًا مِّنَ الْمُسْرِفِيْنَ ',
		ayahNumber: 31,
		translationId: 'dari (siksaan) Fir‘aun, sungguh, dia itu orang yang sombong, termasuk orang-orang yang melampaui batas.',
	),
	Ayah(
		ayahId: 4446,
		ayahText: 'وَلَقَدِ اخْتَرْنٰهُمْ عَلٰى عِلْمٍ عَلَى الْعٰلَمِيْنَ ۚ ',
		ayahNumber: 32,
		translationId: 'Dan sungguh, Kami pilih mereka (Bani Israil) dengan ilmu (Kami) di atas semua bangsa (pada masa itu).',
	),
	Ayah(
		ayahId: 4447,
		ayahText: 'وَاٰتَيْنٰهُمْ مِّنَ الْاٰيٰتِ مَا فِيْهِ بَلٰۤـؤٌا مُّبِيْنٌ ',
		ayahNumber: 33,
		translationId: 'Dan telah Kami berikan kepada mereka di antara tanda-tanda (kebesaran Kami) sesuatu yang di dalamnya terdapat nikmat yang nyata.',
	),
	Ayah(
		ayahId: 4448,
		ayahText: 'اِنَّ هٰٓؤُلَاۤءِ لَيَقُوْلُوْنَۙ ',
		ayahNumber: 34,
		translationId: 'Sesungguhnya mereka (kaum musyrik) itu pasti akan berkata,',
	),
	Ayah(
		ayahId: 4449,
		ayahText: 'اِنْ هِيَ اِلَّا مَوْتَتُنَا الْاُوْلٰى وَمَا نَحْنُ بِمُنْشَرِيْنَ ',
		ayahNumber: 35,
		translationId: '”Tidak ada kematian selain kematian di dunia ini. Dan kami tidak akan dibangkitkan,',
	),
	Ayah(
		ayahId: 4450,
		ayahText: 'فَأْتُوْا بِاٰبَاۤىِٕنَآ اِنْ كُنْتُمْ صٰدِقِيْنَ ',
		ayahNumber: 36,
		translationId: 'maka hadirkanlah (kembali) nenek moyang kami jika kamu orang yang benar.”',
	),
	Ayah(
		ayahId: 4451,
		ayahText: 'اَهُمْ خَيْرٌ اَمْ قَوْمُ تُبَّعٍۙ وَّالَّذِيْنَ مِنْ قَبْلِهِمْۗ اَهْلَكْنٰهُمْ اِنَّهُمْ كَانُوْا مُجْرِمِيْنَ',
		ayahNumber: 37,
		translationId: 'Apakah mereka (kaum musyrikin) yang lebih baik atau kaum Tubba‘, dan orang-orang yang sebelum mereka yang telah Kami binasakan karena mereka itu adalah orang-orang yang sungguh berdosa.',
	),
	Ayah(
		ayahId: 4452,
		ayahText: 'وَمَا خَلَقْنَا السَّمٰوٰتِ وَالْاَرْضَ وَمَا بَيْنَهُمَا لٰعِبِيْنَ',
		ayahNumber: 38,
		translationId: 'Dan tidaklah Kami bermain-main menciptakan langit dan bumi dan apa yang ada di antara keduanya.  ',
	),
	Ayah(
		ayahId: 4453,
		ayahText: 'مَا خَلَقْنٰهُمَآ اِلَّا بِالْحَقِّ وَلٰكِنَّ اَكْثَرَهُمْ لَا يَعْلَمُوْنَ',
		ayahNumber: 39,
		translationId: 'Tidaklah Kami ciptakan keduanya melainkan dengan haq (benar), tetapi kebanyakan mereka tidak mengetahui.',
	),
	Ayah(
		ayahId: 4454,
		ayahText: 'اِنَّ يَوْمَ الْفَصْلِ مِيْقَاتُهُمْ اَجْمَعِيْنَ ۙ ',
		ayahNumber: 40,
		translationId: 'Sungguh, pada hari keputusan (hari Kiamat) itu adalah waktu yang dijanjikan bagi mereka semuanya,',
	),
	Ayah(
		ayahId: 4455,
		ayahText: 'يَوْمَ لَا يُغْنِيْ مَوْلًى عَنْ مَّوْلًى شَيْـًٔا وَّلَا هُمْ يُنْصَرُوْنَۙ ',
		ayahNumber: 41,
		translationId: '(yaitu) pada hari (ketika) seorang teman sama sekali tidak dapat memberi manfaat kepada teman lainnya dan mereka tidak akan mendapat pertolongan,',
	),
	Ayah(
		ayahId: 4456,
		ayahText: 'اِلَّا مَنْ رَّحِمَ اللّٰهُ ۗاِنَّهٗ هُوَ الْعَزِيْزُ الرَّحِيْمُ ࣖ ',
		ayahNumber: 42,
		translationId: 'Kecuali orang yang diberi rahmat oleh Allah. Sungguh, Dia Mahaperkasa, Maha Penyayang.',
	),
	Ayah(
		ayahId: 4457,
		ayahText: 'اِنَّ شَجَرَتَ الزَّقُّوْمِۙ',
		ayahNumber: 43,
		translationId: 'Sungguh pohon zaqqum itu,',
	),
	Ayah(
		ayahId: 4458,
		ayahText: 'طَعَامُ الْاَثِيْمِ ۛ ',
		ayahNumber: 44,
		translationId: 'makanan bagi orang yang banyak dosa.',
	),
	Ayah(
		ayahId: 4459,
		ayahText: 'كَالْمُهْلِ ۛ يَغْلِيْ فِى الْبُطُوْنِۙ ',
		ayahNumber: 45,
		translationId: 'Seperti cairan tembaga yang mendidih di dalam perut,',
	),
	Ayah(
		ayahId: 4460,
		ayahText: 'كَغَلْيِ الْحَمِيْمِ ۗ',
		ayahNumber: 46,
		translationId: 'seperti mendidihnya air yang sangat panas.',
	),
	Ayah(
		ayahId: 4461,
		ayahText: 'خُذُوْهُ فَاعْتِلُوْهُ اِلٰى سَوَاۤءِ الْجَحِيْمِۙ ',
		ayahNumber: 47,
		translationId: '”Peganglah dia kemudian seretlah dia sampai ke tengah-tengah neraka,',
	),
	Ayah(
		ayahId: 4462,
		ayahText: 'ثُمَّ صُبُّوْا فَوْقَ رَأْسِهٖ مِنْ عَذَابِ الْحَمِيْمِۗ',
		ayahNumber: 48,
		translationId: 'kemudian tuangkanlah di atas kepalanya azab (dari) air yang sangat panas.”',
	),
	Ayah(
		ayahId: 4463,
		ayahText: 'ذُقْۚ اِنَّكَ اَنْتَ الْعَزِيْزُ الْكَرِيْمُ ',
		ayahNumber: 49,
		translationId: '”Rasakanlah, sesungguhnya kamu benar-benar orang yang perkasa lagi mulia.”',
	),
	Ayah(
		ayahId: 4464,
		ayahText: 'اِنَّ هٰذَا مَا كُنْتُمْ بِهٖ تَمْتَرُوْنَ ',
		ayahNumber: 50,
		translationId: 'Sungguh, inilah azab yang dahulu kamu ragukan.',
	),
	Ayah(
		ayahId: 4465,
		ayahText: 'اِنَّ الْمُتَّقِيْنَ فِيْ مَقَامٍ اَمِيْنٍۙ',
		ayahNumber: 51,
		translationId: 'Sungguh, orang-orang yang bertakwa berada dalam tempat yang aman,',
	),
	Ayah(
		ayahId: 4466,
		ayahText: 'فِيْ جَنّٰتٍ وَّعُيُوْنٍ ۙ',
		ayahNumber: 52,
		translationId: '(yaitu) di dalam taman-taman dan mata air-mata air,',
	),
	Ayah(
		ayahId: 4467,
		ayahText: 'يَّلْبَسُوْنَ مِنْ سُنْدُسٍ وَّاِسْتَبْرَقٍ مُّتَقٰبِلِيْنَۚ',
		ayahNumber: 53,
		translationId: 'mereka memakai sutra yang halus dan sutra yang tebal, (duduk) berhadapan,',
	),
	Ayah(
		ayahId: 4468,
		ayahText: 'كَذٰلِكَۗ وَزَوَّجْنٰهُمْ بِحُوْرٍ عِيْنٍۗ ',
		ayahNumber: 54,
		translationId: 'demikianlah, kemudian Kami berikan kepada mereka pasangan bidadari yang bermata indah.',
	),
	Ayah(
		ayahId: 4469,
		ayahText: 'يَدْعُوْنَ فِيْهَا بِكُلِّ فَاكِهَةٍ اٰمِنِيْنَۙ ',
		ayahNumber: 55,
		translationId: 'Di dalamnya mereka dapat meminta segala macam buah-buahan dengan aman dan tenteram,',
	),
	Ayah(
		ayahId: 4470,
		ayahText: 'لَا يَذُوْقُوْنَ فِيْهَا الْمَوْتَ اِلَّا الْمَوْتَةَ الْاُوْلٰىۚ وَوَقٰىهُمْ عَذَابَ الْجَحِيْمِۙ ',
		ayahNumber: 56,
		translationId: 'mereka tidak akan merasakan mati di dalamnya selain kematian pertama (di dunia). Allah melindungi mereka dari azab neraka,',
	),
	Ayah(
		ayahId: 4471,
		ayahText: 'فَضْلًا مِّنْ رَّبِّكَۚ ذٰلِكَ هُوَ الْفَوْزُ الْعَظِيْمُ',
		ayahNumber: 57,
		translationId: 'itu merupakan karunia dari Tuhanmu. Demikian itulah kemenangan yang agung.',
	),
	Ayah(
		ayahId: 4472,
		ayahText: 'فَاِنَّمَا يَسَّرْنٰهُ بِلِسَانِكَ لَعَلَّهُمْ يَتَذَكَّرُوْنَ',
		ayahNumber: 58,
		translationId: "Sungguh, Kami mudahkan Al-Qur'an itu dengan bahasamu agar mereka mendapat pelajaran.",
	),
	Ayah(
		ayahId: 4473,
		ayahText: 'فَارْتَقِبْ اِنَّهُمْ مُّرْتَقِبُوْنَ ࣖࣖ',
		ayahNumber: 59,
		translationId: 'Maka tunggulah; sungguh, mereka itu (juga sedang) menunggu.',
	),
];
