// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah77 = [
	Ayah(
		ayahId: 5623,
		ayahText: 'وَالْمُرْسَلٰتِ عُرْفًاۙ',
		ayahNumber: 1,
		translationId: 'Demi (malaikat-malaikat) yang diutus untuk membawa kebaikan,',
	),
	Ayah(
		ayahId: 5624,
		ayahText: 'فَالْعٰصِفٰتِ عَصْفًاۙ',
		ayahNumber: 2,
		translationId: 'dan (malaikat-malaikat) yang terbang dengan kencangnya,',
	),
	Ayah(
		ayahId: 5625,
		ayahText: 'وَّالنّٰشِرٰتِ نَشْرًاۙ',
		ayahNumber: 3,
		translationId: 'dan (malaikat-malaikat) yang menyebarkan (rahmat Allah) dengan seluas-luasnya,',
	),
	Ayah(
		ayahId: 5626,
		ayahText: 'فَالْفٰرِقٰتِ فَرْقًاۙ',
		ayahNumber: 4,
		translationId: 'dan (malaikat-malaikat) yang membedakan (antara yang baik dan yang buruk) dengan sejelas-jelasnya,',
	),
	Ayah(
		ayahId: 5627,
		ayahText: 'فَالْمُلْقِيٰتِ ذِكْرًاۙ',
		ayahNumber: 5,
		translationId: 'dan (malaikat-malaikat) yang menyampaikan wahyu,',
	),
	Ayah(
		ayahId: 5628,
		ayahText: 'عُذْرًا اَوْ نُذْرًاۙ',
		ayahNumber: 6,
		translationId: 'untuk menolak alasan-alasan atau memberi peringatan.',
	),
	Ayah(
		ayahId: 5629,
		ayahText: 'اِنَّمَا تُوْعَدُوْنَ لَوَاقِعٌۗ',
		ayahNumber: 7,
		translationId: 'Sungguh, apa yang dijanjikan kepadamu pasti terjadi.',
	),
	Ayah(
		ayahId: 5630,
		ayahText: 'فَاِذَا النُّجُوْمُ طُمِسَتْۙ',
		ayahNumber: 8,
		translationId: 'Maka apabila bintang-bintang dihapuskan,',
	),
	Ayah(
		ayahId: 5631,
		ayahText: 'وَاِذَا السَّمَاۤءُ فُرِجَتْۙ',
		ayahNumber: 9,
		translationId: 'dan apabila langit terbelah,',
	),
	Ayah(
		ayahId: 5632,
		ayahText: 'وَاِذَا الْجِبَالُ نُسِفَتْۙ',
		ayahNumber: 10,
		translationId: 'dan apabila gunung-gunung dihancurkan menjadi debu,',
	),
	Ayah(
		ayahId: 5633,
		ayahText: 'وَاِذَا الرُّسُلُ اُقِّتَتْۗ',
		ayahNumber: 11,
		translationId: 'dan apabila rasul-rasul telah ditetapkan waktunya.',
	),
	Ayah(
		ayahId: 5634,
		ayahText: 'لِاَيِّ يَوْمٍ اُجِّلَتْۗ',
		ayahNumber: 12,
		translationId: '(Niscaya dikatakan kepada mereka), “Sampai hari apakah ditangguhkan (azab orang-orang kafir itu)?”',
	),
	Ayah(
		ayahId: 5635,
		ayahText: 'لِيَوْمِ الْفَصْلِۚ',
		ayahNumber: 13,
		translationId: 'Sampai hari keputusan.',
	),
	Ayah(
		ayahId: 5636,
		ayahText: 'وَمَآ اَدْرٰىكَ مَا يَوْمُ الْفَصْلِۗ',
		ayahNumber: 14,
		translationId: 'Dan tahukah kamu apakah hari ke-putusan itu?',
	),
	Ayah(
		ayahId: 5637,
		ayahText: 'وَيْلٌ يَّوْمَىِٕذٍ لِّلْمُكَذِّبِيْنَ ',
		ayahNumber: 15,
		translationId: 'Celakalah pada hari itu, bagi mereka yang mendustakan (kebenaran).',
	),
	Ayah(
		ayahId: 5638,
		ayahText: 'اَلَمْ نُهْلِكِ الْاَوَّلِيْنَۗ',
		ayahNumber: 16,
		translationId: 'Bukankah telah Kami binasakan orang-orang yang dahulu?',
	),
	Ayah(
		ayahId: 5639,
		ayahText: 'ثُمَّ نُتْبِعُهُمُ الْاٰخِرِيْنَ ',
		ayahNumber: 17,
		translationId: 'Lalu Kami susulkan (azab Kami terhadap) orang-orang yang datang kemudian.',
	),
	Ayah(
		ayahId: 5640,
		ayahText: 'كَذٰلِكَ نَفْعَلُ بِالْمُجْرِمِيْنَ ',
		ayahNumber: 18,
		translationId: 'Demikianlah Kami perlakukan orang-orang yang berdosa.',
	),
	Ayah(
		ayahId: 5641,
		ayahText: 'وَيْلٌ يَّوْمَىِٕذٍ لِّلْمُكَذِّبِيْنَ ',
		ayahNumber: 19,
		translationId: 'Celakalah pada hari itu, bagi mereka yang mendustakan (kebenaran).',
	),
	Ayah(
		ayahId: 5642,
		ayahText: 'اَلَمْ نَخْلُقْكُّمْ مِّنْ مَّاۤءٍ مَّهِيْنٍۙ',
		ayahNumber: 20,
		translationId: 'Bukankah Kami menciptakan kamu dari air yang hina (mani),',
	),
	Ayah(
		ayahId: 5643,
		ayahText: 'فَجَعَلْنٰهُ فِيْ قَرَارٍ مَّكِيْنٍ',
		ayahNumber: 21,
		translationId: 'kemudian Kami letakkan ia dalam tempat yang kokoh (rahim),',
	),
	Ayah(
		ayahId: 5644,
		ayahText: 'اِلٰى قَدَرٍ مَّعْلُوْمٍۙ',
		ayahNumber: 22,
		translationId: 'sampai waktu yang ditentukan,',
	),
	Ayah(
		ayahId: 5645,
		ayahText: 'فَقَدَرْنَاۖ فَنِعْمَ الْقٰدِرُوْنَ ',
		ayahNumber: 23,
		translationId: 'lalu Kami tentukan (bentuknya), maka (Kamilah) sebaik-baik yang menentukan.',
	),
	Ayah(
		ayahId: 5646,
		ayahText: 'وَيْلٌ يَّوْمَىِٕذٍ لِّلْمُكَذِّبِيْنَ ',
		ayahNumber: 24,
		translationId: 'Celakalah pada hari itu, bagi mereka yang mendustakan (kebenaran).',
	),
	Ayah(
		ayahId: 5647,
		ayahText: 'اَلَمْ نَجْعَلِ الْاَرْضَ كِفَاتًاۙ',
		ayahNumber: 25,
		translationId: 'Bukankah Kami jadikan bumi untuk (tempat) berkumpul,',
	),
	Ayah(
		ayahId: 5648,
		ayahText: 'اَحْيَاۤءً وَّاَمْوَاتًاۙ',
		ayahNumber: 26,
		translationId: 'bagi yang masih hidup dan yang sudah mati?',
	),
	Ayah(
		ayahId: 5649,
		ayahText: 'وَّجَعَلْنَا فِيْهَا رَوَاسِيَ شٰمِخٰتٍ وَّاَسْقَيْنٰكُمْ مَّاۤءً فُرَاتًاۗ',
		ayahNumber: 27,
		translationId: 'Dan Kami jadikan padanya gunung-gunung yang tinggi, dan Kami beri minum kamu dengan air tawar?',
	),
	Ayah(
		ayahId: 5650,
		ayahText: 'وَيْلٌ يَّوْمَىِٕذٍ لِّلْمُكَذِّبِيْنَ ',
		ayahNumber: 28,
		translationId: 'Celakalah pada hari itu, bagi mereka yang mendustakan (kebenaran).',
	),
	Ayah(
		ayahId: 5651,
		ayahText: 'اِنْطَلِقُوْٓا اِلٰى مَا كُنْتُمْ بِهٖ تُكَذِّبُوْنَۚ',
		ayahNumber: 29,
		translationId: '(Akan dikatakan), “Pergilah kamu mendapatkan apa (azab) yang dahulu kamu dustakan.',
	),
	Ayah(
		ayahId: 5652,
		ayahText: 'اِنْطَلِقُوْٓا اِلٰى ظِلٍّ ذِيْ ثَلٰثِ شُعَبٍ ',
		ayahNumber: 30,
		translationId: 'Pergilah kamu mendapatkan naungan (asap api neraka) yang mempunyai tiga cabang, ',
	),
	Ayah(
		ayahId: 5653,
		ayahText: 'لَا ظَلِيْلٍ وَّلَا يُغْنِيْ مِنَ اللَّهَبِۗ',
		ayahNumber: 31,
		translationId: 'yang tidak melindungi dan tidak pula menolak nyala api neraka.” ',
	),
	Ayah(
		ayahId: 5654,
		ayahText: 'اِنَّهَا تَرْمِيْ بِشَرَرٍ كَالْقَصْرِۚ',
		ayahNumber: 32,
		translationId: 'Sungguh, (neraka) itu menyemburkan bunga api (sebesar dan setinggi) istana, ',
	),
	Ayah(
		ayahId: 5655,
		ayahText: 'كَاَنَّهٗ جِمٰلَتٌ صُفْرٌۗ',
		ayahNumber: 33,
		translationId: 'seakan-akan iring-iringan unta yang kuning.',
	),
	Ayah(
		ayahId: 5656,
		ayahText: 'وَيْلٌ يَّوْمَىِٕذٍ لِّلْمُكَذِّبِيْنَ ',
		ayahNumber: 34,
		translationId: 'Celakalah pada hari itu, bagi mereka yang mendustakan (kebenaran). ',
	),
	Ayah(
		ayahId: 5657,
		ayahText: 'هٰذَا يَوْمُ لَا يَنْطِقُوْنَۙ',
		ayahNumber: 35,
		translationId: 'Inilah hari, saat mereka tidak dapat berbicara, ',
	),
	Ayah(
		ayahId: 5658,
		ayahText: 'وَلَا يُؤْذَنُ لَهُمْ فَيَعْتَذِرُوْنَ ',
		ayahNumber: 36,
		translationId: 'dan tidak diizinkan kepada mereka mengemukakan alasan agar mereka dimaafkan. ',
	),
	Ayah(
		ayahId: 5659,
		ayahText: 'وَيْلٌ يَّوْمَىِٕذٍ لِّلْمُكَذِّبِيْنَ ',
		ayahNumber: 37,
		translationId: 'Celakalah pada hari itu, bagi mereka yang mendustakan (kebenaran). ',
	),
	Ayah(
		ayahId: 5660,
		ayahText: 'هٰذَا يَوْمُ الْفَصْلِ جَمَعْنٰكُمْ وَالْاَوَّلِيْنَ ',
		ayahNumber: 38,
		translationId: 'Inilah hari keputusan; (pada hari ini) Kami kumpulkan kamu dan orang-orang yang terdahulu. ',
	),
	Ayah(
		ayahId: 5661,
		ayahText: 'فَاِنْ كَانَ لَكُمْ كَيْدٌ فَكِيْدُوْنِ ',
		ayahNumber: 39,
		translationId: 'Maka jika kamu punya tipu daya, maka lakukanlah (tipu daya) itu terhadap-Ku. ',
	),
	Ayah(
		ayahId: 5662,
		ayahText: 'وَيْلٌ يَّوْمَىِٕذٍ لِّلْمُكَذِّبِيْنَ ࣖ ',
		ayahNumber: 40,
		translationId: 'Celakalah pada hari itu, bagi mereka yang mendustakan (kebenaran).',
	),
	Ayah(
		ayahId: 5663,
		ayahText: 'اِنَّ الْمُتَّقِيْنَ فِيْ ظِلٰلٍ وَّعُيُوْنٍۙ',
		ayahNumber: 41,
		translationId: 'Sungguh, orang-orang yang bertakwa berada dalam naungan (pepohonan surga yang teduh) dan (di sekitar) mata air, ',
	),
	Ayah(
		ayahId: 5664,
		ayahText: 'وَّفَوَاكِهَ مِمَّا يَشْتَهُوْنَۗ',
		ayahNumber: 42,
		translationId: 'dan buah-buahan yang mereka sukai. ',
	),
	Ayah(
		ayahId: 5665,
		ayahText: 'كُلُوْا وَاشْرَبُوْا هَنِيْۤـًٔا ۢبِمَا كُنْتُمْ تَعْمَلُوْنَ ',
		ayahNumber: 43,
		translationId: '(Katakan kepada mereka), “Makan dan minumlah dengan rasa nikmat sebagai balasan dari apa yang telah kamu kerjakan.” ',
	),
	Ayah(
		ayahId: 5666,
		ayahText: 'اِنَّا كَذٰلِكَ نَجْزِى الْمُحْسِنِيْنَ ',
		ayahNumber: 44,
		translationId: 'Sungguh, demikianlah Kami memberi balasan kepada orang-orang yang berbuat baik. ',
	),
	Ayah(
		ayahId: 5667,
		ayahText: 'وَيْلٌ يَّوْمَىِٕذٍ لِّلْمُكَذِّبِيْنَ ',
		ayahNumber: 45,
		translationId: 'Celakalah pada hari itu, bagi mereka yang mendustakan (kebenaran). ',
	),
	Ayah(
		ayahId: 5668,
		ayahText: 'كُلُوْا وَتَمَتَّعُوْا قَلِيْلًا اِنَّكُمْ مُّجْرِمُوْنَ ',
		ayahNumber: 46,
		translationId: '(Katakan kepada orang-orang kafir), “Makan dan bersenang-senanglah kamu (di dunia) sebentar, sesungguhnya kamu orang-orang durhaka!”',
	),
	Ayah(
		ayahId: 5669,
		ayahText: 'وَيْلٌ يَّوْمَىِٕذٍ لِّلْمُكَذِّبِيْنَ ',
		ayahNumber: 47,
		translationId: 'Celakalah pada hari itu, bagi mereka yang mendustakan (kebenaran). ',
	),
	Ayah(
		ayahId: 5670,
		ayahText: 'وَاِذَا قِيْلَ لَهُمُ ارْكَعُوْا لَا يَرْكَعُوْنَ ',
		ayahNumber: 48,
		translationId: 'Dan apabila dikatakan kepada mereka, “Rukuklah,” mereka tidak mau rukuk.',
	),
	Ayah(
		ayahId: 5671,
		ayahText: 'وَيْلٌ يَّوْمَىِٕذٍ لِّلْمُكَذِّبِيْنَ ',
		ayahNumber: 49,
		translationId: 'Celakalah pada hari itu, bagi mereka yang mendustakan (kebenaran)! ',
	),
	Ayah(
		ayahId: 5672,
		ayahText: 'فَبِاَيِّ حَدِيْثٍۢ بَعْدَهٗ يُؤْمِنُوْنَ ࣖ   ۔',
		ayahNumber: 50,
		translationId: "Maka kepada ajaran manakah (selain Al-Qur'an) ini mereka akan beriman?",
	),
];
