// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah51 = [
	Ayah(
		ayahId: 4676,
		ayahText: ' وَالذّٰرِيٰتِ ذَرْوًاۙ',
		ayahNumber: 1,
		translationId: 'Demi (angin) yang menerbangkan debu, ',
	),
	Ayah(
		ayahId: 4677,
		ayahText: 'فَالْحٰمِلٰتِ وِقْرًاۙ',
		ayahNumber: 2,
		translationId: 'dan awan yang mengandung (hujan),',
	),
	Ayah(
		ayahId: 4678,
		ayahText: 'فَالْجٰرِيٰتِ يُسْرًاۙ',
		ayahNumber: 3,
		translationId: 'dan (kapal-kapal) yang berlayar dengan mudah, ',
	),
	Ayah(
		ayahId: 4679,
		ayahText: 'فَالْمُقَسِّمٰتِ اَمْرًاۙ',
		ayahNumber: 4,
		translationId: 'dan (malaikat-malaikat) yang membagi-bagi urusan,',
	),
	Ayah(
		ayahId: 4680,
		ayahText: 'اِنَّمَا تُوْعَدُوْنَ لَصَادِقٌۙ',
		ayahNumber: 5,
		translationId: 'sungguh, apa yang dijanjikan kepadamu pasti benar, ',
	),
	Ayah(
		ayahId: 4681,
		ayahText: 'وَّاِنَّ الدِّيْنَ لَوَاقِعٌۗ',
		ayahNumber: 6,
		translationId: 'dan sungguh, (hari) pembalasan pasti terjadi.',
	),
	Ayah(
		ayahId: 4682,
		ayahText: 'وَالسَّمَاۤءِ ذَاتِ الْحُبُكِۙ',
		ayahNumber: 7,
		translationId: 'Demi langit yang mempunyai jalan-jalan,',
	),
	Ayah(
		ayahId: 4683,
		ayahText: 'اِنَّكُمْ لَفِيْ قَوْلٍ مُّخْتَلِفٍۙ',
		ayahNumber: 8,
		translationId: 'sungguh, kamu benar-benar dalam keadaan berbeda-beda pendapat,',
	),
	Ayah(
		ayahId: 4684,
		ayahText: 'يُّؤْفَكُ عَنْهُ مَنْ اُفِكَۗ',
		ayahNumber: 9,
		translationId: "dipalingkan darinya (Al-Qur'an dan Rasul) orang yang dipalingkan.",
	),
	Ayah(
		ayahId: 4685,
		ayahText: 'قُتِلَ الْخَرَّاصُوْنَۙ',
		ayahNumber: 10,
		translationId: 'Terkutuklah orang-orang yang banyak berdusta,',
	),
	Ayah(
		ayahId: 4686,
		ayahText: 'الَّذِيْنَ هُمْ فِيْ غَمْرَةٍ سَاهُوْنَۙ',
		ayahNumber: 11,
		translationId: '(yaitu) orang-orang yang terbenam dalam kebodohan dan kelalaian, ',
	),
	Ayah(
		ayahId: 4687,
		ayahText: 'يَسْـَٔلُوْنَ اَيَّانَ يَوْمُ الدِّيْنِۗ',
		ayahNumber: 12,
		translationId: 'mereka bertanya, “Kapankah hari pembalasan itu?”',
	),
	Ayah(
		ayahId: 4688,
		ayahText: 'يَوْمَ هُمْ عَلَى النَّارِ يُفْتَنُوْنَ ',
		ayahNumber: 13,
		translationId: '(Hari pembalasan itu ialah) pada hari (ketika) mereka diazab di dalam api neraka. ',
	),
	Ayah(
		ayahId: 4689,
		ayahText: 'ذُوْقُوْا فِتْنَتَكُمْۗ هٰذَا الَّذِيْ كُنْتُمْ بِهٖ تَسْتَعْجِلُوْنَ ',
		ayahNumber: 14,
		translationId: '(Dikatakan kepada mereka), “Rasakanlah azabmu ini. Inilah azab yang dahulu kamu minta agar disegerakan.” ',
	),
	Ayah(
		ayahId: 4690,
		ayahText: 'اِنَّ الْمُتَّقِيْنَ فِيْ جَنّٰتٍ وَّعُيُوْنٍۙ',
		ayahNumber: 15,
		translationId: 'Sesungguhnya orang-orang yang bertakwa berada di dalam taman-taman (surga) dan mata air,',
	),
	Ayah(
		ayahId: 4691,
		ayahText: 'اٰخِذِيْنَ مَآ اٰتٰىهُمْ رَبُّهُمْ ۗ اِنَّهُمْ كَانُوْا قَبْلَ ذٰلِكَ مُحْسِنِيْنَۗ',
		ayahNumber: 16,
		translationId: 'mereka mengambil apa yang diberikan Tuhan kepada mereka. Sesungguhnya mereka sebelum itu (di dunia) adalah orang-orang yang berbuat baik;',
	),
	Ayah(
		ayahId: 4692,
		ayahText: 'كَانُوْا قَلِيْلًا مِّنَ الَّيْلِ مَا يَهْجَعُوْنَ ',
		ayahNumber: 17,
		translationId: 'mereka sedikit sekali tidur pada waktu malam;',
	),
	Ayah(
		ayahId: 4693,
		ayahText: 'وَبِالْاَسْحَارِ هُمْ يَسْتَغْفِرُوْنَ ',
		ayahNumber: 18,
		translationId: 'dan pada akhir malam mereka memohon ampunan (kepada Allah).',
	),
	Ayah(
		ayahId: 4694,
		ayahText: 'وَفِيْٓ اَمْوَالِهِمْ حَقٌّ لِّلسَّاۤىِٕلِ وَالْمَحْرُوْمِ ',
		ayahNumber: 19,
		translationId: 'Dan pada harta benda mereka ada hak untuk orang miskin yang meminta dan orang miskin yang tidak meminta. ',
	),
	Ayah(
		ayahId: 4695,
		ayahText: 'وَفِى الْاَرْضِ اٰيٰتٌ لِّلْمُوْقِنِيْنَۙ',
		ayahNumber: 20,
		translationId: 'Dan di bumi terdapat tanda-tanda (kebesaran Allah) bagi orang-orang yang yakin,',
	),
	Ayah(
		ayahId: 4696,
		ayahText: 'وَفِيْٓ اَنْفُسِكُمْ ۗ اَفَلَا تُبْصِرُوْنَ ',
		ayahNumber: 21,
		translationId: 'dan (juga) pada dirimu sendiri. Maka apakah kamu tidak memperhatikan?',
	),
	Ayah(
		ayahId: 4697,
		ayahText: 'وَفِى السَّمَاۤءِ رِزْقُكُمْ وَمَا تُوْعَدُوْنَ ',
		ayahNumber: 22,
		translationId: 'Dan di langit terdapat (sebab-sebab) rezekimu dan apa yang dijanjikan kepadamu.',
	),
	Ayah(
		ayahId: 4698,
		ayahText: 'فَوَرَبِّ السَّمَاۤءِ وَالْاَرْضِ اِنَّهٗ لَحَقٌّ مِّثْلَ مَآ اَنَّكُمْ تَنْطِقُوْنَ ࣖ',
		ayahNumber: 23,
		translationId: 'Maka demi Tuhan langit dan bumi, sungguh, apa yang dijanjikan itu pasti terjadi seperti apa yang kamu ucapkan. ',
	),
	Ayah(
		ayahId: 4699,
		ayahText: 'هَلْ اَتٰىكَ حَدِيْثُ ضَيْفِ اِبْرٰهِيْمَ الْمُكْرَمِيْنَۘ ',
		ayahNumber: 24,
		translationId: 'Sudahkah sampai kepadamu (Muhammad) cerita tamu Ibrahim (malaikat-malaikat) yang dimuliakan?',
	),
	Ayah(
		ayahId: 4700,
		ayahText: 'اِذْ دَخَلُوْا عَلَيْهِ فَقَالُوْا سَلٰمًا ۗقَالَ سَلٰمٌۚ قَوْمٌ مُّنْكَرُوْنَ ',
		ayahNumber: 25,
		translationId: '(Ingatlah) ketika mereka masuk ke tempatnya lalu mengucapkan, “Salaman” (salam), Ibrahim menjawab, “Salamun” (salam). (Mereka itu) orang-orang yang belum dikenalnya. ',
	),
	Ayah(
		ayahId: 4701,
		ayahText: 'فَرَاغَ اِلٰٓى اَهْلِهٖ فَجَاۤءَ بِعِجْلٍ سَمِيْنٍۙ',
		ayahNumber: 26,
		translationId: 'Maka diam-diam dia (Ibrahim) pergi menemui keluarganya, kemudian dibawanya daging anak sapi gemuk (yang dibakar),',
	),
	Ayah(
		ayahId: 4702,
		ayahText: 'فَقَرَّبَهٗٓ اِلَيْهِمْۚ قَالَ اَلَا تَأْكُلُوْنَ ',
		ayahNumber: 27,
		translationId: 'lalu dihidangkannya kepada mereka (tetapi mereka tidak mau makan). Ibrahim berkata, “Mengapa tidak kamu makan.”',
	),
	Ayah(
		ayahId: 4703,
		ayahText: 'فَاَوْجَسَ مِنْهُمْ خِيْفَةً  ۗقَالُوْا لَا تَخَفْۗ وَبَشَّرُوْهُ بِغُلٰمٍ عَلِيْمٍ ',
		ayahNumber: 28,
		translationId: 'Maka dia (Ibrahim) merasa takut terhadap mereka. Mereka berkata, “Janganlah kamu takut,” dan mereka memberi kabar gembira kepadanya dengan (kelahiran) seorang anak yang alim (Ishak). ',
	),
	Ayah(
		ayahId: 4704,
		ayahText: 'فَاَقْبَلَتِ امْرَاَتُهٗ فِيْ صَرَّةٍ فَصَكَّتْ وَجْهَهَا وَقَالَتْ عَجُوْزٌ عَقِيْمٌ ',
		ayahNumber: 29,
		translationId: 'Kemudian istrinya datang memekik (tercengang) lalu menepuk wajahnya sendiri seraya berkata, “(Aku ini) seorang perempuan tua yang mandul.” ',
	),
	Ayah(
		ayahId: 4705,
		ayahText: 'قَالُوْا كَذٰلِكِۙ قَالَ رَبُّكِ ۗاِنَّهٗ هُوَ الْحَكِيْمُ الْعَلِيْمُ  ۔',
		ayahNumber: 30,
		translationId: 'Mereka berkata, “Demikianlah Tuhanmu berfirman. Sungguh, Dialah Yang Mahabijaksana, Maha Mengetahui.”',
	),
	Ayah(
		ayahId: 4706,
		ayahText: 'قَالَ فَمَا خَطْبُكُمْ اَيُّهَا الْمُرْسَلُوْنَۚ  ',
		ayahNumber: 31,
		translationId: 'Dia (Ibrahim) berkata, “Apakah urusanmu yang penting wahai para utusan?”',
	),
	Ayah(
		ayahId: 4707,
		ayahText: 'قَالُوْٓ اِنَّآ اُرْسِلْنَآ اِلٰى قَوْمٍ مُّجْرِمِيْنَۙ ',
		ayahNumber: 32,
		translationId: 'Mereka menjawab, “Sesungguhnya kami diutus kepada kaum yang berdosa (kaum Lut),',
	),
	Ayah(
		ayahId: 4708,
		ayahText: 'لِنُرْسِلَ عَلَيْهِمْ حِجَارَةً مِّنْ طِيْنٍۙ',
		ayahNumber: 33,
		translationId: 'agar Kami menimpa mereka dengan batu-batu dari tanah (yang keras),',
	),
	Ayah(
		ayahId: 4709,
		ayahText: 'مُّسَوَّمَةً عِنْدَ رَبِّكَ لِلْمُسْرِفِيْنَ ',
		ayahNumber: 34,
		translationId: 'yang ditandai dari Tuhanmu untuk (membinasakan) orang-orang yang melampaui batas.”',
	),
	Ayah(
		ayahId: 4710,
		ayahText: 'فَاَخْرَجْنَا مَنْ كَانَ فِيْهَا مِنَ الْمُؤْمِنِيْنَۚ ',
		ayahNumber: 35,
		translationId: 'Lalu Kami keluarkan orang-orang yang beriman yang berada di dalamnya (negeri kaum Lut) itu.',
	),
	Ayah(
		ayahId: 4711,
		ayahText: 'فَمَا وَجَدْنَا فِيْهَا غَيْرَ بَيْتٍ مِّنَ الْمُسْلِمِيْنَۚ  ',
		ayahNumber: 36,
		translationId: 'Maka Kami tidak mendapati di dalamnya (negeri itu), kecuali sebuah rumah dari orang-orang Muslim (Lut).',
	),
	Ayah(
		ayahId: 4712,
		ayahText: 'وَتَرَكْنَا فِيْهَآ اٰيَةً لِّلَّذِيْنَ يَخَافُوْنَ الْعَذَابَ الْاَلِيْمَۗ ',
		ayahNumber: 37,
		translationId: 'Dan Kami tinggalkan padanya (negeri itu) suatu tanda bagi orang-orang yang takut kepada azab yang pedih.',
	),
	Ayah(
		ayahId: 4713,
		ayahText: 'وَفِيْ مُوْسٰىٓ اِذْ اَرْسَلْنٰهُ اِلٰى فِرْعَوْنَ بِسُلْطٰنٍ مُّبِيْنٍ ',
		ayahNumber: 38,
		translationId: 'Dan pada Musa (terdapat tanda-tanda kekuasaan Allah) ketika Kami mengutusnya kepada Fir‘aun dengan membawa mukjizat yang nyata. ',
	),
	Ayah(
		ayahId: 4714,
		ayahText: 'فَتَوَلّٰى بِرُكْنِهٖ وَقَالَ سٰحِرٌ اَوْ مَجْنُوْنٌ',
		ayahNumber: 39,
		translationId: 'Tetapi dia (Fir‘aun) bersama bala tentaranya berpaling dan berkata, “Dia adalah seorang pesihir atau orang gila.” ',
	),
	Ayah(
		ayahId: 4715,
		ayahText: 'فَاَخَذْنٰهُ وَجُنُوْدَهٗ فَنَبَذْنٰهُمْ فِى الْيَمِّ وَهُوَ مُلِيْمٌۗ  ',
		ayahNumber: 40,
		translationId: 'Maka Kami siksa dia beserta bala tentaranya, lalu Kami lemparkan mereka ke dalam laut, dalam keadaan tercela. ',
	),
	Ayah(
		ayahId: 4716,
		ayahText: 'وَفِيْ عَادٍ اِذْ اَرْسَلْنَا عَلَيْهِمُ الرِّيْحَ الْعَقِيْمَۚ  ',
		ayahNumber: 41,
		translationId: 'Dan (juga) pada (kisah kaum) ‘Ad, ketika Kami kirimkan kepada mereka angin yang membinasakan,',
	),
	Ayah(
		ayahId: 4717,
		ayahText: 'مَا تَذَرُ مِنْ شَيْءٍ اَتَتْ عَلَيْهِ اِلَّا جَعَلَتْهُ كَالرَّمِيْمِۗ ',
		ayahNumber: 42,
		translationId: '(angin itu) tidak membiarkan suatu apa pun yang dilandanya, bahkan dijadikannya seperti serbuk.',
	),
	Ayah(
		ayahId: 4718,
		ayahText: 'وَفِيْ ثَمُوْدَ اِذْ قِيْلَ لَهُمْ تَمَتَّعُوْا حَتّٰى حِيْنٍ ',
		ayahNumber: 43,
		translationId: 'Dan pada (kisah kaum) Samud, ketika dikatakan kepada mereka, “Bersenang-senanglah kamu sampai waktu yang ditentukan.” ',
	),
	Ayah(
		ayahId: 4719,
		ayahText: 'فَعَتَوْا عَنْ اَمْرِ رَبِّهِمْ فَاَخَذَتْهُمُ الصّٰعِقَةُ وَهُمْ يَنْظُرُوْنَ',
		ayahNumber: 44,
		translationId: 'Lalu mereka berlaku angkuh terhadap perintah Tuhannya, maka mereka disambar petir sedang mereka melihatnya.',
	),
	Ayah(
		ayahId: 4720,
		ayahText: 'فَمَا اسْتَطَاعُوْا مِنْ قِيَامٍ وَّمَا كَانُوْا مُنْتَصِرِيْنَۙ ',
		ayahNumber: 45,
		translationId: 'Maka mereka tidak mampu bangun dan juga tidak mendapat pertolongan,',
	),
	Ayah(
		ayahId: 4721,
		ayahText: 'وَقَوْمَ نُوْحٍ مِّنْ قَبْلُ ۗ اِنَّهُمْ كَانُوْا قَوْمًا فٰسِقِيْنَ ࣖ ',
		ayahNumber: 46,
		translationId: 'dan sebelum itu (telah Kami binasakan) kaum Nuh. Sungguh, mereka adalah kaum yang fasik. ',
	),
	Ayah(
		ayahId: 4722,
		ayahText: 'وَالسَّمَاۤءَ بَنَيْنٰهَا بِاَيْىدٍ وَّاِنَّا لَمُوْسِعُوْنَ',
		ayahNumber: 47,
		translationId: 'Dan langit Kami bangun dengan kekuasaan (Kami), dan Kami benar-benar meluaskannya.',
	),
	Ayah(
		ayahId: 4723,
		ayahText: 'وَالْاَرْضَ فَرَشْنٰهَا فَنِعْمَ الْمَاهِدُوْنَ',
		ayahNumber: 48,
		translationId: 'Dan bumi Kami hamparkan; maka (Kami) sebaik-baik yang telah menghamparkan. ',
	),
	Ayah(
		ayahId: 4724,
		ayahText: 'وَمِنْ كُلِّ شَيْءٍ خَلَقْنَا زَوْجَيْنِ لَعَلَّكُمْ تَذَكَّرُوْنَ',
		ayahNumber: 49,
		translationId: 'Dan segala sesuatu Kami ciptakan berpasang-pasangan agar kamu mengingat (kebesaran Allah). ',
	),
	Ayah(
		ayahId: 4725,
		ayahText: 'فَفِرُّوْٓا اِلَى اللّٰهِ ۗاِنِّيْ لَكُمْ مِّنْهُ نَذِيْرٌ مُّبِيْنٌۚ  ',
		ayahNumber: 50,
		translationId: 'Maka segeralah kembali kepada (menaati) Allah. Sungguh, aku seorang pemberi peringatan yang jelas dari Allah untukmu. ',
	),
	Ayah(
		ayahId: 4726,
		ayahText: 'وَلَا تَجْعَلُوْا مَعَ اللّٰهِ اِلٰهًا اٰخَرَۗ اِنِّيْ لَكُمْ مِّنْهُ نَذِيْرٌ مُّبِيْنٌ',
		ayahNumber: 51,
		translationId: 'Dan janganlah kamu mengadakan tuhan yang lain selain Allah. Sungguh, aku seorang pemberi peringatan yang jelas dari Allah untukmu. ',
	),
	Ayah(
		ayahId: 4727,
		ayahText: 'كَذٰلِكَ مَآ اَتَى الَّذِيْنَ مِنْ قَبْلِهِمْ مِّنْ رَّسُوْلٍ اِلَّا قَالُوْا سَاحِرٌ اَوْ مَجْنُوْنٌ',
		ayahNumber: 52,
		translationId: 'Demikianlah setiap kali seorang Rasul yang datang kepada orang-orang yang sebelum mereka, mereka (kaumnya) pasti mengatakan, “Dia itu pesihir atau orang gila.” ',
	),
	Ayah(
		ayahId: 4728,
		ayahText: 'اَتَوَاصَوْا بِهٖۚ بَلْ هُمْ قَوْمٌ طَاغُوْنَۚ ',
		ayahNumber: 53,
		translationId: 'Apakah mereka saling berpesan tentang apa yang dikatakan itu. Sebenarnya mereka adalah kaum yang melampaui batas. ',
	),
	Ayah(
		ayahId: 4729,
		ayahText: 'فَتَوَلَّ عَنْهُمْ فَمَآ اَنْتَ بِمَلُوْمٍ  ',
		ayahNumber: 54,
		translationId: 'Maka berpalinglah engkau dari mereka, dan engkau sama sekali tidak tercela. ',
	),
	Ayah(
		ayahId: 4730,
		ayahText: 'وَذَكِّرْ فَاِنَّ الذِّكْرٰى تَنْفَعُ الْمُؤْمِنِيْنَ ',
		ayahNumber: 55,
		translationId: 'Dan tetaplah memberi peringatan, karena sesungguhnya peringatan itu bermanfaat bagi orang-orang mukmin. ',
	),
	Ayah(
		ayahId: 4731,
		ayahText: 'وَمَا خَلَقْتُ الْجِنَّ وَالْاِنْسَ اِلَّا لِيَعْبُدُوْنِ',
		ayahNumber: 56,
		translationId: 'Aku tidak menciptakan jin dan manusia melainkan agar mereka beribadah kepada-Ku. ',
	),
	Ayah(
		ayahId: 4732,
		ayahText: 'مَآ اُرِيْدُ مِنْهُمْ مِّنْ رِّزْقٍ وَّمَآ اُرِيْدُ اَنْ يُّطْعِمُوْنِ ',
		ayahNumber: 57,
		translationId: 'Aku tidak menghendaki rezeki sedikit pun dari mereka dan Aku tidak menghendaki agar mereka memberi makan kepada-Ku.',
	),
	Ayah(
		ayahId: 4733,
		ayahText: 'اِنَّ اللّٰهَ هُوَ الرَّزَّاقُ ذُو الْقُوَّةِ الْمَتِيْنُ ',
		ayahNumber: 58,
		translationId: 'Sungguh Allah, Dialah Pemberi rezeki Yang Mempunyai Kekuatan lagi Sangat Kokoh.',
	),
	Ayah(
		ayahId: 4734,
		ayahText: 'فَاِنَّ لِلَّذِيْنَ ظَلَمُوْا ذَنُوْبًا مِّثْلَ ذَنُوْبِ اَصْحٰبِهِمْ فَلَا يَسْتَعْجِلُوْنِ',
		ayahNumber: 59,
		translationId: 'Maka sungguh, untuk orang-orang yang zalim ada bagian (azab) seperti bagian teman-teman mereka (dahulu); maka janganlah mereka meminta kepada-Ku untuk menyegerakannya. ',
	),
	Ayah(
		ayahId: 4735,
		ayahText: 'فَوَيْلٌ لِّلَّذِيْنَ كَفَرُوْا مِنْ يَّوْمِهِمُ الَّذِيْ يُوْعَدُوْنَ ࣖ ',
		ayahNumber: 60,
		translationId: 'Maka celakalah orang-orang yang kafir pada hari yang telah dijanjikan kepada mereka (hari Kiamat).',
	),
];
