// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah74 = [
	Ayah(
		ayahId: 5496,
		ayahText: 'يٰٓاَيُّهَا الْمُدَّثِّرُۙ',
		ayahNumber: 1,
		translationId: 'Wahai orang yang berkemul (berselimut)!',
	),
	Ayah(
		ayahId: 5497,
		ayahText: 'قُمْ فَاَنْذِرْۖ',
		ayahNumber: 2,
		translationId: 'bangunlah, lalu berilah peringatan!',
	),
	Ayah(
		ayahId: 5498,
		ayahText: 'وَرَبَّكَ فَكَبِّرْۖ',
		ayahNumber: 3,
		translationId: 'dan agungkanlah Tuhanmu,',
	),
	Ayah(
		ayahId: 5499,
		ayahText: 'وَثِيَابَكَ فَطَهِّرْۖ',
		ayahNumber: 4,
		translationId: 'dan bersihkanlah pakaianmu,',
	),
	Ayah(
		ayahId: 5500,
		ayahText: 'وَالرُّجْزَ فَاهْجُرْۖ ',
		ayahNumber: 5,
		translationId: 'dan tinggalkanlah segala (perbuatan) yang keji,',
	),
	Ayah(
		ayahId: 5501,
		ayahText: 'وَلَا تَمْنُنْ تَسْتَكْثِرُۖ ',
		ayahNumber: 6,
		translationId: 'dan janganlah engkau (Muhammad) memberi (dengan maksud) memperoleh (balasan) yang lebih banyak.',
	),
	Ayah(
		ayahId: 5502,
		ayahText: 'وَلِرَبِّكَ فَاصْبِرْۗ ',
		ayahNumber: 7,
		translationId: 'Dan karena Tuhanmu, bersabarlah.',
	),
	Ayah(
		ayahId: 5503,
		ayahText: 'فَاِذَا نُقِرَ فِى النَّاقُوْرِۙ ',
		ayahNumber: 8,
		translationId: 'Maka apabila sangkakala ditiup,',
	),
	Ayah(
		ayahId: 5504,
		ayahText: 'فَذٰلِكَ يَوْمَىِٕذٍ يَّوْمٌ عَسِيْرٌۙ ',
		ayahNumber: 9,
		translationId: 'maka itulah hari yang serba sulit,',
	),
	Ayah(
		ayahId: 5505,
		ayahText: 'عَلَى الْكٰفِرِيْنَ غَيْرُ يَسِيْرٍ ',
		ayahNumber: 10,
		translationId: 'bagi orang-orang kafir tidak mudah.',
	),
	Ayah(
		ayahId: 5506,
		ayahText: 'ذَرْنِيْ وَمَنْ خَلَقْتُ وَحِيْدًاۙ ',
		ayahNumber: 11,
		translationId: 'Biarkanlah Aku (yang bertindak) terhadap orang yang Aku sendiri telah menciptakannya,',
	),
	Ayah(
		ayahId: 5507,
		ayahText: 'وَّجَعَلْتُ لَهٗ مَالًا مَّمْدُوْدًاۙ ',
		ayahNumber: 12,
		translationId: 'dan Aku beri kekayaan yang melimpah,',
	),
	Ayah(
		ayahId: 5508,
		ayahText: 'وَّبَنِيْنَ شُهُوْدًاۙ ',
		ayahNumber: 13,
		translationId: 'dan anak-anak yang selalu bersamanya,',
	),
	Ayah(
		ayahId: 5509,
		ayahText: 'وَّمَهَّدْتُّ لَهٗ تَمْهِيْدًاۙ ',
		ayahNumber: 14,
		translationId: 'dan Aku beri kelapangan (hidup) seluas-luasnya.',
	),
	Ayah(
		ayahId: 5510,
		ayahText: 'ثُمَّ يَطْمَعُ اَنْ اَزِيْدَۙ    ',
		ayahNumber: 15,
		translationId: 'Kemudian dia ingin sekali agar Aku menambahnya.',
	),
	Ayah(
		ayahId: 5511,
		ayahText: 'كَلَّاۗ اِنَّهٗ كَانَ لِاٰيٰتِنَا عَنِيْدًاۗ ',
		ayahNumber: 16,
		translationId: "Tidak bisa! Sesungguhnya dia telah menentang ayat-ayat Kami (Al-Qur'an).",
	),
	Ayah(
		ayahId: 5512,
		ayahText: 'سَاُرْهِقُهٗ صَعُوْدًاۗ ',
		ayahNumber: 17,
		translationId: 'Aku akan membebaninya dengan pendakian yang memayahkan.',
	),
	Ayah(
		ayahId: 5513,
		ayahText: 'اِنَّهٗ فَكَّرَ وَقَدَّرَۙ ',
		ayahNumber: 18,
		translationId: 'Sesungguhnya dia telah memikirkan dan menetapkan (apa yang ditetapkannya),',
	),
	Ayah(
		ayahId: 5514,
		ayahText: 'فَقُتِلَ كَيْفَ قَدَّرَۙ ',
		ayahNumber: 19,
		translationId: 'maka celakalah dia! Bagaimana dia menetapkan?',
	),
	Ayah(
		ayahId: 5515,
		ayahText: 'ثُمَّ قُتِلَ كَيْفَ قَدَّرَۙ ',
		ayahNumber: 20,
		translationId: 'Sekali lagi, celakalah dia! Bagaimana dia menetapkan?',
	),
	Ayah(
		ayahId: 5516,
		ayahText: 'ثُمَّ نَظَرَۙ ',
		ayahNumber: 21,
		translationId: 'Kemudian dia (merenung) memikirkan,',
	),
	Ayah(
		ayahId: 5517,
		ayahText: 'ثُمَّ عَبَسَ وَبَسَرَۙ ',
		ayahNumber: 22,
		translationId: 'lalu berwajah masam dan cemberut,',
	),
	Ayah(
		ayahId: 5518,
		ayahText: 'ثُمَّ اَدْبَرَ وَاسْتَكْبَرَۙ ',
		ayahNumber: 23,
		translationId: 'kemudian berpaling (dari kebenaran) dan menyombongkan diri,',
	),
	Ayah(
		ayahId: 5519,
		ayahText: 'فَقَالَ اِنْ هٰذَآ اِلَّا سِحْرٌ يُّؤْثَرُۙ ',
		ayahNumber: 24,
		translationId: "lalu dia berkata, “(Al-Qur'an) ini hanyalah sihir yang dipelajari (dari orang-orang dahulu).",
	),
	Ayah(
		ayahId: 5520,
		ayahText: 'اِنْ هٰذَآ اِلَّا قَوْلُ الْبَشَرِۗ ',
		ayahNumber: 25,
		translationId: 'Ini hanyalah perkataan manusia.”',
	),
	Ayah(
		ayahId: 5521,
		ayahText: 'سَاُصْلِيْهِ سَقَرَ',
		ayahNumber: 26,
		translationId: 'Kelak, Aku akan memasukkannya ke dalam (neraka) Saqar,',
	),
	Ayah(
		ayahId: 5522,
		ayahText: 'وَمَآ اَدْرٰىكَ مَا سَقَرُۗ ',
		ayahNumber: 27,
		translationId: 'dan tahukah kamu apa (neraka) Saqar itu?',
	),
	Ayah(
		ayahId: 5523,
		ayahText: 'لَا تُبْقِيْ وَلَا تَذَرُۚ ',
		ayahNumber: 28,
		translationId: 'Ia (Saqar itu) tidak meninggalkan dan tidak membiarkan,',
	),
	Ayah(
		ayahId: 5524,
		ayahText: 'لَوَّاحَةٌ لِّلْبَشَرِۚ ',
		ayahNumber: 29,
		translationId: 'yang menghanguskan kulit manusia.',
	),
	Ayah(
		ayahId: 5525,
		ayahText: 'عَلَيْهَا تِسْعَةَ عَشَرَۗ ',
		ayahNumber: 30,
		translationId: 'Di atasnya ada sembilan belas (malaikat penjaga).',
	),
	Ayah(
		ayahId: 5526,
		ayahText: 'وَمَا جَعَلْنَآ اَصْحٰبَ النَّارِ اِلَّا مَلٰۤىِٕكَةً ۖوَّمَا جَعَلْنَا عِدَّتَهُمْ اِلَّا فِتْنَةً لِّلَّذِيْنَ كَفَرُوْاۙ لِيَسْتَيْقِنَ الَّذِيْنَ اُوْتُوا الْكِتٰبَ وَيَزْدَادَ الَّذِيْنَ اٰمَنُوْٓا اِيْمَانًا وَّلَا يَرْتَابَ الَّذِيْنَ اُوْتُوا الْكِتٰبَ وَالْمُؤْمِنُوْنَۙ وَلِيَقُوْلَ الَّذِيْنَ فِيْ قُلُوْبِهِمْ مَّرَضٌ وَّالْكٰفِرُوْنَ مَاذَآ اَرَادَ اللّٰهُ بِهٰذَا مَثَلًاۗ  كَذٰلِكَ يُضِلُّ اللّٰهُ مَنْ يَّشَاۤءُ وَيَهْدِيْ مَنْ يَّشَاۤءُۗ وَمَا يَعْلَمُ جُنُوْدَ رَبِّكَ اِلَّا هُوَۗ وَمَا هِيَ اِلَّا ذِكْرٰى لِلْبَشَرِ ࣖ',
		ayahNumber: 31,
		translationId: 'Dan yang Kami jadikan penjaga neraka itu hanya dari malaikat; dan Kami menentukan bilangan mereka itu hanya sebagai cobaan bagi orang-orang kafir, agar orang-orang yang diberi kitab menjadi yakin, agar orang yang beriman bertambah imannya, agar orang-orang yang diberi kitab dan orang-orang mukmin itu tidak ragu-ragu; dan agar orang-orang yang di dalam hatinya ada penyakit dan orang-orang kafir (berkata), “Apakah yang dikehendaki Allah dengan (bilangan) ini sebagai suatu perumpamaan?” Demikianlah Allah membiarkan sesat orang-orang yang Dia kehendaki dan memberi petunjuk kepada orang-orang yang Dia kehendaki. Dan tidak ada yang mengetahui bala tentara Tuhanmu kecuali Dia sendiri. Dan Saqar itu tidak lain hanyalah peringatan bagi manusia.',
	),
	Ayah(
		ayahId: 5527,
		ayahText: 'كَلَّا وَالْقَمَرِۙ',
		ayahNumber: 32,
		translationId: 'Tidak! Demi bulan,',
	),
	Ayah(
		ayahId: 5528,
		ayahText: 'وَالَّيْلِ اِذْ اَدْبَرَۙ',
		ayahNumber: 33,
		translationId: 'dan demi malam ketika telah berlalu,',
	),
	Ayah(
		ayahId: 5529,
		ayahText: 'وَالصُّبْحِ اِذَآ اَسْفَرَۙ',
		ayahNumber: 34,
		translationId: 'dan demi subuh apabila mulai terang, ',
	),
	Ayah(
		ayahId: 5530,
		ayahText: 'اِنَّهَا لَاِحْدَى الْكُبَرِۙ',
		ayahNumber: 35,
		translationId: 'sesunggunya (Saqar itu) adalah salah satu (bencana) yang sangat besar,',
	),
	Ayah(
		ayahId: 5531,
		ayahText: 'نَذِيْرًا لِّلْبَشَرِۙ',
		ayahNumber: 36,
		translationId: 'sebagai peringatan bagi manusia, ',
	),
	Ayah(
		ayahId: 5532,
		ayahText: 'لِمَنْ شَاۤءَ مِنْكُمْ اَنْ يَّتَقَدَّمَ اَوْ يَتَاَخَّرَۗ',
		ayahNumber: 37,
		translationId: '(yaitu) bagi siapa di antara kamu yang ingin maju atau mundur.',
	),
	Ayah(
		ayahId: 5533,
		ayahText: 'كُلُّ نَفْسٍۢ بِمَا كَسَبَتْ رَهِيْنَةٌۙ',
		ayahNumber: 38,
		translationId: 'Setiap orang bertanggung jawab atas apa yang telah dilakukannya,',
	),
	Ayah(
		ayahId: 5534,
		ayahText: 'اِلَّآ اَصْحٰبَ الْيَمِيْنِ ۛ ',
		ayahNumber: 39,
		translationId: 'kecuali golongan kanan,',
	),
	Ayah(
		ayahId: 5535,
		ayahText: 'فِيْ جَنّٰتٍ ۛ يَتَسَاۤءَلُوْنَۙ',
		ayahNumber: 40,
		translationId: 'berada di dalam surga, mereka saling menanyakan,',
	),
	Ayah(
		ayahId: 5536,
		ayahText: 'عَنِ الْمُجْرِمِيْنَۙ',
		ayahNumber: 41,
		translationId: 'tentang (keadaan) orang-orang yang berdosa, ',
	),
	Ayah(
		ayahId: 5537,
		ayahText: 'مَا سَلَكَكُمْ فِيْ سَقَرَ ',
		ayahNumber: 42,
		translationId: '”Apa yang menyebabkan kamu masuk ke dalam (neraka) Saqar?”',
	),
	Ayah(
		ayahId: 5538,
		ayahText: 'قَالُوْا لَمْ نَكُ مِنَ الْمُصَلِّيْنَۙ',
		ayahNumber: 43,
		translationId: 'Mereka menjawab, “Dahulu kami tidak termasuk orang-orang yang melaksanakan salat, ',
	),
	Ayah(
		ayahId: 5539,
		ayahText: 'وَلَمْ نَكُ نُطْعِمُ الْمِسْكِيْنَۙ',
		ayahNumber: 44,
		translationId: 'dan kami (juga) tidak memberi makan orang miskin, ',
	),
	Ayah(
		ayahId: 5540,
		ayahText: 'وَكُنَّا نَخُوْضُ مَعَ الْخَاۤىِٕضِيْنَۙ',
		ayahNumber: 45,
		translationId: 'bahkan kami biasa berbincang (untuk tujuan yang batil), bersama orang-orang yang membicarakannya, ',
	),
	Ayah(
		ayahId: 5541,
		ayahText: 'وَكُنَّا نُكَذِّبُ بِيَوْمِ الدِّيْنِۙ',
		ayahNumber: 46,
		translationId: 'dan kami mendustakan hari pembalasan, ',
	),
	Ayah(
		ayahId: 5542,
		ayahText: 'حَتّٰىٓ اَتٰىنَا الْيَقِيْنُۗ',
		ayahNumber: 47,
		translationId: 'sampai datang kepada kami kematian.” ',
	),
	Ayah(
		ayahId: 5543,
		ayahText: 'فَمَا تَنْفَعُهُمْ شَفَاعَةُ الشَّافِعِيْنَۗ',
		ayahNumber: 48,
		translationId: 'Maka tidak berguna lagi bagi mereka syafaat (pertolongan) dari orang-orang yang memberikan syafaat. ',
	),
	Ayah(
		ayahId: 5544,
		ayahText: 'فَمَا لَهُمْ عَنِ التَّذْكِرَةِ مُعْرِضِيْنَۙ',
		ayahNumber: 49,
		translationId: 'Lalu mengapa mereka (orang-orang kafir) berpaling dari peringatan (Allah)?',
	),
	Ayah(
		ayahId: 5545,
		ayahText: 'كَاَنَّهُمْ حُمُرٌ مُّسْتَنْفِرَةٌۙ',
		ayahNumber: 50,
		translationId: 'seakan-akan mereka keledai liar yang lari terkejut,',
	),
	Ayah(
		ayahId: 5546,
		ayahText: 'فَرَّتْ مِنْ قَسْوَرَةٍۗ',
		ayahNumber: 51,
		translationId: 'lari dari singa. ',
	),
	Ayah(
		ayahId: 5547,
		ayahText: 'بَلْ يُرِيْدُ كُلُّ امْرِئٍ مِّنْهُمْ اَنْ يُّؤْتٰى صُحُفًا مُّنَشَّرَةًۙ',
		ayahNumber: 52,
		translationId: 'Bahkan setiap orang dari mereka ingin agar diberikan kepadanya lembaran-lembaran (kitab) yang terbuka. ',
	),
	Ayah(
		ayahId: 5548,
		ayahText: 'كَلَّاۗ بَلْ لَّا يَخَافُوْنَ الْاٰخِرَةَۗ',
		ayahNumber: 53,
		translationId: 'Tidak! Sebenarnya mereka tidak takut kepada akhirat.',
	),
	Ayah(
		ayahId: 5549,
		ayahText: 'كَلَّآ اِنَّهٗ تَذْكِرَةٌ ۚ',
		ayahNumber: 54,
		translationId: "Tidak! Sesungguhnya (Al-Qur'an) itu benar-benar suatu peringatan. ",
	),
	Ayah(
		ayahId: 5550,
		ayahText: 'فَمَنْ شَاۤءَ ذَكَرَهٗۗ',
		ayahNumber: 55,
		translationId: 'Maka barangsiapa menghendaki, tentu dia mengambil pelajaran darinya. ',
	),
	Ayah(
		ayahId: 5551,
		ayahText: 'وَمَا يَذْكُرُوْنَ اِلَّآ اَنْ يَّشَاۤءَ اللّٰهُ ۗهُوَ اَهْلُ التَّقْوٰى وَاَهْلُ الْمَغْفِرَةِ ࣖ',
		ayahNumber: 56,
		translationId: "Dan mereka tidak akan mengambil pelajaran darinya (Al-Qur'an) kecuali (jika) Allah menghendakinya. Dialah Tuhan yang patut (kita) bertakwa kepada-Nya dan yang berhak memberi ampunan. ",
	),
];
