// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah89 = [
	Ayah(
		ayahId: 5994,
		ayahText: 'وَالْفَجْرِۙ',
		ayahNumber: 1,
		translationId: 'Demi fajar,',
	),
	Ayah(
		ayahId: 5995,
		ayahText: 'وَلَيَالٍ عَشْرٍۙ',
		ayahNumber: 2,
		translationId: 'demi malam yang sepuluh,',
	),
	Ayah(
		ayahId: 5996,
		ayahText: 'وَّالشَّفْعِ وَالْوَتْرِۙ',
		ayahNumber: 3,
		translationId: 'demi yang genap dan yang ganjil,',
	),
	Ayah(
		ayahId: 5997,
		ayahText: 'وَالَّيْلِ اِذَا يَسْرِۚ',
		ayahNumber: 4,
		translationId: 'demi malam apabila berlalu.',
	),
	Ayah(
		ayahId: 5998,
		ayahText: 'هَلْ فِيْ ذٰلِكَ قَسَمٌ لِّذِيْ حِجْرٍۗ',
		ayahNumber: 5,
		translationId: 'Adakah pada yang demikian itu terdapat sumpah (yang dapat diterima) bagi orang-orang yang berakal?',
	),
	Ayah(
		ayahId: 5999,
		ayahText: 'اَلَمْ تَرَ كَيْفَ فَعَلَ رَبُّكَ بِعَادٍۖ',
		ayahNumber: 6,
		translationId: 'Tidakkah engkau (Muhammad) memperhatikan bagaimana Tuhanmu berbuat terhadap (kaum) ‘Ad?',
	),
	Ayah(
		ayahId: 6000,
		ayahText: 'اِرَمَ ذَاتِ الْعِمَادِۖ',
		ayahNumber: 7,
		translationId: '(yaitu) penduduk Iram (ibukota kaum ‘Ad) yang mempunyai bangunan-bangunan yang tinggi,',
	),
	Ayah(
		ayahId: 6001,
		ayahText: 'الَّتِيْ لَمْ يُخْلَقْ مِثْلُهَا فِى الْبِلَادِۖ',
		ayahNumber: 8,
		translationId: 'yang belum pernah dibangun (suatu kota) seperti itu di negeri-negeri lain,',
	),
	Ayah(
		ayahId: 6002,
		ayahText: 'وَثَمُوْدَ الَّذِيْنَ جَابُوا الصَّخْرَ بِالْوَادِۖ',
		ayahNumber: 9,
		translationId: 'dan (terhadap) kaum samud yang memotong batu-batu besar di lembah,',
	),
	Ayah(
		ayahId: 6003,
		ayahText: 'وَفِرْعَوْنَ ذِى الْاَوْتَادِۖ',
		ayahNumber: 10,
		translationId: 'dan (terhadap) Fir‘aun yang mempunyai pasak-pasak (bangunan yang besar),',
	),
	Ayah(
		ayahId: 6004,
		ayahText: 'الَّذِيْنَ طَغَوْا فِى الْبِلَادِۖ',
		ayahNumber: 11,
		translationId: 'yang berbuat sewenang-wenang dalam negeri,',
	),
	Ayah(
		ayahId: 6005,
		ayahText: 'فَاَكْثَرُوْا فِيْهَا الْفَسَادَۖ',
		ayahNumber: 12,
		translationId: 'lalu mereka banyak berbuat kerusakan dalam negeri itu,',
	),
	Ayah(
		ayahId: 6006,
		ayahText: 'فَصَبَّ عَلَيْهِمْ رَبُّكَ سَوْطَ عَذَابٍۖ',
		ayahNumber: 13,
		translationId: 'karena itu Tuhanmu menimpakan cemeti azab kepada mereka,',
	),
	Ayah(
		ayahId: 6007,
		ayahText: 'اِنَّ رَبَّكَ لَبِالْمِرْصَادِۗ',
		ayahNumber: 14,
		translationId: 'sungguh, Tuhanmu benar-benar mengawasi.',
	),
	Ayah(
		ayahId: 6008,
		ayahText: 'فَاَمَّا الْاِنْسَانُ اِذَا مَا ابْتَلٰىهُ رَبُّهٗ فَاَكْرَمَهٗ وَنَعَّمَهٗۙ فَيَقُوْلُ رَبِّيْٓ اَكْرَمَنِۗ',
		ayahNumber: 15,
		translationId: 'Maka adapun manusia, apabila Tuhan mengujinya lalu memuliakannya dan memberinya kesenangan, maka dia berkata, “Tuhanku telah memuliakanku.”',
	),
	Ayah(
		ayahId: 6009,
		ayahText: 'وَاَمَّآ اِذَا مَا ابْتَلٰىهُ فَقَدَرَ عَلَيْهِ رِزْقَهٗ ەۙ فَيَقُوْلُ رَبِّيْٓ اَهَانَنِۚ',
		ayahNumber: 16,
		translationId: 'Namun apabila Tuhan mengujinya lalu membatasi rezekinya, maka dia berkata, “Tuhanku telah menghinaku.”',
	),
	Ayah(
		ayahId: 6010,
		ayahText: 'كَلَّا بَلْ لَّا تُكْرِمُوْنَ الْيَتِيْمَۙ',
		ayahNumber: 17,
		translationId: 'Sekali-kali tidak! Bahkan kamu tidak memuliakan anak yatim,',
	),
	Ayah(
		ayahId: 6011,
		ayahText: 'وَلَا تَحٰۤضُّوْنَ عَلٰى طَعَامِ الْمِسْكِيْنِۙ',
		ayahNumber: 18,
		translationId: 'dan kamu tidak saling mengajak memberi makan orang miskin,',
	),
	Ayah(
		ayahId: 6012,
		ayahText: 'وَتَأْكُلُوْنَ التُّرَاثَ اَكْلًا لَّمًّاۙ',
		ayahNumber: 19,
		translationId: 'sedangkan kamu memakan harta warisan dengan cara mencampurbaurkan (yang halal dan yang haram),',
	),
	Ayah(
		ayahId: 6013,
		ayahText: 'وَّتُحِبُّوْنَ الْمَالَ حُبًّا جَمًّاۗ',
		ayahNumber: 20,
		translationId: 'dan kamu mencintai harta dengan kecintaan yang berlebihan.',
	),
	Ayah(
		ayahId: 6014,
		ayahText: 'كَلَّآ اِذَا دُكَّتِ الْاَرْضُ دَكًّا دَكًّاۙ',
		ayahNumber: 21,
		translationId: 'Sekali-kali tidak! Apabila bumi diguncangkan berturut-turut (berbenturan),',
	),
	Ayah(
		ayahId: 6015,
		ayahText: 'وَّجَآءَ رَبُّكَ وَالْمَلَكُ صَفًّا صَفًّاۚ',
		ayahNumber: 22,
		translationId: 'dan datanglah Tuhanmu; dan malaikat berbaris-baris,',
	),
	Ayah(
		ayahId: 6016,
		ayahText: 'وَجِايْۤءَ يَوْمَىِٕذٍۢ بِجَهَنَّمَۙ يَوْمَىِٕذٍ يَّتَذَكَّرُ الْاِنْسَانُ وَاَنّٰى لَهُ الذِّكْرٰىۗ',
		ayahNumber: 23,
		translationId: 'dan pada hari itu diperlihatkan neraka Jahanam; pada hari itu sadarlah manusia, tetapi tidak berguna lagi baginya kesadaran itu.',
	),
	Ayah(
		ayahId: 6017,
		ayahText: 'يَقُوْلُ يٰلَيْتَنِيْ قَدَّمْتُ لِحَيَاتِيْۚ',
		ayahNumber: 24,
		translationId: 'Dia berkata, “Alangkah baiknya sekiranya dahulu aku mengerjakan (kebajikan) untuk hidupku ini.”',
	),
	Ayah(
		ayahId: 6018,
		ayahText: 'فَيَوْمَىِٕذٍ لَّا يُعَذِّبُ عَذَابَهٗٓ اَحَدٌ ۙ',
		ayahNumber: 25,
		translationId: 'Maka pada hari itu tidak ada seorang pun yang mengazab seperti azab-Nya (yang adil),',
	),
	Ayah(
		ayahId: 6019,
		ayahText: 'وَّلَا يُوْثِقُ وَثَاقَهٗٓ اَحَدٌ ۗ',
		ayahNumber: 26,
		translationId: 'dan tidak ada seorang pun yang mengikat seperti ikatan-Nya.',
	),
	Ayah(
		ayahId: 6020,
		ayahText: 'يٰٓاَيَّتُهَا النَّفْسُ الْمُطْمَىِٕنَّةُۙ',
		ayahNumber: 27,
		translationId: 'Wahai jiwa yang tenang!',
	),
	Ayah(
		ayahId: 6021,
		ayahText: 'ارْجِعِيْٓ اِلٰى رَبِّكِ رَاضِيَةً مَّرْضِيَّةً ۚ',
		ayahNumber: 28,
		translationId: 'Kembalilah kepada Tuhanmu dengan hati yang rida dan diridai-Nya.',
	),
	Ayah(
		ayahId: 6022,
		ayahText: 'فَادْخُلِيْ فِيْ عِبٰدِيْۙ',
		ayahNumber: 29,
		translationId: 'Maka masuklah ke dalam golongan hamba-hamba-Ku,',
	),
	Ayah(
		ayahId: 6023,
		ayahText: 'وَادْخُلِيْ جَنَّتِيْ ࣖࣖ',
		ayahNumber: 30,
		translationId: 'dan masuklah ke dalam surga-Ku.',
	),
];
