// ignore_for_file: lines_longer_than_80_chars
import 'package:murojaah_web/app/model/ayah.dart';

const surah83 = [
	Ayah(
		ayahId: 5849,
		ayahText: 'وَيْلٌ لِّلْمُطَفِّفِيْنَۙ',
		ayahNumber: 1,
		translationId: 'Celakalah bagi orang-orang yang curang (dalam menakar dan menimbang)! ',
	),
	Ayah(
		ayahId: 5850,
		ayahText: 'الَّذِيْنَ اِذَا اكْتَالُوْا عَلَى النَّاسِ يَسْتَوْفُوْنَۖ',
		ayahNumber: 2,
		translationId: '(Yaitu) orang-orang yang apabila menerima takaran dari orang lain mereka minta dicukupkan, ',
	),
	Ayah(
		ayahId: 5851,
		ayahText: 'وَاِذَا كَالُوْهُمْ اَوْ وَّزَنُوْهُمْ يُخْسِرُوْنَۗ',
		ayahNumber: 3,
		translationId: 'dan apabila mereka menakar atau menimbang (untuk orang lain), mereka mengurangi. ',
	),
	Ayah(
		ayahId: 5852,
		ayahText: 'اَلَا يَظُنُّ اُولٰۤىِٕكَ اَنَّهُمْ مَّبْعُوْثُوْنَۙ',
		ayahNumber: 4,
		translationId: 'Tidakkah mereka itu mengira, bahwa sesungguhnya mereka akan dibangkitkan, ',
	),
	Ayah(
		ayahId: 5853,
		ayahText: 'لِيَوْمٍ عَظِيْمٍۙ',
		ayahNumber: 5,
		translationId: 'pada suatu hari yang besar, ',
	),
	Ayah(
		ayahId: 5854,
		ayahText: 'يَّوْمَ يَقُوْمُ النَّاسُ لِرَبِّ الْعٰلَمِيْنَۗ',
		ayahNumber: 6,
		translationId: '(yaitu) pada hari (ketika) semua orang bangkit menghadap Tuhan seluruh alam.',
	),
	Ayah(
		ayahId: 5855,
		ayahText: 'كَلَّآ اِنَّ كِتٰبَ الْفُجَّارِ لَفِيْ سِجِّيْنٍۗ',
		ayahNumber: 7,
		translationId: 'Sekali-kali jangan begitu! Sesungguhnya catatan orang yang durhaka benar-benar tersimpan dalam Sijjin. ',
	),
	Ayah(
		ayahId: 5856,
		ayahText: 'وَمَآ اَدْرٰىكَ مَا سِجِّيْنٌۗ',
		ayahNumber: 8,
		translationId: 'Dan tahukah engkau apakah Sijjin itu? ',
	),
	Ayah(
		ayahId: 5857,
		ayahText: 'كِتٰبٌ مَّرْقُوْمٌۗ',
		ayahNumber: 9,
		translationId: '(Yaitu) Kitab yang berisi catatan (amal).',
	),
	Ayah(
		ayahId: 5858,
		ayahText: 'وَيْلٌ يَّوْمَىِٕذٍ لِّلْمُكَذِّبِيْنَۙ',
		ayahNumber: 10,
		translationId: 'Celakalah pada hari itu, bagi orang-orang yang mendustakan! ',
	),
	Ayah(
		ayahId: 5859,
		ayahText: 'الَّذِيْنَ يُكَذِّبُوْنَ بِيَوْمِ الدِّيْنِۗ',
		ayahNumber: 11,
		translationId: '(yaitu) orang-orang yang mendustakannya (hari pembalasan).',
	),
	Ayah(
		ayahId: 5860,
		ayahText: 'وَمَا يُكَذِّبُ بِهٖٓ اِلَّا كُلُّ مُعْتَدٍ اَثِيْمٍۙ',
		ayahNumber: 12,
		translationId: 'Dan tidak ada yang mendustakannya (hari pembalasan) kecuali setiap orang yang melampaui batas dan berdosa,',
	),
	Ayah(
		ayahId: 5861,
		ayahText: 'اِذَا تُتْلٰى عَلَيْهِ اٰيٰتُنَا قَالَ اَسَاطِيْرُ الْاَوَّلِيْنَۗ',
		ayahNumber: 13,
		translationId: 'yang apabila dibacakan kepadanya ayat-ayat Kami, dia berkata, “Itu adalah dongeng orang-orang dahulu.” ',
	),
	Ayah(
		ayahId: 5862,
		ayahText: 'كَلَّا بَلْ ۜرَانَ عَلٰى قُلُوْبِهِمْ مَّا كَانُوْا يَكْسِبُوْنَ ',
		ayahNumber: 14,
		translationId: 'Sekali-kali tidak! Bahkan apa yang mereka kerjakan itu telah menutupi hati mereka. ',
	),
	Ayah(
		ayahId: 5863,
		ayahText: 'كَلَّآ اِنَّهُمْ عَنْ رَّبِّهِمْ يَوْمَىِٕذٍ لَّمَحْجُوْبُوْنَۗ',
		ayahNumber: 15,
		translationId: 'Sekali-kali tidak! Sesungguhnya mereka pada hari itu benar-benar terhalang dari (melihat) Tuhannya. ',
	),
	Ayah(
		ayahId: 5864,
		ayahText: 'ثُمَّ اِنَّهُمْ لَصَالُوا الْجَحِيْمِۗ',
		ayahNumber: 16,
		translationId: 'Kemudian, sesungguhnya mereka benar-benar masuk neraka. ',
	),
	Ayah(
		ayahId: 5865,
		ayahText: 'ثُمَّ يُقَالُ هٰذَا الَّذِيْ كُنْتُمْ بِهٖ تُكَذِّبُوْنَۗ',
		ayahNumber: 17,
		translationId: 'Kemudian, dikatakan (kepada mereka), “Inilah (azab) yang dahulu kamu dustakan.”',
	),
	Ayah(
		ayahId: 5866,
		ayahText: 'كَلَّآ اِنَّ كِتٰبَ الْاَبْرَارِ لَفِيْ عِلِّيِّيْنَۗ ',
		ayahNumber: 18,
		translationId: 'Sekali-kali tidak! Sesungguhnya catatan orang-orang yang berbakti benar-benar tersimpan dalam ’Illiyyin. ',
	),
	Ayah(
		ayahId: 5867,
		ayahText: 'وَمَآ اَدْرٰىكَ مَا عِلِّيُّوْنَۗ',
		ayahNumber: 19,
		translationId: 'Dan tahukah engkau apakah ’Illiyyin itu?',
	),
	Ayah(
		ayahId: 5868,
		ayahText: 'كِتٰبٌ مَّرْقُوْمٌۙ',
		ayahNumber: 20,
		translationId: '(Yaitu) Kitab yang berisi catatan (amal),',
	),
	Ayah(
		ayahId: 5869,
		ayahText: 'يَّشْهَدُهُ الْمُقَرَّبُوْنَۗ',
		ayahNumber: 21,
		translationId: 'yang disaksikan oleh (malaikat-malaikat) yang didekatkan (kepada Allah). ',
	),
	Ayah(
		ayahId: 5870,
		ayahText: 'اِنَّ الْاَبْرَارَ لَفِيْ نَعِيْمٍۙ',
		ayahNumber: 22,
		translationId: 'Sesungguhnya orang-orang yang berbakti benar-benar berada dalam (surga yang penuh) kenikmatan,',
	),
	Ayah(
		ayahId: 5871,
		ayahText: 'عَلَى الْاَرَاۤىِٕكِ يَنْظُرُوْنَۙ',
		ayahNumber: 23,
		translationId: 'mereka (duduk) di atas dipan-dipan melepas pandangan. ',
	),
	Ayah(
		ayahId: 5872,
		ayahText: 'تَعْرِفُ فِيْ وُجُوْهِهِمْ نَضْرَةَ النَّعِيْمِۚ',
		ayahNumber: 24,
		translationId: 'Kamu dapat mengetahui dari wajah mereka kesenangan hidup yang penuh kenikmatan.',
	),
	Ayah(
		ayahId: 5873,
		ayahText: 'يُسْقَوْنَ مِنْ رَّحِيْقٍ مَّخْتُوْمٍۙ',
		ayahNumber: 25,
		translationId: 'Mereka diberi minum dari khamar murni (tidak memabukkan) yang (tempatnya) masih dilak (disegel), ',
	),
	Ayah(
		ayahId: 5874,
		ayahText: 'خِتٰمُهٗ مِسْكٌ ۗوَفِيْ ذٰلِكَ فَلْيَتَنَافَسِ الْمُتَنَافِسُوْنَۗ',
		ayahNumber: 26,
		translationId: 'laknya dari kasturi. Dan untuk yang demikian itu hendaknya orang berlomba-lomba. ',
	),
	Ayah(
		ayahId: 5875,
		ayahText: 'وَمِزَاجُهٗ مِنْ تَسْنِيْمٍۙ',
		ayahNumber: 27,
		translationId: 'Dan campurannya dari tasnim, ',
	),
	Ayah(
		ayahId: 5876,
		ayahText: 'عَيْنًا يَّشْرَبُ بِهَا الْمُقَرَّبُوْنَۗ',
		ayahNumber: 28,
		translationId: '(yaitu) mata air yang diminum oleh mereka yang dekat (kepada Allah). ',
	),
	Ayah(
		ayahId: 5877,
		ayahText: 'اِنَّ الَّذِيْنَ اَجْرَمُوْا كَانُوْا مِنَ الَّذِيْنَ اٰمَنُوْا يَضْحَكُوْنَۖ',
		ayahNumber: 29,
		translationId: 'Sesungguhnya orang-orang yang berdosa adalah mereka yang dahulu menertawakan orang-orang yang beriman.',
	),
	Ayah(
		ayahId: 5878,
		ayahText: 'وَاِذَا مَرُّوْا بِهِمْ يَتَغَامَزُوْنَۖ',
		ayahNumber: 30,
		translationId: 'Dan apabila mereka (orang-orang yang beriman) melintas di hadapan mereka, mereka saling mengedip-ngedipkan matanya,',
	),
	Ayah(
		ayahId: 5879,
		ayahText: 'وَاِذَا انْقَلَبُوْٓا اِلٰٓى اَهْلِهِمُ انْقَلَبُوْا فَكِهِيْنَۖ',
		ayahNumber: 31,
		translationId: 'dan apabila kembali kepada kaumnya, mereka kembali dengan gembira ria. ',
	),
	Ayah(
		ayahId: 5880,
		ayahText: 'وَاِذَا رَاَوْهُمْ قَالُوْٓا اِنَّ هٰٓؤُلَاۤءِ لَضَاۤلُّوْنَۙ',
		ayahNumber: 32,
		translationId: 'Dan apabila mereka melihat (orang-orang mukmin), mereka mengatakan, “Sesungguhnya mereka benar-benar orang-orang sesat,”',
	),
	Ayah(
		ayahId: 5881,
		ayahText: 'وَمَآ اُرْسِلُوْا عَلَيْهِمْ حٰفِظِيْنَۗ',
		ayahNumber: 33,
		translationId: 'padahal (orang-orang yang berdosa itu), mereka tidak diutus sebagai penjaga (orang-orang mukmin). ',
	),
	Ayah(
		ayahId: 5882,
		ayahText: 'فَالْيَوْمَ الَّذِيْنَ اٰمَنُوْا مِنَ الْكُفَّارِ يَضْحَكُوْنَۙ',
		ayahNumber: 34,
		translationId: 'Maka pada hari ini, orang-orang yang beriman yang menertawakan orang-orang kafir, ',
	),
	Ayah(
		ayahId: 5883,
		ayahText: 'عَلَى الْاَرَاۤىِٕكِ يَنْظُرُوْنَۗ',
		ayahNumber: 35,
		translationId: 'mereka (duduk) di atas dipan-dipan melepas pandangan.',
	),
	Ayah(
		ayahId: 5884,
		ayahText: 'هَلْ ثُوِّبَ الْكُفَّارُ مَا كَانُوْا يَفْعَلُوْنَ ࣖ',
		ayahNumber: 36,
		translationId: 'Apakah orang-orang kafir itu diberi balasan (hukuman) terhadap apa yang telah mereka perbuat? ',
	),
];
